### ISSUE TITLE
[Frontend] Communicate about the fees charges during checkout and managing lock 

### ISSUE THREAD

**Issue by ChialiTsai** [unlock-protocol/unlock#10011]
To clearly communicate to the members during the checkout, suggest adding a message and fee breakdown on the checkout UI,
2 screens/area to help communicate.
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/16527634/197607782-1d037ef9-b421-47e3-baa2-da7a58ecc904.png">

To inform creators about the fee charges to their members, suggest adding a message in the connect credit card payment UI 
There is 3 states of the connect credit card payment, please copy the message from design or suggest better writing.
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/16527634/197608124-63d2877c-1448-480b-8f05-ad5d8b2fd949.png">

Figma: https://www.figma.com/file/pNN7ER1F4mdToFfk1bB0gu?node-id=2417:66157#292117934

**Comment by julien51** [comment]
@ChialiTsai Thanks a lot!
@searchableguy When showing the fees, only show the $ amount (the crypto price is irrelevant)..
