### ISSUE TITLE
Verifier Camera Not Loading

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10038]
**Describe the bug**

**To Reproduce**
1. Scan a QR code from any Key with an iPhone 12's native 

**Expected behavior**
Verifier app should allow for a picture to be taken

**Screenshots**
Attached
![IMG_1923](https://user-images.githubusercontent.com/32484647/197870817-00da58b8-b6ec-4796-8986-b5a2a797e658.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS16
 - Browser: Chrome

**Comment by julien51** [comment]
@searchableguy is this related to that? https://github.com/unlock-protocol/unlock/pull/10033

**Comment by searchableguy** [comment]
Yes.

**Comment by searchableguy** [comment]
Yes.
