### ISSUE TITLE
Unexpected error on keychain

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10046]
I am seeing an "unexpected error" on the keychain:
<img width="1727" alt="Screen Shot 2022-10-25 at 9 36 59 PM" src="https://user-images.githubusercontent.com/17735/197914045-d420b971-5040-4e11-bbd8-67e25211f62f.png">

**Comment by kalidiagne** [comment]
related to https://github.com/unlock-protocol/unlock/issues/10163
