### ISSUE TITLE
Broken checkout on mobile wallets

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10045]
One of the difficult things about several mobile wallets like MetaMask and others is that they don't inject the provider in iframes (only on the main window/frame).
That is the reason why the paywall app has a "proxy" provider. that basically passes RPC calls from the main frame to the iframe.
It appears that this is not working right now.

You can try from our home page or a demo page with mobile MetaMask and/or Coinbase's wallet application.

**Comment by searchableguy** [comment]
It is working for me. I use wallet connect and it connects the account properly.  Can you record a clip?
