### ISSUE TITLE
Inconsistent messaging in automated 'A key was added to your wallet' email

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10057]
**Is your feature request related to a problem? Please describe.**
When email is captured in checkout or added during an airdrop, an automated email is sent. The copy in this email should align with messaging in Checkout. 

**Describe the solution you'd like**
The word 'key' is not referenced in Checkout. 

The subject line 'A key was added to your wallet' may confuse users who don't know what a 'key' is. Revise subject line to 'A membership was added to your wallet'

'A new NFT in your wallet!' should be 'A new Membership NFT in your wallet!'
 
'A new NFT key' should be 'A new membership'

'It has been added to your Unlock Keychain where you can view it and, if needed, print it as a signed QR Code!' should be 'It has been added to your Unlock Keychain where you can view it'

'The Unlock team' and the Unlock Protocol footer should be 'Unlock Labs'

**Comment by julien51** [comment]
Very good! I'll do these changes ASAP.
