### ISSUE TITLE
Checkout does not allow scrolling on mobile 

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10059]
When visiting https://unlock-protocol.com/membership on an iPhone 13, the modal does not allow scrolling. 

https://user-images.githubusercontent.com/32484647/198109751-f51bae05-d10f-4aa1-8ae5-82ed32b9b95d.mov

**Comment by searchableguy** [comment]
because there is nothing to scroll 🤔 

The scroll wheel will appear if there are locks to scroll on the side.
