### ISSUE TITLE
Remove 'lock' from checkout

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10058]
Remove 'lock' from 'Select lock' in checkout. Lock is an uncommon term for users and may cause confusion.

![Screen Shot 2022-10-26 at 2 24 25 PM](https://user-images.githubusercontent.com/32484647/198106511-8df8122d-013f-4d0a-8a7e-1356814c8acb.png)

**Comment by julien51** [comment]
What would you use instead? 
"Select contract", or "select membership" or "select product"... or?

**Comment by julien51** [comment]
I think one of the challenges is that there are multiple kinds of memberships: subscriptions, tickets... etc.

**Comment by patrickworkman** [comment]
Just 'Select:'
