### ISSUE TITLE
Placeholder text when email is required could cause confusion

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10061]
When users are asked for their required email address (required due to LockManager selecting 'Collect email address' in Checkout Builder), the placeholder of 'hello@unlock-protocol.com' could cause confusion. We should assume users don't know what Unlock Protocol is.

Maybe replace it with 'your@email.com'? 

<img width="437" alt="Screen Shot 2022-10-26 at 6 43 06 PM" src="https://user-images.githubusercontent.com/32484647/198152794-0917d56a-442d-4358-9249-109c3165a1da.png">

**Comment by julien51** [comment]
Good one!
