### ISSUE TITLE
"Update Metadata" to "Edit Metadata" fixes and requests

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10095]
No-code creators "see" their collections and members on OpenSea. We should make it clear to creators using our metadata configurator, that the tool edits their member's NFTs on OpenSea. 

OpenSea Create Tool [here](https://opensea.io/asset/create)

If metadata can be updated at any time, the CTA should be "Edit Metadata" or "Edit OpenSea"

"Edit Metadata" CTA should be purple like other CTAs throughout Dashboard

"Edit Metadata" subtitle should be "Adding rich data to your memberships on OpenSea and other marketplaces "

Basic 
- Name: Subtext should be "This will appear as each NFT's name on OpenSea on other marketplaces. [Edit your collection on Opensea](https://www.youtube.com/watch?v=s_Lo2RxPYGA)"

- Description: Add Subtext "This is each NFT's description on OpenSea and other marketplaces." 

Event Ticketing
- Meeting link should be "Event link"

Advanced
- "Youtube URL" should be "YouTube URL"
- Do Livepeer or [glass.xyz](https://glass.xyz/watch/6WwVsta2gqkhz4tqpCeH3K36GxoU3f6dh7JqeH8YVTTW) links work?
- What background does 'Background Color' edit? Where is the background "seen"?

Custom 
- Properties subtext should be "Textual traits that show up as rectangles on OpenSea and other marketplaces"
- Levels subtext should be "Numerical traits that show as a progress bar on OpenSea and other marketplaces"
- Stats subtext should be "Numerical traits that just show as numbers"

Feature requests
- Toggle for Unlockable Content that can only be revealed by the owner of the item.
- Toggle for Explicit & Sensitive Content ([OpenSea Policy](https://support.opensea.io/hc/en-us/articles/1500010882222-Is-explicit-sensitive-content-allowed-on-OpenSea-))

**Comment by searchableguy** [comment]
> "Edit Metadata" subtitle should be "Adding rich data to your memberships on OpenSea and other marketplaces "

The subtitle is actually the current description and link. It's not a description for the button itself.

**Comment by searchableguy** [comment]
For the opensea feature request, it would be a bit more complicated to add since they don't provide a documented API (I see it does a mutation via graphql API) and require authentication + collection authorization.

**Comment by patrickworkman** [comment]
All of the major NFT Marketplace refers to "metadata" as "properties" on individual NFT pages.

[OpenSea](https://opensea.io/assets/ethereum/0x23581767a106ae21c074b2276d25e5c3e136a68b/1451)
[Zora](https://market.zora.co/collections/0x23581767a106ae21c074b2276D25e5C3e136a68b/422)
[LooksRare](https://looksrare.org/collections/0x23581767a106ae21c074b2276D25e5C3e136a68b/4898)

We should change "Edit Metadata" to "Edit Properties". @searchableguy
