### ISSUE TITLE
starting to drift from clean navigation on the lock management page

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#10098]
we have five separate regions on the lock management page with action buttons. as unlock adds more features, this fragmentation of the interface may continue.

<img width="843" alt="Screen Shot 2022-10-29 at 2 41 12 PM" src="https://user-images.githubusercontent.com/214760/198853580-9c1a5982-25a3-4634-bbb0-a0e4e3995e70.png">

suggest looking at some patterns and best practices to see if these actions can be consolidated into a consistent location and pattern, perhaps on the left sidebar.

**Comment by ChialiTsai** [comment]
Agreed. Thank you for create the issue.
