### ISSUE TITLE
Lock Listing and Keys subtitles

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10096]
Locks are deployed through the Unlock smart contract. A Lock is specific to Unlock. It is not widely known what a Lock is.

The subtitle of [Lock Listing](https://staging-app.unlock-protocol.com/locks) could be revised from "Create membership for Event ticketing, Media membership, DAO, Certification, collectibles and more." to "A Lock is a smart contract you create, deploy, and own on Unlock Protocol"

Keys are created by contracts deployed on Unlock. A Key is specific to Unlock. It is not widely known what a Key is.

A subtitle could be added to "Keys" below "[Member Keychain](https://staging-app.unlock-protocol.com/keychain)" to describe a Key. Example: "A Key is a membership NFT created on Unlock Protocol".

**Comment by julien51** [comment]
Very good ideas! Assiging to @kalidiagne who he can implement!
