### ISSUE TITLE
Expired keys not shown as expired on Keychain!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10108]
I use a fairly old lock for many of my demo: https://zplit.online/xdai/
When I get a membership it is shown for me as it should on the keychain, but when I cancel it from there, it stays on the keychain and is not marked as expired.

**Comment by julien51** [comment]
This will be fixed by https://github.com/unlock-protocol/unlock/pull/10169

**Comment by kalidiagne** [comment]
> This will be fixed by #10169

i cant buy the membership to test it, is this solved?

**Comment by kalidiagne** [comment]
> > This will be fixed by #10169
> 
> i cant buy the membership to test it, is this solved?

@julien51
