### ISSUE TITLE
Preview Keys functionality in Dashboard

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10106]
**Is your feature request related to a problem? Please describe.**
Creators want to 'see' Keys their contracts will create.

**Describe the solution you'd like**
Enable "Preview Key" functionality where Creators can 'see' their memberships. 

**Describe alternatives you've considered**
Creators should test on testnets to 'see' their NFTs. We could add copy to Lock Creator that encourages testing, possibly pointing users to testnet faucets.

**Comment by julien51** [comment]
Thanks @patrickworkman !

Would you be able to clarify this?

> Enable "Preview Key" functionality where Creators can 'see' their memberships.

Where would they "see" the keys? OpenSea? What would they see exactly? the image?

> Creators should test on testnets to 'see' their NFTs. 

I agree with this a lot! Too many people are just deploying on production network "first" when they should start from a test net almost always as it allows them to... test things!

**Comment by julien51** [comment]
> We could add copy to Lock Creator that encourages testing, possibly pointing users to testnet faucets.

We do point to the faucets but I think we should indeed add copy about deploying on testnets first.

**Comment by patrickworkman** [comment]
Would you be able to clarify this?

Enable "Preview Key" functionality where Creators can 'see' their memberships.

Where would they "see" the keys? OpenSea? What would they see exactly? the image?
Creators want to see how the image, description, and properties of their Keys appear on OpenSea.

**Comment by patrickworkman** [comment]
> 

We do point to the faucets but I think we should indeed add copy about deploying on testnets first.



> 
Copy could be 'Bootstrap testing on Goerli and Mumbai'

**Comment by julien51** [comment]
> Creators want to see how the image, description, and properties of their Keys appear on OpenSea.

I understand what the sentence, but I really have no idea how to make that because we don't have a way to "control" OpenSea :D

**Comment by patrickworkman** [comment]
> 

We cannot "control" OpenSea.

How can Lock Managers 'see' their memberships? Maybe add a modal similar to Checkout Configurator based on what an NFT looks like on OpenSea?
