### ISSUE TITLE
cant get cancellation value for token id = 1

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#10163]
On keychain page we have an error message for some keys.

By checking on details I realized that on goerli when using get `getCancelAndRefundValueFor` when token = 1 this gives an error 

testing on goerli:  https://goerli.etherscan.io/address/0x500404480f8a7f54fa346f4ae174522639233a12#readProxyContract

**Error when tokenID = 1**
<img width="1386" alt="Screenshot 2022-11-01 at 14 39 50" src="https://user-images.githubusercontent.com/20865711/199247124-98417f7d-13dd-4572-8691-41c7249ea58c.png">

**Any other tokenID work
<img width="1407" alt="Screenshot 2022-11-01 at 14 39 59" src="https://user-images.githubusercontent.com/20865711/199247230-42d8f05a-4d93-48d1-b6dd-f311b0c41285.png">
s fine**

**Comment by julien51** [comment]
Could this be due to this @clemsos ? https://goerli.etherscan.io/tx/0xa8750e5f8b6b41462648e6ac0bd51d6e34fcd73c97796460f1f2c5805e1318f6

**Comment by julien51** [comment]
@kalidiagne I think this is the bug we fixed in v12 where when canceling a key... but basically you should _not_ be able to cancel keys that have already been cancelled?
