### ISSUE TITLE
'Sign up for Updates' for email collection in Dashboard

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10166]
**Is your feature request related to a problem? Please describe.**
Dashboard is permissionless to use. Labs wants to share news about Dashboard with Creators, Lock Managers, and anyone who would be interested.

**Describe the solution you'd like**
Add copy and feature to collect email addresses within Dashboard's Lock Listing and Lock Creation Pages. This feature will be completely optional. 

Headline: 'Sign up for Updates
Subtext: 'Receive fresh news about Unlock, including new features and opportunities to contribute' 

**Describe alternatives you've considered**
Add a pop-up window that requests an email address (optional) and/or asks users to 'Claim your free Unlock Membership'

**Additional context**
![Screen Shot 2022-11-01 at 10 06 22 AM](https://user-images.githubusercontent.com/32484647/199252952-e4f02019-2ca2-47ea-ba56-305836240313.png)
Similar to Signup option at the bottom of [Unlock's Homepage](https://unlock-protocol.com/).

**Comment by julien51** [comment]
> Describe alternatives you've considered
> Add a pop-up window that requests an email address (optional) and/or asks users to 'Claim your free Unlock Membership'
>

**Comment by julien51** [comment]
Good point! I think we can just bring the footer too. What do you think @ChialiTsai ?

**Comment by julien51** [comment]
Also let's move to the UI library so we can (re)use it in both unlock-app and unlock-protocol-com please!

**Comment by julien51** [comment]
Assigning to Kali as he's working on a new component for the footer that should include this and that we will be able to re-use in all of our apps + docs + guides!
