### ISSUE TITLE
"Create Lock" button invisible on mobile in dashboard

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1016]
**Describe the bug**
When viewing the dashboard on mobile, the "Create Lock" button is invisible in the layout

**To Reproduce**
1. Go to dashboard

**Screenshots**
![screenshot_20190114-131512](https://user-images.githubusercontent.com/98250/51131780-a6423680-17fe-11e9-8dd5-5c89a2818357.png)

**Smartphone (please complete the following information):**
 - any device

**Comment by julien51** [comment]
I think that was intentional :)
The use case of creating locks on the go is probably fairly advnlanced for now.

**Comment by julien51** [comment]
We also do not have a good looking form for mobile. Closing until we decide to actually implement this.
