### ISSUE TITLE
Handle ENS in the unlockjs

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10213]
In unlockjs, we have many methods which interact with user addresses. We should support also ens for these and automatically resolve the address for the consumer.

This can elevate issues on our frontend where we handle ENS explicitly.

**Comment by julien51** [comment]
Also, we should be smarter when we do resolutions: we should only assume the resolved account address is correct on mainnet and if there is a match but we're looking at a different network, we should only accept the match if it is an EOA.

**Comment by julien51** [comment]
As I think more about this, I am actually not sure this is the job of unlock-js. I worry that it adds a bit of complexity and coupling for things which should not be coupled. I think resolution should be dealt with "at a higher level"  and UnlockJS only handles proper addresses. I also don't like the idea of picking "winners". I can imagine people want to do resolution using Unstoppable Domains or others down the line...
I know ethers.js does ENS resolution but I am not sure this is a great idea either (and is explained by the shared story between ENS and ethers!)

**Comment by julien51** [comment]
I will close in favor of https://github.com/unlock-protocol/unlock/issues/10398
