### ISSUE TITLE
Unlock start time x, end time y, url z

### ISSUE THREAD

**Issue by atotsm** [unlock-protocol/unlock#10232]
If people have the NFT, they have access to the redirect of a url from time x to time z.

That way we can sell parts in a website or app to third party creators. Timeslot nft.

Have this unlock nft and this part from the website is yours from this hour to that hour.

Request 1. An unlock that starts from time x
Request 2. An unlock that enables the buyer of that url-nft to have access to the redirect from time x to time y.

Highly appreciated 🙏

**Comment by julien51** [comment]
Hello! That's already quite ready using hooks!

**Comment by julien51** [comment]
> If people have the NFT, they have access to the redirect of a url from time x to time z.

Ok, first question are `x` and `z` the same for everyone?
If not what triggers `x` and `z` for a single address?

By default the NFT membership starts when it has been minted by the user. 

> Request 2. An unlock that enables the buyer of that url-nft to have access to the redirect from time x to time y.

Is that something like https://token-gated.com/ It basically redirects the user unless they have a special NFT.

**Comment by atotsm** [comment]
Ok, first question are `x` and `z` the same for everyone? If not what triggers `x` and `z` for a single address?

One option could be. 1 unlock NFT = 1 Timeslot. It's an online meeting between the one who sold the NFT and the one having the NFT.

Someone wants to order a phone call with someone. That someone buys the phone call tomorrow from 10:00 to 11:00 through a u-nft.

You could offer someone a u-nft that basically is temporarily access to a url that is a zoom or so.

It can't unlock at the time of minting.

Maybe it could function if it would redirect the call-url after x time, and the user would not see the call-url. 

Am I making any sense? 😗🙏

**Comment by julien51** [comment]
@atotsm Sorry for the delay here! Things have been a bit busy recently :D

I honestly would not use the expiration to specific the time slot because things get complicated really quickly here.
If I were to build what you're trying to achieve I would actually have a token gated calendar that would let people who have _any_ membership NFT just book any slot (but only one). This way the NFT does not have to be specific to a slot.

**Comment by julien51** [comment]
After careful consideration the way to implement this is using hooks! With the `onValidKey` hooks you can customize the starting and end date for each (or all) of the keys!
