### ISSUE TITLE
Paywall does not seem to load

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10240]
It looks like the paywall application does not seem to load on the demo on staging https://staging-app.unlock-protocol.com/demo?network=5&lock=0x0852ca744ee97c6c315686958e69b88a99a864e8

This blocks the prod PR https://github.com/unlock-protocol/unlock/pull/10238

**Comment by julien51** [comment]
Great catch @searchableguy

**Comment by searchableguy** [comment]
Fixed by revert.
