### ISSUE TITLE
Auto refresh metadata on opensea when changing it on our frontend

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10249]
Opensea doesn't fetch the latest metadata when displaying it on NFTs. 

Sometimes it gets delayed until they do their regular crawl or get enough visitors. Creators may be confused why the new metadata doesn't reflect on opensea and may not know about the refresh button on the collection. 

We should hit the opensea refresh endpoint for collection whenever user updates the metadata.

**Comment by julien51** [comment]
At the same time we should see if we can automatically verify contracts on Etherscan (or similar).
This could leverage our websub infrastructure!

**Comment by pulsarforge** [comment]
Hi, I am interested on solve this bounty, (as previously talked at the community), pls if there some extra links, docs or info to take in account? It would be useful to have it.

**Comment by julien51** [comment]
> Why do we need to verify the contract on etherscan? Is that related to opensea?

Not related to OpenSea. And we need this for convenience...


Regarding the update, indeed this is not ideal. I think for now we will have to wait for users to hit "refresh" on OpenSear.

Closing for now.
