### ISSUE TITLE
Partial withdraws

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1025]
Right now, when the lock owner withdraws, they withdraw all the funds on the lock. 
Since we want to implement a mechanism to cancel a key, we need to allow the lock creator to only withdraw funds partially. 

For this feature to exist we need to things:
1. Support on the smart contract. Assigning this to @nfurfaro .
2. Support on the creator dashboard. Assigning this to @smombartz for the design and @cellog for implementation.

**Comment by nfurfaro** [comment]
@julien51 off the top of my head...there could be 2 withdraw functions, 1 with 0 args and 1 with one uint arg. Both would end up calling an internal function `_withdraw(uint amount)` similar to how `purchaseFor` and `purchaseForFrom` are implemented. The uint amount could be in ETH or a percentage (such as `withdraw(50)` to take half.)

**Comment by nfurfaro** [comment]
RE: TODOS in withdraw function
>    * TODO: consider allowing anybody to trigger this as long as it goes to owner anyway?
>   * TODO: check for re-entrency?
As for number 1, Not sure we want to let anyone call this even if it can only go to the owner...
As for number 2, this is easy to implement, but as only the owner can currently call the function is reentrancy a concern in this case?

**Comment by smombartz** [comment]
want to make sure i understand fully. is this to partially withdraw funds or cancel a key (which essentially is a partial withdraw)?

**Comment by julien51** [comment]
No, this is not about canceling keys. It's for the lock owner. Once people have purchased keys, their lock receives the funds. Right now the lock owner can withdraw the funds when they want, but we want to allow them to do that only partially.

For example, I have a lock whose keys are $10. If 2 people purchase keys, I receive $20. Right now I can only withdraw $20, but we want the ability to withdraw only $15 (that is leaving $5 on the lock until I withdraw again).

Makes sense?

**Comment by julien51** [comment]
@nfurfaro For the use case 1. I actually think this could be a nice feature to build for some organizations where we trigger withdraws automatically on behalf of creators (I see this as a way to secure the funds, because we never know 100% that a smart contract could not be abused, or as a bug which would allow malicious people to steal the funds)

**Comment by nfurfaro** [comment]
@julien51 so for now I'll just leave the TODOs in place.

**Comment by smombartz** [comment]
@julien51 thats was my hunch. thanks for clarifying. so in the UI we need them to enter the amount they want to withdraw + confirmation button (which then gets sent to the wallet). correct?

**Comment by cellog** [comment]
what's the priority on this one?

**Comment by smombartz** [comment]
here a quick solution that uses parts of the lock creation pattern

![image](https://user-images.githubusercontent.com/1377389/51844448-4b6f0b80-22e3-11e9-8abe-7133c25e61fb.png)

**Comment by julien51** [comment]
The smart contract part of this one is done.
@cnasc is working on the front end implementation. (feel free to open sub-issues !)

**Comment by julien51** [comment]
Let's close this as stale for now.
