### ISSUE TITLE
Optimize rpc calls in unlockjs

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10265]
As part of building new interface on top of unlock js, we should optimize sequential calls with multicall whenever possible to speed up the response time.

This will be useful in getting properties of lock in constant time instead of calling a bunch of methods in promise.all as an end user.

We already have a package for multicall in unlock js which we can use in other places and wrap our contracts in it. 

Additionally, next version of ethers support multicall natively. 

We should ideally follow https://github.com/ensdomains/ensjs-v3 which allow batch calling most of their library easily.

**Comment by darkdrag00n** [comment]
Hi @julien51, I am interested in picking this work item. I can see the "bounty" label on this issue. Can you please share the amount as well as the procedure for claiming the bounty upon work completion? Note that I checked the [docs](https://docs.unlock-protocol.com/governance/grants-bounties/bounties) but there is no information about it. Thanks!

**Comment by julien51** [comment]
With `ethers` 6 tyhis is happening by default!
