### ISSUE TITLE
Discord On-boarding: 'Buy Membership' CTA in Lobby should be 'Claim Membership' 

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10278]
**Is your feature request related to a problem? Please describe.**
When people join Unlock's Discord, they're asked to 'Unlock Discord' in the #lobby channel. After clicking, they are asked to 'Buy Membership'. People do not join Unlock's Discord to buy a membership. 

**Describe the solution you'd like**
We should change the button to 'Claim Membership' or 'Free Membership'. 

**Describe alternatives you've considered**
We could change the button to 'Free Membership'.

**Comment by julien51** [comment]
Fair point. @searchableguy can we change it to "claim" ?
