### ISSUE TITLE
Allow using connect (SIWE) inside iframe

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10276]
We allow using checkout inside iframe to integrate better with the application interface.

We should allow the same for connect (SIWE).

There are a few things to keep in mind here.

We use postmate packagw for iframe communication which does not work properly with multiple iframes on the same page so we will need to replace it with a different package or directly communicate via our own wrapper.

**Comment by julien51** [comment]
I am actually not sure we need this. Let's have a deeper conversation about it before you start working on it please.

**Comment by julien51** [comment]
Ok Patrick thinks this would be nice to have. I say let's try! if we do it I also want us to have a nice API inside of `unlock-web` for it so that it's easy to open/close inside of react apps for example!
