### ISSUE TITLE
Ethereum address that will receive the membership NFT is an Email Address in Checkout

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10299]
**Describe the bug**
During 'Add recipients' in Checkout, the copy states 'The Ethereum address that will receive the membership NFT' is the email address associated with an Unlock Account when users are using the no-crypto wallet flow in Checkout.

**To Reproduce**
1. Go to Checkout
2. Create or use an Unlock Account
3. On 'Add recipents' see the copy error.

**Expected behavior**
Should state, 'The address that will receive the membership NFT'

**Screenshots**
<img width="442" alt="Screen Shot 2022-11-18 at 6 33 44 AM" src="https://user-images.githubusercontent.com/32484647/202696667-64436195-d164-4a3a-b08f-bf45d8e24e19.png">

Global issue

**Comment by julien51** [comment]
Good point. I fixed it yesterday. It will go live soon.
