### ISSUE TITLE
Restart when user changes network on the checkout

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10301]
**Describe the bug**
User is unable to purchase an Unlock membership to access the Unlock Discord.

User selects 'Unlock Discord' and 'Buy Membership' in #lobby of Unlock's Discord. 

**To Reproduce**
1. Switch to Gnosis Chain, sign Metamask message, click next
2. Fill in email address
3. Pay via cryptocurrency (You don't have enough DAI for gas fee), switch to ethereum -> have DAI so I click to proceed forward
4. Allow access to Unlock Discord Community, sign Metamask message
5. Screenshot

**To Reproduce**

**Expected behavior**
A successful transaction. 

**Screenshots**
![2022-11-18 07 00 11](https://user-images.githubusercontent.com/32484647/202701005-295ddc58-d7b5-4b11-b4b8-c829b5a87a54.jpg)

Desktop Chrome

**Comment by searchableguy** [comment]
> Pay via cryptocurrency (You don't have enough DAI for gas fee), switch to ethereum -> have DAI so I click to proceed forward

This is why the purchaseKey function is missing. We cannot find the contract on mainnet since it was deployed to gnosis. 

We should be throwing user back to start screen when they change network

**Comment by julien51** [comment]
Yeah, we should not let the user proceed if they are changing the chain mid-way. Can you look at this @searchableguy ?
