### ISSUE TITLE
Unclear user expectations within 'Don't have a crypto wallet' flow

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10304]
**Is your feature request related to a problem? Please describe.**
Users without crypto wallets are prompted to 'Get started' and asked for their email address & prompted to create a password without context. 

**Describe the solution you'd like**
It should be clear to users without crypto wallets they are creating an Unlock Account.
'Let's start with your email address' should be 'Let's create an Unlock Account'. 
A link to '[What is an Unlock Account?](https://docs.unlock-protocol.com/tools/sign-in-with-ethereum/unlock-accounts/)' would provide the necessary context to users unaware of what they're creating. 

**Describe alternatives you've considered**
Add copy about what an Unlock Account is in the Checkout modal under 'Let's create an Unlock Account' and email collection field. The copy could be:
'Unlock Accounts enable you to own a membership without a crypto wallet. Once created, you'll sign in to authenticate your membership with your email and a password

<img width="354" alt="Screen Shot 2022-11-18 at 7 20 32 AM" src="https://user-images.githubusercontent.com/32484647/202704810-8e57beb6-383e-47c1-927b-186f75dfe333.png">

**Additional context**
We should prioritize a consumer-facing Guide explaining Unlock Accounts.

**Comment by searchableguy** [comment]
That's a good point.

**Comment by julien51** [comment]
> It should be clear to users without crypto wallets they are creating an Unlock Account.

The challenge is that if they already have an account, we will not create a new one for them. I will try to come up with better copy to make things more obvious.

**Comment by julien51** [comment]
> A link to '[What is an Unlock Account?](https://docs.unlock-protocol.com/tools/sign-in-with-ethereum/unlock-accounts/)' would provide the necessary context to users unaware of what they're creating.

Great idea!

**Comment by julien51** [comment]
> We should prioritize a consumer-facing Guide explaining Unlock Accounts.

cc @ccarfi @wonderwomancode

**Comment by julien51** [comment]
Here is what I have:

<img width="515" alt="Screen Shot 2022-11-18 at 11 58 55 AM" src="https://user-images.githubusercontent.com/17735/202760007-0073d663-c47b-4794-92c8-9b8cc994b99b.png">

If the email I enter matches an _existing_ account: 
<img width="556" alt="Screen Shot 2022-11-18 at 11 59 22 AM" src="https://user-images.githubusercontent.com/17735/202760100-31e15e2c-3ccf-49d5-9bd7-810d534621e3.png">

If it does not: 
<img width="531" alt="Screen Shot 2022-11-18 at 11 59 42 AM" src="https://user-images.githubusercontent.com/17735/202760163-a4b8f5b8-c5f1-426d-b165-39957b80f2fc.png">

**Comment by patrickworkman** [comment]
‘Unlock Account’ or ‘Unlock account’?

I vote Unlock Account.

**Comment by patrickworkman** [comment]
A ‘Create Unlock Account’ CTA would be clearer than ‘Create Account’
