### ISSUE TITLE
Save Configuration in Checkout Builder

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10303]
**Is your feature request related to a problem? Please describe.**
When configuring Checkout in Checkout Builder, there should be an option to Save the configuration. As-is, configuration needs to be recreated during each user session. 

**Describe the solution you'd like**
Insert a 'Next' CTA so it's clear to users there is a 'Locks' tab with additional configuration options

**Alternative solution**
Enable an option to save the configuration after configured with a 'Save' CTA

**Comment by julien51** [comment]
At this point we have decided to *not* save these URLs because that adds a LOT of complexity. We will explore this later.

**Comment by patrickworkman** [comment]
Can we add copy to explain that checkout URLs created in Checkout Builder will not be saved once configured?
