### ISSUE TITLE
flocker styles different on confirmation page

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#10323]
<img width="814" alt="Screen Shot 2022-11-20 at 9 56 47 AM" src="https://user-images.githubusercontent.com/214760/202918074-566bec11-82ce-4c7a-ba05-26c14c6dfe82.png">

**Comment by julien51** [comment]
It was kind of intentional because I felt the top part was more important? Let me know if you want to have everything be of the same size.

**Comment by searchableguy** [comment]
fixed
