### ISSUE TITLE
Copy misalignment on Sign In With Ethereum 

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10320]
**Describe the bug**
‘web3 wallet’ in the body should be ‘crypto wallet’ to align with the CTA copy. 

‘Getting Started’ in the body should be ‘Get started’ to align with the CTA copy. 

Is it Unlock account or Unlock Account?

**Comment by patrickworkman** [comment]
![D905B3E7-30C9-4C00-8517-B8B4E7E20F81](https://user-images.githubusercontent.com/32484647/202873495-f200644c-3b4b-4e3e-8ada-08ca82a1b90a.jpeg)

**Comment by julien51** [comment]
Good catch! Fixing now!
