### ISSUE TITLE
Add to wallet on Checkout confirmation

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10339]
We need to add a button to "add to wallet" on the final screen in the checkout confirmation!
We already have code to add to wallet on the keychain and we could just easily re-use this code here.

**Comment by kalidiagne** [comment]
Add button on top of "open keychain"

<img width="1474" alt="Screenshot 2022-11-29 at 16 44 42" src="https://user-images.githubusercontent.com/20865711/204575620-d799d0b3-b05a-4061-9a77-6fe2faed690c.png">

**Comment by ef3n9r98** [comment]
Hi @julien51, I know some devs who'd be interested in working on this. How much is the bounty for fixing this issue? 

I'll put this issue up, along with the rest of the ones in the /unlock repo on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by ManyRios** [comment]
Still need help with this?

**Comment by SVell** [comment]
![Screenshot 2024-02-02 183228](https://github.com/unlock-protocol/unlock/assets/22966971/a63a83a8-5b92-415a-9990-a85d587ac9d8)
![image](https://github.com/unlock-protocol/unlock/assets/22966971/e02e1f16-8b17-426d-974c-14b5fb4b819e)

Errors adding NFTs even in keychain. With Rabby wallet and Metamask.

**Comment by julien51** [comment]
Thanks @SVell 0x8b62e8ef7cac0d042e59727dd5fb00a89d7f56a6
