### ISSUE TITLE
Purchasing a key on Goerli results in null keys object error

### ISSUE THREAD

**Issue by thehen** [unlock-protocol/unlock#10336]
When purchasing a key on Goerli in Unlock-js, I'm getting the following error:

`unlock-custom.js:109355 Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
    at WalletService.purchaseKey_default4 (unlock-custom.js:109355:14)
    at async Module.purchaseKey (unlock-custom.js:115241:3)`

It looks like the keys object here is null.

![image](https://user-images.githubusercontent.com/1434865/203182159-f0da811d-d22b-41e9-a451-00575915c4fb.png)

Live example - just try and buy a chest on Goerli: https://thehen.github.io/unlock-unity-demos/RPG%20Shop/

To debug, seach for this code in unlock-custom.js:

`
  await walletService.purchaseKey(
    {
      lockAddress: lockAddress,
      referrer: referrer
    }
  )
  `

**Comment by julien51** [comment]
Thanks @thehen ! I am able to reproduce and I think I found the issue!

**Comment by julien51** [comment]
Long story short, try to pass the "normalized" address for the lock...
We will have a version that's more robust very soon!

**Comment by thehen** [comment]
Awesome, thanks for the quick fix!
