### ISSUE TITLE
Add Flocker Profile link to 'Your membership contracts'

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10334]
**Is your feature request related to a problem? Please describe.**
When users come back to Flocker, it isn't clear where there permalink is. Users need this to share with their followers. 

**Describe the solution you'd like**
Add a pointer to the flocker profile under 'Your membership contracts' 

**Describe alternatives you've considered**
After creating a membership contract, default to the Flocker profile created with an 'Edit Attributes' CTA. 

Add a share CTA under the 'Edit Attributes' CTA 

![2022-11-21 17 29 04](https://user-images.githubusercontent.com/32484647/203170946-de5aab45-d6c7-46b6-9741-7670b7e8e73d.jpg)

**Comment by julien51** [comment]
<img width="463" alt="Screen Shot 2022-11-21 at 9 37 23 PM" src="https://user-images.githubusercontent.com/17735/203207303-d53f924d-a562-47be-a4c0-08ab6a784483.png">
We now added a share button!
