### ISSUE TITLE
Let Locksmith use non-tracked configuration file

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#1034]
Right now, you can edit configuration options in Locksmith by changing `config.js`. Unfortunately, because that file is tracked as part of the main project, that makes it very easy for database details to be accidentally committed into git as part of a local clone or, potentially, a branch commit in preparation for a PR.

I'd like to suggest that Locksmith checks for the existence of a new file, eg `config.user.js`, which would be untracked by git and mentioned explicitly in `.gitignore`. If the file exists and contains valid settings, those settings would then supersede the default settings that are laid out in `config.js`. In the first instance, perhaps it could be assumed that `config.user.js` is always a full copy of `config.js` that overwrites it completely.

**Comment by benwerd** [comment]
Tagging @akeem to weigh in here.

**Comment by akeem** [comment]
@benwerd thanks for raising this, I'll come up with something that should help to ensure that database details aren't captured in version control and wont be a pain to develop with

**Comment by benwerd** [comment]
I discussed it briefly with @julien51 and I don't think it's necessary for v0. But wanted to raise it!

**Comment by akeem** [comment]
Closing as this was resolved with the deployment of #1715
