### ISSUE TITLE
Use a contract creator's Twitter profile picture as the default image for Flocker checkout

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10341]
**Is your feature request related to a problem? Please describe.**
When claiming a membership, users see the Unlock logo instead of a Twitter account's profile picture. 

**Describe the solution you'd like**
Add the Twitter profile picture from the membership contract creator to the Checkout flow.

**Describe alternatives you've considered**
Add an 'Edit Purchase URL' CTA pointing to Checkout Builder on the page post-deployment and/or on the Flocker homepage after a membership contract has been deployed.

**Comment by julien51** [comment]
Moved to the right repo.
