### ISSUE TITLE
Wrong Fatal Error

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1038]
We are not showing the right fatal error when the user is "logged out" of metamask. 
Here's a screenshot which shows this.

<img width="1451" alt="screenshot 2019-01-15 at 14 41 59" src="https://user-images.githubusercontent.com/17735/51205900-ec69c980-18d4-11e9-9f0d-4cb93d2c8e7e.png">

There we should not show "network mismatch" but something about the wallet being locked.

**Comment by cnasc** [comment]
I'm willing to take a stab at this if you have other things going on, @cellog

**Comment by cellog** [comment]
go for it :) I'll leave myself on here to watch your comments.

**Comment by cnasc** [comment]
<img width="1399" alt="screen shot 2019-01-22 at 10 43 49 am" src="https://user-images.githubusercontent.com/9300702/51546652-a3fd5f00-1e32-11e9-969e-66a3be0c5a1d.png">

I think we may be able to close this issue now, the work to fix #966 seems to have handled it.

**Comment by cellog** [comment]
thanks!
