### ISSUE TITLE
Add helper to check if a key can be renewed by a renewMembershipFor

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10393]
If a lock changes, renewMembershipFor will fail to renew despite approval. There is no way to check for this without calling the `renewMembershipFor` method and tracking the error.

We should add a lastUpdatedLock timestamp field or a function to check if key can be renewed without calling renewMembershipFor.

**Comment by julien51** [comment]
Agreed we need to be better with this. Let me chat with @clemsos about this.

**Comment by julien51** [comment]
For now the requirements that need to be true for the renewal transaction:
* ERC20 approval from user to lock is sufficient (easy to check)
* ERC20 balance of user is enough (easy to check)
* Price/Duration/Currency was not changed using `_originalDurations`, `_originalPrices` and `_originalTokens`... We don't have a way for this yet.

I think we will need to add a view function like `originalTermsChanged` that would return `true` or `false` and can be used inside `renewMembershipFor`?

In the meantime, I think we can just assume that if first 2 conditions are met the renewal will succeed? (we provide warning around price changes...)

**Comment by clemsos** [comment]
Added the change as a private function for now in #11134 as we are still running into contract code size issues in PublicLock, so we want to make sure all sig we had are really relevant
