### ISSUE TITLE
Replace Jest

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10476]
Jest is not the best JavaScript testing framework anymore.
It also creates significant issues (memory leaks for ESM) in Locksmith.

Let's move to a better framework (I will let you @searchableguy recommend one), ideally for all the apps, but starting with Locksmith!

- [x] Replaced in locksmith (@searchableguy)
- [x] Replaced in UnlockJS (@clemsos)
- [x] In Unlock-app (@kalidiagne)
- [x] paywall (@clemsos)
- [x] paywall-app (@kalidiagne )
- [x] unlock-protocol-com (@kalidiagne)
- [x] eslint-config (@kalidiagne )

**Comment by searchableguy** [comment]
We use `Vitest` in ui library and we can use it everywhere else where we use jest especially on the frontend.

**Comment by julien51** [comment]
Will [Vitest](https://vitest.dev/) work with locksmith? and smart-contracts @clemsos ?

**Comment by searchableguy** [comment]
It will work with locksmith, yes. 

No idea about smart contracts part.

**Comment by clemsos** [comment]
I don't think it will work with smart contracts - or it will kind of a hack. Hardhat uses mocha natively or sth called [Waffle](https://getwaffle.io).

The main change now will be remove jest from Unlock-js

**Comment by kalidiagne** [comment]
✅ Replaced for `wedlocks` https://github.com/unlock-protocol/unlock/pull/10652

**Comment by julien51** [comment]
@kalidiagne It looks like you did not remove `jest` from `paywall` but from `paywall-app`. I will update the issue to reflect this.

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/11332

**Comment by julien51** [comment]
@clemsos found an issue with vitest + hardhat https://github.com/NomicFoundation/hardhat/issues/3790

**Comment by clemsos** [comment]
ok then ! Unlock js now uses vitest https://github.com/unlock-protocol/unlock/pull/11826
