### ISSUE TITLE
Redirect to relevant Day post claim in Checkout

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10490]
**Is your feature request related to a problem? Please describe.**
After claiming a Day's NFT through Advent Calendar, it's not clear as to why 'Return to Site' is relevant to the experience. 

**Describe the solution you'd like**
Post claim, the CTA copy should be 'Unwrap Day 2!' or something relevant to what the claim has enabled. 

<img width="363" alt="Screen Shot 2022-12-02 at 10 51 00 AM" src="https://user-images.githubusercontent.com/32484647/205333296-348e4409-00c8-461e-9e07-4664a031296c.png">

**Comment by julien51** [comment]
> Post claim, the CTA copy should be 'Unwrap Day 2!' or something relevant to what the claim has enabled.

We actually don't have a way currently to change the CTA on checkout.
