### ISSUE TITLE
does it make sense to add a "close" button to the checkout builder screen?

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#10523]
from the "tools" menu in the dashboard, bringing up the checkout builder in the Tools menu gives no way (other than the browser back button) to get back to the lock management page.

<img width="1387" alt="Screen Shot 2022-12-06 at 12 12 39 PM" src="https://user-images.githubusercontent.com/214760/206013626-c40af5b3-4e05-4219-bc28-d9924aac8060.png">

**Comment by ccarfi** [comment]
this is in contract to the Edit NFT Properties screen, which does have a close button.

<img width="1392" alt="Screen Shot 2022-12-06 at 12 18 30 PM" src="https://user-images.githubusercontent.com/214760/206014158-6cbb2430-dd3d-4292-af38-4965fab0fb07.png">

**Comment by julien51** [comment]
Cc @kalidiagne i think that's a good addition
