### ISSUE TITLE
Link to verification page missing

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/unlock#10530]
Link to /verification in the Unlock app is missing from the UI. If you don't know what the link is you'd never find it. Updated the event ticket page in the guides and added it to the Dashboard page in the docs, so it's not urgent. I think it would be good to have it in the "Tools" dropdown in the lock details page.

**Comment by julien51** [comment]
That's a good point. The QR code itself points to that, but it would be good to have a link anwyay.
