### ISSUE TITLE
Images and copy overlapping on Lock Settings page of Unlock Membership Dashboard

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10535]
**Describe the bug**
The image and copy overlap on each Lock Settings page within Unlock Membership Dashboard.

**To Reproduce**
1. Go to Lock Settings
2. View each page
3. See the copy overlapping the image on the right

**Expected behavior**
Copy and imagery should be separated

**Screenshots**
<img width="251" alt="Screen Shot 2022-12-07 at 6 57 35 AM" src="https://user-images.githubusercontent.com/32484647/206174788-6148d6d8-e148-4eb8-b65f-ada8724ad96a.png">
<img width="239" alt="Screen Shot 2022-12-07 at 6 57 45 AM" src="https://user-images.githubusercontent.com/32484647/206174794-f64042fb-c3f5-4cad-9202-692329016a09.png">
<img width="279" alt="Screen Shot 2022-12-07 at 6 57 50 AM" src="https://user-images.githubusercontent.com/32484647/206174795-07adb132-19b9-4775-9ef8-ad113231bdd7.png">
<img width="256" alt="Screen Shot 2022-12-07 at 6 57 58 AM" src="https://user-images.githubusercontent.com/32484647/206174798-8dbf3fdc-bf20-4392-af8b-52e773e1afbc.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 107

**Comment by julien51** [comment]
They also don't look great in mobile 

![Screenshot_20221207-225848](https://user-images.githubusercontent.com/17735/206353218-d3537642-40b5-4dfe-a69c-ddd444ba3498.png)
