### ISSUE TITLE
Add links to Unlock Twitter and Discord on 2022 Advent Calendar

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10541]
**Is your feature request related to a problem? Please describe.**
There is no pointer back to Unlock on 2022 Advent Calendar

**Describe the solution you'd like**
Add links to Unlock's Twitter and Discord in the upper right-hand corner

**Describe alternatives you've considered**
Add links to Unlock's Twitter, Discord, Dashboard, and Blog as top navigation

**Additional context**
<img width="1137" alt="Screen Shot 2022-12-07 at 9 45 19 PM" src="https://user-images.githubusercontent.com/32484647/206344680-5372e080-83b5-4ce6-ac36-c5f2d1032923.png">

**Comment by julien51** [comment]
Fixed!
