### ISSUE TITLE
Checkout confusion from non-crypto users

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10552]
**Is your feature request related to a problem? Please describe.**
The first few screens of Checkout confuse non-crypto users, leading them to abandon the experience. The confusing screen is 'Recipient'. Non-crypto users think they need to put a wallet address in the field. They don't know what a wallet is or why it is there. 

**Describe the solution you'd like**
Enable creators to add 'Recipient' to Checkout in Checkout Builder; turn it off by default.

**Describe alternatives you've considered**
turn off 'Recipient' by default

**Additional context**
![Screen Shot 2022-12-09 at 3 00 34 PM](https://user-images.githubusercontent.com/32484647/206787282-1ff9f2ee-53d5-4e50-b5e5-fd4ffcaa6143.png)

**Comment by searchableguy** [comment]
I think we could change the UI here a little to be less confusing. Collapse the recipient field further. 

It is already possible to skip recipient field using `skipRecipient` and happens when no metadata is collected (in this case, email is collected so we do get to this page).

**Comment by julien51** [comment]
@searchableguy I think we could do 2 things:
* if the user is an Unlock account, we don't let them customize the recipient (unless there are more than 1 of course!)
* If the user is an Unlock account, if `emailRequired` like it is here, we pre-fill the email address and skip that step?

**Comment by julien51** [comment]
> Enable creators to add 'Recipient' to Checkout in Checkout Builder; turn it off by default.

It is off by default, but shown when the checkout flow requires the user to enter metadata... (like in this case where the paywall is configured to collect email addresses)

**Comment by searchableguy** [comment]
@julien51 

> if the user is an Unlock account, we don't let them customize the recipient (unless there are more than 1 of course!)

You can buy membership for a different address using credit card though for an unlock account. With airdrop, this also changes a little because you would be able to add an email as recipient. 
 
Same with regards to second point. Unlock account user is able to buy for a different address using card where they could customize the email or other metadata.
