### ISSUE TITLE
"require" specific account

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10566]
Our checkout flow (rightfuly) keeps the user "logged in" when it is loaded, but sometimes, users are using different wallet addresses when they connect to different websites. This can create confusion as they don't necessarily _verify_ that the address connected on the application matches the one connected on the checkout.

It would be interesting to add another option to the paywall config `expectedAddress` that, if set, will verify that the user is connected to that one, or, if not, will try to connect to that one, and if it fails, just treat the user as _disconncted_.

**Comment by searchableguy** [comment]
The problem with this is metamask does not allow you to actually disconnect from the dapp. There are various work arounds but all require re-prompts which are confusing and fincky. This is why when you click on connect after disconnecting from our app or any other popular app when using injected provider, it re-connects back to the same account without prompt. 

Another issue is we need to handle multiple different way to connect here (injected provider, unlock account, coinbase, and wallet connect).

I'm not sure how the rest works when it comes to this. Are you able to re-prompt for account switch?

**Comment by julien51** [comment]
ok let's start with a simple warning about the expected account not matching.
