### ISSUE TITLE
Add Mint Date to NFT Metadata

### ISSUE THREAD

**Issue by blastchat** [unlock-protocol/unlock#10599]
**Is your feature request related to a problem? Please describe.**

We want to display our members "joined date" to the NFT's metadata as a sign of clout. Ex: The earlier you join the community the more clout you will have in our community. 

@julien51

**Comment by julien51** [comment]
Thanks a loyt @blastchat ! W'll get started on this!

**Comment by blastchat** [comment]
@julien51 any luck or progress on this? Lol

**Comment by julien51** [comment]
Sorry for the delay here. We now have the `createdAt` and `createdAtBlock` in the subgraph so I believe it should be fairly easy to build.

I will add a bounty tag to this one.

**Comment by blastchat** [comment]
Thank you Julien!

**Comment by blastchat** [comment]
That would be amazing @iMac7

**Comment by julien51** [comment]
@iMac7 Let's go for it! Please add the `mintedAt` value in the subgraph for each key (yes that is the NFT). Once it is in the subgraph, please check the `locksmith` calls that renders the metadata to make sure this is "served" as well. (as an attribute).

We are attaching 250 USDC because this includes 2 significant changes (subgraphs + locksmith)

**Comment by julien51** [comment]
> @julien51 since there is already createdAt in the subgraph, will mintedAt have the same functionality but with a different name?

Ha! you are correct, we already have `createdAt`so we do not need `mintedAt` in the subgraph... we just need to expose it in the metadata i locksmith...

**Comment by julien51** [comment]
@iMac7 do you mind posting the address I should use for the payment here? Thanks!

**Comment by julien51** [comment]
Sorry for the very long delay here! This was just paid https://basescan.org/tx/0x85c1258ed7ad18bcb39a44a858c5425ffe7d1e00e22f9e76dfaaf37616df8c19
