### ISSUE TITLE
Support update to lock expiration on subgraph

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10595]
**Describe the bug**
Lock duration does not get updated on subgraph whenever someone updates it after initially. 

We don't have an explicit event for expiration separately so we would need to think of some other way to update this.

**Comment by julien51** [comment]
@searchableguy Can you send an example of this? tx that updates the expiration + subgraph query that shows the wrong one/ It would be very helpful.

**Comment by julien51** [comment]
https://goerli.etherscan.io/tx/0x78ba0c93e2de299b586ca1c1d62b863af24dda76a43752b2a9c4e670a7dc8549

**Comment by julien51** [comment]
On `v12`, we can use `LockConfig` which we currently handle.

Since we did not have an event for this in older versions, we need a workaround.
For this, I suggest to use `handleLockUpgraded` handler to reset all the values.

**Comment by clemsos** [comment]
do you think we should have a separate event just for expiration? The goal of `LockConfig` was to package all this lock setting into a single function. What we seem to need is a workaround for lock with version prior to v12 ? If so we can remove the smart-contract and v13 tags, as this looks more like a subgraph issue

**Comment by searchableguy** [comment]
No. I don't think separate event is needed. This issue was opened for support for older locks which did not have an explicit event.

**Comment by julien51** [comment]
Thanls for the clarification @searchableguy I'd say we can probably close it and ask users to update their locks?

**Comment by searchableguy** [comment]
I think that's fine. Most active users are on lock v12
