### ISSUE TITLE
Editing email on members page fail if a membership already has key metadata

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10619]
**Describe the bug**
If you go to members page and try to add or edit email for a membership which already has some key metadata, it will fail because it will try to update non-existent user metadata. This happens because we check for key metadata when deciding between creating or updating user metadata.

**Comment by kalidiagne** [comment]
cant reproduce with this steps: 

**scenario 1**
- mark key as `check-ed in`
- add/edit email. 


**scenario 2**
- add/edit email

**Comment by julien51** [comment]
@searchableguy Can you please provide a bit more context on how to reproduce this? Thanks!

**Comment by searchableguy** [comment]
Reproduction steps

1. Mark key as checked in
2. Reload the page (this is the triggering point)
3. Try to add email now

**Comment by kalidiagne** [comment]
> Reproduction steps
> 
> 1. Mark key as checked in
> 2. Reload the page (this is the triggering point)
> 3. Try to add email now
> 
> As also explained in the comment
> 
> > This happens because we check for key metadata when deciding between creating or updating user metadata.
> 
> When we should be checking for user metadata.

Still can't replicate with the steps suggested 

https://user-images.githubusercontent.com/20865711/211555584-56d36942-a27a-4551-8f32-13f698340d3c.mov

**Comment by searchableguy** [comment]
https://user-images.githubusercontent.com/73341821/211561175-97e16e75-d6ee-48c5-bbe7-cf11832b3aff.mp4

@kalidiagne 

Lock for reproduction: https://goerli.etherscan.io/address/0xb78d7a08e3dfab5ecb82d5ec916285abb26feba5
