### ISSUE TITLE
Use Header/Footer

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10617]
Now that we have Header and Footer let's add them:

Header:
* [X] https://unlock-protocol.com/
* [ ] https://docs.unlock-protocol.com/
* [ ] https://unlock-protocol.com/guides
* [ ] https://showcase.unlock-protocol.com/

Footer:
* [X] https://unlock-protocol.com/
* [x] https://app.unlock-protocol.com/ 
* [ ] https://docs.unlock-protocol.com/
* [ ] https://unlock-protocol.com/guides
* [ ] https://showcase.unlock-protocol.com/

**Comment by kalidiagne** [comment]
@julien51 for now we can not integrate for docs, react 18 not supported yet in docusaurus

- https://github.com/facebook/docusaurus/issues/7264
- https://github.com/trussworks/Engineering-Playbook/pull/293#issuecomment-1420978018

**Comment by julien51** [comment]
Is there any reason why we _need_ React 18 for our UI library?

**Comment by julien51** [comment]
So it looks like some tailwin library require the use of React 18... so for now it is probably more reasonable to wait for Docusaurus to support React 18. 

Please focus on the guides!

**Comment by julien51** [comment]
Related https://github.com/unlock-protocol/unlock/issues/10715

**Comment by julien51** [comment]
@searchableguy would you be able to help here so we ship or header/footer components in a way that could allow them to be embedded in guides? (WordPress site)

**Comment by julien51** [comment]
Adding @searchableguy so we can add the UI package to Wordpress.

**Comment by searchableguy** [comment]
I opened a PR to add cdn build. There is an example inside it which you can copy to add import and mount react components directly from our UI library.

**Comment by julien51** [comment]
@kalidiagne Thisis back on your plate. Please take of it ASAP.

**Comment by kalidiagne** [comment]
Header/Footer are now added in showcase and guides website.

We need more steps: 

- [ ] Add notion documentation that includes the details about how we can change the menu and how to set it
- [ ] Include the showcase/guides menu in the `ui` package to prevent losing the menu configuration

**Comment by kalidiagne** [comment]
@julien51  

An update on the implementation for guides/showcase that i checked with Chris.
it's all now set and works fine with Chrome/Brave, but we have to consider these issues: 

- Cross-browser support: for example, not all versions of Safari/Firefox are not supporting `importmaps` which makes not possible to show the footer/header components 

<img width="600" alt="Screen_Shot_2023-06-08_at_6 33 32_PM" src="https://github.com/unlock-protocol/unlock/assets/20865711/c5914a5c-5b00-40ba-abc3-1bb38f7d7ad0">

- First loading can be very slow, about 8/10sec to load the header/footer 

<img width="1414" alt="Screen_Shot_2023-06-08_at_6 22 06_PM" src="https://github.com/unlock-protocol/unlock/assets/20865711/74453bcf-15aa-43eb-ba59-c80f61dddae0">

I suggest pausing the implementation for showcase/guides and considering the Headless CMS approach.
