### ISSUE TITLE
`@unlock-protocol/contracts` `IUnlock` interfaces do not have proper return types

### ISSUE THREAD

**Issue by sebastiantf** [unlock-protocol/unlock#10654]
https://github.com/unlock-protocol/unlock/blob/ef24d9cb9447df896fa1838d891c749f23d1405c/packages/contracts/src/contracts/Unlock/IUnlockV11.sol#L183-L187

`publicLockVersions`,  `publicLockImpls` in `IUnlockV11` doesn't have return types causing issues when using those methods

_Originally posted by @sebastiantf in https://github.com/unlock-protocol/unlock/issues/9877#issuecomment-1366758727_

**Comment by julien51** [comment]
@clemsos can you please look into this end fix it? Please be careful about only using the interface for the existing version (not including the latest changes)

**Comment by julien51** [comment]
@clemsos can you please look into this end fix it? Please be careful about only using the interface for the existing version (not including the latest changes)

**Comment by julien51** [comment]
@sebastiantf This has been fixed in version 0.0.15 https://www.npmjs.com/package/@unlock-protocol/contracts :)

**Comment by sebastiantf** [comment]
Thank you so much! Works good now
