### ISSUE TITLE
Configure ENV for cross-platform support (Windows support)

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1067]
**Describe the bug**
On Windows several of the npm commands I have tried fail.  Below are two examples caused by setting an ENV variable.  We could consider using https://www.npmjs.com/package/cross-env for cross platform support.  Note I do not have experience with this package, but it seems to fit our needs.

```
unlock\unlock-app> npm run test

> unlock-app@0.1.0 test E:\UnlockProtocol\unlock\unlock-app
> UNLOCK_ENV=test jest --env=jsdom

'UNLOCK_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unlock-app@0.1.0 test: `UNLOCK_ENV=test jest --env=jsdom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unlock-app@0.1.0 test script.
```

```
unlock\unlock-app> npm run test

> unlock-app@0.1.0 test E:\UnlockProtocol\unlock\unlock-app
> UNLOCK_ENV=test jest --env=jsdom

'UNLOCK_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unlock-app@0.1.0 test: `UNLOCK_ENV=test jest --env=jsdom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unlock-app@0.1.0 test script.
```

**To Reproduce**
1. On windows, cd unlock-app
2. `npm run test`

**Expected behavior**
Tests execute.

**Actual behavior**
Tests fail to run.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: n/a
 - Version: 10.0.17134 Build 17134

**Comment by cellog** [comment]
I saw this issue in the react-redux repo. The fix is simple, we have to use the npm package `cross-env` and prefix the commands that set env variables with it.

I knew we would get bitten by this soon, didn't expect it pre-v0 :)

**Comment by hardlydifficult** [comment]
I'll pick this up tomorrow.
