### ISSUE TITLE
Metamask wallet button is stuck when you go to dashboard login page sometimes

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10713]
**Describe the bug**
Sometimes, the browser wallet connect button gets stuck especially first time you open the browser and metamask is locked. 

**To Reproduce**
1. Open a new browser session
2. Go to unlock dashboard login page
3. Click on connect in browser wallet button

It happens infrequently so you may need to repeat a few times.

**Comment by julien51** [comment]
Yeah, I have seen this too! What's interesting is that once you click on the button and nothing happens, refreshing the page just loads the content. So I suspect some kind of race condition where the app does not "know" that the user is logged in.

**Comment by julien51** [comment]
I suspect a race condition here. I anticipate this will be fixed once we change our definition of "authenticated"  from "wallet connected" to "we have a siwe/api token".

**Comment by searchableguy** [comment]
Let me know if it happens on the connect modal.
