### ISSUE TITLE
Upgrade to node 18

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10720]
We are using node 16.
I think some of the libraries we use for the contracts are stuck in node16 though. Can you confirm @clemsos ?

**Comment by clemsos** [comment]
> We are using node 16. I think some of the libraries we use for the contracts are stuck in node16 though. Can you confirm @clemsos ?

not that I know of. Which one did you have in mind?

**Comment by julien51** [comment]
I thought there was an issue with hardhat... but I guess that's not the case! Onward then!
