### ISSUE TITLE
Link to Github in package.json

### ISSUE THREAD

**Issue by mankins** [unlock-protocol/unlock#10766]
**Is your feature request related to a problem? Please describe.**

It would be great to have a link back to the monorepo so that you can locate the code when browsing [npm urls like this](https://www.npmjs.com/package/@unlock-protocol/contracts).

**Describe the solution you'd like**

Add to `package.json` https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository

**Comment by mankins** [comment]
For monorepos:

```
{
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/react.git",
    "directory": "packages/react-dom"
  }
}```

**Comment by julien51** [comment]
Thanks a lot @mankins ! I think we can get this done before the end of the week!

**Comment by julien51** [comment]
Just in time! Now we need to have a good changelog for each of them!

**Comment by mankins** [comment]
Awesome, thanks for this.
