### ISSUE TITLE
Checkout bugs + hook bug.

### ISSUE THREAD

**Issue by mbuxmann** [unlock-protocol/unlock#10774]
**Describe the bugs**
1. When buying the same key again, the execution gets reverted.
2. When entering the wrong password and then going back to and enter the right password leads to execution reverted.
3. The new locks contracts don't seem to work with the hooks contract. Followed this guide https://unlock-protocol.com/guides/password-protected-nft-memberships/# with goerlie hook - https://goerli.etherscan.io/address/0xe6e4b5daa2733e5090f23820d5a17d6cb25eea42#writeContract

**To Reproduce**
See loom videos

**Expected behavior**
1. I would expect that if given the option to "buy more" I should be able to buy more than one key of the same key. I've also run into this issue during testing my workflow and app which means I need to create a new lock each time at this moment for testing.

2. I would expect that going back and then entering the right password would work instead of having to refresh my browser.

3. I would expect that if entering the right password I would be able to mint an nft however this doesn't seem to be working.

**Screenshots**
In this video I am trying to buy the same key again however it is not working: 
https://www.loom.com/share/032f97f50077439f96eb06e469a3d3f6

In this video I am buying the same key with a new account however on the first try I enter the wrong password and then I go back and enter the right one however this leads to execution reverted and then after refreshing I just enter the right password and mint the key. 
https://www.loom.com/share/6479d6a08f7249c287e59226960784c5

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOS
 - Browser [e.g. chrome, safari]: Brave
 - Version [e.g. 22]: [Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (arm64)](https://brave.com/latest/)

**Additional context**

**Comment by julien51** [comment]
Thanks a lot for this detailed bug report!

**Comment by julien51** [comment]
Confirming that the 2nd bug has now been fixed on production and that new locks have been deployed to support the latest lock version! 
This means we can close this issue! Thanks a lot!
