### ISSUE TITLE
Red Envelope RPC error

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10775]
**Describe the bug**
The user attempted to send the mint with a wallet that didn't have enough MATIC (by accident), it showed the complete screen with an overlay that there wasn't enough to mint. When I added MATIC and tried again, it generated an "RPC" error. Maybe it thought this user had already minted an envelope and then generated the error. The user used a different wallet to successfully mint.

Error occurred on mobile. Successful mint occurred on desktop.

**Comment by julien51** [comment]
This has been fixed! We now show an error message when the user does not have Matic in their wallet and they can't click the button to send the transaction.
