### ISSUE TITLE
Create Checkout URL opens in a new tab

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10787]
**Is your feature request related to a problem? Please describe.**
When customizing a checkout URL, users stay in the same tab. This creates friction because once the Checkout URL is created and users return to their Lock page, the configured checkout isn't saved.

**Describe the solution you'd like**
Open a new tab to Create Checkout URL

**Describe alternatives you've considered**
Add a 'back' arrow on the Checkout Builder

**Comment by julien51** [comment]
I think the best approach here is to "save" configs. I think we can prioritize this.
