### ISSUE TITLE
Show key managers in member list

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10788]
<img width="728" alt="Screenshot 2023-01-20 at 11 33 03 AM" src="https://user-images.githubusercontent.com/17735/213752697-470f8e85-9a95-4228-a479-bb4992773ff3.png">
Once we have this we could also add a button for the lock manager to change the key manager for a given key.

**Comment by SouravInsights** [comment]
Do you wish to add the Key Manager like this: 👇 @julien51
![image](https://user-images.githubusercontent.com/26466468/218528078-0ebeb941-f2f8-4285-967c-091e5a58f1ff.png)

Also, I suppose I can query the `key manager` address from our [subgraph](https://api.thegraph.com/subgraphs/name/unlock-protocol/polygon-v2/graphql?query=%7B%0A++locks%28%0A++++first%3A+1%0A++++where%3A+%7B%0A++++++address%3A+%220xdf6c8253397cef13b190b397696816ebf744c2ff%22%0A++++%7D%0A++%29+%7B%0A++++address%0A++++name%0A++++totalKeys%0A++++keys+%7B%0A++++++owner%0A++++++manager%0A++++%7D%0A++%7D%0A%7D). So I tried this query below query but not sure why the `manager` field returns `null`. Is this the right way to query the key manager address? @julien51 @kalidiagne 

```{
  locks(
    first: 1
    where: {
      address: "0xdf6c8253397cef13b190b397696816ebf744c2ff"
    }
  ) {
    address
    name
    keys {
      owner
      manager
    }
  }
}
```

**Comment by julien51** [comment]
It is the right query! When the value is `null`, it means that the manager has not been set and that it defaults to the `onwer` :)

**Comment by julien51** [comment]
> Once we have this we could also add a button for the lock manager to change the key manager for a given key.

Please don't forget that part! This will require adding a small change to `unlockjs`!

**Comment by julien51** [comment]
@SouravInsights are you still working on this?

**Comment by kalidiagne** [comment]
> @SouravInsights are you still working on this?

@SouravInsights I take it on charge
