### ISSUE TITLE
purchaseKeys issue

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#10780]
find this issue with multiple`Cannot read properties of undefined (reading 'purchaseKeys")` (cant reproduce anymore)

need to be double checked to see where the issue come from!

<img width="747" alt="Screenshot 2023-01-19 at 20 43 22" src="https://user-images.githubusercontent.com/20865711/213550443-b32fd231-b27b-4c36-8e05-12d0cf8a3a16.png">

**Comment by searchableguy** [comment]
From investigating, it seems to be RPC related where it cannot fetch contract in the background. I'll continue to monitor but this isn't related to frontend.
