### ISSUE TITLE
Direct users to Lock, not Lock List after deploying a Lock

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10784]
**Is your feature request related to a problem? Please describe.**
After deploying a Lock, users are sent to the Lock List. After deploying a Lock, users likely want to manage their Lock, not see all Locks deployed.

**Describe the solution you'd like**
After deploying a Lock, users would be sent directly to the Lock deployed, not the Lock List.

**Comment by julien51** [comment]
Oh yes! I'll work on this!
