### ISSUE TITLE
Extensions are not actually triggering extensions

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10795]
I bought a [membership from a lock](0x66f1ce695128b3b5633eefed97636d075feb561717da896704682f4902b102f4).
Then [I canceled it](https://goerli.etherscan.io/tx/0x96ff0e21abcfd7569cefa9856f3d4b67f22cd5b7baebee568f33d0e879d26c3a).

Then I went to the keychain to extend it, but the keychain only prompted for an ERC20 approval when it should have *also* triggered a call on the contract to actually extend the key.

**Comment by julien51** [comment]
Note: checkout UI does offer to extend (which is expected)!

**Comment by julien51** [comment]
However, there is a 2nd bug! When I try to cancel again from the keychain it shows an error.

<img width="662" alt="Screenshot 2023-01-21 at 9 17 36 PM" src="https://user-images.githubusercontent.com/17735/213897632-ec1c0c81-1f9a-41b3-aa64-b724956e234f.png">

I know this is not correct because I am able to cancel from Etherscan =)

**Comment by searchableguy** [comment]
Regarding the extension, it actually works when I try it. It should be extending automatically if the key is expired from the data received on subgraph.

The only reason automatic extension would not trigger if there an approval but not actual balance to cover it. 

As for the cancel, I'm not sure. I did not touch that part.

**Comment by julien51** [comment]
>  It should be extending automatically if the key is expired from the data received on subgraph. It triggers after waiting for the approval to go through.

Not if the key was manually cancelled. The contract will prevent it!

**Comment by searchableguy** [comment]
As explained on discord. The transaction I linked was for an explicit extension. It gets triggered when key is expired. We fetch this expiration from subgraph. There was an inconsistency issue in subgraph for `cancelKeyEvent` which resulted in cancelled key appearing as valid in the keychain.

Opened a PR for the first bug.
