### ISSUE TITLE
Support full screen web browser

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1080]
When browsing in full screen, Firefox does not visibly open a popup with Metamask. The user has to click on the Metamask icon to actually approve the transaction (the Metamask icon will actually show a very small number overlay to indicate that something is expected but that's fairly hard to see!)

A solution to that issue is to actually show something like "Check your web3 provider" when a transaction is being initiated so that the user knows that something is expected from them.
We could either do that globally across the app (by applying a window wide lightbox which says "check your web3Provider" or something custom for each transaction but I think the first approach would be easier for now.

What do you think @smombartz ?

**Comment by cnasc** [comment]
If this issue only occurs in fullscreen mode, we can detect that the browser's inner height is the same as the screen height and only display the message then

**Comment by julien51** [comment]
@cnasc That's a good point. However I am thinking that even though this is only a big problem in full screen it may also be a nice to have on non full screen so users understand they need to look at that pop-up which just opened?

**Comment by cnasc** [comment]
That's definitely a fair point

**Comment by smombartz** [comment]
we have this view for the purchase card
![image](https://user-images.githubusercontent.com/1377389/51345795-dfcaaa00-1a69-11e9-87ea-ff0c7bd50454.png)

you can see the purchase card flow here (note design needs to be updated to include new purchase button layout)
https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=6%3A0

**Comment by julien51** [comment]
@smombartz I think we have not implemented this :( oups.

**Comment by julien51** [comment]
Also as much as this works for key purchases this does not work for all of the other types of transactions (I just was trying to see if withdrawing was working on locks but nothing happened when clicking on the button which caught me by surprise :/)

**Comment by smombartz** [comment]
@julien51 what are the other transaction types/actions we would need this for? lock creation, lock edit, lock withdrawal, key purchase?

**Comment by julien51** [comment]
All of them. Anything can be trigger on full screen and the user would not know that something is waiting for them in a new window/popup.

Please provide a design with a full page overlay? Thanks!

**Comment by cellog** [comment]
FYI, I run ff full-screen, and the window changes to a full-screen popup for metamask when I click to buy a key in my tests. Is this perhaps a per-user popup setting?

**Comment by smombartz** [comment]
updated purchase flow is here
https://www.figma.com/proto/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=0%3A825&viewport=675%2C24%2C0.240769&scaling=min-zoom

specs are here: https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=0%3A825

maybe we should discuss precise wording messaging for the different states.

**Comment by julien51** [comment]
@smombartz I insist because I think this is important that we have an "app-wide" mechanism for that.

**Comment by julien51** [comment]
@smombartz Status on this one please?

**Comment by smombartz** [comment]
here an overlay mockup. as much as @julien51, liked this i'm not a fan of overlays – but i haven't come up with a more convincing solution. happy to throw ideas around if anyone else is :)

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/52225934-a2438a80-2879-11e9-93e0-e0af469fe197.png)

## Specs
https://www.figma.com/proto/LkWSSnCGlKEITBB5T5NYXW/Paywall?node-id=179%3A0&viewport=1362%2C155%2C0.242144&scaling=min-zoom

**Comment by cnasc** [comment]
@smombartz how will this look on mobile?
