### ISSUE TITLE
Optimistic unlocking

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1081]
Purchasing keys takes a long time. On main-net, depending on gas prices we should not expect the key purchase to happen for 15 to 45 seconds at least (with high gas prices) and then if we wait for 12 confirmations, we're talking about about 10 minutes at least for the transaction to be confirmed and the key to be actually purchased.

I anticipate that this will be one of the most important pieces of feedback we'll get in the early days: key purchases need to be faster.

There are ways to deal with that at the chain level (probably via the use of state channels) but I worry that these solutions might add complexity to users *earlier*: they would be required to assign some funds to a channel and have these funds locked up for a little while.

Another approach would be to use some heuristics and just "trust" the users. What is the worst case after all? That a user reads a couple articles for a few minutes for free when they should have paid? (For now at least, they can easily do that by just disabling JS for example...).

So I am proposing that very quickly we proceed to some checks when the transaction is initialized and then immediately grant access to the users while we wait for the transaction to go through. We should of course keep track of the transaction and block access if it has not gone thru after say 15 minutes... (which should be enough even for low gas prices transaction?).

Example of the instant checks we could perform:
* Balance of the account when doing the transaction. If it less than the required price, the transaction will not go through.
* Gas price: with it we should be able to determine how long we might have to wait for the transaction to go thru. And the longer the wait the more risk that the transaction will nto go through (double spend). 
* Previous failed transactions: has the user performed key purchase transactions which failed?
... etc.

If we can pull this off, this is a very big win in terms of usability for a fairly small risk in terms of $.It'd be good go have everyone's opinion on this!

**Comment by julien51** [comment]
@cellog Could you update this status with the status/work remaining to be done on the front-end?

**Comment by cellog** [comment]
sure. Desktop implementation is 1 1-line PR away from done. The mobile implementation for wallets like coinbase wallet is not started yet. I'm not sure how much work that will be, it's a substantial re-design internally

**Comment by cellog** [comment]
Fully implemented!
