### ISSUE TITLE
Native currency token in the dropdown missing after changing to erc20 token

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10834]
**Describe the bug**
Currently, once you move to an erc20 token on the pricing. No native currency token appears anymore. There are duplicates of USDC or erc20 you set as the default. 

![image](https://user-images.githubusercontent.com/73341821/215161307-a07dc882-3fca-463a-b902-1efd25bf782a.png)

**Reproduction Steps**

1. Create a lock on goerli
2. Change currency to USDC
3. Try to change back to eth. You will find double USDC in the dropdown menu instead of eth.

**Comment by julien51** [comment]
<img width="510" alt="Screenshot 2023-01-31 at 10 42 11 AM" src="https://user-images.githubusercontent.com/17735/215806868-95180c49-67b9-43da-ae6d-07aa9c36c71b.png">
