### ISSUE TITLE
Receipt fixes

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10848]
Before we ship receipts we need to fix some things:

* [x] BUG: receipts for which the `receiptDetails` is not set are failing to load (see image 1 below)
* [x] `undefined` amount when keys have been granted. We need to show `0` in that case because nothing was paid (see image 2 below)
* [x] add link to block explorer on the transaction hash
* [x] show wallet address on the `Bill to` section (both when we have details and when we have not)
* [x] `Fullname` needs to be `Full name`.
* [x] Alignment is wrong in the receipt view (see image 3 below)

<img width="1089" alt="Screenshot 2023-01-30 at 5 05 54 PM" src="https://user-images.githubusercontent.com/17735/215606171-8488bfb1-4e55-4184-9b63-41e3911d7836.png">

![image](https://user-images.githubusercontent.com/17735/215604276-3ad0a3f5-2566-49ad-ba71-63dade50de3f.png)

![image](https://user-images.githubusercontent.com/17735/215604300-66f40725-a303-4f33-834a-4be5df0d9438.png)

**Comment by kalidiagne** [comment]
>  Alignment is wrong in the receipt view (see image 3 below)

Alignment is done in this way on purpose, in case the `service performed` text is too long, in order to avoid text overlaps 

<img width="498" alt="Screenshot 2023-01-31 at 10 36 07" src="https://user-images.githubusercontent.com/20865711/215723650-43febf6d-02f6-4d1d-b9b0-ca39ee4de9bf.png">
