### ISSUE TITLE
Can we get rid of the green line 

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1085]
I think the green line on our paywall application looks gross. 

I suggest we get rid of it and change the color of the gradient on the overlay to have something which slowly blends like this:
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/17735/51333782-78eac800-1a4c-11e9-995e-34f2431fb6cb.png">

cc @smombartz

**Comment by smombartz** [comment]
updated fade and purchase button
![image](https://user-images.githubusercontent.com/1377389/51343175-c0308300-1a63-11e9-98ea-7f5e9658c519.png)

specs are here
https://www.figma.com/proto/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=0%3A825&viewport=1269%2C738%2C0.355284&scaling=min-zoom

**Comment by julien51** [comment]
This is cool! Thanks @smombartz
