### ISSUE TITLE
Errors on Lock Manager page after deploying a Lock

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10860]
**Describe the bug**
After deploying a Lock on Polygon, creators are redirected automatically to a Lock Manager page. Upon arriving, they experience an error. 

**To Reproduce**
1. Deploy a Lock on Polygon
2. Redirect to Lock Manager Page
3. See errors. 

**Expected behavior**
The creator should be sent to a Lock Manager page without errors. 

**Screenshots**
[Loom](https://www.loom.com/share/c91caf5970914893bd124b17deaad379)

**Desktop (please complete the following information):**
 - OS: 11.6
 - Browser: Chrome

**Comment by kalidiagne** [comment]
fix here https://github.com/unlock-protocol/unlock/pull/10861
