### ISSUE TITLE
Purchase Button for Paywall Card

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#1090]
**Description**
When a user is served the paywall a card appears that indicates price of the key. The card is clickable but to make it more apparent we've added a Purchase button. The user can still click anywhere on the card to start the payment process

**Screenshot**
![image](https://user-images.githubusercontent.com/1377389/51345544-4ef3ce80-1a69-11e9-9309-4213e4fe29f8.png)

**Specs**
https://www.figma.com/proto/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=0%3A825&viewport=1269%2C738%2C0.355284&scaling=min-zoom

**Comment by julien51** [comment]
I think @cnasc Is already working on that in https://github.com/unlock-protocol/unlock/pull/1178, so re-assign to him ;)
