### ISSUE TITLE
Events not loading after adding an contract address

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10935]
**Describe the bug**
When I attempt to use Events (a good name BTW; better than 'don't call me Blockparty') by adding a contract address I've deployed to the URL , I get a 'not an event' error. When I attempt to 'Edit NFT Properties' I get a 'Unexpected Base Token URI error.

**To Reproduce**
1. Add a contract to the Events URL
2. Get a 'not an event' error

**Expected behavior**
Event details page should load information from the NFT properties edited through Membership Dashboard.

**Screenshots**
Attached
![Screen Shot 2023-02-01 at 10 12 10 AM](https://user-images.githubusercontent.com/32484647/216082745-924b8145-6e8b-4a09-9ee1-34982aab09cb.png)

**Comment by julien51** [comment]
@patrickworkman Please share thre URL + lock address if you can!

**Comment by patrickworkman** [comment]
[Contract](https://app.unlock-protocol.com/locks/lock?address=0xe1048c35222ccc902c73e095131fc125d106eff3&network=137)

**Comment by julien51** [comment]
<img width="841" alt="Screenshot 2023-02-01 at 11 55 39 AM" src="https://user-images.githubusercontent.com/17735/216109584-75aa4fb5-594f-4b9f-b618-79aa0d94508e.png">

So on that page I do not see the issue you're seeing? Can you double check and then lets have a call with screen share?
