### ISSUE TITLE
Add configuration for Discount Hooks in dashboard

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10936]
We currently let user enter custom addresses for hooks.
Let's add "pre-set" hooks here with a basis configuration for each of them.

First, we will update the network config to include a new object `hooks`. This object has multiple keys, one for each "type" of hook `onKeyPurchase`, ... etc. and the values are objects with a name "Password Required", "Discount Codes" as well as an address.

Here is an example:
```
export const mainnet: NetworkConfig = {
  id: 1,
...
  hooks: {
     onKeyPurchase: [{
            name: "Password Required",
            address: '0x...',
        }, {
            name: "Discount Codes",
            address: '0x...',
        }
     ]
}
```

Once added, we will replace the `input` fields with a select on the Hooks settings page for each type of hook. The Select should include the name of the hook (ex "Password Required"), as well as a way to enter a "Custom" address.

Based on the value selected, the UI will load a custom component for each hook. Let's first add a component for `Custom` which is simply an address field.

Then we should add a custom component for "Password Required". This component should include a field to enter a password and "save" it on the hook. Follow the instructions detailed on this repo https://github.com/unlock-protocol/password-required-hook

**Comment by julien51** [comment]
For now, users are only able to select a single hook contract per hook function.

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/11108

**Comment by julien51** [comment]
Once we have done the work for Password Hook, let's do it for Discount Code Hooks and Captcha Hook as well

**Comment by kalidiagne** [comment]
blocked by `Discount code` hooks

**Comment by julien51** [comment]
fixed! https://github.com/unlock-protocol/unlock/pull/13184
