### ISSUE TITLE
Paywall Embed missing Key Purchase Card

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#1093]
## Description
Paywall Key Purchase Card does not show up when logged out of metmask

## To Reproduce
http://projects.mombartz.com/unlock/

## Screenshots
<img width="1314" alt="screen shot 2019-01-17 at 15 15 00" src="https://user-images.githubusercontent.com/1377389/51346315-51efbe80-1a6b-11e9-8260-9076cc6c782d.png">

## Expected behavior
Should show error/instructions on wallet/metamask logout or network mismatch
[Mockup](https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=88%3A0)
<img width="992" alt="screen shot 2019-01-17 at 15 23 36" src="https://user-images.githubusercontent.com/1377389/51346530-e35f3080-1a6b-11e9-9dab-6f67f5919baf.png">

**Comment by cellog** [comment]
In order to quickly iterate on this bug, I need to somehow set up a local server that will load the paywall, because with the demo on staging, it won't load at all. I'll see if I can whip up the built-in apple webserver and serve some static html

**Comment by cellog** [comment]
ok I've got local repro working, now I can solve this sucker

**Comment by julien51** [comment]
oh, I think you can try [serve](https://www.npmjs.com/package/serve)?

**Comment by julien51** [comment]
Any update on that one @cellog ?

**Comment by cellog** [comment]
yes, last PR will be the next thing I code, should be before lunch

**Comment by cellog** [comment]
update: the code works, the styling is not there yet, so I'm going to push to after lunch.
