### ISSUE TITLE
Replace `endpointV2` with `endpoint` accross the apps

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10959]
Now that we are not using the `endpoint` anymore anywhere (I think). Let's just move back to it by removing `endpointV2`!

**Comment by searchableguy** [comment]
Would not recommend because that would break anyone who uses v2 endpoints. We can deprecate the old ones but not change the path.

**Comment by julien51** [comment]
ha! Good point. ok let's then only remove the `endpoint` across the networks to reduce confusion.
