### ISSUE TITLE
Unexpected Base Token URI error

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10961]
**Describe the bug**
When attempting to Edit NFT Properties, I get an 'Unexpected Base Token URI' error.

**To Reproduce**
1. Go to 'Edit NFT Properties'
2. See error

**Expected behavior**
Edit NFT Properties 

**Screenshots**
<img width="647" alt="Screen Shot 2023-02-03 at 1 22 48 PM" src="https://user-images.githubusercontent.com/32484647/216679261-c53fada1-a5ff-433e-ae8c-8388768443a4.png">

**Comment by julien51** [comment]
Please @patrickworkman Do post the URL of the page you're on when reporting issues :) We need to be able to reproduce!
