### ISSUE TITLE
Polygon listed first on Lock List directory page

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10968]
**Is your feature request related to a problem? Please describe.**
Polygon is the most used and recommended blockchain. We should list them first on the Lock List directory of the Membership Dashboard. 

**Describe the solution you'd like**
We should list Polygon first on the Lock List directory of the Membership Dashboard. 

**Describe alternatives you've considered**
We should list Polygon first and Mumbai second.

**Comment by julien51** [comment]
> Polygon is the most used and recommended blockchain. We should list them first on the Lock List directory of the Membership Dashboard.

I'll have to check but the order is actually based on speed of loading for the subgraphs, correct @kalidiagne ? So it's not really something we control that much.

**Comment by searchableguy** [comment]
I added a defaultNetwork parameter to config which I'm using for showing preferred network in select network options (We used to use user's network but no longer do). 

The order is not related to subgraph speed so can be changed. I would use the defaultNetwork parameter to highlight which network we want to put first so can be configurable in future.

**Comment by julien51** [comment]
Good idea @searchableguy ! Assigning this to you!
