### ISSUE TITLE
Verifier copy added to Events create flow

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11005]
**Is your feature request related to a problem? Please describe.**
 It needs to be clarified what organizers should do with the QR codes. Attendees receive a QR code, but there is no context 

**Describe the solution you'd like**
Add copy about Verifier in the create flow. This could be Edit NFT Properties > Event ticketing or on the event details page viewed by the lock manager. 

**Describe alternatives you've considered**
Create a dedicated guide for Verifier and link to it from Edit NFT Properties > Event ticketing or on the event details page

**Comment by julien51** [comment]
@kalidiagne added this a few weeks ago!
<img width="700" alt="Screenshot 2023-03-29 at 4 52 10 PM" src="https://user-images.githubusercontent.com/17735/228664480-e5cb9513-f2b7-4f3f-b163-30e0b958eeee.png">
