### ISSUE TITLE
Preview and meta HTML tags on event details pages

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11010]
**Is your feature request related to a problem? Please describe.**
Event platforms (Eventbrite, Partiful) include preview and meta HTML tags on their event details pages. They do this so apps can generate previews. 

**Describe the solution you'd like**
Add preview and meta HTML tags on event details pages

**Comment by searchableguy** [comment]
This is an existing issue https://github.com/unlock-protocol/unlock/issues/10268

Closing this one. We will have it soon.
