### ISSUE TITLE
Embed links in the event description on Events

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11017]
**Is your feature request related to a problem? Please describe.**
Organizers would like to embed links in the event description so people can join discords, follow twitters, check out homepages, etc.

**Describe the solution you'd like**
Enable the ability to embed links in the event description.

**Describe alternatives you've considered**
Enable fields organizers can use to add URLs (similar to how they can add metadata in Checkout Builder).

**Comment by julien51** [comment]
It's already fully supported via Markddown.
