### ISSUE TITLE
Allowing lock managers to use saved checkout URL for their events

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11019]
**Is your feature request related to a problem? Please describe.**
Often, organizers don't want their events to be open to everyone. For this they may set a hook on their locks but right now we don't have easy way for them to point to a specific checkout URL.

**Describe the solution you'd like**
Allow lock managers to use a saved checkout URL for their events.

**Comment by julien51** [comment]
That's a bit harder to do and requires us to work on 3 things
* simpler UI to set passwords in Dashboard directly (@kalidiagne will work on this shortly)
* Saving config from checkout URL

**Comment by julien51** [comment]
Now that we have a way to save checkout URLs in the config, let's let the lock manager select one of their saved checkout URL in the lock's config so that we use it.
We should add this to the events detail page.
