### ISSUE TITLE
Add "slug" to the metadata on locks so we can use this for certification and events

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11014]
It should not be exposed as part of the NFT metadata but this way we can use "nice" paths on the events page.
Since we do not have server-side routing it will need to use the the `/#/<slug>` syntax so we have `https://app.unlock-protocol.com/event/#/<slug>` for event, and similar for certification... etc

**Comment by kalidiagne** [comment]
Done with https://github.com/unlock-protocol/unlock/pull/11699 https://github.com/unlock-protocol/unlock/pull/11700
