### ISSUE TITLE
Multiple issues with the AddressInput component

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11029]
There are many issues with the `AddressInout` component. We need to fix these ASAP or revert it completely.

1. [x] It is missing stories in Storybook. Please add them
2. [x] The "default" state when shown in the form to add lock manager is an error state which is not right
3. [x] When entering any value it gets stuck and makes the web page unusable on the "Add Manager" UI.
4. [x] It is not used on the Verifier form (and it should be)
5. [x] It is not used on the airdrop form (and it should be) for both the recipient field and the key manager field.
6. [x] It is not used on the Checkout builder for the `Referrer` field (and it should be).
7. [x] It shows that the ENS is not valid even when it is valid (and it has actually been able to resolve it)
8. [x] When the ENS or address is valid there is no need to show a message
9. [x] When the ENS is valid, show the full address below so the user can still compare.

<img width="582" alt="Screenshot 2023-02-13 at 10 23 06 PM" src="https://user-images.githubusercontent.com/17735/218631071-26300e4b-eb0f-4e2a-b40b-9ca6698913d6.png">

**Comment by kalidiagne** [comment]
> @kalidiagne any update on the last item here?

`AddressInput` added with this PR https://github.com/unlock-protocol/unlock/pull/11240, closing because all point are done
