### ISSUE TITLE
We should add a helper for testing transactions which should fail.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#1106]
**Is your feature request related to a problem? Please describe.**
Something that was brought up recently by @hardlydifficult was the use of tests such as this example below. The observation he made was:

"This test will not fail if it did not revert, as expected. It will only fail if it reverts for the wrong reason."
### The test:
```
it('should fail if called by address other than owner', () => {
  assert.notEqual(owner, accounts[1]) // Making sure
  return locks['OWNED'].partialWithdraw(withdrawalAmount, {
    from: accounts[1]
  }).catch(error => {
    assert.equal(error.message, 'VM Exception while processing transaction: revert')
  })
})
```

**Describe the solution you'd like**
The suggestion was to create a helper function to be reused in all cases like this where a failing transaction means a passing test. It should work correctly on bothe Ganache and Geth.

**Describe alternatives you've considered**
 
- https://gist.github.com/xavierlepretre/d5583222fde52ddfbc58b7cfa0d2d0a9
  I've used this option before in school.
- openzeppelin has a helper in `/test/helpers/expectThrow.js`

**Comment by hardlydifficult** [comment]
I really like open-zeppelin's approach: https://github.com/OpenZeppelin/openzeppelin-eth/blob/master/test/helpers/expectThrow.js

Good find, are you okay using this one?

**Comment by nfurfaro** [comment]
Sure, we'll give it it try and see how it works for us. There's some talk on [this](https://ethereum.stackexchange.com/questions/9103/how-can-you-handle-an-expected-throw-in-a-contract-test-using-truffle-and-ethere) thread about it not working in Geth, but a truffle dev says it should 
"Truffle dev here - this should work w/ geth & parity as long as you're using the latest version of truffle-contract. If it doesn't, please raise an issue! – Ben Burns Nov 6 '18 at 20:03 "
