### ISSUE TITLE
Robustness principle for referrer

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11162]
If the `referrer` in the checkout URL is empty, we should just ignore it.
[Example with this checkout URL](https://app.unlock-protocol.com/checkout?paywallConfig=%7B%22locks%22%3A%7B%220x4a4446eda1a6cbb592e8d999b957e6205a917e54%22%3A%7B%22network%22%3A137%2C%22skipRecipient%22%3Atrue%7D%2C%220x7c63a8b93cabb508c6e628a4502ea82aefb3791c%22%3A%7B%22network%22%3A137%2C%22name%22%3A%22Club+DeFi+Mensual%22%7D%7D%2C%22pessimistic%22%3Atrue%2C%22skipRecipient%22%3Atrue%2C%22title%22%3A%22Club+DeFi%22%2C%22icon%22%3A%22https%3A%2F%2Fi.postimg.cc%2FPqV26gXx%2FLoguitillo-PNG.png%22%2C%22redirectUri%22%3A%22https%3A%2F%2Fdiscord.gg%2F73BrRwH8%22%2C%22persistentCheckout%22%3Afalse%2C%22referrer%22%3A%22%22%2C%22messageToSign%22%3A%22%22%2C%22hideSoldOut%22%3Afalse%7D).

**Comment by searchableguy** [comment]
We actually do ignore it, I believe. 

The issue is a contract bug which when set to `0x` address, it will error.

**Comment by julien51** [comment]
We should not pass `0x0` anyway...

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/11226
