### ISSUE TITLE
Show that there is no key on a lock?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1117]
When a lock is created, there are no key at first... I believe we should show a message indicating that, rather than leave the space empty (which introduces a doubt?).

<img width="1753" alt="image" src="https://user-images.githubusercontent.com/17735/51393261-4650d600-1b05-11e9-8ab0-3a804eded02c.png">

cc @smombartz

**Comment by cnasc** [comment]
This is simple enough to handle, just returning early from `render` in KeyList. Any opinions on how the message should be worded?

**Comment by smombartz** [comment]
![image](https://user-images.githubusercontent.com/1377389/51408228-03eebf80-1b2c-11e9-9513-b6068eec8123.png)

specs are here: https://www.figma.com/file/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-Dashboard?node-id=0%3A2

**Comment by cnasc** [comment]
Looks great, do you think we should hide the table header since there are no fields relating to it?
