### ISSUE TITLE
Move "execution" logic from paywall to paywall-app

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11224]
Our Paywall package does a bit too much :) 
Immediately after being loaded it instantiates a [new Paywall object](https://github.com/unlock-protocol/unlock/blob/master/packages/paywall/src/index.ts).

We should not do that as part of the paywall package but as part of the paywall-app and make sure this part happens in the javascript `unlock.latest.min.js` file.

The package itself should just export the `Paywall` object which can then be instantiated by any application.

**Comment by julien51** [comment]
@clemsos Any status update on that?

**Comment by clemsos** [comment]
> @clemsos Any status update on that?

Yes status update is in the PR https://github.com/unlock-protocol/unlock/pull/11237
