### ISSUE TITLE
Performance optimization for members page

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#11231]
Let's load all members at once and do search on the client side instead of using the API using fuse. 

Use react query to cache the members for a small period and do background refreshes and build index.

**Comment by julien51** [comment]
> Let's load all members at once and do search on the client side instead of using the API using fuse.

that would not scale well for multiple reasons:
1. subgraphs are limited to 1000 objects so that would not work for any lock > 1,000 members
2. we need to combine the keys + metadata and this would probably create a mess on the backend with large locks..
