### ISSUE TITLE
Link to QR ticket/Keychain in Event Invite

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11274]
**Is your feature request related to a problem? Please describe.**
After registering for an Event, users need to search their email inboxes for their membership to find their ticket and event information. Event information is only available in the email if organizers have added copy to the email through Membership Dashboard. 

**Describe the solution you'd like**
If we're able to add Events to user's calendars (ie [Luma's Event Registration Process](https://help.lu.ma/en/articles/5104669-event-registration-process)), the invite should include a link to the user's QR Code ticket or Keychain to optimize IRL redemption/check-in. 

**Describe alternatives you've considered**
The email received after registering could be the QR ticket vs copy from Unlock Labs.

**Comment by julien51** [comment]
We now have a custom "event" email that includes the ticket (+QR code) and can be easily findable (it has the lock name in it) + a link to the keychain!
