### ISSUE TITLE
Ethpass notifications

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11273]
**Is your feature request related to a problem? Please describe.**
After users claim/buy a membership to an Event and add it to their Apple or Google wallet, they aren't prompted when or how to use the pass. 

**Describe the solution you'd like**
Enable iOS/Android notifications from ethpass so users are aware of the pass in their wallet and receive a reminder when their event will start. This functionality is native to ethpass.

**Comment by julien51** [comment]
Ha! That is something that I am not sure we have any control over?
