### ISSUE TITLE
Burned NFT still showing on the subgraph

### ISSUE THREAD

**Issue by PJijin** [unlock-protocol/unlock#11282]
**Describe the bug**
After burning an NFT on the Polygon Mumbai network, I noticed that it is still being displayed on the subgraph.

Transaction: https://mumbai.polygonscan.com/tx/0x089b8dd56d6d8a1d31d49a857aa0873bbe31f4821a7cf752adbbb4f095a5fef4

Subgraph: https://api.thegraph.com/subgraphs/name/unlock-protocol/mumbai-v2/graphql?query=query+%7B%0A%09%09keys%28%0A%09%09%09where%3A+%7B%0A%09%09%09%09and%3A+%5B%0A%09%09%09%09%09%7B+owner%3A+%220xf1996154c34e3dc77b26437a102231785e9ad7fe%22+%7D%0A%09%09%09%09%09%7B+lock%3A+%220xef24dacc7b5bd579c71f006a8c9d24330d99f37c%22+%7D%0A%09%09%09%09%5D%0A%09%09%09%7D%0A%09%09%29+%7B%0A%09%09%09tokenId%0A++++%09expiration%0A++++%09cancelled%0A++++lock%7B%0A++++++price%0A++++%7D%0A%09%09%7D%0A%09%7D

**To Reproduce**
1. Burn an NFT
2. Query it using the subgraph

**Expected behavior**
It should remove the burned nft from the keys list.

**Comment by julien51** [comment]
@clemsos Is that something you could look into please?

**Comment by clemsos** [comment]
Thanks @PJijin for filing the issue, I'll look inot it

**Comment by PJijin** [comment]
Hey @clemsos 

Does it take time to reflect the change. 

I have tried to burn and NFT few min ago and tried to query it using the subgraph. it is still showing the burned nft in that list.

**Comment by clemsos** [comment]
Hey ! Yes we need to do a prod redeploy of our subgraphs for all chains first for the changes to propagate. We will trigger that to push a bunch of other changes live at the same time. Then it takes a few hours for the subgraph to reindex everything.

> Hey @clemsos
> 
> Does it take time to reflect the change.
> 
> I have tried to burn and NFT few min ago and tried to query it using the subgraph. it is still showing the burned nft in that list.
