### ISSUE TITLE
Events - Copy edits

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11320]
**Describe the bug**
Under Ticketing Events with Unlock is Simple, the copy should read:
**No-code smart contract deployment**
_Fill out a form and hit the deploy button. All the metadata information will automatically be included in the NFT tickets. You can always add and modify other properties at a later date._

**QR codes and proof of purchase ticketing**
_The easiest way to authenticate tickets. Once attendees purchase a ticket, they receive an email and a QR code to check in at the venue._

**Check-ins at the venue are a breeze**
_Volunteers or door staff can check attendees in with smartphones and ensure tickets aren’t transferred or reused once someone has entered the door._

**To Reproduce**
1. Go to Events
2. Scroll down to Ticketing Events with Unlock is Simple
3. Update copy
<img width="676" alt="Screen Shot 2023-03-14 at 9 02 51 AM" src="https://user-images.githubusercontent.com/32484647/225009226-a6639394-f1a0-46d0-90e4-b6bde18fc580.png">

**Comment by julien51** [comment]
cc @ccarfi

**Comment by ccarfi** [comment]
these copy changes look fine. 

that said, not sure of the potential impact — these seem to be minor wording changes in the descriptive copy?
