### ISSUE TITLE
Multiple Check-Ins for a QR Code

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11321]
**Is your feature request related to a problem? Please describe.**
When memberships are redeemed IRL using Verifier, the QR code is only valid for a single use. Many creators (I.e., a club or gallery) want their members to attend multiple IRL events.

**Describe the solution you'd like**
Enable multiple check-ins for a QR code. This could be managed through Settings > Membership Terms > Redemptions, allowing creators to choose how many redemptions a single QR code represents (one - unlimited) for the duration of Membership. 

**Describe alternatives you've considered**
Enable creators to 'reset' check-ins after an event. This could be managed in Settings > Roles > Verifier with a 'Reset check-ins' toggle.

**Comment by julien51** [comment]
This has now been implemented!
