### ISSUE TITLE
refactoring ShowUnlessUserHasAnyKeys to simplify and allow other use cases

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1134]
`ShowUnlessUserHasKeyToAnyValidLock` is currently doing too much. It has at least 3 possible components in it:

1. displays something if the user hasn't purchased a lock (a `ShowWhenLocked` component)
2. displays something if the user has purchased a lock (a `ShowWhenUnlocked` component - currently not possible without some weird code duplication)
3. something that communicates with the iframe using messaging (an `IframeService` component)

Logic duplication can be avoided through centralizing it in the `mapStateToProps` of the paywall component itself, and generating the `locks`, `keys` and `modalShown` props there. The `keys` and `modalShown` props can then be easily passed down into child components `IframeService` and the `ShowWhen*` components, and `locks` can be passed into the `Overlay` component.

This question needs to be resolved to properly implement #980 as there is currently no component that displays something if the paywall is unlocked.

**Comment by cellog** [comment]
is this design OK?

**Comment by cellog** [comment]
needed for #980 which is a p-2, changing to p-2 for that reason

**Comment by cnasc** [comment]
I believe we can close this now that #1319 has landed

**Comment by cellog** [comment]
Yes! well done @cnasc
