### ISSUE TITLE
Webflow plugin {this is not real}

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11386]
Listed below is the suggested information you should include. The more information you give, the better the community will understand your grant request.

## The plugin for Webflow!

I want to build something cool
## Contact Name

Your name

## Email

Your email address

## City

Your city

## Project Description

A description of the proposed grant project

## Website URL

Your project's URL

## Discord Handle

Your Discord hanlde

## Social Profiles

Social profile URLs (e.g. Twitter, etc.)

## Pitch Deck

If you have a detailed pitch deck, please provide a link or attach as a comment in the discussion of this proposal

## What dev languages or frameworks will you use?

Development languages that will be used

## Is this project open source?

* [ ] Yes

## What is your estimated timeframe for this project?

How long you believe development will take

## Project team information including size and team profiles

Profiles or links to profiles of key team members

## How did you hear about Unlock Protocol?

How'd you learn about Unlock?

## Provide two or three measurable milestones for periodic review (please include both measurable goal and expected timeframe to reach the goal

1.
2.
3.

## Anything else you think we should know

Feel free to include any other relevant information about your grant proposal here

**Comment by julien51** [comment]
This owuld be a great plugin...

**Comment by ccarfi** [comment]
here is another comment
