### ISSUE TITLE
test issue - ignore

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#11423]
### Description

this is a box of copy with an image 
<img width="316" alt="Screen Shot 2023-03-30 at 5 48 55 AM" src="https://user-images.githubusercontent.com/214760/228841241-4cede598-5c65-440f-9cc2-37ebff3498a1.png">
[Coinvise Grant Completion.pdf](https://github.com/unlock-protocol/unlock/files/11111708/Coinvise.Grant.Completion.pdf)

### Website URL

https://example.com

### Twitter

@example

### Github

https://github.com/example

### LinkedIn

https://linkedin.com/in/example

### Discord handle

example#1234

### Completion time

4 mos

### Team

team previes

### Milestones

things we'll do

### Anything else you think we should know

other items

### Is your work Open Source

No, my project does not use an Open Source license

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ccarfi** [comment]
this is a comment on the application

**Comment by julien51** [comment]
@ccarfi Cool to close now? Please re-open if you need :)
