### ISSUE TITLE
Consider adding a jsconfig.json file to the root of unlock-app

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1145]
**Describe the solution you'd like**
Adding a `jsconfig.json` to the root of `unlock-app` can improve some tooling, as seen here: https://code.visualstudio.com/docs/languages/jsconfig

This would benefit users of VSCode, and (selfishly) the Tide plugin for Emacs that I use.

**Comment by julien51** [comment]
I think this will be required by TypeScript if we adopt it? 
Let's keep track of this issue in [that context](https://github.com/unlock-protocol/unlock/issues/1449) then.
