### ISSUE TITLE
Ghost Plugin for Unlock Protocol

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#11514]
### Description

I've spent some time going through the Ghost documentation and found the best way to integrate Unlock to allow maximum flexibility and adoption would be to create a Ghost-Unlock theme since the Ghost admin client is an app and can't be modified. https://forum.ghost.org/t/custom-plugin-in-ghost-admin-panel/13190

### Website URL

https://github.com/blahkheart/ghost-unlock-theme

### Twitter

https://twitter.com/dannithomx

### Github

https://github.com/blahkheart/ghost-unlock-theme

### Discord handle

blahkheart#8618

### Completion time

3 months

### Team

danni thomx // @blahkheart

### Milestones

- Create public repository
- Create authentication API
- Create membership API
- Creator settings page where the creator can update their lock settings
- End-user functionality for showing and hiding locked content
- Deploy theme

### Requested grant amount

200 UDT

### Anything else you think we should know, including why you've requested a particular grant amount

Developing in Nodejs, JavaScript, HandlebarsJs

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ccarfi** [comment]
Work-in-progress video:
https://drive.google.com/file/d/18MjG2jMBTCyatZT_qPoPXnyHxHIO-hyH/view

**Comment by julien51** [comment]
@blahkheart please add a comment so we can assign this to you formally :) (github lets us only assign people who have commented!)

**Comment by blahkheart** [comment]
Okay, thanks @julien51 Making great progress and will have some more visuals to share next week.

**Comment by ccarfi** [comment]
@blahkheart right on — please drop any updates here as they are coming through. can't wait to see them!

**Comment by blahkheart** [comment]
Here's a link to the latest updates on the integration: https://drive.google.com/file/d/1DV9E9VLaCK0oUE8zkWAGTaarQnixbX5z/view?usp=sharing

**Comment by ccarfi** [comment]
> Here's a link to the latest updates on the integration: https://drive.google.com/file/d/1DV9E9VLaCK0oUE8zkWAGTaarQnixbX5z/view?usp=sharing

@blahkheart thank you for sharing the updates here! folks, check it out.

**Comment by blahkheart** [comment]
Here's a link to the latest updates on the integration: members can now subscribe to a plan(lock) from the blog.
https://drive.google.com/file/d/1OOrX1meE7vmYIwZCu-WyZwznMthbYHtY/view?usp=sharing

**Comment by blahkheart** [comment]
The Milestones have been completed and an MVP is ready. Here's the link to a video of the MVP, which basically goes over the usage flow from start to finish.
https://www.youtube.com/watch?v=Cd0VCCT2ul4&feature=youtu.be

**Comment by ccarfi** [comment]
> The Milestones have been completed and an MVP is ready. Here's the link to a video of the MVP, which basically goes over the usage flow from start to finish. https://www.youtube.com/watch?v=Cd0VCCT2ul4&feature=youtu.be

Nice!

**Comment by ccarfi** [comment]
Can also check out a live demo at https://p2einferno.xyz/

**Comment by julien51** [comment]
Hey @blahkheart I am trying to go thru the demo link as posted by @ccarfi but for some reason I am unable to login on the website after getting the email in my inbox.
<img width="1453" alt="Screenshot 2023-08-01 at 11 14 36 AM" src="https://github.com/unlock-protocol/unlock/assets/17735/74bdb52a-f105-48d8-8297-3de348d5ed01">


It looks like a certificate error.

Also, do you have docs for creators (beyond the video) that we could point users to?

**Comment by blahkheart** [comment]
Hey @julien51 the issue has been fixed, please delete the previous email and try again.

**Comment by blahkheart** [comment]
As of right now the [README.md ](https://github.com/blahkheart/ghost-unlock-theme/blob/master/README.md) exists as a guide to help creators get started with the theme. The official [ghost documentation](https://ghost.org/docs/) also provides extensive guides and tutorials on how to set up a ghost publication. However, if you have other ideas in mind I'd be happy to hear it.

**Comment by julien51** [comment]
I want thru the flow as a "subscriber" and it is pretty good! Goog job!

**Comment by blahkheart** [comment]
Great! If you run into any issues or have any questions regarding the "creator" flow, let me know

**Comment by blahkheart** [comment]
Here's my address: 0xE11Cd5244DE68D90755a1d142Ab446A4D17cDC10

**Comment by julien51** [comment]
The grant has now been paid! https://polygonscan.com/tx/0xfb529aeb27c9767869f6c12d598302983ed0bd2a2fe5bdb2779cd43c95ff0c87 Thanks @blahkheart !
