### ISSUE TITLE
Redeploy previous lock templates on testnets

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#11529]
All PublicLock versions prior to 10 were deployed for testing on Rinkeby - which is no longer active. We should redeploy older versions of unlock on Goerli to be able to create legacy versions of locks for testing purposes.

```
Deploying PublicLock v9 from contracts package
PUBLIC LOCK > Deploying lock template on Goerli (Testnet) for released version 9 with signer 0x81a662065d5c83Fa9c5C12d0dc0104dF57f85A12
PUBLIC LOCK > deployed v9 to : 0xD8da9c1b03b637C829Bcd75CE94c80212b9a9A83 (tx: 0x399cb47f18cd3db7d6665c4b92b6f1eb2b1c5751f83edfe3e9dfc8a1f562bd8c)
```

**Comment by julien51** [comment]
Great idea!

**Comment by julien51** [comment]
Ha but you _really_ did it :D https://goerli.etherscan.io/tx/0x399cb47f18cd3db7d6665c4b92b6f1eb2b1c5751f83edfe3e9dfc8a1f562bd8c

**Comment by clemsos** [comment]
> Ha but you _really_ did it :D https://goerli.etherscan.io/tx/0x399cb47f18cd3db7d6665c4b92b6f1eb2b1c5751f83edfe3e9dfc8a1f562bd8c

yes but verification failed!

**Comment by clemsos** [comment]
again that should move to Sepolia

**Comment by julien51** [comment]
Maybe the Health check should check that all supported versions are deployed for every Unlock on every chain?
