### ISSUE TITLE
We are testing against Goerli... and this is not right

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11522]
Some unlockjs tests are apparently running againt Goerli. This is dangerous because it breaks our tests when something is wrong on goerli.

We should **never** test against any external data source (chain, subgraphs... etc)

**Comment by julien51** [comment]
Example of failed jobs because of this https://github.com/unlock-protocol/unlock/actions/runs/4602690240/jobs/8131935944

**Comment by clemsos** [comment]
It seems to be here https://github.com/unlock-protocol/unlock/blob/de0df50c28bb0864f31859aa59c2a30a20374986/packages/unlock-js/src/__tests__/web3Service.test.js#L8

**Comment by clemsos** [comment]
That may start to fail when goerli gets deprec

**Comment by clemsos** [comment]
Subgraph get its introspection file from Goerli too

**Comment by clemsos** [comment]
we are now testing against Optimism https://github.com/unlock-protocol/unlock/pull/13540

**Comment by clemsos** [comment]
> Subgraph get its introspection file from Goerli too

This was changed to mainnet a while ago
