### ISSUE TITLE
Events: Seconds not needed for start/end times

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11536]
**Describe the bug**
Event detail pages show hour/minute/second for start and end times. Seconds aren't necessary. 

**To Reproduce**
1. Go to any EDP
2. Look at Start and End times

**Expected behavior**
Time should be formatted in hours:minutes not hours:minutes:seconds

**Screenshots**
<img width="517" alt="Screen Shot 2023-04-04 at 9 47 23 PM" src="https://user-images.githubusercontent.com/32484647/229960324-a980bd2c-c993-45c5-a5a6-9a651ae1065a.png">

**Comment by julien51** [comment]
good catch! cc @kalidiagne
