### ISSUE TITLE
Paywall does not launch on Brave

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1154]
**Describe the bug**
Paywall does not render when using Brave browser.

**To Reproduce**
1. Use Brave browser with Metamask installed and logged in.
2. Go to a page that has a lock that you do not have a key for.
3. Note that no paywall appears.

**Expected behavior**
A paywall will appear that prevents me from scrolling/using the page and provides the opportunity to purchase a key that will grant me access.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser Brave 0.58.21

**Additional context**
Error console:
<img width="557" alt="screen shot 2019-01-22 at 12 38 54 pm" src="https://user-images.githubusercontent.com/9300702/51554660-cba8f300-1e43-11e9-8f8e-e8e259310f82.png">

The app dies when localStorage access fails. @cellog pointed out that there is no use of localStorage in the unlock-app codebase and that it may be something in node_modules trying to use it.

**Comment by nfurfaro** [comment]
@cnasc I think this is working for me. Will update, but currently at 7 confirmations.
![image](https://user-images.githubusercontent.com/17053076/51558921-deb8c480-1e3d-11e9-87de-a41aa45b9b3c.png)

**Comment by nfurfaro** [comment]
So, this works for me on Rinkeby on a lock I created. I don't see a paywall on Sascha's page...

**Comment by julien51** [comment]
Moving to p2 as this is maybe not as critical now that Brave is not special anymore? (no web3 provider in in by default)

**Comment by akeem** [comment]
This appears to be related to a chromium security setting, https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document . With this noted, i'll see how this can be resolved

**Comment by akeem** [comment]
https://github.com/ethereum/web3.js/pull/2203 should resolve this issue, there will be an increase in scope as we will need to accommodate for additional changes introduced to web3

**Comment by akeem** [comment]
At the moment, this is consider blocked until we can upgrade unlock-app to 1.0.0.beta41

**Comment by akeem** [comment]
This is still pending an upgrade to a recent version of web3. It should be picked up after the work I currently have in play

**Comment by julien51** [comment]
We're waiting for a new deploy to production to check this but it should be fixed.

**Comment by cellog** [comment]
this is fixed on the desktop version of brave, broken on mobile (#2366)
