### ISSUE TITLE
Dripps Universe

### ISSUE THREAD

**Issue by exstalis** [unlock-protocol/unlock#11544]
### Description

**Project Name:** Dripps
**Description:** Dripps is a social community hub for more inclusive and secure IRL engagements
**Vision:** My vision with Dripps is to build a safer platform with global reach, where anyone can organize and participate in gatherings, no matter where they live in the world. Using blockchain technology, we plan to continue improving event security, privacy, and transparency for all involved.
**Problem:** One of the biggest reasons I want to bring the Dripps project to life is that I want to make IRL engagements a safer and more inclusive ecosystem for everyone, especially women.
### Solution/Product: 
**Phase 1:** We believe that integrating NFTs with our platform will offer even greater value to our users by providing a seamless and secure event management experience in Web3. The NFT membership will grant access to the platform, events, and communication channels.
**Phase 2:** Building on the success of Phase 1, our next focus is on expanding the onboarding strategy to smoothly transition Web2 users to Web3. We aim to create a user-friendly experience that allows Web2 users to easily opt-in and become part of the Web3 community on Dripps.

The UX flow will be designed to be seamless and intuitive, guiding users through the process step-by-step. We will provide clear instructions and resources to educate users about the benefits of Web3 and the advantages of being part of the Dripps community in the blockchain ecosystem.

Web2 users will have the option to connect their existing accounts to a Web3 wallet within the Dripps platform. This will enable them to take advantage of the enhanced features and benefits of Web3, such as NFT ownership, secure transactions, and decentralized governance.

We will also provide comprehensive support, including FAQs, tutorials, and customer service, to ensure that the onboarding process is as smooth as possible for all users. Our goal is to make the transition from Web2 to Web3 seamless, user-friendly, and accessible to all, while empowering users to fully participate in the Dripps community and the broader blockchain ecosystem.

**Phase 3:** Community Accounts

Building on the success of Phase 1 and Phase 2, our next focus is on introducing Community Accounts as a key feature of Dripps. Community Accounts will allow communities to have their own dedicated accounts within the platform, with enhanced features and functionalities that cater specifically to their needs.

Community Accounts will provide communities with a streamlined and customizable experience, allowing them to create their own unique profiles, manage their events and gatherings, and interact with their members in a more personalized and engaging way. Community leaders will have access to powerful tools and analytics to better understand and serve their members, enabling them to create a thriving and vibrant community on Dripps.

One of the key benefits of Community Accounts is the ability to create and manage NFT-based memberships for their communities. Community leaders can create exclusive NFTs that represent membership to their community, providing additional perks, benefits, and privileges to members. These NFT-based memberships can be bought, sold, and traded within the Dripps marketplace, creating a dynamic and vibrant economy within the platform.

Additionally, Community Accounts will have access to decentralized governance features, allowing community leaders and members to actively participate in the decision-making process of the Dripps platform. This will empower communities to have a direct say in the direction and development of the platform, fostering a sense of ownership and engagement among the community members.

For more information regarding milestones, roadmap and proposal please review the attached document.
[Dripps Proposal [Draft]- Unlock.pdf](https://github.com/unlock-protocol/unlock/files/11160435/Dripps.Proposal.Draft.-.Unlock.pdf)

### Website URL

https://dripps.io

### Twitter

@drippsuniverse

### Github

https://github.com/Dripps-Universe

### Discord handle

exstalis#9505

### Completion time

5 months

### Team

Founder: Elif Ece Arslan
Freelance Contractors:
Front End Developer: Kaseem Dodson
Technical Support: Cameron Dimitroff
Legal Support: Sean (Coinflask)

### Milestone 1: Product Development

Develop the NFT event ticketing, check-in, and proof of attendance integration with Unlock Protocol by deploying smart contracts and integrating with the Unlock Protocol API.
Establish a system for the minting of unique NFTs representing events that can be sold as tickets or value adds using Polygon network.
Test the integration with a small group of users to ensure that it meets the requirements and expectations of organizers and attendees.
Launch the NFT event ticketing, check-in, and proof of attendance integration on the Dripps platform. Ensure the seamless integration to provide greater security and privacy for users.

### Technical stack for Milestone 1:

Solidity for developing smart contracts for NFT event ticketing, check-in, and proof of attendance integration on the Polygon network.
Hardhat for deploying and testing smart contracts on the Polygon network.
Web3.js for interacting with smart contracts from the front-end.
Unlock Protocol API for integrating with the platform to enable NFT event ticketing, check-in, and proof of attendance.
IPFS for storing event data and NFT metadata in a decentralized manner. (e.g., Pinata)

### Milestone 2: Launch and Marketing

Develop a marketing and promotional strategy to raise awareness about the NFT event ticketing, check-in, and proof of attendance integration with Unlock Protocol.
Launch a social media campaign to promote the integration and generate interest among potential users.
Collaborate with other Web3 organizations to promote Dripps, via a referral program, to incentivize users to join the platform.
Host a series of events to educate users on the benefits of the integration and how to use the platform effectively.
Achieve the target of 500 NFT membership subscriptions minted by Fall 2023 and report on progress regularly to demonstrate the impact of the partnership.

By achieving these milestones and using the above technical stack, Dripps can successfully launch an NFT event ticketing, check-in, and proof of attendance integration with Unlock Protocol on the Polygon network. The integration would provide greater security, privacy, and cost-effectiveness for organizers and attendees while also offering a unique and innovative value proposition to users. By focusing on the development of the NFT integration and the necessary infrastructure, as well as marketing and promotional activities, Dripps can establish itself as a leader in the event management space in web3.

### Requested grant amount

300 UDT

### Information about the founder:
**Website:** https://exstalis.space
**Twitter:** https://twitter.com/exstalis

### Dripps Additional Documents

**Pitch Deck:**
[dripps_pitchdeck.pdf](https://github.com/unlock-protocol/unlock/files/11160471/dripps_pitchdeck.pdf)
[brand [Recovered].pdf](https://github.com/unlock-protocol/unlock/files/11160489/brand.Recovered.pdf)
![Dripps mind map - Dripps Roadmap (1)](https://user-images.githubusercontent.com/3525956/230130365-293c472f-f051-4eb9-8290-e88f5af20736.jpg)
[Dripps mind map (1).pdf](https://github.com/unlock-protocol/unlock/files/11160502/Dripps.mind.map.1.pdf)

Additional Documents are available upon request. 

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ccarfi** [comment]
Thank you, @exstalis ! Will make sure the Unlock DAO community is aware of this grant application! I know there were some questions on the Snapshot / "temperature check" part of the overall Grant flow, and will drop some thoughts here on that later today.

**Comment by ccarfi** [comment]
@exstalis , thank you again for the comprehensive write-up on your vision! As noted, would recommend giving the members of the Unlock DAO community a couple of days to digest and think about the proposal, ask-answer any questions they may have here in this thread, and then (as noted in the [Grantee Handbook](https://docs.unlock-protocol.com/governance/grants-bounties/udt-grantee-handbook)), propose an "off-chain" vote on Snapshot to get a temperature check if members of the DAO are likely to support the project with a grant if you build it. (Again, the decision belongs to the members of the decentralized Unlock DAO, which is made up of individuals who hold UDT, which is the governance token in the Unlock Protocol ecosystem.

To propose an "off-chain" vote on Snapshot, you'd go to [https://snapshot.org/#/unlock-protocol.eth](https://snapshot.org/#/unlock-protocol.eth) and click on New Proposal.

<img width="1371" alt="Screen Shot 2023-04-05 at 1 01 02 PM" src="https://user-images.githubusercontent.com/214760/230195342-18cd840f-224c-4ebf-8c55-355f9f300c93.png">

In that proposal, you'd ask folks if they are likely to support a grant of the amount you've proposed. You can learn more about Snapshot itself and how to create proposals in the [Snapshot docs](https://docs.snapshot.org/).

As noted in the process in the [Unlock Grantee Handbook](https://docs.unlock-protocol.com/governance/grants-bounties/udt-grantee-handbook), if a majority of the folks voting on that temperature check are likely to support the grant and you decide to move forward, as you are hitting your milestones you can then consider making an "on-chain" proposal as the milestones are met to actually formally request the grant itself, using a tool like [Tally](https://www.tally.xyz/gov/unlock). If the vote passes in Tally, then it would AUTOMATICALLY fund the grant, since it is an on-chain vote.

Thanks for being on this ride with the Unlock community! These are new processes that we are trying out, and we all greatly appreciate your interest and involvement!

**Comment by exstalis** [comment]
Hello @ccarfi ,
Thank you for explaining the snapshot process. I will be working on it as of today. Also if I can provide more detail information please let me know :) 
I will be joining the Town Hall tomorrow

**Comment by exstalis** [comment]
@ccarfi https://snapshot.org/#/unlock-protocol.eth/proposal/0x99c157d0b67c847e96cf118fd11dbc7405790da4dbf146e6e9274bae3685c3e9

**Comment by ccarfi** [comment]
Thanks @exstalis  for sharing your description of Dripps and your proposal on the Unlock Protocol Town Hall! If Unlock DAO members want to (re-)listen to Elif discuss Dripps, you can tune in here at the 38:00 mark: https://twitter.com/i/spaces/1OyKAVNQqwwGb?s=20

**Comment by exstalis** [comment]
Thank you @thehen 
I just started my research paper on Dripps. Will be adding the repo here :)

**Comment by ccarfi** [comment]
Hi @exstalis — wanted to check in. Is this project still under development? I know there was a temp check done a while back: https://snapshot.org/#/unlock-protocol.eth/proposal/0x966a23b4d58d8d017fb075ee35059fc407e42ba1170eb556fda2924810ea6527

**Comment by ccarfi** [comment]
Archiving this dormant grant.
