### ISSUE TITLE
Broken receipts

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11553]
When loading the receipt from my keychain, I cannot edit it...
https://app.unlock-protocol.com/receipts?address=0x38181253e065b18df0006644f5fa9c2fda46cc75&network=5&hash=0xaa9a7112a5a2738e6d45b3966f2df358d25c535fa53441639cf2ab5ecedad4ed

I am connected wiuth the right wallet.
I suspect the fact that is is missing the `Wallet:` is why I can't edit it.

<img width="698" alt="Screenshot 2023-04-05 at 6 02 53 PM" src="https://user-images.githubusercontent.com/17735/230221915-5ddc3ada-3fd7-45cb-b240-14926ac1e987.png">

**Comment by kalidiagne** [comment]
here `Payer` is not set, this is a key airdropped or purchased from the checkout?

**Comment by julien51** [comment]
it was purchased

**Comment by julien51** [comment]
Related: https://github.com/unlock-protocol/unlock/issues/11616

**Comment by julien51** [comment]
Once fixed please let's add https://github.com/unlock-protocol/unlock/issues/11552
