### ISSUE TITLE
Checkout builder adds locks to the checkout display in a different order than they are added in the builder

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#11566]
**Describe the bug**
Checkout builder adds locks to the checkout display in a different order than they are added in the builder.

When adding each lock in order under "Locks" and then click the "Save" button, it actually mixes up the order of the locks in the actual checkout URL. Here you can see the correct order on the right is Explorer -> Venturer -> Pioneer, but once I click save, the order in the checkout is Venturer -> Explorer -> Pioneer 

**To Reproduce**
Add three locks to a checkout.

**Expected behavior**
Locks would show up in preview in same order they were added in the right hand pane.

**Screenshots**
<img width="1483" alt="Screenshot 2023-04-06 at 1 51 33 PM" src="https://user-images.githubusercontent.com/214760/230467309-a46762fc-2ec6-4772-ac9b-87f5cbbb0892.png">

**Comment by julien51** [comment]
Good one! @kalidiagne this one is for you!

**Comment by boskiv** [comment]
It would be great to respect an order from a builder or reorder feature.
