### ISSUE TITLE
Missing duration on locks 

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1156]
When showing the lock on the paywall we currently do not show the duration of the purchased keys.
@smombartz Could you provide a quick desighn update?

<img width="270" alt="image" src="https://user-images.githubusercontent.com/17735/51557799-e8e1bf80-1e4b-11e9-914c-17f5dc630768.png">

**Comment by smombartz** [comment]
hows this?
![image](https://user-images.githubusercontent.com/1377389/51560674-3877b980-1e53-11e9-9a0f-fe4e55f8ed49.png)

specs: https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=0%3A825

**Comment by julien51** [comment]
@cnasc Do you want to work on this one? [we currently do not have the green part either BTW... please add both at once ;)]

**Comment by julien51** [comment]
Also note that the `Monthly` thing at the top ois the name of the lock... which we currently do not have available (it will be coming from locksmith)

**Comment by cnasc** [comment]
Working on it. Adding the green part now.

**Comment by cnasc** [comment]
Getting the green purchase part is a bit difficult without lots of changes, so I'm going to split this up into adding the duration and then getting the styling in sync with Figma

**Comment by cnasc** [comment]
@smombartz will the other forms of the lock (pending, confirming, confirmed) also have changes to the design? It looks like to implement this there will be some big changes to the current lock pieces and I want to make sure I'm not going to step on anything.

**Comment by smombartz** [comment]
@cnasc i updated the locks based on that new design. you can see them [here](https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=0%3A1978). the flow is prototyped [here](https://www.figma.com/proto/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=0%3A817&viewport=679%2C819%2C0.46261&scaling=min-zoom). probably good to check in with julien.

@julien51 have you seen the above?

**Comment by julien51** [comment]
@smombartz I just did, pretty much cool with the new design... except for the "border" which I do not like but my tastes are not the point here ;)
