### ISSUE TITLE
3Pad

### ISSUE THREAD

**Issue by 3Pad** [unlock-protocol/unlock#11584]
### Description

We are a Web3-based platform that provides landing pages for users. Our platform is designed to give content creators an easy-to-use framework for building and managing a single webpage or landing page. With our platform, content creators can own, control, and engage with their audience in a way that is secure, censor resistant and transparent.

![Logo](https://api.fileverse.io/content/e1caf382-a7c4-455e-8b3b-2a5ee4aac09b?sessionId=643391bacf833d0ba180fabb)

With the Unlock Protocol grant money, we plan to implement the feature of allowing users to lock their content with a customizable paywall like shown below . 

[![Alt text for the thumbnail image](http://img.youtube.com/vi/HTuG-uJ_9RE/0.jpg)](http://www.youtube.com/watch?v=HTuG-uJ_9RE)

This was originally included in the first iteration of the platform, but was archived due to changes in planning and direction. The original implementation was simpler because the content was locked server side, but this new implementation will require us to figure out a way to do it client side. We believe that this feature will add to our seamless one page user sites & a new level of security and control for content creators and we are excited to work on bringing it back to the platform.

### Website URL

https://hello.3pad.xyz

### Twitter

@3padxyz

### Github

https://github.com/3Pad/3pad

### Discord handle

Osiris | 3pad

### Completion time

3 Months

### Team

Two independent co-founders, a man and a woman, are the brains behind this platform. They both have a strong interest in decentralized technologies and the potential they hold. One of the co-founders, who is in charge of the platform's development and deployment, brings a wealth of technical experience and knowledge to the project.

The platform's direction and focus are influenced by the other co-founder, who has a keen vision and a thorough understanding of the needs of content creators. Together, they have pooled their talents and expertise to develop a platform that gives content creators the power to take charge of their work and forge fresh, engaging connections with their audiences.

### Milestones

Milestone 1: Test Phase (2 months)

Goal: Successfully implement and test the paywall feature on the platform.

Expected timeframe: 2 months from the start of development.

During this phase, the development team will work on implementing the paywall feature into the platform and ensuring that it functions correctly. They will also test the feature thoroughly to identify and fix any bugs or issues that may arise.

---

Milestone 2: Publish Phase (3 months)

Goal: Launch the paywall feature to users.

Expected timeframe: 3 months from the completion of the test phase.

During this phase, the paywall feature will be made available to users on the platform, and marketing efforts will be ramped up to promote the feature to potential users. The team will closely monitor the performance of the paywall feature and make any necessary adjustments to optimize.

### Requested grant amount

300 UDT

### Anything else you think we should know, including why you've requested a particular grant amount

Unlock Protocol is already an integral part of our platform's infrastructure, particularly in the areas of user login/signup and NFT access (Shown Below). 

[![Alt text for the thumbnail image](http://img.youtube.com/vi/Xui3UTU9_Ks/0.jpg)](http://www.youtube.com/watch?v=Xui3UTU9_Ks)

Therefore, it makes sense to build on this foundation and explore additional ways to leverage the protocol's capabilities to further enhance the user experience.

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julien51** [comment]
Thanks @3Pad ! This looks very interesting!

**Comment by ccarfi** [comment]
Hello @3Pad! We'd love to have you on our Twitter Space next Weds so the community can learn more about your proposal. Please let us know if you're interested and we'll get you the details!

**Comment by ccarfi** [comment]
@3Pad thank you for presenting today! If folks want to check out the recording of the presentation, the 3Pad presentation starts at about 45:00 in the recording here: https://twitter.com/i/spaces/1BdGYyodQzQGX?s=20

**Comment by ccarfi** [comment]
Hi @3Pad — is this project still under development? If so, can you please provide an update?

**Comment by ccarfi** [comment]
Archiving this dormant grant.

**Comment by ccarfi** [comment]
Archiving this dormant grant.
