### ISSUE TITLE
Paywall does not show locks in coinbase wallet for Android

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1158]
**Describe the bug**

In coinbase wallet, the lock does not appear.

**To Reproduce**
1. Go to https://projects.smombartz.com/unlock

**Screenshots**

![screenshot_20190122-141958](https://user-images.githubusercontent.com/98250/51559846-0b2a0c00-1e51-11e9-925c-d291775a7fd3.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Coinbase wallet
 - Version latest as of today

**Smartphone (please complete the following information):**
 - Device: Pixel 3XL

**Comment by akeem** [comment]
Adding docs for reference: https://drive.google.com/file/d/1UU9_36keso1DbKKEck4DdO19Ap1FF0ov/view

**Comment by cellog** [comment]
don't know where to start, reached out to coinbase for help, will have to wait for a reply.

**Comment by cellog** [comment]
fixed!
