### ISSUE TITLE
Wording update on Certifications page

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#11594]
<img width="794" alt="Screen Shot 2023-04-10 at 4 36 54 PM" src="https://user-images.githubusercontent.com/214760/231019180-f4025cf3-847a-4eaf-a8d7-23087d0abef1.png">

Recommend changing the wording on the detail text at the bottom here to not reference "tickets." 

Perhaps update to:
"This is the maximum number of certifications available."

**Comment by kalidiagne** [comment]
solved with https://github.com/unlock-protocol/unlock/pull/11586
