### ISSUE TITLE
Changing settings fails when user is not on right network

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11602]
It is impossible to change any lock setting when the user is not on the right network.

**Comment by julien51** [comment]
This was also reported as part of this https://github.com/unlock-protocol/unlock/pull/11587

**Comment by kalidiagne** [comment]
Checked and is not only related on the settings page, but on every action with a different network eg.

- try to withdraw funds from a Mumbai lock, but on Goerli network 

<img width="754" alt="Screenshot 2023-04-12 at 12 58 59" src="https://user-images.githubusercontent.com/20865711/231437987-fac9db25-2210-44ec-b4e8-413b3fba7a6d.png">


Looking i found that this is a recent issue on Metamask side :/ https://github.com/MetaMask/metamask-extension/issues/18509

**Comment by julien51** [comment]
ok it looks like this was fixed by MetaMask! Good news!
