### ISSUE TITLE
Certifications dapp specifies "days" but uses "seconds"

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#11625]
The configuration page at app.unlock-protocol.com/certification specifies the duration of a certification "in days"
<img width="893" alt="Screen Shot 2023-04-12 at 3 11 34 PM" src="https://user-images.githubusercontent.com/214760/231597684-12fe2185-e02c-4205-b9fa-a83f510bb391.png">

However, putting in "365" results in a certification that expires in 365 *seconds*
<img width="334" alt="Screen Shot 2023-04-12 at 3 11 10 PM" src="https://user-images.githubusercontent.com/214760/231597822-41f45dbb-46bd-4a34-81a1-3b79756fb28e.png">

**Comment by julien51** [comment]
Oups. Let me fix this ASAP.

**Comment by kalidiagne** [comment]
> Oups. Let me fix this ASAP.

PR here -> https://github.com/unlock-protocol/unlock/pull/11626

**Comment by julien51** [comment]
fixed!
