### ISSUE TITLE
Add Sepolia

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11654]
Goerli will in fact go away [at some point in 2023](https://ethereum.org/en/developers/docs/networks/#goerli)... so let's add Sepolia!

**Comment by clemsos** [comment]
Goerli  is deprecated in the next weeks so should bring that on top of priorities

https://ethereum-magicians.org/t/proposal-predictable-ethereum-testnet-lifecycle/11575/17

**Comment by clemsos** [comment]
Seems Sepolia is recommended for apps (goerli for staking / chain-level dev) https://moralis.io/sepolia-testnet-guide-what-is-the-sepolia-testnet/

**Comment by clemsos** [comment]
First lock on Sepolia there https://sepolia.etherscan.io/address/0x395C3F0DEC45B7c8752f1A1A8b5bc5cbd914B7a5#readProxyContract
