### ISSUE TITLE
[Feature] Allow user to see previously created events

### ISSUE THREAD

**Issue by ChialiT** [unlock-protocol/unlock#11666]
Currently, user can only see the "events" type of lock via the dashboard. I'd recommend to allow user view their previously created locks in the events use case page, the event list should use same components from the dashboard. 

prerequisite: user has to connect the wallet

figma: https://www.figma.com/file/glmh5GX316O4TGiwaPyC8f?node-id=331:6386#420201413

<img width="949" alt="image" src="https://user-images.githubusercontent.com/16527634/232314275-61de6f35-e5c1-48b6-a8c8-69e253637f1e.png">

**Comment by julien51** [comment]
I like this idea! @kalidiagne When you work on this, please make sure you re-use as much code as possible from the `/locks` page.

**Comment by julien51** [comment]
We should also support that for certifications!
