### ISSUE TITLE
Enable protocol fee on a testnet

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11675]
Let's add a protocol fee for Goerli for example so we can test out that it works as expected there!

**Comment by clemsos** [comment]
Can actually enable on Sepolia if we redeploy there. That will require a clean UDT

**Comment by clemsos** [comment]
UDT contracts have been deployed and set on Sepolia, as well as an oracle. We could enable the protocol fee whenever we want now

**Comment by julien51** [comment]
> UDT contracts have been deployed and set on Sepolia, as well as an oracle. We could enable the protocol fee whenever we want now

Let's do it!

**Comment by clemsos** [comment]
Protocol fee is now enabled on Sepolia (200 bps) https://sepolia.etherscan.io/address/0x36b34e10295cCE69B652eEB5a8046041074515Da#readProxyContract
