### ISSUE TITLE
Skip select on checkout UI

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11707]
On the checkout UI, the first step is to select a lock.
When there is a single lock, let's make it possible to skip it. We already have `skipRecipient` and let's have a similar flow with `skipSelect`. 
If a paywall loads with this setting enable, let's just move directly to the next step!

**Comment by Anurag-Raut** [comment]
@julien51 I am not able to run unlock-app locally, I am getting this error,-
![image](https://user-images.githubusercontent.com/102049482/234767307-878fa219-444f-484d-9fc8-57fa9d722205.png)

**Comment by julien51** [comment]
@Anurag-Raut Please open a new issue if your problem persist but I am pretty sure you did not run `yarn && yarn build` at the root of the repo.

**Comment by julien51** [comment]
@searchableguy Let's take the easy approach and not refactor everything. Basically if that paywall config option is set, we do load all the data on that first screen, but we automatically advance to the next screen.
