### ISSUE TITLE
Find lock address before deployment

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1175]
We currently assign a new (temporary) address to locks while we wait for them to have been deployed.
It turns out that we can know the address which will be used for the lock before the transaction has actually been mined. 
This will remove the need for the temporary address.

**Comment by hardlydifficult** [comment]
This creates a race condition to consider.  Addresses are based on the account `nonce`.  When a contract is deployed by another contract, the `nonce` is from the original contract (Unlock for us) and not the user's `nonce`.  

When someone creates a new Lock, we can determine the address of the next Lock.  However if someone else is creating a Lock around the same time - the first to be mined will have correctly determined the Lock address however the second to be mined would be pointing to a valid Lock, but not the Lock they expected.

**Comment by hardlydifficult** [comment]
I believe we could address this once EIP-1014 is merged using CREATE2. https://eips.ethereum.org/EIPS/eip-1014

**Comment by akeem** [comment]
^ is super cool. We should shift to this when it become available. @julien51 since we shipped the first pass of this. How you feel about us adjusting this issues to update when available with a weekly check?

**Comment by hardlydifficult** [comment]
Labeling `Blocked` since we have an implementation today and the next step, switching to `CREATE2` can only happen after an Ethereum hard fork.

**Comment by hardlydifficult** [comment]
eta this week. Fingers crossed

**Comment by julien51** [comment]
I believe this was implemented by @akeem!
Closing!
