### ISSUE TITLE
Smart contract acceptance suite

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1176]
It would be good to have a smart contract acceptance test suite. It should not run during our CI process but we should be able to point it to the mainnet deployment and ensure that the smart contract does what we expect it to do.
The first step is to actually write some scenarios.

**Comment by nfurfaro** [comment]
Sounds good. For reference, more context on this here: #969

**Comment by nfurfaro** [comment]
@julien51 
> "The first step is to actually write some scenarios."

Did you have a specific format in mind for scenarios? I would probably start writing a bunch of skeleton tests with no implementation details such as `it("should do something...", () => {}
unless there is a different approach I should consider using here.

**Comment by hardlydifficult** [comment]
Is this done with the recent doc you published?  ..and other changes like the integration tests.  Not sure what the next steps here are.

@nfurfaro

**Comment by nfurfaro** [comment]
Yeah, this needs to be revisited. Not done yet.

**Comment by nfurfaro** [comment]
I'm wondering where we're at with this after the summer away. 
Does our current integration testing cover this, or do we still want to create a separate test suite as per this issue? 
If not we can close this and a couple sub-issues as well.
cc @NickCuso @julien51

**Comment by NickCuso** [comment]
I think we can close these.  For testing, I think next step up should be #4809

**Comment by julien51** [comment]
@clemsos It would be interesting to see if our "fork of network" approach does actually provide an easy way to test run a full test suite against any deployed network? wdyt?
