### ISSUE TITLE
Cancel and Refund, then Extend - possible metadata issue

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#11792]
Wallet `0x58e76afe6209a0088f355789f434e5244a79ddd1` had an active key to lock contract address `0xede277702b056f4c8086b6b0647425144154db0e`

Logged into Unlock Dashboard as user, went to Keys page, did "Cancel and Refund"

Key showed up in Dashboard/Keys as "Expired" (good!)

Went through WordPress plugin

Logged into WordPress site (since that wallet was already a valid user for the site)

Connected wallet

Got to Checkout link

"Extended" key

Transaction for Extend (seemed) to process successfully

<img width="1297" alt="Screen Shot 2023-05-01 at 9 41 11 AM" src="https://user-images.githubusercontent.com/214760/235489835-6f5922db-23dc-46d3-a1c2-349b018aa9ae.png">

[https://goerli.etherscan.io/address/0xede277702b056f4c8086b6b0647425144154db0e](https://goerli.etherscan.io/address/0xede277702b056f4c8086b6b0647425144154db0e)

Went to Dashboard/Keys for wallet to look at renewed key. Did not see key for the "All About Drawing" in Keys anymore, even though I just renewed it for wallet `0x58e76afe6209a0088f355789f434e5244a79ddd1`
<img width="1125" alt="Screen Shot 2023-05-01 at 9 43 42 AM" src="https://user-images.githubusercontent.com/214760/235490199-f1529985-79d4-4205-8ad4-a08262ec2ccb.png">

Onchain, the wallet still owns the token (tokenID = 2)
[https://goerli.etherscan.io/nft/0xede277702b056f4c8086b6b0647425144154db0e/2
](https://goerli.etherscan.io/nft/0xede277702b056f4c8086b6b0647425144154db0e/2
)
However, the Locksmith metadata appears to show the owner of tokenID = 2 as 0x0
[https://locksmith.unlock-protocol.com/api/key/5/0xede277702b056f4c8086b6b0647425144154db0e/2
](https://locksmith.unlock-protocol.com/api/key/5/0xede277702b056f4c8086b6b0647425144154db0e/2
)
```{"name":"Unlock Key","description":"A Key to an Unlock lock. Unlock is a protocol for memberships. https://unlock-protocol.com/","image":"https://locksmith.unlock-protocol.com/lock/0xEdE277702B056F4c8086B6B0647425144154DB0E/icon?id=2","expiration":1714494156,"tokenId":"2","owner":"0x0000000000000000000000000000000000000000","attributes":[{"trait_type":"Expiration","display_type":"date","value":1714494156}],"keyId":"2","lockAddress":"0xEdE277702B056F4c8086B6B0647425144154DB0E","network":5}```

**Comment by julien51** [comment]
ok confirming this is exactly that bug https://github.com/unlock-protocol/unlock/issues/10939 which was fixed in version 13!
