### ISSUE TITLE
Move docs inside of monorepo

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11820]
We currently have our docs [on a different repo](https://github.com/unlock-protocol/docs). We want to bring these docs to the monorepo.

As part of this, we will need to ensure that all scripts used to autogenerate docs (locksmith, smart contracts...) from code are still working as part of the build process for the docs. This will simplify the process of creating documentation and make sure we always have up to date documentation.

Finally, we will take this step as an opportunity to move our docs to be hosted as Cloudflare functions. For this we will use Github actions.

**Comment by pulsarforge** [comment]
I am interested on take this bounty. How could we proceed with the assigment?

**Comment by julien51** [comment]
Ths was done!
