### ISSUE TITLE
Phantom Wallet flagging Unlock's website as spam

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11828]
**Describe the bug**
When approving a transaction using Phantom Wallet, the domain (app.unlock-protocol.com) is flagged as 'very likely to be a scam'. The blocklist is coming from [ScamSniffer](https://www.scamsniffer.io/) .

**To Reproduce**
1. Approve a transaction using Checkout and Phantom Wallet
2. See blocklist message

**Expected behavior**
There should be no scam message when checking out using Unlock's Checkout.

**Screenshots**
<img width="332" alt="Screenshot 2023-05-07 at 4 45 24 PM" src="https://user-images.githubusercontent.com/32484647/236838236-b1fbdcc8-dc8b-4968-9b83-f8e191f089dc.png">

**Comment by julien51** [comment]
ok I found this https://github.com/search?q=repo%3Ascamsniffer%2Fscam-database%20unlock-protocol.com&type=code

I will contact them to see if they can remove us from their lists!

**Comment by julien51** [comment]
It looks like this was actually removed 6 days ago... I guess Phantom has some kind of cache...
