### ISSUE TITLE
Events: Use event details banner as a tile/thumbnail when shared on Twitter & Discord

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11849]
**Is your feature request related to a problem? Please describe.**
When organizers share their event details page URL on Twitter or Discord, no tile/thumbnail is created. Without an image, the tweets aren't as effective. 

**Describe the solution you'd like**
Use the banner image added by organizers on event detail pages as the tile/thumbnail when they share a URL on Twitter or Discord

**Describe alternatives you've considered**
Using the ticket image would be better than no image, although not optimal
<img width="582" alt="Screen Shot 2023-05-10 at 9 15 29 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/dff52f14-e444-4488-a0d2-a422aff96aff">

**Additional context**
[Example from Twitter](https://twitter.com/Thehouseofweb3/status/1656067125738606592?s=20)

**Comment by ChialiT** [comment]
<img width="1056" alt="image" src="https://github.com/unlock-protocol/unlock/assets/16527634/1698eb53-15e5-4007-9705-6428336ad786">


@searchableguy template here: https://www.figma.com/file/glmh5GX316O4TGiwaPyC8f?node-id=403:6519#443034699

**Comment by julien51** [comment]
Very cool! Thanks @ChialiT

**Comment by julien51** [comment]
Maybe we can add some code from https://github.com/unlock-protocol/unlock/compare/playwright

**Comment by patrickworkman** [comment]
Event tiles aren't populating on Twitter: [Example](https://twitter.com/thehouseofweb3/status/1666498745591300097?s=20)

**Comment by julien51** [comment]
@searchableguy confirmed: https://www.opengraph.xyz/url/https%3A%2F%2Fapp.unlock-protocol.com%2Fevent%3Fs%3Dlayer2scalingjourney

Please fix ASAP!

**Comment by searchableguy** [comment]
As explained on the discord, the issue comes from lack of SSR since most OG previewer services only fetch via get request and do not run javascript. We would need to move the next app to use SSR to show the OG image.

**Comment by julien51** [comment]
Ok, that means we need to move to either Vercel (home of nextjs) or Cloudflare(which we already use!)
