### ISSUE TITLE
Events: Remove seconds from event details pages

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11846]
**Describe the bug**
Event details pages created through Events contain seconds (00:00:00). Organizers rarely, if ever, need to provide start or end times in seconds

**To Reproduce**
1. View an event details page
2. See start/end times in seconds

**Expected behavior**
Time would be hour:minutes instead of hour:minutes:seconds

**Screenshots**
<img width="1280" alt="Screen Shot 2023-05-09 at 4 29 26 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/649d8f77-01ba-4c77-8eae-f0e69a5ce84f">

**Comment by julien51** [comment]
@kalidiagne please prioritize this.
Also do the changes we discussed:
* start time increments by 5 minutes
* end time is always after start time
