### ISSUE TITLE
Burn does not reset `totalKeys`

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11850]
I burned a key: https://goerli.etherscan.io/tx/0xaff237b9cd8176fa376e1e6b2a0e683aa7b1a3b05fc4297d7f402af41b5a5e45
But then the contract still shows I own 1 and it actually shows this token id `2` as mine:
<img width="1344" alt="Screenshot 2023-05-10 at 1 39 04 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/a2b9923a-0301-4f83-97f7-7ca6d5423950">

**Comment by clemsos** [comment]
very weird. We shipped that fix in https://github.com/unlock-protocol/unlock/issues/11331 but it seems to have been reverted in repo :/ Likely a merge issue

**Comment by clemsos** [comment]
The git blame shows nothing, as if the changes have never been merged... https://github.com/unlock-protocol/unlock/blame/98ad208948ac03b2a4f5e0300875562b649bf2d9/smart-contracts/contracts/mixins/MixinKeys.sol#L143
