### ISSUE TITLE
Paywall should return email address

### ISSUE THREAD

**Issue by blahkheart** [unlock-protocol/unlock#11854]
Currently, the paywall app only returns the transaction hash and the lock address when a user completes a purchase with the paywall app. 
It would be great if it returns the email address of the user as well when the purchase is complete.

**Comment by julien51** [comment]
> It would be great if it returns the email address of the user as well when the purchase is complete.

I think we could rather return all the metadata saved by the user.

**Comment by blahkheart** [comment]
Yeah, that's even better!
