### ISSUE TITLE
White Hat DAO Grants Application

### ISSUE THREAD

**Issue by White-Hat-Dao** [unlock-protocol/unlock#11856]
### Abstract
White Hat DAO is a valuable resource for individuals looking to conduct their own research on blockchain projects more effectively and efficiently. The platform compiles various data points and metrics for onboarded projects, helping users make more informed decisions. We provide a safety score for each project based on various factors, such as code security and potential risks and vulnerabilities. This rating can be helpful for users when evaluating the trustworthiness of a project.

Here is an example of safety rating - https://whitehatdao.com/safety-ratings/rating/6345ff8c365260933fecc7e0

### Context
Defi lost 3.1 billion USD in funds last year to hacks, and what we are building can easily be used to not only inform people of the types of information that need to be known when they DYOR but also allow good projects who care about the safety of their members to shine. We have seasoned developers and industry experts who are diligently working to provide training and educational resources for the good of web3.

We believe a better educated community and project transparency will increasingly become the norm, and organizations like ours will be at the forefront of such education.

### WHD Roadmap

**Q1 - 2023**
- We have gone live
- DAO Framework and DAO Constitution already completed
- WHD Platform and Safety Rating apps are live and undergoing further optimization
- We are ahead of schedule on our Q1 goals.

**Q2 - 2023**
- Onboard 500 projects on Safety Rating App
- Development of safety analysts & educational Program
- Quest-based DAO Membership NFT application ( Sybil Resistant ) 
- { Note: Membership NFT contract has been deployed on Polygon Network ( free mint ) and please check at https://whitehatdao.com and apply for NFT membership, make sure to select polygon network in your web3 wallet before connecting the site, Membership NFTs have voting rights and governance }
- Decentralized verification system, Distribute Membership NFTs

**Q3 - 2023**
- Governance App, Decentralized Community Forum
- On-chain Governance Mechanism
- Live Safety Rating
- API creation
- Governance Token Launch
- Distribution of Governance tokens

**Note:** 
We are using Unlock Protocol on our platform and currently working on our own governance platform. All security & safety rating assessments published by White Hat DAO are the sole and independent work product of the WHD. Scores are subject to change without notice. The ratings and other WHD work product are not endorsed by any asset development teams, foundations, regulatory agencies or any other third parties.

Safety Ratings are not financial advice. Lets remind ourselves that crypto assets are speculative, complex and involve significant risks, which can be highly volatile and sensitive to secondary activities. Its performance is unpredictable and past performance is no guarantee of future results. Always make sure to DYOR !!

Please feel free to reach out or for more information, please visit our website at https://whitehatdao.com

Here is an introductory video - https://www.youtube.com/watch?v=L2ZAQi_HK_I

### Website URL

https://whitehatdao.com/

### Twitter

@White_Hat_DAO

### Github

https://github.com/WhiteHatDAO

### Discord handle

https://discord.gg/G5NvT2AyWA

### Completion time

We are live, But developments are ongoing.

### Team

**Contributors**

White Hat#6398

NFThinker🏴#2814

0xAnimal

CompositeFellow#7988

LordRanchoatos#1813

Andy

Nupur | Parcel#4467

Itsuki

JosepBove#9999

IsraelRex#3613

ab_colours#3481

AmyMarcella#9076

Gold Fury#5995

RedCrystalDragon🏴#4188

xuanling11.crypto#0521

Raj

affirmation2021#5840

### Milestones

1. Quest-based DAO Membership NFT application ( Sybil Resistant )
2. Decentralized verification system, Distribute Membership NFTs
3. NFT Gated Web3 Governance Platform & forum discussion

### Requested grant amount

300 UDT

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ccarfi** [comment]
thanks, @White-Hat-Dao ! will make sure the community sees this!

**Comment by SolomonFoskaay** [comment]
Interesting @White-Hat-Dao , I checked out the project and just applied and minted my NFT
![Selection_005](https://github.com/unlock-protocol/unlock/assets/83863629/c0db04ea-dcc4-43a5-addb-497ff90746a2)

The rating for Unlock (https://whitehatdao.com/safety-ratings/rating/6345ff8c365260933fecc7e0) is also detailed IMO especially helping to see top holders by wallet too with the security ratings.

Couldn't join the Discord because link says expires from the NFT application on your website, so check that to fix it.

**Comment by SolomonFoskaay** [comment]
> > Interesting @White-Hat-Dao , I checked out the project and just applied and minted my NFT ![Selection_005](https://user-images.githubusercontent.com/83863629/237792246-c0db04ea-dcc4-43a5-addb-497ff90746a2.png)
> > The rating for Unlock (https://whitehatdao.com/safety-ratings/rating/6345ff8c365260933fecc7e0) is also detailed IMO especially helping to see top holders by wallet too with the security ratings.
> > Couldn't join the Discord because link says expires from the NFT application on your website, so check that to fix it.
> 
> Thanks for the feedback Solomon. I will update the discord link. We will be deploying a new version shortly, making some changes in the backend. Pls feel free to mint the NFT via desktop or laptop. I can see the NFT image did not load properly there. The NFT app is not tablet/mobile friendly yet.

@White-Hat-Dao okay. I was able to mint it successfully and the NFT image display well when viewed via Opensea.
Its a cool design you got there.

**Comment by White-Hat-Dao** [comment]
@ccarfi We are happy to announce that 90% of our project roadmap have been completed, Apart from Gov token creation & distribution. Please advise how we can proceed with the Grants. I think we have completed the Unlock community temperature check. Thanks 🙏

**Comment by ccarfi** [comment]
Hi @White-Hat-Dao — wanted to check in. Is this project still under development? If so, could you please provide an update? Thanks!

**Comment by ccarfi** [comment]
Archived.
