### ISSUE TITLE
Lock should round display value to the day

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1185]
**Describe the bug**

Locks are currently limited to being saved by the day in our dashboard, but there is nothing in the protocol preventing them from being other lengths. Our Lock UI should round to the nearest day if necessary

<img width="1670" alt="screen shot 2019-01-23 at 3 19 40 pm" src="https://user-images.githubusercontent.com/98250/51634653-cbcbf000-1f22-11e9-9533-7ce804588ced.png">

**Comment by cellog** [comment]
Just the story. But if someone were to use a different UI to create a lock with a non-day expiration it would show when we view the lock

**Comment by julien51** [comment]
Ho, ok! Thanks!
