### ISSUE TITLE
Custom slug for Products on Unlock homepage

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11866]
**Is your feature request related to a problem? Please describe.**
We need an easy way to direct people directly to apps and experiments created by Unlock Labs. Today, apps and experiments are viewed through the homepage when people click 'Products.'

**Describe the solution you'd like**
Create a custom slug that directs people to the products tab on Unlock-Protocol.com. 

**Describe alternatives you've considered**
Create a landing page with all Unlock Labs apps and experiments (similar to Showcase) 

**Additional context**
![Screen Shot 2023-05-11 at 3 55 02 PM](https://github.com/unlock-protocol/unlock/assets/32484647/590c5d54-a31a-4c27-8bab-e117d8377d26)

**Comment by julien51** [comment]
We already have custom urls for https://events.unlock-protocol.com/ or https://certifications.unlock-protocol.com/
Is that what you are referring to?

or do you want us to have a page like https://unlock-protocol.com/products that lists all the products?

**Comment by patrickworkman** [comment]
If we had a page like https://unlock-protocol.com/products that lists all the products, it would make sharing all of our products more efficient.
