### ISSUE TITLE
Unlock Protocol WordPress Plugin Community Edition

### ISSUE THREAD

**Issue by SolomonFoskaay** [unlock-protocol/unlock#11882]
## Proposal Summary

The Unlock Protocol presents a revolutionary way to monetize digital content by leveraging the power of NFT. However, the current implementation of its official WordPress plugin leaves much to be desired due to community-reported issues remaining unresolved for extensive periods, and the lack of timely feature additions hinders the wider adoption and usability of the protocol on wordpress. 

Meanwhile wordpress powering over 40% of websites online (over 500 new websites built daily with wp) as of January 2023 is a huge market to target for increasing adoption of the Unlock Protocol.

WordPress statistics (top picks)
810 million websites use WordPress, which is 43% of all the websites on the internet
WordPress has a 64.2% share of the CMS market, which is more than 10x greater than its closest competitor 
54.3% of WordPress users are running the latest version of the software (WordPress 6.0)
Divi is used on over 3.8 million websites, making it the most popular WordPress theme.
Source: [https://colorlib.com/wp/wordpress-statistics/](https://colorlib.com/wp/wordpress-statistics/)

This proposal seeks funding to spearhead a Community Edition of the Unlock Protocol WordPress Plugin. This effort aims to ensure timely updates and feature implementation, create comprehensive documentation, and foster a more dynamic community around the plugin.

&nbsp;

## Background

My name is Foskaay Solomon, a dedicated member of the Unlock DAO community for over 1 year now considering have been recognized as No1 top community contributor on the official monthly contributors' leaderboard for the past 6 months consecutively till date. Am also a previous Unlock educational content grantee - one of my educational content as part of the grant about unlock wp implementation remains top bringing people to the community on youtube to date - a search for "unlock protocol wordpress" which currently gets 20-100 search monthly on youtube have my video consistently ranking among the top 5 with over 1,200 views. See it here [https://www.youtube.com/watch?v=mKISNHj2u3o&t=9s&pp=ygUZdW5sb2NrIHByb3RvY29sIHdvcmRwcmVzcw%3D%3D](https://www.youtube.com/watch?v=mKISNHj2u3o&t=9s&pp=ygUZdW5sb2NrIHByb3RvY29sIHdvcmRwcmVzcw%3D%3D)

As a developer, I have actively contributed to the development of the official Unlock Protocol WordPress plugin, most notably, I have initiated the restructuring of the plugin to make it more contributor-friendly, and introduced full post/page locking functionality.

However, during my contributions, I've noticed significant delays in feature implementation and issue resolution (including the fact that the core team already have a lot at hand improving the core protocol itself that when you push a PR to fix issues it takes a while for them to have the time even to check it out). All the aforementioned factors have further contributed to making some critical and essential issues submitted by the community for fixes have been left unresolved for over a year, hindering good user experience that would increase Unlock Protocol adoption in the WordPress community.

This lead me to the creation of the "Unlock Protocol Wordpress Plugin Community Edition", forked from the official unlock plugin.

&nbsp;

## Project Description

With the creation of the Community Edition of the Unlock Protocol WordPress Plugin, the following are the key objectives:

1. **Timely issue resolution**: Address long-standing unresolved issues from the official repository and ensure at least one issue is resolved per month.

2. **Feature updates**: Implement feature requests from the community on a regular basis.

3. **Comprehensive Documentation**: Create detailed documentation tailored for WordPress users. This will include a dedicated FAQ section and a Showcase segment to highlight WordPress websites utilizing Unlock Protocol.

4. **Demo Site**: Build a demo site to illustrate the functionality of the community plugin.

5. **Add to Wordpress plugin directory**: Submit the community edition plugin to be added to the official WordPress plugin directory to make it available to users within the wp plugin store.

6. **Community Support**: Maintain consistent and continuous support for users of the Community Plugin through the already existing official Discord #WordPress channel.

7. **Open Source**: Just like the official plugin, the community edition repository and docs will remain open-sourced, promoting contributions from the broader community.

## Why a Community Edition

As Unlock Protocol is moving towards a full DAO, this initiative aligns with the spirit of decentralization and shared control. It would lighten the load on the core team, allowing them to focus on core protocol development while the community steps up to create and manage plugins/integrations for the protocol users like this community edition WordPress plugin. This is not a competition (or a way to just get free money for what already existed) but a demonstration of how the community can contribute to the mass adoption of the protocol by encouraging developers to pick different areas of the protocol, build what will help the community and increase adoption with consistent update and maintenance for it. (maybe this could even span an official Unlock Protocol plugin directory where all community-contributed plugins/integrations with different platforms can be listed and encourage devs to either develop new ones or join existing ones as contributors).

### Why this is important for mass adoption:
The fact is if we want more adoption at the rate and high speed the Unlock core team is adding amazing features to the core Protocol (**kudos to them something new and fresh gets added weekly/Monthly**), The Unlock DAO also need devs that build and manage plugins/integration tools independently of the core team as an individual dev or team of devs to make it easier for creators to use Unlock Protocol across different platforms (let's build the base, why creator focus on coming to use it without the need to learn the core or build on it themselves which do discourage many).

&nbsp;

## Comparison: Official Plugin Vs. Community Edition

A comparative analysis of the official plugin and the proposed community edition illustrates how the latter could boost the adoption of the Unlock Protocol further in Wordpress community:

| No   | Features                                                                                                    | Official Plugin | Community Edition   |
|------|-------------------------------------------------------------------------------------------------------------|-----------------|---------------------|
| 1.0  | Block Lock (Gutenberg Editor Only)                                                                          | Yes             | Yes                 |
| 2.0  | Block Lock (Non-Gutenberg Editors like Elementor, Divi, Classic etc.)                                       | No              | Yes                 |
| 3.0  | Full Post/Page Lock (Gutenberg Editor Only)                                                                 | Yes             | Yes                 |
| 4.0  | Full Post/Page Lock (Non-Gutenberg Editors like Elementor, Divi, Classic etc.)                              | No              | Yes                 |
| 5.0  | WP Shortcodes                                                                                               | No              | Yes                 |
| 6.0  | Custom Post Types Lock                                                                                      | No              | Yes                 |
| 7.0  | Edit existing Lock details                                                                                  | No              | Yes                 |
| 8.0  | Issues/New features request (the time it usually takes to fix/add new features it to the plugin)                              | 1-2 Year        | 1-3 Months          |
| 9.0  | Dedicated documentation                                                                                     | No              | Yes                 |
| 10.0 | Dedicated Support                                                                                           | Discord         | Discord             |
| 11.0 | Overall Unlock Protocol Adoption Boost (based on available features, support, on-time issues fixes)         | As Usual        | At least +50% more  |

The proposed Community Edition unlocks several new features, addresses issues more timely, and provides comprehensive documentation and dedicated support. This effectively encourages more people to use the Unlock Protocol on wordpress and it is estimated to boost overall protocol adoption by at least 50% more on Wordpress.

`And this shouldn't be as usual where it is taken over by the core team after dev(s) complete the plugin/integration development, then suffer from not being updated regularly.` No, we should instead encourage the dev(s) to maintain, and update the plugin/integration and support the community using it with special grant plans dedicated to this type of developer contributors as proposed below in this proposal. 

&nbsp;

## Unlock Plugin/Integrations Developers Grant
As aforementioned, I believe to attract developers to build tools/plugins/integrations on the Unlock protocol for the community, there is need for a dedicated grants specifically for developers and I believe am spearheading that with this.

The Devs grant may be for 3 months, when given, the dev(s) will have to showcase everything their grant was approved for to continue to get another after 3 months. Plugins/integrations need consistent maintenance to remain useful for the community and this type of grant for dev(s) will encourage consistency from them to keep the plugin/integration updated monthly for as long as the 3 months dev(s) grants is re-issued to them by the Unlock DAO.

It may also include the dev(s) sending monthly updates via the governance channel in the Unlock Discord server to keep them accountable directly to the Unlock DAO community every single month their dev(s) grant is still active. These accountability and transparency measures also ensure dev(s) that get the special dev grants for the first 3 months without delivering will not qualify for future ones.

I humbly suggest a `devs grant prize of 100UDT - 200UDT` for the "Unlock Plugin/Integrations Developers Grant" every 3 months.

Also, a Plugin/Integration showcase to display them to the Unlock DAO as community dev(s) made tools for more adoption of the Protocol may be created on the official Unlock website.

`TEMPLATE`: If need be there could be a separate template for the dev's grant different from this general one.

&nbsp;

## Milestones
To initiate this, here are my "3 Months (May-July, 2023) Unlock Plugin/Integrations Developers Grant Measurable Milestones":

1. **Set up the Community Edition WordPress plugin repository** - fork the official plugin and continue to build on it.
2. **Fix 2 long-standing pending issues from the official plugin**
   - 2.1. WP Shortcode Lock - for increased compatibility with various WordPress editors beyond the only Gutenberg editor the forked official plugin support  (Classic, Elementor, etc.).
   - 2.2. Category/Tag Lock - allow the wp plugin user to lock category/tag with Unlock, making it suitable for wordpress websites with a lot of content to token-gate at once easily.
3. **Develop comprehensive documentation and create a demo site**
   - 3.1. Set up documentation website - it is set up to allow contribution from the community as part of the plugin repo itself [here](https://github.com/AiHiPUniversity/unlock-protocol-wordpress-plugin-community-edition/tree/main/docs) and also have a frontend for easy access at [https://unlock-wpplugin-community-edition.aihipuniversity.com](https://unlock-wpplugin-community-edition.aihipuniversity.com)
   - 3.2. Demo website - accessible at [https://demo.aihipuniversity.com/unlock-protocol-wpplugin-community-edition/](https://demo.aihipuniversity.com/unlock-protocol-wpplugin-community-edition/) 
4. **Submit to Wordpress directory** - submit the community edition plugin to the wordpress plugin directory to make it easily accessible within wordpress websites' plugins directory search.
5. **Implement a system for regular issue resolution, feature updates and continuous support** - this is done in 2 ways. 
   - 5.1. Plugin users can submit issues for fixing via the repo issues section [here](https://github.com/AiHiPUniversity/unlock-protocol-wordpress-plugin-community-edition/issues) 
   - 5.2. Establish a system for community support - this is done via the existing dedicated wordpress channel in the official Unlock DAO community Discord server at [https://discord.com/channels/462280183425138719/926137583564619836](https://discord.com/channels/462280183425138719/926137583564619836)

&nbsp;

## Conclusion

In conclusion, the creation of a Community Edition of the Unlock Protocol WordPress Plugin is not just about improving a tool; it's about fostering a more engaged, dynamic, and self-supporting community around Unlock Protocol as a whole via Wordpress huge community.

I am confident that this initiative will not only improve the WordPress plugin but `will also serve as a model for other community-led initiatives` for developers and non-developers that will lead to contributing to the overall growth and success of Unlock Protocol and the Unlock DAO.

Thanks!  

### Website URL

https://github.com/AiHiPUniversity/unlock-protocol-wordpress-plugin-community-edition

### Twitter

@SolomonFoskaay

### Github

https://github.com/AiHiPUniversity/unlock-protocol-wordpress-plugin-community-edition

### LinkedIn

https://www.linkedin.com/in/foskaay/

### Discord handle

Foskaay#1594

### Completion time

Major features in the milestone are already done, while in-progress milestones will be ready in about 2-3weeks but after that I will still continue to provide fixes and support for the plugin users consistently for 3 Months validity (May-July, 2023) of this dev(s) grant.

### Team

Solomon Foskaay  
Twitter: [SolomonFoskaay](https://twitter.com/SolomonFoskaay)  
LinkedIn: [Foskaay](https://www.linkedin.com/in/foskaay/)

## Milestone Summary & Tracking Table
Here is the Milestone Summary & Tracking Table with the above milestone data to make it much easier to follow the community edition project progress:

| No  | Description                                      | Status       |
|-----|--------------------------------------------------|--------------|
| 1.0 | Set up Community Edition WordPress plugin repository | Done      |
| 2.0 | Fix 2 long-standing pending issues from the official plugin | -    |
|     | - 2.1 WP Shortcode Lock                          | Done         |
|     | - 2.2 Category/Tag Lock                          | In-progress  |
| 3.0 | Develop comprehensive documentation and create a demo site | -    |
|     | - 3.1.1 Set up documentation website            | Done         |
|     | - 3.1.2 Add tutorials for the plugin            | In-progress  |
|     | - 3.2 Demo website                               | In-progress  |
| 4.0 | Submit to WordPress directory                    | In-Progress  |
| 5.0 | 3 Months supports/updates                        | (May-July, 2023) In-Progress |

### Requested grant amount

100 UDT

### Anything else you think we should know, including why you've requested a particular grant amount

I will like to see the proposed `Unlock Plugin/Integrations Developers Grant` become a point of attracting more developers to build not just for themselves but build, manage and maintain tools (plugins/integrations) on top of Unlock Protocol that will make it easier for more people to adopt Unlock just like the Unlock core team is the only one I see doing this for now. 

If developers are giving consistent grants every 3 months. It will encourage them not just to keep building on Unlock Protocol but also ensure whatever tools they have built for Unlock community are well maintained and users of the plugins/integrations in Unlock DAO are also well supported.

And if Unlock DAO and the protocol want to grow bigger, more solid and better, `we need to go beyond the Unlock core team being the only one building the needed tools` for the community.

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by White-Hat-Dao** [comment]
Excellent proposal. +1

**Comment by SolomonFoskaay** [comment]
> Excellent proposal. +1

Thanks @White-Hat-Dao

**Comment by ccarfi** [comment]
Hi @SolomonFoskaay — is this project still under development? If so, could you please provide an update?

**Comment by SolomonFoskaay** [comment]
I have put it on hold and move on considering it's 8months already without getting response of interest and support to move the proposal forward from neighter the Unlock team nor the community.
