### ISSUE TITLE
[frontend] Goal launcher within membership dashboard

### ISSUE THREAD

**Issue by ChialiT** [unlock-protocol/unlock#11896]
**Is your feature request related to a problem? Please describe.**
Guide user to quickly achieve their goals; currently available paths are: event, certification, or general lock.

**Describe the solution you'd like**
When user click on the "create lock" btn, we will propose the curated path for them.

Design:
<img width="2427" alt="image" src="https://github.com/unlock-protocol/unlock/assets/16527634/1248b673-7032-47bb-b6c8-e9241e9a4206">

figma:
https://www.figma.com/file/pNN7ER1F4mdToFfk1bB0gu?node-id=3506:83435#444643289

**Comment by julien51** [comment]
@kalidiagne We should actually just have that page at the root of `app.unlock-protocol.com` and skip the previous screen in @ChialiT 's design:

<img width="197" alt="Screenshot 2023-06-20 at 12 01 58 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/691ee67c-965d-4b43-9037-4df25515f556">

Also, if the user has already deployed a lock do not show "I am not sure let me create my own" but "Manage the membership contracts I deployed previously".

**Comment by julien51** [comment]
This is now done: https://app.unlock-protocol.com/
