### ISSUE TITLE
Adding the "kind" of wallet on the members page for lock managers

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11903]
When a lock managers lists all of their members, we should show the "type" of memberships.
We have 3 types:
* `user wallet`
* `unlock account`
* `walletless`

Let's show these as labels/tags on the UI.

**Comment by Anurag-Raut** [comment]
is this type of memberships stored somewhere?
I tried searching but couldn't find.


The object returned by getMembers doesn't have a "type" attribute

![image](https://github.com/unlock-protocol/unlock/assets/102049482/2ac89643-6d73-4bd0-b9c1-564abc10176f)
https://github.com/unlock-protocol/unlock/blob/master/unlock-app/src/components/interface/locks/Manage/elements/Members.tsx#L43

**Comment by ChialiT** [comment]
re-arrange the layout at same time, 
<img width="2054" alt="image" src="https://github.com/unlock-protocol/unlock/assets/16527634/54646454-611c-4bf1-ad30-32f6091dbc74">


figma: https://www.figma.com/file/pNN7ER1F4mdToFfk1bB0gu?node-id=3525:85789#449975933

**Comment by julien51** [comment]
Thanks @ChialiT !
