### ISSUE TITLE
Events: Add fields for First Name and Last Name to event details pages

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#11902]
**Is your feature request related to a problem? Please describe.**
In addition to an email address, event organizers want to know their attendees' first and last names.

**Describe the solution you'd like**
Add fields to collect First Name and Last Name to event details pages.

**Describe alternatives you've considered**
Add Phone Number as an optional field (Eventbrite does this)

**Comment by julien51** [comment]
Do we want to add these by default on every event and do we want to make them requirements?

**Comment by patrickworkman** [comment]
Default on every event & requirement. Event organizers who don't care to know their attendee's names are a small minority.

**Comment by julien51** [comment]
This has been implemeted!
