### ISSUE TITLE
Add swap and purchase support to universal card purchaser!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11908]
This would allow us to suport _any_ lock for which the currency is convertible!

**Comment by christopapas** [comment]
Hey! Sorry to budge in on this GitHub comment Saw your team is writing in solidity. My team is building a proactive web3 devsec tool for solidity smart contracts. Here is our website. https://www.olympix.ai/ 


Shoot me a message on telegram/Twitter if you want to learn more about them. Linked on my profile. It’s totally free. Happy coding.  

If not pretend you never saw this

**Comment by julien51** [comment]
Universal cards have been deprecated for now.
