### ISSUE TITLE
Sold out locks should not allow keys to be sold anymore

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1191]
When a lock is sold out, we should show it as such on the paywall so that customers cannot try to actually purchase keys from it...

@smombartz we probably need a design for that?

**Comment by cnasc** [comment]
We do have a disabled form of the lock, although it doesn't explicitly say that there are no keys left to be sold. Would it be sufficient to use that, but with a message along the bottom saying "Sold Out" or similar?

**Comment by smombartz** [comment]
mocked it up on the quick. we need to think a bit more about paywall messaging and customizability (or minimizing it)

![image](https://user-images.githubusercontent.com/1377389/51715547-2cccf400-2007-11e9-9289-2999d4ccb419.png)

**Comment by cnasc** [comment]
Maybe we should open a new issue for updating the sold out style?
