### ISSUE TITLE
Terms of Service is slightly too wide on mobile

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1193]
**Describe the bug**
The Terms of Service box pushes content (including the menu) off-screen to the right on mobile. I'll attach a screenshot momentarily

**To Reproduce**
1. Go to staging

**Screenshots**

![screenshot_20190123-164305](https://user-images.githubusercontent.com/98250/51639135-2b7bc880-1f2e-11e9-8bbb-50ea6d99ccc8.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Chrome and Coinbase Wallet

**Comment by julien51** [comment]
This is fixed!
<img width="400" alt="image" src="https://user-images.githubusercontent.com/17735/51781930-e7cfbd00-20ed-11e9-8488-d184891e5ce2.png">
