### ISSUE TITLE
"fixed" amount withdraws

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11944]
Our withdraw UI lets the user chose what amount they want to withdraw with a bar.
We also need to let the user enter a fixed amount. That amount needs to bet between `0` and the full balance, rather than only decimal amounts.

For example on the screen below I want to withdraw 20 USDC exactly but I cannot.

<img width="551" alt="Screenshot 2023-05-19 at 2 29 41 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/7f951cc7-40c2-480a-baea-14e28977f746">

**Comment by Anurag-Raut** [comment]
Can I work on this issue?

**Comment by Anurag-Raut** [comment]
## This is my proposed solution
#### we can provide user notion to choose between a number input field and a range input field

![image](https://github.com/unlock-protocol/unlock/assets/102049482/2eb0d458-ccee-4d10-bea9-8b1f861fdaaa)

![image](https://github.com/unlock-protocol/unlock/assets/102049482/4cad4e5b-9a63-43d3-ab78-e693f1db96a8)


### Please let me know if I can work on this issue , and if so what changes need to be done .

**Comment by Anurag-Raut** [comment]
> Ha! thanks @Anurag-Raut but I don't think users know what "Switch to Typebox" even means :) I think the way to go to would be to add a "pencil" next to the amount and when the user clicks on it, then the amount would turn into a field.

which library can I use for pencil icon?

**Comment by Anurag-Raut** [comment]
> > Ha! thanks @Anurag-Raut but I don't think users know what "Switch to Typebox" even means :) I think the way to go to would be to add a "pencil" next to the amount and when the user clicks on it, then the amount would turn into a field.
> 
> ![image](https://user-images.githubusercontent.com/102049482/239993195-893abf20-e7dc-41c6-ad38-fafdfab42fe7.png)
> 
> ![image](https://user-images.githubusercontent.com/102049482/239993317-b3f246a9-b11d-4801-9493-ed81079e6b57.png)
> 
> does this look good?, mention if any additional changes is to be done.

@julien51
