### ISSUE TITLE
After purchasing a key on Julien's Lock, I'm unable to view content.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#1195]
**Describe the bug**
After purchasing a key on Julien's Lock, I'm unable to view content. The "Go to Content" button doesn't work.

**To Reproduce**
1. Go to 'https://www.ouvre-boite.com/members/'
2. Click on 'purchase key'
3. Wait for 12 confirmations
4. Attempt to view content

**Expected behavior**
I should be able to view content with a valid key.

**Screenshots**
![image](https://user-images.githubusercontent.com/17053076/51640039-b86b5580-1f1f-11e9-8ac9-3d0ab5104cb0.png)

![image](https://user-images.githubusercontent.com/17053076/51639795-0c296f00-1f1f-11e9-8d8f-c03b12ba6af3.png)

**Desktop (please complete the following information):**
 - OS: osX 10.14.2
 - Browser Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by julien51** [comment]
The lock is there: https://rinkeby.etherscan.io/address/0x202ee6b98cef909876339b07560d605ca6c426c4

**Comment by julien51** [comment]
Good news! This lock is a lock with a max number of keys of 0... so yeah, purcchasing keys is never going to work and closing the modal should not be expected to work.
This is 2. above.

We still need to do 1. and also https://github.com/unlock-protocol/unlock/issues/1191

**Comment by julien51** [comment]
@nfurfaro I just updated the lock I am using on my blog. Could you try again and let me know if this works better?

**Comment by julien51** [comment]
And please close if it does!

**Comment by julien51** [comment]
I cannot reproduce. @nfurfaro are you able to close this?

**Comment by nfurfaro** [comment]
@julien51 Same issue for me with your updated lock, until I disabled Adblock...then it worked.

**Comment by nfurfaro** [comment]
Closing, as I just tried again (with adblock enabled) and had no issues.
