### ISSUE TITLE
Get tokenID from  receipts SubGraph query in polygon network

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#11987]
Can I get tokenID by tokenAddress from receipts query ?
```
{
  receipts(
    where: {
      lockAddress: "0xb6db2c1923dad7411dad2c0c16c9997e5a481fe8"
      payer: "0x1f8a830fa5769c7e835308fa01ed8b82559991ef"
    }
  ) {
    timestamp
    payer
    tokenAddress
    amountTransferred
    receiptNumber
    
  }
}
```
I want to contruct nft url to polygonscan https://polygonscan.com/token/0xb6db2c1923dad7411dad2c0c16c9997e5a481fe8?a=51

**Comment by julien51** [comment]
@boskiv After studying this a bit more, I think it is not a great idea. The receipts are specific to payments and should not be used to identify the token ids.

**Comment by boskiv** [comment]
But how I get information about what token ID was purchased by user?

**Comment by boskiv** [comment]
Payment for what? In payments, you should see what you buy. Isn't it?
