### ISSUE TITLE
 Polygon Subgraph has no keyPurchases

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#11986]
https://api.thegraph.com/subgraphs/name/unlock-protocol/polygon-v2/graphql?query=%0A++%7B%0A++keyPurchases%28%0A++++orderBy%3A+timestamp%2C+%0A++++orderDirection%3A+desc%2C+first%3A+5%2C%0A++++where%3A+%7B%0A++++++purchaser%3A+%220xe1252b39b2e7865ffe2d6ded4fa5d3e62a287fb0%22%0A++++%7D%29+%7B%0A+++purchaser%2C%0A++++price%0A++++timestamp%0A++++tokenAddress%09%0A++%7D%0A%7D%0A%0A

```
{
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "message": "Type `Query` has no field `keyPurchases`"
    }
  ]
}
```

**Comment by julien51** [comment]
I think you were using the wrong (old) subgraph. Check our docs for the subgraphs.
