### ISSUE TITLE
Receipt Subgraph Query contains wrong payer info

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#11992]
I paid for a key and check info in subgraph
https://api.thegraph.com/subgraphs/name/unlock-protocol/polygon-v2/graphql?query=%7B%0A++receipt%28id%3A+%220x067edd6e72e9fae09f934c23b55a817ce1cfef12ca3445918c4ca404c1e447c6%22%29+%7B%0A++++receiptNumber%0A++++payer%0A++++%0A++%7D%0A%7D

https://app.unlock-protocol.com/locks/lock?address=0x9e0ba8b2a6e9ffc74a013c1a0e177f73f0190e58&network=137
my wallet is : `0xe1252b39b2e7865ffe2d6ded4fa5d3e62a287fb0`
contract address is: `0x9e0ba8b2a6e9ffc74a013c1a0e177f73f0190e58`
receipt no: `0x067edd6e72e9fae09f934c23b55a817ce1cfef12ca3445918c4ca404c1e447c6`

Response from subgraph contains contract address in payer filed. Is that a mistake?

```
{
  "data": {
    "receipt": {
      "receiptNumber": "1",
      "payer": "0x9e0ba8b2a6e9ffc74a013c1a0e177f73f0190e58"
    }
  }
}
```

**Comment by julien51** [comment]
> Response from subgraph contains contract address in payer filed. Is that a mistake?

Yes it is! We'll get a fix ASAP!

**Comment by julien51** [comment]
@boskiv We have merged the code and we will trigger a Subgraph upgrade shortly!
