### ISSUE TITLE
Failed to show renewal reason for the lock when it should be there

### ISSUE THREAD

**Issue by Sal1y-H** [unlock-protocol/unlock#12009]
**Is your feature request related to a problem? Please describe.**
Two of my memberships have expired / not renewed however I do not know if this is a lack of USDC, or an issue with the renewal itself. 
**Describe the solution you'd like**
I would like to be able to click on the non-renewed key and for it to show something like 'did not renew due to inadequate funds on X date'. Or, if the person has cancelled then it would say 'did not renew due to cancellation'.
Ideally, we could also easily pull off a daily or weekly report which gave this data in a spreadsheet or similar. e.g. columns would be:
Nonrenewed wallets - date attempted - reason for failure

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
@Sal1y-H We actualy show _some_ details about renewals... Can you check if you have that info on your end? 
Also could you add me as a lock manager temporarily on your lock so I can investigate more closely?

<img width="962" alt="Screenshot 2023-06-01 at 9 30 39 AM" src="https://github.com/unlock-protocol/unlock/assets/17735/eac9bc66-c6f5-4f9f-879a-c72f14dc4f41">

**Comment by Sal1y-H** [comment]
No. I only see this much: 
<img width="692" alt="image" src="https://github.com/unlock-protocol/unlock/assets/109059043/b5be207e-e447-4644-8153-90afa4774eb9">

Where do I find your address to add you as a lock manager?

**Comment by Sal1y-H** [comment]
I dont' know if this reopens it or not, but as per Discord. I do not see all the information above on my Dashboard? let me know if this is an error my end. 
<img width="728" alt="image" src="https://github.com/unlock-protocol/unlock/assets/109059043/14dd6667-2237-46d0-beda-0315b137a31d">
