### ISSUE TITLE
many files/variables need to be camel-Cased

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1203]
**Describe the bug**
many files like currencyconvert.js and staticdemo.js need to be camel-cased to fit the style guide

**Comment by cnasc** [comment]
Not starting on this yet, but an idea to detect places where this is necessary may be to extract features from the codebase (filenames, identifiers in a file...) and then detect if they are already camel-cased. If not, we can use something like [wordninja](https://github.com/keredson/wordninja) to split them and then transform to camelcase.

Not to overengineer it, but it seems like it could make a tedious job into something semi-automated.

**Comment by julien51** [comment]
`staticdemo` has been fixed for a little while. 
A quick lookup did not show any issue so we can close this as soon as #1676 has been merged.

**Comment by julien51** [comment]
Actually! I just found `mutationobserver`... so need to fix that too!
