### ISSUE TITLE
Splitting up the creator dashboard and the paywall app

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1205]
Both the creator dashboard an the paywall are currently inside a single app... I believe we should strongly consider splitting them in 2 different apps.

The main rationale for that is that the creator dashboard does a lot more things and loads a lot more data than the paywall... which makes the paywall app particularly bloated and slow while it needs to be especially speedy and efficient.

I am sure there would be shared components and libraries between the 2, but I think we should start considering splitting them because the longer we wait the more painful it will be.

**Comment by cnasc** [comment]
This is definitely a smart idea
