### ISSUE TITLE
Verify Transparent Proxy!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12100]
It looks like our transprent proxy contract is not verified...

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/12104#pullrequestreview-1462731496

**Comment by clemsos** [comment]
polygon ref https://polygonscan.com/address/0xf1cd0131c2b226dae452a68ae5fb0cbe8ab8f482#code

**Comment by clemsos** [comment]
hmm so the process was tedious as I had to do the network 1 by 1. Then it is also better /cheaper as it doesnt require to redeploy empty locks anymore. It went as follow

- checkout a commit with the correct OZ version (4.9.2 here)

now on the block explorer
-  go to Unlock 
- find a deployed lock where proxy isnt verified (use latest `create at version` tx, then `newLock` from events) - .eg https://goerli.basescan.org/address/0xee872e973f8782ba3b133df061ae0860a3471ce2#code
- in the "internal txs" tab, find the creation tx https://goerli.basescan.org/tx/0x74bc52570fad1cd1529f30d347a62931ed2db946cdb57d1e0667eef2f4193a04
- pass the param creation to the tx (decode input data)
- pass these params to the cli util

```
yarn hardhat verify-proxy --network baseGoerli --transparent-proxy-address 0xee872E973F8782ba3B133Df061ae0860A3471Ce2 --calldata 0x6eadde430000000000000000000000007e926a05710f400b3d87c11e3ceca3e27eb6d744ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002386f26fc10000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000a63727970746f6c696e7800000000000000000000000000000000000000000000 --lock-version 12
```

**Comment by clemsos** [comment]
also you have to comment the ```require('@openzeppelin/hardhat-upgrades')```  in `hardhat.config.js` L14 to prevent verify from throwing
