### ISSUE TITLE
Old logo apears as image when sharing the .com URL on Telegram

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12105]
**Describe the bug**
When sharing Unlock-Protocol.com on Telegram, the old red logo appears.

**To Reproduce**
Share .com on Telegram

**Expected behavior**
When sharing .com on Telegram, the new logo should be the image.

**Screenshots**
Attached
![Screen Shot 2023-06-05 at 10 07 33 AM](https://github.com/unlock-protocol/unlock/assets/32484647/56ebaddd-e414-416f-bbf1-a94085a2a671)

**Comment by julien51** [comment]
I think that is because Telegram caches stuff .... _forever_ and we have no way to change it :(
