### ISSUE TITLE
Favicons for Apps by Unlock Labs in Chrome browser tabs are the old red Unlock logo

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12106]
**Describe the bug**
The favicons for Apps by Unlock Labs (Dashboard, Events, Certifications) in Chrome browser tabs are the old red Unlock Logo.

**To Reproduce**
1. Visit any app
2. Look at favicon in a browser tab

**Expected behavior**
The logo should be updated

**Comment by julien51** [comment]
This has been fixed!
