### ISSUE TITLE
Unlock account not recognized

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#12160]
**Describe the bug**
Unlock account not recognized as logged in disconnect modal 

https://github.com/unlock-protocol/unlock/assets/20865711/a7d9e8be-a6d6-4b3d-8acf-1156ff4bf486

**To Reproduce**

1. Go to every page in our app
2. Login in with `unlock-app`
3. Reload the page and click on the address 
4. The popup that shows ask us to login-in even if we have already logged-in 

**Expected behavior**
See the popup with account details and `Disconnect` button 

<img width="400" alt="Screenshot 2023-06-13 at 19 48 41" src="https://github.com/unlock-protocol/unlock/assets/20865711/dbb33dfc-4428-4d6e-a12f-e91f75901572">

**Screenshots**

**Comment by searchableguy** [comment]
This is expected for unlock accounts since we only store the provider in memory for security.
