### ISSUE TITLE
Events: Require Registration Approval

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12180]
**Is your feature request related to a problem? Please describe.**
Organizers of free events often want to approve guests to limit who can attend. This feature is often mentioned by organizers using Luma.

**Describe the solution you'd like**
Allow organizers to approve guests, airdropping (walletless) a ticket after approval. 

**Describe alternatives you've considered**
For paid events, enable organizers to approve guests. Guests would receive an email allowing them to purchase a ticket.

**Additional context**
You can try the organizer's journey by creating an event on Luma [here](https://lu.ma/create). 

You can try the guest journey for applying to attend an event on Luma [here](https://lu.ma/urx96iw8).

Luma's Event Creation Flow for registration approval:
Access control for organizers: 
![Screen Shot 2023-06-15 at 4 06 39 PM](https://github.com/unlock-protocol/unlock/assets/32484647/b93538a0-1abc-4bb0-bf2d-334165a681ee)

Registration for guests: 
![Screen Shot 2023-06-15 at 4 07 05 PM](https://github.com/unlock-protocol/unlock/assets/32484647/09d5edaf-c765-4ecc-8ac5-121e3df6447b)

Approval dashboard for organizers: 
![Screen Shot 2023-06-15 at 4 07 23 PM](https://github.com/unlock-protocol/unlock/assets/32484647/45e3552d-1c5b-42e9-ae1f-de378dfc0262)

**Comment by julien51** [comment]
I think it is doable but requires a significant lift. Do we have any customer for this?

**Comment by patrickworkman** [comment]
Edge & Node and Spark Labs (Paris weekly meetups) have both requested this feature.

**Comment by julien51** [comment]
Shipped! https://github.com/unlock-protocol/unlock/pull/13214
