### ISSUE TITLE
Make an input box in Withdrawal dialog

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#12193]
**Is your feature request related to a problem? Please describe.**
When you withdraw funds from a contract you should specify how many funds exactly you want to move.
For now, it's super inconvenient to get whole numbers to withdraw. For example, it's impossible to withdrawal 100 or 1000

**Describe the solution you'd like**
Make an input box instead of a range.

**Describe alternatives you've considered**
Make the range more precise than just 1%

**Additional context**
<img width="554" alt="Screenshot 2023-06-19 at 2 39 21 PM" src="https://github.com/unlock-protocol/unlock/assets/1939783/05781da1-a20a-4b36-96a7-a6249864def6">

**Comment by julien51** [comment]
Duplicate https://github.com/unlock-protocol/unlock/issues/11944 :)
