### ISSUE TITLE
Ucollect.me

### ISSUE THREAD

**Issue by MiroRadenovic** [unlock-protocol/unlock#12194]
![MicrosoftTeams-image (12)](https://github.com/unlock-protocol/unlock/assets/3492186/c41b84f7-43a3-45d4-b9e3-870403780f63)

# Proposal Summary
Web2 platforms have created an oversaturated market, where users focus on accumulating followers, leading to a lack of genuine interaction and loyalty, and in the pursuit of followers and visibility on social platforms, the platforms themselves primarily benefit.

We believe that with blockchain, it is possible to reclaim ownership of work and prioritize building loyal communities without intermediates. This can be accomplished only if we focus on building the best UI and UX to onboard Web2 users.

For this reason, we are building Ucollect.me: a platform for creating and nurturing tokenized communities.  
Ucollect.me gives anybody the tools to create utilities for tokenized communities by relying on Unlock Protocol for advanced membership features.  

The goal of our project is to give ownership of communities to people and remove the dependencies of centralized social platforms.

This grant application seeks funding for a deeper integration of Unlock Protocol as the default protocol for creating a membership. We believe that this partnership is highly compatible, and it can definitely benefit both parties.  

<img width="1543" alt="Screenshot 2023-07-09 at 07 56 37" src="https://github.com/unlock-protocol/unlock/assets/3492186/71fd9f9b-d5b2-4f83-b595-c6b97214b491">

## Background
My name is Miro Radenovic, and I have 20 years of experience in software development. As an entrepreneur, I have launched 2 successful companies here in Italy with 50+ employers:
- https://www.dev4side.com/ : a software factory specialized in complex cloud web applications
- https://intranet.ai/: a SAAS company that delivers an intranet for Microsoft 365.
I'm currently all-in in web3, and I have started https://demind.io, with the primary goal of creating UCollect.ME.

## Description
With the creation of UCollect.ME, we want to allow creators to take back control of their communities and revenue models. This video that we create should summarize our primary goal:  https://www.youtube.com/watch?v=I9qGHOQuawk

Even if our first focus is the creator's economy, the platform is flexible enough to cover different use cases:
- **Brands**, can create loyalty programs
- **Artists**, can sell tickets as tokens
- **Organizations** can launch tokens to crowdfund. 
- _and many more_

By providing a flexible platform with great UI/UX and no-code tools, UCollectME will allow anyone to shape it for their specific needs.

### Core features 
What will be implemented for the launch and are part of this grant application
- Creation of tokenized memberships: minting of unlock's smart contracts
- purchase of minted unlock's tokenized membership
- Simple onboarding of web2 users: social login with the integrated noncustodial wallet. Metamask is also supported
- Importing of any erc721 token
- creation of a profile and posting similar to socials
- creation of token-gated utilities

## More on this project
The project aims to be built bottom-up, with the final goal of becoming a DAO.
If anyone is interested in being part of the beta launch or following/joining our project, please join our discord: https://discord.gg/4ZvjtkK8XA 

### Website URL

https://ucollect.me

### Twitter

@ucollectme

### LinkedIn

https://www.linkedin.com/in/miroradenovic/

### Discord handle

miroblocks

### Completion time

2-3 months

### Team

The team behind this project is Demind.io, which is a web3 company founded by Miro Radenovic.
We are included in this project our best resources, taken from [Dev4side Software SRL](https://www.dev4side.com/) and [Intranet.ai,](https://intranet.ai/) which are part of the same company groups to deliver ucollect.me
I will include all the users working full-time on this project:
- **Miro Radenovic**, Founder: https://www.linkedin.com/in/miroradenovic/
- **Raffaele Brivio**, CTO:  https://www.linkedin.com/in/raffaele-b-0a470580/
- **Giacomo Stelluti**, developer: https://www.linkedin.com/in/gsscoder/
- **Samuel Gratarola**, developer: https://www.linkedin.com/in/samuel-gratarola/
- **Serena Cadoni**, marketing: https://www.linkedin.com/in/serenacadoni/
- **Samantha A**, marketing: https://www.linkedin.com/in/samantha-augello-b92152238/

### Milestones
The development of UCollectME **started at the beginning of 2023**, and we are really close to the launch.

We are aiming to release the following:
- a first beta will be launched on July 2023. The beta will allow users to mint collections using unlock. Web3 Users will be invited to test it
- a second web2 beta, at the end of August 2023, which will target web2 users
- we will launch the platform in September/October 2023. 

### Requested grant amount
300 UDT

### Anything else you think we should know, including why you've requested a particular grant amount
We invite anyone to join our beta to check and review what we are planning to launch in the next months.
Our usage of UDTs will be to stay closer to the Unlock community and start joining the DAO. 

### Is your work Open Source

No, my project does not use an Open Source license.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MiroRadenovic** [comment]
Please let me know if you need any additional info on this application.

**Comment by MiroRadenovic** [comment]
To give a better overview of what we have already built, let me share some screenshots:

<img width="970" alt="Screenshot 2023-07-09 at 07 56 04" src="https://github.com/unlock-protocol/unlock/assets/3492186/66c83cd0-dba3-4b16-9876-b89daee6bc00">
<img width="1199" alt="Screenshot 2023-07-09 at 07 58 16" src="https://github.com/unlock-protocol/unlock/assets/3492186/69a6bd69-e679-47cb-a780-9dfc369788a3">
<img width="1589" alt="Screenshot 2023-07-09 at 08 04 54" src="https://github.com/unlock-protocol/unlock/assets/3492186/1b992d73-389a-4d3f-a0bb-aa7d7ff99e92">
<img width="1589" alt="Screenshot 2023-07-09 at 08 06 42" src="https://github.com/unlock-protocol/unlock/assets/3492186/c3b4f70a-796e-4bb2-9a12-a7d9a942e792">
<img width="1581" alt="Screenshot 2023-07-09 at 08 31 04" src="https://github.com/unlock-protocol/unlock/assets/3492186/c7c4728a-69c7-446a-af1e-8aedeee1db31">
<img width="1608" alt="Screenshot 2023-07-09 at 08 36 18" src="https://github.com/unlock-protocol/unlock/assets/3492186/f271281d-75ff-4c99-8971-1ca02e16c185">
<img width="1608" alt="Screenshot 2023-07-09 at 08 37 05" src="https://github.com/unlock-protocol/unlock/assets/3492186/dd189303-b02c-4054-9ab5-5e23a9ed8c0d">
<img width="1608" alt="Screenshot 2023-07-09 at 08 44 04" src="https://github.com/unlock-protocol/unlock/assets/3492186/e09701d1-4f2c-4796-a915-7df3e417c1f0">
<img width="1608" alt="Screenshot 2023-07-09 at 08 43 40" src="https://github.com/unlock-protocol/unlock/assets/3492186/0a59e350-7250-4268-ae05-f5b79f8f6561">

**Comment by ccarfi** [comment]
<img width="868" alt="Screen Shot 2023-07-20 at 6 30 11 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/3d8e8a6c-128f-43b4-bc11-ca0b3cb0c398">

i'm loving the direction that UCollectMe is going https://ucollect.me/manifesto

**Comment by MiroRadenovic** [comment]
### I have an additional update! 
- We have launched our beta with our community: https://beta.ucollect.me/showcase 
- We have updated our roadmap: https://ucollect.me/roadmap

**Comment by MiroRadenovic** [comment]
I want to share with the community a video that demonstrates major features we built on Ucollect.me. This video has been shared internally with our community in Discord for the launch of the beta.

- part 1: https://www.youtube.com/watch?v=-6-ENdLGVkI
- part 2: https://www.youtube.com/watch?v=AHks_JPU6gU
- part 3: https://www.youtube.com/watch?v=UHmRmO4CJS8

**Comment by MiroRadenovic** [comment]
Hello back Unlock, we made it, we have lauched ucollect.me in production and everythig is live 🚀

It took us more than expected, but we finally made it. Now ANYONE can create and launch tokenized memberships with unlock without any web3 complications as we have implemented account abstraction:

- ✅ login with your email, and [ucollect.me](http://ucollect.me/) creates a wallet for you
- ✅ create an NFT Membership, and [ucollect.me](http://ucollect.me/) deploys it on the blockchain
- ✅ mint and subscribe to membership, and [ucollect.me](http://ucollect.me/) pays for the transaction

And everything is NON-CUSTODIAL! You don't like [ucollect.me](http://ucollect.me/)? Export your keys and enjoy web3!

🥳

**Comment by ccarfi** [comment]
Thank you for the update, @MiroRadenovic! Will make sure the members of the Unlock DAO are aware of the progress!

**Comment by ccarfi** [comment]
@MiroRadenovic Thank you for sharing the progress on UCollectMe with the community! Indeed, if you are ready to submit your proposal to the Unlock DAO, would recommend sharing your proposal on Tally for an official, onchain vote from the community! https://docs.unlock-protocol.com/governance/grants-bounties/udt-grantee-handbook#final-delivery-share-the-results-show-your-work

**Comment by ccarfi** [comment]
And you can certainly remind the members of the community who reviewed the original proposal and the temp check on Snapshot of your progress and point them to the Tally proposal when it's live! Here was the original Snapshot proposal https://snapshot.org/#/unlock-protocol.eth/proposal/0x81f62bc5a56f4dcfcca68381d48d4dd6ad07a1ce7db57faff9e6d1dcf97d38bf

**Comment by ccarfi** [comment]
<img width="1100" alt="Screen Shot 2023-12-22 at 2 30 49 PM" src="https://github.com/unlock-protocol/unlock/assets/214760/78f2dd74-4e88-4415-bbac-80b94b268c57">


also, loving seeing all the UcollectMe locks showing up in production!
https://dune.com/queries/2386609/3913363

**Comment by ccarfi** [comment]
@MiroRadenovic  Thank you for sharing the progress on UCollectMe with the community! Indeed, if you are ready to submit your proposal to the Unlock DAO, would recommend sharing your proposal on Tally for an official, onchain vote from the community! https://docs.unlock-protocol.com/governance/grants-bounties/udt-grantee-handbook#final-delivery-share-the-results-show-your-work

**Comment by ccarfi** [comment]
Onchain vote is open here: https://www.tally.xyz/gov/unlock/proposal/40096337376636285759230997527484615006160927132329526478786055377967930828651?chart=1

**Comment by MiroRadenovic** [comment]
Thank you Unlock! our grant has been approved!
