### ISSUE TITLE
Events: Add 'Event Dashboard' for the Lock organizers have created

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12238]
**Is your feature request related to a problem? Please describe.**
After creating an event, organizers want to manage attendance. This is achieved in Dashboard through our Lock Management options. However, organizers need the option to manage their lock on the event details page they've created. 

**Describe the solution you'd like**
Add 'Event Dashboard' under 'Tools for you, the Lock Manager' with the subtext 'See who is attending your event, how many tickets remain, and edit advanced details.' 

**Describe alternatives you've considered**
Change 'Tools for you, the Lock Manager' to 'Your Event Management Toolbox.' Event organizers must become more familiar with a 'Lock 'With context. 

ATX DAO has requested this!

**Additional context**
This is Eventbrite's Event Management Dashboard for potential copy
<img width="925" alt="Screen Shot 2023-06-26 at 9 29 47 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/1633abda-1550-41d3-af51-d6a0de9c1387">

This is Luma's Event Management Dashboard for potential copy
<img width="458" alt="Screen Shot 2023-06-26 at 9 32 00 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/e990b958-540c-4c94-8fd2-c1529ea8f5ff">
<img width="452" alt="Screen Shot 2023-06-26 at 9 32 09 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/b213d116-bd13-47ab-a5a8-9cdf25d78b4d">
<img width="431" alt="Screen Shot 2023-06-26 at 9 32 16 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/aefe2605-17ec-40b5-9ced-fa0402f3b9b2">

**Comment by julien51** [comment]
Merged! Coming live on next prod deploy!
