### ISSUE TITLE
Events: Make first name and last name default fields on event details pages

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12237]
**Is your feature request related to a problem? Please describe.**
Most event organizers want to know the first/last name and email addresses of people attending their events. 

**Describe the solution you'd like**
Enable organizers to select what information they want from attendees. This could be done by including an 'Attendee Information' section with the subtext 'What do you want to know about your attendees.' First Name, Last Name, and Email address would be the default, with the option to make First Name and Last Name optional.

Include a 'Custom' toggle, allowing organizers to create a custom field request information from attendees (I.e., 'Are you an AWT member, ATX WiW3, or both'). This custom feature would include an option to make the field optional or required.

ATX DAO has requested this!

**Describe alternatives you've considered**
Add First Name and Last Name collection on event details pages as a default—a few event organizers do not want to know the names of attendees. Anons can use their anon name if they wish to remain anonymous. 

**Additional context**
We could modify the copy within the Metadata' section of Checkout Builder > Locks to focus on event organizers' needs
<img width="487" alt="Screen Shot 2023-06-26 at 8 56 22 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/96e177fa-bdf9-46d9-a55d-6ce881a670a1">
 and include it within the Events creation flow.

**Comment by julien51** [comment]
Hum, I am not sure we should complicate the flow to create events, but we can easily add and field for fullname on the default checkout for events.

**Comment by julien51** [comment]
Merged! Should go live today or tomorrow!
