### ISSUE TITLE
Events: Option to remove wallet or ENS capture from Event Details Page for free events

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12236]
**Is your feature request related to a problem? Please describe.**
Event organizers host free events for many audiences, most of whom still need a wallet or ENS. These organizers aim to encourage people to register for their event, not introduce the concept of a wallet or ENS, which can create friction.

This was requested by ATX DAO, which hosts multiple meetings a month to educate people who are crypto-curious and need a wallet or ENS. 

**Describe the solution you'd like**
Enable organizers to remove wallet or ENS capture within the event creation flow in Events. This would be a toggle in the 'Price and Capacity' section of Event creation. The copy would be 'Wallet-less registrations only' which the subtext 'Disable the option for attendees to mint a ticket with their non-custodial wallet.' 

Capturing a wallet or ENS should remain the default in the creation process.

When wallet or ENS capture is disabled, we could default deployment to the network with the lowest gas (Gnosis). The email sent to people receiving a wallet-less airdrop would not reference OpenSea or wallet transfer instructions. 

**Describe alternatives you've considered**
Redirect users on an Event Details Page to a tutorial about creating a wallet (Metamask) under the Wallet or ENS capture. 

**Additional context**
<img width="587" alt="Screen Shot 2023-06-26 at 8 41 11 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/83c5705b-6b11-4fff-9cac-e117bd0b5bc3">

When disabled, users can only register with an email address.
<img width="256" alt="Screen Shot 2023-06-26 at 8 44 51 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/d1b10371-0a23-4043-8e83-96635e9789d7">

**Comment by julien51** [comment]
> This was requested by ATX DAO, which hosts multiple meetings a month to educate people who are crypto-curious and need a wallet or ENS.

I think that's a reason to make sure users who _have_ a wallet can optionally (as it is now) enter its address, not a reason to remove it!

Maybe we can it more obvious that this is optional but I think it is important that leave it.

> Redirect users on an Event Details Page to a tutorial about creating a wallet (Metamask) under the Wallet or ENS capture.

That's a good idea!

**Comment by patrickworkman** [comment]
If we decide not to enable organizers to remove the wallet and ENS capture, organizers who want it removed will use Eventbrite or Luma. 

Why is this a trade-off we are making as we prioritize Events?
