### ISSUE TITLE
Download all receipts

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12234]
We currently have the ability for lock managers to show individual receipts.. and we also need to add the ability to download _all_ receipts from the `receipts` section in the settings.

**Comment by julien51** [comment]
This has been requested by Dappcon!

**Comment by searchableguy** [comment]
What format do we want for the receipts when downloading? Some kind of zip with receipts in pdf? Spreadsheet with entires?

**Comment by julien51** [comment]
Let's just reuse what we already have? PDFs ?
