### ISSUE TITLE
Renewal fee second time goes to unrecognised wallet

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#12253]
**Describe the bug**
I have created a checkout page with paywallConfig
```
https://app.unlock-protocol.com/checkout?redirectUri=https://spreadfighter.web.app&paywallConfig=%7B%22icon%22:%22https://storage.unlock-protocol.com/c1dc6bc4-be85-4776-af01-59bcbf36aeb8%22,%22locks%22:%7B%220x9e0ba8b2a6e9ffc74a013c1a0e177f73f0190e58%22:%7B%22network%22:137%7D%7D,%22pessimistic%22:true,%22referrer%22:%220x6d8b14b30d53de96a3698d03b80c0b2c845d92e0%22%7D
```

Make a new purchase by this link. and set a limit with 2 USDT
This transation: `https://polygonscan.com/tx/0x0339d19f455578267d34b27c8b156b95efa742566c1aa60ec606fe3429d8bcfe`
Got a refer fee back to wallet `0x6d8b14b30d53de96a3698d03b80c0b2c845d92e0` that is correct

Wait a day to key expired and automatically renewed

This transaction: `https://polygonscan.com/tx/0xff2fc0e977cc9465abdab713d353102315fe8b4030b5cff7f294dc424a615588`

What is a wallet number : `0x479f3830fbd715342868ba95e438609bce443dfb` from recent transaction? 

Why it does not refer wallet that used for first payment `0x6d8b14b30d53de96a3698d03b80c0b2c845d92e0` 

Lock adress is: `0x9e0ba8b2a6e9ffc74a013c1a0e177f73f0190e58`

More than all renewals goes to that `0x479f3830fbd715342868ba95e438609bce443dfb` unrecognised wallet. Looks like a refer was changed somehow after first purchase.

**Comment by julien51** [comment]
The `referrer` is set by the sender of the transaction on any payment transaction. Here we are sending these renewal transactions (but you can also send them if you want)... and we set the teams multisig wallet as referer. This is how we currently cover the gas fees for these renewals.

**Comment by boskiv** [comment]
But 0x6d8b14b30d53de96a3698d03b80c0b2c845d92e0 wallet does not get a reward from `Renew Membership For ` method
