### ISSUE TITLE
Events: Add 'Manage Your Event', directing to Lock Management Page on Homepage

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12265]
**Is your feature request related to a problem? Please describe.**
When organizers create an event using Events and visit the Events homepage, there is no option to manage their event.

**Describe the solution you'd like**
Organizers should have the option to manage their events from the Events homepage. A 'Manage your Event' CTA directing to the Lock Management dashboard would enable them to do so. This CTA should be next to the 'Create your event now' CTA.

**Describe alternatives you've considered**
Add 'Manage your Event to the top navigation bar. This would provide us space to add additional features (FAQ, tutorials, etc) when they are available.

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/12374

**Comment by julien51** [comment]
We implemented a basic way to list all events by an organizer: 
<img width="1074" alt="Screenshot 2023-08-11 at 4 12 26 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/2fdb939a-0c17-4067-befa-aff4f94f0c13">
