### ISSUE TITLE
Locks with Unlimited Keys shows as Sold Out

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#1227]
## Description
When creating a lock with unlimited keys the paywall show the lock as sold out without having sold a single key

## Reproduce
http://projects.mombartz.com/unlock

## Expected behavior
Should show lock as purchasable and never be sold out

## Screenshots
**Dashboard**
![image](https://user-images.githubusercontent.com/1377389/51722200-9c9ca800-2022-11e9-8c67-33f5c0afaa4d.png)

**Paywall**
![image](https://user-images.githubusercontent.com/1377389/51722214-a6bea680-2022-11e9-8bed-a6e07c0e79b5.png)

**Comment by cnasc** [comment]
I believe this is no longer an issue as of #1226

**Comment by julien51** [comment]
Confirmed! Closing as soon as this is deployed!
