### ISSUE TITLE
Mobile Paywall allows for Scrolling

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#1228]
## Description
On mobile (iOS chrome) the paywall allows for unpurchased content to be scrolled

## Reproduce
visit following site on mobile (iOS chrome) http://projects.mombartz.com/unlock or https://www.ouvre-boite.com/members

## Expected behavior
should not allow content to be scrolled

## Device
**Smartphone**
 - Device: iphone x
 - OS: iOS 12.1.2
 - Browser: chrome

**Comment by julien51** [comment]
@cellog This is probably for you!

**Comment by julien51** [comment]
Do we need an iOS device in the office to test this with?

**Comment by cellog** [comment]
I have my iPad, Chris has an iPhone too, should be covered but can't hurt to have a couple

**Comment by cnasc** [comment]
Been poking around with the dev tools trying a few different iOS scroll-killers I've seen online. The only one I've gotten to work is setting `position: fixed;` on the `body`, but I'm not sure if that's a palatable solution.

**Comment by cellog** [comment]
Ooh, position:fixed will screw with content, you can see it with our demo. Perhaps the solution is to either integrate the paywall into the site, or to go to a separate page with complete control over content?

**Comment by cnasc** [comment]
To be fair, I'm not 100% certain that it's not Safari being weird about overriding the `touchmove` event from the console. This may be something that works delivered in another fashion, since there are posts from this past year recommending doing it that way.

**Comment by cnasc** [comment]
@julien51 and I talked this through and came up with an alternative to stopping scrolling entirely. We can grow the height of the paywall the further the user scrolls down the page, until eventually the page body is obscured entirely. I tested, and we are able to work with the `window` `scroll` event.
