### ISSUE TITLE
Events: Change Tools > Event details copy and direct to 'Edit your event details page'

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12336]
**Is your feature request related to a problem? Please describe.**
After creating an event, organizers are presented with tools to 'Event Details'. The copy references a contract (Lock) and 'detail' without reference to their event details page. When organizers click 'Edit Details' link, are directed to the 'Edit Properties', which references 'Add rich properties and data to your NFT memberships', which may be confusing to organizers creating an event that creates tickets. 

**Describe the solution you'd like**
Change 'Event detail' to 'Edit your event details page' with the subtext 'Edit the date & time, location, and preview the ticket your attendees will receive'. When the 'Edit Details' CTA is clicked, direct organizers to 'Event ticketing' in NFT properties. Change 'Event ticketing' to 'Edit your event details page' with subtext 'Add details for your event. These will be displayed on your event details page (add URL to the organizer's event details page), and NFT marketplaces support your tickets.'

**Describe alternatives you've considered**
Move 'Metadata' from the top of 'Edit Properties' below 'Certification' so 'Basic' appears first. 'Metadata' is an advanced feature for event organizers.

**Comment by julien51** [comment]
We will soon have on page editing for simplicity.
