### ISSUE TITLE
Events: Change 'Deploy your contract' CTA to 'Create your event'

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12338]
**Is your feature request related to a problem? Please describe.**
Organizers creating an event are asked to 'Deploy your contract' without context that their event is a 'contract'.

**Describe the solution you'd like**
Change 'Deploy your contract' CTA to 'Create your event'.

**Describe alternatives you've considered**
Introduce organizers to a 'What is a contract? URL, directing them to the [Unlock Glossary ](https://docs.unlock-protocol.com/getting-started/glossary/).

**Comment by julien51** [comment]
Fixed!

**Comment by patrickworkman** [comment]
The CTA remains 'Deploy your contract' vs 'Create your event' in Events.

![Screen Shot 2023-08-11 at 2 35 34 PM](https://github.com/unlock-protocol/unlock/assets/32484647/e95ef7cd-4b81-4425-af6b-cd0e7fbe1aac)
