### ISSUE TITLE
Can not withdrawal money from contract

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#12331]
**Describe the bug**
Uncaught (in promise) Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)

**Additional context**
Lock address: 0xb6db2c1923dad7411dad2c0c16c9997e5a481fe8

**Comment by boskiv** [comment]
Able to do it with polygonscan write proxy method. But you should fix it on your side :)

**Comment by julien51** [comment]
Related: https://github.com/unlock-protocol/unlock/issues/11944
