### ISSUE TITLE
Can't find a way to disconnect from the Events dapp using Brave

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#12342]
**Describe the bug**
Using Brave on laptop, cannot see any way to disconnect from the app.

**To Reproduce**
Using Brave, go to https://events.unlock-protocol.com 
For some reason (not sure why) the Events app was showing me as connected. 

Tried to disconnect and could not find a way to do so. 

(On the other hand, using the Chrome browser and proper wallet, things work as expected.)

**Expected behavior**
I would expect to see some way to "disconnect."

**Screenshots**
https://www.loom.com/share/fd220211250049778398413225fe83af?sid=fef511c6-865b-4a16-802c-a4154d50583f

**Comment by julien51** [comment]
@ccarfi Did you previously connect as an "unlock account" ?

**Comment by ccarfi** [comment]
unsure. maybe?

**Comment by ccarfi** [comment]
looking at the 0x address for the wallet in the screenshot, i don't recognize it from my "normal" wallets, so yes, was probably an unlock account at some point.

**Comment by julien51** [comment]
Ok, that clarifies things. @searchableguy can we add a disconnect message when the user is an unlock account for whom we have a valid token but no password?

**Comment by julien51** [comment]
I think this is relted to that @searchableguy https://github.com/unlock-protocol/unlock/issues/12321

**Comment by searchableguy** [comment]
closing this one. Opened a PR to fix this. Tracking later changes in the other issue.
