### ISSUE TITLE
Events: Add Africa as an available Time Zones

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12361]
**Is your feature request related to a problem? Please describe.**
African cities are not included in time zones.

**Describe the solution you'd like**
Add African cities to available time zones.

**Comment by julien51** [comment]
They are actually in there : 
<img width="837" alt="Screenshot 2023-08-08 at 1 09 46 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/f3dbb1aa-d74a-4c3d-b383-81c921a466af">
