### ISSUE TITLE
Add "The Problem" section to EVENTS page

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#12367]
There is a section called "The Problem" on the main unlock protocol home page. 

We want to add a similar section (with unique copy) to the EVENTS page.
<img width="942" alt="Screen Shot 2023-07-13 at 4 15 50 PM" src="https://github.com/unlock-protocol/unlock/assets/214760/138570a6-5762-4f24-b015-7ed70fc29051">

sample from the main unlock protocol page, above

For the "The Problem" section on the EVENTS page, please use the following copy and imagery.

_Small superheader:_
**The Problem**

_Header:_
### Legacy ticketing solutions don't meet the needs of web3 and crypto event organizers

_Left copy:_
Your web3 or crypto event isn't walking the walk, and is using a legacy ticketing solution like Eventbrite, Meetup or Luma instead of embracing the very technology your attendees expect you to champion.

_Middle copy:_
You're losing money on ticket sales because of upsells, hidden fees, and slow payouts from your existing ticketing provider.

_Right copy:_
Your attendees stop engaging the moment the event is over, and are not continuing conversations as an ongoing, connected community.

For the images, let's re-use several images from the unlock-protocol home page

for the _left copy_ image, please re-use the gum stuck on shoe https://unlock-protocol.com/images/illustrations/img-stuck.svg
for the _middle copy_ image, please re-use the wallet https://unlock-protocol.com/images/illustrations/img-wallet.svg
for the _right copy_ image, please re-use the people talking https://unlock-protocol.com/images/illustrations/img-goodvibe.svg

**Comment by patrickworkman** [comment]
Nice work. Ship it!
