### ISSUE TITLE
Web 3.0 provider lag lets me see the content

### ISSUE THREAD

**Issue by patrykadas** [unlock-protocol/unlock#1236]
At the initial load of the website, I can the article, until it disappears after my wallet balance is fully loaded.

Preview:
https://drive.google.com/file/d/1mkxrt52Qj8rLDYIGE8QqyWMaxe0lRYla/view?usp=sharing

I'd expect the loading spinner that says 'Checking your access right' and only after the Web 3.0 provider is fully loaded seeing the content or the payload with the buy-in option.

I can help you with the prototype of this if you'd like! 

BTW. Great job developing this, can't wait to see use-cases with personal tokens :)

**Comment by julien51** [comment]
@patrykadas Thanks! You are right. We are working on something both faster and a bit smarter.

**Comment by cellog** [comment]
this is implemented, thanks for the report
