### ISSUE TITLE
"Error: Invalid parameters: must provide an valid address." in the demo app

### ISSUE THREAD

**Issue by PetrKubes97** [unlock-protocol/unlock#12375]
**Describe the bug**
When I go to https://app.unlock-protocol.com/locks, click "connect it now", wallet opens, I click "confirm ownership" and then nothing happens.

In the logs, it says: "Error: Invalid parameters: must provide an valid address."

**Expected behavior**
Wallet gets connected.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Arc
- Version 0.112.0
- TrustWallet

**Comment by julien51** [comment]
Thanks @PetrKubes97 . I am not able to reproduce. Would you be able to send a screenshot by chance?
Also do you use WalletConnect to connect with TrustWallet?
Thanks

**Comment by PetrKubes97** [comment]
Hi, I've tried it again today and worked, so not sure what was causing the issue.
