### ISSUE TITLE
Update destination for CTA buttons on EVENTS by Unlock Labs page

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#12373]
There are two CTA buttons on the EVENTS by Unlock Labs landing page
<img width="795" alt="Screen Shot 2023-07-14 at 12 51 52 PM" src="https://github.com/unlock-protocol/unlock/assets/214760/a7181fa8-e1f7-4bc5-93f0-7b4422d0d55b">

<img width="1152" alt="Screen Shot 2023-07-14 at 12 51 59 PM" src="https://github.com/unlock-protocol/unlock/assets/214760/d4f3e719-8150-446b-974d-d3b5a5b10161">

Please have both these buttons link to this URL instead of the current destination
[http://unlock-protocol-1.hubspotpagebuilder.com/unlock-protocol-newsletter-signup-0](http://unlock-protocol-1.hubspotpagebuilder.com/unlock-protocol-newsletter-signup-0)

**Comment by julien51** [comment]
@ccarfi are we completely removing self serve?

**Comment by kalidiagne** [comment]
> @ccarfi are we completely removing self serve?

PR ready if confirmed https://github.com/unlock-protocol/unlock/pull/12382
