### ISSUE TITLE
Tools menu shows on lock manager dashboard for locks where someone is not the lock manager

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#12372]
is this the expected behavior? it didn't let me airdrop the key, but it let me get all the way through the process.

<img width="1420" alt="Screen Shot 2023-07-14 at 9 59 08 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/c79c8d11-0856-41eb-8314-fa821245926e">

<img width="1426" alt="Screen Shot 2023-07-14 at 9 55 53 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/6ec3ab6a-8aca-4848-8be3-3d1e2f80c3fe">

<img width="1423" alt="Screen Shot 2023-07-14 at 9 56 12 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/0609ffe5-8c40-4ab5-8217-1a92180b30e2">

<img width="1680" alt="Screen Shot 2023-07-14 at 9 56 28 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/c03ae079-96e7-4924-9a96-5dee6b5783cf">

**Comment by julien51** [comment]
We could hide the menu but I generally find it useful to be able to open *some* of the menus... So we decided to keep it since in any case, the user who isn't a lock manager won't be able to do anything harmful anyway.
