### ISSUE TITLE
Checkout Builder: Add Persisent 'Save' CTA to Steps 1 and 2

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12389]
**Is your feature request related to a problem? Please describe.**
When users return to Steps 1 and 2 of Checkout Builder, the only option to save their configuration is to revisit Step 3. This creates friction and needs to be more intuitive.

**Describe the solution you'd like**
Add a 'Save' CTA under the 'Next' CTA on Steps 1 and 2

**Describe alternatives you've considered**
Add a persistent 'Save' CTA below the 'Customize your membership checkout experience. The preview on the left is updated in realtime.' subheader.

**Comment by julien51** [comment]
We should actually remove the save button completely and autosave on changes.
