### ISSUE TITLE
Use discord and/or twitter and/or email to airdrop.

### ISSUE THREAD

**Issue by sherajr** [unlock-protocol/unlock#12390]
**Is your feature request related to a problem? Please describe.**
I was trying to airdrop NFTs to some people who took my course but I don't have all their e-mails, so I have to do a workaround to get the airdrop to function by just putting in my own email multiple times. 
![image](https://github.com/unlock-protocol/unlock/assets/16519706/a0e2e65a-9a08-40e7-8d7b-35ba272d2491)

**Describe the solution you'd like**
It would be nice if one could use the twitter or discord accounts as well so if you don't have their email you can use one of those.

**Describe alternatives you've considered**
Having a checkbox to just have nothing for contact info could work too. But I get why an alert is preferable.

**Additional context**
This is for Airdropping bulk keys or airdropping keys manually.

**Comment by julien51** [comment]
Hello @sherajr We dont have an easy way to identify provenance for Twitter/Discord like we do for emails (+ Twitter's API just became ridiculously expensive for these things), so we're not going to do that...
