### ISSUE TITLE
Enable coupon Discount Codes (hooks) to work from the URL automatically into the checkout

### ISSUE THREAD

**Issue by balive** [unlock-protocol/unlock#12397]
**Is your feature request related to a problem? Please describe.**
There is currently no way to pass a coupon discount code automatically into checkout via the URL.

**Describe the solution you'd like**
By including the ability to add the discount code into the URL, this solves the problem, eg https://domain.com/?discountCode

**Describe alternatives you've considered**
I cannot think of any other way to do this.

**Additional context**
From the developers Discord channel, they suggested this would be possible for these discount codes to be incorporated into the checkout URL, so that a discount was automatically applied into a checkout.

**Comment by julien51** [comment]
That's a neat idea! Let's add a bounty to that one!

**Comment by julien51** [comment]
To complete this idea a bit, we would want the option for that discount code to be passed both in the URL _or_ in the paywallConfig object, exactly as we do for the referrer address.
Once passed, this value should then be pre-set by default on the screen where users enter the discount/promo code, to let users visually identify the discount they are getting, and, optionally, change it to a different value.
