### ISSUE TITLE
DAOsign

### ISSUE THREAD

**Issue by TetianaRiabova** [unlock-protocol/unlock#12405]
### Description

DAOsign is a smart signature and workflow automation platform, with publicly verifiable, cryptographic proofs-of-signature, designed for DAOs and WEB3 companies.

Verifiable Signature is at the core of DAOsign and is based on 3 key proofs: proof-of-identify, proof-of-authority, and proof-of-agreement. Utilizing these proofs, DAOsign provides a platform to design and configure complex workflows that combine smart-contract-based automation with authorized approvals.

![image](https://github.com/unlock-protocol/unlock/assets/122782612/12043cb5-0e2c-431f-b58f-8c1abaa698ae)
![image](https://github.com/unlock-protocol/unlock/assets/122782612/3a28303f-cec5-4f9a-89cb-54892f6f194e)

DAOsign addresses the need for a secure and transparent way to sign, manage, and automate agreements of all kinds with a configurable level of anonymity disclosure.

**Our proposal is to implement DAOsign's Grant Programs use case for Unlock Protocol.** The purpose of this use case is to simplify all stages within the grant program completely. Also, such **governance automation** should improve trust within the Unlock DAO and its community.

![image](https://github.com/unlock-protocol/unlock/assets/122782612/b5b4c0f2-579a-4c95-a389-9dc34c4ef2bc)

### Website URL

https://daosign.org/

### Twitter

https://twitter.com/dao_sign

### Github

https://github.com/DAOsign

### LinkedIn

https://www.linkedin.com/company/daosign

### Discord handle

https://discord.gg/AwnhGFbT8Z

### Completion time

3 months

### Team

Eugene Fine (CEO & Founder) - Over 20 years of building, scaling, and managing technology organizations. Recent experience includes a CTO role at Explorer Surgical Corp., which was recently acquired by GHX, and VP of Engineering at GHX. Eugene is a founder at consideritdone.tech, a Blockchain/WEB3 development studio.
GitHub:[ https://github.com/ConsiderItDone](https://github.com/ConsiderItDone)
LinkedIn link:[ https://www.linkedin.com/in/eugenefine/](https://www.linkedin.com/in/eugenefine/)

Ramil Amerzyanov (CTO) - 15+ years building complex technical architecture and software solutions., focusing on Blockchain/WEB3 technologies over the past 7 years. Recent projects include the Fractional CTO role at Landslide Network and CTO role at consideritdone.tech.
GitHub:[ https://github.com/ramilexe](https://github.com/ramilexe)
LinkedIn link:[ https://www.linkedin.com/in/ramil-amerzyanov/](https://www.linkedin.com/in/ramil-amerzyanov/)

Misha Kushka (Technical Lead) - 6+ years developing Blockchain/WEB3 technical architecture and software solutions. Recent projects include Lead Technical Architect roles at Akiva Capita! Holdings and Avalaunch
GitHub: https://github.com/kushkamisha

Oleksandra Burmenska (Head of Partnerships) - Over 10 years of experience in Business Development and Management roles in Technology organizations, focusing on Blockchain/WEB3 technologies over the past 5 years. Recent projects include contributions to NEAR, Axelar, GnosisSafe, and Avalanche ecosystems.
GitHub:[ github.com/burmenska](http://github.com/burmenska)
LinkedIn link:[ https://www.linkedin.com/in/oleksandra-burmenska/](https://www.linkedin.com/in/oleksandra-burmenska/)

Our portfolio with the previous projects: https://docsend.com/view/fjrvjtyzgm7wgrkj

### Milestones

Grants Use Case Implementation

### Requested grant amount

300 UDT

### Anything else you think we should know, including why you've requested a particular grant amount

Currently, our product is on [**Testnet**](https://testnet.daosign.org/). DAOsign already allows users to store proofs of signature in the IPFS, Ethereum launch is planned in the nearest week. Also, recently, we received grants from SUI and Polkadot, so DAOsign users will be able to use these blockchains for proofs storing purposes soon as well.

Please, take a look at our **pitch deck** with more details: https://docsend.com/view/sbexkxn5su3ahdg8. Here you can also find our other use cases and an overview of the product. Our team works on expanding the number of use cases, so in case you have an idea of a DAOsign usage for your Ecosystem, we would be happy to discuss it with you. 

In regards to the grant amount, it is negotiable.

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ccarfi** [comment]
@TetianaRiabova thanks for submitting this. we'll make sure to share it with the community. as the project progresses, will you be able to post updates here in this thread?

**Comment by TetianaRiabova** [comment]
@ccarfi sure, thank you!

**Comment by TetianaRiabova** [comment]
@ccarfi hello!

I would like to share some updates regarding DAOsign with you and your team, as previously discussed.

Currently, our product is on Testnet. DAOsign already allows users to store proofs of signature in the IPFS, Ethereum launch is planned in the nearest week. Also, recently, we received a grant from SUI, so DAOsign users will be able to use the SUI blockchain for proofs storing purposes soon as well. Also, our team is working on expanding the number of use cases (we would be happy to tell you more about that during the call).

It would be highly appreciated if you could spare some time for a quick call with our tech representatives so they could answer all your questions and for further discussion. And I’m sure that we could adapt to the requirements of your protocol and its users, improving your governance. Please let me know.

Regards.

**Comment by TetianaRiabova** [comment]
Hi @ccarfi,
I hope that you're doing well. I updated our grant application. Please take a look at our proposal for Unlock Protocol when you have time. We would appreciate hearing your thoughts on it! Let me know if you need more information, and feel free to ask any questions you may have. Thank you!

**Comment by ccarfi** [comment]
Hi @TetianaRiabova! Grants are driven by the Unlock DAO, by way of the process described here:
https://docs.unlock-protocol.com/governance/grants-bounties/udt-grantee-handbook/

Members of the DAOsign team are welcome to participate in the weekly Unlock Protocol Town Hall meetings (Weds at 10am PT) to share more about the grant proposal, and of course are very welcome to share thoughts and progress here in the proposal discussion thread as well as in the Unlock Discord.

What type of development work has the DAOsign team done using Unlock Protocol?

**Comment by ccarfi** [comment]
No response to prior outreach. Archiving this dormant grant.
