### ISSUE TITLE
Checkout Builder: Saved basic configurations do not appear in 'Configure the basics' 

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12413]
**Describe the bug**
When a user goes to Checkout Builder to re-configure the basics of their modal, each field is blank.

**To Reproduce**
1. Go to Checkout Builder
2. Choose a saved modal
3. Go to Configure the Basics
4. See blank fields

**Expected behavior**
When users go to Configure the Basics for a saved lock, their saved inputs should appear.

**Screenshots**
[Loom of bug](https://www.loom.com/share/108c15a05d8343808bae565d2a9ab60e)

**Comment by julien51** [comment]
This was fixed!
