### ISSUE TITLE
watch for account change to prevent 'invalid from address' error

### ISSUE THREAD

**Issue by MagRelo** [unlock-protocol/unlock#1242]
**Describe the bug**
Switching web3 accounts after the lock has loaded causes an error in web3

**To Reproduce**
1. Visit https://www.ouvre-boite.com/members/ with an account that doesn't have a key 
2. Switch accounts in MetaMask
3. Click Purchase
4. See error in console: `MetaMask - RPC Error: Error: WalletMiddleware - Invalid "from" address.`

**Expected behavior**
Watch for changes and update the selected account

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome 
 - Version: 71.0.3578.98 (Official Build) (64-bit)
 - MetaMask: v5.3.1

**Additional context**
FYI, I'm doing it like this atm but I'm not sure how well `publicConfigStore`    is supported...

```
    // watch changes to current account
    web3.currentProvider.publicConfigStore.on('update', data => {
      if (data.selectedAddress) {
        store.dispatch({
          type: 'ACCOUNT_CHANGE',
          payload: {
            currentAccount: data.selectedAddress
          }
        });
      } else {
        store.dispatch({
          type: 'ACCOUNT_LOGOUT'
        });
      }
    });
```

**Comment by cellog** [comment]
thanks for the report, this is very helpful!

**Comment by julien51** [comment]
Very cool indeed! Thanks @MagRelo
