### ISSUE TITLE
Price and balance overflow their containers on dashboard

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1249]
**Describe the bug**
Price and balance on the dashboard are wider than their columns.

**To Reproduce**
1. From a fresh clone of master
2. Go to the dashboard with some locks on it (screenshot from storybook)
3. See the too-wide data

**Expected behavior**
Price and balance will be formatted to not be so large

**Screenshots**

<img width="1007" alt="screen shot 2019-01-28 at 8 42 43 am" src="https://user-images.githubusercontent.com/9300702/51840021-e7dfe080-22d8-11e9-9acb-d29f52f40336.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 64.0.2

**Additional context**
IIRC some changes were made to unit conversions on the locks, this could be related to that

**Comment by cnasc** [comment]
Similar issue with prices on locks

<img width="320" alt="screen shot 2019-01-30 at 10 43 38 am" src="https://user-images.githubusercontent.com/9300702/51993002-05997b00-247c-11e9-900b-800648c10766.png">

**Comment by julien51** [comment]
Closing, because IO think the specific issues are fixed and https://github.com/unlock-protocol/unlock/issues/1403 will deal with the over-arching issue (how to handle large prices!)
