### ISSUE TITLE
Loty

### ISSUE THREAD

**Issue by nicoblancostorz** [unlock-protocol/unlock#12494]
### Description

We are a Mexico baed SaaS that helps businesses design, create and manage digital loyalty programs for their customers. We use NFTs as our technology (every distributed loyalty membership is an NFT), but the UX for users is completely web2. 

**This is our pitch deck:** 
[Loty_PD.pdf](https://github.com/unlock-protocol/unlock/files/12254545/Loty_PD.pdf)

**This is a demo of the product:**
https://www.youtube.com/watch?v=tQ2CkKhpkmA

We currently have 15 customers and our app has 100 monthly active users.

Some of our customers enroll their clients in the loyalty program as long as they pay a monthly fee; in case this fee is not paid, the customer is no longer part of the program. At loty we achieve this using Unlock. We distribute NFTs with a monthly validity and renew them as long as the customer does not cancel its subscription.

At this stage, we want to generate more traction. We have designed one two-month campaign and another one-month-campaign that will help us bring leads and activate the programs once they are implemented. 

**Campaign 1**: We will create 3 pools worth USD 1,500 each. 5 people can participate in each pool to win a fraction of those 1,500. The way they participate to win is by bringing us leads (we will of course onboard them to the product and type of customers we are looking for beforehand) and after two months, the 1,500 will be distributed proportionally to how many leads they brought. 
One pool will be in Mexico, another one in Central America and the last one in South America (specific countries TBD)

**Campaign 2**: All the sales made from the first campaign will go through an activation phase, where the business will start enrolling customers into the program. We want to give our customers some of the incentives to give out for their first customers that enroll. (For example, for a restaurant we could pay them for 50 desserts to give out to 50 customers that enroll into the program).
For the amount of sales we are expecting, we would need around USD 5,400 for this campaign

Both campaigns combined would cost us USD 9500. We would pay a part of this cost with the Grant received from you

### Website URL

https://www.loty.io/

### Twitter

https://twitter.com/nicoblanco12

### Github

https://github.com/Loty-io

### LinkedIn

https://www.linkedin.com/in/nicolas-blanco-storz-9b112918a/

### Discord handle

nicoblanco12

### Completion time

3 months

### Team

Our founding team consists of three people:

Nicolas (CEO): I am an engineer. I have worked at big companies like P&G in Berlin and Mastercard in Mexico City as a consultant, where I became passionate about loyalty. I also previously founded a Startup called mynfo, which allows people to share contact information using NFC technology. 

Carlos (COO): Former lawyer. Expert in Crypto, DeFi, NFTs. 
I established and managed a successful guild in the game Axie Infinity. I created a recruiting system that amassed over $500k in assets and attracted over 300 players from Latin America. I implemented incentives and training to keep members engaged and motivated.
Twitter: https://twitter.com/xenonnel

Ricardo (CTO): I am a software developer with 10+ years of experience in companies of all sizes. I have spent my last 6 years in Seattle working for Amazon and the last few years at Coinbase. This has opened up a perspective on the scale of services that is hard to obtain with other companies. From maintaining contact with Amazon vendors, building a new streaming service, to helping Coinbase execute its incentives and market orders. 
LinkedIn: https://www.linkedin.com/in/rmoguel/

The rest of the Loty team consists of three junior devs: Emmanuel, Alejandro and Sebastian; a UI/UX designer Damián; and our head of Marketing Celia.

### Milestones

Both campaigns mentioned in our Grant can be measured. 

**Campaign 1**: We will create 3 pools worth USD 1,500 each. 5 people can participate in each pool to win a fraction of those 1,500. The way they participate to win is by bringing us leads (we will of course onboard them to the product and type of customers we are looking for beforehand) and after two months, the 1,500 will be distributed proportionally to how many leads they brought. 
One pool will be in Mexico, another one in Central America and the last one in South America (specific countries TBD)

**Campaign 2**: All the sales made from the first campaign will go through an activation phase, where the business will start enrolling customers into the program. We want to give our customers some of the incentives to give out for their first customers that enroll. (For example, for a restaurant we could pay them for 50 desserts to give out to 50 customers that enroll into the program).

We will track every lead brought by the ambassadors participating in the pools. We can review them with the frequency you prefer. 
We expect to attract at least 60 leads from each pool.

Considering we can close 20% of those deals, we can assume we acquired 36 new customers. 
During the campaign 2, we can also track how many customers are being enrolled by the businesses and see if the campaign incentives are bringing in the expected results

We expect to bring at least 1,400 end users

### Requested grant amount

300 UDT

### Anything else you think we should know, including why you've requested a particular grant amount

We are applying for 300 UDT although we need more money to deliver our campaigns, since we know that asking for a grant that big can be more complicated and time consuming. 

We hope to gather the rest of the money from additional grants

### Is your work Open Source

No, my project does not use an Open Source license

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ccarfi** [comment]
Incorporates https://github.com/unlock-protocol/unlock/issues/11528 by reference

**Comment by ccarfi** [comment]
Hi @nicoblancostorz — wanted to check in on the status and progress of Loty. How are things going? I know that there was a "temperature check" done on Snapshot in April of last year: https://snapshot.org/#/unlock-protocol.eth/proposal/0x0bed1a799b86b375732ca1412c3ed8a18c13ce54bd5824aa1d4ffd1bae48077d

Is this project still under development?
