### ISSUE TITLE
Update Polygon logo through Unlock Labs apps

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12500]
**Is your feature request related to a problem? Please describe.**
The Polygon logo displayed throughout Unlock Labs apps has been depreciated. Polygon has requested we update their logo.

**Describe the solution you'd like**
Update Polygon's logo to one in their Brand Resources [Brand Resources](https://polygontechnology.notion.site/Polygon-Brand-Resources-External-2cd18ae436584e98a6c5aae56db73058)

Deprecated logo used by Unlock Labs below 
<img width="235" alt="Screenshot 2023-08-04 at 10 28 22 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/a2aaca11-419f-4e7a-9245-e4bf5b1ca26a">

**Comment by julien51** [comment]
We use an external library for these and it looks like the lirabry was updated so all good!
