### ISSUE TITLE
Events: Enable organizers to approve attendees before registering

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12529]
This request is from most event organizers who use Luma to announce their events, have guests apply, and approve/decline applications to attend.  

**Is your feature request related to a problem? Please describe.**
Event organizers often want their guests to apply before being approved to attend their events. attendees before they are eligible to register. Organizers use Luma to create an application form prospective guests complete to apply to attend their events. Organizers review guest applications and approve or deny their ability to attend an event. 

**Describe the solution you'd like**
1. Enable organizers to create an application guests must complete to be approved or declined to attend an event. 
2. With this application creation, organizers can add custom questions. (1:13 of this video is how organizers do this on Luma (https://drive.google.com/file/d/1koD8O8nSuexBKUGpQ12tRlHDmlPKU6Lc/view)).
3. For each question they create, organizers have a dropdown for Text, Long Text, Checkbox, Single Select, Multiple Select, URL, or Phone fields. Organizers can make each field required or optional for their guests to complete. Name and email are always required fields to notify guests of details about the event. 
4. If applications are required for guests to attend, an 'Apply to Join' CTA is added to the organizer's event details page, where users are prompted to complete and submit an application.
5. When an application is submitted by a guest, they receive a pending email that creates an invite to their calendar with the date/time of the event, which includes event details and a link to the event details page.
6. Enable organizers to see applications with responses from their guest applications and approve or decline their attendance. (:30 of this video is how organizers do this on Luma (https://drive.google.com/file/d/1VsH2Lb0qSheGYGsx8VsmToQ0dOTHAoRo/view))
7. If approved, guests are sent an approval email with their onchain ticket through a wallet-less airdrop OR to their EVM account (if available).
8. If declined, guests are sent a declined email that removes the event from their calendar.

**Describe alternatives you've considered**
Create a how-to guide that helps organizers create an application using DeForm, Typeform, or Google Forms, approve attendees, and airdrop tickets with approval emails to guests that have been approved. 

**Additional context**
[Luma Event Creation Flow & Event Registration Process Doc](https://www.notion.so/unlockprotocol/Luma-Event-Creation-Flow-Event-Registration-Process-1484d9ac33ae4527a9ac81505213366c?pvs=4)

[Luma approval and rejection dashboard video overview](https://drive.google.com/file/d/1VsH2Lb0qSheGYGsx8VsmToQ0dOTHAoRo/view)

[Luma user application creation dashboard video overview](https://drive.google.com/file/d/1koD8O8nSuexBKUGpQ12tRlHDmlPKU6Lc/view)

[Luma organizer Approval/Decline feature](https://www.loom.com/share/f55ba62d01374f73b33818dae3ed63c3)

**Comment by julien51** [comment]
Done and shipped! https://github.com/unlock-protocol/unlock/pull/13214
