### ISSUE TITLE
Events: Enable Email Templates for Creators

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12540]
This request is from Alex Pisarevski, founder of [Epic Web 3](https://www.epicweb3.com/), a global organizer of crypto-native events.

[Loom of Luma's Dashboard for Registration Emails ](https://drive.google.com/file/d/1koD8O8nSuexBKUGpQ12tRlHDmlPKU6Lc/view)

**Is your feature request related to a problem? Please describe.**
Luma offers organizers three registration email templates they can use and customize for three use cases (Registration Received, Registration Approved, Registration Rejected).

**Describe the solution you'd like**
Offer creators an email template in Settings > Email for tickets purchased/claimed with an email/Unlock Account and with crypto wallet events.

Proposed registration email copy (screenshot below):
Subject: **You're attending 'Contract Name'** 
H1: **You are registered to attend 'Contract Name'.
On 'Event Date + Time'**

**Congratulations!** You can use the attached ticket to attend 'Contract Name'. You can find more information and updates on our event page.

**'Purple 'Open Event Page' CTA linking to the lock's event page.'**

**Your ticket is an NFT!** You can view it on **OpenSea** (link to NFT on OpenSea) and transfer it to your own wallet **here** (link to transfer). 

**^If purchased/claimed with a crypto wallet, the copy is:**
Your ticket is an NFT! You can view it on **OpenSea** (link to NFT on OpenSea). 

**'Add Option to Share the event details page to Twitter and Linkedin.'**

**Describe alternatives you've considered**
Include the QR code in the body of the email instead of attaching a ticket

Luma's Registration Email
 <img width="298" alt="Screen Shot 2023-08-11 at 10 55 40 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/7432e955-5c20-4950-9842-1bb7630c4124">

**Comment by julien51** [comment]
> Luma offers organizers three registration email templates they can use and customize for three use cases (Registration Received, Registration Approved, Registration Rejected).

Since we don't have (yet) a mechanism for "approvals", we can't do that for now... 
That said we are adding a way to send any email and once we have approvals we can revisit.

**Comment by patrickworkman** [comment]
The solution proposed is a revision to the email copy used after someone claims or purchases a ticket to an Event, which does not require an approval workflow. The copy proposed is a single email template in Events, replacing the email copy attendees receive today post-purchase/claim through Events

I shared Luma’s email registration flow for attendee approvals as context.
