### ISSUE TITLE
Swap and Purchase does not work on BNB chain

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12554]
It looks like swap and purchase does not work on the BNB Chain.
This has been raised by one of our users with this checkout URL: https://nft.cryptoisfire.ai/
I chose the "Flame" membership and, even though I have enough BNB to swap to USDC, the transaction reverts.

I have [performed a simulation using Tenderly](https://dashboard.tenderly.co/julien51/unlock-protocol/simulator/new?stateOverrides=%5B%5D&rawFunctionInput=0x5e8f45020000000000000000000000005fb4c4b333fd8b713a42a6655e2ae83ec5f18897000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff1722376f9c3e0000000000000000000000004648a43b2c14da09fdf82b161150d3f634f4049100000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000003e000000000000000000000000000000000000000000000000000000000000002e424856bc30000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000030b010c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000001000000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c844000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b8ac76a51cc950d9822d68b83fe1ad97b32cd580d000bb8bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c84400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002643381899700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c0103534000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000041fe4abbdd5cc77b3fdfead4070e6087844269325f61eb41b3372aca76de72eed80631058c1c2303261bbfad63df4bce904a42733196e29f5a55d00b3104be6e8f1c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&simulationId=4e81c00f-645b-426e-8983-c721a40cc07f&value=0&contractAddress=0x5ad19758103d474bdf5e8764d97cb02b83c3c844&contractFunction=0x5e8f4502&functionInputs=0x5fb4c4b333fd8b713a42a6655e2ae83ec5f18897&functionInputs=0x0000000000000000000000000000000000000000&functionInputs=71801554787605566&functionInputs=0x4648a43b2c14da09fdf82b161150d3f634f40491&functionInputs=0x24856bc30000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000030b010c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000001000000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c844000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000122730d9336046c00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b8ac76a51cc950d9822d68b83fe1ad97b32cd580d000bb8bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000005ad19758103d474bdf5e8764d97cb02b83c3c8440000000000000000000000000000000000000000000000000000000000000000&functionInputs=0x3381899700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000ebec21ee1da400000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c01035340000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f5c28ce24acf47849988f147d5c75787c0103534000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000041fe4abbdd5cc77b3fdfead4070e6087844269325f61eb41b3372aca76de72eed80631058c1c2303261bbfad63df4bce904a42733196e29f5a55d00b3104be6e8f1c00000000000000000000000000000000000000000000000000000000000000&network=56&headerBlockNumber=30866463&headerTimestamp=1692078863) to confirm and indeed, we get a revert with `Error Message: InsufficientETH[]`.

When looking deeper in the transaction trace, it looks like the issue is coming from a malformed `swapCalldata` object.

**Comment by julien51** [comment]
Maybe we can automate the check that these things work as part of https://github.com/unlock-protocol/unlock/issues/12819

**Comment by clemsos** [comment]
I tested things by recreating a new USDC lock on BNB (the one in the comment above is now on Polygon). There is no issue with the UI now and Uniswap SDK works properly (see screenshot). 

However, the payment itself reverts with a `UnautorizedRouter["0x5302086a3a25d473aabbd0356eff8dd811a4d89b"]`. Likely Uniswap Universal Router has been redeployed and we didn't whitelist the new contract on our BNB `SwapPurchaser` contract.

A new working version has been redeployed in #13311 


![Screenshot 2024-02-05 at 13 59 03](https://github.com/unlock-protocol/unlock/assets/743246/96ec88b2-8ed9-4f92-a563-e16592a43ed5)

**Comment by julien51** [comment]
@clemsos Please test on staging to confirm and close!

**Comment by clemsos** [comment]
so after testing on staging, it seems that the uniswap js sdk on the frontend returns the address of a contract called `UnsupportedProtocol` instead of the universal router address

see the tenderly simulation https://www.tdly.co/shared/simulation/2b29beaa-3535-4a12-959e-2aeeb4120363

**Comment by clemsos** [comment]
Looking into it it seems a mistake from 

https://github.com/unlock-protocol/unlock/blob/99a430fde57a24e8580a9a6cb7663150297c0f82/packages/networks/src/networks/bsc.ts#L135C30-L135C72 

we have the wrong address... 

https://github.com/Uniswap/universal-router/blob/41183d6eb154f0ab0e74a0e911a5ef9ea51fc4bd/deploy-addresses/bsc.json#L2

We may have to redeploy the SwapPurchaser once again to fix

**Comment by clemsos** [comment]
reppening once again as it is not tested yet (waiting for staging to fully deploy). Here is a test checkout link with a Binance USDC lock https://staging-app.unlock-protocol.com/demo?network=56&lock=0x4b723ce2146f37bee2a179c801b430bb1050694f

**Comment by clemsos** [comment]
ok it worked ! https://bscscan.com/tx/0x4415f619740e414083b2fe364df19bc8077c12759b0b3446b929b909005eb86e
