### ISSUE TITLE
Checkout Builder: Remove configured locks from existing Checkout modal not working

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12551]
**Describe the bug**
When attempting to remove a featured configured lock from an existing checkout modal, the trash can icon to delete a lock does not delete a lock

**To Reproduce**

1. Go to Checkout Builder
2. Edit an existing configuration with more than two locks
3. Go to Configured Locks
4. Click on the trash can icon to delete a lock, which doesn't work

**Expected behavior**
Click the trash can icon next to a Configured Locks in a configured checkout modal to delete a configured lock

**Screenshots**
[Loom of the bug](https://www.loom.com/share/2764e6c76f6a4670bc920172200d3dd3)
**Desktop (please complete the following information):**

**Comment by julien51** [comment]
This has been fixed!
