### ISSUE TITLE
Show and set custom referrer fees

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12557]
The locks support setting referrer fees for specific referrer addresses.  The address is `0x0` is used to set the referrer amount for _any_ amount.

The Unlock Dashboard only supports settings referrer fees for the `0x0` address because we have no easy way to "list" all referrer fees set for custom addresses. However, we now need to let users set a custom referrer fee and show any custom referrer fees set per address.

To do that, the first step is to add the referrer fees to subgraphs. We need to add them to the lock objects.
Once they are added to the subgraph, we can list them on the dashboard and let user set custom ones.

**Comment by blahkheart** [comment]
So to be clear, is the task to "add referrer fees to subgraphs" alone?

**Comment by julien51** [comment]
> So to be clear, is the task to "add referrer fees to subgraphs" alone?

Nope, it's not the subgraohg part and the UI part...  they are both being worked on by @easyrun42
