### ISSUE TITLE
Base proxy contract not verified...

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12578]
Still the same issue :(

**Comment by clemsos** [comment]
ok done ~ https://basescan.org/address/0x66F3D9863e89bFBC3B74225d59fF449ae7BCB3F6#code

It is a bit tedious as we need to verify the proxy contract from the correct version of OpenZeppelin that has been compiled into Unlock. For reference, it is how I have done it

- look at [Unlock implementation](https://basescan.org/address/0x2499d94880b30fa505543550ac8a1e24cffefe78#code) and scan for the OZ version of `Proxy.sol` (we see `// File @openzeppelin/contracts/proxy/Proxy.sol@v4.8.2`)
- change the version in smart contracts package
- adapt the code so it compiles (i had to comment a line from the Unlock contract)
- verify the proxy using the hardhat command `hardhat verify-proxy`. You can pass the arguments found in an existing lock creation tx (like [this one](https://basescan.org/tx/0x28a0b1d17322538d15adb8ff6e075ce7c33cfac258b85e880461723698de5ae0#eventlog)). Below what I used.

```
yarn hardhat verify-proxy 
--calldata 0x6eadde43000000000000000000000000b2650168ac849eb1e37907a09b388450e3f2b34dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000096f30396f30396f30390000000000000000000000000000000000000000000000 
--lock-version 13 
--proxy-admin-address 0xa7325f041e4b05b78959001ce88306edb649833c 
--unlock-address 0xd0b14797b9D08493392865647384974470202A78 
--transparent-proxy-address 0x66F3D9863e89bFBC3B74225d59fF449ae7BCB3F6 
--network base
```


Also there is an annoying error from OZ upgrades plugin that doesnt allow to verify any other proxy thatn the one bundled in the upgrades package.

```
Failed to verify TransparentUpgradeableProxy contract at 0x66F3D9863e89bFBC3B74225d59fF449ae7BCB3F6: Bytecode does not match with the current version of TransparentUpgradeableProxy in the Hardhat Upgrades plugin.
```

You need to comment the line `require('@openzeppelin/hardhat-upgrades')` in `hardhat.config.js` to make it work
