### ISSUE TITLE
Multi sig withdrawl

### ISSUE THREAD

**Issue by Sal1y-H** [unlock-protocol/unlock#12587]
**Is your feature request related to a problem? Please describe.**
It would be great to have an option where more than one manager was required to approve a balance withdrawal eg. If using Unlock to raise funds for a DAO members want to know the balance is being withdrawn to the DAO account.

**Describe the solution you'd like**
Approval from a set number of managers as required by the lock owner.  Once set it needs that number to also change the number of managers required so the lock owner can not revert to just themselves.

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
this logic probably belongs in a multisig wallet and not at the core protocol level.
