### ISSUE TITLE
Checkout: Credit card payments not working

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12588]
**Describe the bug**
When I attempt to purchase a key from [a lock](https://polygonscan.com/address/0xc81d7f79d517bb8c09f58da06bab51cd606565a7) where credit card payments have been enabled, transactions are not processed. 

[Loom of error](https://www.loom.com/share/d2c33c151ab84d00be30031b91b1958b)

**To Reproduce**

1. Go to [Checkout](https://app.unlock-protocol.com/checkout?id=7be22f75-105d-40ee-a487-40cef00aa91e)
2. Attempt to purchase with a credit card
3. See error

**Expected behavior**
Credit card transaction should be processed for users paying with a credit card

**Comment by julien51** [comment]
Hey @patrickworkman sorry I missed this one earlier. It's an important one. I see no charge in our database. can you confirm you have not been charged on your card either?
