### ISSUE TITLE
Purchase email

### ISSUE THREAD

**Issue by Sal1y-H** [unlock-protocol/unlock#12586]
**Is your feature request related to a problem? Please describe.**
1. At the moment the email reads as if it is from Unlock not the org selling the membership.
2. The checkout allows us to change out the Unlock logo etc so there is no link to Unlock but then they get an email with Unlock branding and a reference to 'contact info@unlock' which will seem out of place. 
3. I'd also like for it not to say 'you've minted X NFT' as often we are trying to onboard newbies so are using non-NFT language.

**Describe the solution you'd like**
1. Email subject to be set by user
2. Either no logo at top, or it auto takes from the logo from the check out modal
4. Remove 'a new membership lock was just minted for you' - force lock managers to update the email if they choose the send email option to be on
5. Remove all the 'unlock' references at the bottom. I want members emailing me not you if there is an issue. 
But there could be a standard footer which is 'This token was minted using the Unlock protocol' and a link.

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
Unfortunately, because of the way spam filters behave, we cannot do all the customizations you're asking for.
Alternatively, as a user, you can fully disable emails we send and send the ones you want to send.
