### ISSUE TITLE
Checkout: Image icon reverts to Unlock default logo when adding Redirect button text

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12592]
**Describe the bug**
When a user adds text to the Redirect button text field, the image icon added reverts to the Unlock logo.

**To Reproduce**
1. Go to Checkout Builder
2. Create a new or edit an existing configuration
3. Configure the basics
4. Change the image icon (upload or URL)
5. Add text to the Redirect button text field
6. See the image icon revert to the Unlock default logo

**Expected behavior**
Adding text to the Redirect button text field shouldn't revert the image icon to the Unlock default logo.

**Screenshots**
[Loom of the bug](https://www.loom.com/share/3fb74a3f22074d1e8787f7f757896b0c)

**Comment by julien51** [comment]
This is a pretty fun bug :D We'll fix it aSAP.

**Comment by julien51** [comment]
This has been fixed!
