### ISSUE TITLE
Events: Refunding "Stake"

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12593]
_This is a feature request from the ETH Barcelona 2024 planning team._

**Is your feature request related to a problem? Please describe.**
To improve the attendance rate of free events, organizers want registrants to “stake” funds that can be refunded after check-in. This mechanism increases the likeliness of registrant attendance because they have funds at stake.

**Describe the solution you'd like**
Refunds would be processed at check-in when a verifier validates an attendee’s ticket. The process requires an “on-chain” check-in system where, when a verifier validates an attendee’s ticket through the Unlock Labs Verification app, they can send a transaction issuing a refund to the attendee (leveraging the `expireAndRefund` function of the contract). 

**Pros:**
- No new contract
- Attendees are immediately refunded

**Cons:**
- Requires organizers to use the Unlock Labs Verification app
- Requires custom UI development on the Unlock Labs Verification app
- Adds latency to the check-in process
- Less “Secure” (verifiers need to have `Lock Manager` -admin- role)
- No incentive for attendees to continue staking or holding tokens deposited (all attendees are refunded)
- Brittle: Sensitive to verifier having gas for transaction fees, a good Internet connection, the lock having enough funds… etc, and no clear recovery mechanism
- Refunded stake is *at most* ticket paid (we can’t refund more because we don’t know how many people will eventually show up)

**Describe alternatives you've considered**
Event organizers would process refunds asynchronously (*after* the event). Organizers can identify all tickets marked as checked-in using the Unlock Labs Verification app through Membership Dashboard and deploy a “refund” contract allowing attendees to claim their refund. This is effectively an airdrop contract/mechanism where the lock manager transfers the lock proceeds to an airdrop contract.

**Pros:**
- Pull vs. Push (user-triggered, if they want)
- No change to the Unlock Labs Verification app
- Most flexible

**Cons:**
- Attendees might be frustrated with refund lag
- Requires a new contract + attendee claim front-end UI

**Comment by julien51** [comment]
> To improve the attendance rate of free events, organizers want registrants to “stake” funds that can be refunded after check-in. This mechanism increases the likeliness of registrant attendance because they have funds at stake.

This is actually what KickBack used to do. It's a pretty cool mechanism.

I do think that indeed a better approach is in fact a combination of the 2 you highlighted... as as "3rd party" app. This app would let a lock manager connect their wallet, list the contracts they have deployed and then list all the attendees that have been checked in. Then it would have a single button to process refunds in one go, or in multiple transactions, probably using something like https://disperse.app/

I would love to see someone from the community build this!

**Comment by julien51** [comment]
This was implemented! https://unlock-protocol.com/guides/unlock-commitment-staking-kickback-refund/
