### ISSUE TITLE
Events: Add event details page to 'Your Ticket for....' Email

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12661]
**Is your feature request related to a problem? Please describe.**
After a user claims or purchases a ticket, they receive an email with an attached ticket that contains copy of the event's details added by the organizer. Organizers update their event details pages with agendas, speakers, and sponsors before an event, and none of this information is easily accessible via email from attendees. 

**Describe the solution you'd like**
Include a link to the event details page in the 'Your Ticket for....' email received post claim/purchase. 

Luma email to attendees with a CTA directing to the event detail page
![Screen Shot 2023-09-08 at 11 24 00 AM](https://github.com/unlock-protocol/unlock/assets/32484647/d69d75a9-0505-4d4f-affd-fd443b543764)

**Comment by julien51** [comment]
Fixed!
