### ISSUE TITLE
Extending key wrong result

### ISSUE THREAD

**Issue by boskiv** [unlock-protocol/unlock#12663]
**Describe the bug**
Extending key to 01.01.2024 works as not expected. After transaction confirmed date is set to 29.10.2024

**To Reproduce**

1. Go to lock
2. Click on key
3. Extend it to 01.01.2024 00:00
4. See date after transation

**Expected behavior**
Date should be as set in transation

**Screenshots**
![Screenshot 2023-09-11 at 8 16 41 AM](https://github.com/unlock-protocol/unlock/assets/1939783/bb075dfe-907a-46b3-b4c9-2f955b02ceab)
![Screenshot 2023-09-11 at 8 17 00 AM](https://github.com/unlock-protocol/unlock/assets/1939783/5c3a896b-f2f4-4111-af39-17e62b191716)

**Additional context**
(https://polygonscan.com/tx/0x16579112c6168fe8dfe3eaa898bfd41586ed7dba118dade5402efbc4f19a1b96)

**Comment by julien51** [comment]
Thanks! Fix will be deployed to production shortly.
