### ISSUE TITLE
Events: Lock Name should replace 'Ticket Contract' when customized Checkout is used on EDPs

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12683]
**Is your feature request related to a problem? Please describe.**
When organizers add a custom Checkout to their event details page, users are not provided with the names of tickets available, only 'Ticket contract contractaddress'. This creates confusion because the user doesn't know the purchase options before registering. The ticket name is more relevant to users than the contract the ticket is created from.

**Describe the solution you'd like**
Add the LockName for each lock above the price and available ticket supply.

**Describe alternatives you've considered**
Replace 'Ticket contract' with the name of each Lock.

**Additional context**
[Ethereum Mexico 2023 EDP with a custom Checkout](https://app.unlock-protocol.com/event/ethereummexico2023)

<img width="324" alt="Screen Shot 2023-09-19 at 7 04 24 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/93ffc20f-eaac-45f6-b1f6-2adb11a445d0">

**Comment by julien51** [comment]
This has been fixed!
