### ISSUE TITLE
Verification: Change ‘Checked-in’ color to red

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12682]
**Is your feature request related to a problem? Please describe.**
When a QR code has been scanned and checked-in through Verification, the color is yellow. Yellow is a neutral color. 

**Describe the solution you'd like**
Change the checked-in color to red. Red = stop and is clear to anyone the QR code is invalid.
![IMG_7468](https://github.com/unlock-protocol/unlock/assets/32484647/28172646-c5b1-45fa-8837-00342b7688f3)

**Comment by julien51** [comment]
We actually have a state of "error" which is AR code is invalid/forged so we need to keep "yellow" for this "warning: this is a valid ticket but it has already been redeemed.
