### ISSUE TITLE
Do not limit compiler version to 8.17?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12697]
A team at EthGlobal NYC was trying to use Unlock's packages with another project (Uniswap) but apparently we have some hardcoded compiler on 8.17 which prevented them to use it easily.

**Comment by clemsos** [comment]
We should bump the compiler version to latest but each version introduces changes so it is better to keep it managed (at least in the contracts) as it may break things. Currently the idea is to keep things consistent across all contracts in monorepo so everything (including interfaces) uses the same version.
