### ISSUE TITLE
Move all network tasks to the hardhat-plugin

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12707]
We still currently deploy or verify contracts from our `smart-contracts` folder. This is not ideal because there are files that are work in progress in that folder and that creates a bunch of confusion.

We should only deploy from the "released" versions of the contracts package, so i suggest we move all the tasks to the hardhat plugin (or the hardhat helper if we need some code to be available in smart contracts)

**Comment by clemsos** [comment]
I was thinking we could actually create another "contracts admin" folder with all tasks related to verify, governance, etc. So we keep the contracts folder only for dev and don't add things to the hardhat plugin that are only used by us

Wdyt?
