### ISSUE TITLE
Deploy Transparent Proxy independently

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12708]
Our Unlock contract includes the code for the Transparent Proxy that is used when deploying new Locks.
This isn't ideal because every time we deploy a new Unlock we have to reverifiy this contract (its code changes a bit with new OpenZeppelin versions).
Let's set its address as a variable that can be changed thru governance for easier management.

**Comment by clemsos** [comment]
Here is a method to verify a Lock proxy on v13 https://github.com/unlock-protocol/unlock/issues/12578#issuecomment-1688086026
