### ISSUE TITLE
beyondClub - Localize Event Ticket feature for the Japanese market

### ISSUE THREAD

**Issue by yukiwaki** [unlock-protocol/unlock#12717]
### Description

We are requesting 300UDT to support the localization of Unlock membership and ticketing flow for the Japanese market.  

BeyondClub is already leveraging Unlock Protocol to support Japanese clients and partners with our no-code web3 loyalty platform. We were also selected for the  Unlock retroactive funding in April 2023. (as Yuki / yuki_xyz)
However, we’d like to further localize these efforts for a more seamless membership NFT and ticketing system for Japanese users.

As the Japanese government recently launched a new grant program for big events to use NFT tickets, we believe this can be a great opportunity to expand the Unlock ecosystem to the Japanese market.
(We had the press release with Unlock, to support events that want to apply for this government grant.)
https://prtimes.jp/main/html/rd/p/000000018.000080182.html

This grant will enable us to:
- Translate the Unlock membership system into Japanese inside beyondClub product, ensuring that the user experience is seamless and user-friendly.
- Localize the NFT ticketing system for event organizers and participants launching as ticket.beyondclub.xyz
- Making the localized event ticketing system as open source 

The expected outcomes of this project include focusing on community-building and fan empowerment through gamification. Unlike traditional membership programs, we aim to foster genuine relationships between brands and their audiences, creating a sense of belonging and identity within the community. 

### Website URL

https://beyondclub.xyz

### Twitter

@beyondClub_xyz

### Github

https://github.com/BeyondClub

### LinkedIn

https://www.linkedin.com/company/beyondclub/

### Discord handle

.yuki_xyz

### Completion time

1 month

### Team

beyondClub is a dynamic crew of experienced blockchain enthusiasts from India, Japan, Canada, and the Philippines. The team is dedicated to building a loyalty program launcher for brands, creators, and communities to create their own NFT loyalty program in minutes and even without blockchain knowledge, bridging the gap between web2 and web3 brands.

Meet the team:
Yuki Wakiyama
CEO / PM & UI
Founder at PONT and exit to the creator agency
Tokyo University graduate

Jijin P
CTO / Fullstack
Built web3 products: HashMetrics and Send a Coin
Built ClixWall - help publishers monetizing websites

Pawan Bajaj
Co-founder / Solidity
Built DeSci Exchange and PeerPool
Music producer

Rizza Gomez
Social Media Manager
Copywriting and executing social media campaigns related to web3, from digital fashion to PFPs

Ed On
Partnership Manager
Working on Wonder, web3 community management tool
Strong relationship around web3 communities

Our team has deep ties within the Japanese web3 ecosystem where 2 of our team members are also Bankless Japan core team members.  BeyondClub has supported Japanese projects and brands like DAO/ETH Tokyo with token-gated exclusives and access, Cryptobar P2P with NFT loyalty program and is partnered with major Japanese marketing and consulting agencies to support their client portfolios.

### Milestones

1. beyondClub successfully launched a token-gated city guide at ETH Tokyo through Unlock’s contract garnering 2,600+ mints.

2. We receive the Unlock retroactive funding on April 2023. (as Yuki / yuki_xyz)
https://snapshot.org/#/unlock-protocol.eth/proposal/0xf0e392d073c803c78128b55a09a43d0c0952e2dc764f6a5f5541e321d4f6b1d1

3. Market recognition from ETH Global, Japan’s f6s, Polygon, and notable entities in Japan like Astar Japan Lab, TofuNFT, Hakuhodo Key3.

### Requested grant amount

300 UDT

### Anything else you think we should know, including why you've requested a particular grant amount

In pursuit of our mission to localize Unlock for the Japanese market, we are seeking a grant in the amount of 300 UDT. This funding will play a crucial role in supporting localization and furthering Unlock’s impact within the Japanese web3 space. 

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yukiwaki** [comment]
Hi! 
We could finally complete the translation to Japanese! 

Where you can create the new event.
https://ticket.beyondclub.xyz/ja/event/new
![Screenshot 2024-01-15 at 16 53 22](https://github.com/unlock-protocol/unlock/assets/90386676/4a475bcb-eb3a-432e-8701-1d23c937e796
![Screenshot 2024-01-15 at 16 54 32](https://github.com/unlock-protocol/unlock/assets/90386676/ec65ca4b-429a-41c8-94db-841eef87255b)
)


This is the sample event page.
https://ticket.beyondclub.xyz/ja/event?lockAddress=0x1d07b78ee5a7dd82894ac8e94c284adf0c6e036e&network=11155111
![Screenshot 2024-01-15 at 17 09 02](https://github.com/unlock-protocol/unlock/assets/90386676/93c486d0-92c2-475e-b113-a1e6aadc5e4d)
![Screenshot 2024-01-15 at 17 10 20](https://github.com/unlock-protocol/unlock/assets/90386676/a5658677-7ee9-4b7d-96d9-c0a1648ce108)


We will try to onboard more events to use this ticket feature in Japan.
Please let us know if you have any question!

**Comment by ccarfi** [comment]
Moved to onchain vote. Voting opens 10Feb2024 https://www.tally.xyz/gov/unlock/proposal/68468691491387971881685975600181096977807705656351967668945364567994021050640?chart=0

**Comment by ccarfi** [comment]
Passed and funded.

**Comment by ccarfi** [comment]
Congrats to the team.
