### ISSUE TITLE
`SH` for Windows dev support

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1277]
**Describe the bug**

Running `npm i` on Windows fails attempting to execute `./scripts/postinstall.sh`.

It seems on Windows, we must prefix the command with `SH`.  However when I tried this, it caused the Travis build to fail.  Maybe we need to use run-script-os to add SH while on Windows only.

**To Reproduce**
1. On Windows, run `npm i` in the root directory

**Expected behavior**
Installation should complete, but currently fails on the postinstall script.

**Additional context**
There does appear to be a couple other commands using SH scripts we should update as well.

**Comment by hardlydifficult** [comment]
Hey @julien51 ,
This is the issue RE windows support I mentioned in the meeting.  Windows seems to require prefixing sh commands with `sh`... but for some reason adding that causes the script to fail on Linux.  

As an alternative I tried using `run-script-os` to add `sh` only when on Windows... but using `run-script-os` causes issues inside `postinstall.sh`.

**Comment by cnasc** [comment]
@hardlydifficult do you run npm from PowerShell or Git Bash? (assuming PowerShell based on the `sh` prefix)

**Comment by hardlydifficult** [comment]
Yes PowerShell.  Never tried Git Bash before, just gave it a go - same error:

```
/E/UnlockProtocol/unlock (master)
$ npm i

> unlock@1.0.0 postinstall E:\UnlockProtocol\unlock
> ./scripts/postinstall.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by cnasc** [comment]
Curious. I believe that the `sh` command runs things through Git Bash, so I guess that isn't too surprising but just wanted to be sure.

**Comment by cnasc** [comment]
What happens if you try to run `postinstall.sh` on its own? I wonder if the issue is the way the paths are specified.

**Comment by hardlydifficult** [comment]
When I change package.json to `"postinstall": "sh ./scripts/postinstall.sh",` then `npm i` appears to work.

Oh I forgot I have example builds:
Adding `sh` breaks Travis: https://travis-ci.com/hardlydifficult/unlock/builds/98520725
Adding `run-script-os` breaks the script: https://travis-ci.com/hardlydifficult/unlock/builds/98523870 (I believe with some help this approach could work)

**Comment by cnasc** [comment]
> Adding `run-script-os` breaks the script: https://travis-ci.com/hardlydifficult/unlock/builds/98523870 (I believe with some help this approach could work)

Looking at the error it gives, I suspect that somehow `run-script-os` is polluting the npm commands. It fails trying to run `ci:linux`, even though CI wasn't touched by `run-script-os` directly. I wonder we have to specify OS-variants of each command that might be called by a command even indirectly.

**Comment by cnasc** [comment]
Is this still an issue?

**Comment by NickCuso** [comment]
Yes - but it's fine.  I suggest we just close this down.  I have a linux box to use when needed.
