### ISSUE TITLE
Pagination UI showing impossible values

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#12780]
Pagination showing out-of-range options for navigation.

<img width="1051" alt="Screen Shot 2023-10-04 at 5 44 11 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/f4d37470-d0f6-4827-80e8-6bbb9f0a2a38">

This particular lock has 52 keys at the current time:
https://app.unlock-protocol.com/locks/lock?address=0xcffde30c41361a67bacb7b9e3fa4f26c0130f394&network=137

Pagination shows "impossible" values of -1, 0, and 3.

Clicking any of those goes a non-lock page.

**Comment by julien51** [comment]
This has been fixed!
