### ISSUE TITLE
Swap and Purchase issue

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12797]
It appears that our swap and purchase feature us not working anymore.
This is a front-end issue as we are just not able to list "routes".

Here is an example of a checkout URL : https://staging-app.unlock-protocol.com/checkout?id=67ab19b8-5e50-45ab-8f46-e16c1f72204d

We get an error in the console: 

```
Error: Unexpected pool type in route when constructing trade object
```

<img width="606" alt="Screenshot 2023-10-10 at 5 07 42 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/8d3aad0e-31d4-4f00-b0c7-68f2ffccb48f">

**Comment by clemsos** [comment]
looking at it we are also getting web API errors. Could that be related?

<img width="548" alt="Screenshot 2023-10-11 at 21 13 34" src="https://github.com/unlock-protocol/unlock/assets/743246/a83a5e2a-2a32-45ba-b340-81e2a97764e8">
