### ISSUE TITLE
Events: Enable organizers to edit email subject line, body, when notifications are sent to attendees, and what notifications are sent

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12805]
**Is your feature request related to a problem? Please describe.**
Emails received from the organizer represent their event after a guest applies, RSVPs, or purchases a ticket. Organizers want emails received by guests to be awareness of the event's details in order to encourage them to attend

**Describe the solution you'd like**
**_All emails sent to guests are from hello@unlock-protocol.com to avoid spam challenges._**

1. Offer organizers the ability to customize registration email templates. These emails would reflect the guest's status and could include a purchased ticket, RSVP confirmation, or guest application received/approved/declined (if the feature is enabled through Events or another form creation product). 
2. Organizers can customize the subject line, the body of emails, the sender's name, a reply-to email for support from the organizer, and view a preview of the event. Markdown is enabled if organizers choose to use it in the body of emails. 
3. By default, the body of emails guests receive will include the event name, location that links to Google Maps, start/end time, a link to the event details page, a calendar invite, a link to their ticket on Unlock Labs Keychain, and the option to add the ticket to their Apple or Google wallet.

**Describe alternatives you've considered**
Disable customizing the body of emails, enabling organizers to only edit the subject line, add the sender's email, and a reply-to email for support.

**Additional context**
[Luma Event Creation Flow & Event Registration Process Doc ](https://www.notion.so/unlockprotocol/Luma-Event-Creation-Flow-Event-Registration-Process-1484d9ac33ae4527a9ac81505213366c?pvs=4)

**Comment by julien51** [comment]
Current we send only 1 email when the user receives a ticket.
This email is different based on whether the ticket was "airdropped" or "purchased". 

* Airdropped ticket email:
<img width="662" alt="Screenshot 2023-11-02 at 12 05 12 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/176189c1-2ae7-4f32-b0aa-6d930cdd536c">

* Purchased ticket email:
<img width="652" alt="Screenshot 2023-11-02 at 12 04 56 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/95280426-0b35-46ce-a0a8-0749c9d02781">

Here are the changes I am working on:

- First I am adding the ability to customize emails straight from the event details page if the organizer (lock manager) is connected.
- Second, we are updating the templates a bit to add a link to the event page
- Finally, we are adding 1 more template: "Event starts tomorrow" that sends a summary of the event as it is about to happen.

**Comment by julien51** [comment]
Fixed in https://github.com/unlock-protocol/unlock/pull/12939
