### ISSUE TITLE
Lock manager should be able to transfers keys even when transfers are disabled

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12800]
A lock manager should always be able to transfer keys (no fees) even if transfers are disabled.

Example of transaction:
https://dashboard.tenderly.co/julien51/unlock-protocol/simulator/fd747dab-59d2-4401-b73c-57c702d0f5d3

**Comment by julien51** [comment]
This is also blocking https://github.com/unlock-protocol/unlock/issues/12799

**Comment by clemsos** [comment]
It seems that was fixed already in https://github.com/unlock-protocol/unlock/pull/11355 but not deployed yet
