### ISSUE TITLE
When changing user account, the web3Service needs to reset its listeners

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1281]
**Describe the bug**

When changing user account, we reset state, but the web3Service keeps listening for new events. Because it can take a long time for newer transactions to come in, it's possible for stale state to appear.

**To Reproduce**
1. Go to the dashboard with metamask
2. Choose an account that has no locks/keys
3. Choose another account that has lots of locks/keys
4. Choose the first account again

**Comment by julien51** [comment]
Blocked after https://github.com/unlock-protocol/unlock/issues/625

**Comment by julien51** [comment]
Closing because I do not think this is applicable anymore.
