### ISSUE TITLE
Events: Change 'View your ticket online here' to 'View the event details page here'

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12868]
**Is your feature request related to a problem? Please describe.**
After users register or pay to attend an event through Events by Unlock Labs' event details page or are airdropped a ticket, they receive an email with event details. Users who want to see the event details page they registered with need help through the email they've received. 

**Describe the solution you'd like**
Change 'View your ticket online here' to 'View the event details page here,' directing users to the event details page they used to register for the event.

**Describe alternatives you've considered**

- Add 'View the event details page here' above 'View your ticket online here.'
- Change 'View your ticket online here' to 'View your ticket on Opensea here'
- Change ' PS: you can view and print a transaction receipt if needed' to 'View your transaction receipt here'
- Remove  PS: you can view and print a transaction receipt if needed.'

**Additional context**
<img width="452" alt="Screen Shot 2023-10-31 at 12 29 57 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/9d4e8a9d-aefe-4002-84b7-20629732b0ad">

**Comment by julien51** [comment]
Fixed in https://github.com/unlock-protocol/unlock/issues/12868
