### ISSUE TITLE
Events: Add page break to Event Details section of the email users receive

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12869]
**Describe the bug**
When organizers create an event using Events by Unlock Labs and add a Description, they can add page breaks. When users receive emails after registering, purchasing, or being airdropped a ticket to an event, the page breaks are lost, making the Event Details a solid block of text.

**To Reproduce**

1. Create an event using Events by Unlock Labs
2. Add a Description with page breaks under Basic Information
3. Claim a ticket for the event
4. Receive an email with Events Details as a solid text block.

**Expected behavior**
Event Details in the email received by users after registering, buying, or being airdropped a ticket should include the page breaks added by the organizer while creating an event using Events by Unlock Labs.

**Screenshots**
<img width="452" alt="Screen Shot 2023-10-31 at 12 29 57 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/315d1038-1771-479a-8365-e4659a9344a7">
<img width="525" alt="Screen Shot 2023-10-31 at 12 43 25 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/91753dcd-d602-4c53-a757-cd75053e8dfb">
<img width="630" alt="Screen Shot 2023-10-31 at 12 42 43 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/44b7bb47-389d-4a56-8fc8-a80eadf5ddeb">

**Comment by julien51** [comment]
Great cacth! This is fixed as part of https://github.com/unlock-protocol/unlock/pull/12939
