### ISSUE TITLE
Send transaction in new tab

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1287]
We have several issues with some web3 wallets/dapp browsers which all come down to the fact that we are trying to access the web3 provider from *inside* an iframe. 

The work around which was suggested was to use a new tab to actually perform the web3 transaction.
Basically, from inside the iframe, if we detect that no web3 provider is available, clicking on the lock should actually open a new tab/frame in which the user is asked to perform the key purchase.

Once the transaction has been initiated we can send the user back to the original creator page and show the transaction status (or the full content if the consumer already has a key) since we can use our "read only" web3 provider for this.

This will provide workarounds for https://github.com/unlock-protocol/unlock/issues/1154 https://github.com/unlock-protocol/unlock/issues/1241 and https://github.com/unlock-protocol/unlock/issues/1158

Comments @akeem @cellog @cnasc @benwerd ?

**Comment by julien51** [comment]
This does require https://github.com/unlock-protocol/unlock/pull/1283 to be merged and https://github.com/unlock-protocol/unlock/issues/1225 to be fixed (working on both!)

**Comment by cellog** [comment]
I'll work up a short document to describe the workflow before I begin work, and get the thing ironed out that way

**Comment by cellog** [comment]
The 4 issues above are the steps needed to implement this, plus the new read-only provider in #1225

**Comment by julien51** [comment]
closing per @cellog
