### ISSUE TITLE
Events: Change 'Upload/Select a File' to 'Upload/Select an Image'

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12946]
**Is your feature request related to a problem? Please describe.**
When users want to change the NFT image or banner of an event details page, they're asked to 'Select a File' and 'Upload File' when they are uploading an image. 

**Describe the solution you'd like**
'Upload File' should be 'Upload an Image'. The CTA should be 'Select an Image,' not 'Select a File'.

<img width="447" alt="Screen Shot 2023-11-03 at 4 38 12 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/5e292e13-78a6-401b-8f9f-ae22ec985de1">
<img width="314" alt="Screen Shot 2023-11-03 at 4 37 52 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/b5e5bf7c-d4bd-49dc-a50b-7902e0afba63">

**Comment by julien51** [comment]
Good point and it is an easy fix so I will work on this ASAP!
