### ISSUE TITLE
Events: Replace event management contract address & network w/ contract name

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12941]
**Is your feature request related to a problem? Please describe.**
When sharing the event management URL with organizers, it is a long, intimidating string. 

**Describe the solution you'd like**
Replace: https://app.unlock-protocol.com/locks/ **lock?address=0x63e6F9Cb7B546bE2AeF3a3c357d9b72b02df82f3&network=100**

With: https://app.unlock-protocol.com/locks/ **contract name**

**Describe alternatives you've considered**
Replace: https://app.unlock-protocol.com/locks/ **lock?address=0x63e6F9Cb7B546bE2AeF3a3c357d9b72b02df82f3&network=100**

With: https://app.unlock-protocol.com/event/ **management/ **contract name****

**Comment by julien51** [comment]
We now have slugs for events which are completely decoupled from the contracts themselves!
