### ISSUE TITLE
Price shows as null on UI

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#12969]
The price of [this lock](https://sepolia.etherscan.io/address/0x528da717bb9f6640d31e01e33f075e5f2f6a7804) is shown as 0 even though it should be `0,0001`

![Screenshot 2023-11-08 at 14 23 13](https://github.com/unlock-protocol/unlock/assets/743246/dfc1689d-3ebe-43f5-bba0-82b3bd960a22)

**Comment by julien51** [comment]
I think this comes down to showing the right number of significant digits! I suspect this happens in multiple places.
Can you look into this @SVell ?

**Comment by clemsos** [comment]
yes it also happen when setting the price in the settings panel. The price disappear if it is less than 0.001
