### ISSUE TITLE
Events: 'Edit Event Details' CTA directing to 'Edit NFT Properties' on event details page 

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12970]
**Is your feature request related to a problem? Please describe.**
These feature requests are based on friction I've identified when managing events on behalf of organizers and the Myosin x Unlock Dinner Party.

After organizers create an event, they are directed to their event details page. A common next step is to edit any details for the event that may need to be corrected. Today, it is not clear how to edit event details from an event details page. 

Organizers must know how to edit their event details through 'Manage Attendees' > 'Tools' > 'Edit NFT Properties', which directs to 'Edit default properties'. There is no reference on 'Edit default properties' of an event or their event details page. When they scroll to 'Event ticketing' on 'Edit default properties', their event details page URL, which is the most important part of Events to promote their event, is a text-based hyperlink to 'your event page'. 

This path to editing an event's details is unclear to anyone unfamiliar with Unlock's Membership Dashboard. 

**Describe the solution you'd like**
Create an 'Edit Your Event Details' CTA on event details pages directing to 'Edit default properties' in the Unlock Dashboard. Change 'Edit default properties' to 'Edit Your Event Details'. 

In the header of 'Edit Your Event Details', remove 'Locks' and 'Keys', replacing with 'Manage Attendees' (directing to Dashboard) and 'Share Your Event' (directing to their event details page).

On the header of Dashboard, remove 'Locks' and 'Keys', replacing with 'Edit Your Event Details' (directing to 'Edit Your Event Details') and 'Share Your Event' (directing to their event details page). 

Remove 'Certification' from 'Edit Your Event Details'. 

**Describe alternatives you've considered**
Add an 'Edit Event Details' CTA on an organizer's event details page, directing to 'Edit default properties'. 

On 'Edit default properties' include a CTA to an organizer's event details page next to the 'Edit default properties' header.

**Additional context**
<img width="701" alt="Screen Shot 2023-11-08 at 8 55 53 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/932576d3-da5d-43b0-ae93-120afba498e1">
<img width="1070" alt="Screen Shot 2023-11-08 at 8 58 10 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/4a091852-4b6e-479a-9a70-52a8b82e4685">
<img width="1036" alt="Screen Shot 2023-11-08 at 8 59 55 AM" src="https://github.com/unlock-protocol/unlock/assets/32484647/6787fa90-a424-4d7e-bf5e-b66e862889f1">

**Comment by julien51** [comment]
We now have a Settings button to edit the event directly from the EDP!
<img width="777" alt="Screenshot 2024-01-29 at 1 24 03 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/2de28f00-c294-451c-8feb-34d038ef0760">
