### ISSUE TITLE
Events: Twitter share link doesn't include the Events detail page URL

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12974]
**Describe the bug**
When users click the bird link to share an event, it opens a window to post on Twitter without the event details page URL. 

**To Reproduce**

1. Go to an [event details page](https://twitter.com/intent/tweet?text=%F0%9F%8E%9F%EF%B8%8F+I+will+be+attending+Patrick+Workman%27s+Excellent+Adventure+on+Wednesday%2C+March+11%2C+2099.+%0A%0AGet+your+ticket+with+%40unlockProtocol%21&url=)
2. Click on the Twitter share icon
3. See the Twitter post without the Events details page URL

[Loom of user journey](https://www.loom.com/share/e46295c414f54073824673c0a29cfe63)

**Expected behavior**
The Events detail page URL should be included in the Twitter post. 

<img width="594" alt="Screen Shot 2023-11-08 at 4 41 01 PM" src="https://github.com/unlock-protocol/unlock/assets/32484647/c97988ff-428c-46fc-850c-e506d1f6eb99">

**Comment by julien51** [comment]
Fixed!
