### ISSUE TITLE
Events: Calendar invites sent post registration/purchase don't appear in Google Calendar

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12971]
**Describe the bug**
After a guest registers for an event or purchases a ticket, they receive an email with event details, which looks like a calendar invite. The invite doesn't appear on their Google Calendar.

**To Reproduce**
1. Go to an [event details page](https://app.unlock-protocol.com/event/patrick-workman)
2. Register for an event, including your email address
3. Receive an email with event details
4. Look at your Google Calendar
5. See no event added to your calendar

**Expected behavior**
The event registered for should be automatically added to a guest's calendar.

**Comment by julien51** [comment]
This is not possible unless we ask users to connect their Google account and ask the permission to access the calendar.
For now we are just sending the calendar invite by email.
We may eventually ask users to connect their google accounts.
