### ISSUE TITLE
Event: Invite > Registration > Accepted Invitation Organizer Workflow

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12977]
**Is your feature request related to a problem? Please describe.**
As an organizer of an event without unlimited capacity, there are necessary steps to get people to attend:
- Invites: Send invitations with an EDP URL by email, text, telegram, discord, or another communication tool to guests you'd like to attend the event.
- Registration: Allow guests to see event details on the EDP to decide whether to attend, register, or purchase a ticket.
- Accepted Invitation: Organizers want to track the conversion of invites sent and registered attendees to balance sending additional invites and venue capacity. 

With Events by Unlock Labs, organizers cannot track who received an invite and registered, requiring them to use another tool, likely a spreadsheet, to measure attendance.  

**Describe the solution you'd like**
- Enable organizers to send invitations via email with event details and the EDP URL to potential guests through Events by Unlock Labs. 
- Allow organizers to see who they sent an invitation to and if the guest who received the invitation registered for the event through Events by Unlock Labs.

**Describe alternatives you've considered**
- After registering for an event, automatically send guests an email with event details and a calendar invite. They must respond Yes/No/Maybe. This active action ensures they know when the event will occur vs. having an invite on their calendar w/o an activity. Requiring guests to accept an invite is especially valuable at conferences, where many events overlap, requiring guests to choose what event they will attend at the moment. 
- When a guest registers for an event through an event details page, send the organizer an email notification with their guest information. 
- As invites are sent and new emails from registered guests are collected, organizers can use emails from previous events to invite guests to an upcoming event. 

**Additional context**
I've documented the organizer workflow [here](https://www.notion.so/unlockprotocol/Events-Invites-Registrations-Tracking-91bd356b3070470da38ee2ecab8bce8d?pvs=4).  

Here is [a spreadsheet ](https://docs.google.com/spreadsheets/d/1JVvLJkpmKu6k19eVkdQZ6jdVxC1R9v_K21g2agYb9Fw/edit#gid=0)I've been using to track who has been invited to an event, who has registered, and who has accepted a calendar invite.
- Selected guests are added to the spreadsheet and sent invitations with event details by email, telegram, and text.
- Registration is measured by manually tracking who has registered using Dashboard daily and then adding their registration to the spreadsheet. There should be a mechanism to notify organizers if a guest has registered.
- Calendar invites for the event are sent to each guest who has registered using Google Calendar so they accept attendance. Accepted invites are manually added to the spreadsheet.

**Comment by julien51** [comment]
This has now shipped! https://github.com/unlock-protocol/unlock/pull/13214
