### ISSUE TITLE
Lock duration in Dashboard accepts fractional values then fails

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#12987]
<img width="1096" alt="Screen Shot 2023-11-14 at 10 02 44 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/3dfee9b6-14de-4fb2-ad62-8828b1e4ce41">

<img width="1051" alt="Screen Shot 2023-11-14 at 10 09 10 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/f2eb054c-85de-42c8-ad4a-0d542269e68c">

Goal was to create a "one minute" duration lock.

Dashboard accepted a fractional value via the interface, but then failed on lock creation.

Loom of interaction:
https://www.loom.com/share/73704b34f2684425a04c525ce5b9e77f

Could gracefully disallow fractional values and instruct that more granular values than "one day" can be updated directly on the smart contract via a block explorer.

**Comment by julien51** [comment]
Thanks! I will look into this. I am not sure what the best way to solve this is...
