### ISSUE TITLE
Prefix for receipts

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#12999]
Our dashboard includes the ability for lock managers to customize the receipt details for each transaction.
We should add the ability for lock managers to set a "prefix" for the receipts so that when an organization has several locks with receipts they avoid having duplicate receipt numbers.

**Comment by teawaterwire** [comment]
prefix would be set in the settings/receipt section for a lock?
then displaying the prefix before the receipt number?
(seems to be a bug at the moment regarding the receipt number)
![image](https://github.com/unlock-protocol/unlock/assets/1702973/aab150f5-5fd2-41c8-8799-fe0b6e5908d5)

**Comment by julien51** [comment]
> prefix would be set in the settings/receipt section for a lock?

Yes, this screen should include the ability to set a prefix. Let's limit the size of the prefix to 6 characters (and no space).

<img width="1229" alt="Screenshot 2023-12-04 at 4 59 26 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/3c47be83-18fd-4803-a278-9d1454f44791">

> then displaying the prefix before the receipt number?

Yes, we should then display the receipt number with the prefix ahead of it. Here is an example : (Prefix should be displayed uppercase, and separated from the number by a hyphen `-`). There the prefix is `EARLYBIRD`.


<img width="554" alt="Screenshot 2023-12-04 at 5 09 18 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/a9a82389-d092-4a31-bcc4-46ce3dc6fca6">
