### ISSUE TITLE
Bulk export receipts

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13001]
Currently, receipts have to be downloaded one by one. This is a bit cumbersome for lock managers.
Let's add the ability to download all receipts as an async job.
A background job should be triggered when the user clicks the button to download all receipts. 
the background job will generate every single receipt as a PDF and combine them in a large zip file. 

Once completed, the user should be able to download the file.

Since the export can take a while, we should probably create a specific model in the database that will keep track of all the "exports". The table will keep track of the status of the job (pending, completed). The Settings UI should list any "recent" export (last 30 days) and allow users to download the ones that are completed.

**Comment by 0xRowdy** [comment]
I'm interested in this bounty

**Comment by julien51** [comment]
Thanks @0xRowdy ! Please feel free to ask any question that arises here or on Discord!

**Comment by searchableguy** [comment]
This was already done. There is an API endpoint if you look into the openapi spec. The only change needed is to create a button which makes a request to that endpoint on the frontend.

**Comment by 0xRowdy** [comment]
> The backend was done. There is an API endpoint if you look into the openapi spec. The only change needed is to create a button which makes a request to that endpoint on the frontend.

Great to hear. Thanks for the update.

**Comment by 0xRowdy** [comment]
> The backend was done. There is an API endpoint if you look into the openapi spec. The only change needed is to create a button which makes a request to that endpoint on the frontend.

@searchableguy Can you confirm this is the correct API for this issue? 
https://docs.unlock-protocol.com/api/locksmith/get-receipts

**Comment by searchableguy** [comment]
Yes @0xRowdy

**Comment by iMac7** [comment]
@0xRowdy still working on this? 👀

**Comment by julien51** [comment]
@iMac7 It's yours if you want it!

**Comment by julien51** [comment]
@iMac7 I tested and things are working as expected for me! Can you please confirm I can send a USDC payment to this `0x88751a1a1fCC8ae52a9eE596e9B6B5b26409e562` on Base or Optimism?

Thanks!

**Comment by julien51** [comment]
This was just paid https://basescan.org/tx/0x037c0698f9306dcb706ace3844f9fd937e1ff69daec855cb9a101e2af2b17c53
