### ISSUE TITLE
Filter ticket by transaction hash

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13000]
On the Lock page we should let the lock managers look up by transaction hashes.

**Comment by teawaterwire** [comment]
it seems that we can get "list of transaction hashes for purchase/extensions of a specific token" from the subgraph.
so that would be about adding this option in the select/filter.

**Comment by julien51** [comment]
> it seems that we can get "list of transaction hashes for purchase/extensions of a specific token" from the subgraph.

Exactly. The `Key` object in the subgraph has a `transactionsHash` property which is an array for transaction hashes for a specific Key (NFT). It's an array as if the Key is renewable and has been renewed, there are multiple transactions (an initial one for the purchase, and then ones for extensions).
Here is an example of query you can use [on the Goerli subgraph](https://thegraph.com/hosted-service/subgraph/unlock-protocol/goerli-v2):

```graphql
{
  keys(where:{transactionsHash_contains: ["0xf14c805e5d794e408c0dc28b1114c828b51992947c8f2511ed8cd415b9bcda10"]}) {
    lock{
      address
    }
    tokenId
    owner
    transactionsHash
  }
}```


In terms of UI, let's add an option in this dropdown (`Transaction Hash`) where the value that needs to be added is a transaction hash. The search should be case insensitive, and ideally should support partial hashes...

<img width="1171" alt="Screenshot 2023-12-04 at 3 55 18 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/d5d9c9cb-f15c-456c-be46-eb05d044c7f7">
