### ISSUE TITLE
Look into adding a logger for deep debugging scenarios

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#1301]
We've run into a few tricky to debug situations, giving us the need to add additional logging to the application. 

We'll probably need to add a logger to give this work some structure while allowing us to gain insight into these scenarios

**Comment by cellog** [comment]
Where were you imagining the logging would happen? I saw Julien did a server logger. Were you imagining something like using the log npm package to log stuff in my places?

**Comment by akeem** [comment]
Yes, something along these lines. We can move away from relying on console.log, use the logger and modulate the level of output based on the current log level
