### ISSUE TITLE
Events: Batch ticketing to avoid lag between fiat and crypto payments

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#13066]
**Is your feature request related to a problem? Please describe.**
Demand is more significant than supply when tickets when events like EthCC go on sale. Payments are processed faster for users who purchase tickets with crypto vs. fiat. This creates friction for organizers from attendees who believe they bought a ticket with fiat and discover no tickets are available. 

**Describe the solution you'd like**
When tickets are purchased, each transaction is time-stamped based on when a user 'purchases' a ticket. When tickets sell out, attendees who 'purchased' a ticket are airdropped a ticket, receiving an email with their ticket and event details. 

**Describe alternatives you've considered**
Enable organizers to create an event with tickets that can only be purchased with fiat so attendees paying with crypto and fiat are only competing for tickets based on their currency. Organizers would set supply for both fiat and crypto payment options.

**Comment by julien51** [comment]
I am not sure we can solve that problem in fact. Both payments (crypto or fiat) are actually "competing" onchain.
