### ISSUE TITLE
Discount code not applied when using fixed credit card prices

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13065]
When a lock uses a fixed credit card price, we don't take possible discounts into account.
This should still be possible by 'recovering' the discount %age from the `data` field and just apply that discount to the fixed price from the database.

**Comment by njokuScript** [comment]
@julien51 I can start with this or this other one: https://github.com/unlock-protocol/unlock/issues/13454

**Comment by njokuScript** [comment]
Hi @julien51, Do you have a test checkout url that has a discount code and accepts credit card as a payment method?

**Comment by julien51** [comment]
> Hi @julien51, Do you have a test checkout url that has a discount code and accepts credit card as a payment method?

Nope but you can/should create one from the staging site https://staging-app.unlock-protocol.com/
There you can use Stripe's test card numbers, etc!

**Comment by njokuScript** [comment]
> > Hi @julien51, Do you have a test checkout url that has a discount code and accepts credit card as a payment method?
> 
> Nope but you can/should create one from the staging site https://staging-app.unlock-protocol.com/ There you can use Stripe's test card numbers, etc!

Hi @julien51, can you help me create a staging link that accepts card payments and has a discount code? I can't seem to approve stripe payments on my settings

**Comment by julien51** [comment]
It is applied and was solved!
