### ISSUE TITLE
Close Paywall modal causes infinite signing loop

### ISSUE THREAD

**Issue by jterskine** [unlock-protocol/unlock#13084]
**Describe the bug**
Requests repeated signatures after declining

**To Reproduce**

1. Run `main` branch on https://github.com/jterskine/examples-1/tree/main/examples/paywall/wagmi
2. Click on connect wallet
3. Click "Checkout!"
4. Don't sign and click checkout modal

**Expected behavior**

If user signs, should not ask for repeated signatures

**Screenshots**

https://github.com/unlock-protocol/unlock/assets/2965738/2f832222-9e25-44ea-8d80-8e589d9938b7

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Tested on Chrome and FF 
- Version: `"@unlock-protocol/paywall": "^0.6.8",` and ` "@unlock-protocol/networks": "^0.0.16",`

**Additional context**

**Comment by julien51** [comment]
@jterskine Thanks for reporing! This is indeed quite annoying. 

Fix incoming!
