### ISSUE TITLE
Add Native USDC to Base Mainnet (Not USDbC)

### ISSUE THREAD

**Issue by repfigit** [unlock-protocol/unlock#13109]
Please add native USDC on Base instead of (or in addition to) USDbC? 

It causes some confusion as they're two different token addresses and native USDC is the more intuitive option.

Native USDC has been available since Sep 2023.  https://www.circle.com/blog/usdc-now-available-natively-on-base

Thx in advance.

**Comment by julien51** [comment]
Thanks! We will in fact add _both_ to make sure users can switch from one to the other easily.
