### ISSUE TITLE
Custom emails don't respect line breaks

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#13186]
<img width="879" alt="Screenshot 2024-01-09 at 7 54 19 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/dc682a7d-1c17-42db-8493-c577c775e71f">

<img width="762" alt="Screenshot 2024-01-09 at 7 54 37 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/e5a8983d-694f-4954-a985-b19d1de354da">

**Comment by julien51** [comment]
<img width="1531" alt="Screenshot 2024-01-10 at 2 18 54 PM" src="https://github.com/unlock-protocol/unlock/assets/17735/ffe7e189-9b50-4688-9c9c-cd0e6eb76401">
