### ISSUE TITLE
Custom emails heavily Unlock Protocol branded 

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#13187]
the custom emails are heavily Unlock Protocol branded. when an event organizer is sending out an email, the icons and links at bottom and heavy branding make it feel like the email is coming from Unlock, not the organizer.

request is to remove most/all of the heavy unlock branding where possible from custom emails

<img width="762" alt="Screenshot 2024-01-09 at 7 54 37 AM" src="https://github.com/unlock-protocol/unlock/assets/214760/5f6e149d-6f59-4784-819c-cd90c8d89ea1">

**Comment by julien51** [comment]
This was fixed per the convo last week. Deploying today.
