### ISSUE TITLE
Gitcoin Passport hook

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13208]
Can we create a Hook for `onKeyPurchase` that would require the recipient of the NFT to have a Gitcoin passport?

**Comment by julien51** [comment]
We could also add one for PolygonId.

**Comment by julien51** [comment]
And proof of humanity https://github.com/unlock-protocol/unlock/issues/13208

**Comment by julien51** [comment]
Let's start with the Gitcoin hook!
The goal of the system is to let a lock manager "restrict" who can purchase memberships on their locks based on having a valid Gitcoin Passport. To get there we need to perform multiple things.

- Create a smart-contract hook (very similar to the Guild Hook or the [CaptchaHook](https://github.com/unlock-protocol/unlock/blob/c299fc1d6ffe08b4f1d234fffbbb4df72fa4ce16/smart-contracts/contracts/hooks/CaptchaHook.sol#L4)) that will 'fail' the transaction, unless the signer is one of the backend Locksmith signers. That contract will in fact be pretty much identical, and we could maybe just ruse the `CaptchaHook` for simplicity.

- Create a backend API call which, given a user address, will verify that the user has a valid Gitcoin passport. If they do, sign a response (again, similar to the CaptchaHook behavior) which can then be passed as a param to the `purchase` transaction.

- Update the front-end 
    -  In the lock settings, let the lock manager "select" the new Gitcoin Passport Hook
    -  In the checkout flow, adds the verification step and show a message to the user if they do not have the right Gitcoin passport.

Let me know if you have questions! We are attaching a 500 USDC bounty to this feature!

**Comment by 0xTxbi** [comment]
got it!

thanks for the details! i'll begin working on this.

**Comment by 0xTxbi** [comment]
> Let's start with the Gitcoin hook!
> 
> The goal of the system is to let a lock manager "restrict" who can purchase memberships on their locks based on having a valid Gitcoin Passport. To get there we need to perform multiple things.
> 
> 
> 
> - Create a smart-contract hook (very similar to the Guild Hook or the [CaptchaHook](https://github.com/unlock-protocol/unlock/blob/c299fc1d6ffe08b4f1d234fffbbb4df72fa4ce16/smart-contracts/contracts/hooks/CaptchaHook.sol#L4)) that will 'fail' the transaction, unless the signer is one of the backend Locksmith signers. That contract will in fact be pretty much identical, and we could maybe just ruse the `CaptchaHook` for simplicity.
> 
> 
> 
> - Create a backend API call which, given a user address, will verify that the user has a valid Gitcoin passport. If they do, sign a response (again, similar to the CaptchaHook behavior) which can then be passed as a param to the `purchase` transaction.
> 
> 
> 
> - Update the front-end 
> 
>     -  In the lock settings, let the lock manager "select" the new Gitcoin Passport Hook
> 
>     -  In the checkout flow, adds the verification step and show a message to the user if they do not have the right Gitcoin passport.
> 
> 
> 
> Let me know if you have questions! We are attaching a 500 USDC bounty to this feature!
> 
> 
> 
> 

got it!

thanks for the details! i'll begin working on this.

**Comment by julien51** [comment]
@0xTxbi Any progress on this? We have someone else who is interested on taking that one. Please respond within 48 hours!

**Comment by 0xTxbi** [comment]
progress has been made. would make a PR for the GitcoinHook contract and it's necessary test and deploy scripts. At the moment, it is deployed on the Sepolia network.

It has also being integrated into the backend and the logic for verifying gitcoin passport scores has been added. currently enhancing how the UX for verification would be for users in the checkout UI

**Comment by julien51** [comment]
> progress has been made. would make a PR for the GitcoinHook contract and its necessary test and deploy scripts. At the moment, it is deployed on the Sepolia network.

That's the right way!

> I am currently following the V2 API structure for the backend API call for the gitcoin verification logic. is that fine?

Yes! using v2 routes is better!

Please, do keep us in the loop as you make progress and feel free to open a "draft" PR so we can start looking at it and guide you better!

**Comment by julien51** [comment]
This was just paid https://optimistic.etherscan.io/tx/0xde9358d791c3c0d74341053c522ae9482063c3d9df1f268cbf97cb49b172314f
