### ISSUE TITLE
Improve Verification data

### ISSUE THREAD

**Issue by crypto-fans** [unlock-protocol/unlock#13211]
A s a Improvement Idea for QR verification in Memberships, it would be interesting to  have the hability to add names when adding verifiers.

Later, when these verifiers  mark tickets as  checked in, it would show the adress and the specified name of the verifier. 

Name is important for when working with a lot of verifiers/partners with the possibility to add a name when adding the verifier  wallet address, so it appears:  
```
Checked In :  A few seconds ago   
Verifier:  Name (in case there is) / Wallet address (with ENS resolution)...
```

![Captura de pantalla (580)](https://github.com/unlock-protocol/unlock/assets/99991532/251a229e-61bc-4e90-8d4f-90814635e7b8)

**Comment by julien51** [comment]
Let's add a 200 USDC bounty/reward for that one!

**Comment by JoaoCampos89** [comment]
Thanks for the tips @julien51 . I started worked on this and did the 2 things that you mention, and I think there is more places that we need to change or I am not understanding well the requirements.

 I need to create an array replacing checkedInAt for a new array, could be named checkedInMetadata where I save the checkedIn date and the verifier metadata. Then I need to change as well the KeyData model to include the account that verified the QR code or the Ticket.

On ticket  controller on the method markTicketAsCheckIn I need to pass the account that verified to then be able to save on the KeyData model, for finally pass this data on the method getTicket.

Let me know if this makes sense.

**Comment by julien51** [comment]
> I need to create an array replacing checkedInAt for a new array, could be named checkedInMetadata where I save the checkedIn date and the verifier metadata. Then I need to change as well the KeyData model to include the account that verified the QR code or the Ticket.

Oh we actually already support multiple check-ins as the metadata `checkedInAt` can be an array (see https://github.com/unlock-protocol/unlock/blob/099032f7a96c0e1550f19abeaaac576f42bd368a/locksmith/src/controllers/v2/ticketsController.tsx#L46). This code is a bit complicated already because it handles both the (legacy) single check-in and multiple check-ins. One idea could be to change this array of timestamp to an array of {time,verifier} objects.

**Comment by JoaoCampos89** [comment]
@julien51 should I move forward with my approach?

**Comment by julien51** [comment]
@JoaoCampos89 Let's try, yes!

**Comment by julien51** [comment]
@JoaoCampos89 any progress on that front?

**Comment by JoaoCampos89** [comment]
@julien51 I will try to do a pull request till end of this week.

**Comment by JoaoCampos89** [comment]
@julien51 I added a initial pull request for this, let me know if I am on the right path.

**Comment by julien51** [comment]
@JoaoCampos89 you'te but only in the right path but you're almost there!

**Comment by JoaoCampos89** [comment]
0x5265Bde27F57E738bE6c1F6AB3544e82cdc92a8f

**Comment by julien51** [comment]
Thanks @JoaoCampos89 ok to pay on Base? I will send 200 USDC/

**Comment by JoaoCampos89** [comment]
Yes

**Comment by julien51** [comment]
This was just paid! Thanks for your patience...
