### ISSUE TITLE
LYKIN: Web3 Metaverse & Infusion Marketplace

### ISSUE THREAD

**Issue by joeyfoldi** [unlock-protocol/unlock#13229]
### Description

LYKIN's Generative AI Web3 and metaverse technologies empower the individual and weaves together communities. LYKIN connects digital-to-digital, digital-to-physical, and physical-to-digital. "Drag any of your digital content into the physical world using our 'Bottom Up' approach for persistent shareable experiences on a global scale.

Our No-Code and UNLOCK-SDK enables superpower-like abilities for non-technical users and developers. Imagine the accelerated and cost-effective onramp for future UNLOCK community members and groups with a reduced barrier to entry to create untold number of aps and Layers. "Touchless" Smart Contract and metaverse authoring gives the ability to create experiences that transcend written language and democratizes communications.

Infusion Marketplace is the intersection of the UNLOCK blockchain and traditional industries with: 1) immediate member-level monetization, 2) SEC regulation satisfaction (in the United States), and 3) Overall UNLOCK cryptocurrencty valuation lift. Together we will fundamentally change the way anyone, anywhere, creates virtual and IRL experiences to advance the adoption of your altcoin and ultimately effect societal change.

### Website URL

http://www.LYKIN.com

### Twitter

https://twitter.com/getlykin

### Github

n/a

### LinkedIn

https://www.linkedin.com/in/jfoldi/

### Discord handle

https://discord.com/invite/ZEMTuTCe6Z

### Completion time

12-18 months depending on Grant pledge amount.

### Team

Our team has both On-world & Off-world experience. We’ve fixed stuff on Mars!  

https://www.linkedin.com/in/jfoldi/  

https://www.linkedin.com/in/christopher-p-santos/  

https://www.linkedin.com/in/rafaelrayo/  

https://www.linkedin.com/in/debbagh/  

https://www.linkedin.com/in/ruthychen/

### Milestones

Funding Goals & Activation Thresholds
2 months - Step 1 (Wave 1)
Layers
Grids
Elevation
Fellow Layer on LYKIN

2 Months - Step 2 (Wave 1)
UI/UX development & updates
Artificial Intelligence (AI) Content Authentication 

2 Months - Step 3 (Wave 1)
Infusion Marketplace - Internal
Fellow Apps

3 Months - Step 4 (Wave 1)
Infusion Marketplace - External
Fellow Apps - New Fellows & Updates for Existing Fellows`

4 months - Step 5 (Wave 2)
Artificial Intelligence (AI) 2.0
MetaPhysical Toolkit
No Code

4 Months - Step 6 (Wave 2)
SDK
Generative AI - Metaverses
Generative AI - Smart Contracts
3DAF

### Requested grant amount

Other amount, or not requesting UDT

### Anything else you think we should know, including why you've requested a particular grant amount

The LYKIN platform will benefit your protocol and ecosystem by:
- Dramatically increasing Member-level engagement
- Massive New-Member recruitment and onboarding
- UDT token overall Valuation Lift

Please see our attached proposal for a detailed explanation, roadmap, tech stack, and Fellowship offer.

Thank you for your consideration.
https://drive.google.com/file/d/14fdr8XrbzoPev90tYO-q6yvyvOrZecuH/view?usp=sharing
[LYKIN+UNLOCK Proposal.pdf](https://github.com/unlock-protocol/unlock/files/14016689/LYKIN%2BUNLOCK.Proposal.pdf)

### Is your work Open Source

Yes, my project will use an Open Source license such as MIT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ccarfi** [comment]
Hi @joeyfoldi — thanks! Two quick questions/requests:
1) Can you please update the name of this grant request to the name of your project (right now has the default "Project Name <- Replace me!" :)
2) How'd you hear about Unlock?

thanks!

**Comment by joeyfoldi** [comment]
Done!Thanks for the catch, Christopher. We found you on the Blockworks website. https://www.blockworks.co/grants/programsI think we could be a really good fit - bridging the traditional with the non-traditional. Cheers!JoeySent from my alter egoOn Jan 22, 2024, at 16:14, Christopher Carfi ***@***.***> wrote:﻿
Hi @joeyfoldi — thanks! Two quick questions/requests:

Can you please update the name of this grant request to the name of your project (right now has the default "Project Name <- Replace me!" :)
How'd you hear about Unlock?

thanks!

**Comment by Calla-Ji** [comment]
Hi there and GM @joeyfoldi,

Thank you for your application!
I read your entire proposal and understand that your application pulls data together from various platforms to create cross-platform augmented reality experiences (please correct me if I misunderstood).
What I have not yet quite grasped is how Unlock Protocol will be weaved into all of this. Could you explain this in two very clear sentences, please :). 
Additionally, it was confusing to me that you labeled Unlock Protocol as a blockchain. "Ʉnlock is a protocol for memberships built on a blockchain," but it is not a blockchain, just for clarification purposes.

Looking forward to your reply!

**Comment by joeyfoldi** [comment]
Hi @Calla-Ji, 

Great questions! (apologies for the delayed response, I got hit with a really bad case of "standard" influenza)

LYKIN enables anyone to drag ANY digital asset, along with its inherent properties, values, instructions, or impacts into the physical world - persistently. We chose the "Bottom Up" approach instead of the "Top Down" Microsoft or [insert "Metaverse" company here] where you have to join their app, webpage, or world. The world you see and exist in IS the metaverse! You should be able to, as you browse the Internet this very moment from your cellphone, drag digital content into YOUR world - and be able to share it with anyone/everyone.  
   
Think of how protocols of the past have been brought to the forefront. SMTP with a web frontend like Hotmail.com literally launched the killer app for the World Wide Web. Usage and the value of a protocol is only as good as the applications built on top of them. 

LYKIN is building both an SDK for sophisticated users and a No-Code version to enable superhuman powers to create. Wrap linked virtual experiences that exist in the physical world in the Ʉnlock protocol and deploy on a layer, within a layer, over a layer (if you like) within the physical world. If the average person, that is non-technical, can easily create these digital experiences (that have your protocol embedded), content is unleashed. Some people will make crappy experience, but some will get it and make wonderful experiences. LYKIN is creating the tools that will engage the next BILLION "normies." The average Ʉnlock community member can now have an active "say" in that movement. You already have a small army of believers in the protocol. LYKIN gives them the tools to mobilize, create, recruit, and propagate. It's like your own personal app store for Ʉnlock. 

Note: Just for clarity, the Ʉnlock community we talk about extends past your Foundation and specifically to the organizations you market Ʉnlock for creating memberships. As one oversimplified example, LYKIN can be the Frontend your clients/community utilize to implement their solutions - while being underpinned by the Ʉnlock protocol.    

My apologies for the proposal if we mislabeled things. I will update the proposal and repost it - but the idea is still the same: You can be a protocol, Layer 1 blockchain, or other and manipulate LYKIN in various ways to engage your existing community...and more importantly onboard "normies" that have no clue they are even using your protocol (e.g. like most people that use the internet today).  You can give it a face (Hotmail example), or create untold number of applications that use it in the background (e.g. UDP for chat, gaming, vidoes, DNS, etc...).

I hope this provides more clarity to your questions. Please keep them coming!

(Apologies for the lengthy, non-2 sentence response, I am passionate about what we are doing. Although we've created a simple way to use our technology it is neither trivial to execute nor easy to explain. "Like describing the metaverse and blockchain to my mother.")

**Comment by wonderwomancode** [comment]
@joeyfoldi, for clarification, because I don't wish to make assumptions, you will be integrating Unlock Protocol into your own SDK. You currently don't have that SDK written, which is fine, but when you write it, people will be able to. 

1. Create new Unlock NFTS?

2. Update Unlock NFT's?

3. Interact with Unlock NFTs in some way

Please specify how you intend to have your SDK integrate Unlock Protocol, specifically.

Let me explain why this is important to us as a DAO. Network traffic is how we measure success; knowing how much network traffic is likely expected is one way that we determine whether or not to award a grant. Network traffic has no upside if your platform doesn't create new NFTs. However, there is still value to the community in having tools that help us visualize the NFTs created in other places, but usually with a more minor immediate impact on network traffic. Hopefully, that makes sense.

Something else I need clarification on is under Requested Grant Amount; you said "other amount, or not requesting UDT." what are you asking for then? To be clear, you don't need permission to integrate the protocol into your SDK. That process is entirely permissionless since this is an open-source project, and I'm more than happy to help you through any part. If you'd like to get some funding, please let me know how much. Just so you know, we typically make those in UDT because that is mostly what we have in our treasury, and the amounts generally range from 100-500 for integrations, but there are no hard and fast rules. When you ask for funding, since you are early, be conservative, realizing you have a better chance of getting funded that way, and you can always break your integration up into different parts, finish one thing, and then ask for more on the next.

Hopefully, this will help you understand some more.  Thanks for helping us evaluate things better.

**Comment by ccarfi** [comment]
Archived.
