### ISSUE TITLE
OpenGraph Image throws 404 on Events

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#13304]
OpenGraph image tags for OG / Twitter / etc have a non-resolving URL.

Example:
https://app.unlock-protocol.com/event/vino-vibes-and-sushi-with-charmverse

https://www.opengraph.xyz/url/https%3A%2F%2Fapp.unlock-protocol.com%2Fevent%2Fvino-vibes-and-sushi-with-charmverse

All seem to map to
`<meta property="og:image" content="https://app.unlock-protocol.comlocksmithEventOG">
`

**Comment by julien51** [comment]
This was fixed!
