### ISSUE TITLE
Duplicated email fields

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13320]
Do not show "twice" the email field on checkout.
If we have both a meatdataInput + `emailRequired` we should only show a single email field!
![image](https://github.com/unlock-protocol/unlock/assets/17735/e3292efa-1733-439d-b096-6f7565359f36)

**Comment by julien51** [comment]
This is pretty small, so let's add 100 USDC @0xTxbi !

**Comment by 0xTxbi** [comment]
> This is pretty small, so let's add 100 USDC @0xTxbi !

LGTM! let's do it!

**Comment by 0xTxbi** [comment]
pr to fix the bounty has been submitted.

pr – #13828 13828
wallet addess –  0x8022b0078d899b6e2f17949f45d78968f59c9070

**Comment by julien51** [comment]
Thank you so much @0xTxbi ! I just merged your PR and sent the payment! https://optimistic.etherscan.io/tx/0xad2efbb61ba4a37e4279f205742ed3dab18a33d70c9f1a68e10ffe1482df8011
