### ISSUE TITLE
Passing email address to Stripe

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13348]
If the user uses an Unlock account, or if they have an email linked to their wallet, we should try to pass it to Stripe's form so the user does not have to enter it twice.

**Comment by julien51** [comment]
Exactly!

**Comment by julien51** [comment]
Hey @0xTxbi want to take that one on? this is a pretty small one, so we are attaching a 150 USDC bounty here.

**Comment by 0xTxbi** [comment]
> Hey @0xTxbi want to take that one on? this is a pretty small one, so we are attaching a 150 USDC bounty here.

yes, interested! that works!

**Comment by 0xTxbi** [comment]
pr to fix the bounty has been submitted.

pr – #13833
wallet addess –  0x8022b0078d899b6e2f17949f45d78968f59c9070
