### ISSUE TITLE
Share link to Farcaster frame when sharing event to Warpcast

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#13367]
In [unlock](https://github.com/unlock-protocol/unlock/tree/master)/[unlock-app](https://github.com/unlock-protocol/unlock/tree/master/unlock-app)/[src](https://github.com/unlock-protocol/unlock/tree/master/unlock-app/src)/[components](https://github.com/unlock-protocol/unlock/tree/master/unlock-app/src/components)/[content](https://github.com/unlock-protocol/unlock/tree/master/unlock-app/src/components/content)/[event](https://github.com/unlock-protocol/unlock/tree/master/unlock-app/src/components/content/event)
/CastItButton.tsx

on line 29 could link to:
https://unlock-frame.vercel.app/events/s/${event.slug} 

which would automatically create a frame on share to Warpcast

**Comment by julien51** [comment]
We are using `https://events-frame.unlock-protocol.com/events/s/`

**Comment by julien51** [comment]
Done!
