### ISSUE TITLE
Iframe z-index change breaks developer overlay and blocks subscription status flag

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1338]
**Describe the bug**
#1279 fixed the issue with the iframe getting in the way of links on the page, but unfortunately caused the developer overlay to not respond to hover. Similarly, to implement #980 we'll need the flag element to respond to hover as well.

Per previous discussion, a possible solution is to resize and reposition the iframe so that it goes to the right-margin of the page and stays above things. This will require some thought to make sure it doesn't block anything, and can also fit both the subscription status flag and the developer overlay. (Maybe when we're on dev, the subscription status flag can contain both?)

**To Reproduce**
1. Launch demo page on master
2. Purchase key
3. Attempt to use the developer overlay to switch provider

**Expected behavior**
Developer overlay will slide out on hover and allow me to change provider.

**Comment by cellog** [comment]
oh that's a slick idea to incorporate the developer overlay into the flag for development :). Another solution is to not change the z-index on development, which may be more complex to implement, I'm pretty sure the `paywall.min.js` script can't know this.

If we go with the shrinking-iframe solution, then I think the best path is to combine the overlay and the flag as you suggest.

**Comment by cellog** [comment]
fixed by the one and only @cnasc
