### ISSUE TITLE
Remove mumbai from supported networks

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#13429]
The Polygon Mumbai testnet is getting deprecated (as it uses Goerli underneath) and we should remove it from our supported networks. 

see official annoucement : https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos

> The beloved and widely used Mumbai testnet for Polygon PoS uses Ethereum’s Goerli testnet as its root chain. This means Mumbai counts on Goerli for block production. 

relates to #13428

**Comment by StephanGerbeth** [comment]
Do you plan to deploy unlock to amoy?

**Comment by clemsos** [comment]
> Do you plan to deploy unlock to amoy?

Hello @StephanGerbeth, we are limiting the number of testnets we support atm so we wont be supporting Amoy - only Sepolia and Base Sepolia.
