### ISSUE TITLE
Deprecate goerli

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#13428]
The Goerli testnet has been officially deprecated and we should remove support for it

- [x] add deprec notice on UI with fixed date
- [ ] remove from networks package
- [ ] remove from tests ? (see #11522)
- [ ] remove Mumbai (#13429 )

**Comment by njokuScript** [comment]
Hi, can I pick this up?

**Comment by clemsos** [comment]
> Hi, can I pick this up?

Hey, actually we will have to wait for the deprecation notice to expire (Apr 30) before proceeding with the next steps (removing refs to goerli).

Thanks anyways !

**Comment by julien51** [comment]
@njokuScript we have a BUNCH more bounties https://github.com/unlock-protocol/unlock/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%F0%9F%92%B0bounty would you be interested in taking on a few?

**Comment by njokuScript** [comment]
> @njokuScript we have a BUNCH more bounties https://github.com/unlock-protocol/unlock/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%F0%9F%92%B0bounty would you be interested in taking on a few?

Alright got it. Yeah, will definitely be interested! let me take a look

**Comment by njokuScript** [comment]
> > @njokuScript we have a BUNCH more bounties https://github.com/unlock-protocol/unlock/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%F0%9F%92%B0bounty would you be interested in taking on a few?
> 
> Alright got it. Yeah, will definitely be interested! let me take a look

@julien51 Let me know which ones I should pick up

**Comment by clemsos** [comment]
It seems like Goerli is getting shut down on Apr 17 https://blog.ethereum.org/2023/11/30/goerli-lts-update?utm_source=substack&utm_medium=email

**Comment by clemsos** [comment]
Solved in https://github.com/unlock-protocol/unlock/pull/13540
