### ISSUE TITLE
Mint fee is missing from credit card purchase

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#13449]
The credit card total appears wrong with credit card when a fixed price is set (see below). The "minting fee (gas)" is missing from calculation and not shown on lines.

![image](https://github.com/unlock-protocol/unlock/assets/743246/a9bfbe3d-8b04-4845-8666-dd9cee56ebc0)

**Comment by julien51** [comment]
Thank you so much @Shaik-Sirajuddin ! Please post your wallet address here so we can pay the bounty here!

**Comment by Shaik-Sirajuddin** [comment]
> Thank you so much @Shaik-Sirajuddin ! Please post your wallet address here so we can pay the bounty here!

Optimisim : 
0x0ef30faa73d8dc99eca81e82f71e04240d8ee221

**Comment by julien51** [comment]
Thanks @Shaik-Sirajuddin ! This was just paid https://optimistic.etherscan.io/tx/0x6b152c015250fbe4cd8cfc7cadb08e333654a4d626e1c57ef2b182f258b29910
