### ISSUE TITLE
Refund keys extended by the lock manager

### ISSUE THREAD

**Issue by SVell** [unlock-protocol/unlock#13441]
**Describe the bug**
User can cancel and refund lock key that was extended by the lock manager

**To Reproduce**

1. Purchase a key for a lock
2. Cancel and refund it or wait until expired
3. Lock manager extends the key
4. Cancel and refund the key

**Expected behavior**
User should not be able to cancel the extended key or the cancel should be without refund

**Comment by julien51** [comment]
This is in fact the expected behavior.
