### ISSUE TITLE
Buy "multiple" periods at once

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13444]
Right now, the `purchase` function only supports buy 1 period.
An interesting feature could be for users to "pre-pay" multiple periods in a single transaction.

One of the challenges would be to *not* break compatibility by keeping the `purchase` function "as is" but adding a new function which can be used to purchase multiple periods for a single recipient.

**Comment by njokuScript** [comment]
can I pick this up?

**Comment by clemsos** [comment]
Related to https://github.com/unlock-protocol/unlock/issues/13457

**Comment by julien51** [comment]
> Related to https://github.com/unlock-protocol/unlock/issues/13457

Agreed! If we move to a Struct for each key, then we should add a `periods` attribute in the struct (default to 1) that would show how many periods have been bought. and the `value` attribute should reflect that `periods` value.
