### ISSUE TITLE
Promo Code UX in Modal Needs Reworking

### ISSUE THREAD

**Issue by isaac-martin** [unlock-protocol/unlock#13454]
When entering a promo code, it appears that onChange of the input it validates the promo code, however if that API call is still in progress I can press skip, which doesn't apply my promo code (even if the input is valid)
 

<img width="459" alt="image" src="https://github.com/unlock-protocol/unlock/assets/8649366/3e926426-b6db-453d-9016-7c19346be17f">

The Main CTA should when pressed

- Validate promo code
  - if code not valid show an error message (and maybe a secondary CTA to skip)
  - if code valid, continue to next step
 
 Also while writing this i realized there is no indication that a promo code is invalid, only if valid. 
 
 
<img width="495" alt="image" src="https://github.com/unlock-protocol/unlock/assets/8649366/1e6bf589-3faf-4849-9f03-c228462df5e7">

**Comment by julien51** [comment]
Thanks @isaac-martin !

**Comment by julien51** [comment]
@njokuScript want to take that one?

**Comment by njokuScript** [comment]
> @njokuScript want to take that one?

Sure! Is that a frontend or locksmith related issue?

**Comment by julien51** [comment]
Front end!

**Comment by njokuScript** [comment]
> Front end!

sweet! On it.

**Comment by njokuScript** [comment]
Just to be certain, this is the issue we're talking about: https://github.com/unlock-protocol/unlock/issues/13065 @julien51
