### ISSUE TITLE
Add more networks to the cross-chain governance 

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#13463]
As the Connext bridge is now supporting more networks, we need to add the ones we use to our cross chain gov process https://docs.connext.network/resources/deployments

Process is 

- [ ] add `governanceBridge` section to the network package: https://github.com/unlock-protocol/unlock/blob/15c396ea583dc9fa2d6901d68c478a6a3f93b077/packages/networks/src/networks/optimism.ts#L22C2-L29C5
- [ ] follow instructions in `./scripts/deploy_multisig_mods` 
   - [ ] deploy the connextMod for the multisig
   - [ ] verify the connextMod
   - [ ] deploy the delayMod for the multisig
   - [ ] verify the delayMod
- [ ]  add the modules addresses to the `governanceBridge` section with the deployed modules address
- [ ] setup modules correctly in SAFE by running the command 
 `yarn hardhat safe:submit --proposal proposals/enableModule.js --network <xxx>`

**Comment by clemsos** [comment]
Added full instructions for adding new bridge governance modules above

**Comment by julien51** [comment]
We should add these docs to README + create a healthcheck script that would automatically identify if new networks can be added.

**Comment by julien51** [comment]
Related https://github.com/unlock-protocol/unlock/issues/14489

**Comment by clemsos** [comment]
From our supported chains, only Linea is available right now on Connext. Let's wait for the cross chain migration to be finalized before we move forward with deploying it https://github.com/unlock-protocol/unlock/issues/14489

**Comment by clemsos** [comment]
Not supported by Connext as today

- zksync era
- zkevm 
- celo (?)
- avalanche
- scroll

**Comment by clemsos** [comment]
Instructions where moved to the README #14608. Closing for now
