### ISSUE TITLE
Run health-check scripts when adding new networks

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13533]
When the `networks` package is touched, we should run the health-check script and block the PR (fail CI) if there are any issue. This will ensure we only add networks that are correctly set-up and configured!

**Comment by clemsos** [comment]
so we are running into a perm issue here as the github action that adds a comment for feedback does not have enough rights to write when a PR comes from a fork. 

There is a potential solution here but not ideal https://github.com/mshick/add-pr-comment#proxy-for-fork-based-prs

**Comment by clemsos** [comment]
so for this we need

- a running version of that comment proxy app
- an auth token with correct access rights
