### ISSUE TITLE
Add script to create proposals to add ERC20 to Unlock GNP Calc

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13538]
Also, add a check against which tokens are used for GNP

**Comment by clemsos** [comment]
> Also, add a check against which tokens are used for GNP

We can check against all values in `tokens` in the package networks for instance.

**Comment by clemsos** [comment]
this has been submitted to DAO as https://www.tally.xyz/gov/unlock/proposal/2319636103025394838

**Comment by clemsos** [comment]
Executed here 

https://polygonscan.com/tx/0xa5abd6dcc642727156af8de18ac467f02ac09be5ad6d547c40270b6367f50b53
https://basescan.org/tx/0x5435c0a65e0060ef17aeb843ac21643ee60fbfbbef06d4ff53a35929fd64dccb
https://arbiscan.io/tx/0x1ee169ba9a5bc4350f143a8d5a124a21a46379de7f4913f15b1c48c23ed5261a
https://optimistic.etherscan.io/tx/0x4a8ea78e8018d4e754b47ffc1ceed88dcad55d4a090830c3062feb0ce7f412ec
