### ISSUE TITLE
Submit proposal to resume distribution of UDT

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13543]
We want to resume distribution of UDT when people use the protocol on selected networks:
* Polygon
* Base
* Optimism
* Arbitrum
* Gnosis Chain

The UDT should have been "bridged" (or made bridgeable) on all these networks. 

Prior to this, we should test that distribution works as expected on a test network!

**Comment by clemsos** [comment]
What is needed to activate the protocol

On each chain 

- [ ] bridged UDT
- [ ] Uniswap Pool (with 0.05% fee) created 
- [ ] liquidity provided to the pool
- [ ] at least one swap in the pool (to start tracking value)
- [ ] deployed Unlock Oracle contract
- [ ] verify oracle contract can fetch UDT price (wait 1h after first swap after checking historical values, else pool will revert with `OLD`)

In the cross chain gov proposal:

- [ ] run `setOracle(<UDTAddress>, <oracle address>)` in Unlock

**Comment by julien51** [comment]
@clemsos Can you update this please?

**Comment by clemsos** [comment]
Looks to me that these are all done now
