### ISSUE TITLE
Cannot mint key via checkout builder 2-nd time

### ISSUE THREAD

**Issue by SVell** [unlock-protocol/unlock#13637]
**Describe the bug**
When minting a key 1-st time, I get error 400 for clam/network/lock but can mint ({"message":"Lock is not free"})
For the 2-nd mint I get error 500 and an error on the checkout page "There was an error when preparing the transaction." ({"message":"You cannot claim the membership"})

**To Reproduce**
- Create checkout url for a lock
- Mint a key
- Mint once more

**Expected behavior**
- Second mint should work if the lock allows >1 keys per wallet

**Screenshots**
![image](https://github.com/unlock-protocol/unlock/assets/22966971/96add006-192d-40da-938a-f37c881c9f1d)
![image](https://github.com/unlock-protocol/unlock/assets/22966971/1a01f8a3-a61f-49d7-b0a1-9e697885c8b2)
![image](https://github.com/unlock-protocol/unlock/assets/22966971/97ae40ef-2cfe-4a96-abc9-c71a6b6a4b5b)
If no metadata configured:
![image](https://github.com/unlock-protocol/unlock/assets/22966971/f6fab9f0-a281-4a14-8197-46e1a0870dd3)

**Comment by julien51** [comment]
> When minting a key 1-st time, I get error 400 for clam/network/lock but can mint ({"message":"Lock is not free"})

That's not a bug. It's expected if the lock is not free that locksmith will return that to indicate that a key cannot be claimed for free.
