### ISSUE TITLE
Not allow set gas refund higher than necessary

### ISSUE THREAD

**Issue by JoaoCampos89** [unlock-protocol/unlock#13650]
**Describe the bug**

At the moment when we want others users to renew the membership we need to set gas refund, however if we set a value higher than the lock, we are not able to purchase the lock, giving us an allowance error.

**To Reproduce**

1. Use lock with token to renew memberships.
2. Set gas refund higher than the lock price.
3. It not allow now to buy the lock

**Expected behavior**

Should not allow user to set gas refund higher than the lock price. Additionally, an info field text could be used to explain about it.

**Comment by julien51** [comment]
This is a good one @JoaoCampos89 I will work on this!

**Comment by julien51** [comment]
This was just paid! https://basescan.org/tx/0x6361fb38bcba5087b88b1a645849319eb42dc3ce8a3ce95012e0a1b82e7c3081
