### ISSUE TITLE
Event landing page 404s should resolve to a page with a helpful message 

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#13670]
Currently, a user who goes to a non-existent event landing page ends up on a "Connect your wallet" experience.

**Examples:**
https://app.unlock-protocol.com/event/taco-twosday-avl-
https://staging-app.unlock-protocol.com/event/the-fake-party

Broken or non-existent URLs end up on this page
![Screenshot 2024-04-24 at 6 14 45 AM](https://github.com/unlock-protocol/unlock/assets/214760/7159af33-6c78-462d-a428-825803a5be69)

That page implies the user is in the correct place, but "needs to connect a wallet". This is incorrect and confusing.

Instead, non-existent pages on the **/event/** path should instead resolve to a helpful 404 page with a message to the effect of:

```
**404**

Hmmm. That event page does not seem to exist.

[Back to EVENTS](https://events.unlock-protocol.com)
```

The last element could be a button.

**Comment by julien51** [comment]
Good point! I will work on that!

**Comment by ccarfi** [comment]
tysvm
