### ISSUE TITLE
Change members counter in members list

### ISSUE THREAD

**Issue by kryzpee** [unlock-protocol/unlock#13685]
**Is your feature request related to a problem? Please describe.**
The "Total members" counter in the members list includes the null-address

**Describe the solution you'd like**
I would love to either have an exclusion of the null-adress in this counter (I know, technically the null-address is also an owner, but to be consitent it should then also be visible in the members list) or...

**Describe alternatives you've considered**
 ... a seperate indicator for "Active memberships"

**Comment by julien51** [comment]
Thanks! That's a good point. This will require a contract change though so it is a bit more complex! Let me discuss this with @clemsos !
