### ISSUE TITLE
walletMiddleware swallows all actions if no user account exists

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1368]
**Describe the bug**
when logged out, the `walletMiddleware` never gets its initialization action to trigger the release of any stored actions. It is waiting for one of `[SET_NETWORK, SET_ACCOUNT, SET_PROVIDER]`

Perhaps the `web3Middleware` can spit out a `SET_NETWORK` action? Or maybe the `walletMiddleware` should just not hold on to actions?

**To Reproduce**
1. run `UNLOCK_ENV=staging npm run dev`
2. go to `http://localhost:3000/demo/0x42dbdc4CdBda8dc99c82D66d97B264386E41c0E9`
3. See error

**Comment by julien51** [comment]
I think we can actually remove this behavior altogether. I'll work on that next week!

**Comment by cellog** [comment]
this is fixed by @julien51
