### ISSUE TITLE
Adding guidelines for contributing, opening issues

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#137]
We need to work on making it easy to onboard contributors of all kinds (code, issues, docs... etc).
For this we need clear guidelines and I believe Github provides tools to do that.
We should also set up [Gitcoin](https://gitcoin.co/bounty/quickstart).

**Comment by julien51** [comment]
We also need a COC.

**Comment by abuiles** [comment]
@julien51 for the COC, have  a look https://www.contributor-covenant.org

**Comment by julien51** [comment]
Closing for now I think we've successfully implemented this [check list](https://github.com/unlock-protocol/unlock/community).
