### ISSUE TITLE
Duplicating "skip recipient" field in checkout builder

### ISSUE THREAD

**Issue by SVell** [unlock-protocol/unlock#13774]
**Describe the bug**
Currently, there are 2 checkboxes for "Skip recipient' one in "Configure the basics" section other in "Configured locks" on the lock itelf

![image](https://github.com/unlock-protocol/unlock/assets/22966971/d03ec7d2-f08a-4900-9ac3-b0cc268696e5)
![image](https://github.com/unlock-protocol/unlock/assets/22966971/74e09709-5e3a-4dc7-9dc4-b82a050cc539)

**Comment by julien51** [comment]
Good find! Please clean it up :)

**Comment by julien51** [comment]
Sorry, this is expected behavior, there is a setting at the checkout level and another one ayt the lock level. We should probably clarify the docs.
