### ISSUE TITLE
Improved paywall development workflow

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1382]
Currently, working on the paywall has a lot of friction because the related files are only built once, they don't automatically rebuild when you make changes. As a result, we have to constantly start and stop the dev server to build those changes.

**Describe the solution you'd like**
This might be part of #1205, but it would be nice if the paywall scripts automatically updated in response to changes.

**Describe alternatives you've considered**
An alternative might be to have a manual build command that can be run as needed while the server is running. It's less convenient than automation, but still better than the current process.

**Comment by julien51** [comment]
Should this be part of a larger discussion about splitting the paywall app and the creator dashboard from `unlokk-app`?

**Comment by cellog** [comment]
because the paywall does not start up ganache, restarting it takes about 30 seconds. This should be sufficient even in the worst case.
