### ISSUE TITLE
Native iOS and Android Passes API

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13855]
Our application includes the ability for owners of any NFT to add it as a "pass" on their Google or iOS devices.

For now, these passes were generated using https://ethpass.xyz/. Last year EthPass was acquired by Moonpay and it's unclear how long support for these will remain so we want to bring that capability in-house.

As such we will need to introduce a new Locksmith API that generates passes for iOS or Android. It is ok to use 3rd party libraries but we should not depend on 3rd party APIs, outside of Apple's and Google's APIs.

The API will consist of 2 `GET` endpoints:
* `/v2/pass/{network}/{lockAddress}/{keyId}/ios` and,
* `/v2/pass/{network}/{lockAddress}/{keyId}/android` 

These endpoints will respectively create the iOS and Android passes for the key `keyId` of the lock `lockAddress` on the network `network`. Importantly the pass will include the QR code signed by Locksmith so that they can be used to "store" event tickets.

The design of the passes should include the following elements and is left up to the implementer:
- key/NFT image
- key id
- lock address
- lock name
- network name
- Unlock Protocol logo

Once the API is ready it will need to be added to Unlock-app and replace the ethpass API calls!

We are attaching a 2000 USDC bounty for this feature which needs to be fully tested!

**Comment by 0xTxbi** [comment]
looks interesting! interested in taking on this bounty.

**Comment by 0xTxbi** [comment]
wallet address – 0x8022b0078d899b6e2f17949f45d78968f59c9070

**Comment by julien51** [comment]
This was just paid! https://basescan.org/tx/0x583bde9df91caf31ddbcd7c21d27325cb2e87d96b67edf510f3b040bc5f91a0b 

Thanks a LOT @0xTxbi !
