### ISSUE TITLE
Disable cancel button on keychains

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#13902]
On the keychain, we should not let a user who is not a manager for their key cancel it.
We should keep the menu active, but when the modal opens we should show a message indicating that the membership cannot be cancelled since the user is not the manager.

**Comment by julien51** [comment]
We will pay a 150 USDC bounty!

**Comment by sudheerDev** [comment]
Hey @julien51 can you assign this to me?

**Comment by julien51** [comment]
Thanks @sudheerDev ! Can ypu please paste your wallet address so I can pay the bounty? Thanks!

**Comment by julien51** [comment]
Sorry for the delay here @sudheerDev ! Cool if I use USDC on Optimism?

**Comment by julien51** [comment]
Paid! https://optimistic.etherscan.io/tx/0x50c442b961f11d8646599909454c2fbc33b29469713cba1acc0a59dc7edc4b77
