### ISSUE TITLE
Create ability to provide user with all transactions against locks (successful or otherwise) 

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#1397]
We want to be able to show to the user any transactions they’ve performed on a lock. This issue covers the investigation and should be close with the opening of an issue covering the implementation. 

There are a few avenues to leverage including the use of Locksmith for offchain storage

**Comment by julien51** [comment]
Could you clarify the intent here and what this will be useful for? 
Feel free to close if this is not applicable anymore... otherwise: tag and assign it ;p

**Comment by cnasc** [comment]
Right now we pull this information off the chain, so it can take a long time. I believe the goal here is to allow locksmith to act as a caching layer so that we can hand off that info ASAP

**Comment by cellog** [comment]
I like that idea @cnasc, I would add with a caveat that this should be just an optimistic loading layer, and that once the chain catches up, its data should replace the locksmith data, and if there is a discrepancy, that should trigger some kind of reconciliation, either an error state, or replace locksmith's data, or something else along those lines

**Comment by julien51** [comment]
This is a task for The Graph!
