### ISSUE TITLE
EVENTS organizer attendee list pagination wraps 

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#14010]
On the event organizer attendees page in the EVENTS app, the pagination at the bottom of the attendee list wraps unexpectedly. Clicking on different numbers also causes the number that is wrapped to the next line to change.(It is not always the last number that wraps, sometimes it is a number in the middle of the sequence.)

![Screenshot 2024-06-05 at 8 14 04 AM](https://github.com/unlock-protocol/unlock/assets/214760/eeaadcb2-120b-4c32-a4d0-cd0d0f9f047e)

**Comment by julien51** [comment]
ha yes I actually found that opn Monday and fixed it :) https://github.com/unlock-protocol/unlock/commit/5cf4dc6017b9e61497f102df0dfe75824fee7ffd

Should be live on the next prod deploy!
