### ISSUE TITLE
Unlock App landing page should feature "Subscriptions" as a first-class option

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#14024]
![Screenshot 2024-06-08 at 5 38 33 PM](https://github.com/unlock-protocol/unlock/assets/214760/e8b136a2-407b-4f0a-bc24-aa103ee7f32e)

1. An image option should be added before Events called "Earn subscription revenue" (so there are images for Subscriptions, Events, and Certifications" — the link should direct to the same place the "I am not sure" link directs to currently

2. **Remove** the "I am not sure yet let me create my own membership contract" text-only option below the images and add it as another option in the same style for "Create a custom membership"

3. Change the text on the Event option to read "Sell or create event tickets"

4. Change the image on the Event option to show a ticket with a QR code

5. Change the text on the Certification option to read "Create a certification" and update image

6. We will need an image for the "Subscription" option that is in the brand style

7. Simplify the text above the images

![Screenshot 2024-06-09 at 6 44 55 AM](https://github.com/unlock-protocol/unlock/assets/214760/f14a9ae6-0ca9-4bd7-be69-1198fcbc4926)

**Comment by ccarfi** [comment]
i would envision that there is eventually a landing page for Subscriptions that is similar to events.unlock-protocol.com and certifications.unlock-protocol.com that explains the messaging for Subscriptions (will be a different issue / PR)

**Comment by julien51** [comment]
> i would envision that there is eventually a landing page for Subscriptions that is similar to events.unlock-protocol.com and certifications.unlock-protocol.com that explains the messaging for Subscriptions (will be a different issue / PR)

Agreed!

**Comment by julien51** [comment]
> An image option should be added before Events called "Earn subscription revenue" (so there are images for Subscriptions, Events, and Certifications" — the link should direct to the same place the "I am not sure" link directs to currently

I will ask @ChialiT to create a basic "subscription" illustration!

**Comment by ccarfi** [comment]
![certification-icon](https://github.com/unlock-protocol/unlock/assets/214760/01e82602-e939-4b2d-bf9f-6d0d48b4451a)
![event-icon](https://github.com/unlock-protocol/unlock/assets/214760/7495fab1-ca73-4272-9b25-bc2cc28ce99e)
![new-membership-icon](https://github.com/unlock-protocol/unlock/assets/214760/d0094112-42b3-40cb-8efc-24a607dfb75b)
![subscription-icon](https://github.com/unlock-protocol/unlock/assets/214760/db144b06-6f26-48a2-b550-bbc9456db78a)

@julien51 images attached — please let me know if any edits needed

**Comment by ccarfi** [comment]
![new-membership-icon](https://github.com/unlock-protocol/unlock/assets/214760/ca2e068b-19f8-449f-9018-989ac9dab28e)
![certification-icon](https://github.com/unlock-protocol/unlock/assets/214760/1f685f62-dff9-476b-9733-783963597f9e)
![event-icon](https://github.com/unlock-protocol/unlock/assets/214760/04d75b8f-c3c5-4f4d-a7c8-75246cc9f8d3)
![subscription-icon](https://github.com/unlock-protocol/unlock/assets/214760/aba9ad6a-1f4a-4915-b4af-b9c45ea157ad)

@julien51 images attached

**Comment by julien51** [comment]
Getting there https://www.loom.com/share/0460a6cfe64247e5b1b046d2b41f2efb
