### ISSUE TITLE
Payment step of checkout is a dead end for end users if credit card not enabled

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#14027]
If credit cards are not enabled for a lock and a user without a crypto wallet gets to step four, the end user hits a dead end situation with no obvious way to either proceed or go back. Only option is "Sign out".

![payment-step-dead-end](https://github.com/unlock-protocol/unlock/assets/214760/dd8216dd-8832-423c-af01-1b4213ed286a)

**Comment by julien51** [comment]
Yes, that's always been the case. Not sure else we could do.
