### ISSUE TITLE
Minting screen spams with requests if left opened after successful mint

### ISSUE THREAD

**Issue by SVell** [unlock-protocol/unlock#14036]
**Describe the bug**
Minting screen starts to span with requests after successful minting. With time, it can cause the whole browser to lag.

**To Reproduce**
Mint any lock key and stay on the Successfully minted page

**Expected behavior**
After the key is minted, no additional requests should be done

**Screenshots**

<img width="509" alt="image" src="https://github.com/unlock-protocol/unlock/assets/22966971/c03eae38-1352-4827-8653-8c0113ba5bc4">

**Comment by julien51** [comment]
I think this is fixed now with https://github.com/unlock-protocol/unlock/pull/14033 but please check again?
