### ISSUE TITLE
Refactor paywall story to mock container for unlocked flag

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1404]
**Describe the bug**
#1402 relies heavily on the iframe to handle the positioning and hiding of the `UnlockFlag` component. Since the storybook does not use the iframe for the paywall, we'll need to massage that story so that it will display in a manner consistent with the actual app.

**To Reproduce**
1. Go to storybook
2. Click on `Paywall > the paywall overlay, unlocked`
3. Notice the vertical positioning and lack of hide behavior on the `UnlockFlag`

**Comment by cellog** [comment]
this will be fixed by the fix for #1731, and by enabling storybook in the paywall (which I'll set up now)
