### ISSUE TITLE
Docs Algolia search not returning results when results exist

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#14041]
**Describe the bug**
Docs search using Algolia does not return results for searches that definitely have matches

This was originally reported here:
https://github.com/unlock-protocol/docs/issues/327

Currently still an issue (e.g. searching "Arbitrum" in the docs returns zero results)

![Screenshot 2024-06-12 at 7 50 44 AM](https://github.com/unlock-protocol/unlock/assets/214760/d57fb989-bb05-4a35-9fdb-320d9bc8cbb5)

**Comment by julien51** [comment]
Honestly I am not sure what os going on here. Maybe we should ditch algolia? Not sure how to fix it.

**Comment by clemsos** [comment]
ok that was just a tweak in settings on Algolia. Should work now 

![Screenshot 2024-06-14 at 15 12 08](https://github.com/unlock-protocol/unlock/assets/743246/8d26dfbb-175d-455a-a5dc-35506ac890b2)
