### ISSUE TITLE
Payments Lock Settings: Currency Token Persists After Update

### ISSUE THREAD

**Issue by nestorbonilla** [unlock-protocol/unlock#14054]
**Describe the bug**
The currency token displayed in the Payments Lock Settings persists after the user selects a new token after updating the settings. This issue also occurs after refreshing the page.

**To Reproduce**
1. Select a Lock Membership, go to the Lock Settings, and finally to the Payments tab.
2. Select price, and on the currency, select any other token. (For example, import the DEGEN ERC-20 token with contract address `0x4ed4e862860bed51a9570b96d89af5e1b0efefed` on Base Mainnet.)
3. Change the selected token in the dropdown menu to a different one.
4. Click "Update" and sign the transaction.
5. Observe that the displayed currency token on the page has not changed.
6. (Optional) Refresh the page and observe that the incorrect token persists.

**Expected behavior**
After selecting a new currency token in the dropdown menu, clicking "Update," and signing the transaction, the dropdown menu should display the newly selected token. Additionally, the correct token should persist after refreshing the page.

![unlock_github_issue](https://github.com/unlock-protocol/unlock/assets/3916389/ac70c66c-a270-4aaf-a2ae-e288ce1a59bb)

**Desktop (please complete the following information):**

- OS: MacOS Sonoma
- Browser: Brave
- Version 1.67.115 

**Additional context**
No additional context.

**Comment by julien51** [comment]
Hey @nestorbonilla Thanks for reporting! I am unable to reproduce. Here is a video I recorded. https://www.loom.com/share/08cf2730a3df4a8184f8421dc6f4525a
Did I miss something?
