### ISSUE TITLE
Sending transaction hashes to Locksmith

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1405]
When a user creates a transaction we should send its hash to locksmith right away so that we have a way to keep track of it until (and if!) it has been successfully mined and added to the chain.

We should use the `storageMiddleware` for this.

**Comment by akeem** [comment]
Please expect the following endpoint point to be present [post] `/transaction`

At the moment the expectation is that the body of the request will include valid json with a property of `transaction_id` . If you would like to use something else as the identifier please state below
