### ISSUE TITLE
Retrieving user transaction hashes from locksmith

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1406]
We currently retrieve a user's past transaction from the chain itself.
This present a few challenges:
* the transaction has to have been mined (pending transactions are not returned)
* the transaction has to have triggered an event (the web3 api only allows for this to work by filtering on index-ed events

We will use locksmith as an extra layer to store user's transaction.
We need a mechanism to retrieve the hashes of transactions performed by a given user from locksmith.

**Comment by akeem** [comment]
Please expect the following endpoint to be present `/{address}/transactions`

**Comment by julien51** [comment]
So... what is `address` here? is that the `sender` or the `recipient`? Also can I expect an object of the same format as https://github.com/unlock-protocol/unlock/issues/1405?

```
{ transactionHash: '0x123', sender: '0xabc', recipient: '0x123', }
```

**Comment by julien51** [comment]
I am thinking of doing `GET /transactions` and then have a bunch of query params to filter on?

For example `GET /transactions?sender=0x123`. We could also do stuff like pagination using this for example (probably MUCH later).

**Comment by akeem** [comment]
I can add support for this as an alias but would like to keep the address centric route
