### ISSUE TITLE
Subgraph `lastKeyMintedAt` is not implemented

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#14080]
It turns out that there is a `lastKeyMintedAt` param in the lock schema but no implementation exists (so its currently always null)

**Comment by julien51** [comment]
@iMac7 Want to look at that one at the same time? It's pretty similar to https://github.com/unlock-protocol/unlock/issues/10599 (for the subgraph part). 
We are attaching 100 USDC/

**Comment by julien51** [comment]
> @julien51 julien51 apart from the subgraph, are there changes required in locksmith or unlock-app for this one?

Nope!

**Comment by julien51** [comment]
Thanks @iMac7 ! This was just paid https://basescan.org/tx/0x8cbb78f48873d9df3a0410047a622f6686b750e0e752687b745c36a5ecbec930
