### ISSUE TITLE
Extract a minimal web3Service for paywall actions

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1410]
For the paywall app, we need a minimal read-only web3Service that can do these actions:

- retrieve the latest on-chain data about a lock based on its address (price, expiration, max number of keys, current number of keys)
- retrieve any keys on a lock that match the current account (if any)

@cnasc anything I'm forgetting?

**Comment by cnasc** [comment]
I think that should cover it for the read-only part
