### ISSUE TITLE
Input with actions has a minor issue

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14109]
On some input, we have the ability to to provide `actions` which are displayed _inside_ the input. For example, we do this for the email input + continue action when users are connecting.

We need to refactor the `Input` component completely so that it supports actions much better. Also please add stories for actions (with 1 or more actions)

**Comment by julien51** [comment]
<img width="454" alt="Screenshot 2024-08-20 at 11 19 08 AM" src="https://github.com/user-attachments/assets/d11a2552-b018-4ea6-b0dc-c50a0bc5d67e">

**Comment by 0xTxbi** [comment]
got it!
