### ISSUE TITLE
eslint smart contract tests

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1424]
**Is your feature request related to a problem? Please describe.**
A best practice.

**Describe the solution you'd like**
We should be running `eslint` on the Javascript under `smart-contracts`.

**Describe alternatives you've considered**
n/a

**Additional context**
Running with current settings produces 31 errors today.  We may want to consider configuration used for unlock-app.

**Comment by hardlydifficult** [comment]
We should add this to both `npm run dev` and `npm run ci`

**Comment by julien51** [comment]
Great idea!
