### ISSUE TITLE
Let lock managers edit checkout URL

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14248]
Right now, we use the `createdBy` field on a checkout URL to list them and/or enable edits.
Instead of relying on this mechanism for "access control" we should use lock managers.

**Comment by julien51** [comment]
We will likely need to solve this in 2 steps:
1. Let a lock manager "save" a config for which they are *not* the creator, but for which they are lock manager on one of the locks. This will first require changes in locksmith, and then changes in the UI
2. List configs that were *not* created by a user, but for which the user is a lock manager on one of the locks.

**Comment by 0xTxbi** [comment]
got it!
