### ISSUE TITLE
SUBSCRIPTIONS landing page

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#14252]
Copy, images, and prototype for a subscriptions landing page to be housed at 
https://subscriptions.unlock-protocol.com

Copy here:
https://docs.google.com/spreadsheets/d/1Upfb8MCM5uhLqkGsUncvxbRcWmGu_bBqVoTvLpegpas/edit?usp=sharing

![subscriptions-opengraph](https://github.com/unlock-protocol/unlock/assets/214760/d807f8c6-5f96-4025-91b4-4793d7f39442)
![artist-and-fans](https://github.com/unlock-protocol/unlock/assets/214760/2b94a3cd-2aa2-4d53-9e88-77c67a2c80bb)
![magic-wand](https://github.com/unlock-protocol/unlock/assets/214760/a99c9f86-4453-46ec-a266-16bdcc0a8b00)
![recurring](https://github.com/unlock-protocol/unlock/assets/214760/f7a24ce5-a433-427d-8c73-0fc2c62bd91b)
![subscriptions-hero](https://github.com/unlock-protocol/unlock/assets/214760/d65730d6-ea92-4b7d-ab07-f92b8ee9f37f)
![dirt](https://github.com/unlock-protocol/unlock/assets/214760/f690772f-59b8-4d50-ba73-d361350e1df1)
![litaf](https://github.com/unlock-protocol/unlock/assets/214760/cc917841-6a0f-4357-9b6d-641801ed568a)
![stella](https://github.com/unlock-protocol/unlock/assets/214760/8eb3dc27-dddf-404e-a24a-d68270a96e8a)
![subscriptions-logo](https://github.com/unlock-protocol/unlock/assets/214760/db3ba56a-8ff7-4ac7-b24e-49c3c0aef6d7)
![subscriptions-logo](https://github.com/unlock-protocol/unlock/assets/214760/c91d9078-6895-4002-a06c-6e6e98918141)

Prototype
![subscription-landing-v1](https://github.com/unlock-protocol/unlock/assets/214760/f44ab64e-c65d-42a7-993e-cd509a2bed06)

**Comment by julien51** [comment]
@ccarfi can you provide a good description for SEO purposes (description)
