### ISSUE TITLE
Make sure that storeTransaction for StorageService is idempotent

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1426]
Based on our current architecture it is possible that the same transaction may be sent to storage multiple times.
Locksmith should handle that gracefuly and just ignore subsequent `storeTransaction` when it already has a transaction for the same hash.

**Comment by akeem** [comment]
@julien51 this should already return a 400, are you experiencing different behavior here?

**Comment by akeem** [comment]
Closing as this was addressed with the release of #1544
