### ISSUE TITLE
NFT Transfers not working

### ISSUE THREAD

**Issue by SVell** [unlock-protocol/unlock#14325]
So, we have an issue with Key transfers by email code.

How to reproduce:
Select a lock and airdrop a key to an email. Then open the transfer link from the email and try to get the transfer code. Locksmith will error out.

Not, there are several different errors depending on the lock network and environment.
- For the main app on Base, you will get an error from route /transfer `signer.signTypedData is not a function`. This is I guess cause unlock-js uses ethers:5.7.2 as a peer dependency while using 6.13.0 as dev
- If you try to do the same with the same lock but running everything locally, you get `No signer is set as locksmith on the Key Manager contract`. Cannot yet explain why this is happening here.
- Same goes for Sepolia on localhost and staging
- Staging on Base works and email with code is sent 
- On the Optimism, it seems like no emails are even sent

**Comment by julien51** [comment]
Please focus on the first bullet point. 

A key airdropped from staging can only be transferred from staging. A key airdropped from prod been only be transferred from prod.
