### ISSUE TITLE
Lock sort is wrong when creating a new lock

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1437]
When a new lock is created, the dashboard displays it at the bottom of the list, instead of the top of the list...

**Comment by cnasc** [comment]
Well, this is interesting. No `blockNumber` on transactions...

<img width="631" alt="image" src="https://user-images.githubusercontent.com/9300702/52368370-3baaa200-2a1c-11e9-95ae-433cf3e72695.png">
 
...until you refresh the page.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/9300702/52368516-9d6b0c00-2a1c-11e9-966d-58410001d0da.png">

**Comment by cnasc** [comment]
@julien51 I believe this is fixed as of #1456. Can you confirm?

**Comment by julien51** [comment]
I think this is fixed indeed. closing.
