### ISSUE TITLE
Write Scenarios as part of smart-contract acceptance suite

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#1438]
**Is your feature request related to a problem? Please describe.**
This is a sub-task (1/3) of #1176. It has the single goal of clearly defining what scenarios we want to test in the new suite. This suite will be testing the deployed Unlock contract on mainnet in a black-box manner, making no assumptions about how it was deployed, with or without a proxy, etc...

**Describe the solution you'd like**
Open to other ideas, but a google doc should suffice for this. (It could also be done as a simple list within this issue.)

**Additional context**
#969

**Comment by hardlydifficult** [comment]
How about...
We maintain two proxies per network (well 2 for rinkeby and 2 for mainnet).  Let's call it UnlockProxy and TestUnlockProxy.  The process could be:
 - v0 is already out...
 - Deploy TestUnlockProxy, have it point to the very same contract the current UnlockProxy points to
 - v1 is ready for testing:
   - Deploy v1
   - Upgrade TestUnlockProxy
   - Test
   - Upgrade UnlockProxy (using the same contract address as TestUnlockProxy)

For the `Test` step, I think we can follow the script currently in the upgrades.js test (although maybe we migrate this script to a wiki).  So basically we 
 - deploy 1 or more locks
 - buy 1 or more keys
 - then after upgrade
    - confirm that the keys still work (is valid and can be transferred)
    - new keys may be purchased on the old lock
    - deploy a new Lock, buy a new key and test
    - confirm the data in Unlock considers data both before and after the upgrade

If a test using TestUnlockProxy fails in a way which corrupts data, UnlockProxy is not impacted in any way.  In this scenario, we redeploy a new TestUnlockProxy and start with v0 again, populate data, upgrade, etc..

**Comment by nfurfaro** [comment]
Here are my thoughts:

>maintain two proxies per network(rinkeby & mainnet)

I like it. The process you've outlined seems reasonable and has some nice safety-nets built in.

>I think we can follow the script currently in the upgrades.js test (although maybe we migrate this script to a wiki)

I think the wiki makes sense as a reference, but we would want to keep `upgrades.js` as part of our contract test suite as well right? Or were you thinking that testing upgrades would _only_ need to be done as part of this new smart-contract acceptance suite?

**Comment by hardlydifficult** [comment]
> we would want to keep `upgrades.js` as part of our contract test suite as well right

Yes agree.  Keep the test and write a manual script which does similar steps.

**Comment by nfurfaro** [comment]
To add to the `Test` step:
I think the original plan here was to test the "live" deployed Unlock contract to make sure it functions as expected (not just that upgrades work correctly).
So, we could follow the plan you've outlined above as a test of the live upgrade process, but could add a suite of tests of the basic (to start with) functionality of Unlock. These tests would be Black-box (ie: they have no idea how Unlock was deployed, only that they expect to find an Unlock contract at a specific address on rinkeby and mainnet) 

I realize that the plan to create this independent test suite was formulated based on the thinking that we would _NOT_ be running the existing test suite against the live deployed contract, so maybe this needs to be revisited to see if we still want to proceed with this issue (beyond testing the upgrade process as outlined above).

**Comment by nfurfaro** [comment]
So just to recap this issue:

1.) The truffle recommendation to run tests once against contracts deployed on testnet and/or mainnet was the original motivation for #1176.
2.) Discussion in #969 led to the decision to _NOT_ run existing tests against deployed contracts, but to create an independent acceptance test suit which would be run against the Live Unlock contract, and would have no idea how Unlock was deployed.
3.) In this current issue, @hardlydifficult outlined an approach we might take for safely testing the upgrade process. 
4.)In a slack discussion here: https://unlock-protocol.slack.com/archives/CF57E9HCG/p1552079029023600 we revisited the idea of running the existing tests against the Live, deployed Unlock contract, but using an additional "testing' proxy which points at the same Unlock contract.

#### Goals
- Better Test Coverage
- Test the "Live" upgrade process (beyond just the basic tests we already have for upgrades)
- Acceptance-tests for the Live Unlock contract (or possible run existing tests against the Rinkeby-deployed Unlock contract)
- try not to overly complicate the process;)

**Comment by nfurfaro** [comment]
My thoughts on the above:

- I'm open to revisiting the idea of running tests once on rinkeby _if_ it could achieve what the acceptance test suite was intended to do.
- I think the plan detailed above to test upgrades is sound and something we should pursue. I wonder if that portion should be broken out into its own issue.
- I have concerns around creating too many proxies...(still gathering my thoughts on this, it may not actually be an issue)
Let's say we ended up with 3 on Rinkeby. 
  - 1 for general testing, 
  - one for testing upgrades(where we're not concerned with corrupting data storage) 
  - the Live proxy which the apps use.
All of these will live in `zos.rinkeby.json` under `proxies/unlock-protocol/Unlock` and will be differentiated only by their position in the array and their address. Add to this the proxies created by `upgrades.js` and `UnlockProxy.js` and it starts to add up.

**Comment by julien51** [comment]
Ok, I like the idea @hardlydifficult. However as @nfurfaro noted I want to clarify the goal (and maybe the 2 proxies give us this clarity.

The main goal: testing that the currently deployed contracts work "as we expect them to". We do have a test suite running locally against ganache but arguably a real node on an actual network (testnet and/or mainnet) is not strictly the same thing. I think we should ensure that our existing test suite actually works great again the real nodes too.

[As a side note I think our current test suite does not run well with Ganache when there is a block time `-- -b3` rather than when it is mining _on-demand_. We should look into that too...]

Now, in the context of upgrades, I think it will be important to see if we can ensure backwards compatibility. This can only be done by running the test suite for each previous versions against the new versions. This way we know that if an app was built against v0 it still works against v1 once the contract has been upgraded.

**Comment by julien51** [comment]
Based on the discussion above we have opened 2 new issues:
* https://github.com/unlock-protocol/unlock/issues/2467
* https://github.com/unlock-protocol/unlock/issues/2466

For the rest we will also write https://github.com/unlock-protocol/unlock/issues/1176

Closing in favor of the sub-issues.
