### ISSUE TITLE
Expand EVM support for $EDU Chain, a forthcoming L3 Rollup Chain on the Arbitrum Orbit Stack 

### ISSUE THREAD

**Issue by YonksTEAM** [unlock-protocol/unlock#14416]
NOTE:  EDU chain is still in "Pre-Launch".  This feature request is to spark interest within the Unlock-Protocol community and to hopefully add EDU chain support to Unlock's Roadmap for future inclusion.

# Why $EDU Chain / Open Campus Protocol

## _Empowering educators, content creators, and students to transform learning._

![Open-Campus_banner](https://github.com/user-attachments/assets/6894df4a-7902-445c-a1a9-e2e541afcc69)

* image source: [Education Meets the Blockchain: Introducing the Open Campus Protocol](https://opencampus-xyz.medium.com/education-meets-the-blockchain-introducing-the-open-campus-protocol-c519995e9c7b) (opencampus-xyz.medium.com | 11Apr2023)

## _Over 100,000 Open Campus IDs have been claimed since launch in January, marking a significant step in adoption of its Web3 education protocol_

![Open-Campus-ID](https://github.com/user-attachments/assets/bc7fcbee-c6ef-45de-b3cf-87290d41a3bc)

* image source: [Open Campus ushers in new era of learning by empowering lifelong learners with control over their educational identity and data](https://opencampus-xyz.medium.com/open-campus-ushers-in-new-era-of-learning-by-empowering-lifelong-learners-with-control-over-their-f843cbb7c9d5) (opencampus-xyz.medium.com | 18Mar2024)

## _EDU Chain will be an L3 Rollup built on the Arbitrum Orbit Stack_

![Arbitrum_Open-Campus](https://github.com/user-attachments/assets/c4a20d21-05f7-4798-ba3b-d80abf6d135d)

* image source: [Open Campus receives grant from Arbitrum Foundation to launch EDU Chain, the first blockchain for education](https://opencampus-xyz.medium.com/open-campus-receives-grant-from-arbitrum-foundation-to-launch-edu-chain-the-first-blockchain-for-86a912cbca4f) (opencampus-xyz.medium.com | 03Jul2024)

# Why I want to see Unlock Protocol add support for $EDU Chain

- We are Pre-Launching EDUchain.Club via [EDU Chain Hackathon: Semester 1](https://dorahacks.io/hackathon/educhain/detail).  This platform will be a "Best Practices" educational and resource hub for hyper-local clubs to form and organize with minimal efforts.
- Garnering support from college aged students is a proven formula for adopting lifelong users of products & services.
- We will be building OnchainBootcamp.com, a hybrid events format, using Unlock-Protocol.  We would like to use EDU Chain for events surrounding academia.

# Additional Articles to learn more about $EDU / Open Campus

* [Decentralized Education Platform Empowers Learners With Data Ownership, Unlocking Innovative Educational Experiences](https://www.entrepreneur.com/en-au/technology/blockchain-project-empowers-learners-with-data-ownership/468014) (entrepreneur.com | 08Jan2024)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(including this article to show that Open Campus continues to release worthwhile improvements to their protocol like launching their own DID solution.)*
* [Understanding Open Campus: A Comprehensive Overview](https://messari.io/report/understanding-open-campus-a-comprehensive-overview) (messari.io | 30Nov2023)

**Comment by julien51** [comment]
You are encouraged (and welcomed) to deploy Unlock on that chain! We have a tutorial on how to achieve this. Please refer to this issue: https://github.com/unlock-protocol/unlock/issues/9304
