### ISSUE TITLE
Add metadata to dashboard creator form

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1443]

**Comment by cnasc** [comment]
Using [this Figma](https://www.figma.com/file/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-Dashboard?node-id=0%3A1457) as the basis for now. Here's a question: where do these options get stored? On- or off-chain?

**Comment by cellog** [comment]
They will be put into the snippet, and so will not be stored at all :) (unless you count the snippet as a kind of static storage). For now, don't worry about hooking up the UI to anything until we decide whether to use a new meta tag or attributes on the existing one or whatnot

**Comment by cnasc** [comment]
The case I was considering was something like: if I have a lock and I've embedded the snippet on a page, and sometime later I want to use the same lock on a new page with the same leakiness/trust settings it would be convenient if the form retained the settings I last used. Not critical, but definitely a nice-to-have UX thing.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/9300702/52963690-77bffa00-336e-11e9-9383-9e6e3c454283.png">
Here's some progress on putting those elements into the form.

**Comment by cellog** [comment]
Might I suggest you borrow the `useLocalStorage` hook from the paywall and use that?

**Comment by cnasc** [comment]
Not a bad idea! We might have to establish a convention for handling things that will exist in both the paywall and the dashboard to avoid duplication...

**Comment by cellog** [comment]
Copy paste and add a 1 line TODO to extract a shared library when it seems necessary. I wouldn't worry about duplication yet, the split is pretty new and we have 100% duplication of the display components and redux stuff atm

**Comment by julien51** [comment]
Closing as not applicable anymore.
