### ISSUE TITLE
Create transaction log page UI

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1444]
Requirements for this feature mostly live in the [Figma](https://www.figma.com/file/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-Dashboard?node-id=0%3A67)

Per discussion with @smombartz, the plan right now is to show only the first 3 columns until a good design for showing disparate kinds of data in the table can be devised. So this issue is really a v1 of the transaction log, and it will be enhanced over time.

I anticipate the following steps:

- [x] create `transactionLog` page
- [x] format the page into columns
  - [ ] make that formatting mobile-friendly
- [x] determine how transaction data will be fetched (it seems that right now only lock creation is always available from the Redux state, so we have to figure out key purchase, price update, and withdrawal)
- [ ] set up navigation
- [ ] date time of each transaction rather than blockNumber (and probably "pending" for ones that have yet to be mined)

**Comment by cnasc** [comment]
I'm going to get started on this based on the Figma here: https://www.figma.com/file/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-Dashboard?node-id=0%3A67

**Comment by cnasc** [comment]
Just wanted to show some progress on this. I have a `transactionLog` page, and it does keep track of transactions for the most part. It looks like some transactions are ephemeral; for example, key price updates don't stay after a refresh (the lock shows the correct price, but the update doesn't go into a transaction anymore). So we'll need to figure out how we're going to handle the data.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/9300702/52645866-a42bd000-2eaf-11e9-9c3e-caf4b2aaa48d.png">

**Comment by cnasc** [comment]
Some additional thoughts on this:
- I can use `getPastLockTransactions` from `web3Service` to get most or all of the data we need.
- It pulls a lot of stuff, which means we'll probably want to cache it
  - That means that in [`_getPastTransactionsForContract`](https://github.com/unlock-protocol/unlock/blob/master/unlock-app/src/services/web3Service.js#L197) we should probably allow a `blockNumber` parameter.
  - Then we can just pull updates since the last time we checked instead of pulling the whole thing down each time.
- We also probably don't want to get all of it right away
  - Therefore, I propose that we get transactions per lock. So maybe an individual transaction log page per lock linked from the lock card on the dashboard?
  - Using lock address as a query parameter/hash value

**Comment by cellog** [comment]
That's sounds good, I think also getting all past transactions per user would be good but perhaps impractical?

**Comment by cellog** [comment]
I mean all transactions of the current logged in user

**Comment by cnasc** [comment]
Good point, I think we can look at this as an example:
https://github.com/unlock-protocol/unlock/blob/a12d77448763b4a0c249488f8529472b5061606e/unlock-app/src/services/web3Service.js#L209-L222

I _think_ it should be sufficient to do that, but get all events instead of just `NewLock`. I'll have to play around with it.

**Comment by cnasc** [comment]
Just to keep tracking my thoughts in the open here:

| Contract | Event |
----------|--------
| Unlock | Lock creation |
| PublicLock | Key purchase |
| PublicLock | Withdrawal |
| PublicLock | Key price update |

All the data is available, and it should just be a matter of making a call to get `allevents` for each of the two contracts. Then, data in hand, they can be interleaved. Allowing us to query for deltas instead of just grabbing everything is a valid enhancement, but in the interest of shipping I think this first version will just always do that call.

**Comment by cellog** [comment]
nice table! this sounds good to me
