### ISSUE TITLE
decide how to manage UI state

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1446]
Options:

- redux
- local state and lift to common parents
- mobx
-other?

**Comment by cellog** [comment]
Based on extensive reading, I would like to use native React state management tools as much as possible. This means using hooks to manage side effects, and also local state. We can use context for passing down things like the web3 connection, and use those directly in a `useWallet` hook (or something along those lines). This will allow us to split up the gigantuan services, we won't need middleware, and it will be much smaller both in code size and in code execution. We won't need redux for something as simple as the paywall. We can either pass props or use context directly.

**Comment by cnasc** [comment]
I agree with that 100%

**Comment by cnasc** [comment]
Gonna close this since we've made a decision and this will clean up the issue log
