### ISSUE TITLE
Choose a system for managing CSS

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1447]
Options

- styled components
- CSS modules
- raw CSS *shudder*

**Comment by cellog** [comment]
“How is Linaria different from Emotion and Styled Components” by Satyajit Sahoo https://link.medium.com/PhItZ01wbU

**Comment by cellog** [comment]
Some more considerations:

1. Since the paywall is a client-side app, any caching we can take advantage of is good for return visits by users to any paywall that uses unlock. Thus, a tool that generates a static CSS file will allow us to cache that CSS browser-side
2. styled-components generate all CSS at run-time every time. For a server-rendered framework like next, this works fine, but adds a delay to every render where the CSS is generated on the server-side.
3. The primary benefit of styled-components is the ability to generate CSS on-the-fly from react props. It turns out, there is a SUPER clever way to handle props using CSS variables that allows using static CSS, as we can change the variable value at runtime and the CSS will update.
4. PostCSS and CSS modules allow isolating CSS rules just as effectively as styled components, and generate static CSS files on build.
5. a disadvantage (advantage?) of CSS modules is that the CSS is defined outside the component files, in `.css` files.
6. CSS that is defined in external `.css` files can also be effectively linted.

For these reasons, I am in favor of using CSS Modules for the css in the paywall. I don't think linaria (which is a hybrid solution that uses the syntax of styled components, but generates static CSS) is the right solution yet, but it is a possibility as well. I am not in favor of continuing with styled components.

**Comment by cellog** [comment]
note that initially, I will enable styled-components to ease the split

**Comment by cnasc** [comment]
That all sounds reasonable to me. 

> It turns out, there is a SUPER clever way to handle props using CSS variables that allows using static CSS, as we can change the variable value at runtime and the CSS will update.

That's definitely interesting. Do you have a link?

**Comment by cellog** [comment]
I found it in the linaria docs, one of the .md files that describes how it works, sorry on my phone about to drive to Maine :)

**Comment by cnasc** [comment]
No worries, I'll check it out. Get there safe!

**Comment by julien51** [comment]
Can I suggest consistency > convention > configuration ;)

**Comment by cellog** [comment]
this is a larger discussion about the future of the app. let's stick with styled-components for now
