### ISSUE TITLE
Transfer ownership of UP Token to Unlock Base DAO

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14488]
Transfer ownership of UP Token AND ownership of ProxyAdmin to Unlock Base DAO.
Before we do it let's make sure that a proposal can happen to "change" UP... etc.

This was raised by @pi0neerpat based on https://tokensniffer.com/token/8453/0xac27fa800955849d6d17cc8952ba9dd6eaa66187

**Comment by pi0neerpat** [comment]
Was the role renounced?

**Comment by clemsos** [comment]
> Was the role renounced?

The owner is now the DAO on Base (technically, the time lock contract used by the Governor).
