### ISSUE TITLE
Pass issues

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14495]
The pass names should NOT say "[TEST ONLY]".

<img width="553" alt="Screenshot 2024-08-30 at 3 19 07 PM" src="https://github.com/user-attachments/assets/8c2d96bb-7e85-4271-a106-2b765e2d9121">

**Comment by 0xTxbi** [comment]
<img width="833" alt="Screenshot 2024-09-25 at 14 54 13" src="https://github.com/user-attachments/assets/fdf1392b-92bc-4957-8092-95cd32f0e44a">

now fixed!
