### ISSUE TITLE
Set Unlock contracts to distribute UP

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14491]
The Unlock contracts are still distributing UDT instead of UP. We need to change this. For each network (except for BAse) we will need to bridge UP. 
For each proposal, we need to both set the reward tken to be UP AND also add UP's Oracle.

**Comment by clemsos** [comment]
Starting with Base

**Comment by julien51** [comment]
Submitted! https://www.tally.xyz/gov/unlock-protocol/proposal/71525868617611735117075003965381623116383749113359209663419238815930355157896
