### ISSUE TITLE
Enable a migration path for Lock owners

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#1450]
**Is your feature request related to a problem? Please describe.**
This is a sub-task (1/3) of "Lock Deletion" #1348
If Lock owners want to upgrade and benefit from new features in a new version of the Lock contract, there needs to be a mechanism to "migrate" existing valid keys to the new lock.
 
**Describe the solution you'd like**
Either implement a `grantKeys` function as per https://github.com/unlock-protocol/unlock/issues/1348#issuecomment-459974142, 
or build the ability for future Locks to acknowledge keys from a prior version, as per https://github.com/unlock-protocol/unlock/issues/1348#issuecomment-459997864

**Additional context**
- #1348 
> "We need to keep in mind the cancelAndRefund feature here as well. If the Lock owner simply re-creates Keys on the new Lock without first invalidating them on the old lock (or first deprecating the old lock which could also block cancel attempts) then a user could try to cancel both the new and the old and potentially profit."

**Comment by nfurfaro** [comment]
@hardlydifficult regarding your idea from #1348,
> An alternative is instead of manually transferring keys, we could build the ability for future Locks to acknowledge keys from a prior version

Did you have an idea in mind for how this might work? I'd just like to consider how this alternative might be implemented before proceeding one way or the other. 
Am I correct in thinking this would only work if we "manually" disabled the old lock's payable functions, but don't kill it?

**Comment by hardlydifficult** [comment]
I was thinking we could have the Lock owner specify the address of a previous Lock for the same content.  Then when a user calls `getHasValidKey` or similar, the contract checks it's own storage and if no Key is found it then forwards the call to the previous Lock.

Yes, a best practice would probably include turning isAlive to false to stop purchases on the old Lock version - however it shouldn't be critical.

**Comment by nfurfaro** [comment]
Ok, thx for weighing in. It seems that this approach is not compatible with `selfdestruct`ing the old contracts to minimize bloat on the blockchain. As that's one of the stated goals here, I'll have to go with the "migration" of keys option.

**Comment by nfurfaro** [comment]
In thinking about migration I've thought of an issue we need to resolve. 
Let's say a lock owner wants to migrate 10 existing keys (tokenID's 1-10) to her new lock. They should not have their tokenID's changed (as per erc721 spec) so they would remain as numbers 1-10 on the new lock. however, if a brand new user tries to purchase a key _before the migration is completed, he may buy `tokenID` # 1, so we now have two tokenID's which are identical. This may just be a matter of scheduling...where the lock owner doesn't reference the new lock address at all until the migration is succesfelly completed.
The other option is to have the new lock in a paused state (`isAlive` == false) by default until `activateLock` is called...but this is added friction for lock owners on every single lock created.

**Comment by nfurfaro** [comment]
Here's a breakdown of what I think needs to happen in order to enable a migration path for lock owners so they can take advantage of new features added to the lock contract.
- walk the `owners` array on old lock and retrieve all owner addresses. 
 - use `keyByOwner` to check each existing key's `expirationTimestamp to see if it is valid. If valid (not expired), get the key details ((`tokenId`, `expirationTimestamp`, `data`)
- set `numberOfKeysSold` to match old lock (needed to avoid duplicating `tokenID`'s)
- copy `owners` array over to new lock.
- set `keyByOwner` on the new lock for each owner.
- set `ownerByTokenId` on the new lock for each tokenID.
- finally, allow new key purchases on new lock after the migration is completed (see comment above for reasoning).

I would think that we want to add the minimum required functionality to the contract to enable this, and deal with the rest on the frontend (perhaps from a new lock migration/management page.).
I don't want to add any unneeded complexity, but I think this is what needs to happen for migration to work. cc @hardlydifficult @julien51

**Comment by hardlydifficult** [comment]
I think we can simplify.  For example, does it matter that the tokenId may change or be duplicated?  The Lock address is changing so the tokenId losses meaning as well.  From a ERC721 perspective, this is a brand new token we are creating on the new Lock.

**Comment by nfurfaro** [comment]
I would really like to simplify this. as to your points:
I don't think it matters so much that the tokenID changes, as it is technically a new token contract and therefore a brand new token. 
I think it's very important that we never have duplicate tokenID's though. As per the erc721 spec:
>"Every NFT is identified by a unique uint256 ID inside the ERC-721 smart contract. This identifying number SHALL NOT change for the life of the contract. The pair (contract address, uint256 tokenId) will then be a globally unique and fully-qualified identifier for a specific asset on an Ethereum chain."
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md#rationale

I think we're ok with changing the tokenID as it's a new contract here, but I don't think we can have duplicates. It seems the simplest way to ensure this is to resume our tokenID sequence where we left off in the prior contract. I may be missing another option here.

**Comment by hardlydifficult** [comment]
The pair (address+tokenId) must be globally unique, so it should not be a problem to use the same tokenId in the new contract that appeared in an old one.

**Comment by nfurfaro** [comment]
Agreed. I should clarify: My concern is that if we "migrate" old tokens to a new contract and _keep_ their existing tokenID's, then we need to ensure we don't assign any of those ID's to another token. 
If we disregard the existing ID's and just start our sequence fresh from number 1 on the new contract we can disregard this issue.

**Comment by hardlydifficult** [comment]
Oh I misunderstood.  Yes, however I think we keep it simple and have a method to `grantKey` which takes an address, expirationDate, and data and simulates a purchase without any cost.  Then we can look to add a `grantKeys` which accepts arrays of the same.  These methods could be used for other use-cases as well (e.g. a giveaway).

I think this would be easier to implement and maintain.  However we lose the complete owners list (you could workaround by referring to the old Lock as well) and the total keys sold (but all the info is there to calculate it by referencing the old Lock).

**Comment by nfurfaro** [comment]
Ok thank you for looking at this. I'll take your advice here and implement the singular version of `grantKey` first.

**Comment by julien51** [comment]
Hey. I understand the lesson is an important feature, but not sure we need to dive too deep in that right now?

**Comment by nfurfaro** [comment]
@julien51 Implementing "Lock deletion" without enabling migration is certainly a simpler task...It may just be that I misinterpreted the urgency of this portion of the larger issue (#1348). My thinking was that if we allow the disabling of a lock, we must _already_ have a mechanism in place to deal with any remaining keys. If you're ok with adding the migration piece later then I can jump straight into lock disabling/deletion.

**Comment by cellog** [comment]
From a security perspective I would be wary of any functionality that allows gifting a key without requiring payment. We want to make sure that cannot be abused

**Comment by hardlydifficult** [comment]
I believe we would like to move forward with this, correct?

User stories: as a Lock owner, I would like to:
 - Migrate all my existing Key owners to a new Lock, allowing me to take advantage of some new feature.
 - Gift a Key, possible for a gift/contest or other PR goal.

Goals: add the ability for a Lock owner to `grantKey` or `grantKeys` (an array).
Non-goals: preserve the original tokenId, prevent tokenId conflicts with the original Lock, migrate expired key data. 
This enables both user stories.

Open question: should we prevent Key owners who acquired a key this way from calling `cancelAndRefund`? -- this would allow a gift recipient to get money back.

Risk: at the moment, the original Lock allows `cancelAndRefund` even when it has been deprecated.  In the Lock migration story, a Key owner could attempt to call `cancelAndRefund` on the old Lock after `grantKey` was called on the new Lock but before `selfdestruct` was called on the old.  (i.e. get a partial refund and keep a Key).  We could either disable `cancelAndRefund` on deprecated Locks or the Lock owner can deal with this today by changing the refund penalty to max (preventing giving any money back).

Alternatives: the Lock migration story could also be enabled via:
 - Javascript, where content is unlocked if the user has a Key from the new or the old Lock.  
 - or in the contract by allowing a new Lock to fallback to the old Lock contract address when a Key is not found.
Personally I think one of these alternatives could be a nice-to-have addition, but either way the `grantKey` ability is worth adding.

Thoughts?
