### ISSUE TITLE
Protect users from losing money on invalid Locks

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#1452]
**Is your feature request related to a problem? Please describe.**
This is a sub-task (2/3) of "Lock Deletion" #1348
When a Lock is destroyed (selfdestructed), and then someone attempts to purchase a key, the ETH will be burned and the user gets nothing.

**Describe the solution you'd like**
I think the 2-step solution for issue #1468 could be useful here too. Basically using a bool `isAlive` as a requirement for all payable functions. If a lock is going to be deprecated, `isAlive` is set to `false` rendering all payable functions unusable. The one issue here is that after `selfdestruct` is called, if a user tries to buy a key, the `purchaseFor` function no longer exists and so the fallback is called instead, allowing the ether to be transferred to the contract with no way to retrieve it (effectively burning it).

**Additional context**
#1348

**Comment by hardlydifficult** [comment]
@nfurfaro this is done and can be close, right?

**Comment by nfurfaro** [comment]
Yes, this is done. Closing.
