### ISSUE TITLE
Eslint cleanup

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14564]
Now that we have upgraded to eslint, I noticed we are using different rules in many of our packages, as well as only applying eslint to _some_ files and not all the files in some packages.

For example, we use `yarn run eslint src/` instead of `yarn run eslint .` which would cover _all_ the files. We should make that in all the packages/applications.

Many packages do also include their own rules and we should avoid that.

This 200 USDC bounty is open for anyone who "normalizes" our use of eslint to the max!

**Comment by julien51** [comment]
Thanks a lot @Myestery !
Please post a wallet address for a USDC payment on Base or Optimism!

**Comment by julien51** [comment]
@Myestery Actually there is an issue! I am trying to run `yarn run lint` in the `unlock-app` folder and it just hangs!
I will have to revert your PR.

Please make sure linting runs/works in *every* single folder!

**Comment by julien51** [comment]
@Myestery can you please open anew PR with the changes?

**Comment by julien51** [comment]
@Myestery I can confirm we're still having issues with liunt that's hanging for some reason. I confirmed this with @0xTxbi for whom this is happening as well. I am not sure how to reproduce but please can you try on your end as well?

**Comment by julien51** [comment]
> I suspect its still using the old eslint version and not reading config from the config file thereby scanning node_modules as well.
> yarn install should fix this

I don't think that is what is happening.
I did a full cleanup of the repo locally (git clean -fdx) and then I did `yarn && yarn build`. At that point it looks like the lit command succeeds... but later when i do changes in the `unlock-app` app, eventually the lint command fails.

**Comment by julien51** [comment]
> I was finally able to replicate this issue after I ran yarn build, I had to add an ignore rule to the .next folder that nextjs adds. The fix is here https://github.com/unlock-protocol/unlock/pull/14633

Awesome! Please let me test things tomorrow and pay the bounty after that! Thank you so much !

**Comment by Myestery** [comment]
Hello, were you able to test it yet?

**Comment by julien51** [comment]
yes! I also just paid the bounty! https://basescan.org/tx/0xc235f2be4a1fcfed979ef7c88909927345a70c6cfbef64ce0af4dcf3909d96e0

Thanks for your hard work!

**Comment by Myestery** [comment]
Many thanks
looking foward to doing more
