### ISSUE TITLE
Show the same lock's view "features" to the event attendee page

### ISSUE THREAD

**Issue by valentinahl** [unlock-protocol/unlock#14579]
The current attendee list on the event landing page only shows the option to check in an attendee, while the same view of attendees on the lock view shows options to update email, resend QR code, and more. To avoid confusion, we should add all the same options to both lists.

**Comment by julien51** [comment]
Current view of the "attendee" example:
<img width="1548" alt="Screenshot 2024-09-10 at 9 31 14 AM" src="https://github.com/user-attachments/assets/3087bf25-4786-4597-8fb4-044247dafbc3">
Current view of the "lock" example:

<img width="1144" alt="Screenshot 2024-09-10 at 9 31 50 AM" src="https://github.com/user-attachments/assets/36045d78-9db5-465f-a3ce-939ea4943230">

We should move the "ticket" specific stuff from the "lock" view to the "attendee" view (Send QR code by email, Mark as checked in). We should also remove tokenId, transactionHash from the attendee view
