### ISSUE TITLE
events collection page feedback

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14660]
Here is a list of minor issues to fix on event collection pages:

* [x] Trash can icon is misaligned when trying add/remove collection managers. Also when a manager has been added, we should show it as `<Address>` not as `<AddressInput>` (that will solve the alignment issue)
* [x] Invalid links are not looking great :
<img width="702" alt="Screenshot 2024-09-24 at 1 35 33 PM" src="https://github.com/user-attachments/assets/20a37282-fc94-4790-99f3-3b761caf80a2">

* [x] Add "share" buttons, similar to what we do on event pages:
* [x] Remove the "gray placeholder" from list of events (we will add a calendar/map view later)
<img width="805" alt="Screenshot 2024-09-24 at 1 36 50 PM" src="https://github.com/user-attachments/assets/f81e7d32-5a8f-4323-ac3b-d018aa9ccd7c">

* [x] Send emails (you need to add a field to collect the email and add that to the "manager" object) when a new collection is created
* [x] The button to "select from existing events" should say "Select events I organized". (also please do not use CamelCase on buttons... just regular sentence case)
* [x] Refresh when adding new events needs to be fixed
* [x] Add a button to add to calendar in drawer
* [x] Send an email to organizers on submission 
* [x] Send an email to submitted when their event has been approved or denied in the collection

**Comment by 0xTxbi** [comment]
got it!

**Comment by julien51** [comment]
Now that we have Privy and we require user's email address we can query their API to get the user's email address from a wallet address https://docs.privy.io/guide/server/users/get-batch

**Comment by julien51** [comment]
We need to add 5 templates:
* event collections page deployed d(sent to all managers)
* event submitted to a collection (sent to all managers)
* event submitted to a collection (sent to submitter)
* event approved in collection (sent to submitter)
* event denied in collection (sent to submitted) 

Next, we check that wedlocks works
Finally, we trigger emails being sent from locksmith. For each relevant state change, we use the Privy API to get the email address linked to the manager or submitters' wallet. If none is set, skip the email.

**Comment by 0xTxbi** [comment]
got it!
