### ISSUE TITLE
Editable Image URL Inputs Not Working in Event Settings

### ISSUE THREAD

**Issue by 0xTxbi** [unlock-protocol/unlock#14678]
In Event Settings, the image URL input fields are not editable. This prevents users from updating event images using URLs.

**To Reproduce**

1. Go to the **Settings** page for an event.
2. Attempt to edit the image URL in the input field.
3. Notice that the input field is non-editable and cannot be changed.

**Expected behavior**
Users should be able to edit and update image URLs in Event Settings, allowing them to use URLs to set event images.

**Desktop (please complete the following information):**

- OS: macOS 15
- Browser: Chrome
- Version: 129

**Additional context**
This issue limits the flexibility for users who prefer to use image URLs for setting event images.

**Comment by julien51** [comment]
Great catch!
