### ISSUE TITLE
QA Dashboard Lock

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#1478]
A couple of QA items for the dashboard locks. let's chat about them briefly

- [x] add Key to header column labels for Duration Quantity, Price
![image](https://user-images.githubusercontent.com/1377389/52448352-a255bb80-2b01-11e9-9bd8-651dec3189bc.png)

- [x] Shorten Button Text (Withdraw, Edit, Embed)
![image](https://user-images.githubusercontent.com/1377389/52448348-9c5fda80-2b01-11e9-935b-6d9ee2fdb897.png)
- [x] Lock Form Field Fixes (lemniscate, spacing)
![image](https://user-images.githubusercontent.com/1377389/52448358-a71a6f80-2b01-11e9-9690-ebefa3e2967a.png)

- [x] Lock UX improvements (hover states and transition animation)
![image](https://user-images.githubusercontent.com/1377389/52448365-aa156000-2b01-11e9-8d9a-9dad299d10fd.png)

**Comment by julien51** [comment]
I just checked the lemniscate (which was the last on the list!) and it is fixed:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/17735/54454712-7fd24600-4730-11e9-83c2-9c9acae8e4cb.png">
