### ISSUE TITLE
Better Menu

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14819]
Our current menu on the "static" app is too limited and focuses exclusively on developers, at the expense of making it hard to find details about the products we offer, We need to refactor the menu to be the following:
- Developers
  - Docs
  - Libraries and tools
  - Code examples
  - Video tutorials
- Products By Unlock Lbs
  - Events
  - Certifications
  - Subscriptions
  - Unlock Prime (to come!)
- Governance
- Blog

**Comment by 0xTxbi** [comment]
got it!
