### ISSUE TITLE
OpenGraph missing?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#14905]
We need to use the content in `DEFAULT_SEO` to make sure OpenGraph gets populated for _every_ page in Unlock App with sensible defaults: 

* Title: `Unlock App`.
* Description: `Unlock is a protocol which enables creators to monetize their content with a few lines of code in a fully decentralized way.`
* Default Image: https://unlock-protocol.com/images/unlock.png

We should also make sure this includes the `twitter:` metadata.

Finally we should have a custom image for the Prime page with the following image : https://storage.googleapis.com/papyrus_images/f75b33885013fd16274fb54251ef6a2f.jpg

Let's make sure we're not breaking the existing tag that are using `NextSeo`.

**Comment by 0xTxbi** [comment]
got it!
