### ISSUE TITLE
Decide what urls paywall will run on

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1491]
This is a fourfold decision, as we need to decide how the paywall will run in these environments:

1. dev
2. test
3. staging
4. production

In dev, we can probably run the paywall on port 3001 so on `localhost:3001` and update the links accordingly using `configuration` in the dashboard (this is for the demo)

In test, we need to think about integration tests, and how that will look

In staging, we need to decide how it is deployed to netlify, and what subdomain to use (`staging.paywall.unlock-protocol.com`?)

for production, we need to decide both how it is deployed and what subdomain to use (`paywall.unlock-protocol.com`?)

**Comment by julien51** [comment]
We sure need a custom subdomain for the paywall in production... And I don't think using staging.paywall.unlock-production.com  is a problem?

**Comment by cellog** [comment]
#1649 is the follow-up for this
