### ISSUE TITLE
Lock Creation fails immediately with runtime error: revert

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1509]
**Describe the bug**
On master, creating a lock on the dashboard immediately fails with runtime error revert. No error message is displayed when this occurs, things just break.

**To Reproduce**
1. Go to Dashboard
2. Create a new lock
3. Note that lock never goes through confirmations
4. Note that attempting to create a second lock does not add anything to the list of locks
5. Note that failed lock disappears on refresh

**Expected behavior**
Lock creation should not fail, if it does it should be caught and an error should be displayed

**Additional context**
From the console:
```
  Transaction: 0x95cad37eebc53bd656c11228217338d95be7adba6e28f336463e227d3cb3b843
  Gas usage: 1939351
  Block Number: 310
  Block Time: Tue Feb 12 2019 09:06:20 GMT-0500 (Eastern Standard Time)
  Runtime Error: revert
```

Per Akeem in Slack:
> I think the hardcoded default gas amounts we have inside of the platform are no longer sufficient
> I am not clear on what has actually changed and why

Workaround for the time being:
> I adjusted https://github.com/unlock-protocol/unlock/blob/master/unlock-app/src/services/walletService.js#L255 to 5000000

**Comment by akeem** [comment]
@cnasc this should now be resolved in master, please let me know if it doesn't appear to be resolved

**Comment by cnasc** [comment]
Confirmed resolved!
