### ISSUE TITLE
Consider using Yarn for package management?

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1527]
# Why Yarn?
There may be some things that Yarn would make more convenient for us.

- Package caching
  - Yarn caches everything it downloads. In the event a reinstall is needed, this means it will happen noticeably faster than it does with NPM.
  - This also means that we can rebuild offline (Greg won't burn through his data allocation by downloading Chrome while on the train)

- Monorepo support
  - Yarn has better support for monorepos using [workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/)
  - This may simplify our dependency management, and can also help lighten our installation load by taking care of duplication between workspaces
    
- Determinism
  - We can be more confident that everyone has the exact same dependency tree with Yarn
    
- Ergonomics
  - Yarn commands are a bit "prettier" than NPM's (`yarn dev` instead of `npm run dev`, for example)
  - Yarn comes with some built-in extra stuff that can be replicated with NPM but would require additional dependencies and setup.
  - No need to worry about the difference between `npm install` (which takes `node_modules` as the source of truth, and updates the lockfile based on it) and `npm ci` (which takes the lockfile as the source of truth, and updates `node_modules` based on it)
    
- Plug 'n' Play
  - Allows efficient deduplication and can make our Node bootup times faster; Node won't have to probe the filesystem to find packages since Yarn will tell it exactly where they reside. See [pnp](https://yarnpkg.com/en/docs/pnp).
  - Requires additional setup beyond simply using Yarn, we have to be concerned about which resolvers are used when building the app.
    
- No more nuke script?
  - It seems like with Yarn the `nuke` script will be obsolete; everyone will have the same (ideally) known-working dependency tree. Nuking and reinstalling shouldn't be a concern anymore.
    
## Switching Cost
Yarn isn't as widespread as NPM. I don't know that any of the Unlock core team has much experience with Yarn. That means that everyone has to learn to use this new tool (admittedly, it seems like it's simple enough to learn, but it's worth considering). There could also be some impact on open source contributors (people may be less willing to send us a patch if they aren't familiar with Yarn). Moving to a third-party build tool is riskier than using the official built-in tool.

NPM has caught up with some of Yarn's early advantages, including lockfiles and speed. If Yarn was strictly superior on all fronts it would be an easier decision to make.

Different versions of Yarn have different lockfile formats. It's possible to declare which version your project supports, but the fact that people may have different versions (`brew` having a different version from `apt`, for example) may introduce some friction. I am not sure how likely a conflict is in practice.

Trying out Yarn seems relatively low-cost. Yarn and NPM can coexist in the same project; Yarn users will all have exactly the same dependency tree and NPM users may have varying ones. See [migrating from NPM](https://yarnpkg.com/lang/en/docs/migrating-from-npm/).

## Conclusion
Personally, I lean toward trying Yarn out and seeing if it works for us. The cost of trying it out is lower than the cost of making it our tool of choice, and there are some compelling features on offer.

Anyone else want to chime in with opinions?

**Comment by cellog** [comment]
if you have the space to do the heavy lifting on this, the only question would be which sprint and milestone to put this in. Let's wait for @julien51 to weigh in when he returns. We had another issue (#738) which fizzled, so it's nice to see this brought up again. I definitely prefer yarn, but only if we can enforce the version in package.json somehow to avoid those inconsistencies you spoke of.

**Comment by cnasc** [comment]
It looks like we can add a specific Yarn version to the `engines` property in [package.json](https://docs.npmjs.com/files/package.json#engines). This should warn if the wrong version of Yarn is used.

**Comment by julien51** [comment]
My initial willingness to explore yarn was about speed but it looks like `npm ci` is actually faster and solves the issue of having `npm install` install different versions for everyone. I believe `npm ci` solves the caching and determinism issues you highlighted above.

The monorepo stuff is very interesting and may be the final straw

As for the nuke script, I think we'll still need it at least for the artifacts stuff which really happens to be the main reason behind nuke.

So, it would be of course good to explore/benchmark at least and see what we gain!

**Comment by cnasc** [comment]
Yesterday I tried to get Yarn to work with our project. Unfortunately, it's not an easy transition and some packages we rely on aren't compatible. It's possible to get it moving with Yarn, but I don't know that it's worth the time.

**Comment by julien51** [comment]
Ok, thanks for the experiment! Closing for now. We can revisit in the future.

**Comment by julien51** [comment]
Hey @cnasc Do you by any chance remember the list of blockers? I think it would be good to keep track of them to see when it is a good time to revisit!
