### ISSUE TITLE
eth_accounts chattiness

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1542]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/9300702/52864927-58746300-3109-11e9-901f-692dd16b994e.png">

This `eth_accounts` call happens quite a lot. Maybe it can be backed off to only happen when strictly necessary (in the interests of being frugal with the network)? Or possibly suppressed/limited in logging. When we had the instant revert issue a few days ago, it took a while to find out what was happening because it was pushed past my scrollback limit by an infinite parade of `eth_accounts`.

**Comment by julien51** [comment]
I think we can safely get rid of this in dev/testing.

**Comment by julien51** [comment]
Actually not sure we can get rid of it because it is useful to test.I **wish** the web3 provider would tell us when it changed :/

**Comment by julien51** [comment]
I think @cellog worked no that recently?

**Comment by cnasc** [comment]
Yes, the `eth_accounts` call happens less frequently now, so maybe we can consider this solved. @akeem thoughts?

**Comment by cellog** [comment]
eth_accounts only happens every 2 seconds, plus we had it happening on both client and server, so there were 2 eth_accounts calls per second (4 if using the paywall). Now we have 1 every 2 seconds. I think we can improve this further by disabling it on dev, but that's a discussion to have

**Comment by julien51** [comment]
I think we're good for now! Just wanted to confirm!
