### ISSUE TITLE
Refactor CreatorLockForm and lock creation code

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1546]
Following on #1543, there are a few places where the creation of a lock with unlimited keys can be improved.

- [ ] refactor `CreatorLockForm`
  - The way the form behaves when clicking the unlimited button is confusing. It should be a clearly defined toggle, and not something that mutates the input field and then disappears.
  - Having an explicit toggle for unlimited keys should allow us to simplify the validation logic and also what we have to pass around to the backend
- [ ] More bullet points to come as I look into this and more clearly see what the implications of the form changes are

**Comment by julien51** [comment]
Status of that one @cnasc ?

**Comment by cnasc** [comment]
Haven't gotten to it yet! I think it may make most sense to do this as part of modifying the form for ERC20 locks?
