### ISSUE TITLE
Use the PromiEvent callbacks for new transactions?

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1558]
As described in the docs for `web3.eth.sendTransaction` (https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendtransaction) There are several events emitted which we could use for the transaction status that would eliminate transaction polling:

- "transactionHash" returns String: Is fired right after the transaction is sent and a transaction hash is available.
- "receipt" returns Object: Is fired when the transaction receipt is available.
- "confirmation" returns Number, Object: Is fired for every confirmation up to the 12th confirmation. Receives the confirmation number as the first and the receipt as the second argument. Fired from confirmation 0 on, which is the block where its minded.
- "error" returns Error: Is fired if an error occurs during sending. If a out of gas error, the second parameter is the receipt.

Is there any reason we can't use this @julien51?

**Comment by julien51** [comment]
`PromiEvent` should 🔥 !

Yes there is: if the user refreshes the page we lose all info. Most transactions are not triggered by the application in that session. So it is much easier to treat each transaction in the exact same way, whether it is triggered by us in that session or by another instance of the application (or even a different app!).

Once we have the hash, all of the other "events" are easily handled.

PS: We *were* using the promiEvent before and created a whole mess while
