### ISSUE TITLE
Add meaningful names to front end components

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#1579]
As part of the process of writing integration test for the front end, we noticed the need for identifiers to aid in the testing process. 

With the functional use case of being the basis for future accessibility work, we will be moving forward with this. 

This issue will be updated as the scope becomes a bit clearer.

**Comment by julien51** [comment]
Is that still a thing @akeem ?

**Comment by julien51** [comment]
I think this is an ongoing effort when writing integration tests so closing. Feel free to re-open if I am wrong!
