### ISSUE TITLE
set up paywall.unlock-protocol.com and staging.paywall.unlock-protocol.com

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1649]
The 2 urls `paywall.unlock-protocol.com` and `paywall.staging.unlock-protocol.com` (or `staging.paywall.unlock-protocol.com`?) need to be set up and enabled. On build, we should deploy master builds to the staging URL for the paywall/ directory.

In addition, special paywall URLs for the staging builds will need to be set up, and their address somehow injected into the environment so we can use it in the demo.

**Comment by julien51** [comment]
I can only set them up if there is something to assign them to ;)
What should I assign these subdomains domains to? Are we deploying the paywall app yet?

**Comment by cellog** [comment]
A while ago you asked me to open up issues defining what is needed in order to split off the paywall app. This is definitely going to be needed. Hooking up the unlock-app to these new URLs will be a next step, it won't be fully deployed until then, but having this set up will allow us to test it prior to the full deploy

**Comment by julien51** [comment]
done ;)
