### ISSUE TITLE
Create new configuration settings for paywall URL

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1650]
in config.js, on both unlock-app and the paywall, we should have a new config setting which defines the paywall URL for each environment.

In dev and test: `http://localhost:3001`
In staging: `https://staging.paywall.unlock-protocol.com` (or whatever the address @julien51 chooses to set up)
In production: `https://paywall.unlock-protocol.com`

For CI builds: whatever is passed into the environment for `PAYWALL_URL` and pulled out of next.config

**Comment by julien51** [comment]
That's a good one indeed!
