### ISSUE TITLE
decide how we should handle running the dev server after the paywall split

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1651]
There are 2 development workflows in which we may want to run the paywall:

1. we are working on the unlock-app
2. we are working on the paywall

For #1, we don't really care about running the paywall, and so it should not require much brain to run.
For #2, we want to be able to stop and start the paywall often and keep the unlock-app running.

Decisions need to be made on whether we want to automatically run the paywall in the unlock-app's `npm run dev`, or require users to start it in a separate window, much as they must start locksmith.

I personally think that supporting #1 may not often require actually using the demo, so perhaps it would be best to just update the docs on how to run the app?

This issue is a sounding board for ideas. Once it is finalized, it will be closed and a separate issue opened up with the solution everyone agreed upon.

**Comment by julien51** [comment]
I think this is actually an even bigger discussion because the same applies to locksmith.
I am starting to think we'll have to use docker locally to manage all services.

I am very intrigued by [tilt.dev](https://tilt.dev) and I was hoping to ask their team to help us set it up!

**Comment by akeem** [comment]
I'm presenting #1677 as a point of discussion and a potential immediate solution as it meets our immediate needs while being a relatively small change will little to no impact on developer workflow

**Comment by cellog** [comment]
Great! I think this is what I was hoping existed

**Comment by julien51** [comment]
Here is the issue about Tilt: https://github.com/unlock-protocol/unlock/issues/1853

**Comment by julien51** [comment]
So, for now, we're not using Title after @akeem's investigation.
For now I think it is probably ok to run services manually until we eventually find a great solution. Each app is honestly different and we probably not need to run all services all the time.

For example, once a lock has been deployed, there is no need to run the dashboard at all to run the paywall app. (and we could even write a small script to deploy a lock instantly without running the full dashboard).

Closing for now until we revisit!
