### ISSUE TITLE
connect to walletService provider just-in-time

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1653]
Currently, the walletService attempts to connect to the provider right away in order to retrieve the user account, and also the network the wallet is using. This results in some odd UX on two separate occasions.

1. When viewing unlock-protocol.com, metamask immediately asks to log in, even though there is absolutely nothing ethereum-related until one clicks on the dashboard
2. When viewing a locked paywall. Until the user clicks on the lock, we don't need the account. However, we *do* need the account if the user has purchased a key.

One consideration is whether it might make sense to always store the user's account in localStorage, but also always check to see if we can enable the wallet when the user takes action.

With this system, a user's unlocked content will display if they have ever visited the content with their wallet, regardless of whether they are logged in at that moment.

For the dashboard, the wallet would be requested immediately.

**Comment by cellog** [comment]
love to get your thoughts on this, @julien51 @benwerd @akeem @cnasc

**Comment by julien51** [comment]
> Currently, the walletService attempts to connect to the provider right away in order to retrieve the user account, and also the network the wallet is using. 

I actually think this is good practice because it means we can retrieve information right away and avoid latency... It also "fails" silently if the user does not have a wallet, and will only show an error message if the user tries to load the dashboard and/or click on a "purchase" button on the paywall.

> When viewing unlock-protocol.com, metamask immediately asks to log in, even though there is absolutely nothing ethereum-related until one clicks on the dashboard
Indeed. I have been thinking about this one. But I am honestly not sure this is a big problem? Again, if the user has no wallet, no error is shown and if they have one, they are asked to authorize the app, which they can still decline and use the website (until the dashboard).

> When viewing a locked paywall. Until the user clicks on the lock, we don't need the account. However, we _do_ need the account if the user has purchased a key.

Actually we do need the account when the user clicks on the lock because they do that to purchase the key?

**Comment by cellog** [comment]
> > When viewing a locked paywall. Until the user clicks on the lock, we don't need the account. However, we _do_ need the account if the user has purchased a key.
>
> Actually we do need the account when the user clicks on the lock because they do that to purchase the key?

Yes. We only need it to *purchase* a lock, not to display it. So it is required to purchase, but not to display the lock.

It's also currently required to retrieve keys, but as demonstrated in the coinbase wallet stuff, that is not necessary. We can store the account in localStorage and use it without authorizing on a new URL to retrieve keys.

However, it's worth noting that the popup to enable wallet for a site only happens once, so this may not be a big UI concern.

> I just did a test and we are showing the "Missing wallet error" even before showing the locks which is a bug I think.

I don't see this behavior locally (I always run with metamask logged out) can you open an issue with reproduce steps?

**Comment by julien51** [comment]
I think we're aligned: we do not "need" the user account until the user does a purchase. The right behavior is then to not complain to the user until they click on the purchase button.

The one exception is about retrieving keys on the paywall app where we *ideally* need to know the account before the user does anything. I think that indeed using the localStorage value is a good temporary fix (until we have a server side wallet!).
