### ISSUE TITLE
refactor web3Service's generic transaction handling so that it is in a separate service

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1654]
Each transaction type is slightly different. Currently, the web3Service transaction handling has all the edge cases for different transaction types inside several different slightly different functions.

A cleaner solution would be to create a `transactionService` that handles the details of retrieving transaction information from the chain based on the transaction hash. This would take the information returns from `web3.eth.getTransaction` and `getBlockNumber` and determine what the status of the transaction is, and also check its receipt. It would pass this information back up using callbacks. It would also determine transaction type if requested.

The web3Service would then have separate transaction "parsers" that would handle the next logical tier, so for example NewLockTransactionParser, TransferTransactionParser, PriceChangedTransactionParser, and KeyPurchaseTransactionParser. The job of these parsers would be to convert the raw transaction data and its status, and couple that with other information to generate metadata on the transaction. (lock on NewLockTransaction, key on TransferTransaction, etc.)

The last tier would be the middleware, which would coordinate polling for transactions that need it, and pass the transaction as well as any other logically created information to the redux reducers.

With this design, it will make it simpler to extract paywall-specific code, and remove paywall-irrelevant code.

**Comment by julien51** [comment]
Let's not do that until we actually talk about all this in person? I think there is still a misunderstanding about the goal of the Service here.

**Comment by julien51** [comment]
For now, let's just use the services as is for the paywall. I understand this means that there is some un-used code, but I think it's ok: that's the point of many libraries.
