### ISSUE TITLE
refactor walletService into 3 services, keyPurchaseWalletService, transactionService, and LockWalletService

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1655]
I would like to split the walletService into 3 services:

1. transactionService (mentioned in #1654), which would accept a read-write web3 instance passed down from either of the new WalletServices to send a transaction and listen for the promise and events that kickstart other processes in the read-only web3 instance, which will pass that to the transactionService (explained in detail in #1654)
2. keyPurchaseWalletService, which would be a higher-level wrapper around the transactionService to format and send a key purchase transaction. It would also take the raw output returned and present it logically to its invoker.
3. lockWalletService, which would be a higher-level wrapper around the transactionService to format and send withdrawal transactions, lock creation transactions, key price update transactions, and signing.

account handling would exist in a separate thing, as defined by #1653

**Comment by julien51** [comment]
Same as https://github.com/unlock-protocol/unlock/issues/1654
