### ISSUE TITLE
Track status.im wallet and general dev

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1678]
The ethereum work being done by https://status.im is very interesting. They currently have a wallet app in beta, it would be good if the paywall and dashboard all worked with it when it is released!

**Comment by cellog** [comment]
@julien51 can you set the labels? Mobile GitHub is minimal, can't do it on my phone

**Comment by julien51** [comment]
@cellog Any idea what this was about exactly? Do they have a browser we should test?

**Comment by cellog** [comment]
yes, they have a wallet app in beta, which will be good to support.
