### ISSUE TITLE
Allow Unlock owner to cancel a Lock

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1681]
**Is your feature request related to a problem? Please describe.**
Someday a scammer is going to create a Lock.  Maybe it unlocks nothing, or worse maybe they create Keys and try to sell them on a secondary market as if they were Keys to some other, valid Lock - it is easy for people to overlook addresses after all.

**Describe the solution you'd like**
Today the Unlock contract saves addresses of each of the Locks it created.  This data could be leveraged to expose a method such as `validateLock`.  The Unlock contract is also `ownable` today.  I propose we allow the owner to remove Locks from that list, and we could do so in response to a scam potentially.

**Describe alternatives you've considered**
We could also have the Lock itself disable and/or selfdestruct in this scenario but that may be too heavy handed, which is why I was thinking we simply remove it from the list of valid Locks created by Unlock instead.  This approach would allow the Lock to otherwise function as normal.

**Additional context**
We may not want this.  If we can police content in any way, maybe we will inherit an expectation to do so.  Or worse, maybe we inherit some liability as well.

**Comment by cellog** [comment]
It seems to me that we now have this liability no matter what, as doing nothing could be considered negligence. We need to address this prior to instituting the secondary market I think. Good call!

**Comment by hardlydifficult** [comment]
From the front-end perspective, we could surface a warning based on this flag before allowing a new purchase... but still allow the user to proceed if they wish.

**Comment by julien51** [comment]
>  If we can police content in any way, maybe we will inherit an expectation to do so. Or worse, maybe we inherit some liability as well.

I think this is key. We should also remember that as much as we are "owners" of the Unlock contract right now we will eventually have a governance mechanism which makes sure that this kind of decision is taken by not a single entity (us or anyone else) but by the community of users (lock owners, token owners...?)
