### ISSUE TITLE
One Lock, many content

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1682]
**Is your feature request related to a problem? Please describe.**
I'd like to charge per-article or per-category and today that means I need to create many Locks.  That's a fair amount of overhead... can we find a better way?

**Describe the solution you'd like**
Create one Lock and use the Key data field to identify the content of interest.  I suggest we do this with a new Lock type (an alternative to `PublicLock`). To support this use case we need to:

* Save data on transfer (it's cleared today)
* Ensure the user cannot change data post-purchase (on-par with what we have today)
* Allow a single user to own multiple Keys for a Lock (not allowed today)

Note that the Lock owner could offer a second Lock which offers a Key to all content with a single purchase.  The front-end then considers both before potentially unlocking content.

**Describe alternatives you've considered**
n/a

**Additional context**
This is a proposal from @cellog in slack.

A limitation of this approach is all content is priced the same.

We are working on a refactor of the PublicLock logic, which would make it easier to create.  We should be able to reuse most of the logic and data, while making a few modifications to support both use cases.

**Comment by cellog** [comment]
P.S. I'm not sure I'm in favor of this, it was casual dreaming, so I'm not willing to die on a hill for it ;). I like very much how you have fleshed this out and thought deeply about it, thanks for that Nick!

**Comment by julien51** [comment]
I think we eventually need to have an API to deploy locks in "batches" and make sure gas costs for deploying locks are consistently low (less than $1 is probably a good goal)...

But let's revisit this when this is actually a problem ;)
