### ISSUE TITLE
"we much decentralize the web"

### ISSUE THREAD

**Issue by fulldecent** [unlock-protocol/unlock#1684]
The main graphic in README.md includes a typo.

Typos are a red-flag for projects that want my money.

**Comment by julien51** [comment]
Thanks @fulldecent! @benwerd is on it ;)

**Comment by benwerd** [comment]
Confirming that I'm going to rerender the video this week. I'll update when I do. Thanks again for the heads up.

**Comment by benwerd** [comment]
Closing this. The UI has been in so much flux that an entirely new video is the way to go.
