### ISSUE TITLE
Make transaction log reachable from navigation

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1688]
The log page is in the app, but nothing points to it yet!

This feature should implement the new header icons found in this Figma: https://www.figma.com/file/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-Dashboard?node-id=0%3A67

I think there was some question about the icons, @smombartz I assume the 2 new icons map as follows:

- Home icon -> Dashboard
- List icon -> Log page

Is that correct?

**Comment by cnasc** [comment]
This is blocked until #1694 is fixed

**Comment by smombartz** [comment]
yes correct! unless @julien51 still opposes the home icon thats good to go from my side.

**Comment by cellog** [comment]
You can use https://nextjs.org/docs/#using-a-higher-order-component to access the route information you need without waiting for #1694

**Comment by cnasc** [comment]
Nice, looks like that's a lot easier than keeping Redux in sync with the router, which is dubiously necessary in the first place

**Comment by cnasc** [comment]
Another question: when do these new navigation buttons show up? I think we do not want them on the homepage, since they would allow someone to bypass the terms of service. Same for the non-app pages? In other words, they should only show up on the dashboard or the transaction log?

**Comment by cellog** [comment]
That depends, and perhaps @benwerd can chime in here, but my understanding is that we don't need people to agree to terms unless they are creating locks. Viewing info is free, legally and financially.

If that's true it opens up the possibility of linking from the homepage

**Comment by smombartz** [comment]
i would say only dashboard. thats once you enter into the app. the landing page should be informative.

**Comment by benwerd** [comment]
Sorry for chiming in late - we don't need people to agree to terms for landing pages, but all application pages need to be after terms have been agreed to. It's just not about the activity; it's about any usage, including reading.
