### ISSUE TITLE
Translate blockNumber to date/time

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1690]
For the transaction log (and perhaps other places in the app), we may want to show when a transaction occurred using a date rather than a block number. Ideally we'll do this in a somewhat efficient way, probably making use of localStorage so we don't make tons of repeated little requests every time we have a list of blockNumbers.

**Comment by julien51** [comment]
Given that we know the average block time and that the blocks are "Sequential" we can probably get good estimates by just getting a few block's actual mining time? (not sure the log needs the actual second-precise value?)

**Comment by cnasc** [comment]
It looks like average block time is somewhere around 20 seconds, I'd just be concerned about the possibility of drift over longer time intervals

**Comment by akeem** [comment]
closing as this code has shipped
