### ISSUE TITLE
Lock ABI NPM module not yet published

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1698]
**Describe the bug**
Our package `public-lock-abi-0` currently points to a generic security repo and not our code.

**To Reproduce**
1. Go to https://www.npmjs.com/package/public-lock-abi-0
2. Click on homepage

**Expected behavior**
Should point to our code, but instead points to a security message.

**Comment by hardlydifficult** [comment]
Once this is complete, we should migrate our test.  See https://github.com/unlock-protocol/unlock/pull/1790#issuecomment-468785311

**Comment by nfurfaro** [comment]
It looks like this is actually done?

**Comment by hardlydifficult** [comment]
I still see the security package.

**Comment by julien51** [comment]
Sorry I missed this one. Email npm support again :(

**Comment by julien51** [comment]
Fixed! I just published version `1.0.0`: https://www.npmjs.com/package/public-lock-abi-0
