### ISSUE TITLE
KEY_PURCHASE transactions should include the lock they're for

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1704]
**Is your feature request related to a problem? Please describe.**
Right now KEY_PURCHASE transactions don't indicate which lock they're for. This makes the transaction log page a little less useful.

**Describe the solution you'd like**
Include the target lock in the transaction in Redux.

**Comment by cnasc** [comment]
Actually, it looks like this information is included in the transaction, just not as immediately accessible. Will cook up a change to the transaction log to handle it.

**Comment by julien51** [comment]
Done, so closing ;)
