### ISSUE TITLE
Documentation and use cases.

### ISSUE THREAD

**Issue by ydennisy** [unlock-protocol/unlock#173]
Great project, just wondering if you have some early docs you can share and maybe a document showing some possible alternative use cases apart from a publishing paywall.

Thanks!

**Comment by julien51** [comment]
At this point, there is no doc, but this is obviously something we need to produce.

It's important to consider Unlock as an access control protocol more than a publishing paywall solution. For example, you could look at software licenses as another use case. You could also even consider tools where you want to only allow certain paying members to perform actions... etc.

**Comment by ydennisy** [comment]
Hey Julien, thanks for the reply.

So it is fair to say that the goal is to create a permissioned layer on a permisionless system (ethereum)?

**Comment by julien51** [comment]
Yes I believe Unlock can be used to allow someone to access a user's personal data as long as this data is "protected" by a lock.

**Comment by ydennisy** [comment]
When would some docs be ready, or some code to try this?

**Comment by julien51** [comment]
@benwerd What do we do with this issue?

**Comment by benwerd** [comment]
@ydennisy Hi! I'm closing this issue for now. We have an increasing amount of documentation [on the wiki](https://github.com/unlock-protocol/unlock/wiki), which we will continue to add to. The initial code is now also ready for download and deploy.

With respect to other uses cases, check out [the roadmap](https://github.com/unlock-protocol/unlock/wiki/Roadmap) - this lays out where we're going, and will evolve over time. Here you can see mailing list, one off, subscription, and patronage models.
