### ISSUE TITLE
pages should have as little React in them as possible to make them testable

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1740]
In doing a refactor of the paywall app, I found that `pages/paywall.js` contained a lot of React code. Pages are more difficult to test because they have a fair amount of next.js magic in them, such as `getInitialProps`. We should extract as many of these pages into components that accept props from the pages as possible. This will allow more comprehensive testing of our most critical top-level items, and make changing less likely to fail silently

**Comment by cnasc** [comment]
So we'd still have a `pages/paywall.js` as a wrapper for next to do its thing on, just the real work would be done in a separate React component? Makes sense to me!

**Comment by cellog** [comment]
so, for instance, this is the current paywall page in `paywall/pages`

```js
import React from 'react'
import Paywall from '../src/components/Paywall'
import BrowserOnly from '../src/components/helpers/BrowserOnly'

export default function NextPaywall() {
  return (
    <div>
      <BrowserOnly>
        <Paywall />
      </BrowserOnly>
    </div>
  )
}
```

I know it's hard to reason through, but we can probably manage ;)

**Comment by julien51** [comment]
I agree wholeheartedly!
