### ISSUE TITLE
Adding `view` only functions such as `name()` increase gas costs

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1757]
**Describe the bug**
Adding `external view` or `view` functions to the PublicLock contract seems to increase the gas costs for transactions such as `purchaseFor` and `transferFrom` by about 22 gas per view function.

**To Reproduce**
1. Call `purchaseFor` and record gas costs
2. Add a new `view` function such as
```
function getSomething() view {}
```
3. Call `purchaseFor` and record gas costs

**Expected behavior**
Gas should not be impacted by adding another read-only method.  

**Additional context**
I tried investigating for a bit already... no leads...

**Comment by julien51** [comment]
I'd be curious to hear the rational about that? Also, arguably (at least for us), these functions are more likely to be used not in transactions but when "reading" the contract (so no gas involved?)

**Comment by hardlydifficult** [comment]
Yea... I don't have a clue what's going on here.  I'm hoping that by walking away from this for a bit and returning maybe I'll discover I was making a silly mistake somewhere.

**Comment by hardlydifficult** [comment]
Confirmed the issue with this simple example:
```
contract Test {
    function testWrite() public {}
    
    function get() public pure returns (bytes memory) {
       return bytes('yo');
    }
}
```

Commenting out the `get()` function makes calling `testWrite` 22 gas cheaper.  Copy-paste a `get2()` and calling `testWrite` costs 44 more.  This trend seems to usual continue, each new view function adds 22 gas to the write function - however sometimes the gas change of adding one more reduces costs.  So for this simple example we see:
 - no get: 122
 - 1 get: 144
 - 2 gets: 166
 - 3 gets: 188
 - 4 gets: 210
 - 5 gets: 232
 - 6 gets: 210 ! (diverge from pattern)
 - 7 gets: 210
 - 8 gets: 232
 - 9 gets: 232

If you look at the assembly executed, there is significantly more going on when `get` is added.  WHY?!  I don't understand.

**Comment by hardlydifficult** [comment]
Posted this question for help https://ethereum.stackexchange.com/questions/68098/why-does-adding-a-view-function-make-write-functions-cost-more-gas

**Comment by hardlydifficult** [comment]
An answer! See https://ethereum.stackexchange.com/a/68148/51260
CC @julien51 

Begs the question, do we attempt to optimize for this?  I'll give this some thought.

**Comment by hardlydifficult** [comment]
Every function we add (even read-only functions) potentially makes other functions more expensive.  We could:

 - Limit the API where we can.  For example, I added 3 ways of grantingKeys, maybe we should only have 1.
 - Move non-critical APIs to a different contract. For example, `getTokenIdFor(account)`.  I'm not sure the best pattern here, but maybe the main contract has a fallback function which uses delegatecall to then try the non-critical contract instead.  The non-critical contract has a fallback function which reverts.

**Comment by hardlydifficult** [comment]
Closing this as I don't believe there is any more action.

Interesting lesson about Solidity though.  Check out the stack exchange answer and the github issue they link for even more discussion.

CC @nfurfaro @julien51
