### ISSUE TITLE
Review wallet expectations for contracts

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1764]
**Is your feature request related to a problem? Please describe.**
When viewing a Lock or a Key on a blockexplorer or in a wallet, what information might the wallet try reading from the contract in order to make that a good experience for users?

**Describe the solution you'd like**
We should review any plans regarding ERC721 in wallets such as Metamask, Fortmatic, Portis.  Do they look for standard metadata fields? as an example

**Describe alternatives you've considered**
n/a

**Additional context**
Etherscan recently added ERC721 with name, description, and icon - although that info may be gathered off-chain like source code is today.

**Comment by hardlydifficult** [comment]
Also review other popular NFTs to see what metadata they leverage and how

**Comment by julien51** [comment]
This is a great point. Since we now have ERC721 full support, maybe we should plan an upgrade to our deployed smart contract to see if this works better?

**Comment by hardlydifficult** [comment]
Yes, we should probably plan for an upgrade.  But for this, I believe we could test it before then - e.g. with Metamask I could point to the local ganache and see how things look.  I have not tried this yet though.

**Comment by hardlydifficult** [comment]
related to this we should answer if we want to ERC165 register support the the ERC721 metadata extension.

**Comment by julien51** [comment]
I think this will require deploying our latests smart contract to see how "compatible" they are with a list of the most popular crypto wallets, but ideally also market places such as opensea and rarebits.

**Comment by nfurfaro** [comment]
I just wanted to start keeping track of this stuff somewhere. Can be moved to a google doc when I have time.

WALLET             ERC721 Spec             MetaData
======================================
OpenSea           OZ                              TokenURI, erc721 metadata extension
Rare Bits            EIP-721                      Custom?
