### ISSUE TITLE
Lock Deletion

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1765]
A creator who has previously created a lock should be able to delete it, only if all of the pending keys have expired.

**Comment by hardlydifficult** [comment]
I believe this is complete.  @nfurfaro re-open if I overlooked something.

**Comment by nfurfaro** [comment]
I believe we still need to implement this check: https://github.com/unlock-protocol/unlock/blob/2c2120ac08089f37765fab9130845ca0f4199d79/smart-contracts/contracts/mixins/MixinDisableAndDestroy.sol#L55

**Comment by hardlydifficult** [comment]
That's not possible though - is it?

**Comment by nfurfaro** [comment]
I suppose we could do something on the frontend...get the `owners` array, and loop through it calling `getHasValidKey` for each address.

**Comment by hardlydifficult** [comment]
Yea.  

Or actually we were discussing before tracking the oldest expiration date.  That would work.
But it makes me question if we really want to enforce this in the contract itself.  Feels more like a front-end warning.  It seems legit to kill a Lock early in some cases.

**Comment by nfurfaro** [comment]
Yeah, probably dealing with this on the front end is sufficient. Re-closing.
