### ISSUE TITLE
Key Cancellation

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1767]
When a customer has purchased a key, they should be offered the ability to cancel their key and get a partial refund.

The refund is partial based on 2 things:
* Prorated
* A penalty

The prorata is based on the current new key price (at time of cancellation) and the remaining validity time on the key. There is an additional penalty equal to a percentage of the price of a new key.

The lock owner can change the default penalty of 10% of the new key price.

Implementing this requires the lock's balance is large enough that it can cover (some?) refunds and impementing this can then only happen after partial withdraws have been implemented.

**Comment by julien51** [comment]
The smart contract part of this is finished at this point.
We need to implement this in the UI, but it will require the key ring work to be done first.

**Comment by cnasc** [comment]
We'll need to add a method to `WalletService` to support this action on the frontend

**Comment by julien51** [comment]
We now have this! 🥳
