### ISSUE TITLE
Consider putting tests alongside the files in src/

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1777]
Currently, we use

src/__tests__/<file structure but ending in .test.js>
src/<file structure>

I would like to propose that we instead put tests alongside their files, so that we get:

src/file.js
src/file.test.js

Very often, I will click on a file in __tests__ thinking it is the regular file, and it is also tricky to find tests for files and vice versa. By placing them alongside src, we can implicitly enforce the .test.js extension without needing a lint rule.

Then, in __tests__ we can put things like `storyshots.test.js` that don't attach to specific files.

**Comment by julien51** [comment]
I am honestly in fave of keeping tests in their own directory which maps the structure of the project (when applicable).
In the end, I think this is just a matter of taste, so I think I'll close that one.
