### ISSUE TITLE
Smart contract test coverage

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1781]
Tracking the work for smart contracts started in #38

**Comment by hardlydifficult** [comment]
Two options: 
 - `solidity-coverage` started work on a PR to support solc5 today.  We can restore that once complete.
 - 0x has a new coverage tool.  They are working on adding Ganache support, which we require ATM.  We can try this tool once support is released.

So both options are blocked for now.

**Comment by julien51** [comment]
What is the status of this one @hardlydifficult ?

**Comment by hardlydifficult** [comment]
solidity-coverage has a working branch but is trying to complete testing before merging to master.
0x has ganache support but have not yet updated documentation.  they have a sample truffle project we can try to learn from.  I started on this the other day with hopes of turning on sol-trace but it's non-trivial... may be best to wait for docs.

Neither have stated an ETA, but both sound close.

**Comment by hardlydifficult** [comment]
Just checking in - it appears both of the options above stalled out.  No recent progress from either :(

I don't know of any other option at this point.

**Comment by hardlydifficult** [comment]
Per recent 0x update, their tools should work with ganache

**Comment by NickCuso** [comment]
Tried this again, getting closer but there appears to be an issue with how we manage migrations.
