### ISSUE TITLE
Use CREATE2 to find the correct Lock address before the block is mined

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1782]
This is a continuation of #1175 , switching the Lock address from a nonce based address to a salt based address.

The current implementation has a race condition.  Usually the Lock address is correct, but sometimes it is a valid Lock but not the Lock you expected it to be.

Currently blocked on the Ethereum hard fork planned for this week.

**Comment by hardlydifficult** [comment]
Hard fork happened - we can pick this up now.  I suggest doing a bit more research and then running details past the team.

**Comment by hardlydifficult** [comment]
The code for this appears to be very simple.  It does require the front-end update in order to generate a salt when calling `createLock`.  

We could make the salt a random uint256 value, which should never collide.  If there is a collision (e.g. someone hardcodes `0` as the salt) then only the first Lock will be created, the other transaction will revert.

I'm actually not sure of the use-case for this other than maybe simplify the race condition concern above.  Should we proceed? Maybe @akeem 

https://github.com/miguelmota/solidity-create2-example

**Comment by cellog** [comment]
would the same salt generation not be needed for purchasing a key?

**Comment by hardlydifficult** [comment]
Nope - the goal of using CREATE2 is to know an address before it's on-chain. It's only for createLock, allowing us to know the address of the Lock before the transaction is mined.  Today we guess, but per my comment above sometimes that guess is wrong.

**Comment by cellog** [comment]
OK. We use the same thing to get the key transaction prior to being mined, so we will need that as well. I think we may want it for edits as well, but that's up to others

**Comment by hardlydifficult** [comment]
No I believe that's a different scenario.  For a key transaction, you have the correct tx hash as soon as it's created - and when buying a key the user already knows the Lock address of interest.  This is unique to `createLock`

The challenge is the normal way addresses are defined are by using the account's nonce, and when we `createLock` it uses the Unlock contract account nonce and not the Lock creator account's nonce.  So we know when the createLock transaction is created what the next nonce is, however if anyone submits a transaction before mine is mined (maybe they have a higher gas price) then I don't get the nonce I thought I would and therefore the Lock address I guessed is not correct.

**Comment by cellog** [comment]
Cool, thanks for the explanation

**Comment by hardlydifficult** [comment]
Security consideration:  Using both CREATE2 and selfdestruct is a risky combination.  If a real Lock is selfdestructed then a scammer can stand a new one up at the same address to pose as that Lock.  We can prevent this by leveraging the `locks` mapping in Unlock.sol as the authority on if a Lock has already been created or not.

**Comment by hardlydifficult** [comment]
I took a look at this but currently cannot figure the correct encoding for calling a constructor with parameters in assembly.  Setting aside for awhile...

**Comment by hardlydifficult** [comment]
Also depends on #1995

**Comment by julien51** [comment]
Now that #1995 is done, what is the state of this one?

**Comment by hardlydifficult** [comment]
We should be able to pick this task up again now.

**Comment by NickCuso** [comment]
https://github.com/miguelmota/solidity-create2-example

**Comment by NickCuso** [comment]
https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/lib/contracts/upgradeability/ProxyFactory.sol

**Comment by julien51** [comment]
One question about this: is there a way to get the address from JS itself?

**Comment by NickCuso** [comment]
Yes.  The zos proxy factory exposes a method you can call via the contract, but it's better to use straight JS for that.  I started working on this

**Comment by julien51** [comment]
perfect!

**Comment by NickCuso** [comment]
from miguelmota:
```
function buildCreate2Address(creatorAddress, saltHex, byteCode) {
  return `0x${web3.utils.sha3(`0x${[
    'ff',
    creatorAddress,
    saltHex,
    web3.utils.sha3(byteCode)
  ].map(x => x.replace(/0x/, ''))
  .join('')}`).slice(-40)}`.toLowerCase()
}
```

**Comment by NickCuso** [comment]
For our implementation, I'm thinking we support setting the salt to 0 and then fallback to `create` (a nonce-based address) instead of using `create2` (a salt-based address) and likely failing..
