### ISSUE TITLE
Increase default timeout of integration tests

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1786]
Currently, about half of the builds on CircleCI fail when the integration tests time out. Can we increase the default timeout for these from 30 seconds to perhaps 60?

**Comment by julien51** [comment]
I guess we can but what is enough? Wouldn't it be better to find the root cause? Can you post comments with the links of the failing builds so we can try to see patterns?

**Comment by julien51** [comment]
I think I found one https://travis-ci.com/unlock-protocol/unlock/builds/102895633.
The error is
```
 TimeoutError: Text not found "30 days"
```

**Comment by cellog** [comment]
I think this is superseded by @akeem 's excellent work. Closing as outdated
