### ISSUE TITLE
Unlock dashboard doesn't release local storage cache

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#179]
**Describe the bug**
The web dashboard doesn't update based on completed transactions. The values for balance, outstanding tokens, and amount to withdraw stay static unless action is taken to force the dashboard to release the cache.

**To Reproduce**
1. Visit the dashboard.
2. Perform a balance-changing action such as purchasing a key - or simply change your network in Metamask.
3. Reload the page.
4. Note that the values have not updated as expected.

**Expected behavior**
On each reload, the Unlock dashboard should reflect current confirmed transactions on the current network.

**Desktop (please complete the following information):**
- Chrome on OSX

**Comment by julien51** [comment]
Closing because we are not using local storage anymore. @benwerd please re-open if this is not appropriate.
