### ISSUE TITLE
/log should show the creator dashboard log page

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1804]
The creator log dashboard is currently not accessible because the `/log` path is not mapping to it in the next.js configuration.

**Comment by cnasc** [comment]
As far as I can see from [the docs](https://nextjs.org/docs/#usage), the configuration we have in place should be sufficient to make the log work 🤔

It'll take some investigation to see what's up with this

**Comment by cnasc** [comment]
This actually is all set up, the issue is that staging is stale! Closing in favor of #1809
