### ISSUE TITLE
Key Cancellation UI

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1806]
The smart contract can now support key cancellations as of https://github.com/unlock-protocol/unlock/pull/1419
We need to implement the UI for this, based on @smombartz 's design.

**Comment by smombartz** [comment]
design is here: https://www.figma.com/proto/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=226%3A524&viewport=-78%2C-67%2C0.253176&scaling=min-zoom

**Comment by cnasc** [comment]
This is part of @smombartz's overall keychain design (I don't think we intend to allow cancellation from the paywall at the moment), so I'll close this as a separate issue
