### ISSUE TITLE
Add NFT `symbol` to the contract (?)

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1818]
The ERC721 standard includes an optional metadata standard: https://eips.ethereum.org/EIPS/eip-721

We have already added the `name` field, should we also add `symbol`?

From the standard:

```
/// @notice A descriptive name for a collection of NFTs in this contract
function name() external view returns (string _name);
/// @notice An abbreviated name for NFTs in this contract
function symbol() external view returns (string _symbol);
```

This is related to #1672 (adding `name`).  The gas impact of adding `symbol` should be on-par with that.

It's not clear to me if a symbol field would be useful.  There are other metadata fields we can consider (such as URI) but since symbol is suggested by the standard I thought we should pose the question here.

**Comment by julien51** [comment]
I would focus on URI for sure. Symbol makes sense for ERC20, but less for NFT?

**Comment by julien51** [comment]
Could we arbitrarily decide that for Locks we return the name in lieu of symbol?

**Comment by hardlydifficult** [comment]
The spec suggests using both name and symbol.

We could certainly leave symbol out... it does seem a bit strange.  However per metamask, I currently have `1 CK` (1 cryptokitty).  I created an issue to research wallet expectations more #1764

Also related is #1819

**Comment by hardlydifficult** [comment]
Or and your question - you mean have one data field which is surfaced both for name and symbol.  Yea that's certainly an option too.  I would just wonder if wallets have expectations regarding symbol length.

**Comment by hardlydifficult** [comment]
Oh, we could also hard-code the symbol.  So every lock we create uses the same symbol `KEY` or similar

**Comment by julien51** [comment]
Let's see after https://github.com/unlock-protocol/unlock/issues/1764 if this is required? I am not sure what symbol we should use tho and it feels like asking this to creators is maybe counter productive: what should they put?

**Comment by julien51** [comment]
I think this is done, right @nfurfaro @hardlydifficult ? Can we close?
