### ISSUE TITLE
We should allow key owners to update their key data

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#1827]
- If a key owner transferrs a key to a user who currently has No keys, the data field on the recipients key will be empty/0. 
- In the case where the key data field is used for, say, the owners email address, there must be a mechanism to allow editing/updating this field in the case of an address change.

This could be done by creating  a public `updateData` function which could be used externally or by existing contract functions as needed.

**Comment by hardlydifficult** [comment]
No longer applicable.
