### ISSUE TITLE
Missing lock address on /log for some transactions

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1834]
The `/log` is very useful! Unfortunately it seems to have a small bug when displaying some transactions.
![image.png](https://images.zenhubusercontent.com/5c4133c214621d11daa67711/d1766ed6-f24d-4818-a262-779756b5134b)

As you can see some lock addresses are empty, but the link is actually there with `undefined` when pointing to etherscan: https://rinkeby.etherscan.io/address/undefined

**Comment by cnasc** [comment]
Yup, Pr for this is #1707 but it still needs some work. I've been bouncing around a bit too much lately, I'll need to sit and focus on one thing at a time I think.
