### ISSUE TITLE
Hardcoding Unlock contract address

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1840]
The Unlock smart contract address is hard-coded in our code (config.js) for the main net and the rinkeby test network.
I suggest that we also hard code it for local dev and CI environment.

This will have several benefits:
* On CI, when running the integration tests we actually have to re-compile and deploy the smart contracts before running tests, and then re-compile the next applications so that the artifacts files 's latest version is added to the running application
* Locally it will help us avoid copying/linking the artifact files which has proven fairly brittle on environments such as windows.
* It also opens the door to using "locked" versions of our ABI, decoupling the development workflow of smart contracts and the web applications.

We can leverage the fact that the contract is always deployed at the same address locally and on CI.

This is coming from a discussion I had with @akeem.

Thoughts @cellog @nfurfaro @hardlydifficult @cnasc ?

**Comment by julien51** [comment]
I'll do a quick experiment PR to see if there are any obvious road blocks.

**Comment by cellog** [comment]
If this is practical, it would be very useful. So this would introduce a compile step for every smart contract stage prior to commit? We would probably need some kind of quick hash of the source to make sure a compilation is not needed, probably as a pre-commit hook. It could be a local gitignored file generated if not present or on any recompile.

So, if practical I am all in favor

**Comment by julien51** [comment]
> So this would introduce a compile step for every smart contract stage prior to commit?

Well, no, we would use our packaged abi which means we can now make progress on the smart contracts without worrying about breaking the web app.

**Comment by cellog** [comment]
Even better

**Comment by julien51** [comment]
Starting to think this is actually very simple: https://github.com/unlock-protocol/unlock/pull/1846

**Comment by julien51** [comment]
Would love to get feedback here before I send a real PR ;p

**Comment by akeem** [comment]
I think this makes sense, with that said while working on the tilt stuff I was able to remove this from being an issue by making some changes to the existing ci compose file. 

I'll look at the associated pr in a minute but I think the only risk would be if a precondition changes that shifts the hard-coded address
