### ISSUE TITLE
Switch `truffle migrate` to follow the ZOS example

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1841]
**Is your feature request related to a problem? Please describe.**
We are currently using shell commands to interact with ZOS, however they just released a better way.

**Describe the solution you'd like**
Follow the example here: https://github.com/zeppelinos/zos/tree/master/examples/truffle-migrate

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
This would bring consistency in the way we deploy smart contracts locally (dev + ci) and staging + production so I am in favor!

**Comment by hardlydifficult** [comment]
Yes - to clarify on the issue I mentioned in a call that with this we should be able to remove the `if` condition in migrations and run all tests through ZOS.

**Comment by nfurfaro** [comment]
I took a crack at removing `shell.js` from our migrations weeks ago based on the example linked above, but failed...it was too early. It should work now and I'm totally in favour. I would like to discuss whether it makes sense to use migrations to deploy proxies for our tests as well. If so, then yes, we can remove the if-statements .

**Comment by nfurfaro** [comment]
I've also thought about what it would look like to have 1 migration script per unlock version, as that's the road we're potentially heading down...

**Comment by hardlydifficult** [comment]
Re-open, there's still a goal of having tests go through the ZOS proxy as well.

**Comment by hardlydifficult** [comment]
But we could close this and open a new issue instead

**Comment by nfurfaro** [comment]
Sorry, didn't mean to close this out with my PR.

**Comment by nfurfaro** [comment]
Can we revisit the goals here? 
We've had some discussion around zos, migrations, testing , deployment/upgrades in the past. Some relevant background info can be found here (specifically around testing):
https://app.zenhub.com/workspaces/unlock-5bfd5c894b5806bc2bf85d03/issues/unlock-protocol/unlock/1176
more context on this here: #969

**Comment by hardlydifficult** [comment]
Yea there are a few things floating around, good to organize a bit.  I think related to ZOS, we have the following outstanding (in priority order):
 - Ensure that we can migrate without requiring a --reset each time
 - Improve confidence by having more tests go through the ZOS proxy.  Expanding this to the point of deploying v0 and then upgrading to v1 and using that in tests would be great IMO.
 - Simplify the environment - it seems we should have `development`, `rinkeby` and `mainnet` - i.e. let's delete `local` and `ganache` and remove any scripted setting of the network.

The acceptance tests are a bit related, but I believe we should keep it separate.  In fact, I think defining our plan around acceptance tests should be higher priority than the tasks above.

**Comment by nfurfaro** [comment]
As for # 1, I'm actually ok with this. It allows us to do things like we do in `upgrades.js`, where we deploy an older version, check certain properties, then upgrade, and compare/test what we need to. If we try to run this through migrations with zos instead (with no If statements checking the network) then when we run `npm run test`, all migration scripts will run (including future scripts which make upgrades). How do we then perform before/after testing? I feel like letting the test suite handle zos on its own allows maximum flexibility in how/what we test. 

#2). We already switched to using migrations with zos to bring our dev setup in line with rinkeby and mainnet deployments. Previously, dev was deploying Unlock with no proxy at all.

#3.) I think this area could be better. We have done all our deployments and upgrades manually using `zos-cli`. As long as the steps are done exactly right there's no problem with this. There was one instance of the Unlock owner being set to an incorrect address already. I favor the approach of scripting our upgrades, where they can be reviewed and are repeatable. 

Of course, all of this depends on doing things in our migration scripts conditional on the network being used. This is currently being achieved with if statements, but  it would be cleaner (in my mind) with a switch statement. There is an example of using network-based conditional actions in the truffle docs here:https://truffleframework.com/docs/truffle/getting-started/running-migrations#network-considerations

**Comment by nfurfaro** [comment]
>Ensure that we can migrate without requiring a --reset each time
Yes, absolutely.

**Comment by hardlydifficult** [comment]
#1) these can remain independent.  The upgrades test can simply ignore migrations and continue to use its own proxy.  This should be fine.

#2) we are still using no-proxy for the majority of tests, no?

#3) would this be with the new deploy-unlock script maybe?  or truffle migrations?

**Comment by nfurfaro** [comment]
If the upgrade test can "ignore" migrations then I would be ok with this. But not sure how this works? I guess we just never reference the deployed(by migrations) Unlock contract.

**Comment by hardlydifficult** [comment]
Yup, in fact as-implemented today we should be good.

**Comment by nfurfaro** [comment]
So for 1, I'm ok with removing the network conditions. This means that for the majority of our tests, we just need to reference the deployed Unlock and we're automatically using zos, correct?

**Comment by hardlydifficult** [comment]
That I do not know. Was hoping we could find a way to explicitly confirm. Maybe with a test checking bytecode at that address

**Comment by nfurfaro** [comment]
Ok. So needs testing, but I believe this should be the case.

**Comment by hardlydifficult** [comment]
I suspect there's another step.  I just wish their example actually had a test too.

**Comment by nfurfaro** [comment]
@hardlydifficult 
> I think defining our plan around acceptance tests should be higher priority than the tasks above.

Feel free to comment on https://app.zenhub.com/workspaces/unlock-5bfd5c894b5806bc2bf85d03/issues/unlock-protocol/unlock/1176

**Comment by nfurfaro** [comment]
I just ran a test. `npm run nuke` followed by `npm ci` to get to a clean slate, and then in `/smart-contracts` I ran `npx truffle migrate` a few times. No issues encountered...output bellow. If nobody can repro the error ("Error: Returned values aren't valid, did it run Out of Gas?") I think we can say that the `--reset` issue is gone.

**Comment by nfurfaro** [comment]
So, re: using the proxy deployed in migrations in our tests, it should be doable using `Unlock.at()` and passing the proxy address from the `zos.dev-1984.json` file. (which probably needs to be deleted before each test run...)

**Comment by hardlydifficult** [comment]
Sounds good
