### ISSUE TITLE
Migrate test to use abi from npm

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1843]
The ABI is now published, let's migrate the upgrades test to use the npm module.

See also https://github.com/unlock-protocol/unlock/pull/1790#issuecomment-468785311 and #1698

**Comment by julien51** [comment]
I should clarify that the published package is for v0 so not sure we can use it to test anything but the v0 version of the smart contracts.

**Comment by hardlydifficult** [comment]
We use this today to explicitly confirm a key created with v0 works as expected in v1
