### ISSUE TITLE
PayWall Reader Landing Page

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#1852]
# Description
This page exists to inform readers and content consumers about what Unlock is. Readers should be able to get to this page from a locked as well as unlocked page when clicking on the Unlock logo in the flag or powered buy Unlock underneath the Payment Box.

The text that on this page is located in this doc (feel free to suggest changes)
https://docs.google.com/document/d/14Kzinz9-T-1xUZOYGuwSllld1x2SuhMhJx7f_m4zbKA

# Design
https://www.figma.com/proto/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=264%3A1159&viewport=2734%2C732%2C0.354305&scaling=min-zoom

**Comment by julien51** [comment]
@cellog have you been able to work on that?

**Comment by cellog** [comment]
Just as soon as the split is finalized it's in the next batch of stories, so perhaps tomorrow or Wednesday!

**Comment by julien51** [comment]
@cellog I think this can soon be closed?

**Comment by cellog** [comment]
as soon as #2108 is merged, it will close it (I put a "Fixes" in the description)
