### ISSUE TITLE
Evaluate the use of tilt for development environment

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#1853]
After meeting with some of the folks on the tilt team we have decided to dedicate a bit of time evaluating if their software or something similar would be a good fit for our multi-application environment. 

I'm time boxing this to around two days with about 0.5 days currently invested

**Comment by akeem** [comment]
As an update, at the time of writing there has been around 1.5 days spent into the investigation. After reaching out to the tilt team it was noted that some regressions currently exist. Upon receipt of updated documentation, the remaining half day of evaluation will begin before providing an assessment on the viability of utilizing this tool in our work flows

**Comment by julien51** [comment]
@akeem What is the state of this?

**Comment by julien51** [comment]
After a bit research it looks like tilt is not quite ready do solve our problems very easily. We should re-consider in a couple weeks/months.
