### ISSUE TITLE
set up CHROMATIC_APP_CODE for CI

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1856]
to run chromatic in CI, we need to set the `CHROMATIC_APP_CODE` env variable to our chromaticqa app code, found at https://www.chromaticqa.com/manage?appId=5c7d369cd530c00020ea8e0e&branch=master

**Comment by julien51** [comment]
To do that I think I need a bit more context about when that code is running.
Basically our tests run in docker *inside* CI, and env variables from the "host" are not passed inside the docker processes. Which means we have to manually do that.

Is that code secret? What are the processes which need it?

**Comment by julien51** [comment]
If it is not secret then maybe it is easier to have it inside version control?

**Comment by cellog** [comment]
it's secret. With it, anyone can use our plan to run their chromaticqa tests :)

**Comment by cellog** [comment]
the command that needs it is found in #1857 `npm run chromatic`

**Comment by julien51** [comment]
Just to clarify, our `unlock-app` needs it to run its tests then, right?

**Comment by cellog** [comment]
Yes, in order to get comparisons between PRs and master of the visual changes in storybook stories for `unlock-app` by using chromaticqa, we will need this. Let me know if there is any other assumption I'm not voicing! :)

**Comment by julien51** [comment]
Once merged, I believe the env variable `CHROMATIC_APP_CODE` will be available do use from inside the script file for `unlock-app`!

**Comment by cellog** [comment]
ok, I'll modify the draft PR to see if it runs a build :)

**Comment by julien51** [comment]
Added both to Circle and Travis! Closing now.
