### ISSUE TITLE
unlock-js library

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1873]
The `web3Service` and `walletService` files are copied between unlock-app (soon to be creator dashboard) and the paywall app.

These 2 libraries can/should actually be re-used by any library which uses Unlock's smart contracts.
We should package them into `unlock-js` and import these from the apps that use them.

**Comment by cellog** [comment]
a couple thoughts: maintaining a library for others requires a fair amount of boilerplate, to set up ES and CommonJS builds, as well as set up peer dependencies for things like the web3 library.

I'm not sure we are quite ready for that level of admin, perhaps a step along this path would be to make a shared directory outside of paywall and unlock-app with the things that they have in common, and then gradually refactor to the point where we can install it locally (put a package.json in there, and use it with file:../shared/package.json, for example) and when it works outright, we publish and try updating config to load the remote version.

Also, I strongly recommend that we spend some time refactoring the services to make them simpler to extend and to test before we publish them to the world. Right now, they are a bit difficult to reason through. We can start the process by writing docs for them, that will help expose any non-obvious pain points.

All of these thoughts should be considered a brain dump, work-in-progress as my understanding of the issue evolves, and the start of conversation.

**Comment by julien51** [comment]
Once we have that, it will become trivial to work on https://github.com/unlock-protocol/unlock/issues/625

**Comment by julien51** [comment]
Closing because this is now a thing!
