### ISSUE TITLE
Wallet check overlay can use the logo of wallet, if detected

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1878]
Currently the wallet check overlay displays a generic message. We have a method in `config.js` for detecting the kind of wallet, a nice UI enhancement would be to display a specific message like "Check Metamask" along with the logo of the wallet.

**Comment by julien51** [comment]
This is a good one. Probably worth adding to #3093

**Comment by cellog** [comment]
Ok cool. The only part of unlock-js that is not unit tested is the function you'd need to use, so I guess it would be good to add tests :). We can't verify that the check is accurate for the wallet, but we can verify that when the situation we expect occurs it properly detects the wallet

**Comment by cellog** [comment]
Oh and in case it wasn't obvious, that method was extracted from config.js and moved to unlock-js
