### ISSUE TITLE
Regression in unlimited lock display during creation

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1880]
**Describe the bug**
#1543 fixed an issue where there would be a momentary flash of MAX_UINT on an unlimited-key lock just after creation. It seems that we've regressed on that because I observed the behavior again this morning:

![out](https://user-images.githubusercontent.com/9300702/53809675-36f5e280-3f23-11e9-8d1c-b4aef42f3399.gif)

**Expected behavior**
The infinity symbol should appear on locks that do not have a limited number of keys.

**Comment by cellog** [comment]
@julien51 I believe this is related to the PR we discussed last week #1711

**Comment by julien51** [comment]
I think this is actually an issue in the `createLock` inputHandler inside web3Service... I'll look into it next.
