### ISSUE TITLE
Full integration tests of the paywall needed to ensure validity

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1889]
Integration tests are needed for the paywall:

[X] Paywall displays lock when loaded from `demo.js` in `unlock-app` #1882
[X] Clicking lock attempts lock purchase #1883
[X] After lock purchase, Paywall iframe minimizes to right side #1884
[X] Paywall redirects back to content after key purchase in main window #1886
[X] Paywall redirects back to content if key has already been purchased in main window #1887

Also needed but harder to test (may have to be manual):

[ ] Paywall redirects to paywall page if there is no account #2275
[X] Paywall prevents scrolling #2268

**Comment by cnasc** [comment]
Thank you for coming up with a good list of the tests we'll need!

**Comment by julien51** [comment]
@cellog What is the status on this one? Can we close?

**Comment by cellog** [comment]
Not yet, but the work I'm about to do will make it significantly easier for us to do these tests so soon :)
