### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1890]
The unlock app needs integration tests that load the full application to ensure that the frontend works with smart contracts and the paywall iframe properly communicates with the underlying paywall application

**Comment by julien51** [comment]
This previous issue has a list of integration tests which we probably need: https://github.com/unlock-protocol/unlock/issues/1399

**Comment by julien51** [comment]
I think we can close this issue/epic because it is a bit too vague for now and we have indeed implemented a bunch of integration tests!
