### ISSUE TITLE
Implement `watchAsset` to auto-add a purchased Key (eip-747)

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1904]
**Is your feature request related to a problem? Please describe.**
When I purchase a key today, it does not automatically appear in Metamask.  I could add it manually, but that's non-trivial.

**Describe the solution you'd like**
Implement eip-747: https://github.com/estebanmino/EIPs/blob/master/EIPS/eip-747.md
This is a front-end task, however we could consider sourcing the data from the contract.

I think we could add a `watchAsset` call anytime the user attempts to purchase a key.  This way we don't flood metamask with entries which have 0 quantity.

**Describe alternatives you've considered**
We could consider submitting to: https://github.com/MetaMask/eth-contract-metadata
However given the manual nature of this approach, I believe we would need to re-architect the solution to use a single contract for PublicLock instead of a contract per-Lock.

**Additional context**
eip-747 is still considered a WIP eip so details may change, but should be working in metamask today.

**Comment by julien51** [comment]
I think this is in the context of https://github.com/unlock-protocol/unlock/issues/1764 ?

**Comment by hardlydifficult** [comment]
Yes, this appears to be the recommendation from Metamask documentation when I started poking around.

**Comment by julien51** [comment]
Status of this one?

**Comment by hardlydifficult** [comment]
This is a front-end task.

**Comment by julien51** [comment]
Finally added it in #7795
