### ISSUE TITLE
Add sol-trace for a stack-trace when the contract reverts

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1908]
**Is your feature request related to a problem? Please describe.**
Often a revert does not give us any information to follow up on.  

**Describe the solution you'd like**
Add `sol-trace` which promises a stack-trace anytime a revert occurs.

**Describe alternatives you've considered**

**Additional context**
I believe we need to wait for version 3.0.1 or greater as they just implemented ganache support.

**Comment by hardlydifficult** [comment]
Started looking into this again.  There is an example here we can work from: https://github.com/0xProject/dev-tools-truffle-example

take note of the truffle-config.js

**Comment by hardlydifficult** [comment]
Per recent 0x update, their tools should work with ganache

**Comment by NickCuso** [comment]
I tried this again and it still does not work.  Now it gets stuck in a loop during migrations constantly checking for a Receipt but never acknowledging the tx completed.

Closing, we can revisit some other time..
