### ISSUE TITLE
Create a `responsible disclosure policy`

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1913]
**Is your feature request related to a problem? Please describe.**
Given that we are on mainnet and handling ETH transfers, it seems we should have a responsible disclosure policy.  If someone finds a bug which risks funds, they should have a path to let us know without disclosing that publicly right away.  

**Describe the solution you'd like**
Listing an email address with PGP fingerprint is fairly common.  

A secure contact like the options above are typically what's needed, but we could consider (maybe longer term) adding terms on how quickly we will react and when we'll share details with the public, etc.

**Describe alternatives you've considered**
We could also use hackerone.com 

**Additional context**
This would only be for security concerns, most issues would go through github issues.

**Comment by hardlydifficult** [comment]
BTW this may be overkill.  I was reading a best practices document and reacted to a few suggestions.
