### ISSUE TITLE
Log page does not show the right lock address?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1917]
When going to the log page on the creator dashboard I see several "lock creation" transactions shown with the same lock address... This can't be right:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/17735/53852303-9b4e8b80-3f8f-11e9-9f97-97671e6a1f02.png">

I suspect this is actually showing the address for the Unlock smart contract?

**Comment by cnasc** [comment]
We had some discussion about this in `#dev` about 2 weeks ago--I think the conclusion there was that this may be caused by #1175 but I can look into it more deeply
