### ISSUE TITLE
Wait for ganache to be up on deploy-locks script

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1934]
The deploy script runs "too fast" and ganache may not be up. This creates the issue that this PR is trying to fix: https://github.com/unlock-protocol/unlock/pull/1929

Rather than sleep, I think we should have a method to try whether ganache is up and deploy scripts only after ganache is up.

**Comment by cnasc** [comment]
This isn't just a matter of having `ganache` up at the right time: we've also found that the `UNLOCK_ADDRESS` environment variable can't be set globally from within an NPM script.
