### ISSUE TITLE
Smart contract tests may be assuming a bit too much about the state of the world

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#1944]
While working on updating our integration test, I came across an issue where adjusting out test ganache configuration caused the smart contract tests to fail. 

The change adjusts to block mining time to one second.

Here are some references of failed builds:
https://travis-ci.com/unlock-protocol/unlock/builds/103453403
https://travis-ci.com/unlock-protocol/unlock/builds/103453408

This was discovered while working on: #1774

**Comment by hardlydifficult** [comment]
Oh I see.  Setting a mining time turns off a feature known as `auto-mine`.  The tests currently depend on that feature.  We could change, however it's intrusive with little benefit.  I recommend we close this issue as `Won't Fix`.

Does that pose a challenge for what you are trying to achieve here?

**Comment by akeem** [comment]
@hardlydifficult Ah, that makes a lot of sense. As a work around we setup another instance in the dockerized instance of ganache with the mining time set in order to avoid introducing weird behavior with the existing test.

Please let me keep it open for a week to see if I can find a way for these to exist happily before closing this

**Comment by hardlydifficult** [comment]
Hmm, maybe it is worth updating the contract tests?  CC @nfurfaro 

Every test would need a change, but we could create a helper script to ease the pain.

**Comment by hardlydifficult** [comment]
Oh I should add that if we do fix this, actually running the tests this way will take MUCH longer to complete.

**Comment by akeem** [comment]
In its current state, I wouldn't consider this to be a high priority issue

**Comment by hardlydifficult** [comment]
Priority aside, I'm still leaning towards won't (ever) fix.  Since executing tests this way would take longer, it's kind of a development environment bug to try.  

That said, maybe there is an opportunity to handle the two different ganache environments better. (i don't have a specific suggestion in mind)

**Comment by nfurfaro** [comment]
We are setting the block time differently (auto-mining vs 3 seconds) for local test vs dev in NPM scripts, so it should be possible to run ganache in ci with different params.

**Comment by hardlydifficult** [comment]
On second thought, we should fix this.  Truffle has a best practice of running the suite against an official node once before launch.  We cannot without dropping the dependency on auto-mine.

**Comment by julien51** [comment]
This is interesting. In what ways do we depend on automine?

**Comment by hardlydifficult** [comment]
2 ways:
 - We assume the object returned includes the `.receipt` and `.logs`, they don't without auto-mine.
 - We assume the impact of a write call occurs immediately, e.g. setX then the test confirms by reading getX.  Without automine we need to sleep before the get call is impacted.

**Comment by hardlydifficult** [comment]
Closing in favor of #2466
