### ISSUE TITLE
Account header on Dashboard and Log should be updated to match Figma

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1945]
![image.png](https://images.zenhubusercontent.com/5c7808ab9546cc1a88f4f8bd/2d0b15fd-c8d9-42cd-9f05-1360233212c1)

The account header has been redesigned, and some of our assumptions moving forward rely on this layout.

Some requirements:

[ ] The "Create Lock" button has 2-pronged behavior
  [ ] On the dashboard, it opens the Create Lock form
  [ ] On the log page, it moves you to the Dashboard (and also opens the form?)

[ ] The search will have to be implemented
  [ ] Initial version can be fairly naive
  [ ] Later versions will likely involve some interaction with Locksmith.

Complexity estimates:
 - Header Layout: simple
 - Button Behavior: medium difficult
 - Search: complex

**Comment by julien51** [comment]
I think we deprecated search a long time ago as there is no real use case for it (even in the mid term future...) ;) @smombartz

**Comment by smombartz** [comment]
will remove search for ever ever!
