### ISSUE TITLE
Subscription status flag floats to top of paywall within unlock-app

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1949]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/9300702/53973720-44e86680-40cf-11e9-9594-f7cd9e08dc58.png">

The subscription status flag is incorrectly positioned on the paywall within `unlock-app` (that is, not on the paywall that has its own subrepo). This may be irrelevant as soon as we switch over to the split-off paywall, but I'm logging an issue just so we can keep track of it.

**Comment by julien51** [comment]
I think this is not a thing anymore? Please confirm @cnasc @cellog and re-open if not!

**Comment by cellog** [comment]
yes, fixed
