### ISSUE TITLE
Use the deploy-unlock script for paywall tests

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1950]
**Is your feature request related to a problem? Please describe.**
The paywall tests are currently using the latest v1 contracts we are actively working on.  Because of this, when the contracts change an API from the v0 version the paywall tests break.  For example see #1938

**Describe the solution you'd like**
Use the `deploy-unlock` script currently in use by unlock-app for the paywall tests as well.  This way that app remains on a specific version until we choose to upgrade.

**Describe alternatives you've considered**

**Additional context**
This is coming from the comments in #1938

This will unblock #1938 (which is for issue #831) and #1782.

**Comment by cellog** [comment]
this should have been fixed by #1947, can you rebase and try again?

**Comment by hardlydifficult** [comment]
oh cool, missed that.  will test now.

**Comment by hardlydifficult** [comment]
You are fast - looking good.  thanks

**Comment by cellog** [comment]
checking in, did that fix this?

**Comment by cellog** [comment]
oh I'm late to the party 👍
