### ISSUE TITLE
Move lock version from Unlock to the PublicLock contract

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1952]
Today the Unlock contract defines the PublicLock version when createLock is called.  I think it would be more appropriate to have the lock contract self declare its version.  This may become important when add multiple locks (e.g. eventually PublicLock will stabilize while other lock types continue to iterate).

**Comment by nfurfaro** [comment]
I think this makes sense in terms of decoupling the development cycles of different lock type. I'm in favour.
