### ISSUE TITLE
Having to add `--no-verify` every time I commit (Windows only?)

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1965]
**Describe the bug**
Every time I attempt to commit, I get the following error:
```
husky > pre-commit (node v10.15.1)
$(git was unexpected at this time.
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Additional context**
Similar issue #1962 made me think to open this, thanks @nfurfaro .  However the push checks seem to work correctly for me.

This may be a Windows only issue.

**Comment by nfurfaro** [comment]
@hardlydifficult Is this fixed for you, or still an issue?

**Comment by hardlydifficult** [comment]
Still an issue, same error.
