### ISSUE TITLE
Storybook doesn't serve

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1974]
**Describe the bug**
`npm run storybook` doesn't serve the storybook anymore.

**To Reproduce**
1. In `unlock app` execute `npm run storybook`
2. Note that storybook builds but does not serve

**Expected behavior**
Storybook will serve and open a browser window

**Additional context**
```
$ npm run storybook

> unlock-app@0.1.0 storybook /Users/christoph/code/unlock/unlock-app
> start-storybook -p 9001 -c .storybook -s src

info @storybook/react v4.1.13
info
info => Loading static files from: /Users/christoph/code/unlock/unlock-app/src .
info => Loading presets
info => Loading presets
info => Loading custom addons config.
info => Using base config because react-scripts is not installed.
info => Using default webpack setup based on "create-react-app".
info => Using base config because react-scripts is not installed.
webpack built 7d3d28c0f4651cf5ad84 in 7577ms                                  0 ^C
```

**Comment by cellog** [comment]
this does not appear to be a problem in current master, after running nuke and npm ci. Could you try again and report?

**Comment by julien51** [comment]
I confirm this is indeed fixed!
