### ISSUE TITLE
Price keys in ERC20 tokens

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1976]
**User stories**
 - As a Lock owner, I would like to offer Keys for sale priced in the ERC20 token of my choice.
 - As a user interested in content, I would like to purchase a Key using ERC20 tokens.
 - As a Lock or a Key owner, I expect features available for ETH based Locks to work for ERC20 as well (e.g. `withdraw` and `cancelAndRefund`).

**Requirements**
 - Define token type on create lock
 - Purchase a key (and purchase for) with tokens
 - Support withdraw tokens (Lock owner)
 - Support cancel key for a partial refund in tokens
 - Drain contract of tokens before `selfdestruct`
 - Validate the address provided on create lock is an ERC20 (as much as possible)

Other features such as `updateKeyPrice` should work without modification.

**Questions/concerns**
 - How this impacts discount tokens from Unlock.sol is not clear, however that feature is still TBD.

**Assumptions**
 - There are no restrictions on which ERC20 tokens are supported in the contract
 - A Lock supports only a single currency type  (i.e. we can't say it's .5 ETH or 2000 STokens).
 - We will not allow a Lock owner to change the supported token type after a Lock has been created.

**Implementation**
Here are a couple options for how we could architect a solution for these requirements:

 - Option 1) implement two lock contracts, one for ETH and the other for ERC20 tokens.
   - Extract a currency related mixin for ETH which implements an interface (let's call it IMoneyMoney for now) we will be able to use for ERC20 as well. 
   - Have all other mixins use IMoneyMoney instead of depending on the EthMixin directly. 
   - Implement a new Lock type with an Erc20Mixin implementing IMoneyMoney, all other mixins remain the same. 
   - When you create a new Lock, an address is required representing the Erc20 token it's priced in. We could:
      - a) have a different API for the different lock type 
      - b) use one api, adding an address field which if set to 0 means use ETH instead of ERC20
      - c) or create a lock using only two fields - lockType (an enum of sorts) and constructorData (as arbitrary data so that Unlock.sol does not need to know how locks are made)
 - Option 2) Keep a single PublicLock contract implementation. 
   - Add an address representing currency and set it to 0 to represent ETH. All money related methods have an `if` condition as appropriate to branch to the correct logic.

Note: not all ERC20 tokens follow the standard so do not trust the return value, require a balance change.

**Comment by nfurfaro** [comment]
I don't have much experience with erc20, but will still try to weigh in here.

In general, I think I favour the approach of splitting up the logic into smaller, dedicated mixins following our established pattern and emphasizing readability and simplicity.
As far as this part:
> When you create a new Lock...

This is a decision that will affect not only locks priced in different tokens, but also different types of locks such as Private, restricted, etc...So the solution here should be the one that enables all these different use-cases. In light of this I think the c. option probably gives the most flexibility, without resorting to the dynamic contract factory and assembly code we had discussed previously?

**Comment by hardlydifficult** [comment]
For consideration:
When we implement this, we could:
 - Require the Lock owner has a token allowance on createLock
 - When transfers occur, move funds directly into the Lock owner's account
 - When a refund occurs, it's transferred from the Lock owner's account to the Key owner's account
 - Remove withdraw on ERC20 Locks

Risk: similar to how an ETH Lock owner may withdraw too much, if the ERC20 Lock owner moves funds out of their wallet or cancels the approval then we are unable to pay refunds.

**Comment by hardlydifficult** [comment]
We hit a challenge while implementing the plan above.  The Unlock.sol contract cannot store another Lock type's bytecode without exceeding the per-transaction gas-limits on Ethereum.

We have 3 options for moving forward:

 1) Merge ERC20 and ETH support into a single Lock
 2) Use a Factory per Lock-type
 3) Use a Dynamic Factory

The merged approach would use the token address as the key.  If the address == 0 then branch to ETH logic, else it is ERC20.

The `factory` approaches simply means that instead of the Unlock.sol holding the bytecode for Lock-types inline, it is sourced elsewhere.
 - A Factory per Lock-type would create a contract wrapping each Lock-type (PublicLock and PublicErc20Lock).  This wrapper would deploy the Lock when called by Unlock via the `createLock` flow we have today.  The difference is the bytecode has been relocated to the wrapper contract(s) so Unlock.sol stays under limits.
 - A Dynamic Factory would allow us to create and/or upgrade Lock-types anytime by the Unlock owner calling a `publishLock` function with its bytecode in a transaction. Each available Lock-type is then stored in a `mapping`, indexed by a descriptive string (maybe or an uint/enum).

Pros/cons for each:
 1) Merged
    - Pros:
      - Easiest to implement today
    - Cons:
      - Slightly higher gas cost to create a lock or purchase a key as compared to the other options 
      - Non-applicable functions cannot be removed (e.g. `withdraw` is always a no-op if using ERC20 - the differences like this may grow overtime)
 2) Factory
    - Pros
      - Unlock.sol can handle more than a single Lock-type
    - Cons
      - Requires maintaining a wrapper contract per Lock-type
 3) Dynamic
    - Pros
      - Unlock.sol can handle more than a single Lock-type
      - Locks may be upgraded at any time (today in order to upgrade a Lock, we re-deploy Unlock which has the Lock itself inline - the dynamic factory would allow us to only upgrade a single Lock instead of everything bumping versions)
    - Cons 
      - Requires adding a new mapping data structure to Unlock.sol, a way of publishing Locks, and an update to our deploy flow.
      - Requires we use assembly to call `create` (however we are considering using `create2` anyways, if we did all options have this same con)

Ultimately the cons for 1) are minor and the development cost for 3) is high.

I recommend we pursue 1) the merged solution.  I also recommend we open a task to pursue 3) in the future.

**Comment by nfurfaro** [comment]
Nice breakdown of options. 
I'm leaning toward the same as your recommendation (option 1 for now, pursue 3 for future lock types).
I think long-term 3 will be simpler to maintain than 2, and will nicely decouple individual lock-type's development/release cycles.

**Comment by julien51** [comment]
I *think* this can be closed?

**Comment by hardlydifficult** [comment]
Yes, there are just some testing tasks remaining and we have other issues for that.
