### ISSUE TITLE
Update contract deployment script to be idempotent for local deployments

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#1993]
During our work of setting up integration test, we noticed that the tests are sensitive to multiple deployments locally. 

If possible we should update the script to avoid multiple deployments of the same contract if they already exist in the test environment

**Comment by julien51** [comment]
Hey! I am not quite sure I understand. Could you provide more context and/or close if this not applicable anymore?

**Comment by akeem** [comment]
This was prior to us having fixed addresses in our configuration for the location of the unlock contract. Previously we were using the abi file I believe the help determine the location of the contract, double deployment of the unlock contract were causing a bit of an issue.

closing as resolved
