### ISSUE TITLE
Support Key swaps

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1998]
**User stories**
 - As a Key owner, I would like to trade my Key for a Key to a different Lock of interest.

**Requirements**
 - A Key owner can approve a swap for a Key from a specific Lock of interest.
 - A Key owner can execute a previously approved swap.
 - A Key owner can cancel an approval they previously made.
 - Approvals include an expiration date.
 - The front-end can display approvals: given Key x, list what Keys the user can accept and execute the swap on immediately.

**Questions/concerns**
 - How do we handle different durations remaining on keys?  Maybe when approving a swap, state that the expiration date must be `>= x`?
 - Does the transfer fee apply in this scenario? See #1997 
 - Do we allow the approving a swap for a list of potential keys?  Or keep it 1:1?

**Assumptions**
?

**Implementation**
A few options on how we could meet these requirements:
 - 0x could be an option - however based on preliminary research the approval requires a specific tokenId.  This means we must match before approving, and then it could be executed.  I don't know a good way to handle that process.  More research may uncover a better solution from 0x.
 - On-chain approval: Approvals are recorded with an on-chain transaction.  The advantage is all information is in one place, the disadvantage is approvals cost gas.
 - Off-chain approval: Approvals are recorded with a signed message stored off-chain.  The advantage is approvals are free to create, the disadvantage is it requires a second data-storage solution.

**Comment by hardlydifficult** [comment]
@julien51 `off-chain approval` seems like a good path forward, agree?

**Comment by julien51** [comment]
Let's push this to MUCH later ;)
