### ISSUE TITLE
0x marketplace trading tests

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#1999]
**User stories**
 - As a Key owner, I would like to sell or trade my Key on a 0x marketplace.

**Requirements**
 - Support the ERC721 standard
 - Charge a fee on transfer: #1997

**Implementation**
This should be complete and only require testing to confirm.  We could follow the example here: https://github.com/0xProject/0x-starter-project to perform trades using our contracts to help uncover anything we may be missing.

Note: we may want to time-box this task in case integrating 0x turns out to be challenging.

**Comment by julien51** [comment]
Let's push this to later
