### ISSUE TITLE
Migrate smart-contract tests to Typescript

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#2002]
**Is your feature request related to a problem? Please describe.**
This may be a nice-to-have.  I think the benefit would be most noticeable when interacting with helper scripts (something I think we should consider using more). 

**Describe the solution you'd like**
Switch from `.js` to `.ts`

**Describe alternatives you've considered**
n/a

**Additional context**
This is supported by Truffle per https://truffleframework.com/docs/truffle/testing/writing-tests-in-javascript#typescript-file-support

**Comment by hardlydifficult** [comment]
Hmm took a quick look at this, but hit an error when attempting to use typescript syntax.
Setting it back down.
