### ISSUE TITLE
Lower test verbosity on CI

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#2020]
At the moment, we have a lot of chatter in out test output. We should start to reduce the amount of noise in our tests/ci builds in order to narrow in on things that have gone amiss

**Comment by julien51** [comment]
I think CircleCI does a pretty good job at hiding/isolating things? I worry that we may miss valuable information if we drop this?

**Comment by akeem** [comment]
We could defer this for another time, but our current workflow when determining the reason for failure on CI is something like scroll scroll scroll pass all the non-failure stuff in search for what actually went wrong.

**Comment by akeem** [comment]
closing this for now
