### ISSUE TITLE
Create ERC20 token contract to use for testing

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2025]
We will need an ERC20 token contract to test Locks priced in ERC20.

We should use OpenZeppelin for this... or maybe copy-paste Dai?

**Comment by hardlydifficult** [comment]
RE: OpenZeppelin or Dai
The challenge with Dai is it's created for an older version of Solidity.  If we want to use their code, to keep it true to form we should deploy the bytecode instead of using a .sol file.

So using OpenZeppelin would be easier / cleaner but using Dai is more representative of our primary use case.  That said, we have no reason to believe Dai won't match the functionality provided in OpenZeppelin's implementation.  The best benefit of using Dai that I can think of is it will be a more accurate estimate of gas requirements.

I'm leaning towards using OpenZeppelin here.
cc @nfurfaro @julien51

**Comment by nfurfaro** [comment]
@hardlydifficult can you link to the Dai contract you're looking at?

**Comment by hardlydifficult** [comment]
https://etherscan.io/address/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359#code
