### ISSUE TITLE
When running the app in dev we should be using a proxy

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#2036]
Currently, `npm run dev` deploys a new Unlock contract via `deploy-unlock.js`. Unlike our contracts on rinkeby and mainnet, on dev we interact with unlock directly as there is _No_ proxy involved.

I think we should revisit the use of a proxy on dev for consistency (which we used to have). 
The implementation could be fairly straightforward. Before the `deploy-unlock.js` script is run we need to run truffle migrations. After Unlock is deployed (from the npm package) we need to use the Zos API to call `setImplementation()` to point the deployed proxy at the hardcoded Unlock address.
The question becomes "where to implement this?"
- If done in `deploy-unlock.js`we need to import and use Zos here (it's currently only used in the `smart-contracts` directory.
- If done in the migrations scripts, we need to re-introduce conditionals to perform the `setImplementation()` call only when on the development network, but _NOT_ when we're testing contracts via `npm run test`.

**Comment by julien51** [comment]
Hey @nfurfaro is this still accurate?

**Comment by nfurfaro** [comment]
@julien51 I think in a perfect world we would be mimicking our production
environment as closely as possible in dev, which would mean deploying a
proxy(we currently do not). That said, I don't think it would add a lot, if
any, value. The exception might be that we could catch a proxy-specific
error earlier, but our smart contract test suite should be adequate in this
regard.

**Comment by nfurfaro** [comment]
@NickCuso what are you're thoughts here? I'm thinking to close this issue, unless you think it's important or adds good value in some way.

**Comment by NickCuso** [comment]
I do think this adds value.  I wrote a script to deploy with proxy: https://github.com/HardlyDifficult/hardlydifficult-ethereum-contracts/blob/master/src/protocols/unlock.js (need to bump the version now though)
and use it when testing unlock-contracts: https://github.com/HardlyDifficult/unlock-contracts/blob/master/test/PaidOnlyFeature.js#L15

**Comment by NickCuso** [comment]
Why this might be a nice to have: going through the proxy will change gas costs and may impact how errors are communicated.

**Comment by julien51** [comment]
Given that we don't run this locally anymore (most dev happens against Rinkeby) we can close.
