### ISSUE TITLE
Implement ERC20 token support

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2039]
This task should complete the epic by implementing the IMixinFunds for ERC20 and creating a new lock type.

It's not clear that we can sub-divide further unless with submit un-tested changes as a stepping stone.

**Comment by julien51** [comment]
Is that a dup of https://github.com/unlock-protocol/unlock/issues/1976 ?

**Comment by hardlydifficult** [comment]
At this point it kinda is.  #1976 was an epic broken into a few separate issues, this issue was a bit of a catch-all bucket of work remaining at the end.

However the way I'm approaching things at the moment will leave a couple follow up tasks for consideration in the epic.
