### ISSUE TITLE
Standardize and import mocks in tests

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#2045]
**Is your feature request related to a problem? Please describe.**
Right now we have mocks defined all over the place in the tests. This is a lot of code duplication, and can make it difficult to tell which tests may be out of sync with reality. (Imagine we start to model state differently, so a component that accesses the state will be unable to do so successfully. If it has a local mock of the old model of state, the tests won't flag that there is an issue.)

**Describe the solution you'd like**
Extract the most common mocks into a module, and begin to use those mocks throughout the tests and stories. In particular, I think the mocks of Redux state are important here. It should be relatively easy to have a variety of different states that can be imported and used in tests, and this way all the pieces move at the same time as the others.

It looks like we've done a very small amount of this sort of thing with the `__mocks__` folder in `unlock-app`.

**Comment by cellog** [comment]
for reference in the discussion, here is the documentation on how jest processes files in `__mocks__`:

https://jestjs.io/docs/en/manual-mocks

**Comment by cellog** [comment]
also for reference in the discussion, we have a standard directory for test helpers in each repo, it is `__tests__/test-helpers`, so we could put our standard mocking helpers there

**Comment by julien51** [comment]
When you say `mock`, do you mean more like fixtures?

**Comment by cnasc** [comment]
Yes, what I had in mind while writing this is how many files need to have some dummy Redux state passed into them. Instead of spreading that effort out over every file that needs it, it would be preferable to have a few standardized states that we can import.
