### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#208]
As an open source project, we should have a well-described documentation site, as well as in-line code documentation.

I recommend using [Read the Docs](https://readthedocs.org/) to establish a documentation site at docs.unlock-protocol.com, which would be configured to automatically rebuild from markdown files stored in the Unlock repository itself. New commits to master would automatically rebuild the documentation site.

For in-line documentation, I think we should use JSDoc-style syntax, which can then be automatically compiled into a reference site.

**Comment by cellog** [comment]
react-redux used docusaurus (https://docusaurus.io/) and hosts the docs on netlify for a good rate as an open source project. This could work well for unlock

**Comment by benwerd** [comment]
Closing this as we've made the decision to use the wiki for now. We can come back to it later if it doesn't work out.
