### ISSUE TITLE
Add ERC721 enumerable extension

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#2082]
**Is your feature request related to a problem? Please describe.**
We have functionality already implemented which is similar to APIs suggested in the ERC721 spec.

**Describe the solution you'd like**
Consider using: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/IERC721Enumerable.sol

**Describe alternatives you've considered**
Maybe https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721Enumerable.sol but that includes a lot.  We should take a close look at this class before picking up this task to decide if we can use this or just the interface.

**Additional context**
See also https://eips.ethereum.org/EIPS/eip-721 and search for "enumeration extension"

**Comment by hardlydifficult** [comment]
Let's revisit after #1764

**Comment by NickCuso** [comment]
From OpenSea:

Regarding “automagic” submission, as long as the contract is ERC721-compliant, implements `supportInterface()` for ERC721Enumerable (0x780e9d63) and `name()`, and has metadata, it should auto-appear when the first token is minted. The main question I would have is whether you want all of the contracts to appear under the same storefront / category on OpenSea or different ones?
