### ISSUE TITLE
Switch to OZ ERC721Holder implementation

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2083]
**Is your feature request related to a problem? Please describe.**
We have implemented a feature which appears to be available from OpenZeppelin.

**Describe the solution you'd like**
Consider switching to https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721Holder.sol

**Describe alternatives you've considered**
n/a

**Additional context**
Pending testing, this appears to be 1:1 with what we have today.

**Comment by nfurfaro** [comment]
Sounds like a plan. It will help to simplify the core PublicLock contract a bit more as well.
