### ISSUE TITLE
read-only provider URL is not set for the paywall app on netlify

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2105]
`PAYWALL_NETLIFY_STAGING_READ_ONLY_PROVIDER` and `PAYWALL_NETLIFY_PROD_READ_ONLY_PROVIDER` are not set on CircleCI, which breaks the paywall on both staging and production.

**Comment by cellog** [comment]
I successfully configured PAYWALL_NETLIFY_STAGING_READ_ONLY_PROVIDER, just need the production to be set up

**Comment by cellog** [comment]
added production, waiting for master build to finish to confirm the fix is in

**Comment by cellog** [comment]
fixed in staging

**Comment by cellog** [comment]
can't verify the fix in master until Tuesday when staging deploys to master

**Comment by julien51** [comment]
Let;s close for now and re-open if this is no-op.
