### ISSUE TITLE
Wording of the paywall landing page section about the benefits of unlock needs expansion.

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2113]
The current wording is:

```
Unlock is built on top of the Ethereum blockchain and therefore offers
          a number of great privacy and security features....
```

@cnasc suggested we expand this into more concrete benefits, this issue is designed to track those changes and eventually lead to a PR.

**Comment by julien51** [comment]
Maybe @smombartz can have a look at this?

**Comment by smombartz** [comment]
hows this @julien51 

> Unlock does not collect any personal information. Like all transactions on the the Ethereum blockchain they are captured in its ledger in an anonymous form. `
