### ISSUE TITLE
add ChromaticQA to our README

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2116]
Here is a sample they sent as a possible way to acknowledge the support they are giving our open source project:

https://github.com/govuk-react/govuk-react#acknowledgements

**Comment by domyen** [comment]
Appreciate that @cellog 🙏 

Our friends at Auth0 have a [nice shoutout format too](https://github.com/auth0/cosmos#thanks), maybe you can paste theirs.
