### ISSUE TITLE
Metamask prompts on first page load

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#2126]
**Describe the bug**

On loading any Unlock page, Metamask pops up and prompts you to log in. It should only ever pop up if we're actually doing anything that requires its involvement.

**To Reproduce**
1. Visit the homepage.
2. Say hi to Metamask!

**Expected behavior**
We shouldn't get in the user's way unless we absolutely have to. Metamask should not pop up when visiting the homepage or any public page, in particular.

**Screenshots**

<img width="1438" alt="Screen Shot 2019-03-15 at 3 35 39 PM" src="https://user-images.githubusercontent.com/624104/54465371-05a5bf80-4738-11e9-8874-e6c5e8fe6bd3.png">

**Desktop (please complete the following information):**
 - OSX 10.14.3, Chrome 72

**Comment by cellog** [comment]
I believe #1653 (when implemented) would fix this

**Comment by julien51** [comment]
This is actually how a lot of web3 app work and I think in the end it is a good thing. This lets us a little bit of time to load data in the back for the user and it is a much better experience than askig the user to wait for the data...

Note that when/if we split the static app from the dashbaord, we will not be able to do that and, at least for me, this is a reason to *not* do the split until we can guarantee a fast loading of the data.
