### ISSUE TITLE
User key management dashboard

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2137]
In order to manage keys, cancel keys and get partial refunds, and see the length of time keys have left, we need a User key management dashboard.

This will live on the paywall as an app at `https://paywall.unlock-protocol.com/dashboard` and will be based upon @smombartz 's design work found here: https://www.figma.com/file/ZIhu6WMu781dsGDHszPKb1UT/Unlock-Keychain?node-id=0%3A1

**Comment by cellog** [comment]
@julien51 can you confirm that the URL of the keychain dashboard will be on `https://paywall.unlock-protocol.com/dashboard`? I recall a conversation recently where you wanted it to live at `unlock-protocol.com`

**Comment by cnasc** [comment]
IIRC right now the keychain is already on `unlock-app`. You have to manually put in the URL since there's no navigation to it, but the route exists and there is a bit of stuff on the page.

**Comment by julien51** [comment]
The Keychain is now here! Not perfect by any means, but it's shipped ;)
