### ISSUE TITLE
Ether Symbol & Monaco Font

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#215]
@benwerd I looked into why the design specified the Manaco font (which it shouldn't). The Eth symbol isnt available in Plex (the font we're using) and hence it reverted to Monaco. I've created an SVG which you call pull from Zeplin or from [here](https://www.dropbox.com/s/eytrq6maoq5csp1/eth.svg?dl=0)

**Comment by benwerd** [comment]
Thanks @smombartz! I'm having a go at integrating this now.

**Comment by benwerd** [comment]
Implemented in #217.
