### ISSUE TITLE
Store keys for users without crypto wallets

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#2163]
Users without crypto wallets need to have their keys stored for them, in such a way that we (or another entity hosting Unlock code) can't access them. 

* [ ] The key will need to be generated from scratch.
* [ ] Keys should be attached to a user account, with the password used to decrypt them for use. The user should never need to understand what keys are, or have to interact with them directly.
* [ ] A recovery key should be generated at the same time.

**Comment by cnasc** [comment]
This is completed, we only store encrypted private keys
