### ISSUE TITLE
Allow users to recover their private key

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#2164]
On account creation, the user was given a recovery key. The user needs to be able to supply that recovery key to a logged-out page that will:

* [ ] trigger a confirmation email to the original account email address
* [ ] on confirmation ask the user to supply a new password (with confirmation)
* [ ] re-encrypt the user's wallet keys with the new password
* [ ] log the user in

Related: #2160

**Comment by akeem** [comment]
The api portion of this feature was released in #2312

**Comment by julien51** [comment]
We have that!
