### ISSUE TITLE
Allow users to change their passwords

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#2166]
While logged in, a user should be able to change their password. This will

* [ ] prompt for a new password (with validation field)
* [ ] on submission, re-encrypt the user's private key with the new password

**Comment by cnasc** [comment]
I don't know what discussions we've had around password standards, but we may want to include a check against this as part of the validation https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/

**Comment by akeem** [comment]
I think this has been resolved for the most part, @cnasc ?

**Comment by cnasc** [comment]
This is almost done, but I think we shouldn’t close it until we have an unlock provider working, since they need to sign the payload for the changed password
