### ISSUE TITLE
Set more strict Lint rules on contracts and address outstanding warnings 

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2173]
**Is your feature request related to a problem? Please describe.**
We recently recently had an instance where Nick correctly a lint issue in a PR while submitting an unrelated change.  So why wasn't this rejected originally?

https://github.com/unlock-protocol/unlock/pull/1716/files#r260537112

**Describe the solution you'd like**
Check the lint configuration, test lint errors in Travis, and address outstanding warnings. 

**Describe alternatives you've considered**

**Additional context**
We may want to check both the JS and Solidity linters.

**Comment by julien51** [comment]
@hardlydifficult Is this still a thing?

**Comment by julien51** [comment]
Closing for now. Feel free to re-open if needed.
