### ISSUE TITLE
Run contract tests w/ and w/o ERC20 tokens

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#2174]
**Is your feature request related to a problem? Please describe.**
The current ERC20 implementation selectively tests functions believed to be impacted by using ERC20 instead of the usual ETH pricing.  This approach assumes that we have selected the correct subset of tests.

**Describe the solution you'd like**
Switch the tests to use a behavior pattern (or similar) and have them run twice - once when priced in ETH and once when priced in ERC20.

**Describe alternatives you've considered**

**Additional context**

I think it may be best to have all tests run for both scenarios.  I think this will be easier on us when we add other scenarios in the future.  When a test needs ERC20 specific changes, there's an if condition in the test.

**Comment by hardlydifficult** [comment]
Maybe using this approach: https://mochajs.org/#dynamically-generating-tests

**Comment by hardlydifficult** [comment]
This is important for the transfer fee implementation as well.  #1997

**Comment by julien51** [comment]
I actually want to do something like that at the `unlock-js` level: we deploy multiple lock "flavors" (version, currency... etc) and we make sure the "core" function:
- create lock
- withdraw
- change price
- purchase key
...
 behave as they should!

**Comment by julien51** [comment]
I have implemented this inside of `unlock-js` in the integration tests for walletService. I'll close but feel free to re-open if applicable!

**Comment by NickCuso** [comment]
I do still want to implement this.  Although maybe it's a low priority.

If we consider the test design it shouldn't be a large maintenance expense.  After the initial migration, we just need to get in the habit of using a slightly different pattern.

If we do encounter an issue it'd be best to catch it when introduced into the contract instead of after starting an app upgrade.

**Comment by NickCuso** [comment]
We do have a place for this now, but still need to port a few more tests over to use it.
