### ISSUE TITLE
Consider moving convenience functions to an external contract

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2175]
**Is your feature request related to a problem? Please describe.**
Read only functions do not cost gas to interact with, however they do increase gas costs for 1) deploying the contract, i.e. `createLock` and 2) raise gas costs a tiny bit for every other function.

Gas requirements are always too much, can we optimize?

**Describe the solution you'd like**
Move `getOwnersByPage` to an external contract.  The external contract simply takes a single read transaction and uses a loop to pull the information from our main contract. This still allows the front-end to benefit from a paginated request when making a request to a Ethereum node, while removing the negative gas impact on our primary use cases.

If agreed, we should review other functions to see if more could use a pattern like this.

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
This is a neat idea! I like the idea of removing that from the lock contract to save on gas while still keeping this inside the evm to avoid massive latencies.

**Comment by nfurfaro** [comment]
I like this as well. Would this be achieved with a "convenience" library perhaps?

**Comment by hardlydifficult** [comment]
Going the other direction instead, simplify on-chain as much as possible (overtime..).  See #3646
