### ISSUE TITLE
Switch to OpenZeppelin's ERC721 standard implementation

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2176]
**Is your feature request related to a problem? Please describe.**
We are not using the ERC721 implementation from OpenZeppelin today because we wanted to make some functions `payable`.  The reason for this was to support transfer fees, however per #1997 we are not certain that we will need this (tl;dr; charging this fee in ETH adds complexity and new data storage requirements, we may want to simplify and charge in WETH instead).

**Describe the solution you'd like**
Switch to OpenZeppelin where possible.  We could start with interfaces and then consider if the concrete classes make sense for our needs.

**Describe alternatives you've considered**

**Additional context**

**Comment by nfurfaro** [comment]
OpenZeppelin's ERC721 requires that `transferFrom` is not payable.
