### ISSUE TITLE
Re-sort the inheritance order contracts use

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2178]
**Is your feature request related to a problem? Please describe.**
There is a Solidity best practice for inheritance to be in the order of most base-like to the most derived.  We do not follow this consistently today.

**Describe the solution you'd like**
Review and update the order used by Unlock and PublicLock (which cascades impact to the mixins).

**Describe alternatives you've considered**

**Additional context**
Adding new classes and refactoring features will encounter less errors related to linearizing if we do this consistently.

**Comment by nfurfaro** [comment]
Strongly in favor!
