### ISSUE TITLE
Front-end support for multiple Lock versions

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2179]
**Is your feature request related to a problem? Please describe.**
As soon as we upgrade `Unlock.sol`, there are potentially multiple Lock versions in the wild.  We have a migration path, but no plans to force that.

**Describe the solution you'd like**
The JS implementation should consider the Lock version and adjust the ABI used accordingly.

**Describe alternatives you've considered**

**Additional context**
Related to this, I'd be curious to better understand the process we'll use for upgrading contracts going forward.

**Comment by julien51** [comment]
This is correct. I think the answer to this is covered in https://github.com/unlock-protocol/unlock/wiki/How-we-work ?

Closing but please, feel free to re-open if that does not answer your question.
