### ISSUE TITLE
Remove the Lock interface until there's a use-case for it

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2180]
**Is your feature request related to a problem? Please describe.**
I have not been consistently updating the ILockCore.sol interface file.  At the moment, we only use this in Unlock.sol which does not depend on most of the features it includes.

**Describe the solution you'd like**
Either:
 - Remove the file completely use the PublicLock type instead
 - Reduce the scope of this interface file (and maybe rename it) to limit it for use-cases Unlock.sol cares about

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
Works for me.
