### ISSUE TITLE
ETH locks should transact in either ETH or WETH

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2183]
**Is your feature request related to a problem? Please describe.**
At the moment you could price a Lock in either ETH or WETH.  However we know those are the worth the same.

**Describe the solution you'd like**
We could accept WETH on any Lock priced in ETH (or maybe give the Lock owner an option to enable/disable that).  When a user calls `purchaseFor`, we first check `msg.value` and if there was not enough included then attempt to get the rest from WETH (and if that fails then revert).

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
That would be a nice feature indeed but I believe this is very low priority. I also worry about introducing confusion.

In the end, maybe the best way forward would be to deprecate the Eth lock at some point?
