### ISSUE TITLE
File system operations don't work with netlify

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#2187]
**Describe the bug**

`fs` doesn't work by default on Netlify. As a result, the blog engine doesn't work as expected.

We will either need to generate the blog json on the command line and commit it in, or use something like `netlify-cms-backend-fs` to allow files to be written.

In order to continue to be host-agnostic, I'm going to add the json generation as a command line option.

**Comment by julien51** [comment]
I think we need to generate the blog pages locally before committing? This would guarantee that we know exactly what is crying deployed?

**Comment by benwerd** [comment]
Yeah, I think so. It's an easy fix - just got to move where the functions are called.
