### ISSUE TITLE
Address warnings from truffle-security

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2218]
We ran the truffle-security report and here's the results at the moment.  The good news is that the only error is from a dependency, not our code.  However we should review each of the warnings in detail

```
zos-lib/contracts/Initializable.sol
  1:0  warning  A floating pragma is set  SWC-103

openzeppelin-solidity/contracts/math/SafeMath.sol
  1:0  warning  A floating pragma is set  SWC-103

/IERC721Receiver.sol
  1:0  warning  A floating pragma is set  SWC-103

openzeppelin-solidity/contracts/utils/Address.sol
  1:0  warning  A floating pragma is set  SWC-103

E:/unlock/smart-contracts/contracts/PublicLock.sol
  25:29  warning  integer overflow     SWC-101
  41:10  warning  assertion violation  SWC-110

/IERC165.sol
  1:0  warning  A floating pragma is set  SWC-103

openzeppelin-solidity/contracts/token/ERC721/ERC721Holder.sol
  5:5  error  The binary addition can overflow  SWC-101

openzeppelin-solidity/contracts/access/Roles.sol
  1:0  warning  A floating pragma is set  SWC-103

/IERC20.sol
  1:0  warning  A floating pragma is set  SWC-103

E:/unlock/smart-contracts/contracts/Unlock.sol
  1:0  warning  precondition violation  SWC-123

✖ 11 problems (1 error, 10 warnings)
```

**Comment by julien51** [comment]
See #1763 for context.

**Comment by hardlydifficult** [comment]
Ran again, most of the checks fail.  But new warnings:

E:/unlock/smart-contracts/contracts/interfaces/IUnlock.sol
  73:509  warning  Local variable shadows a state variable  SWC-119

zos-lib/contracts/Initializable.sol
  58:609  warning  Local variable shadows a state variable  SWC-119

E:/unlock/smart-contracts/contracts/mixins/MixinKeys.sol
  153:16  warning  Local variable shadows a state variable  SWC-119

openzeppelin-solidity/contracts/utils/Address.sol
  27:215  warning  Local variable shadows a state variable  SWC-119

E:/unlock/smart-contracts/contracts/mixins/MixinGrantKeys.sol
  73:2522  warning  Local variable shadows a state variable  SWC-119

**Comment by hardlydifficult** [comment]
Hmm I just spent a minute looking over each of these entries.  None appear actionable.  The original set does not apply given recent changes.  The new set of local variable shadow errors appear to be all false positives.  This may be because of the errors truffle-security hits while trying to execute now.

I'm going to close this task.  We should revisit truffle-security again at a later date.
