### ISSUE TITLE
Reconsider our use of prettier-eslint

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#2228]
When investigating a prettier bug, @cellog found that we may not be using the recommanded way to work with both eslint end prettier: https://prettier.io/docs/en/eslint.html

We should reconsider the use of that npm module and maybe even our reformat script as this would be taken care of by eslint completely.

**Comment by cellog** [comment]
In my investigations, we would probably still need a reformat script, it would just change to `eslint . --fix`
