### ISSUE TITLE
staging is 10x slower than 2 weeks ago

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2243]
In my browser testing, across platforms, with gigabit internet, purchasing a key, opening the dashboard, refreshing content when a key has been purchased are all 10x slower than 2 weeks ago.

For example, going to https://staging.unlock-protocol.com/demo/0xdD3a0c4b88FA29d1BfCE5F526b0cacF3b79eF622 it takes 10 full seconds to display the lock. This is a relatively recent lock. The UI is just a blank paywall with the "You have run out of access" message. 10 seconds later, the lock appears (and quickly disappears if purchased).

This is across all browsers I have tested. I don't know what is causing the regression yet.

**Comment by cellog** [comment]
For more info, it is slowest in Brave browser, fastest in chrome

**Comment by cnasc** [comment]
I think we should grab some profiling data for a few different browsers to make sure the drag is in the same place for each of them and then get cracking on a fix

**Comment by julien51** [comment]
Let's regroup on this once we actually have a production paywall. For now, please let's focus on our current list of tasks.

**Comment by julien51** [comment]
@cellog Can you provide on context about this now that we have a production paywall? Any data we can use to debug/measure progress?

**Comment by julien51** [comment]
Ok, closing for now until we have more data.
