### ISSUE TITLE
Fix Locksmith deployment 

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#2273]
**Describe the bug**

Current Locksmith is no longer being deployed to production

** Steps to fix **

1. Update circle configuration to utilize the docker image as part of the deployment process
2. Remove error catch all so that builds do fail and we are alerted

**Comment by julien51** [comment]
What is the status of that one @akeem ?

**Comment by akeem** [comment]
We are currently deploying via the new deployment, but have yet to cut over the CNAME. I'll will let it soak for today to pick up subsequent deployments then cut it over midday tomorrow

**Comment by akeem** [comment]
Closing as this has now been cut over and live in staging & production
