### ISSUE TITLE
Paywall should show "pending" state prior to "confirming" state (the blue design) after key purchase clicked

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2284]
Currently, when clicking on the "purchase key" button, nothing is shown for up to 5 seconds. It would be good to show a purchase pending state, using Sascha's blue design.

**Comment by cnasc** [comment]
#1383?

**Comment by cellog** [comment]
nope this is the blue lock, which should show in between the green lock and yellow lock

**Comment by cnasc** [comment]
Right, "between when a user clicks on the purchase button and when the lock shows that it has started confirming"

**Comment by cellog** [comment]
So this is actually caused by a deeper issue, one which I am unsure how to address best. Basically, the problem is at the intersection of the transaction creation and the parsing of receipt.

Here is the progression for key purchase:

1) pending transaction emitted
2) hash received, new transaction emitted
3) <long delay>
4) first transaction receipt is emitted

The first 2 events are emitted by walletService, the last by web3Service. Only web3Service has the logic that sets the metadata on a transaction, which in the case of key purchase is the key and lock that is used by the UI to figure out what to display. Thus, in order to properly address this issue, it looks like some of the logic that is in web3Service will need to be available inside the walletService as well.

This is where my question comes in. We could extract the common logic from web3Service, which would mean taking `eventsHandlers` and making that a shared export. We could also duplicate the logic, since this is only used for pre-populating pending transactions.

Another less invasive alternative would be to have `transaction.new` basically assume that the transaction is a key purchase on the paywall, and fake the lock id that is looked for by the `Lock` component. This is a brittle solution, but would work for now.

So the question is do we want to do something more generic inside walletService, or resort to a bit of a hack inside the paywall only in the middleware?

I'm pretty sure the same issue is responsible for the weird behavior of the `LockIconBar` on the creator dashboard as well, otherwise I would just do the paywall solution and forget about it.

Opinions, @julien51 ?

**Comment by cnasc** [comment]
Just to add one more hacky idea: this intermediate state is really just to paper over the hang between when a transaction starts and when it first gets mined. So the solution could be entirely local to the button: once you click submit, it renders the pending state until something else (error, mining success) happens to change it.

That doesn't tackle the `LockIconBar` problem, of course.

**Comment by cellog** [comment]
that is probably the simplest solution, thanks Chris

**Comment by cellog** [comment]
this is fixed
