### ISSUE TITLE
Add transaction type to walletService._sendTransaction()

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2300]
In order to implement an immediate state change for transactions, it would be great if `walletService._sendTransaction` accepted a 3rd parameter, which would simply be the type of transaction initiated. This can then be passed to the `this.emit('transaction.pending')` as a 2nd parameter, which would set the transaction type, and allow immediate updating of the UI to show that the transaction has started.

**Comment by julien51** [comment]
That's probably indeed a good idea! Want to work on that?

**Comment by cellog** [comment]
sure
