### ISSUE TITLE
refactor transaction types shared between the services

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2306]
In order to both share the transaction types between the wallet and web3 services, as well as to export for use in the UI, these should be refactored. Possibilities include putting them into their own file, and also providing some kind of abstraction layer over them (like a function for comparing a transaction to a status)

**Comment by julien51** [comment]
So they will be extracted in the unlock-js library... BUT we should not require/expect the front end to use the same. Each application could have its own mapping of them.
