### ISSUE TITLE
Asking to sign a lock name when rejecting lock creation

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#2322]
When a user creates a Lock, they are being asked to confirm the transaction using their web3 provider (metamask..). If they click on "reject", they are still asked to sign a message to name the lock.

We should not ask users to sign messages when the lock is not going to be created.

**Comment by akeem** [comment]
This was resolved previously in the following pull request: https://github.com/unlock-protocol/unlock/pull/1528
