### ISSUE TITLE
Use locksmith to load the lock on the paywall?

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2323]
We use locksmith to load locks almost instantly in the dashboard. Would it make sense to enable this as an "optimistic lock load" in the paywall? Then we can display locks as soon as the page loads, improving the user experience. This issue is intended as an exploration to ask the question and is low priority

**Comment by julien51** [comment]
Before we explore off chain optimizations, I think there is a lot we can do on the paywall itself.
Let's make sure we go as far as possible on that front, before involving locksmith.
