### ISSUE TITLE
add the paywall to Chromatic QA

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2345]

**Comment by cellog** [comment]
we use `addDecorator` to set global styles in each repo. It's unclear how to do this once we are creating a global storybook, there is a message out to Chromatic support.

**Comment by cellog** [comment]
Chromatic says we should do 2 separate processes for this, one for paywall and one for unlock-app. Only the admin user can set up a new thing, so assigning that portion to Julien

**Comment by julien51** [comment]
After discussing this it looks like this is not possible until after ChromaticQA supports mono repo :(
