### ISSUE TITLE
mobile design for optimistic unlocking

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2352]
Need a mobile look for optimistic unlocking on the paywall.

**Comment by smombartz** [comment]
@cellog for the user (paywall) or creator (dashboard) view? for creator we currently don't support the embed code view on mobile, which also includes the optimistic unlocking options. so i would say thats not an option on mobile.

**Comment by cellog** [comment]
paywall view is what I was referring to, sorry for being unclear, I'll update the description

**Comment by smombartz** [comment]
mobile paywall is here: https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Unlock-Paywall?node-id=76%3A296

should be exactly same as desktop – i.e. the flag already exists in the desktop version. makes sense? unless im missing something desktop should port easily to mobile.
