### ISSUE TITLE
Key purchase succeeded, paywall does not dismiss if key is expired during confirmation process

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2360]
When purchasing a key from https://www.ouvre-boite.com/members/ while demoing the product, discussion during the demo resulted in more than 5 minutes between key purchase and dismissing the modal. Since the lock is set to 300 second expiration, by the time it was clicked, the key was expired, and the paywall would not dismiss when clicking the modal to dismiss it.

There are 2 things to consider here.

1. the paywall could probably detect keys that expire during the confirmation process and display something
2. the paywall could display something letting the user know that their key has expired

**Comment by julien51** [comment]
@cellog I think both of these approach are good.
Generally we should show a message to users indicating that they previously had an expired key.
