### ISSUE TITLE
Brave mobile crashes on attempt to access localStorage

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2366]
![Screen Shot 2019-03-27 at 10.15.00 AM.png](https://images.zenhubusercontent.com/5c7807999546cc1a88f4f864/93e805e7-64b6-48bf-b728-54fe03352cc0)

**Comment by cellog** [comment]
This call to localStorage is inside the `web3` library. This is the same issue from #1154, but on the new mobile client.

**Comment by cnasc** [comment]
Interesting, so this is still something that should be fixed by upgrading Web3?

**Comment by cellog** [comment]
probably. I need to load a local copy of stuff in brave browser to verify the path isn't in our code, but I will do that soon, fixing higher priority stuff first

**Comment by cellog** [comment]
cannot reproduce with current master, this may not be an issue any longer. Did find another bug, though. Going to open an issue

**Comment by julien51** [comment]
Brave does not have a web3 wallet anymore by default. We should then ignore it.
