### ISSUE TITLE
unlock-js needs to be included in global npm ci

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2375]
`npm ci` from `unlock` does not include the `unlock-js` directory in its work, so missing dependencies are not installed.

**Comment by julien51** [comment]
Hey, could you clarify why it needs to be installed in the global npm ci and not just in each of the application which uses it?

**Comment by cellog** [comment]
because its deps are not installed when you do:

```
cd unlock/
npm ci
```

so a fresh checkout of the repo doesn't work
