### ISSUE TITLE
Script to perform smart contract upgrades

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#2467]
We currently perform smart contract upgrades on rinkeby and mainnet manually following this well written guide: https://github.com/unlock-protocol/unlock/wiki/Smart-Contracts-Deployments-and-Upgrades

In order to decrease the risk of doing this manually we should write a script to automate upgrades.

**Comment by nfurfaro** [comment]
Closing for now as this doesn't actually gain us much. 
>So, regarding scripting of our upgrades:
to upgrade manually, we would have to first checkout the correct commit from when the latest npm package was published (as noted in the package description).
Then using the zos cli (from inside the smart-contracts directory)  run:
1.)`npm -- zos session --network rinkeby --from <proxyAdmin> --expires 3600
2.) `npm -- zos push`
3.) `npm -- zos update Unlock`
If this is scripted, we still have to:
a.) remember to checkout the correct commit.
b.) pass the correct network to the script.
c.) pass the correct proxyAdmin address to the script.

Not sure how much we’re actually gaining here by scripting this, as it seems that the potential for mistakes is not much different from the manual process.
