### ISSUE TITLE
ReadTheDocs documentation

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#2482]
**Is your feature request related to a problem? Please describe.**
It's a little intimidating jumping into Unlock today.  

**Describe the solution you'd like**
Use ReadTheDocs to document everything both end-users and Lock creators may potentially want to know.  This would include describing the contracts ABIs as well as how to integrate any JS solution we offer.

**Describe alternatives you've considered**
This is comparable to using markdown on GitHub, however ReadTheDocs is a more user friendly experience.

**Additional context**
ReadTheDocs supports .rst, .md, and can generate from source code comments.  I recently used .rst and that seems like a good option.  It provides flexibility to design the site beyond what markdown can do and allows us to add narrative to help readers that may be overkill in the source code itself.

The downside is redundancy... the line between what information is in ReadTheDocs and/or inline comments is not clear.  I would prefer limiting comments to dev / implementation specific notes and move all the explanatory text to ReadTheDocs only... however I could see an argument for copy pasting the data both places... (in which case maybe we should research generating from source more..)

For example, see Solidity's documentation
 - Experience: https://solidity.readthedocs.io/en/v0.5.7/
 - Source: https://github.com/ethereum/solidity/tree/v0.5.7/docs

**Comment by benwerd** [comment]
I actually set up ReadTheDocs earlier in Unlock's life, but we chose to standardize on the wiki here on GitHub. I think the source code argument is good, to be honest - the code itself is definitely intimidating to get into, and we don't have a great overview of it. As a stopgap, it might be worth creating more of a map in the wiki itself.

**Comment by hardlydifficult** [comment]
Yea I brought this up on a call recently.  I picked this up for another project and am currently a big fan of the .rst option - over wiki or source code generation.  But it's certainly a preference and a big maintenance task for the whole team so we shouldn't switch on a dime.
