### ISSUE TITLE
web3Middleware crashes on key.saved event if account is not set

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2505]
In a race condition, if the `'key.saved'` event is emitted by the read-only web3Service before account has been set, the app crashes, because `'key.saved'` handler assumes the account is set.

**Comment by julien51** [comment]
Please make sure you tag issues : what app is that? Paywall? Also assign a priority ;) Thanks!

**Comment by cellog** [comment]
@cnasc same here, this is a p-0 on the paywall, probably not even a problem on the dashboard, since you can't get to it without having an account first. If it is a dashboard issue, please dupe and assign appropriate priority.
