### ISSUE TITLE
We Need a Consistent Grid

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#2611]
## Description
Currently different pages use different grids and rules, which don't follow the design and creating unsightly inconsistencies. Let's discuss and figure out a way forward. A consistent grid will help us look better but also make dev easier.

![image](https://user-images.githubusercontent.com/1377389/55981621-1ed15b80-5c65-11e9-9471-9ecb276c3c88.png)

**Comment by cnasc** [comment]
Agreed on that. In `unlock-app` there are a few places where we've tried to come up with standard components for reuse, like `LockStyles.js`, but that seems too specific to me. Having a standard set of containers will make development easier, and make it easier for us to replicate @smombartz's designs.

**Comment by smombartz** [comment]
should we carve out the next design review to discuss this? and/or should @cellog and @cnasc and I come up with a proposed plan?
