### ISSUE TITLE
Adjust design on WalletService & Web3Service

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#2612]
**Is your feature request related to a problem? Please describe.**

Currently Web3Service and WalletService have some artifacts that reflect its design inside of the creator dashboard.  Outside of this context the some of interface is a bit weird. 

**Describe the solution you'd like**

I believe that we should be able to eliminate the need to implicitly call `connect` when using the WalletService.  While I am not sure that the scenario of network changing applies directly to the library we should be able to enqueue and dequeue request appropriately when in the intermediate state.

**Comment by cnasc** [comment]
👍

**Comment by akeem** [comment]
Bumping this, current portions of web3 and wallet service assume that the caller will have an event listener listening and available in order fo fulfill the intended behavior. This isn't exactly clear and may not reflect expectations. 

We should split the library in two adding a layer explicitly for publishers

**Comment by cnasc** [comment]
Do you have a sketch of how that would work? Like an explicit pub/sub rather than just throwing things into the ether/looking out into the fog for relevant actions?

**Comment by cellog** [comment]
One easy change, which would be a good first step, is to have the lower layer all promise-based. We should always return a value from our async methods, and some do not, but only emit.

The higher layer could simply call the promise-based methods, and emit the events that should be emitted when the promises resolve.

This design would be similar to how ethers works, versus how web3 works. web3 uses promises that emit events, which is much harder to work with, but having a strict separation between the two layers (event emitter simply responds to promises) would be easy. The nice thing about this design is the event emitter layer could easily tack on `.then()` to do the emitting and simply pass on the returned values.

**Comment by akeem** [comment]
@cnasc good question, I am thinking a core library that explicitly returns values and a layer on top of that publishes.  An example would be something like currently Web3 service's getLock method doesn't actually return anything but publishes an event. 

Something along the lines of what @cellog proposes makes sense
