### ISSUE TITLE
Allow the transferFee to be pre-paid

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#2647]
**Is your feature request related to a problem? Please describe.**
If a transfer fee is enabled, as it is by default, it must be paid when the transfer occurs.  However if a contract currently holds the key - this may not be possible.  So if a key is sent to a contract the user may be unknowingly burning that key.

**Describe the solution you'd like**
Allow anyone to pre-pay the transfer fee for a key.

And if you pre-pay, there should be a way to refund that if I decide to keep the key or cancelAndRefund instead.

**Describe alternatives you've considered**

**Additional context**
Unfortunately this will raise gas costs to createLock and to transferFrom.

**Comment by julien51** [comment]
I think this is not relevant anymore as we're moving toward time based fees.
