### ISSUE TITLE
contract deploy uses more gas than we allow in unlock-js/deploy

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2754]
as seen in this dump from `npm run dev` inside `unlock-app`, we use too much gas (more than 300000):

```

  Transaction: 0x280e65631d5bd777f3260945f4469acc82cf4012032388690a92c4f24ebdc11e
  Gas usage: 3053213
  Block Number: 21
  Block Time: Thu Apr 18 2019 23:13:15 GMT-0400 (EDT)

```

To fix, I propose allowing passing in the gas used for contract creation, so we don't have to release a new version of unlock-js just to increase the gas cost

**Comment by hardlydifficult** [comment]
To clarify, this is for the createLock right?

Maybe use the limits set here: https://github.com/unlock-protocol/unlock/blob/master/unlock-js/src/constants.js#L1

I'm working on a new gas report which will log in CI approximate usage requirements.

The current version prints a few critical calls, the new one will print all of them (hoping to PR that today).  Note that actual usage may be a little higher than these numbers.

Open a recent CI build of the `smart-contract-tests` and see the `gas usage report` which currently appears after compile, before tests.

hth
