### ISSUE TITLE
Lock Creation transactions stuck in "Submitted" state

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#2757]
**Describe the bug**
On the creator dashboard, some transactions always show as "Submitted". We need to investigate that and fix it.

**To Reproduce**
This is visible on staging, if you have already created some locks you should see 1 or 2.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/9300702/56426341-f8737780-6285-11e9-8b5e-68d0786e0dbb.png">

These lock creations also have some missing data in Redux:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/9300702/56426376-2789e900-6286-11e9-9602-2c125a262bcb.png">

I believe that the transactions which only have hashes are in that state because of unrelated contract issues, but the two with additional metadata are the locks in the screenshot above.

**Comment by cnasc** [comment]
I am so far unable to reproduce this locally

**Comment by cellog** [comment]
The bug is one I have seen many times, including locally. It seems it is caused by the lock address guesser guessing that the lock will be the next value. In other words, if you were to refresh and create another lock, it would have address `0x0250...`

**Comment by cnasc** [comment]
Not sure if we're talking about the same thing, these locks persistently show in this state, not just temporarily after creation

**Comment by cellog** [comment]
ah, even on refresh you see 2 locks?

**Comment by cnasc** [comment]
Yep

**Comment by cnasc** [comment]
Aha. Contract fix has deployed, which cleared up a number of things. Now there is only one lock stuck at "Submitted" and here's why:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/9300702/56428713-5c01a300-628e-11e9-9c4d-d5a53ba6f300.png">

Two transactions for the same lock.

**Comment by cnasc** [comment]
This *may* be resolved
