### ISSUE TITLE
Allow creation of locks with key validity smaller than 1 day

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#2787]
This will be very useful for test (may not be quite as useful for users...) We may want to only enable that with some kind of flag.
@smombartz Want to design that form where the user can pick between days, hours or even minutes? Anything less than 1 minute is probably not very useful given the inherent mining latencies.

**Comment by smombartz** [comment]
My original idea was to make the word Days clickable and cycle through the options – elegant but a bit hidden. if its too hidden i can come up with a dropdown/menu view.

![Screen Recording 2019-04-23 at 11 53](https://user-images.githubusercontent.com/1377389/56596440-90db6600-65be-11e9-93c9-b4c40e8e8c38.gif)

**Comment by cellog** [comment]
For accessibility, I recommend we use a select

**Comment by julien51** [comment]
Closing for now as stale.
