### ISSUE TITLE
Ticket App Does not Show Barcode on Complete

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#2865]
# Description
Ticket app does not show the QR code once the purchase is complete.

# Screenshots
![image_from_ios](https://user-images.githubusercontent.com/1377389/56702261-236c2a00-66d1-11e9-91f6-2e7df08ceaa4.png)

# Environment
- iOS
- Coinbase Wallet
- iPhone X

**Comment by benwerd** [comment]
I bet this is an issue with how the different wallets sign data requests. Will look into it, but unlikely to be resolved tonight realistically.

**Comment by akeem** [comment]
I think you are right, we will need to dive in here a bit to determine why. Looking at the redux state on Opera I see the following 

```{
  type: 'error/SET_ERROR',
  error: 'FAILED_TO_SIGN_ADDRESS',
  data: {
    code: -32600,
    message: 'invalid json request'
  }
}```

**Comment by julien51** [comment]
I think this is fixed now?
![Uploading image.png…]()

**Comment by julien51** [comment]
<img width="2071" alt="image" src="https://user-images.githubusercontent.com/17735/57243298-cabb5c00-7003-11e9-8daa-9987b5967de0.png">
