### ISSUE TITLE
Tickets app does not warn on insufficient funds

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#2867]
**Describe the bug**
The paywall will change the purchase button to a disabled state and indicate that the purchaser does not have enough eth to buy a key if the purchaser's balance is less than the price of the key. The tickets app does not offer the same warning, but it should.

**To Reproduce**
1. Go to an event page
2. Have a wallet with less eth than the price of the ticket
3. Note that it looks like you can still buy a ticket

**Expected behavior**
The button will indicate that you don't have enough eth to pay for the ticket.

**Screenshots**
![image](https://user-images.githubusercontent.com/9300702/56738272-44b53080-673a-11e9-806e-b99d8e606ca1.png)

(paywall for contrast)
![image](https://user-images.githubusercontent.com/9300702/56738299-526ab600-673a-11e9-92d7-1f4ffabdfbfb.png)

**Additional context**
This is not 100% critical, as MetaMask itself will indicate that funds are insufficient when it pops up, but the UX would be nicer if we could save a click and just present that information.

**Comment by cnasc** [comment]
Adding @smombartz for the design!

**Comment by smombartz** [comment]
design for that is here @cnasc 
https://www.figma.com/proto/bladzEkGVK14JI52xukIDc/Unlock-Tickets?node-id=497%3A1037&viewport=821%2C-2740%2C0.784978&scaling=min-zoom

**Comment by cnasc** [comment]
It looks like tickets doesn't update the account object in the redux state with the user's balance. Fixing that will be a prerequisite for this, and should probably be done in tandem with any handling of ERC20 balance.

**Comment by cnasc** [comment]
This will no longer be a problem when we start using the paywall-based events page so I'll close this.
