### ISSUE TITLE
Adding image/logo to events page

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#2870]
We need to let the event creator add an image on their event page. Let's just allow them to use a "large" one (up to 600x 600px?) which we can scale down on mobile?

For this, we need to save the image using locksmith (S3) and be able to keep track of the location using the events table.

**Comment by akeem** [comment]
Based upon today's standup we have decided to utilize Cloudinary for image uploads on the front end (https://cloudinary.com/documentation/node_integration#quick_example_file_upload)

**Comment by julien51** [comment]
A couple links worth looking at:
- their JS library https://github.com/cloudinary/cloudinary_js
- a component which can do drag and drop uploads and more https://react-dropzone.js.org/

I think the workflow would be this:
- Use DropZone to let the user add their image/logo
- Use cloudinary to save the image file to an s3 bucket we own
- Save the image hash/filename in the events object in locksmith.

**Comment by julien51** [comment]
Sorry for the very late follow up on this BTW...
