### ISSUE TITLE
Difficulty purchasing keys from Tickets application (verification)

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#2955]
**Describe the bug**

There appears to be a bug or two making it difficult to purchase keys for an event in development when the purchaser is not the event creator. 

The use of the HTTP provider may be masking that the issue exist. 

**To Reproduce**

1. start the application in development
2. create an event
3. Using a secondary browser 
   1. user metamask
   2. Import the private key of an address from the readme of unlock-app that is not associated 
        with the event creation.
   3. Visit the event page
   4. Ensure that Metamask is being used.
   4. Attempt to purchase the ticket

**Expected behavior**
1. The event page should load
2. If the account is not correctly set it should signal to the user that the purchase cant be made
3. If the account is correctly set, the user should be able to purchase the ticket.

**Comment by julien51** [comment]
@akeem could you explain a bit more about what is happening exactly?

**Comment by akeem** [comment]
@julien51 absolutely, it looks like the page fails to load properly when the provider isn't set to the HTTP  provider. If I remove the HTTP provider from the  configuration the page loads but fails on purchase

**Comment by julien51** [comment]
After investigating it looks like there is indeed a bug when changing provider.

**Comment by akeem** [comment]
This has been resolved, closing.
