### ISSUE TITLE
Lock stays on top

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#3014]
Both on my account and @cnasc 's account there is a lock which is stuck at the top of the list even though it is not the most recent.
It may be missing a transaction. 

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/17735/57231308-50311300-6fe8-11e9-8498-036be8f2f1a8.png">

**Comment by cnasc** [comment]
More detail: the lock that stayed at the top on my page did not have a transaction field, so in the absence of a `blockNumber` it was always sorted at the top. On a subsequent refresh, the transaction field was present and the lock was in its proper place in the list. This may be an issue with fetching data.

**Comment by julien51** [comment]
Closing for now as stale.
