### ISSUE TITLE
Optimistic unlocking flag grammar

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#3017]
**Describe the bug**
Once the date format changes to be a duration rather than an expiration date, the wording is stilted.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/9300702/57231821-4fe54780-6fe9-11e9-8d46-53573913878b.png">

**Expected behavior**
In this case I would expect to see something like "Valid for 10 seconds"

**Comment by julien51** [comment]
Closing as stale/not applicable anymore.
