### ISSUE TITLE
Consider removing RevokeOwnership from Unlock.sol

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#3022]
**Is your feature request related to a problem? Please describe.**
By using a standard implementation from OpenZeppelin, we may be including some functions which do not make sense for our use case.  RevokeOwnership is one of those..

**Describe the solution you'd like**
Consider using OpenZeppelin as a guide to create a more targeted Ownership implementation.  And review other dependencies for other functions we don't need.

**Describe alternatives you've considered**
We could also continue to use the standard implementation and then override the functions we don't want to make them revert instead.

**Additional context**

**Comment by hardlydifficult** [comment]
Also applies to PublicLock.  RevokingOwnership would mean burning all funds from sales and transfers.

**Comment by hardlydifficult** [comment]
It may be better to override and block the undesired functions .. as opposed to copy paste the desired ones.

**Comment by nfurfaro** [comment]
Closing as redundant with #5949
