### ISSUE TITLE
Event email went directly to spam

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#3028]
**Describe the bug**
When requesting the event email, it has gone into my spam folder

**To Reproduce**
User the staging service request event email

We can probably resolve this by updating the sending email address of this event. It may be worthwhile to add email open rate as an operational metric here.d

**Comment by cnasc** [comment]
This will likely also be an issue with account confirmation emails.

**Comment by benwerd** [comment]
We need to add signing to the DNS. Because that likely conflicts with our own use of Google Apps, I wonder if we need to have a different domain or subdomain for unlock account emails, eg no-reply@accounts.unlock-protocol.com.

**Comment by julien51** [comment]
I was able to setup DKIM using SendGrid and AWS Route53 with no conflict! This is good!
