### ISSUE TITLE
Display remaining number of tickets

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#3034]
While probably not in the original design, we should display the remaining number of tickets to the event. 

1. It will signal to potential attendees how quickly the need to act
2. It will ensure that popular events are not over subscribed.

**Comment by julien51** [comment]
Since we moved to using the paywall for the tickets app, this means the paywall would need to serve that info back to the window which embeds it.

**Comment by julien51** [comment]
@smombartz Maybe worth looking at as part of your re-design for the paywall? I think that would be a cool addition!

**Comment by smombartz** [comment]
@julien51 here a first pass on the number of tickets left. there are two version first one only shows available tickets. below that is one that shows available of total number (in case we decide thats better), though I think just available number is good.

<img width="530" alt="Screenshot 2020-02-06 at 16 05 29" src="https://user-images.githubusercontent.com/1377389/73974384-a544e100-48fa-11ea-8a87-ec9fdf79e6d4.png">

**Comment by julien51** [comment]
@cnasc This will be useful in the context of your work on the checkout page ;)

**Comment by akeem** [comment]
closing as this was related to the older tickets design. This has been built into the paywall component to some extent
