### ISSUE TITLE
Remove confirmed button for ticket holders in exchange for a larger QR code in mobile

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#3057]
On the Events page, we provide those that have purchased tickets with a non-interactive button labeled 'Confirmed'. The relevant QR code is provide below. 

I'd like to propose replacing the button, as it provides low signal in this case and increasing the size of the QR code. 

While functionally the same, it should provide a slightly better experience for mobile users

**Comment by julien51** [comment]
We moved signing to the unlock keychain!
