### ISSUE TITLE
Wallet overlay when waiting for the user to "enable"

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#3093]
We have a cool overlay which pings the user to check their wallet when doing transactions... we should do the same thing when waiting for them to sign or when waiting for them to enable the provider!

**Comment by cnasc** [comment]
For some context: this is as simple as dispatching `waitForWallet` before a signature request or an enable, and then dispatching `gotWallet` afterwards (in both success and failure cases)

**Comment by cnasc** [comment]
And given #3136, it will be pretty easy for us to provide specific messages for specific contexts if we'd like to

**Comment by julien51** [comment]
cc @cnasc
