### ISSUE TITLE
production tickets is broken

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3098]
I just bought my ticket to the nft meetup, and the page froze on "Payment sent". Investigating further yielded the following:

<img width="1384" alt="Screen Shot 2019-05-09 at 8 58 34 AM" src="https://user-images.githubusercontent.com/98250/57455277-cb890380-7238-11e9-9f5f-a7864ae03850.png">
<img width="1604" alt="Screen Shot 2019-05-09 at 8 57 39 AM" src="https://user-images.githubusercontent.com/98250/57455278-cb890380-7238-11e9-844a-525940737ebc.png">

This is in web3Service:

```js
  async getTransaction(transactionHash, defaults) {
    return Promise.all([this.provider.getBlockNumber(), this.provider.getTransaction(transactionHash)]).then(async ([blockNumber, blockTransaction]) => {
      // Let's find the type of contract before we can get its version
      const to = blockTransaction ? blockTransaction.to : defaults.to;
 ```

The `defaults` array does not have `to` set in it!

The defaults is set in web3Middleware:

```js
        // When a new transaction was created, retrieve it
        if (action.type === NEW_TRANSACTION) {
          web3Service.getTransaction(
            action.transaction.hash,
            action.transaction
          )
        }
```

This is totally standard, the paywall does the same thing. The `NEW_TRANSACTION` action was dispatched from:

```js
    walletService.on(
      'transaction.new',
      (transactionHash, from, to, input, type, status) => {
        // At this point we know that a wallet was found, because a new transaction
        // cannot be created without it
        dispatch(gotWallet())
        dispatch(
          newTransaction({
            hash: transactionHash,
            to,
            from,
            input,
            type: transactionTypeMapping(type),
            status,
            network: getState().network.name,
          })
        )
      }
    )
```

This implies that `walletService` sent out a `'transaction.new'` event without a filled in `to` field. However, the state is correct:

<img width="811" alt="Screen Shot 2019-05-09 at 9 06 03 AM" src="https://user-images.githubusercontent.com/98250/57455700-ba8cc200-7239-11e9-80e7-003d829b4991.png">

Unfortunately, the redux action that was the basis of this scrolled away before I figured out I needed to look at it.

**Comment by julien51** [comment]
I think the `to` thing might be a different bug. Probably a transaction from locksmith on a different chain rinkeby vs. mainnet.

**Comment by cellog** [comment]
I saw the same error with a new event I created on staging in coinbase wallet
