### ISSUE TITLE
KeyChain page/login flow not available when there is no wallet available

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#3124]
The flow works as expected if/when the user has metamask installed but is logged out. However the  user received a wallet needed error message when there isn't a wallet available. 

Reproduction:
Visit `https://staging-app.unlock-protocol.com/keychain/` using Safari

Expected behavior:
Visit `https://staging-app.unlock-protocol.com/keychain/` using a browser with metamask installed but a logged out user

**Comment by cnasc** [comment]
I think we aren’t able to fix this until we have unlock-provider up and running—the alternative would be to disable the warning. But good catch, we’ll have to take care of that once accounts are ready for prime time
