### ISSUE TITLE
Locksmith needs to support lock addresses in the tokenURI

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#3157]
**Is your feature request related to a problem? Please describe.**
In order to support both custom metadata on a per-lock or per-key basis, as well as default metadata for locks/keys, the `tokenURI` function (in `PublicLock.sol`) returns the global base token URI (`https://locksmith.unlock-protocol.com/api/key/`) as well as the address of the lock and the `tokenID`.
A complete URI looks like this:
`https://locksmith.unlock-protocol.com/api/key/0x5543625f4581af4754204e452e72a65708708bc2/1`
 , but it fails to return the correct json:
```
Cannot GET /api/key/0x5543625f4581af4754204e452e72a65708708bc2/1
```
However, without the lock address it works fine, as `https://locksmith.unlock-protocol.com/api/key/1` works fine:
```
{
  "description": "Test metadata for Unlock protocol",
  "image": "https://raw.githubusercontent.com/unlock-protocol/unlock/master/unlock-app/src/static/images/unlock-word-mark.png",
  "name": "Lock Metadata Test"
}
```

**Describe the solution you'd like**

For now, I think we need to return the default json for all requests, regardless of the lock address or tokenId. The lock address is important because the tokenID on its own is not globally unique. We should review the data as well, and modify it to better represent the unlock-protocol.
•`description` could be something common to all locks or keys, like "A key to a Lock contract built on the unlock-protocol, a general-purpose blockchain-based access-control protocol. https://unlock-protocol.com/"
•`name` could be "Unlock-Protocol Key"? 
•`image` would look better if we used a round logo perhaps? ![image.png](https://images.zenhubusercontent.com/5c780ecd04004e3ba48b96d4/abff7ea2-918e-409a-9d5e-a4286d00a384)

**Comment by julien51** [comment]
Thanks @nfurfaro ! @akeem Could you add that support in between other stuff you're working on?

@smombartz Could you provider us with a large round PNG for the logo which can be easily used as the default icon on the NFT? (or maybe something else which looks like a key?)

**Comment by nfurfaro** [comment]
I also like the idea of an unlock-logo with a key shape or theme...(but didn't wan't to complicate things too much).

**Comment by akeem** [comment]
Yes, I'll work on this as soon as I done merging in some of the stuff I have in play
