### ISSUE TITLE
Add a util in unlock-js to re-encrypt a wallet

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#3170]
**Is your feature request related to a problem? Please describe.**
Part of the password change piece of user accounts. We need a way to go from a decrypted private key to one that is encrypted with a new password.

**Comment by cellog** [comment]
use this https://github.com/ethers-io/ethers.js/blob/master/src.ts/wallet.ts#L107

**Comment by cnasc** [comment]
Thanks!
