### ISSUE TITLE
comment all the tests in unlock-js that use nock to warn not to use beforeEach

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3187]
because `nock` modifies global state by mocking the core http access, we cannot do any nock setup or teardown in jest's `beforeEach`.  This causes tests to be flaky, etc. etc.

The current tests all use a clunky but effective `nockBeforeEach` which encapsulates all the nock setup calls, and especially any actual blockchain calls during setup. The function must be `await`ed at the start of each test that uses it.

We need to document why this is necessary in each test file, as future devs will be certain to think "that should live in a `beforeEach`" otherwise

**Comment by julien51** [comment]
I think this is NA anymore.
