### ISSUE TITLE
if user has metamask, but is logged out, dashboard is a blank page

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3230]
**Describe the bug**
If the user is logged out of metamask, but has the extension, the dashboard loads without error, and no content.

**To Reproduce**
1. Log out of Metamask
2. Go to https://unlock-protocol.com/dashboard
3. See error

**Screenshots**
<img width="1667" alt="Screen Shot 2019-05-16 at 12 12 04 PM" src="https://user-images.githubusercontent.com/98250/57869832-dfea7480-77d3-11e9-9ba7-db6a01b7d9e6.png">

**Comment by cnasc** [comment]
Just to provide the current state of the art:

- We check that a user has a wallet
- We check that the wallet is on the correct network
- We do not check that the wallet is actually active (apparently calling `enable` on MetaMask while not signed in does not prompt a sign-in request)

**Comment by cellog** [comment]
The same issue occurs if you are on the wrong network - is the error component disabled altogether on the dashboard?

**Comment by cnasc** [comment]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/9300702/57944537-4b504700-78a5-11e9-8079-d1ee2fc066d7.png">

The error only shows up if you are logged in on the wrong network

**Comment by julien51** [comment]
I think this is just another instance of https://github.com/unlock-protocol/unlock/issues/3093
Closing in favor of that other issue.
