### ISSUE TITLE
Show truncated balances

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#325]
The balance on accounts is showing too many numbers. We need to only show relevant decimals.
If the user has more than 1Eth, let's show only 2 decimals.
If the user has less than 0.0001 Eth let's show ` < 0.0001` (about 2cts at current prices).
For anything in between, let's show at most 2 non zero values.

**Comment by hasparus** [comment]
I could give it a shot tomorrow.

**Comment by julien51** [comment]
As a follow up, this component can and will be reused in other places of the applications. Here are 2 places:
<img width="358" alt="screen shot 2018-10-16 at 14 21 17" src="https://user-images.githubusercontent.com/17735/47038166-cd7d5f00-d14e-11e8-9dc2-af8fb304e37f.png">
<img width="139" alt="screen shot 2018-10-16 at 14 21 12" src="https://user-images.githubusercontent.com/17735/47038167-cd7d5f00-d14e-11e8-8b2b-19dae45fcac1.png">

**Comment by julien51** [comment]
Merged! Thanks @akeem !
