### ISSUE TITLE
Automatically build and publish Unlock.js

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#3270]
To avoid people manually build and publishing unlock.js themselves and de-risk all of the issues associated with this we should setup an automated pipeline to build and publish each release of the library. 

A secondary setup can be folding the changelog into the readme prior to each release.

**Comment by julien51** [comment]
Yes I am in string favor of that! We can probably require to update the changelog when submitting  a PR which bumps the version in package.json!

**Comment by julien51** [comment]
Maybe we should give a shot at github actions for this?

**Comment by akeem** [comment]
i'll look into this tomorrow

**Comment by julien51** [comment]
I think the recent changes made by @clemsos almost cover this? At least for us. 
Closing for now!
