### ISSUE TITLE
Apply a cohesive design to the modal components

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#3273]
**Is your feature request related to a problem? Please describe.**
Review of #3272 brought up that the modal templates currently in place don't quite fit with our established design, so we should take some time to apply a consistent design to those. They all use shared components for the most part, so it should be pretty easy to update them all to look a little nicer.

**Comment by smombartz** [comment]
@cnasc can you list the different types of modals and describe where they live/show up?

i see there is a pw change modal in #3272.

generally i think modals should be avoided if possible. they aren't very user friendly and problematic in responsive designs.

**Comment by cnasc** [comment]
We have 3 kinds at the moment:

1. Wallet check (overlay that tells user to look at metamask to approve transaction)
2. General password prompt (for when we need to decrypt their account to perform a transaction)
3. Password reset

The first 2 definitely have to be modals, maybe the third can go on its own page

**Comment by smombartz** [comment]
@cnasc these should all be accounted for now, see [keychain](https://www.figma.com/file/ZIhu6WMu781dsGDHszPKb1UT/Keychain?node-id=1%3A17) and [paywall](https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Paywall?node-id=179%3A0) figma files
