### ISSUE TITLE
split web3Service.test.js

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3317]
The `web3Service.test.js` file in `unlock-js` is quite bulky.

Splitting it will make reasoning about the tests simpler.

There are a couple of approaches to consider. 1 would be making a directory `web3Service` and making a file for each function that we are testing. This is a big change, and maybe worth considering for long term.

For short term, I think the best thing we can do is to split off all the contract-version-specific tests into a separate file. This will make upgrading the smart contract simpler, as there will be 1 place to modify. This would mean 2 files: `web3Service.test.js` and either `web3Service-versions.test.js or `web3Service/versions.test.js` (no strong opinion about naming from me)

**Comment by julien51** [comment]
Closing as NA/stale.
