### ISSUE TITLE
PublicLock.sol withdrawTo

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#3347]
**Is your feature request related to a problem? Please describe.**
Add the ability to specify which account should receive funds when withdrawing from a Lock.

**Describe the solution you'd like**
Add an address to the existing withdraw function.  

**Describe alternatives you've considered**

**Additional context**
This is RE a discussion on Slack.

**Comment by nfurfaro** [comment]
A couple thoughts on this:
Along the lines of making it simple to manage locks for non-crypto savvy users, the address to use for `withdrawTo` could be set in storage. The benefit here being it can be set once and confirmed by a second part once(maybe even Unlock in the Forbes example) as opposed to passing the address in each time a withdrawal is desired, which multiplies the chance for errors.
Also, we could consider adding a "switch" in the lock, like `bool autoWithdrawEnabled`. When set to `true`, Any address can call the withdraw function, and the funds will go the the address which was previously set. This could allow a dapp to be built for the sole purpose of calling this function (from any address) on a schedule, enabling automatic scheduled withdrawals.
