### ISSUE TITLE
We need to set the global default metadata on Unlock.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#3388]
Now that we've upgraded Unlock on rinkeby, the owner (multisig wallet) will need to send a transaction to set both metadata fields. This will need to be done once per network . Optionally, we could hardcode these values and just review them prior to each release/upgrade, and save some gas.
We do this by calling `setGlobalTokenSymbol()` & `setGlobalBaseTokenURI()`
symbol: `KEY`
URI: `https://locksmith.unlock-protocol.com/api/key/`

**Comment by hardlydifficult** [comment]
This was done for both testnet and mainnet.  Re-open if I overlooked something.
