### ISSUE TITLE
clicking on cancel breaks :/

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#344]
When creating a lock, if the user clicks on cancel, the form goes away but the UI also breaks:
<img width="1071" alt="screen shot 2018-10-12 at 14 18 56" src="https://user-images.githubusercontent.com/17735/46886765-cb06c680-ce29-11e8-99c1-cc1e98e44b81.png">

**Comment by julien51** [comment]
I think this is because the lock creation is also triggered ;)

**Comment by benwerd** [comment]
Ugggh. I think I need to revert to what I was using before preventDefault. Sorry about that.

**Comment by julien51** [comment]
This was fixed! Thanks @benwerd !
