### ISSUE TITLE
"wallet missing" design and text needed

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3457]
When a user does not have a crypto wallet, the Ad remover paywall needs to recommend a wallet. We need copy (@julien51) for what to say, and a design (@smombartz) for how to lay it out for both desktop and mobile

I'm using https://www.figma.com/file/EZ4mtBKGj54EQCQvYDArtqKs/Forbes-Crypto-Blockchain?node-id=1%3A166 as a reference

**Comment by smombartz** [comment]
what wallets do we want to suggest?

**Comment by smombartz** [comment]
@cellog @julien51 here a quick first draft: https://www.figma.com/file/EZ4mtBKGj54EQCQvYDArtqKs/Forbes-Crypto-Blockchain?node-id=298%3A18

**Comment by smombartz** [comment]
updated design (including svg icons)
https://www.figma.com/proto/EZ4mtBKGj54EQCQvYDArtqKs/Forbes-Crypto-Blockchain?node-id=1%3A12&viewport=3102%2C-722%2C1&scaling=min-zoom
