### ISSUE TITLE
Structuring data in our Redux application

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#349]
This is not a feature request per se, not it is a bug report. It's a very high level spec on how to handle data in the react/redux application.

First of all: the blockchain is the source of truth (that's probably obvious). This means that transactions are the "atomic" unit of data. Each transaction may then include references to other objects.

Secondly it is important that all other objects are immediately created on the front end, without necessarily having been stored (or even been sent) to the backend. This is important to provide immediate feedback to users.

When loading the application, we should "refresh" the state of each transaction and update/build the corresponding objects.

**Comment by julien51** [comment]
Our application should listen to all changes in transactions and update the layout based on this, not on changes in the objects themselves. Since the transaction include pointers to the objects themselves, when the transaction has been updated, the corresponding objects are changed.

**Comment by kphed** [comment]
An in-depth conversation about the flow of data and the different types and pieces of data within the app would be extremely helpful in coming up with a useful spec.

>Secondly it is important that all other objects are immediately created on the front end, without necessarily having been stored (or even been sent) to the backend. This is important to provide immediate feedback to users.

Would we be persisting data on the frontend (perhaps using something like LocalStorage from which we will update the app state) in order to display to the user the last known state of the transactions? Or would we be making a request to the API in order to fetch most up-to-date data right off the bat?

**Comment by kphed** [comment]
Got it, I wasn't sure if you were only interested in using some mechanism of storage on the frontend (if you wanted to, you could store data on the mobile devices as well) or if fetching from a database was an option. Thanks for clearing that up! I also want to add that I wasn't addressing the issue as a whole, but specifically, the paragraph that I quoted.

**Comment by julien51** [comment]
I think at some point we'll need to sync the localStorage data on a backend server and then we can use  the user's Ethereum address to load it back into another device.
How would you recommend handling this?

**Comment by julien51** [comment]
Closing this because this probably belongs to the wiki!
