### ISSUE TITLE
Update CI logs for bytecode for version verification

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#3501]
**Describe the bug**
We added a log of the hash of the bytecode in order to allow us to confirm a certain version matches the bytecode expected from a specific commit.

The trouble is ATM I'm getting different results for the same code on different machines.

At first I thought the difference was due to the metadata hash, but after excluding that I'm seeing differences throughout the bytecode.  I'm not sure why.

See also #3331, the branch there was last updated to log the entire bytecode value for testing.

**Comment by hardlydifficult** [comment]
@nfurfaro could you take a stab at this?  I hit a wall and could use new eyes..

**Comment by julien51** [comment]
Status of this one?

**Comment by NickCuso** [comment]
No update - but I've been looking into bytecode a bit more since this was touched last.  I could pick this up to give it another go.

**Comment by julien51** [comment]
We now use hardat and it as a built in verification method.
