### ISSUE TITLE
Update Unlock ENS records to reference Main net & Rinkbey 

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#3521]
As part of removing friction for developers, and making implementation that much easier the project should utilize ENS for the mainnet & rinkbey for the respective contracts. 

Ideally in addition to the .eth address the domain name will be claimed in order to provide callers with confidence that they are indeed interacting with the appropriate contracts

**Comment by cellog** [comment]
also, as a side note, because we are using ethers internally, it supports ENS natively. The only thing we would have to change is the nocks in unlock-js

**Comment by julien51** [comment]
We have `unlock-protocol.eth` pointing to the Unlock contract on main net. I could not find a way to do the same thing on rinkeby :(
