### ISSUE TITLE
Potential refactor for unlock-js v0, v01 etc. directories to DRY it up

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3604]
1. because we duplicate the code for every method, if there is a bug in any, we have to fix it in all, this is a lot of surface area that will only get worse over time
2. there is a clever way to keep things clear and avoid duplication! We can define a handler for a particular *signature*. Thus, `createLock(uint256,address,uint256,uint256,string)` is one signature, `createLock(uint256,address,uint256)` is an earlier version. We define one per sig, and then in the index.js for a version, we import the one we actually use and export that as `createLock`
3. With this idea, the primary question becomes how do we make it clear which signature a function supports? We could put it in the filename, which raises escaping issues with the `()`, we could use a different punctuation for parens, like `-` so `createLock-uint256-address-uint256-uint256-string.js`
4. I would prefer we have directories with the function name, and the sigs are filenames, so `createLock/uint256-address-uint256-uint256-string.js`
this will still allow copy/pasting the version directories

**Comment by julien51** [comment]
I like the idea but not sure that this is good enough. From a version to another, the signature may stay the same but the behavior might change?

**Comment by cellog** [comment]
probably a better solution than this one is to use inheritance.

base class for the contract. The newer version extends the old one, overriding methods that have changed. That way we only need to test the new versions. This assumes the functions are not truly methods, and are isolated from one another (which they would be)
