### ISSUE TITLE
Unlock Discount Token contract

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#3710]
**Is your feature request related to a problem? Please describe.**
New feature

**Describe the solution you'd like**
Implement a ZOS upgradable token contract which allows Unlock.sol to mint tokens.

Implements ERC-777, ERC-20, ERC-1820
Maybe add Unlock.sol as a default operator

Once the token rules are established and trusted, we can `revokeOwnership` for an immutable token.

**Describe alternatives you've considered**

**Additional context**
By separating the tokens themselves from Unlock.sol we can more clearly define the owner controls and aim to remove them overtime.

We can implement this token and then in another task follow up with the minting process, and finally using the tokens to apply a discount.

**Comment by julien51** [comment]
> We can implement this token and then in another task follow up with the minting process, and finally using the tokens to apply a discount.

I think this is right!

**Comment by NickCuso** [comment]
We now have an Upgradable ERC-20 token for the Unlock Discount Token (UDT).

Next step is to fix the GDP calculation, and then we can start minting tokens.
