### ISSUE TITLE
Back button non-functional from lock demo

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#372]
The state doesn't update properly when you hit the back button in the browser from the demo page. You can reproduce this by visiting the demo page for a lock and hitting back.

<img width="1031" alt="screen shot 2018-10-17 at 9 59 03 am" src="https://user-images.githubusercontent.com/624104/47103109-5057f580-d1f3-11e8-9c05-2fb9f6f71116.png">

**Comment by julien51** [comment]
Ho... interesting! Thanks I'll assign it to myself.

**Comment by julien51** [comment]
This does not seem to be happening anymore... closing for now then!
