### ISSUE TITLE
Add renovate-bot to CLA-Assistant whitelist

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#3760]
To start to merge upgrades from Renovate, we need to have CLA-Assistant ignore the renovate-bot user.

https://github.com/cla-assistant/cla-assistant/issues/173#issuecomment-402971323

I'd do this myself, but I think only @julien51 and maybe @benwerd have organization-level access to make this setting

**Comment by benwerd** [comment]
This should now be fixed.

**Comment by ChipWolf** [comment]
@benwerd looks like they use a different user now https://github.com/HRZNStudio/playhrzn-k8s/pull/1
