### ISSUE TITLE
unlockService should verify that a contract is deployed before calling `publicLockVersion` or `unlockVersion`

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3761]
There is a bug in ethers (https://github.com/ethers-io/ethers.js/issues/542) that causes an unhandled promise rejection which surfaced this problem.

Basically, this code:

```js
      const contractVersion = await contract.publicLockVersion()
```

in `unlockService` makes an assumption that the contract has been deployed. The call will throw if it has not, and then our code will assume that we have the earliest `PublicLock` version. We need to add a check for whether the contract is actually deployed prior to calling functions on it to avoid this issue.

**Comment by julien51** [comment]
Could we also assume, it it throws that this means the contract has not been deployed?

**Comment by cellog** [comment]
> Could we also assume, it it throws that this means the contract has not been deployed?

...yes

but it causes an unhandled promise rejection in ethers

**Comment by julien51** [comment]
This is something we could add to `unlock-js`.
