### ISSUE TITLE
Implement “proxyProvider” logic on paywall

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#3767]
Once the iframe has been added to the DOM (#3766) our existing proxyProvider should send messages to it (#3765) to achieve the following:
* Get the current network 
* Get the user account (so that the paywall can check whether the user has keys…)
* Perform key purchases

**Comment by julien51** [comment]
Once the iframe has been added to the DOM (#3766) our existing proxyProvider should send messages to it (#3765) to achieve the following:
Get the current network 
Get the user account (so that the paywall can check whether the user has keys…)
Perform key purchases

**Comment by cellog** [comment]
done!
