### ISSUE TITLE
paywall should only retrieve transactions that are key purchase transactions for relevant locks

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3773]
Currently, the paywall app retrieves all the transactions that locksmith returns. This means we retrieve lock creation transactions, and also key purchase transactions for locks that are not specified in the paywall config.

The paywall should ignore any irrelevant transactions by parsing the inputs and using that to filter out irrelevant transactions

**Comment by julien51** [comment]
Oh! I thought we actually did not do that anymore? (or maybe it is just in the new architecture, so not for the "old" paywall?)
It is actually a big issue for people like use who have done a lot of transactions!

**Comment by cellog** [comment]
@akeem and I discussed perhaps adding a filter on the locksmith endpoint. We can pass a list of addresses and it would filter on the "to" field of transactions. In this way, the paywall could send the list of lock addresses it cares about. This should greatly cull the list of prior transactions.
