### ISSUE TITLE
Intercom not showing up on all pages

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#3777]
# Description
The intercom widget is only showing on on the landing page (or the page thats initially loaded). if you navigate to any other page (from landing to info, blog, jobs) the widget does not show up.

# To Reproduce
1. Go to unlock landing page
2. Click on any sub page (info, blog, jobs)
3. Intercom doesnt show up, unless you manually reload that page

# Expected behavior
Should show up on every page on desktop and mobile

# Screenshots
video here: https://www.dropbox.com/s/e03kuc2c8mdu3z5/190613-intercom-01.mov?dl=0

# Tested on
OSX chrome
iOS chrome

**Comment by cnasc** [comment]
That's peculiar, Intercom is on the `<Layout>` component,  which wraps every static page. Maybe it's there and somehow getting hidden?
