### ISSUE TITLE
Can't edit lock names

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#3783]
**Describe the bug**
Right now it's impossible to edit a lock name - the field doesn't let you click in and edit. This is because the underlying lock contract also doesn't allow you to edit.

Because some locks don't have a name stored, the edit form won't allow you to save, meaning these locks can't be saved at all.

**To Reproduce**
1. Go to Dashboard
2. Edit an existing lock
3. Try to edit
4. You'll find that the lock name can't be edited. If the lock doesn't have a name stored, you can't edit any data in the lock at all.

**Expected behavior**
1. You should be able to edit lock names
2. Even if you can't, you should be able to edit other lock data

**Comment by julien51** [comment]
We should certainly allow users to update the lock names. Let's close this for now as stale though.
