### ISSUE TITLE
consider running multiple ganache instances in integration tests so they can run in parallel

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3847]
If we have one ganache instance per integration test file, it could allow running them in parallel for significant speedup

**Comment by julien51** [comment]
Would you mind elaborating? I would assume that we can actually create transactions in parallel? (multiple transactions would be added a block?)

**Comment by cellog** [comment]
if 2 tests are trying to create a lock/buy a key on the same lock we have potential race conditions, which is why we --runInBand

**Comment by cellog** [comment]
in any case, it would be great if we could run the integration tests in parallel somehow :)
