### ISSUE TITLE
add optimistic unlocking to the Checkout UI

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3864]
although not strictly related to the paywall, this step should be done to make the ad remover paywall app have a flag when the paywall is unlocked

**Comment by julien51** [comment]
I think this one is key ;)

**Comment by cnasc** [comment]
It looks like optimistic unlocking works on the paywall right now, is this issue about optimistic unlocking itself or about having the flag on the side?

**Comment by cellog** [comment]
the flag on the side
