### ISSUE TITLE
Stricter Lint rules

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#39]
The current lint rules are fairly limited. We need a set of much stricter rules.

**Comment by kphed** [comment]
Have you considered enforcing JS coding practices based on an existing style guide? For example, AirBnB's is widely used for good reason and it's regularly maintained and kept up-to-date: https://github.com/airbnb/javascript

**Comment by julien51** [comment]
Hey! Thanks for following up on this issue. Right now we use eslint with a [few defaults](https://github.com/unlock-protocol/unlock/blob/master/unlock-app/.eslintrc.js) but I think we need to tighten things up a little bit. I considered using Airbnb but I am not a semicolon person :/ 
Do you think we could just use AirBnb and tweak a couple rules? Is that good practice?

**Comment by kphed** [comment]
>Hey! Thanks for following up on this issue. Right now we use eslint with a few defaults but I think we need to tighten things up a little bit. I considered using Airbnb but I am not a semicolon person :/
Do you think we could just use AirBnb and tweak a couple rules? Is that good practice?

You could definitely tweak the rules to suit your coding preferences, Julien. It's a good base to start from though.

**Comment by benwerd** [comment]
Worth checking to see if there's a rule about `import` order. It's a bit all over the place right now - and I think it'd be a good thing to enforce if we can. I'll take a look after my current batch of PRs too.

**Comment by julien51** [comment]
^ that PR does have a rule for import orders ;)
