### ISSUE TITLE
Local transactions are not working as expected

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#393]
Confirmation numbers don't seem to coincide with the number of mined blocks on the local chain.

**Comment by julien51** [comment]
(confirmations that is!) web3js triggers confirmations even though no block is being mined which is... odd!

**Comment by julien51** [comment]
I think this is a problem with ganache... So only in Dev.

**Comment by julien51** [comment]
Closing because I am not sure there is anything we can actually do about that ourselves.
