### ISSUE TITLE
GA Event trigger upon Unlock of Slide Show view

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#3971]
With GA in place, we have a chance to receive greater visibility into some of our tests. Would it be possible to trigger an event when Slideshows featured on the Unlock blog are enabled.

An example URL would be something like: https://unlock-protocol.com/blog/non-fungible-tokens-betaworks/

**Comment by julien51** [comment]
I think this could maybe be a larger thing where we trigger GA event based on when the page is locked/unlocked by default inside the new paywall app? cc @cellog
