### ISSUE TITLE
tsconfig.json in paywall/ has conflicts between build and storybook

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#3989]
`noEmit=true` causes local runs of `npm run build-checkout` to fail. However, it is required for `npm run storybook`. Solutions tested include setting `outDir` to something, but this fails on CircleCI.

We need to find a solution that works everywhere.

This is a back-burner since there is a workaround (uncomment `noEmit=true`)

**Comment by cnasc** [comment]
What is the circle failure?

**Comment by cellog** [comment]
most recent:
https://circleci.com/gh/unlock-protocol/unlock/75840
older:
https://circleci.com/gh/unlock-protocol/unlock/75803

I see the newer one:
https://github.com/unlock-protocol/unlock/commit/e7d90040f959c1f10c0cd55770a08e84becb6a69

is incorrect, it needs to disable `noEmit`. That may fix it.
