### ISSUE TITLE
if a user has logged in before, and a wallet is removed, the account will stay at the former account

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4006]
This bug is causing integration tests to fail in a couple of PRs that are needed for v1.

Basically, walletService is instantiated inside the data iframe, then the proxy provider throws because there is no wallet, and then we do not reset to use account `null` because no update is ever sent to the cache.

**Comment by julien51** [comment]
I am not sure what you mean by "wallet is removed".

**Comment by cellog** [comment]
metamask is uninstalled, for instance
