### ISSUE TITLE
after purchasing a user key for user accounts, save the transaction in locksmith

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4008]
For purchase flow, after the frontend requests a purchase, the flow should be:

1. send signed purchase request to locksmith
2. locksmith buys a key (with all the requisite credit card/on-chain stuff)
3. after receiving the transaction hash, save the transaction details in locksmith, including the `for` field
4. respond to the purchase request with success/fail

Steps 3 and 4 are needed for the paywall to successfully monitor the key purchase transaction, because the paywall will re-request transactions relevant to the user after step 4

**Comment by akeem** [comment]
This has been sorted: #4131 #4028
