### ISSUE TITLE
A DAO owned lock

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4015]
One thing that I strongly believe is that some locks will be used as bundles, where site X, Y and Z all put the same lock on their pages and if a user has a key to the lock they can read content across all of these sites.

Now, there are 2 ways to build these bundles: top down or bottom up. The first approach requires X, Y and Z to "agree" on how they share revenues. Not great. The second approach is a lot more interesting and should be "self serve". Here is how we could implement it:

1. A DAO is formed with the following rules: each "member" of the DAO has a number of tokens which represents their claim on the revenues from the lock.
2. A lock is created and transferred to the DAO so that the DAO owns it.
3. Someone puts the lock on their site. 
4. Once someone purchases a key to the bundle lock, the "provenance" of the purchase has to be known (user U purchases a key on site X).
5. The DAO will mint a new token and grant it to X.

The funds from the lock are "withdrawn" by the lock and any DAO member can withdraw their share of these. 

This model is completely "permission-less" : anyone can put the bundle lock on their site and, if they sell a key, they will be able to claim their share of the revenue of that lock. 

I think there are interesting things about this approach:

1. At infinity, every co-owner of the DAO will receive exactly their share of the revenue that the lock generates across the network. [The ownership of tokens on the DAO will eventually be completely aligned with the revenue "origin" of the bundle]

2. Early adopters are rewarded until they slowly get diluted. This makes sense because they are taking a greater risk than late adopter who are benefiting from network effects.

I have no idea if this is viable but I have a thousand ideas of stuff which could be added to that model (the price of the keys could be adjusted based on the new supply of tokens too, in a log way so that the "larger" the bundle, the more expensive it becomes, while still being a better deal). 

Now, coming back down to earth, in order to implement this, I think we would need to improve the locks in 2 ways:

1. Add the ability to have "listeners" : the lock owner could add contracts which are "listening" on the the lock to see methods triggered when new keys are purchased, like `onPurchase` for example.
2. Accept a new parameter on `purchaseKey` which should be used for the event representing the "location" from which the key was purchased 

Ideas? As @akeem says it would be interested to run simulations!

For context: here is a blog post about bundles http://cdixon.org/2012/07/08/how-bundling-benefits-sellers-and-buyers/

**Comment by julien51** [comment]
cc @nfurfaro @NickCuso @benwerd

**Comment by NickCuso** [comment]
I think we could leverage ideas from ERC-777 for this https://eips.ethereum.org/EIPS/eip-777

Specifically:
 - Add a bytes `data` field which can be used for anything
 - Add a hook - this is like their tokensReceived but for us it could be keySold maybe
 - The lock owner can register an address to activate the hook
 - If an address was provided, call the hook and include the `data` field
 - The front-end populates the `data` field based on the source
 - The hook is a call into the DAO contract itself so bookkeeping (i.e. minting DAO tokens) happens all on-chain

what about cancelAndRefund? hmm.  but as a starting point..?

**Comment by nfurfaro** [comment]
I like this idea! Will read the linked blog post & take a look at erc-777 for more context.

**Comment by nfurfaro** [comment]
Also, as for running simulations, this is exactly what Gauntlet is meant for. 
https://gauntlet.network/

**Comment by julien51** [comment]
@nfurfaro yeah I have met with Tarun a couple times!

**Comment by nfurfaro** [comment]
@julien51 Cool! I just listened to a good podcast where he describes Gauntlet a couple days ago, and also another today about Daostack, which aims provide a framework which allows one to easily create decentralised governance and custom Dao's modularly.  https://daostack.io/deck/DAOstack-Deck-en.pdf

**Comment by NickCuso** [comment]
We create an interface, like this from the ERC-777 standard:

```
interface ERC777TokensRecipient {
    function tokensReceived(
        address operator,
        address from,
        address to,
        uint256 amount,
        bytes calldata data,
        bytes calldata operatorData
    ) external;
}
```

We want almost exactly the same, however to avoid conflicts it must change a bit.  We could do:

```
interface IUnlockKeySold {
    function keySold(
        address lock, // the lock's address
        address from, // applicable if purchasing as a gift for another account
        address to, // the key recipient 
        address referrer, // the key owner which referred the purchaser
        uint256 pricePaid, // ETH or ERC-20 token value (in base units, e.g. wei)
        bytes calldata data // populated by the front-end to indicate the purchase source
    ) external;
}
```

By using arbitrary data we are more consistent with ERC-777 and open to other use cases potentially.  However practically speaking converting from bytes back into an address is non-trivial (https://ethereum.stackexchange.com/questions/15350/how-to-convert-an-bytes-to-address-in-solidity).

So we could build for this use case more specifically by using `address contentProvider` instead of a generic `bytes calldata data` (or maybe we have both!).

For this to work the contentProvider and/or data field would be added to the `purchase` function call.

Then we use EIP-1820 to handle look up.  https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1820.md

The DOA contract uses this to declare support for this interface.  When a key is sold, we check if the Lock owner has registered support.  If so, call the hook.

Thoughts? @julien51 @nfurfaro

**Comment by julien51** [comment]
I _think_ this is right. I understand that using `data` is more flexible and we should probably do that. I am sure there are solidity libs (from Zeppelin?) which do this kind of conversion? We may not be the only ones doing this?

**Comment by NickCuso** [comment]
Hmm I think to prevent possible abuse we need to add a hook for cancelAndRefund.  In that scenario we cannot trust data to be included with the call.  We could store the data on purchase, or maybe expect the contract accepting hooks to track that information.  ...I'm leaning towards the former ATM but not convinced...

**Comment by nfurfaro** [comment]
> By using arbitrary data we are more consistent with ERC-777 and open to other use cases potentially. However practically speaking converting from bytes back into an address is non-trivial 
What if we use the raw data field (for erc777 compatibility) to pass a uint instead of an address? Each website using the lock could register its address, mapping uints to addresses. Each time a key is sold, the `keySold` function is called and the website's "ID" number is passed to the function. The ID is used to look up the actual address.

**Comment by NickCuso** [comment]
Hmm yea that could work as well.  I guess that's the nice part about going with `bytes`.. the contract consuming it gets to decide.

**Comment by nfurfaro** [comment]
I believe this is heading in the right direction. I'm not seeing any major simplifications we could make on this appoach, or alternate approaches to achieving the goals here. I read up a bit on erc777 last night and have a better idea of what it entails. I'm not certain where the `keySold` hook would be implemented...
As for erc1820, it looks to be the new way to achieve what erc165 did, while staying backwards compatible. Is this  basically it?

**Comment by NickCuso** [comment]
RE 1820 yea that's right. With 165 the contract itself was probed, with 1820 there is a single contract for the entire network.  Think about our NO_FALLBACK feature we had, if a contract implemented that and did not consider 165, asking that contract if they support an interface would cause the transaction to revert.  1820 is safe / will always return bool.

**Comment by NickCuso** [comment]
Feature is implemented.
It would be nice to add a sample use case as well.

**Comment by NickCuso** [comment]
Hmm we may want to add tokenId and a transfer hook.

**Comment by julien51** [comment]
Let's close this for now as I believe most blocks for this already exist!
