### ISSUE TITLE
The paywall config does not provide a logo

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4082]
The paywall snippet does not include a `icon` which means the checkout popup does not look great as pointed out by one of our users (what does _Unlocked_ mean?):

![image](https://user-images.githubusercontent.com/17735/60447847-5f9c9900-9bf2-11e9-8e42-1d822dd4e9da.png)

If no `icon` is present we should just put the Unlock full logo.

**Comment by ajhit406** [comment]
Yeah logo would be great

Or at least provide the ability to customize the "Unlocked" header with the title of the site/blog or some other static content (E.g. "Payment required", "Please subscribe", "Support our site!")... 

"Unlocked" is a misnomer as the content is actually "locked". If anything it should say "locked" not "unlocked"!  

😄

**Comment by julien51** [comment]
We have now removed the title completely and the implementer can easily add a logo!
