### ISSUE TITLE
Editing each form field independently

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4130]
Our dashboard lets creators change some values on their locks: price, name... etc.

Given the nature of the smart contract, it is only possible to change one field at a time. Our current UI provides a single "edit" form which lets the user change all values. This would be confusing for users because they would send X transactions (one for each field) when they only submit one single form.

A better approach is to make each form editable independently.

cc @smombartz

**Comment by smombartz** [comment]
@julien51 two options
- let users know they can only make one change per update
- let users know that each change requires a transaction

**One Change per Update**
<img width="1120" alt="Screen Shot 2019-07-09 at 12 53 14" src="https://user-images.githubusercontent.com/1377389/60907977-d23bf300-a248-11e9-90bb-797679cd05b6.png">

**Multiple Transactions on One Update**
<img width="1124" alt="Screen Shot 2019-07-09 at 12 50 23" src="https://user-images.githubusercontent.com/1377389/60907978-d23bf300-a248-11e9-9c8b-685a4cc22325.png">

**Comment by julien51** [comment]
Hum. I think this is very confusing? I mean, could we just make each field editable "in place" ?

**Comment by smombartz** [comment]
That sounds good. though I would suggest leaving the button where it was (it feels more final). We might want to add a question around this to the FAQ (Why can I only edit one field at a time?).

![image](https://user-images.githubusercontent.com/1377389/60918979-96ae2280-a262-11e9-8f5e-a71f954c9d55.png)

**Comment by cellog** [comment]
from a usability perspective: is there any reason we can't add a single "edit fields" smart contract method for setting all the fields at once? Just as it would be a usability win to have a "retrieve all fields at once" method in the smart contract
