### ISSUE TITLE
Make required changes for paywall<->app communication

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4133]
Making an issue for these so I can make sure I get them all

- [ ] postOfficeMiddleware needs to respond to LockUpdate, not KeyPurchase
``` javascript
 postOfficeService.on(PostOfficeEvents.LockUpdate, locks => {
  const lock = Object.values(locks)[0] // probably not exactly this?
  dispatch(addToCart({ lock }))
})
```

- [x] storageMiddleware needs to dispatch keyPurchaseInitated after success.keyPurchase
``` javascript
storageService.on(success.keyPurchase, () => {
  dispatch(keyPurchaseInitiated())
})
```

- [x] storageMiddleware needs to fetch cards from locksmith when a new payment method is added
``` javascript
storageService.on(success.addPaymentMethod, ({ emailAddress }) => {
  storageService.getCards(emailAddress)
})
```

**Comment by cellog** [comment]
> Making an issue for these so I can make sure I get them all
> 
> * [x]  postOfficeMiddleware needs to respond to LockUpdate, not KeyPurchase
> 
> ```js
>  postOfficeService.on(PostOfficeEvents.LockUpdate, locks => {
>   const lock = Object.values(locks)[0] // probably not exactly this?
>   dispatch(addToCart({ lock }))
> })
> ```
> 

So this is not correct. It needs to save all of the locks it gets into the store. We could receive a key purchase request on any of them
