### ISSUE TITLE
web3Service.getTransaction does not start polling if the transaction is only submitted in some cases

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4149]
This causes polling to fail on some key purchases.

The problem is 2-fold:

1) when `web3Service.getTransaction` is called too early, the alchemy node may not yet have learned of it
2) This causes `getTransaction` to fail without starting polling, because we don't want to poll a non-existent transaction

As for solutions, I think the best long-term solution is to remove polling from inside web3Service, and instead make it an opt-in feature, much like account polling is outside of walletService. This way, we can control the complexity better. ethers, for instance, provides a robust polling solution that is as simple as calling `this.web3.on('<transaction hash>')` which will poll the transaction every block until turned off.

Short term, we need a way to indicate via a return value that polling was started or not started, so that on fail, the data iframe can re-trigger getTransaction after a short delay until it starts polling.

**Comment by julien51** [comment]
Hum. I actually think it is fine to poll transactions if they do not exist yet (and I believe that was the behavior for some time? maybe until the ethers rewrite). Let's do that please! 
Thanks!

**Comment by cellog** [comment]
> > because we don't want to poll a non-existent transaction
> 
> Hum. I actually think it is fine to poll transactions if they do not exist yet (and I believe that was the behavior for some time? maybe until the ethers rewrite). Let's do that please!
> Thanks!

This was never the behavior. Prior to this, it crashed when the transaction was unknown.

To be clear, this will mean if a user ever requests an unknown transaction (because of wrong network or some other error condition), it will poll every 8 seconds until the universe ends or they close the browser window, whichever occurs first.

I'll make this happen, I confirmed it fixes the issue

**Comment by cellog** [comment]
confirmed fixed
