### ISSUE TITLE
netlify config for the user accounts iframe is not set up properly

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4171]
https://staging-app.unlock-protocol.com/account?origin=https%3A%2F%2Fstaging-paywall.unlock-protocol.com

Page is probably not in `static/_redirects`

**Comment by cellog** [comment]
@cnasc until this is fixed, user accounts won't work on staging or prod, just drawing your attention to it

**Comment by cnasc** [comment]
That's actually a helpful reminder, I had forgotten about this. I'll cook up a PR for it tomorrow
