### ISSUE TITLE
transactions for purchases made by locksmith on behalf of users do not have "data" set

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4183]
The `data` field is essential for monitoring pending transactions, if this were set, it would instantly fix monitoring of pending transactions for user account purchases

**Comment by akeem** [comment]
This is not an essential field for monitoring pending transactions, the transaction hash has previously been used for this. 

Having access to the data of the transaction will not provide additional information as to if the transaction itself were to have been mined.

Locksmith in its current iteration was not designed to serve transaction data. I do believe that the front end should be able to function as it does for non-managed users with same level data available to as users that manage their own accounts

**Comment by cellog** [comment]
#3246 

and

https://github.com/unlock-protocol/unlock/commit/11ea8ba153cd7b03d6c2a1799b0fb7e924fce31e

We have been storing data for transactions since mid-May because of a couple of reasons.

1) A transaction hash, the "to" field and the "from" field do not tell us whether the transaction is a key purchase, a withdrawal, or a change (if we own the lock)
2) web3Service does not set the `lock` or `key` fields on a transaction unless it is a key purchase transaction
3) the transaction type can only be determined by parsing the input.

For submitted transactions, or cases where the mempool is full on alchemy, retrieving the transaction does not have input set.

Anyways, implementing this is trivial, just changing `dispatcher.ts` lines 48 to:

```diff
    walletService.on(
      'transaction.new',
-      async (transactionHash: string, sender: string, recipient: string) => {
+      async (transactionHash: string, sender: string, recipient: string, data: string) => {
        await findOrCreateTransaction({
          transactionHash: transactionHash,
          sender: sender,
          recipient: recipient,
          chain: walletService.networkId,
          for: this.buyer,
+          data: data
        })
      }
    )
```

implements the needed functionality

**Comment by akeem** [comment]
Sure it's a trivial change, but this data does not provide insight into if a transaction is pending or not.  It does provide info into what kind of transaction it is but in the context of v1 wouldn't all transactions from the address be key purchases? 

I'll make the change and I guess that will mean that we will have all the end to end communication wired
