### ISSUE TITLE
Review and verify "msg.sender" in the Lock contract constructor.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#424]
During the deployment of a Lock contract, it's uncertain as to which address (Proxy or Unlock) msg.sender refers to in the constructor function.
  
If msg.sender isn't the Proxy contract address but the deployed, upgradeable Unlock contract, we should pass the correct address (the immutable Proxy address) to the Lock via the constructor.

**Comment by nfurfaro** [comment]
I can now confirm that when a new Lock contract is deployed:
- `msg.sender` refers to the proxy contract as desired.
- `address unlockProtocol` is set to the address of the proxy contract as expected.
- the new lock is owned by the address that called `Unlock.createLock()` as expected.

**Comment by julien51** [comment]
Great! Thanks @nfurfaro
