### ISSUE TITLE
Improve handling of account iframe hiding

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4250]
Right now we provide a close button on the account iframe to dismiss the iframe, in the case that a user does not want to complete a purchase. This is fine on a manually triggered checkout (such as paying to remove ads), but it's a problem on hard paywalls. We'll need a way to re-show the iframe after that, or to signal that the close button should not appear. (Part of the task here is going to be to specify exactly what should happen)

Not a blocker for V1, but will need to be sorted out sooner rather than later.

**Comment by cellog** [comment]
Probably the simplest way is to send the configuration to the accounts iframe also, then you can check the paywall type, and if it's paywall, disable the close button
