### ISSUE TITLE
Delegated Purchases ERC20 vs ETH behavior

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#4318]
While working through what we thought was a configuration issue and tracking down a bug we discovered a portion of the code base that we could smooth over for future use cases. 

When purchasing a key via purchaseKey we have two paths:

1. Purchasing a key for an Ethereum backed lock
2. Purchasing a key for an ERC20 backed lock.

Our existing ERC20 path is written given the context of user purchasing and approving token transfer from the lock contract themselves. 

This falls apart a bit when initiated by the programmatic purchaser.  As a work around, we are routing automatic purchases through the non-explict erc20 token path with a value of 0 eth. 

The existence of this issue was masked on our local development environments as our test users have 100 ETH available.

**Comment by julien51** [comment]
The plan is to only support DAI purchases for now.
