### ISSUE TITLE
move retrieval of ether price into unlock-js

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4329]
One of the last redux-based items in the paywall is the retrieval of ether price changes. This will allow us to use features in ethers such as `getEtherPrice()`

https://docs.ethers.io/ethers.js/html/api-providers.html#etherscan

**Comment by julien51** [comment]
I am not actually convinced we should move into that direction... worth a chat!

**Comment by julien51** [comment]
Closing in favor of #4431. We'll use the same
