### ISSUE TITLE
attempting to update key price for a lock with no name fails

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4332]
Most of my rinkeby locks have no name. When I attempt to update the key price, it fails because the name is blank and form validation will not allow submitting. However, the name field is disabled, so it can't be edited

**Comment by cellog** [comment]
![Screen Shot 2019-07-31 at 10.48.08 PM.png](https://images.zenhubusercontent.com/5c7807999546cc1a88f4f864/bf2fb3c1-5ffd-42aa-8a16-4b9a6d7a1cb4)

**Comment by cnasc** [comment]
At present, you shouldn't be able to create a lock with no name. Given that all of the unnamed locks on mainnet are months old and have no transactions, I don't think this counts as a P1.

**Comment by julien51** [comment]
Agreed with @cnasc

**Comment by cellog** [comment]
Yesterday, I tried leaving the lock name at "New Lock" when creating a lock, and then updating the price and it worked. Maybe we should just close this?
