### ISSUE TITLE
Create a donations page on the static site

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4350]
This page basically just holds an instance of the paywall that reads a config encoded in the URL to allow people to set up a donation page without hosting it on their own site.

I think it needs to handle 3 states:
- no config parameter (show a landing page?)
- config parameter that doesn't parse (show an error, recommend they alert whoever linked them)
- normal config, show paywall

This will be my first order of business tomorrow

**Comment by julien51** [comment]
> no config parameter (show a landing page?)

For now let's just redirect to https://unlock-protocol.com and then we can add a landing page.

**Comment by julien51** [comment]
I think this is done, so closing ;)
