### ISSUE TITLE
"Start Reading" button on checkout confirmation is too specific

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4372]
Now that we have the donation feature implemented, I noticed that the wording of the button on the checkout confirmation is too specific -- once you've donated, there isn't necessarily anything to start reading.

And of course, this generalizes with other integrations -- videos, the Scout dashboard, and so on

**Comment by julien51** [comment]
Great point. Please @smombartz @benwerd suggest something which can apply to any use case.... otherwise we'll have to add a new setting to the paywall :/

**Comment by cellog** [comment]
"Continue" should do the trick?

**Comment by benwerd** [comment]
Continue works for me, tbh. It needs to be incredibly generic (and/or incredibly configurable).
