### ISSUE TITLE
isValidKey() returns false if owner is null

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4377]
in `paywall/src/utils/validators.js`, `isValidKey()` returns false if the owner is null, but this is a valid situation for a logged out user

**Comment by julien51** [comment]
Hum. Not sure about that? Would you mind explaining the rational?

**Comment by cellog** [comment]
when we are logged out, the key is a fake key, and the owner is `null` because we have no user. This is still a valid lock/key combo

**Comment by julien51** [comment]
Oh, I think I am confused by what you meant. Sorry. I thought you meant the key is valid... but it is for the `validator` not to decide whether the key is expired or not ;)
