### ISSUE TITLE
Accounts are loading on paywall app when they should not

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4378]
I was doing a demo to one of our prospective customers who is using Unlock on their website. My demo was done with Chrome on Android (and no active wallet). 
I was expecting to see the modal asking me to download a crypto wallet (Coinbase Wallet, Metamask or Opera), but instead the user accounts modal loaded.

This should not happen as this publisher is using Eth locks. See screenshot.

![image](https://user-images.githubusercontent.com/17735/62707187-f2cda900-b9be-11e9-92f2-008002c21da4.png)

**Comment by cnasc** [comment]
Looks like this was resolved in #4432, verified by checking the DOM and I only see 2 iframes (no account iframe) when the config does not have the  `unlockUserAccounts` property.
