### ISSUE TITLE
Visual bug on checkout modal on mobile device

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4380]
See screenshot.
![image](https://user-images.githubusercontent.com/17735/62707510-7d160d00-b9bf-11e9-832d-333649f200b4.png)

**Comment by cellog** [comment]
I wonder if production was current master in this photo? There should be a green button in between the text and the unlock logo that I don't see there. In any case, I can work on this next week once I have actual internet again

**Comment by julien51** [comment]
This is production as of last wednesday.

**Comment by julien51** [comment]
Looks like it has been fixed.
