### ISSUE TITLE
"Unresponsive script" in paywall

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4381]
When at least 2 tabs are open which both load the paywall application, there are cases where the tabs become unresponsive.
See screenshot below taken on a Mac laptop using Chrome while showing a demo to a prospective user.
This has also happened in Firefox. 

My suspicion is that the various tabs/iframes are entering in some "loop" while exchanging messages.

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/17735/62707792-0299bd00-b9c0-11e9-9b78-78de07601c3e.png">

**Comment by cellog** [comment]
I just tried opening 6 tabs, 1 with ouvre boite, 2 with the demo on 2 production locks I have, 1 with unlock-protocol.com, and 2 with the forbes pages. I did this in the console:

```js
window.addEventListener('message', a => console.log(a.data))
```

to watch the incoming messages. I also opened the task manager, and then let it sit for a while.

Then, I switched it to the background and came over here, and suddenly, wham:

<img width="1653" alt="Screen Shot 2019-08-10 at 10 16 06 PM" src="https://user-images.githubusercontent.com/98250/62828804-cd0df300-bbbc-11e9-8e89-98c03a2e3e4d.png">
<img width="1653" alt="Screen Shot 2019-08-10 at 10 18 05 PM" src="https://user-images.githubusercontent.com/98250/62828805-cda68980-bbbc-11e9-8930-923153a8c01c.png">

Still not sure why this is happening yet

**Comment by cellog** [comment]
I think I have a lead on why this is happening

**Comment by cnasc** [comment]
Reopening, just had this happen when I had the blue checkmark page (production) and the staging-with-ads page (staging) open

**Comment by julien51** [comment]
Dang. @cnasc did you see this recently? i have not in a couple of weeks but please do re-open if you see it again!
