### ISSUE TITLE
when receiving a localStorage StorageEvent, don't trigger a re-fetch of the blockchain data unless the key values are submitted/pending/confirming/valid

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4411]
#4381 was caused by a race condition of fetching blockchain data when there is no actual change. We should refetch only when there is a change to the relevant keys. This will stop the race condition from occuring

**Comment by julien51** [comment]
Is this fixed? What is the best way to reproduce this?

**Comment by cellog** [comment]
This was the cause of the browser crashing. Localstorage cache is temporarily disabled, but if reenabled the issue is not fixed yet
