### ISSUE TITLE
Add event time zone and event URL in description

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#4439]
# Add Time Zone
the time zone could automatically be determined by the location of the event. example the berlin BOSS event showed up in my new york time zone

# Event URL in description
would be helpful to have link back to the event page in the event description for easy access and ticket verification. (not in the screenshot but event website in the description could also be helpful)

![image](https://user-images.githubusercontent.com/1377389/63034046-a08cfc00-be86-11e9-9d2e-d33710db2902.png)

**Comment by julien51** [comment]
Yeah, that's an annoying one. That said, most event are probably created in the TZ in which they happen?

**Comment by smombartz** [comment]
@julien51 true. worth backlogging.

@benwerd the description is getting cut off because theres an ampersand in the description...
![image](https://user-images.githubusercontent.com/1377389/63106413-c7b00000-bf50-11e9-8376-1afd7a09b1dd.png)

**Comment by benwerd** [comment]
Can we split this issue up a bit? Ampersands were fixed in #4445.

**Comment by benwerd** [comment]
Event URL is now present in the GCal description as of #4447. Tempted to say we should close this for now and potentially re-open for a specific timezone issue?
