### ISSUE TITLE
Uploading banner to tickets page

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4440]
Our tickets application lets organizers create an event. They can a currently set a title, a description, a location, a date and time... etc.

We need to let them also upload a banner image which will be shown on the ticket checkout page (where attendees can purchase a ticket). Our model already has a `logo` field which could be used for this banner (not the best name...) so it is just a matter of adding the front end which lets the user upload the picture and then filling the `logo` field with the right URL.

For this, we'd love to dogfood more decentralized technologies such as IPFS. We should consider the use of [Uppy](https://uppy.io/).

**Comment by julien51** [comment]
Ideally @bmann and team could help us build this!

**Comment by bmann** [comment]
Thanks for writing this up @julien51! 

Aside from banner, I assume you also want a more square formatted NFT image for the ticket?

I'm not familiar on best practices for IPFS and NFTs, might be good to do some research.

Re: Uppy -- it's an open source uploader with good UX, making it easy for users to select a file from different sources. We wrote up about how FISSION could [add IPFS support to Uppy](https://talk.fission.codes/t/add-ipfs-support-to-uppy-a-javascript-file-uploader/196)

**Comment by julien51** [comment]
Yes, the NFT image would also be useful. However we have to clarify on our end how we store this (the backend is not ready for that...)

For now, let's work on the banner first. Small scope FTW ;)

**Comment by julien51** [comment]
Duplicate of #2870 which I'll close.

**Comment by bmann** [comment]
You’re welcome to provision an API key and use Fission to handle the IPFS parts of this @julien51. React drop zone likely simpler than all of Uppy!

**Comment by julien51** [comment]
Closing as we're moving to a world where tickets are mostly sold from the event website directly!
