### ISSUE TITLE
New Metamask API

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#447]
We are using a deprecated Metamask API: they show this message in the console:
> ATTENTION: In an effort to improve user privacy, MetaMask will stop exposing user accounts to dapps by default beginning November 2nd, 2018. Dapps should call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code.

November 2nd is... in 3 days!

**Comment by cellog** [comment]
beginning work on branch `greg-issue-447-metamask`
