### ISSUE TITLE
Paywall can't monitor superseded transactions

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4470]
**Describe the bug**
For example, if you up the gas price in metamask, it supersedes the transaction that the paywall knows about. This leads to a weird case where the transaction is stuck on "Payment Sent"

![image](https://user-images.githubusercontent.com/9300702/63387897-9c744900-c374-11e9-8a52-c57dbc02d3be.png)

Here's an example transaction that was dropped and replaced by one with a higher gas price: https://etherscan.io/tx/0x64d111fa280d9fa93212fa35fec592cba09e4601cd817b30bf63984e0f8b36d3

**To Reproduce**
1. Buy a key with a very low gas price
2. Raise the gas price in MetaMask
3. If the original transaction gets replaced, you'll see something like the screenshot above, where the new transaction completes but the paywall doesn't update

**Expected behavior**
If possible, the paywall should replace the original transaction with the new one.

**Comment by cnasc** [comment]
The superseded transactions come back as `null`, because they never get to the chain. Fixing this will probably not be easy if we want to do it cleanly. We'll need to poll for all keys rather than just watching a single transaction.

**Comment by julien51** [comment]
I think this is now fixed!
