### ISSUE TITLE
Support any ERC-20 token

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#4479]
**Is your feature request related to a problem? Please describe.**
I'd like to create a Lock which accepts MANA (an ERC-20 token).

**Describe the solution you'd like**
Update the dashboard to support an arbitrary ERC-20 token address.

**Describe alternatives you've considered**
We could also add MANA to a whitelist of supported tokens.  If we go this direction, there are others we would want as well such as USDC.

**Additional context**

**Comment by julien51** [comment]
I am not sure the whitelist approach is a good one because people will keep asking for more and we will not have a good way to setup the limit. However, we should do the following: if the dashboard is loaded with a query string like `defaultERC20=0x....` then we should replace `DAI` in the UI with the value corresponding to that ERC20.
Does it make sense?

**Comment by NickCuso** [comment]
I think a combination may be best.  Selecting MANA from a short list of whitelisted/trusted/known tokens does a lot towards confidence over asking me to copy/paste the token's address from etherscan.  ...how can I be sure I'm looking at the right address.  That's non-trivial for most.

RE the query string - I'm not sure I understand the use case.  Where from / how would I be linked to the dashboard with the MANA token address?

**Comment by julien51** [comment]
It's a discussion worth having with @smombartz I think!

**Comment by smombartz** [comment]
@NickCuso & @julien51 instead of the address would it be possible to input the shortcode (MANA, DAI etc)? im asking because we could give users the option to input shortcode for a number of trusted tokens and the option to add it via the address.

**Comment by smombartz** [comment]
very rough first pass
<img width="978" alt="Screenshot 2019-08-27 at 14 57 39" src="https://user-images.githubusercontent.com/1377389/63773238-0e9bdf00-c8db-11e9-9db3-234109008a79.png">

**Comment by smombartz** [comment]
updated (still drafty but getting there)

<img width="1068" alt="Screenshot 2019-08-28 at 14 01 13" src="https://user-images.githubusercontent.com/1377389/63860944-47ef5000-c9aa-11e9-9017-adfa6661024b.png">

**Comment by julien51** [comment]
So, as much as I think this *can* happen at some point, I want to close that issue for now.
We actually have a "hacky" way of doing this by setting the ERC20 in the query params of the URL such as this: `https://app.unlock-protocol.com/dashboard/?ticker=MANA&erc20=0x0f5d2fb29fb7d3cfee444a200298f468908cc942`

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/17735/66251923-b2a55f80-e790-11e9-8ae7-c9562d3c52f9.png">

I understand it is a hack but it provides a solution which requires no work on our end ;)
