### ISSUE TITLE
Paywall should surface token symbol for any ERC-20

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#4481]
**Is your feature request related to a problem? Please describe.**
ERC-20 tokens which are not specifically DAI surface as "ERC-20" on the paywall.  

**Describe the solution you'd like**
We should retrieve the token `.symbol()` for a better experience.

**Describe alternatives you've considered**

**Additional context**
I'm personally looking to create a Lock which accepts MANA (an ERC-20) in early Sept.

**Comment by julien51** [comment]
I think this is implemented already?

**Comment by cnasc** [comment]
We should double-check, I know we have the code to get the symbol, but I'm not sure if the Paywall actually displays it
