### ISSUE TITLE
Enabling shows "below" the download a wallet message

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4501]
With Metamask installed, but not "logged in" (I have not entered a password yet!), We show a strange message:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/17735/63611484-f14cd500-c5a9-11e9-954b-b108079f8fc5.png">

**Comment by cnasc** [comment]
Does this still happen? I just tried to reproduce and couldn't

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/9300702/64727857-cfa78500-d4a7-11e9-83b9-046b7ea77cee.png">

**Comment by julien51** [comment]
Nope, not anymore, we now ask the user to check their wallet ;)
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/17735/66251874-15e2c200-e790-11e9-9bc3-b7060aae4cc2.png">
