### ISSUE TITLE
Bank contract for one approval for all of Unlock per token type

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#4519]
**Is your feature request related to a problem? Please describe.**
Each individual lock requires token approval before a purchase can be made.  We'd like to lower friction people purchasing multiple locks.

**Describe the solution you'd like**
Approve a 3rd contract to transfer funds.  That contract is responsible for ensuring that the Lock was created by Unlock (ensuring that we can trust the value to charge).

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
This probably requires https://github.com/unlock-protocol/unlock/issues/4518 to exist first?

**Comment by NickCuso** [comment]
Yup

**Comment by NickCuso** [comment]
Same concern applies to the transferFee. Need to consider that as well before using a bank.

**Comment by NickCuso** [comment]
Given KeyPurchaser this would no longer apply.  I think KeyPurchaser is a better solution - re-open if i'm overlooking anything.
