### ISSUE TITLE
Do not charge Credit card unless lock has been approved

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4542]
When the paywall uses user accounts, we should not charge credit cards in locksmith unless we have ourselves manually approved the lock for credit card purchases.

There is no need for us to show specific errors to users for now.

Note: this is distinct from the ERC20 approval for this lock to withdraw from the locksmith purchaser.

**Comment by cnasc** [comment]
Resolving this requires undoing #4030 

One important piece of this is going to be authorizing a lock in the docker standup so that we have a lock we can purchase against while testing
