### ISSUE TITLE
Add spinner on all buttons with lag

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4544]
Many of our buttons on the UI will perform things which have latency (signing requests, encrypting things, making requests to the server). Since these may take an "uncomfortable" amount of time and users are making "money" things we should show an indication of something "slowly" happening by adding a spinner on these buttons.

**Comment by cnasc** [comment]
List of places where we need a spinner (or at least some indication that something is happening):
- [ ] sign up
- [ ] log in
- [ ] user account key purchase
