### ISSUE TITLE
Only show the lock address once lock has been deployed

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4555]
@NickCuso rightfully indicates that the lock address is not known for real until the lock creation transaction has been mined.

We could either hide the lock address or speed up the work on https://github.com/unlock-protocol/unlock/issues/1782 I am in favor of that later option...

**Comment by NickCuso** [comment]
#1782 is done :)

**Comment by julien51** [comment]
We can now safely show the address!
