### ISSUE TITLE
Custom thank you message not shown

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#4560]
**Describe the bug**
After purchasing a key the page says:
```
It confirms your donation and gives you access to exclusive content and features for members!
```

This is misleading as for the donation use case it will be common that this is support without unlocking any exclusive content.

Additionally the custom thank you message appears to be ignored.

**To Reproduce**
Buy the free sponsorship on unlock's repo.
Note the thank you message specified in the config.
Compare to the website.
Not a match.

**Expected behavior**
We should use the custom message if specified.

**Screenshots**

**Additional context**

**Comment by julien51** [comment]
We have now changed the checkout enough that I am not sure this applies anymore...
