### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#458]
At no point do we actually test things "end to end". Both the smart contract and the React app are tested in isolation which means that when we change one side, and the other is not, we end up in trouble. This is what happened with https://github.com/unlock-protocol/unlock/issues/455

We need to test thing end to end.

**Comment by benwerd** [comment]
This looks like an interesting guide, although of course, our setup is going to be a little more complicated (with ganache etc). https://medium.freecodecamp.org/real-integration-tests-with-react-redux-and-react-router-417125212638

**Comment by julien51** [comment]
Maybe @cellog has an opinion about the framework to use for end to end testing?

**Comment by julien51** [comment]
I found that too https://blog.logrocket.com/end-to-end-testing-react-apps-with-puppeteer-and-jest-ce2f414b4fd7

**Comment by julien51** [comment]
And https://www.cypress.io/ was recommended too!

**Comment by cellog** [comment]
React-redux uses puppeteer for benchmarks, and I find it very good, but remember it only tests on chrome. I've run into iPhone-specific bugs with react state, but that's the only one so it's probably OK, but might be worth investing in browserstack and developing a quick manual sanity check for all browsers before releases.

**Comment by cellog** [comment]
turns out, browserstack is free for testing against edge: https://love2dev.com/blog/browserstack-simplifies-testing-in-edge/

I'd go with cypress.io for your integration/end-to-end tests, and then have a brief browserstack-based testing for edge that is used right before deploy to verify the UI correctness

**Comment by julien51** [comment]
Unfortunately it looks like Puppeteer and Travis are not the best friends in the world. We have a PR ready which implements a basic "setup" to run integration tests in this PR: https://github.com/unlock-protocol/unlock/pull/485 but I am unable to make it work on Travis for now.

**Comment by cellog** [comment]
https://github.com/bennyn/example-puppeteer-travis-ci may help, took it from https://github.com/GoogleChrome/puppeteer/issues/3284#issuecomment-428193032

**Comment by julien51** [comment]
Wow, you do have some search skills! I was trying to find such a project yesterday and struggled! Let me try to update our docker/travis conf with these settings!

**Comment by julien51** [comment]
Unfortunately, we still get this error:
```
 libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by julien51** [comment]
My next try is going to run puppeteer in its own docker container.

**Comment by cellog** [comment]
Not sure but this might help:

https://hackernoon.com/dip-dapp-doe-anatomy-of-an-ethereum-distributed-fair-game-part-3-d0229ac6aeba

**Comment by julien51** [comment]
This is also probably related to #195. Somebody with Docker skills would be a great candidate for this one!

**Comment by julien51** [comment]
We now have a better CI setup, so we can start focusing on this. The docker image can be used to deploy the smart contract and run the nextjs application.
Once we have a running end to end application in a container, we can start another container which runs puppeteer and the integration test suite.

**Comment by julien51** [comment]
This has now been set up, we just need to implement actual tests in #714.
