### ISSUE TITLE
Use prettier to automatically implement a style guide

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#461]
**Is your feature request related to a problem? Please describe.**

linting is not automatic, and fixing linting errors often is time wasted adding commas, spaces, and the like.

Linting is best for finding actual problems, such as missing prop-types declarations, unused code.

**Describe the solution you'd like**
https://prettier.io/docs/en/index.html

Prettier automatically formats code to a given strict style

Prettier can be set up as a pre-commit hook to automatically format files staged for commit in a number of ways:

https://prettier.io/docs/en/precommit.html

It can also be easily configured for any code IDE to format on save.

**Describe alternatives you've considered**
The alternatives are manual editing and running `npm run lint` repeatedly.

**Comment by julien51** [comment]
Arguably you can automate linting (but that does not mean this issue is not valid) by integrating this in your IDE. For example, I use VSCode and it does have eslint plugins (I am sure other exists for Atom, Sublime... etc). Let me know if this is helpful in the short term for you.

**Comment by cellog** [comment]
I did automate linting after I realized I had many errors :) here is an article with some perspective on using eslint and prettier together:

These tools will help you write clean code by Adeel Imran https://link.medium.com/y6mfsKcmvR
