### ISSUE TITLE
devDependency vs dependency

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#468]
Up until now we assumed that there was no real difference between these 2 because in practice Unlock is not a library. However @cellog raised an interesting observation in https://github.com/unlock-protocol/unlock/pull/454 where we could distinguish between the dependencies *only* required to build (`dependencies`) and the ones required to tests (`devDepencies`).

This [article](https://silvenon.com/blog/dependencies-or-devdependencies) provides useful information.

**Comment by julien51** [comment]
As part of this, we should also do some cleanup as tools such as `[depcheck](https://www.npmjs.com/package/depcheck)` show a lot of unused dependencies.

**Comment by julien51** [comment]
I think we can close this, right @cellog https://github.com/unlock-protocol/unlock/pull/884

**Comment by cellog** [comment]
Yes!
