### ISSUE TITLE
Partition chain data for checkout

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4711]
At the moment, the checkout is reliant on some data-munging that correlates locks, keys, and transactions. Because of the way that the data validation in the paywall works (which may itself be superfluous), we cannot show anything on the checkout modal until we have received chain data for everything.

We should change the checkout's behavior to be more resilient in the face of incomplete data, and the data itself should not be aggregated. Locks, keys, and transactions should be treated as separate streams of data.

https://github.com/unlock-protocol/unlock/blob/50bc5512fe946dd449b71ed45782eeee2d557235/paywall/src/utils/validators.js#L243

`isValidLocks`, for example, will return false if we have "default keys" attached to the locks, which will cause `useBlockchainData` to return an empty object for the locks until all keys have been retrieved (which causes some difficulty for managed user accounts that haven't logged in yet). Ideally `useBlockchainData` should be able to provide partial data, so downstream consumers which do not depend on all of the data are not blocked.

One example of a component that will need to be changed: https://github.com/unlock-protocol/unlock/blob/50bc5512fe946dd449b71ed45782eeee2d557235/paywall/src/components/checkout/CheckoutLock.tsx#L32

`key` should no longer be a property of a Lock.

https://github.com/unlock-protocol/unlock/blob/50bc5512fe946dd449b71ed45782eeee2d557235/paywall/src/components/checkout/CheckoutLock.tsx#L44

`transactions` should no longer be a property of a Key.

These changes will allow for a simpler, "dumber" `BlockchainHandler` and more flexibility within the paywall app.

**Comment by julien51** [comment]
I think this is not relevant anymore as we are moving toward checkout on Unlock-app.
