### ISSUE TITLE
Approving ERC20 withdrawal for locksmith may cause nonce mismatch

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4728]
This morning while testing user account key purchases on staging, I ran into an issue with "nonce too low" for the locksmith purchaser.

First I did a key purchase on a lock that was not approved to withdraw WEE from the locksmith purchaser (which failed)
https://rinkeby.etherscan.io/tx/0x95145685898e409e2c4589efe8c3df725dbaea2e14a96af7423bf870f1950e88

Then I approved the withdrawal
https://rinkeby.etherscan.io/tx/0xb7e30fc7aba595a916ae32c5df4e984c9ebee8ab6e5bc548056ab0d5c7fb0d30

Then key purchases failed (visible on alchemy dashboard) with "nonce too low".

Restarting locksmith staging in AWS resolved the issue and allowed key purchases for managed users to go through.

We need to find out the root cause of this problem so that we don't have to restart the app in the future.

**Comment by julien51** [comment]
This is a great cacth. Maybe we should "sync" the nonce before sending any transaction?

**Comment by cnasc** [comment]
Just happened, data from alchemy:

```
1
eth_sendRawTransaction
200
11ms
3m ago

    Params Raw request 

0:
"0xf8881a843b9aca00830493e0943628d7170209c58dc1e8f51ad190b69d044fbbf280a4f6e4641f00000000000000000000000064d9b520d3a5e817e9e7b6a961483fed224c78f21ca0932385d9364b19e23d4c07d81888f68de362bb342aff0ce668b4ef6f9ee7d4bba00585948e59c582e1f2d4f1697048da2b46407903275a1ef418fccc36f9e96e05"
(data):
"0xf6e4641f00000000000000000000000064d9b520d3a5e817e9e7b6a961483fed224c78f2"
(from):
0x903073735Bb6FDB802bd3CDD3b3a2b00C36Bc2A9
(gasLimit):
"0x0493e0"
(gasPrice):
"0x3b9aca00"
(nonce):
"0x1a"
(to):
0x3628d7170209c58dc1e8f51ad190b69d044fbbf2

    Error Raw response 

Code:
-32000
Message:
"nonce too low"
```

**Comment by julien51** [comment]
This is a fairly serious one which will come back and bit us several times... adding `p-2` so we can look at it when we get a few free cycles.
