### ISSUE TITLE
Update the no wallet modal to show that Opera supports iOS

### ISSUE THREAD

**Issue by charleshopera** [unlock-protocol/unlock#4735]
**Describe the bug**
Update the no wallet modal to show that Opera supports iOS

**To Reproduce**
Use Opera Touch on iOS
Try to buy a lock.

@julien51

**Comment by cnasc** [comment]
Hi @charleshopera, just opened a PR that I think should resolve this. Feel free to take a look at the approach there and let us know if you think we need any other changes!
