### ISSUE TITLE
User account integration tests

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4749]
I think it would be critical to start adding an integration test suite for user accounts with the following scenarios:
* Signup
* Login
* Key purchase

Optionally we could add some things around credit cards (adding, removing them)

**Comment by akeem** [comment]
Adding the following draft pr here to be resurrected as it cover the signup process sans being able to push through in the case of a wedlocks failure 

https://github.com/unlock-protocol/unlock/pull/4309

**Comment by julien51** [comment]
Closed in favor of most recent one.
