### ISSUE TITLE
"and report if it happens again"

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4751]
We rightfully ask the user to report any problem signing in... but we do not provide a way to do so ;)

We should add a way for them to easily report problem (maybe by adding a support page on unlock-protocol.com?)

**Comment by smombartz** [comment]
we have intercom... but if thats not clear enough – lets create a Feedback button/link in the header that links to a page that gives them a few contact options. ideas: email address, form field, instructions to go to github, instructions to use intercom. @julien51 let me know what you like and i'll mock it up.

**Comment by julien51** [comment]
I think we need a dedicated page so we can people to it. Maybe it is just an empty page with the intercom widget?

**Comment by smombartz** [comment]
hows something like this? @julien51 

![image](https://user-images.githubusercontent.com/1377389/66675965-837d6b00-ec34-11e9-8b3b-8cff07f5c3fb.png)

**Comment by julien51** [comment]
@smombartz is this design on Figma?

**Comment by smombartz** [comment]
@julien51 yes its here: https://www.figma.com/file/YPsoH350j2vkKdx9yEWVYJ/Support-Page?node-id=0%3A1

(In the **Web** projects folder)
