### ISSUE TITLE
Enhancement: Attach metadata to stripe purchases when relevant

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#4758]
We noticed that we could probably enrich the purchase statements with the inclusion of the Lock Address.

This should be a relatively quick change as the API is well documented

**Comment by julien51** [comment]
That's a neat idea!

**Comment by cnasc** [comment]
https://stripe.com/docs/api/metadata

Pretty simple, we just add a property `metadata` to the charge consisting of key-value pairs
