### ISSUE TITLE
Landing Page 2.0

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#4766]
## Description
A redesign of our landing page. Text/Copy can be found [here](https://docs.google.com/document/d/1RJ9txJ9n87E8qd5x90AVcjgYiFDmkxtcfvqnZY4Enk0/edit#) (please make any changes/suggestions there)

## Design
https://www.figma.com/file/KmLXlFmDo7CLOSn4T64Bu2/Landing-Page-2?node-id=0%3A860

**Comment by smombartz** [comment]
I have two draft options. one more similar to the current site one a bit newer/fresher.

**Comment by julien51** [comment]
This is really good. I'll start working on this soon!
