### ISSUE TITLE
Test every public version of Unlock

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#4809]
**Is your feature request related to a problem? Please describe.**
Our upgrades test currently tests v0 -> the latest.

**Describe the solution you'd like**
We should test each public version.

**Describe alternatives you've considered**

**Additional context**

**Comment by NickCuso** [comment]
These tests should confirm the `publicLockVersion` for each as well.  cc @akeem

**Comment by nfurfaro** [comment]
@NickCuso I'd be happy to complete this, just want to be sure we're on the same page.
So, we currently test that upgrading from v0 to the lastest version of Unlock doesn't break anything, and we want to test that upgrading from any version to the latest works as well. Is this what you were thinking?

**Comment by NickCuso** [comment]
Yea - either test each version -> latest individually or we could do v0 -> v1 -> v2 ...
