### ISSUE TITLE
locked/unlocked state cached for too long?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4835]
Right now it looks like we cache the locked/unlocked state until we can actually refresh the cache. We should add a mechanism to expire the cache after the key duration.. (just by caching the actual expiration of the key if any so that we do not take it into account if the user has been logged out long enough.

cc @akeem

**Comment by julien51** [comment]
We also need to cache the actual locks which have been unlocked so that if a domain has multiple locks, we use the relevant information!

**Comment by cnasc** [comment]
To handle expiration in particular I wonder if we should explore options other than localstorage

**Comment by julien51** [comment]
Why is that? couldn't we store in localStorage the expiration date itself? Rather than store 'unlocked' or 'unlocked', we could store `unlocked_until` with the date?

**Comment by cnasc** [comment]
We could, but if there is something that has expiration built-in, we wouldn't have as much bug surface. Just being cautious since complex use of localstorage has bit us before.

**Comment by julien51** [comment]
That's a good point, but I think the change from a boolean to an integer is probably not too ambitious a change ;)
