### ISSUE TITLE
Reset state on failures in User Accounts

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4856]
If for any reason the key purchase fails, we should reset the state on closing of the modal.

**Comment by cnasc** [comment]
I'm currently working on using a pattern like the one for the LogIn component: https://github.com/unlock-protocol/unlock/blob/4a84192221d1154c1031b91216d171987aed8c2c/unlock-app/src/components/interface/user-account/LogIn.tsx#L83

For any of the components on the account page that can have errors associated with them.
