### ISSUE TITLE
User account user testing with Peter

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4865]
We show a strange bar on the side

<img width="991" alt="image" src="https://user-images.githubusercontent.com/17735/65697846-a65f2b00-e049-11e9-8768-49a2c4fa6f91.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/17735/65698121-0c4bb280-e04a-11e9-9f49-11452a8831bd.png">

The user is not logged in the settings page should not be visible.

**Comment by cnasc** [comment]
What browser is this on?

**Comment by julien51** [comment]
Chrome, incognito

**Comment by cnasc** [comment]
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/9300702/65702197-99920580-e050-11e9-8f9e-f9df3f3647cd.png">

Any other info that can help reproduce?

**Comment by julien51** [comment]
Let me try to see wth him. 
Let's fix the seetings page.
