### ISSUE TITLE
Multi-day Event Presentation Update

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#4928]
Currently, the event storage layer has duration storage allowing us to present start and end points of a given event. 

The creation form should be intelligently updated to allow an event creator the ability to provide it and for us to present it gracefully

**Comment by julien51** [comment]
@smombartz Could you design the form for this?
I guess we pick a starting date/time and an ending date/time to be very flexible.

**Comment by smombartz** [comment]
Working on this. Will have something ready on Monday!

**Comment by smombartz** [comment]
updated design can be found here: https://www.figma.com/proto/bladzEkGVK14JI52xukIDc/Tickets?node-id=49%3A740&viewport=-907%2C-432%2C0.541752278804779&scaling=min-zoom

**Comment by julien51** [comment]
Given that we're moving away from hosting event landing pages ourselves (and letting organizers do that on their own websites I think it it safe to close this.
