### ISSUE TITLE
Warnings in the Chrome console

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4946]
When loading a page which has user accounts enabled, like https://www.ouvre-boite.com/members/ I see warnings in the Chrome console which indicate this:

```
A cookie associated with a cross-site resource at http://app.unlock-protocol.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

**Comment by akeem** [comment]
After doing a bit of research, I believe that this may be related to intercom being used at the root of the 'unlock-protocol.com' domain. As the warning was triggered based upon a Chrome change, it looks like we have until February 2020 to resolve this before it becomes a breaking change.

A related resource:
https://community.intercom.com/t/cookie-warning-in-chrome/1397
