### ISSUE TITLE
User Account flow purchase improvements

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4949]
The current user account flow purchase is the following: (as tested [on this site](https://www.ouvre-boite.com/members/)):

## Visit locked paged
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/17735/66251399-b7671500-e78a-11e9-9c01-dd157d1ee0c0.png">

## Click on "Become a member"
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/17735/66251407-cbab1200-e78a-11e9-8338-f7127d435170.png">

On that page, we show both options, which *may* be an issue.  We should show "Balance Insufficient" for the Eth option because user accounts are *just* for DAI lock.

## Click on the **Ether** option 
We rightfully show the login page 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/17735/66251454-3fe5b580-e78b-11e9-8c11-5ee27d36063c.png">

One the log in is successful, even when the user has enter their payment info, we *briefly* show the credit card form (probably because the app does not know that the credit card has already been added. We should avoid that and only show it if the user does not have a CC.

## After that we show the purchase confirmation 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/17735/66251507-c1d5de80-e78b-11e9-922a-8bf9050b1c22.png">
As you can see on the screenshot here, since I picked the Ether lock, we show a purcahse for it, which will fail.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/17735/66251518-d87c3580-e78b-11e9-940b-7bf428c40da3.png">

I suggest that, after the user has been logged in, rather than moving on with the purchase we send the user _back_ to the "pick your lock" screen, with a notice at the top like "You're now logged in!"

This way, we solve multiple problems:
1. we will show "insufficient funds" on the ether lock
2. the user can *only* pick the DAI lock (we could maybe even show insufficient funds for any lock that locksmith did not approve, but we would probably need an endpoint for that? cc @akeem )
3. we will not show the CC form, because by the time the user clicks again on the right lock we will likely have loaded that info

Note: this flow can be "tested" by closing the modal after signing in and re-opening it by clicking again on the "Become a member" button.

**Comment by julien51** [comment]
What do you think @cnasc ?

It might be a little bit "weird" to redirect the user back to the lock selecting phase. If that's the case, then i suggest showing "Log in" instead of "Purchase" under the locks until the user is logged in, so that the process becomes clearer.

**Comment by cnasc** [comment]
> We should show "Balance Insufficient" for the Eth option because user accounts are just for DAI lock.

We should definitely look into this, because there should be no balance for eth in the state. I would have expected it to show "Balance insufficient" here.

> One the log in is successful, even when the user has enter their payment info, we briefly show the credit card form (probably because the app does not know that the credit card has already been added. We should avoid that and only show it if the user does not have a CC.

This is one of the places in the app where we definitely need a "third option" to indicate that we don't have enough information yet. We need to know whether we've gotten a response before we can decide whether or not to show the form.

> If that's the case, then i suggest showing "Log in" instead of "Purchase" under the locks until the user is logged in, so that the process becomes clearer.

That's an option. One thing we'll need in any event is a flow for just logging in to an account, completely separate from purchasing because the current flow for users who have a key but are on a device with no cached state is pretty confusing.

**Comment by julien51** [comment]
> We should definitely look into this, because there should be no balance for eth in the state. I would have expected it to show "Balance insufficient" here.

I was able to consistently reproduce this [on my blog](https://www.ouvre-boite.com/members/). Just go there from a completely clean Safari (right after you've cleared history):

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/17735/66607714-d2ed7800-ebef-11e9-8246-ea83bfbb41fe.png">


Let's talk about the rest on Monday!

**Comment by cnasc** [comment]
Will look into it ASAP

**Comment by julien51** [comment]
This was fixed!
