### ISSUE TITLE
Account recovery seems to fail when using an email address with a "+"

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4975]
**Describe the bug**
While testing other functionality, I created an account on our production app using the "GMail + trick" to have a clean account. I visited the recovery page, and found that my recovery key could not be decrypted. So far I'm not sure exactly where the root of the problem lies, but I verified that simply encoding the `+` as `%2B` did not resolve the issue (though it did make the page render the address correctly).

I _think_ we have to encode and decode each query parameter.

**To Reproduce**
1. Create an account with a `+` (or likely any character that needs to be encoded)
2. Receive an email with a recovery link
3. Click the link

**Expected behavior**
I should be able to reset the password for this account.

**Screenshots**
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/9300702/66499639-3364a400-ea8e-11e9-8105-19b4f94167e4.png">

**Comment by julien51** [comment]
Dang this is a serious one. Thanks for the catch here! I'll try ti investigate today in between meetings.

**Comment by julien51** [comment]
I was able to reproduce but replacing the `+` in the URL with `%2B` did actually solve the problem on my side.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/17735/66524097-6c535600-eb2c-11e9-9074-2bae39de5aeb.png">

**Comment by cnasc** [comment]
Interesting, could have been something with my local environment. In that case, this should be a simple fix. We just have to do `encodeURIComponent` on the email address.

**Comment by julien51** [comment]
exactly. PR on its way!
