### ISSUE TITLE
monorepo.sh: CI should build if diff from master (vs previous commit)

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5007]
**Is your feature request related to a problem? Please describe.**
The current configuration for `monorepo.sh` will skip a CI pass if there were no changes in the commit.  The trouble is CI also automatically cancels builds when another commit is added to a PR.  This can lead to completely missing a test pass that you'd expect was included.  It's easy to miss, looking at the CI build times is the easiest way to know this might have happened.

**Describe the solution you'd like**
Instead of checking if the commit has changes, check if the diff vs master has changes.

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
This is a good catch. I myself almost only every do a single large commit when sending PRs but I am not sure this is good practice. I'll try to see if we can easily change this to include the diff to master, rather than just the latest commit.
