### ISSUE TITLE
Add IPublicLock to the -abi npm package

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5008]
**Is your feature request related to a problem? Please describe.**
We do not yet publish an interface for 3rd party contracts to consume.

**Describe the solution you'd like**
Add the yet-to-be-recreated IPublicLock.sol file to the npm package.

**Describe alternatives you've considered**
As a work-around for now, I've added a partial implementation to `hardlydifficult-ethereum-contracts` to use for the examples in our upcoming blog post.

**Additional context**
We should probably do the same for IUnlock.

**Comment by nfurfaro** [comment]
So this looks like it might be best to tackle in 2 parts:
1.) Create the `IPublicLock.sol` interface and add to to our contracts.
2.) Add it to the npm package.

RE: #2,  Do we want to add it to the next package we publish, or go back and re-publish existing packages to include it?

cc @julien51 @NickCuso

**Comment by julien51** [comment]
I think we can "backfill" when applicable and update the modules? That should not break anything since it is only "additive"?

**Comment by nfurfaro** [comment]
Ok...so if I start with the current PublicLock contract and create its interface first, and then I can modify it to work with each previous version and we can update the modules as needed. How far back should we go? all the way to V0?

**Comment by NickCuso** [comment]
Re-open, I think we should keep this to track updating the package.  TODO: update the version in package.json and then npm publish.

**Comment by julien51** [comment]
Hey @nfurfaro please confirm that this is what I published last week?

**Comment by NickCuso** [comment]
Yup, I saw the update - believe this is ready to close.
