### ISSUE TITLE
Duplicate tokenID assigned

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5026]
**Describe the bug**
We have a duplicate tokenID https://etherscan.io/tx/0x6d1788fe468c1e548bf68db1f04317d05d3ec86ad4abb0679aec94264bf3dcfc vs https://etherscan.io/tx/0xec1ae3c322380918e274f6a4ca3baafb14a481f939dee8539bf7309505f4b5fb

**To Reproduce**
Unclear ATM

**Expected behavior**
They should be unique IDs.

**Screenshots**
![image](https://user-images.githubusercontent.com/14855515/66863514-01e55000-ef48-11e9-8e72-ff290a52a436.png)

**Additional context**

**Comment by NickCuso** [comment]
https://etherscan.io/token/0xb0114bbdce17e0af91b2be32916a1e236cf6034f?a=0xdb92c096bc5efa8adb48f05cd601dddb75228203

I owned an expired key when I called `purchaseFor` again, shortly after "pat" called `purchaseFor`.

**Comment by NickCuso** [comment]
hmm so did pat's account: https://etherscan.io/token/0xb0114bbdce17e0af91b2be32916a1e236cf6034f?a=0xfacafb5baefcd4cf95a72ca88bcefc4ba12a0aa7

**Comment by nfurfaro** [comment]
Hmm. It looks like "Pat" (0xfacafb5baefcd4cf95a72ca88bcefc4ba12a0aa7) purchased a key about 4 hrs after you Nick...but yes, it seems you both already had an expired key.

**Comment by nfurfaro** [comment]
So here's one thing I found that needs to be looked at. in `MixinKeys.sol`(for V4 as well as the current code) `_assignNewTokenId` looks like this:
```
/**
   * Assigns the key a new tokenId (from totalSupply) if it does not already have
   * one assigned.
   */
  function _assignNewTokenId(
    Key storage _key
  ) internal
  {
    if (_key.tokenId == 0) {
      // This is a brand new owner, else an owner of an expired key buying an extension.
      // We increment the tokenId counter
      totalSupply++;
      // we assign the incremented `totalSupply` as the tokenId for the new key
      _key.tokenId = totalSupply;
    }
  }
```
I believe the comments is flawed...`an owner of an expired key buying an extension` will have a tokenId which is not `0`, and therefore just needs an extension of `expirationDuration`, not an incremented `tokenId`.
I will add this to a TODO list here for reference.
