### ISSUE TITLE
Paywall is broken

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5103]
Our [most recent deploy](https://github.com/unlock-protocol/unlock/pull/5100) broke the paywall. We reverted to October 11th' [deploy](https://app.netlify.com/sites/paywall-unlock-protocol/deploys/5da0aab09bad64d30a35c177) but we need to identify what is going on with the most recent deploy!

The error seems related to configuration...

**Comment by cnasc** [comment]
One of the things we noticed wasn’t actually an error: the account caching. I was in a private window for our test, so no localstorage. Didn’t realize that until I was walking home.

**Comment by cnasc** [comment]
Re: the other issue, my guess is that whatever we have set as the stablecoin to approve is somehow not DAI. That’s the only real change we made to balance handling, and the ultimate symptom is that insufficient balance shows

**Comment by julien51** [comment]
So, there has actually been a lot of changes in the paywall in that deploy (we had not deployed in nearly a wweek :/):

```
$ git show 4bf31cdf --name-only -- paywall/
commit 4bf31cdff63c00e867242b1f478c7d343dea7689 (HEAD, origin/production)
Author: Christopher Nascone <cnasc@users.noreply.github.com>
Date:   Wed Oct 23 15:57:09 2019 -0400

    Manual deploy as of commit:361710e8725be4744b39a27e04ce42c04e3247eb (#5100)

paywall/package-lock.json
paywall/package.json
paywall/src/EventEmitterTypes.ts
paywall/src/__tests__/data-iframe/Mailbox/Mailbox.test.ts
paywall/src/__tests__/data-iframe/Mailbox/setupPostMessageListeners.test.ts
paywall/src/__tests__/test-helpers/setupBlockchainHelpers.ts
paywall/src/__tests__/unlock.js/CheckoutUIHandler.test.ts
paywall/src/__tests__/unlock.js/MainWindowHandler/setupUnlockProtocolVariable.test.ts
paywall/src/__tests__/unlock.js/MainWindowHandler/signData.test.ts
paywall/src/__tests__/unlock.js/PostMessageEmitters/DataIframeMessageEmitter.test.ts
paywall/src/__tests__/unlock.js/Wallet/enableCryptoWallet.test.ts
paywall/src/__tests__/unlock.js/Wallet/init.test.ts
paywall/src/__tests__/unlock.js/Wallet/setupUserAccounts.test.ts
paywall/src/__tests__/unlock.js/Wallet/setupUserAccountsProxyWallet.test.ts
paywall/src/__tests__/unlock.js/Wallet/setupWeb3ProxyWallet.test.ts
paywall/src/__tests__/unlock.js/startup.test.ts
paywall/src/__tests__/utils/Callbacker.test.ts
paywall/src/constants.js
paywall/src/data-iframe/Mailbox.ts
paywall/src/data-iframe/blockchainHandler/BlockchainHandler.ts
paywall/src/data-iframe/blockchainHandler/blockChainTypes.ts
paywall/src/messageTypes.ts
paywall/src/unlock.js/CheckoutUIHandler.ts
paywall/src/unlock.js/MainWindowHandler.ts
paywall/src/unlock.js/PostMessageEmitters/DataIframeMessageEmitter.ts
paywall/src/unlock.js/Wallet.ts
paywall/src/unlock.js/constants.ts
paywall/src/unlock.js/startup.ts
paywall/src/unlock.js/startupTypes.ts
paywall/src/utils/Callbacker.ts
paywall/src/windowTypes.ts
```

**Comment by julien51** [comment]
I guess we need to look at user accounts on staging? Do we have a lock which does this?

**Comment by julien51** [comment]
I was able to add a WEENUS lock to https://www.ouvre-boite.com/members-staging/ and the issue is reproduced! Progress..

**Comment by julien51** [comment]
But, I am not able to reproduce locally which is quite strange.

**Comment by julien51** [comment]
The list of commits which changed the paywall before the 2 deploy is actually fairly short
```$ git lg 0ece48563672ca92d586ae2cc7499ab281eabda2..361710e8725be4744b39a27e04ce42c04e3247eb -- paywall
* a4add8c1 - Update unlock-js to 0.3.20 (#5058) (3 days ago)
* 36482633 - update to 0.3.19 (#5049) (6 days ago)
* a45dc11d - Revert "add `signData` method to `window.unlockProtocol` (#4958)" (#5037) (7 days ago)
* 7c69f3c7 - updated node engine to use 10.16.3 (#5023) (9 days ago)
* 79d2dc8b - Update unlock-js in all apps to 0.3.18 (#5021) (9 days ago)
* 87b89c71 - Make sure to zero out eth balance for logged out users (#5014) (10 days ago)
```

**Comment by julien51** [comment]
And indeed, as you anticipated it is probably 87b89c71 which is the only real change here.

**Comment by julien51** [comment]
From what I see this PR inroduces a new variable `managedPurchaseStablecoinAddress` which is actually a duplicate of `erc20ContractAddress`. Maybe this causes the issue?

**Comment by julien51** [comment]
Paywall is fixed! This was because for some reason it started to fail when the name was falsy in the config! @cnasc improved logging on config error and removed the requirement that the need be truthy for the config to be valid!
