### ISSUE TITLE
Indicate to user account users that they can log-in to view their keys

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5104]
When a user has an Unlock account and is logged out on a page, they need to click on "purchase" to be prompted to log in again before we detect that they actually have a key.
We need to indicate the fact that they can log in more obviously on the UI.

**Comment by julien51** [comment]
On the tickets page, even if we do not know whether the user has a ticket or not, under the "Purchase" button, we should show a message which says:

> "If you already have a ticket, you can view it in your keychain."

**Comment by smombartz** [comment]
<img width="898" alt="Screenshot 2019-10-24 at 11 57 40" src="https://user-images.githubusercontent.com/1377389/67503359-7f4e4600-f655-11e9-8b09-69b2cca025b7.png">
