### ISSUE TITLE
Partial Transfers

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5111]
https://docs.google.com/document/d/1GXIX2Saj4H5otYZZbfkl_cSeXACm5rkzcQbJYWkixbo/edit?usp=sharing

**Comment by nfurfaro** [comment]
cc @NickCuso @julien51 
This is what I'm considering for partial Transfers. Personally I prefer the name `shareKey()` as it's very clear what it's for, but functionally it will be most likely very similar to `safeTransferFrom`, so I suppose `partialTransferFrom()` could work as well.

# Interface

General thoughts
• use standard `Transfer` event
• follow pattern of `safeTransferFrom`
• _tokenId may not be needed here as it can be looked up from address _from
```
/**
* @notice Allows the key owner to share their key (parent key) by
* transferring a portion of the remaining time to a new key (child key).
* @dev Throws if _from does not have a valid key.
* @dev Throws if _from does not have enough remaining time on parent key to both pay transfer fee and share time with a child key.
* @dev Throws if _timeShared > maxSharableTime. // something like: maxSharableTime = parentKey.timeRemaining - transferFee
* @dev Throws if _checkOnERC721Received returns false.
* @param _from
* @param _to
* @param _timeShared
* @param _data // do we want this for future flexibility?
* @dev Emit Transfer event
*/
function shareKey(
  address _from,
  address _to,
  uint _timeShared,
  bytes memory _data // ?
) external; 
```

**Comment by NickCuso** [comment]
Looks good.  The _data field could be useful maybe if we add hooks to this flow in the future as well.  But maybe we keep it simple and not have it here.
