### ISSUE TITLE
Use the graph for the list of locks on the dashboard

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5126]
I just hit the tipping point of the dashboard with another address. End result is that 3 of my ~25 locks show up, with over 800 requests made in less than 10 seconds and a whole bunch of alchemy 429 responses.

By using the locks query I recently added in #5102  we should be able to scale it up without issue.

**Comment by julien51** [comment]
Glad you're bumping in the same issues that I am ;p

**Comment by akeem** [comment]
I believe that we are in a space to mark this as done, as the creator dashboard is now pulling from the graphql endpoint. Lets re-open this if this is still not implemented or open an new issue if there are follow up items
