### ISSUE TITLE
Locksmith to purchase "free" keys

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5138]
Currently, locksmith is able to purchase DAI keys which cost > 0.
Ideally we'd want to support locks of price 0 (and cover the gas price with no fee...) at least for our blog lock!

**Comment by akeem** [comment]
@julien51 From reviewing the code it looks as thought the handling a key priced at 0 DAI currently behaves as those  greater than 0. 

Is this feature request to have us handle the gas fees for the purchase, waive any Unlock fee, and not go through Stripe for these keys?

**Comment by julien51** [comment]
Since we're moving to an approach where we grant key, this issue will have to evolve to a world where we will do that only for lock owners who pay us for the gas spent... until the locks actually do that by default!

**Comment by julien51** [comment]
Done! This is happening when th key is free and gas price is less than $0.005. On mainnet this is unlikely to ever happen again, but does happen consistently on xdai and polygon!
