### ISSUE TITLE
Telegram bot with supports Unlock

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5140]
Unlock provides an access control mechanism that could be used to limit access to a chat room on Telegram to users who have a specific NFT in their wallet.

User Stories:
1. As a telegram group admin, I want to add the Unlock Bot to my group. Once the bot has been added I want to assign one (or more) lock(s) for which users need a valid key to be able to stay in the group. 
2. As a new participant, when I enter the group, the bot will ask me to identify myself by signing a message. The bot will then verify that I have a valid key. If I do, I am allowed to stay in the room. If I don't, the bot will ask me to purchase an access key to the lock.
3. As an existing participant, the bot will routinely verify that I own a valid key. If I don't the bot will ask me to renew my key or will remove me from the channel.

**Comment by lustigo** [comment]
Hi, 
for number 1) Is this process happening during the creation of the group, or while there are already members in the group?
for number 2) Should the be in private chat or in the group (and maybe later deleted) ? How should the verification take place? In my Metamask Wallet, I am unable to sign a message.
for number 3) Here you are talking about a channel. But a Channel is different from a group.

Do you have any preferences for the programming language or database servers?
The background for my questions: When you use the Telegram Bot API you are not able to see what users are in the group. So you can just build a User List by reading and storing the Join-Messages. You are also unable to write to people in private, when they have not sent you a "/start" message. 
You could use the Telegram Messenger API, so like building your own Telegram Client. I have not worked with that before.

**Comment by julien51** [comment]
@lustigo I am sorry for the delay here!

1. I think it can happen for any existing group, knowing that people who are in the group at the moment of creation knowing that when step 3 happens (routinely check participants) some of the members might be kicked out?

2. Since it is not possible to do in private chats, maybe we can do it in the channel for now. The message can be removed once the user has either proven their membership, or if they failed to do it after x seconds? For now you can just use our frontend "paywall" application to check the user's status: see https://docs.unlock-protocol.com/#install-a-lock-on-a-web-page

3. Sorry, I mean this should be channels and groups. I believe the key difference is the number of participants?

I did not know about the inability to list group members. Maybe indeed keeping a list "in sync" by looking at joins or messages sent is a good approach?

Thanks again.
