### ISSUE TITLE
Link to settings on user accounts

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5159]
Right now our dashboard has a link to the "transactions". (I do not think we use that very much... maybe worth thinking about deprecating). But we need to add a way to browse to  the following pages:
- dashboard
- keychain
- settings (only for user accounts)

Let's add these 3 buttons!

**Comment by cnasc** [comment]
I think dashboard is also `(only for crypto accounts)`, since it's not useful for a managed account user to go there (at least, not right now)

**Comment by julien51** [comment]
That is right!
