### ISSUE TITLE
We should use a caret on node engines

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5166]
We should have something like:
```javascript
{
  ...
  "engines": {
    "node": "^10"
  },
  ...
}
```
in our `package.json`s. This will solve the issue with renovate trying to install `unlock-js` (which has a strict `10.16.3` engine) from a package which has been updated to use `10.17`.

**Comment by julien51** [comment]
Damned. Another option would be to make `unlock-js` less strict? What's the best practice?

**Comment by cnasc** [comment]
> Damned. Another option would be to make `unlock-js` less strict? What's the best practice?

https://github.com/renovatebot/renovate/issues/320

There's some relevant discussion there. Renovate will only update the engines field if it's pinned (like it is now). So I think we could just apply the caret to `unlock-js` and that would be fine.

**Comment by cnasc** [comment]
We really should do this for all of our package.jsons, because Yarn will fail if you're using 10.17.0 for example and the package.json says 10.16.3.

**Comment by julien51** [comment]
Works for me!

**Comment by cnasc** [comment]
This is handled in the yarn PR, so I'll close this again.
