### ISSUE TITLE
Integration tests for user account flow

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5173]
We need to write integration tests for the user account flow:
1. Create an account (not sure how to handle the email confirmation though...)
2. Log-in (maybe more practical if we have the account created in the db already)
4. Adding Credit card
5. Purchase access key 
6. Ejecting account

This is probably going to take a bunch of time so we should try to make incremental progress on that.

**Comment by cnasc** [comment]
> Create an account (not sure how to handle the email confirmation though...)

Is there any way we can sort of cheat on that and parse the log from wedlocks?

**Comment by julien51** [comment]
Yeah, that's one way. I do not know how to read logs from another app though :/

**Comment by cnasc** [comment]
Replace our CI server with mechanical turk

**Comment by julien51** [comment]
Hum. I duplicated that issue. https://github.com/unlock-protocol/unlock/issues/4749
