### ISSUE TITLE
Different Top Level Menu on app.unlock-protocol.com

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#5203]
## Description
there are two different menus (top right of page) on unlock-protocol.com and app.unlock-protocol.com

![image](https://user-images.githubusercontent.com/1377389/68144117-f068e580-ff00-11e9-9f69-262a952ea183.png)

![image](https://user-images.githubusercontent.com/1377389/68144093-e515ba00-ff00-11e9-9ca6-71802924e1df.png)

**Comment by julien51** [comment]
I think that's ok.
