### ISSUE TITLE
A page which lists the key owners and their metadata

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5209]
Lock owners want the ability to list all existing keys, their state as well as the associated metadata for each key.

This page should be a standalone page and have the ability to list the metadata for a single lock or multiple locks. It should be linked from the dashboard for each lock (defaulting to only listing keys for that single lock). 

See the style on this page (make sure you look at the comments I left) https://www.figma.com/file/drh2YcjcN0dZtdeV0tqOam/Newsletter?node-id=0%3A1

**Comment by cnasc** [comment]
Actually, in retrospect it's a waste of space to reproduce the lock name on each row since it will be the same for all of them. So the lock name will go at the header of the table.

**Comment by julien51** [comment]
Well, since we want to be able to show the keys for multiple locks, I think it's important to show the lock name on each row too :/ (even if I agree this is wasteful).

If we can do that only when there are multiple locks, then, even better!

**Comment by cnasc** [comment]
I'm not sure I see the value in having multiple locks which may have different metadata on the same page or in the same list. Why would you not separate them by lock when you're looking at multiple locks? I'm also confused as to how a user would select multiple locks. As far as I can tell from Figma and the description above, the only way in would be to click on a button for a given lock, which would take you to the metadata page for that lock.

**Comment by julien51** [comment]
So, this is a request by several people who want to use this feature. On their site they have multiple locks for multiple "plans". They will need a single page to view all of their members and their respective plans.

> I'm also confused as to how a user would select multiple locks. 
For now, we will not build a UI for this but we should use the URL to pass the lock (or several locks) for state.
For example, we can use `/members?locks[]=0x1...&locks[1]=0x2....` (I believe this would be parsed as `locks=["0x1"..., "0x2"]`.


PS: The figma design is lacking in many ways, so let's not use this as the source of truth but reather this issue.
