### ISSUE TITLE
Consider moving to Typescript or Flow and removing prop-types

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#525]
**Is your feature request related to a problem? Please describe.**
While updating the tests from enzyme to react-testing-library, I found several dangerous discrepancies between the props passed in tests that were simply not caught by prop-types. For instance, the name of the balance in a lock is `keyBalance` in current tests, but the `Balance` component expects `balance`. Also, some tests passed this as a string, but others expect a number.

This is going to lead to a lot of technical debt, as well as tests that don't actually catch problems

**Describe the solution you'd like**
There are a couple of solutions. Using Flow typing or Typescript. I don't actually have direct experience with either, but both will be better than using prop-types

**Comment by julien51** [comment]
You are very right and it is definitely on the radar.
My experience in the past has been that type checking also has some disadvantages in the form of more slightly more work and slower iterations. I think there is an appropriate time to move to that and I am not sure we reached that point in the maturity of the project/structure.

Happy to be proven wrong though ;)

I have a slight preference for Flow (and some experience with it!)

**Comment by cellog** [comment]
More perspective https://twitter.com/monasticpanic/status/1064742660034965506?s=19

**Comment by julien51** [comment]
Closing in favor of https://github.com/unlock-protocol/unlock/issues/1449 which has a plan forward!
