### ISSUE TITLE
Keychain snap for Metamask

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5268]
Metamask is currently not able to show NFT on desktop. 
It would be really good to work on a snap (plugin) to make this better!

[more details to come later]

**Comment by akeem** [comment]
Adding a link to documentation for the metamask snaps software https://github.com/MetaMask/metamask-snaps-beta

**Comment by julien51** [comment]
It looks like snap did not catch up in MetaMask... closing.
