### ISSUE TITLE
Dashboard Lock Test Page

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#527]
## Description
1. Updated header, to make the page look more like a publication.
2. Powered by Unlock now lives on the right side. This element could be reused to indicate user purchased a key for the content already (see [Test Page Key Purchased](https://zpl.io/adPeJq1))

Specs: https://zpl.io/bA4p4Dp

## Screenshot
![lock test page banner](https://user-images.githubusercontent.com/1377389/48365494-130f4800-e679-11e8-89a4-6158d9bc0b89.png)

**Comment by julien51** [comment]
This https://github.com/unlock-protocol/unlock/pull/572 is only a partial implementation. We need to refactor the the "overlay" part too ;)
