### ISSUE TITLE
Lock States for Key Purchasing 

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#528]
## Description
Mockups of the different interactions and Lock states when purchasing a Key. Mocked up for 2 Locks, in case of 1 or 3 Locks, Locks should always be center aligned (see [Multiple Locks](https://zpl.io/VqlJKkZ)). Once the browser wallet opens all other locks should be faded and inactive.

Specs: https://zpl.io/aM909po
Assets: [checkmark.svg](https://github.com/unlock-protocol/unlock/blob/master/unlock-app/src/static/images/svg/checkmark.svg), [arrow.svg](https://github.com/unlock-protocol/unlock/tree/master/unlock-app/src/static/images/svg/arrow.svg)

## Screenshot
![paywall lock interactions](https://user-images.githubusercontent.com/1377389/49099076-88b11180-f23e-11e8-9b17-b0301be75d1a.png)

**Comment by julien51** [comment]
Working on this through https://github.com/unlock-protocol/unlock/pull/566 first!

**Comment by julien51** [comment]
Implemented the button in https://github.com/unlock-protocol/unlock/pull/623

**Comment by julien51** [comment]
All implemented! Closing now!
