### ISSUE TITLE
Script contract verification

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5280]
Add a script to verify each contract on a given network: Unlock, PublicLock, Proxy, ProxyAdmin, and UnlockDiscountToken

**Comment by NickCuso** [comment]
It may be nice to have the script post to etherscan, https://www.4byte.directory/, and https://verification.komputing.org/

**Comment by akeem** [comment]
@NickCuso would you be able to share a link to some documentation around the verification process, we should be able to script this pretty quickly

**Comment by NickCuso** [comment]
EtherScan: https://etherscan.io/apis#contracts

We have `npm run flatten` for PublicLock (need the same for Unlock but that's an easy change).  It uses https://github.com/BlockCatIO/solidity-flattener (one of the options etherscan suggests).

The deploy process is something like this:
 - Deploy Unlock template
 - Deploy PublicLock template
 - Update the Unlock proxy to the new template
 - Call configUnlock on the Unlock proxy to set the new PublicLock template

The proxy and proxyAdmin contracts don't change.  So we just need to verify the `Unlock` template and the `PublicLock` template.

**Comment by NickCuso** [comment]
4byte: https://www.4byte.directory/docs/

**Comment by julien51** [comment]
Done! Thanks @clemsos :)
