### ISSUE TITLE
Dashboard Withdrawing Funds from Lock

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#529]
## Description
The different Lock states and messaging when withdrawing funds from a Lock.

Specs: https://zpl.io/brNeBPr

## Screenshot
<img width="1157" alt="dashboard withdrawing funds from lock" src="https://user-images.githubusercontent.com/1377389/48366376-b2353f00-e67b-11e8-917e-d95223fb50fa.png">

**Comment by julien51** [comment]
@benwerd This is not working for me on master. When I click on the button, nothing happens.
We should also probably show an error message when the balance is 0 and/or disable the button?

**Comment by benwerd** [comment]
Yeah, I’m still working on this. At the point where the buttons are rendered, most of lock is currently not populated (including the balance) and I’m having trouble telling the component to rerender it. Should have a fix in this morning.

**Comment by benwerd** [comment]
The two stages of this that are not currently implemented are:

1. The "pending browser wallet" status. I can go looking, but I'm not sure how to reliably detect this (beyond maybe triggering it when the button is clicked, but this wouldn't detect cancels).
2. Withdrawal complete. I'm worried about the status sticking around long after the transaction is confirmed - but maybe we display it when the confirmations are above the minimum but below a defined threshold. I'll add this today.

**Comment by julien51** [comment]
1. I looked at that for other transactions (local creatiomn, key purchase) and I found that it was a mess... so I skipped for other things. The fact that the browser wallet window will open is probably good enough?

2. Yes I think that would work. We should also soon have the list of transactions implemented which will be helpeful.

**Comment by julien51** [comment]
@benwerd Do you mind providing an update on that front?

**Comment by julien51** [comment]
@benwerd Can we close this?

**Comment by benwerd** [comment]
I think we can close this. Some other related issues have been reported elsewhere and will be reported there.
