### ISSUE TITLE
Rinkeby deploy of Unlock needs to be updated to reflect the appropriate global base

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#5295]
Currently, the RInkeby deployment of Locksmith has a global base token URI referencing 'https://locksmith.unlock-protocol.com' as opposed to the staging host for locksmith. 

The current configuration will require downstream consumers to convert the URLs received from the graph to reach the existing metadata.

Once the contract change has been made, the subgraph will need to be republished to ensure that the data served is updated

**Comment by julien51** [comment]
Hey @akeem do you think you could update it yourself? I'ts owned by the multisig so that should be using that?
