### ISSUE TITLE
Revert tx if transferFee is 100%

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5298]
**Is your feature request related to a problem? Please describe.**
If there is a fee that consumes 100% of the available time, we should revert the transaction instead of simply burning the time.

**Describe the solution you'd like**
Revert transfer, transferFrom, and shareKey

**Describe alternatives you've considered**

**Additional context**

**Comment by nfurfaro** [comment]
Done, but needs a rebase to complete.
