### ISSUE TITLE
Brave does not prompt to use MetaMask

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5331]
It looks like Brave does not work with MetaMask for Unlock.
When going to https://app.unlock-protocol.com/keychain/
It looks like MetaMask is not "injected" in the page which means we are not able to detect it and we default to showing the user account login form.

**Comment by julien51** [comment]
I think this is because Brave has its own "internal" MetaMask and that is creating strange conflicts :/

**Comment by julien51** [comment]
It does as it's now been fixed ;) Thanks @bbondy

**Comment by bbondy** [comment]
🎉
