### ISSUE TITLE
Paywall intermittently recognising optimistic key

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#5359]
## Description
[I donated to become an unlock member](https://donate.unlock-protocol.com/?r=unlock-protocol/unlock). optimistic unlocking wasnt always successful. you can see it here in the video, i reloaded the page a few times and sometimes it recognises it and sometimes it doesn't.

https://www.dropbox.com/s/ey3qknsdw9ua40k/191120-QA-intermitten%20success%20paywall.mov?dl=0

**Comment by julien51** [comment]
New paywall does not have this bug anymore!
