### ISSUE TITLE
DAI Migration

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5386]
Earlier in November, the Maker team released a new version of DAI called multicollateral DAI. The old one has been renamed SAI (*S*ingle collateral DAI).

As of now, SAI is still the dominant version of DAI, but we should monitor things closely as the next few months with see a migration from one to the other. [This website](https://sai2dai.xyz/) keeps track of the supply of each.
As of writing the SAI/DAI ratio is 84/23.

The migration will include several steps:
* Rename DAI to SAI when talking about the [0x89 contract](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359)
* Default to the new DAI on the dashboard 
* Enable credit card purchases for DAI locks.

**Comment by julien51** [comment]
First step is done! As of today, all locks using [this ERC20](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359) are shown as SAI!

**Comment by julien51** [comment]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/17735/70347523-b5730e00-182e-11ea-892d-5aa8543af1c5.png">

**Comment by julien51** [comment]
@akeem Could you start working on allowing the new DAI for credit cards? (and maybe write the "guide" on how to add new tokens)

**Comment by julien51** [comment]
Addresses:
- DAI: https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f
- USDc: https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

**Comment by julien51** [comment]
@cnasc Could you change the paywall to allow the DAI, SAI and USDc to be "payable" via CC?

I believe now, even if the config specifies unlockUserAccount as "enabled", we will show "Insufficient funds" for anything but SAI

**Comment by cnasc** [comment]
I think the key issue here will be handling these environment variables:

```javascript
{
  erc20ContractSymbol: process.env.ERC20_CONTRACT_SYMBOL,
  erc20ContractAddress: process.env.ERC20_CONTRACT_ADDRESS,
}
```

We'll really need to be able to pass any number of erc20s and symbols into the paywall.

**Comment by julien51** [comment]
In the paywall, we can probably get rid of these and "hard code" the ERC20_CONTRACT_ADDRESS for which we allow credit card purchases...

**Comment by julien51** [comment]
All fixed!
