### ISSUE TITLE
Address contract warnings

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5406]
**Describe the bug**
CI is reporting the following:
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for initialize
WARNING: Multiple definitions for safeTransferFrom

Spot checking initialize, it appears we are not following best-practices.

**Comment by NickCuso** [comment]
The ZOS recommendation for initialize seems to be make them all public and include the modifier.  Currently we are missing modifiers on a few.

I think that may still cause this warning to emit.  We could also consider changing all them to `_initialize` (or maybe `_initializeMixinName`) and mark them as internal.  Then we don't need the modifier on each of them

**Comment by nfurfaro** [comment]
It looks as though the warnings about `safeTransferFrom` are due to there being a function with this name defined in both `MixinTransfer.sol` & `SafeERC20.sol`. Not sure how we get around this one yet.

**Comment by NickCuso** [comment]
At the moment we are able to call `initialize` in MixinFunds, changing the ERC-20 token type.  This is not a security risk, but it was not intentional.  We should check the other initialize function to ensure they all use the correct pattern.
