### ISSUE TITLE
Newly created locks drop to bottom of dashboard

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5438]
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/9300702/70470619-68df3b00-1a99-11ea-8c95-76f936f7e330.png">

**Comment by julien51** [comment]
Sorting is probably due to the data we get from the graph... Ideally we would need to add the block number in the the schema for locks in the graph. This should not create too many issues as there is alwaays a block number, no matter what version of the lock?

**Comment by akeem** [comment]
Closing as them resolution to this has been merged into master
