### ISSUE TITLE
Bump contract versions & add upgrade test

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5448]
Add a test for v5 and update Unlock and PublicLock versions to 6.

**Comment by nfurfaro** [comment]
The new upgrade test will have to wait until we publish the next package.

**Comment by NickCuso** [comment]
Ah I meant for the v5 test.  It was there and I just fixed the test to bump to the latest in the renovate PR this week.  So we just need to bump to v6 now
