### ISSUE TITLE
View/update metadata in keychain

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5460]
On the keychain, we show all of a user's keys.
Some keys have custom metadata, such as the email address for a newsletter lock... etc.
One feature which the keychain should include is the ability to view the metadata for each key of mine, and if there are custom fields, the ability to update them!

**Comment by smombartz** [comment]
Mockup and prototype are in [figma](https://www.figma.com/proto/ZIhu6WMu781dsGDHszPKb1UT/Keychain?node-id=21%3A57&viewport=-85%2C2428%2C1.6244397163391113&scaling=min-zoom) (click on the i button of the first key)

![image](https://user-images.githubusercontent.com/1377389/72827356-03ae6600-3c51-11ea-9eb1-95e6abbc1b4f.png)

**Comment by julien51** [comment]
For now, the metadata to be collected for keys is not stored on our end. This was a design decision to maintain "decentralization" because we want to avoid making Unlock's API a point of failure (website is slightly different because it is static HTML).

But I think we need to support that. 
The right approach is probably to provide a form where a lock manager can set the metadata to be collected for their lock when using an Unlock front-end. They can then "save" it by signing a message with their wallets that is submitted as an API call to locksmith.

Once that is done, our front-ends (checkout and keychain) should query locksmith to identify if any metadata needs to be saved before the purchase and, in that case, should require the user to enter it.
