### ISSUE TITLE
We should allow lock owner to change the token that the lock is priced in.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#5486]
Use case #1.) A lock has been created and is priced in SAI. The Lock owner now wants to switch this to be priced in DAI.

We should provide a clear path to make this happen, as well as define how refunds/cancelations are handled. This mostly comes down to deciding which token a key purchaser should receive. Ideally if they paid in SAI they should be refunded in SAI, but this presents some challenges:
- there is currently no way to select which token to refund. Whatever tokenAddress is set in the lock contract is what will be used for a refund. We could work around this by adding a `_tokenAddress` param to our refund functions, _BUT_ if the lock pricing is changed to DAI, there's no guarantee that there would be enough SAI left in the contract to handle refunds... as the owner may have withdrawn it. 
For that matter, if I bought a key with SAI, and then the owner switched the lock to be priced in DAI, and then I want a refund immediately, there may be 0 DAI in the contract to grant me my refund.

We could make it so that in order to update the tokenAddress, a few things need to happen. In the SAI/DAI example above:
1.) the lock could retain enough of a reserve of SAI to handle refunds for the owners who paid with SAI
2.) the lock owner has to send the lock contract enough DAI to replace the remaing SAI in the contract, which is transferred to the lock owner.

I'm thinking 1.)would be nice, but maybe too much work for too little value, while 2.) is probably a necessity. Thoughts?
cc @julien51 @NickCuso

**Comment by NickCuso** [comment]
Good point on refunds, but I think we can leave this to the lock owner to manager however they would like.  Functionally it's no more of a risk than allowing the lock owner to `withdraw` all the funds.  

That said, this impact may not be clear / expected - for that I think communicating clearly (and maybe suggesting they fund some DAI) on the frontend is sufficient.

**Comment by julien51** [comment]
Regarding refunds, for now let's only refund in the token that is being accepted *currently* by the contract. If the contract was SAI and is now DAI, but I paid in SAI, if I am asking for a refund *after* the change, I should get DAI back.

We will clarify the process on the UI.

**Comment by nfurfaro** [comment]
Sounds good.

**Comment by julien51** [comment]
Good point. I think it is important that the change of currency implies a change of price too to avoid the problem you highlighted!

Let me know if you have further comments, otherwise, let's do it ;)
