### ISSUE TITLE
Coupons or Discount Codes

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5489]
Locks have a price which can be changed by their owner.
The owner may also want to provide a Coupon or discount code which would let the recipient pay "less" than the actual price.

Conferences have a strong need for that feature: they want to give away discounted tickets to press, students or partners.

A lot could have multiple discount codes, each offering specific amounts. The lock owner should be able to add/remove discount codes.

The discount codes should remain "secret" so they cannot be supplied "in clear" when purchasinga key.

**Comment by NickCuso** [comment]
Do we need to address the cancelAndRefund feature as well?  The refund could be > what they paid if they purchased with a discount code.

For implementation we were talking about using signatures where the signing account is the discount code itself.  So the `signing_account_private_key = keccak256(abi.encodePacked(lock_address, discount_code))`.  The public address for that account is registered in the contract and stored with a structure such as `mapping(address => uint) public discount_address_to_discount_basis_points`.  To redeem the key purchaser uses the signing_account in JS to sign a message locally, maybe `"authorizeDiscount"`.  They include this signature with the purchase transaction: `ecrecover` will provide the public address for the signing account, which we then use to look up the discount.

The lock owner could add, remove, or update entries in the discount mapping anytime.

**Comment by julien51** [comment]
> Do we need to address the cancelAndRefund feature as well? The refund could be > what they paid if they purchased with a discount code.

I think for now we can leave that aside but warn creators that they should set the cancellation policy to take the coupons into account.

I think this approach makes sense, but I do not have a deep enough knowledge of `keccak256`. Is `keccak256` yielding a private key? 
We would absolutely need to sign the purchaser's address, otherwise, anyone could look at any transaction with a discount code and issue the same?

**Comment by NickCuso** [comment]
I'm suggesting keccak256 to hash the lock's address and the discount code itself.  This way there are no assumptions / requirements on the length of the discount code string.

Yes we must sign the msg.sender so that it cannot be reused by another account, but the "authorizeDiscount for" portion is not necessary.

Note that with this approach people could attempt to brute force.  i.e. guess and checking can be done entirely in JS.  So if the discount code is trivial people will be able to determine it (e.g. if there's a `5 off` code people could check to see if `10 off`, `20 off`, or `50 off` works better).

**Comment by julien51** [comment]
That's true but it is the case with any discount code system, crypto or not... and they have no way of knowing if it works before actually sending the transaction?

**Comment by nfurfaro** [comment]
Not done with all the details , but I also don’t want to dive too far down this rabbit hole yet.
Basically I was thinking about how we could use Unlock itself to implement discounts. When the recipient’s ethereum address is know ahead of time discount codes are relatively trivial to get working I think. But, when we don’t know the address in advance, it gets trickier. @Nick (HardlyDifficult) has a proposal to achieve this using ethereum signatures which should work… But I couldn’t help but ponder the options.
First I considered using the Unlock-native discount mechanism (the UDT tokens), but it doesn’t seem to be a great fit.
The next thought was to grant discount-keys to potential key purchasers which would “unlock” a discount for them when they go to purchase a key to an event or whatever. For this to be worth considering, we would need a way for this to work when we don’t know their ethereum address in advance, which is what my original question was getting at.

**Comment by NickCuso** [comment]
> That's true but it is the case with any discount code system, crypto or not... and they have no way of knowing if it works before actually sending the transaction?

It's a little different here because you can extract the discount code's address from the contract and then guess and check locally.  Most discount code systems would require checking via an API, which can then be rate limited to prevent brute-force attacks.

They do know if it works before sending the transaction, and sophisticated users can read a few bits of data from the contract and then guess and check very rapidly without any network requests.  So we should encourage codes with a decent amount of information entropy.

**Comment by NickCuso** [comment]
RE the DiscountLock proposal: this seems to be for free keys(?)  Where in the process would the key purchaser pay x?

**Comment by nfurfaro** [comment]
@NickCuso I updated my comment above as it was still incomplete. But no, not meant for free keys.

**Comment by NickCuso** [comment]
Ah okay I follow now.  The downside, as you noted, is the lock owner needs to issue a transaction given the potential purchaser's address.  Additionally since the discount grant call and the purchase call would be from different accounts, we must wait until the grant call is mined (vs using nonce to sequence the transactions).

**Comment by NickCuso** [comment]
But that said, if the Lock owner has a step in this process - maybe we could use signatures instead.  So the lock owner signs a message such as `give user x discount y`.  The nice part about that solution is it's only one transaction and very flexible, the backend can implement any rules around discounts they want and change them anytime entirely off-chain.

**Comment by NickCuso** [comment]
For either of these approaches (grant discount keys or sign discount messages - n/a to discount code accounts), instead of just a single lock owner account I think we should consider adding an operator role.  That way an operator account can sign messages (or maybe submit grant calls) without holding any ether (or a low amount for gas if making grant calls).

**Comment by nfurfaro** [comment]
As I see it, the piece of this that complicates things is possibly not knowing the discount recipient's ethereum address. 
I do think the lock owner has a step in this process.
I think your idea using signatures (generating the signing account from the discount code itself) is likely the way forward It can be done in one step right? (well 2, but only one for the purchaser) How can we ensure that the codes are hard enough to resist brute-forcing?

**Comment by NickCuso** [comment]
3 options are on the table:
 - Sign with discount code: 1) register discount given the code 2) purchase with discount signature
 - Discount key: 1) create discount lock 2) register discount given the purchaser account 3) purchase and have discount applied
 - Signed discount message: off-chain sign authorization and then 1) tx to purchase with signature

RE brute force attacks, the proposal includes the Lock's address.  So any attacks would be targeted.  Ideally we'd suggest rng with a target of 2^128 bits of entropy, but for most use cases significantly less should be fine.  

The safest, easiest, and most flexible implementation on the table is the signed discount message if we are okay with requiring a back-end service in the mix.  I think the next best is sign with discount code as it's just an email, link, or QR code to distribute the discount code.

**Comment by NickCuso** [comment]
Nick and I had a call on this topic.  ATM we like the signature options.  The next question is about the backend service.  @julien51 What's your thoughts on the "signed discount message" approach? -- it requires a backend service to have a private key with permissions to offer discounts.  To purchase, JS would request the discount message and signature from the service and include that info with the contract purchase call.

**Comment by julien51** [comment]
I like the signature approach too, BUT I am not sure I understand why we need the private key on the backend server?

If the Discount code can be used to "seed" the private key, then we should be good one, should;t we? We would then store the public key on the lock with the mapping to the amount of discount? As explained above?

**Comment by NickCuso** [comment]
Yea.  Sorry for the confusion.  We are debating two signature based options with different requirements and features.

"Sign with discount code" - the discount code is used to derive a private key and that's used by the key purchaser in local JS to create a signature to send to the contract authorizing a discount.

"Signed discount message" - a backend server holds the private key for an account which is approved in the contract as an operator.  using any rules the server desires, they can approve a discount by signing a message such as `give user x discount y for lock z`.

Pro sign with discount code: decentralized / no server component
Pro signed discount message: only one tx per purchase (vs registering each supported discount code), flexible and easy to update

**Comment by julien51** [comment]
I think the first approach is better. The creator can add/remove discount codes as they please without involving us ;)

**Comment by julien51** [comment]
Let's depreioritize this in favor of some other more important additions for now!

**Comment by NickCuso** [comment]
An initial version of discount codes is now available: https://github.com/unlock-protocol/unlock/blob/master/smart-contract-extensions/contracts/unlock-examples/hooks/CodeRequiredHook.sol

But that said this initial implementation is limited. And we are looking to redesign the hooks feature.

**Comment by NickCuso** [comment]
This is done, reopen if there was anything we missed.
