### ISSUE TITLE
Not prompting for MetaMask

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5518]
Our paywall application prompts for MetaMask the moment it is loaded. This is a sub-par experience because people may not necessarily have an understanding of why they are being prompted.

On the other end, if we wait for users to actually perform an action to get their identity (by prompting the wallet), we end up in a situation where we cannot assess whether the users have already unlocked the content... which, if they did, would be another bad experience.

**Comment by julien51** [comment]
@cnasc implemented a clever solution which consists of 2 steps:

1. caching (localstorage) the address of the user if it is known

2. upon loading
* if no identity is known/cached: 
  * emit the "locked" event
  * skip initialization of the paywall application, until the user performs an action
* If an identity is known, resume normal loading, as the user has already "connected" their wallet, so the wallet should not prompt.

**Comment by julien51** [comment]
It's now time to test this on staging using the followin scenarios:
1. no crypto wallet (Safari)
   * Nothing should happen, until the user clicks on the "unlock" button.
   * page state should be "locked" 
   * The "no wallet" message should be shown.
2. crypto wallet, user has *never* approved the site
   * Metamask should not prompt the user when the page loads
   * page state should be "locked"
   * When the user clicks on the "unlock" button:
      * MetaMask should prompt to connect
      * The checkout modal should open
      * Page state should be "locked"
3. crypto wallet, user *already* approved the site, but did not purchase
   * Metamask should not prompt the user when the page loads
   * Page state should be "locked"
   * When the user clicks on the "unlock" button:
      * The checkout modal should open
3. crypto wallet, user *already* approved the site, and previously purchased a key
   * Metamask should not prompt the user when the page loads
   * Page state should be "unlocked"
      * The checkout modal should open

**Comment by julien51** [comment]
In test case 1. I can confirm that indeed, there is an issue where the first time the clicks on the button, nothing happens. The second time, it does load the modal. Everything else is happening has expected. (more below)

Case 2. ✅
Case 3. ✅
Case 4. ✅

**Comment by julien51** [comment]
My understanding of the issue is 1. is that the `PostMessages.UPDATE_ACCOUNT` [event may not be triggered when there is no web3](https://github.com/unlock-protocol/unlock/pull/5517/files#diff-c3b2363f95c0188b18fdd376bda9349dR118), because indeed, there is no account...

Now, I wonder if it is strictly required to have this event having been triggered to open the checkout modal? Maybe @cnasc could clarify here.

**Comment by cnasc** [comment]
> the `PostMessages.UPDATE_ACCOUNT` event may not be triggered when there is no web3

Yep, that's an oversight on my part. The reason it's there is to delay showing the checkout until we've received lock info, because without it we'd see a brief flash of the no wallet screen.

**Comment by cnasc** [comment]
I think the solution is to move the code we did earlier for checking the cached account address: https://github.com/unlock-protocol/unlock/blob/636a851ff1b479279248fffe9a4c683ed47c6d5c/paywall/src/unlock.js/startup.ts#L81

I'm pretty sure all the code we need is written, we just need to get the sequencing right.

**Comment by cnasc** [comment]
It looks to me like #5519 fixed this, but I would appreciate independent confirmation on that

**Comment by julien51** [comment]
This, indeed is fixed!
