### ISSUE TITLE
Reduce the number of net version calls being made in production

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#5526]
After some inspection, it looks like we are making a ton of 'net version' calls that do not need to be made. 

We have isolated a probable case of the issue;  the instance of provider being used does not provide the network requiring an additional call to be made. 

An adjusting passing the network should ideally resolved the issue. 

https://docs.ethers.io/ethers.js/html/api-providers.html

**Comment by cnasc** [comment]
We can pass the network as the numeric chain ID: https://github.com/ethers-io/ethers.js/blob/4ac08432b8e2c7c374dc4a0e141a39a369e2d430/src.ts/utils/networks.ts#L13

We have the expected network id for each environment baked into the config when we compile the data iframe: https://github.com/unlock-protocol/unlock/blob/master/paywall/src/data-iframe/constants.ts

And we pass those constants into Web3Service's constructor: https://github.com/unlock-protocol/unlock/blob/d3810491aa39b3450cc78c955904259de92629e7/paywall/src/data-iframe/Mailbox.ts#L214

So we can probably just check in Web3Service what gets supplied, and if `defaultNetwork` is there, pass it as the final param on the constructor.

**Comment by julien51** [comment]
The `net_version` calls have been previously identified: #5285
