### ISSUE TITLE
WordPress Unlock Blocks Not Displaying on Wordpress Website

### ISSUE THREAD

**Issue by Richardbelluk** [unlock-protocol/unlock#5539]
Hi there, love the product, really easy to set up and install.

**Issues:** Paywall is not displaying (aka working for me) in Wordpress on www.layabell.com

**Set Up** I'm using Bitnami , on AWS Lightsail, with the theme [Clean Fotografie](https://catchthemes.com/themes/clean-fotografie/) (not the pro) I have also tested many other themes and still get same issue.

**Steps taken:**
1) Set up Lock on Unlock's a site
2) Installed Unlock WordPress Plug in
3) Configured Lock code in Plug In on Word Press
4) Implemented Block for Paywall & for Sign Up above content I want to Paywall

WordPress Edit Mode Screen Shot with notes

![image](https://user-images.githubusercontent.com/23599353/71316831-a1bfdc80-24a9-11ea-91c5-68fb45d6d731.png)

WordPress Edit Viewing Mode  Screen Shot with notes
![image](https://user-images.githubusercontent.com/23599353/71316859-0844fa80-24aa-11ea-9a1d-78cf8d0d8b60.png)

Look forward to any advice you have.

Richard

**Comment by julien51** [comment]
Hello @Richardbelluk 
Thanks for opening this!
Unfortunately, I am not sure I can understand exactly what is going on here.

That said, I just pushed a new update to the plugin (1.6) which improves the button, so thanks for this!

Maybe the best is to create new "temporary" page on which you would put the locked content before you actually put that in a real page. You could share that temporary page with me so I can look things up?

I have done the same thing on our own WP demo blog: https://wordpress-demo.unlock-protocol.com/

Here is how things look like in the editor for me:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/17735/71324101-c49dc100-24a8-11ea-80ce-d7a8a4b8317e.png">


To add an "Unlock" block just click on on the ⊕ button in the top left corner:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/17735/71324107-ea2aca80-24a8-11ea-9353-36835153d1a4.png">

Once the block has been added, you can configure it to be shown/hidden only for members or non-members in the right column:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/17735/71324119-02024e80-24a9-11ea-94eb-687f535dbc2e.png">


In each Unlock block, you can put any content you want, including images, text, or even button... like the "Checkout button".

**Comment by Richardbelluk** [comment]
Thank you, it's now working. I think I was at error, I did not put my
content in the Block, I placed it below the Unlock Block in a new Block. I
also updated the Plugin before I managed to get it working. Richard

**Comment by julien51** [comment]
Awesome! Please, let us know if you need more help ;)
It looks like our timezones are reversed but I am happy to provide any help I can!
