### ISSUE TITLE
Minor Documentation Typo 

### ISSUE THREAD

**Issue by Richardbelluk** [unlock-protocol/unlock#5540]
**Describe the bug**
Minor Error on Documentation Page: 
![image](https://user-images.githubusercontent.com/23599353/71320683-5aedd900-24e1-11ea-9c4d-5d5b913d9840.png)

**To Reproduce**
Visit: https://github.com/unlock-protocol/unlock/wiki/Integrating-Unlock-on-your-site

Text Reads:'For example, a visitor might purchase a key while they are on the page, going from the unlocked to the locked state.'

Think Locked and Unlocked are in wrong order.

**Expected behavior**
Think it should read: ' For example, a visitor might purchase a key while they are on the page, going from the locked to the unlocked state.'

**Comment by julien51** [comment]
Oh! Thanks a lot! this is now fixed.
