### ISSUE TITLE
Signing in Dapper

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5549]
Our newsletter requires the use of a wallet which is able to "sign" requests to save and retrieve email addresses.
Wallets use different types of signatures which creates issues when we try to verify the signature on the backend. We already have fixed handling of these in some wallets, but it looks like Dapper is still not working.

**Comment by akeem** [comment]
From research, it looks as though we do have a path forward with support for Dapper.  Dapper requires backed support of EIP 1654. 

https://support.dapperlabs.com/hc/en-us/articles/360035463853-Ensure-EIP-Connection

**Comment by julien51** [comment]
Closing as I think Dapper's wallet will never be very relevant.
