### ISSUE TITLE
Difficulties with running the code on Windows 10 Pro

### ISSUE THREAD

**Issue by gyrevik** [unlock-protocol/unlock#555]
I had a Python related error for which I found a fix. It was to run:
npm install --global --production windows-build-tools
The solution comes from:
https://github.com/felixrieseberg/windows-build-tools/issues/56

I then ran into a Windows Script Host error dialogue for truffle.js with Code: 800A138F

There is information about this on the web but I did not resolve it on my laptop.

I don't know if it's worthwhile to change the code base to make it easy to run on Windows 10 Pro. Just thought I'd document this because it appears to be pretty difficult to get the code to run this way.

**Comment by julien51** [comment]
I think it would be nice to get to the bottom of this! 
My understanding is that this is an issue with truffle on Windows, right?

**Comment by julien51** [comment]
Closing this one since I believe it is the same as #594 which is more documented.
