### ISSUE TITLE
Key transfer rights

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5557]
In the current implementation of our keys, only their owner can transfer them.
We need a more flexible approach where a specific address can "own" the transfer rights and that address can be different from the key owner.

This enables these 2 scenarios:
1. Lending keys. As a user I want to be able to "lend" a key to someone else. By transferring ownership to them, but by keeping the transfer rights to myself, I can easily reclaim the key when I need it back!

2. key in CDP. A key has a secondary market value. As a user, I could transfer the key transfer rights to a CDP and get some of the key price back. If I maintain the collateralization ratio, then I can keep owning the key and pay it "back" as time passes. If I fail to pay it back, someone else can liquidate it and sell it on a secondary market.

**Comment by julien51** [comment]
Similarly, it would be interesting to have a reflexion around the rights to change the beneficiary of a lock. Right now, it can be changed by the owner (or the beneficiary) but it would be interesting to limit the ability to change the beneficiary to another 3rd party address (multi sig for example!)

**Comment by julien51** [comment]
We discussed this wih @akeem today. Another use case would be for the lock owner to delegate `grantKey` to a (trusted) 3rd party address.

Ideally, we'd need a very flexible solution where the lock owner can grant access to any function to any address, with a mechanism where it keep tracks of authorized users for functions y keeping track of hashes(function signature, user address) and a modifier on function could check if that mapping exists.

**Comment by NickCuso** [comment]
The challenge here is for the CDP scenario we need to ensure that the original "owner" of the key no longer has permissions to transfer (vs just adding an account with transfer privileges).

Could we get clarification on the requirements to enable a CDP?  I'm not clear on what calls they will be making to our contract in order to make this possible.

**Comment by julien51** [comment]
Let's not focus on the CDP use case for now.
I do think this will be important for "loans", but that needs to also include restrictions on cancellations as well.

This would also be (very) useful in the context of keys purchased thru credit card transactions. The keys purchased this way should only be transferable/cancellable by the purchaser (not the beneficiary) by default. This will make credit card purchases much safer.

**Comment by NickCuso** [comment]
We could add a transfer/cancel hook, similar to the hook on purchase.  That callback could add transfer rules, reverting the tx when they don't have permissions.  Then we could launch a new contract with custom logic - e.g. I think for this use case we could say something like if purchased by x then apply the restriction.

**Comment by julien51** [comment]
This feature would also be very useful in the context of credit card purchases, where the purchaser retains the right to cancel/transfer keys by default, preventing abuse (stolen credit cards used to purchase keys which are then canceled to get a refund in crypto...).

**Comment by nfurfaro** [comment]
@julien51 
>We need a more flexible approach where a specific address can "own" the transfer rights and that address can be different from the key owner.

I agree with this. We could always leverage the "Roles" pattern from openZeppelin ( which we already make use of in `MixinLockManagerRole.sol`).
There could be a `TransferRights` role which is automatically assigned to each key Purchaser, but not to recipients of granted keys. Then when transfering a key we would check that the caller both owns the key AND has the TransferRights to do so. 

It's just one possible approach , and there would be some edge cases to work out the logic for.

regarding use case 1, "Lending keys"
I'm just wondering how much value this adds, considering that we already have "shareKey" functionality?

**Comment by julien51** [comment]
The current state is that we are going to implement the "KeyManager" 'status'. It is not quite a role because there can be a single keyManager per key. 

* By default on regular purchases, it is assigned to the sender of the transaction (most often the key owner, but in the context of a key being bought by someone else, it needs to be the sender, not the owner).
* By default on keys granted, it needs to be assigned to the grantor, not to the key owner.

The keyManager has the following rights:
* transfer (full or partial) of the key to another user
* cancellation of the key
* replace the keyManager

This is critical piece for our better support for credit cards which means that this should take highest priority.

**Comment by nfurfaro** [comment]
A couple other scenarios I want to document & confirm here:
1.) function `shareKey`
  When a key is shared, the Parent key's keyManager becomes the child key's keyManager as well.
2.)function `TransferFrom`
  When a key is transferred, the keyManager status should be transferred to the recipient.

wdyt? 
cc @julien51 @NickCuso

**Comment by NickCuso** [comment]
1) Maybe make it an option, like with `grantKey`
2) sounds good
