### ISSUE TITLE
Drupal integration

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5561]
[Drupal](https://www.drupal.org/) is one of the most popular CMS out there. It is being used by a lot of websites in the publishing space and more. The Drupal community has also been pretty crypto-friendly a[s drupal.org is a Brave verified publisher](https://www.drupal.org/project/drupalorg/issues/2915979)!

Unlock is a protocol for membership that lets any creator easily monetize their content in a frictionless way by letting them deploy "locks" (smart contracts) and then sell keys (NFT) to unlock the content or features that the creator wants to charge for access.

We need a [Drupal Module](https://www.drupal.org/project/project_module) to make it really easy for creators using Drupal to lock some parts of their web site. 

User stories:
- As the owner of a Drupal site, I want to limit access to some of my content (text, images or more) so that only my lock's members can view the content itself, using one or more locks.
- As the visitor to a Drupal site, I am not able to view the locked content unless I own a valid key for the corresponding lock(s).
- As a visitor, if I do not own a key, the site has a button that lets me purchase one.

**Comment by julien51** [comment]
Relevant links:
* [Unlock Documentation](https://docs.unlock-protocol.com/)
* [WordPress plugin](https://wordpress.org/plugins/unlock-protocol/) which offers the same functionality.

**Comment by chiro-hiro** [comment]
Hi @julien51,

I think If we develop a PHP package could help other PHP developers who had experience in CMS like Joomla, Drupal,... could help us in the integration.

**Comment by mikedotexe** [comment]
> Hi @julien51,
> 
> I think, If we develop a PHP package, It could help other PHP developers who had experience in CMS like Joomla, Drupal,... could do the integration easier.

Good thought, but in my 7 years of Drupal experience, you need to use the framework capabilities. I don't see a way to have a one-size-fits-all PHP solution.

**Comment by julien51** [comment]
@mikedotexe Please feel free to share progress on this issue ;)

**Comment by mikedotexe** [comment]
Hey @julien51 sure thing.
I've got the custom block, the settings page to enter the lock address, which is using the Drupal 8 exportable config like you're supposed to. On Monday I was able to see the console's, 

`Unlock: visitor is not a member`

But now I'm having a hard time seeing that again. I've been toying with the order of js (namely the external js file and the `unlockProtocolConfig` variable) but seems to be off, so I'm working on that.
The button to attach to the wallet is not up yet, so I can do that in the meantime, as well as make sure the WYSIWYG works with the custom block.

This was an interesting clue on a difference that I'm seeing between Drupal and Wordpress. In the console, the `unlockProtocol` object is from the external js. If you have thoughts, feel free to chime in. If not, I'm sure I just need to keep cracking at this.

![Screenshot 2020-01-15 18 17 39](https://user-images.githubusercontent.com/1042667/72488159-fd3d6b80-37c4-11ea-9395-d038bc031cf0.png)

**Comment by mikedotexe** [comment]
@julien51 Complete here:
https://github.com/mikedotexe/unlock
I'll start the process of getting it on drupal.org
Also in discussion with friends who own a nice-looking Drupal 8 site for demonstration purposes.

**Comment by mikedotexe** [comment]
Module up on Drupal here:
https://www.drupal.org/project/unlock
I've gone through the process of requesting a security review here:
https://www.drupal.org/project/projectapplications/issues/3107269
and pinged some folks in a Slack channel who soft-volunteered to help take a look.

**Comment by julien51** [comment]
Oh wow! Thanks a lot @mikedotexe ! I will review all this tomorrow and get back to you!
Good luck on your first day at the new job ;)
