### ISSUE TITLE
Consider using styled-jsx

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5570]
[Next includes `styled-jsx`](https://nextjs.org/blog/styling-next-with-styled-jsx), which may be interesting to us. It might be a bit easier than using `styled-components`, and as we're evaluating the unification of our visual design in the cleanup we should consider it. Mildly reduces dependency load, keeps styles close to where they're used. _May_ make stories break less frequently?

https://ricostacruz.com/til/styled-jsx-is-awesome

**Comment by julien51** [comment]
How heavy would be the move?

**Comment by cnasc** [comment]
For the most part it would just involve copying the definitions from our styled components into style tags in the component.

We're writing CSS either way, it's just a different (probably more familiar) way to do it. It may also be nicer, because your editor should realize you're in a style tag and give you some help editing CSS, as opposed to `styled-components` where you're just editing a multiline string constant.
