### ISSUE TITLE
CI: truffle-flatten, compile, and assert

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5622]
**Is your feature request related to a problem? Please describe.**
truffle-flatten worked for us before, now it does not without a few modifications.

**Describe the solution you'd like**
Fix it and then add a test.

Maybe flatten, compile the flattened contract, and assert the bytecode matches.  Or something along those lines.

**Comment by julien51** [comment]
Now that we moved to hardhat we have a tasks which does verifications :)
