### ISSUE TITLE
Bump contract version to 6

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5650]
**Is your feature request related to a problem? Please describe.**
We released v5 contracts.

**Describe the solution you'd like**
Update the version identifier to 6 and add the appropriate tests.

**Comment by nfurfaro** [comment]
version identifiers have been updated to 6 in both Unlock and PublicLock.
As for adding the tests, we already have a test file for updating from v5 to the latest. We can't test for `v6=>latest` until we publish the v6 package.

**Comment by NickCuso** [comment]
done
