### ISSUE TITLE
Ability to require metadata before purchases

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5693]
Our paywall needs to let the creator customize the data that needs to be collected before initiating the purchase (similar to what we do for ethCC and the newsletter for example).
Thru configuration (syntax TBD) the lock creator can indicate a list of fields/type.

This data needs to be saved in the token and once saved, the paywall should issue the key purchase transaction(s).

**Comment by julien51** [comment]
This will leverage the work of #5701

**Comment by smombartz** [comment]
Here's the metadata paywall view. One question: in the case of user accounts, where we already have the email – is there a way not to have to ask the user again for their email during a metadata request?

![image](https://user-images.githubusercontent.com/1377389/72760212-6ac70e80-3bae-11ea-8ad2-1e0e8464127b.png)

[in Figma](https://www.figma.com/file/YIvjlf89MZAXTFuBYXI3fv/Paywall-2?node-id=116%3A2848)

waiting for any feedback and clarification on the above UX regarding the email, will then mockup the interactive flow.

**Comment by julien51** [comment]
> Here's the metadata paywall view. One question: in the case of user accounts, where we already have the email – is there a way not to have to ask the user again for their email during a metadata request?

Probably... we can pre-fill this if we have it.

**Comment by julien51** [comment]
Can you show UI with say a checkbox, and a select as well?

**Comment by julien51** [comment]
note that login/Use web3 will need to happen *before* we show this, so there is no need to show these links/buttons on that page,

**Comment by cnasc** [comment]
A while back I had already done the inputs for this component, looks like they're essentially what we have in mind here: 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/9300702/72817472-d5705c80-3c37-11ea-8184-773de502c6f7.png">\

Note that the inputs in my screenshot have types associated with them, so the date input opens a date picker, the color field opens a color picker, and the email and URL inputs should be validated by the browser

**Comment by julien51** [comment]
this is done! Thanks @cnasc 🎉
