### ISSUE TITLE
Port metadata storage and retrieval functions to unlock-js

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5701]
Currently we have [implementations of these operations](https://github.com/unlock-protocol/unlock/blob/master/newsletter/utils/token.js) in the Newsletter. We can move these into `unlock-js` and make them a bit more generic.

- [x] less manual work, take advantage of existing signature methods in `unlock-js`
- [x] make them more generic, allow storing and querying arbitrary values
- [x] support storage of metadata for keyholder
- [x] support storage of metadata for lock owner

This will enable us in the immediate future to mark tickets as checked in, and should make it easier to work with metadata for other uses in the future. One interesting feature I discussed with @akeem earlier is making an internal test page where we can stick metadata on a token, which can be a bit easier than using the scripts we have in `locksmith`

**Comment by julien51** [comment]
This is going to have a large impact in several parts of the app, which is exciting:
* the [paywall will be able to "collect" data before a user purchases a key](https://github.com/unlock-protocol/unlock/issues/5693)
* the keychain will be able to show the data that a token has stored (as well as maybe edit it!)

**Comment by cnasc** [comment]
This is done!
