### ISSUE TITLE
Remove unlock-js based unlockProvider references in unlock-app

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5706]
When we migrated unlockProvider back to unlock-app, we should have cleaned up any references to the old code. As it stands, developing unlock-js with unlock-app as a testbed is impossible until old references are removed (it will fail to build with a locally-installed unlock-js)

In particular, we need to remove:

```javascript
import {
  createAccountAndPasswordEncryptKey,
  reEncryptPrivateKey,
} from '@unlock-protocol/unlock-js'
```
from storageMiddleware.js and 

```javascript
import { reEncryptPrivateKey } from '@unlock-protocol/unlock-js'
```
from providerMiddleware.ts and replace them with the versions that are inside unlock-app.

**Comment by julien51** [comment]
huhhhh, I thought I did that. sorry about missing some :/

**Comment by cnasc** [comment]
No worries, quick fix
