### ISSUE TITLE
We should review and update our deployment/upgrade checklist. 

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#5741]
Currently, we have the details on how this is done split into 2 locations:
1.) The wiki - https://github.com/unlock-protocol/unlock/wiki/Releasing-a-new-version-of-the-contracts
2.) A google doc - https://docs.google.com/document/d/19dZcB2M3N-A-WHDrNeUNioZ11gFH3_sVVzfYSqQZvAk/edit#heading=h.9w04gbdhauvm

This should maybe be consolidated and have all steps correctly numbered to facilitate a simple to follow flow. 
It may be nice to have some of the steps organized more clearly by subsections such as "**Once Per Network**" and "**Once Per Upgrade**"

**Comment by julien51** [comment]
oh wow, I have not been using the Google doc to make deploys. Is there anything relevant/useful in there? Otehrwise let's add a big "DEPRECATED" message at the top :)

**Comment by nfurfaro** [comment]
It has some good reminders of what needs to be done once per network, an example tranaction for the multisig upgrade, etc.... I could port the relevent bits to the wiki if we don't mind making this public? It has our multisig wallet address and stuff in there, but nothing that's not visible on etherscan. Will let you decide... I could also just clean up this doc and keep it internal to the team for reference.

**Comment by julien51** [comment]
Yes, please merge the applicable bits if you can and let's "DEPRECATE" the good doc ;) Thanks!

**Comment by nfurfaro** [comment]
will do.

**Comment by nfurfaro** [comment]
Ok, the old doc has been marked as deprecated, and I've added a new wiki page for adding a new network here: https://github.com/unlock-protocol/unlock/wiki/Supporting-a-New-Network
