### ISSUE TITLE
Granted keys should not be transferable/cancellable by default

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5753]
In the past we have discussed challenges around granted keys. I believe that, by default, keys which have been created thru the `grantKeys` step should not be transferable/cancellable by their owner.

This should leverage the [work done on this issue](https://github.com/unlock-protocol/unlock/issues/5557).

However the grantor (or lock owner) should be able to revoke that limitation, if they want.

**Comment by nfurfaro** [comment]
Closing, as this was fixed/implemented by #6178.
