### ISSUE TITLE
`/unlock.js` loader

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#578]
Unlock provides a snippet of codes to creators which will enforce that a given visitor to their site has a key. If they don't, the the snippet will display an overlay indicating showing the options to purchase a key.

The overlay has been implemented (see the demo page on each lock) but we need to implement the loader itself.

**Comment by julien51** [comment]
The loader should be fairly limited in its complexity and achieve the following:
* load an iframe from the `unlock-protocol.com` origin.
* wait for the iframe to indicate whether the content should be locked or not.
* if the content needs to be locked, will display the iframe *over* the content's, and disable scrolling on the page
* if the content does not need to be locked, will display the content of the iframe too, but this time the iframe will only show the Unlock button.

The loader's Javascript should not change often. We eventually expect to cache the loader extremely aggressively (using a ServiceWorker as well as propagation through CDNs). 

We should also consider a deploy of that loader to IPFS.

We can/should expect some website owners to even duplicate the loader locally (instead of loading it from `unlock-protocol.com/unlock.js` or IPFS.

**Comment by benwerd** [comment]
Additionally, the loader should be waiting for the DOM to be ready before attempting to cover an area of the screen with a lock iframe.

**Comment by benwerd** [comment]
Implemented in #699 (based on @julien51's original), with an optional decentralized URL for the overlay to be stored in `window.unlock_url`. A deploy to IPFS (and dat!) would certainly be possible at this point, but we should wait until #700 is implemented.
