### ISSUE TITLE
Balance for ERC20 tokens is not properly injected for managed accounts

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#5812]
**Screenshots**
<img width="656" alt="image" src="https://user-images.githubusercontent.com/9300702/73103826-f6001700-3ec2-11ea-9bb0-9236f5e0c325.png">

Unlock user accounts should have a sufficient balance of ERC20 tokens that are handled by the locksmith purchaser. It looks like the code that injects this default balance no longer handles `WEENUS` (at least) appropriately.

PR that probably introduced this: https://github.com/unlock-protocol/unlock/pull/5808

**Comment by julien51** [comment]
Ho I think it is because the WEENUS address is not in the list of ERC20 contracts for which we would allow the purchaser to make a purchase!
In other words, it's just staging that is broken.
