### ISSUE TITLE
Do not revert read-only calls

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5836]
**Is your feature request related to a problem? Please describe.**
Some read-only calls revert under certain conditions, such as if the user's key is expired.  This may be too limiting for some use cases.

**Describe the solution you'd like**
Never revert read-only calls, unless maybe there is no other possible valid response.

**Describe alternatives you've considered**

**Additional context**

**Comment by NickCuso** [comment]
e.g. this makes integration difficult https://github.com/unlock-protocol/unlock/blob/d7093149e24fe27c1d771f6b5dab52361743602d/smart-contracts/contracts/mixins/MixinKeys.sol#L204

**Comment by nfurfaro** [comment]
@NickCuso What are your thoughts on accessing arrays out of bounds in the context of this issue? For example:
`function tokenByIndex` has a require statement: `require(_index < _totalSupply, 'OUT_OF_RANGE');`
I could remove this, but I would generally thing that the error message would be more helpful than a generic failing assertion. There are a few such cases I'm finding as I scan the codebase.

**Comment by nfurfaro** [comment]
Ah, good catch. I glanced at the interface but should have checked the actual EIP on this.
I'd be ok with simplifying the code as a general best-practice in this context. If it becomes an issue for integrations then revisit.
