### ISSUE TITLE
Missing lock address when deployed

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#585]
On staging, when a new lock is deployed it looks like its address is not saved in the redux store...

**Comment by julien51** [comment]
Right now, we only set the lock address when the `NewLock` has been triggered, which means that if the user closes the window before that event has been triggered, we will not be able to keep track of the lock address.

It looks like the `NewLock` event is actually never triggered on rinkeby.

However, we keep track of the transaction id right after it's been submitted, which means we can use the transaction to check for the trigger events.

**Comment by benwerd** [comment]
I've been looking at this this morning, and I'm confused as to where we should go find the transaction details. My assumption is that we should check on a transaction confirmation if the lock's address hasn't been set yet, and then go and backfill, but what do you think?

**Comment by julien51** [comment]
Sorry for the delay. I think you have the right idea... I'll check whether the recent changes in web3Service actually fixed that! (when the app starts we check each transaction and trigger the event which we might have missed...)

**Comment by julien51** [comment]
I believe this is solved.

@benwerd can you confirm on your end too?

**Comment by julien51** [comment]
Closing.
