### ISSUE TITLE
Blog engine!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#586]
We believe it is important that unlock publishes content on its domain and website (and later syndicates to other platforms such as Medium).

This means we need a way to handle publishing posts using the web application.
We want these posts to be in markdown format and script which builds the static post pages upon builds.

**Comment by benwerd** [comment]
There's a lot involved in a blog engine. It might be worth taking Ghost or Jekyll and running them in a subdomain? eg blog.unlock-protocol.com.

**Comment by julien51** [comment]
meh. more code to maintain :( I think we can actually go pretty far with just our current web app. I think we actually do not need to implement much since we can assume most "social" features will be implemented on cross posting platforms!

**Comment by julien51** [comment]
Here is a more complete description of what we are looking for.

1. We use Markdown to "write" our posts. This should be a fairly 'standard' flavor. The markdown templates should use a format similar to what jekyll does, which means that they *may* include a set of metadata in their top part in a YAML block (see [front-matter](https://jekyllrb.com/docs/front-matter/)). These metadata will include at least 3 fields: `slug` and `publishedDate` as well as a `published` boolean value which indicates whether the post has been published or should be considered as draft. Optional fields include `summary`.

2. The posts are then rendered by our next.js application when the path starts with `/blog/<slug>`. The slug will be used to identify which post needs to be displayed. 

3. On a post page, we need to link to the blog's landing page: a page at `/blog/` which shows a reverse chronological order of the posts's excerpts. For now, we do not need to provide pagination on that page (given that the number of posts will be fairly limited). Each post will see its title, and excerpt and a link to the post page. The excerpt should use the `summary` metadata from the post or should be generated (using the first paragraph of the post)

4. Both the posts page and the blog landing page should be server side rendered.

We are intentionally using a limited feature scope here. One the key design decisions is that this blog will have the "canonical" information but we can/should expect its content to syndicated to other platforms and consumed there.

**Comment by julien51** [comment]
Please do not start to work on this unless you have been previously approved by our team to work on this.

We reserve some of our issue for applicants to our full time positions. Thanks for your understanding.

**Comment by vikaskyadav** [comment]
Why aren't we opting for `wordpress`? I know it sounds a little crazy but yeah, wordpress is used when we don't want to do any extra effort. It now has Gutenberg editor as well. PLus, you people might be able to do other stuff such as `Weekly Newsletters` and handling of social media.

This is just my opinion. Although, I too haven't worked with wordpress much but yeah did it for `gitcoin` a few months ago.

Adding to @julien51 's comment, we can also use [gatsby](http://gatsbyjs.org/). We can write content in markdown. It takes care of all the other aspects such as SSR, SEO and a lot can be done as it is built in a very modular way.

**Comment by julien51** [comment]
I strongly think that Wordpress would be completely overkill. The purpose of this very basic engine is just to host the content's canonical source under own own domain. Everything else is superfluous at this point.

However, we could alos set up a wordpress.com blog and syndicate from here! [POSSE](https://indieweb.org/POSSE) ;)

**Comment by julien51** [comment]
@benwerd any progress on that one?

**Comment by akeem** [comment]
@julien51  I believe that it was addressed here: https://github.com/unlock-protocol/unlock/pull/1523

**Comment by benwerd** [comment]
Pages are to follow today.
