### ISSUE TITLE
Events should ONLY be defined in contracts.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#5866]
We currently have some events defined in contracts, some in interfaces, and some events are defined in both places. For consistency, and to avoid comments and or event definitions getting our of sync, we should move towards only defining events in one place.

I think we should proceed with only defining events in contracts.

**Comment by NickCuso** [comment]
hmm I think I'd prefer just one interface file to keep it simple.  i don't think we'll get circular dependencies -- do we?

**Comment by NickCuso** [comment]
the other option of course is no events in the interface.  they are not really necessary, just acts as documentation..

**Comment by nfurfaro** [comment]
> i don't think we'll get circular dependencies -- do we?

We do. 

I'd be fine with your other suggestion about no events in interfaces though. This would be simpler and still achieve the goal of not having duplicate definitions.
