### ISSUE TITLE
Beneficiary can only be changed by beneficary

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5878]
In chatting with the folks at mapple.finance we discussed the challenges around the fact that the lock owner can change the beneficiary if it's not them.
If the lock owner can arbitrarily change the beneficiary it is harder to guarantee that the beneficiary will actually get a proceed of the funds. 

We should make things such that only the beneficiary can change the beneficiary.

**Comment by julien51** [comment]
Maybe worth having a discussion about this though because it may present issue that I am overlooking!

**Comment by nfurfaro** [comment]
@julien51 Definitely worth discussing this.. I'm not sure I understand their (mapple.finance) use-case though?
My take on these permissions is that the lock owner is the highest level of authority, and should be able to revoke beneficiary status at any time. But, it sounds like this isn't meeting their requirements here.

**Comment by julien51** [comment]
Hey! It's not just them ;) I actually think it is a bad idea to have the lock owner be able to change the beneficiary arbitrarily if they have previously decided that it should be someone else.
Basically, by default, yes it should be the lock owner. But, if the lock owner changes it to someone else, then, the lock owner should not be able to "revoke" that change. Otherwise, what's the point of having a beneficiary?

For mapple (but again I can see this being used in other contexts): a creator can deploy a lock and then sell "bonds" to capture revenues of the lock. The contract which manages the bonds should be the beneficiary so that the bond subscribers can then receive their share of the keys sold. If the lock owner can arbitrarily change this, then, the bonds holders are losing their _guarantee_ that they can be repaid from the proceeds of the lock.

**Comment by nfurfaro** [comment]
Yeah, I can see the reasoning behind it in that context.
I was thinking of a different type of scenario, where a creator/lock owner creates a lock and sets the beneficiary to be a spouse, child, charity, etc. After some time, the lock owner decides that they want to contribute to a different charity. In this case, I think the owner should retain the power to do so. Ideally we can support both types of use case. For a more general discussion around permissions I opened a new issue here: https://app.zenhub.com/workspaces/unlock-5bfd5c894b5806bc2bf85d03/issues/unlock-protocol/unlock/5885

**Comment by nfurfaro** [comment]
cc @julien51 @NickCuso I will move ahead with this, changing the `updateBeneficiary` function to be callable by only the beneficiary.
