### ISSUE TITLE
Lock Permissions Review

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#5885]
Currently, the state of permissions/access control in the lock contract is somewhat inconsistent.
We're using a mix of:
- Ownable - A single "root" account with infinite power
- Role Based Access Control - via openzeppelin's Roles.sol /& our `LockManagerRole`
- custom modifiers - `onlyOwnerOrBeneficiary`, 
oh, and of course, posesion of a key grants certain access (to functions) rights in our system.

openzeppelin doesn't use `ownable` in their contracts anymore, as they find the Roles pattern more flexible, and can be tweeked on a more granular level. https://docs.openzeppelin.com/contracts/2.x/access-control#usage-in-openzeppelin

While I think Object Capabilities is very promising as a security model, I don't think there's a ready-made solution yet which we could adopt. Here's a good read on the current state of ocap's in ethereum:
https://ethereum-magicians.org/t/ethereum-object-capabilities/3035
And a link to the framework metamask is going to be using for their new permissions model:
https://github.com/MetaMask/rpc-cap
At the moment it would seem that the openzeppelin Roles approach is probably the best ready to go solution. We could look at implementing it consistently throughout the lock contract, and as a first step we might sketch out what this would look like in a google doc. 

That said I'm open to other ideas/approaches. The one concern I have is that as we continue to add /support new functionality for ever more specific use-cases, our permissions are going to become spaghetti-like and difficult to reason about. This may not be the case, but I would much rather move forward with a clear strategy for handling new use-cases. Ideally we'd be able to manage complex permissions through composition, rather than continually adding new roles.

cc @julien51 @akeem @cnasc @NickCuso

**Comment by julien51** [comment]
> That said I'm open to other ideas/approaches. The one concern I have is that as we continue to add /support new functionality for ever more specific use-cases, our permissions are going to become spaghetti-like and difficult to reason about. This may not be the case, but I would much rather move forward with a clear strategy for handling new use-cases. Ideally, we'd be able to manage complex permissions through composition, rather than continually adding new roles.

I would tend to agree with this, but I worry about premature optimization. Maybe we're actually "good enough" with a few "hardcoded" roles for now.

Here are the ones I can think of:
* lock owner/creator
* lock beneficiary
* key owner:
* key grantor

In terms of capabilities, I think it would be interesting to list the ones we currently have as well and group them. Is that someone you can take on?

**Comment by nfurfaro** [comment]
>In terms of capabilities, I think it would be interesting to list the ones we currently have as well and group them. Is that someone you can take on?

Yes I would be happy to work on this issue. 

> ...I worry about premature optimization. Maybe we're actually "good enough" with a few "hardcoded" roles for now.

I think you're right  here. In fact, hard-coded roles (as per the openzeppelin model) should be easily composable. For example, if one address is to be both the beneficiary AND the key-grantor, they are simply assigned both the `BeneficiaryRole` and the `KeyGrantorRole`, etc...

I will review and see what I can add to the list you started above as a start, as well as looking at /grouping the permissions we currently have in the contracts.
