### ISSUE TITLE
Adjust image building steps and scripts

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#5907]
Opening an issue to keep track of this as it has a few tentacles. At the moment the following items/usages are intertwined:

* Building Docker Images for CI
* Building Docker Images for Running Integration Test Locally
* Local Configuration for Projects (Linting, Code Coverage, etc)

We would like to unwind these to accomplish the following goals:

* Clarify the process in place to build images used during testing
* Shift the responsibility of how to build each project to itself to avoid cascading changes that may not be relevant for certain projects.
* Move project towards a direction that those new to the code base are more likely to expect
* Provide a stepping stone to where we can confidently reduce the size of existing images.

**Comment by akeem** [comment]
Noting that several portions of the project mentioned above are difficult to test locally and should be adjusted so that these core changes can be made confidently

**Comment by julien51** [comment]
Closing as we have now a much better approach with stages! Thanks @clemsos !
