### ISSUE TITLE
Move checkout logic to Unlock-app

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5933]
In order to refactor our paywall application, we're stripping its need to be the place where "checkout" (key purchase) happens.
We also have a new design for key purchases which we will implement at the same time inside of `unlock-app`.
This will include: 
* user account login
* web3 login (through injected wallets, and later through web3Connect)
* Meta-data submission (when applicable)
* Optimistic unlocking

**Comment by cnasc** [comment]
I think we can call this done
