### ISSUE TITLE
KeyGrantor role

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5935]
Lock owners can grant keys "for free" to any user. In the context of our credit-card purchase flow improvement, we need a new role of locks: key grantor.

The Key Grantor role only gets a single permission: the ability to grant keys for free to a specific lock.

This role can be granted by the lock manager. 

The most important characteristic of that role is that keys granted for free should not be cancellable or transferable by their owner... only by the key grantor itself. For context, see #5557

**Comment by nfurfaro** [comment]
@julien51 I don't see this issue on zenHub ?

**Comment by julien51** [comment]
Zenhub is weird :/

**Comment by julien51** [comment]
This should be implemented as soon as #5557 is available.
