### ISSUE TITLE
KeyPurchaser

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5939]
When devising about strategies to allow for recurring payments, we identified the ability to implement a `keyPurchaser` contract whose role is to let 3rd parties renew keys on behalf of users who have approved for renewals.

## Flow
1. A lock is deployed
2. A specific keyPurchaser contract is deployed
3. A user approves an ERC20 withdrawal from the keyPurchaser of K times the keyPrice.
4. The user sends a first `renewal` themselves thru the `keyPurchaser` contract. At that point, the contract keeps track of the `keyPrice`.
5. When/If the user has a (nearly) expired key to the lock, 
_any user_ can trigger a `renewal` on the keyPurchaser.  The `renewal` method will withdraw the ERC20 amount required for itself and will purchase a key for the user who has approved the key purchases.

## Constraints
The `Renewal` call should only be successful if
1. The ERC20 approved amount is high enough (the `purchase` call will fail otherwise)
2. The `keyPrice` has not changed by more than +Δ since approval. Let's default to 10%.
3. The user who has approved for renewals has no key or a nearly expired key.

**Comment by NickCuso** [comment]
I think we should init the keyPurchaser for a price, sort of like the pseudo code I posted (copied below).

The advantage of this approach is it's full meta-transaction support for DAI.  All the user has to do is sign a permit and then our servers can do the rest.

It also allows us to be clear about the specific terms before the user does anything.  Otherwise it looks like we might have a race condition around keyPrice changing.

```
contract KeyPurchaser
{
  // set on initialize
  address lock;
  uint maxKeyPrice, renewWindow, renewMinFrequency;
  // store minimal history
  mapping(address => uint) timeOfLastPurchase;
  // anyone can call this
  // optimistic unlock could monitor this call
  function purchaseFor(address _user)
  {
    require lock.keyPrice() <= maxKeyPrice
    require time remaining on key <= renewWindow
    require time since last purchase >= renewMinFrequency
    token.transferFrom(user, this, lock.keyPrice())
    lock.purchase(for user)
    timeOfLastPurchase[user] = now
  }
  // the user can remove approval to cancel anytime. We could also add a cancel feature but that would be redundant with token allowance.
  // risk: if the user transfers or cancels themselves, they would naturally expect that also cancels the subscription but it does not.
  // not sure we have a way to deal with this other than in the front-end, unless we change the lock to support this
}
contract KeyPurchaserFactory
{
  mapping(address => address) lockToKeyPurchaser; // or maybe an array of options
  function deployKeyPurchaser(address _lock, maxKeyPrice, renewWindow, renewMinFrequency)
  {
    require lock.owner() == msg.sender
    lockToKeyPurchaser[lock] = new KeyPurchaser(maxKeyPrice, ...) // using a minimal proxy
  }
}
```
