### ISSUE TITLE
Lower gas limit for `createLock`

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5963]
**Describe the bug**
When creating a lock, we use a large gas limit and it looks like it's going to be fairly expensive - but we use about 10% of the limit.

Things got much cheaper when PublicLock switched to use minimal proxies.

**To Reproduce**
 - Create a new lock from the dashboard

**Expected behavior**
Use a more accurate estimate / lower limit.

**Additional context**
e.g. https://etherscan.io/tx/0x8d8acd19f7d66496acc4039e7bde7933273d260a4d9775c6af237cc38ad8a9eb

Gas Limit:
4,500,000
Gas Used by Transaction:
406,010 (9.02%)

https://github.com/unlock-protocol/unlock/issues/492 is the general purpose solution

**Comment by julien51** [comment]
This has been fixed!
