### ISSUE TITLE
abi package has a missing dependency

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#5987]
**Describe the bug**
IPublicLockV6.sol requires @openzeppelin/contracts-ethereum-package which is not included as a dependency.

**Additional context**
Adding this could cause unlock-js to grow in size... I'm not sure if the extra stuff would be minimized away.  We could alternatively switch to use a separate npm package for interfaces.

**Comment by nfurfaro** [comment]
@NickCuso Has this been resolved?

**Comment by NickCuso** [comment]
no

**Comment by NickCuso** [comment]
Oh to clarify the PR we merged the other day related to this was just a workaround. Other projects should not be required to do the same.

But I'm still unsure we should just add the dependency due to possible unlock-js bloat. So not sure how we resolve this one yet.
