### ISSUE TITLE
Lock contract size is almost maxed-out.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#6010]
Creating this issue to track/discuss the issue and determine:

**1.)** Is this actually an issue for us?
  I've seen reference to using so-called "transparent" contracts to get around the size limitation. Does this apply to our architecture as it's currently implemented?

**2.)** Explore options for moving forward. There are many ways of both making the locks smaller, and limiting future growth. 

### References:
- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md
- https://ethereum.stackexchange.com/questions/47539/how-big-could-a-contract-be
- https://github.com/ethereum/EIPs/issues/1538
- https://blog.polymath.network/solidity-tips-and-tricks-to-save-gas-and-reduce-bytecode-size-c44580b218e6

**Comment by mudgen** [comment]
Let me know if anyone has any questions about ERC1538.

**Comment by julien51** [comment]
Some recent cleanups have reduced the size of the contract.
