### ISSUE TITLE
Instrumentation & analytics for paywall mining

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#604]
**Description**
We currently have no idea how long it takes for a purchase/transaction to be confirmed. To have a better sense of wait times and to better design the user interaction in the final step, it would be great if we could get some kind of data/analytics on how long a transaction takes.

An additional bonus would be if we could track when/where people also fall off in the payment process. This could help us understand UX and technical issues.

**Screenshot**
<img width="639" alt="screen shot 2018-11-26 at 14 41 16" src="https://user-images.githubusercontent.com/1377389/49037971-9e183400-f189-11e8-814a-ab5f94f781c3.png">

**Comment by julien51** [comment]
Yes! Instrumentation is going to be a fairly project to help us collect valuable data but also make sure we respect unlock's users' privacy. I suspect most existing tools/platform will be limited on that front... but we can certainly use the blockchain itself to assess things like latency between transaction submission and confirmations.

**Comment by benwerd** [comment]
It seems like instrumentation / analytics for the blockchain could be really valuable in lots of contexts. It's surprising to me that I can't find a robust tool that does this already. If anyone's reading this, it's a great startup idea ...

**Comment by akeem** [comment]
Adding for future reference: https://medium.com/metamask/metametrics-an-introduction-to-metamasks-new-analytics-system-e9749e74a275

**Comment by smombartz** [comment]
an option general site analytics: https://matomo.org
