### ISSUE TITLE
Publish a new PublicLock 'core' interface

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#6053]
**Is your feature request related to a problem? Please describe.**
It's not clear which APIs are frozen and should remain with all future versions, and which may change.

**Describe the solution you'd like**
Create a second PublicLock interface that we publish to the NPM with each release that contains only the core features.  This might start with ERC-721 and getHasValidKey()

**Describe alternatives you've considered**

**Additional context**

**Comment by nfurfaro** [comment]
More discussion about this here:
https://unlock-protocol.slack.com/archives/CF57E9HCG/p1582584855036900

I'm going to try to get this into v7

**Comment by julien51** [comment]
@clemsos What do you think?

**Comment by julien51** [comment]
Given that we now have multiple versions with very different ABIs I don't think it's practical anymore.
