### ISSUE TITLE
Optimize the purchase flow

### ISSUE THREAD

**Issue by HardlyDifficult** [unlock-protocol/unlock#6060]
**Is your feature request related to a problem? Please describe.**
Our purchase flow appears to be using more gas than it needs. See https://dashboard.tenderly.dev/HardlyDifficult/unlock/tx/main/0xd1565d1b2596ba92ed2bf7221abda1e6d408bf621ae2ee348e6d96e3d0c79225/gas-usage

**Describe the solution you'd like**
Research required.

**Comment by NickCuso** [comment]
A few possible options come to mind:
 - Remove tokenId and always use the owner as the id.
 - #4804
 - Merge the callback to Unlock.sol into 1 call

**Comment by julien51** [comment]
@clemsos Can you confirm we have done some/all of this already?

**Comment by clemsos** [comment]
Yes we are now using token id all across the board, also we applied various gas savings approach from the audits.
