### ISSUE TITLE
Script interface creation

### ISSUE THREAD

**Issue by HardlyDifficult** [unlock-protocol/unlock#6085]
**Is your feature request related to a problem? Please describe.**
Maintaining the interface files is redundant and prone to error.

**Describe the solution you'd like**
Automate it.

**Additional context**
The IPublicLockCore file would still be manually maintained: https://github.com/unlock-protocol/unlock/issues/6053

**Comment by NickCuso** [comment]
this would be a possible fix for #5987

**Comment by NickCuso** [comment]
In the meantime maybe we should add a test.  We can confirm that the number of entries from the interface ABI matches the number from the contract's ABI.

**Comment by julien51** [comment]
@clemsos What do you think?

**Comment by julien51** [comment]
I think this is done!

**Comment by clemsos** [comment]
This hasn't been done, as I never figured out a proper way to export the interface from our contracts but I don't think it matters that much anyway. 

We have tests for the interfaces that will catch missing functions, so they should be uptodate. Also they store the doc strings for generated doc makes it more complex to automate the export.
