### ISSUE TITLE
Allow callbacks to Unlock.sol to fail

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#6088]
**Describe the bug**
Unlock.sol could be upgraded to disable a lock today.

**Expected behavior**
Allow the call to fail.  This means both do not revert if Unlock reverts and cap the gas so it does not force the tx to fail.

**Comment by nfurfaro** [comment]
I'm not sure why this failed yet. I have tried to reproduce the failure locally with no luck. The test passes as it's supposed to.

**Comment by NickCuso** [comment]
hmm i think you meant to post this under https://github.com/unlock-protocol/unlock/issues/6283

**Comment by julien51** [comment]
This is done
