### ISSUE TITLE
Automate the release of the abi npm modules

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6091]
Our smart contract code is packaged inside of npm modules for each version.
We should automate the release of these npm modules from CI.
This will bring the following benefits:
* "clean" environment when compiling/building
* reduced cycles and latency between smart contract changes and corresponding changes in the front end code.

The first step is to "normalize" our versions. Rather than have 1.X we should from now, create modules for each version used at the smart contract level.

The CI job should automatically compile the ABI, and create the npm module corresponding. If a module exists for the current ABI version, we should publish a new version. If it does not exist, we should deploy a new npm module.

**Comment by julien51** [comment]
@clemsos What do you think?

**Comment by clemsos** [comment]
yes absolutely. We need first #8055 which will also close #7659 - will add rollup and some various check.
