### ISSUE TITLE
"Missing transaction" error is oblique / meaningless

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#612]
If there's a storage mismatch and the system can't find a transaction, it simply displays "missing transaction" in a box. This means something to us as developers, but is not useful to the user. A more helpful explanation might be something along the lines of "We couldn't find the transaction for 'New Lock' on the blockchain. This might be because the lock wasn't saved properly. Some features may not be available for this lock." Or something like that.

<img width="1001" alt="screen shot 2018-11-27 at 11 44 04 am" src="https://user-images.githubusercontent.com/624104/49107142-c5c6d500-f239-11e8-984a-92c9f57691d7.png">

**Comment by julien51** [comment]
Ha! I think this is only happening in dev tho, when a transaction stored locally (localStorage) cannot be found on your local ethereum node ;)

**Comment by julien51** [comment]
This error is not irrelevant because we are not storing transactions in localStorage anymore...
