### ISSUE TITLE
use alchemy_getTokenBalances to get user's token balances

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#6136]
For the checkout, we'd like to have a hook that will call [alchemy_getTokenBalances](https://docs.alchemyapi.io/docs/enhanced-api#section-alchemy-get-token-balances) up front to get the user's ERC20 balances.

To do this, we'll need to compile a list of contract addresses for the following tokens on Rinkeby and Mainnet:

- DAI
- SAI
- USDC
- BAT

We may want to simultaneously call `alchemy_getTokenMetadata` so that we can format the balances that are returned. Alternately, we can get the token metadata in advance and ship it in a config file, since it shouldn't ever change.

We'll have to determine what to do on localdev, since we don't have alchemy there.

**Comment by julien51** [comment]
Since we are changing our approach this is not applicable anymore. closing.
