### ISSUE TITLE
Too many `Mixins`

### ISSUE THREAD

**Issue by HardlyDifficult** [unlock-protocol/unlock#6144]
**Describe the bug**
We have a lot of separate files

**Expected behavior**
I think it would help to rethink some of these and collapse into less files, each with a certain intent.

**Comment by julien51** [comment]
We do have a size issue that we will need to address...

**Comment by clemsos** [comment]
relates to #8358

**Comment by clemsos** [comment]
The number of mixins  does not seem to affect the contract sizes, as they get squashed and optimized together in bytecode. Maybe the various constructors add some code size but it seems only marginal. I will say it still an interesting way to organize a large code base, and one I haven’t seen in many places

**Comment by julien51** [comment]
ok so closing for now.
