### ISSUE TITLE
Check balance before purchase

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#6158]
**Describe the bug**
If I have 1.99999999999 DAI the front end allows me to buy a key for 2 DAI.
But of course that fails because I'm short.

**To Reproduce**
Put just under 2 DAI into your wallet.
Buy a 2 DAI key.

No error, no warning. .. until the tx is mined and reverts.

**Expected behavior**
Do not allow me to approve or purchase if i'm short.

**Comment by julien51** [comment]
I think this is due to the fact that JS will "round" 1.9999999 to 2.0. Not sure what's the best way to handle this?

**Comment by NickCuso** [comment]
You could use a library such as bignumber.js to prevent rounding.
