### ISSUE TITLE
Implement caching on new paywall script

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#6196]
We want to cache locked/unlocked status in the new paywall script. This method should be more robust than what we have in the current paywall -- we should scope it to the lock address in particular

**Comment by julien51** [comment]
first I want to cache the user address so that when a user has unlocked they do not need to click on the checkout button everytime they visit the page.

Then I want to implement caching _per lock_ so that we can respond faster.

**Comment by julien51** [comment]
The next step is to cache the "state" per lock. This should allow for a faster loading but also bring "flashing" due to changing state in unexpected ways.
