### ISSUE TITLE
Checkout iframe needs to be vetted and improved with unlock user accounts

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#6199]
Right now we only handle a subset of the necessary functionality for unlock user accounts to be first-class users of the new checkout. I'll update this issue with a list of required features as we enumerate what is missing.

**Comment by julien51** [comment]
The flow should be this:

1. [ ] Once the user is not logged in, we show disabled locked and login button, and price should be in crypto (prices set on locks  by creators). Only show the log-in button if paywall config allows for `unlockUserAccounts` (this will be changed later though)

2. [ ] Once the user logs in we need to assess which lock can be purchased with CC. Implement a locksmith call for this (given a lock address, check whether it's in the list of approved locks, and return the price to be charged).

3. [ ] Show the $ price for locks which are CC approved and mark them as "purchasable".

4. [ ] Once the user clicks on the lock which is purchasable via CC, 
 a. [ ] If metadata needs to be collected, collect it and move to 4b. 
 b. [ ] show confirmation screen or CC form.

5. [ ] Once user submits, send a purchase call to locksmith and yield transaction hash to paywall script.

**Comment by cnasc** [comment]
For the first task (list of locks when not logged in):

The code to do it is already there, but for some reason it doesn't show up in the iframe. Here's what I mean:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/9300702/76897444-24b6c000-686a-11ea-9e5f-1de809426b23.png">
On the paywall

<img width="432" alt="image" src="https://user-images.githubusercontent.com/9300702/76897465-2e402800-686a-11ea-9473-b5ba0d6a963c.png">
Same config, but directly on the checkout page

Trying to figure out what's going on with that

**Comment by cnasc** [comment]
Got it, had a `useEffect` only firing once so it didn't get the update to lock addresses.

**Comment by cnasc** [comment]
I think this is all done now
