### ISSUE TITLE
Submit button should not be grey

### ISSUE THREAD

**Issue by ligi** [unlock-protocol/unlock#6227]
Currently the submit button is grey like this:

![Selection_364](https://user-images.githubusercontent.com/111600/76771179-3bdcab80-679f-11ea-8e54-2b9e7e0a46d5.png)

This looks like it is greyed out / disabled. It should be e.g. in the accent color the create lock button is in

**Comment by ligi** [comment]
also the displaying of the tokens if the token name is long like here should be improved so both texts do not collide and make each other hard to read

**Comment by smombartz** [comment]
totally agree! thanks for bringing that to our attention @ligi 

@cnasc shall we takle this during our next QA round?
![image](https://user-images.githubusercontent.com/1377389/76772227-eb515800-6776-11ea-8162-5733538d586e.png)

**Comment by cnasc** [comment]
@smombartz happy to take a look this week! Let's set something up.
