### ISSUE TITLE
Replace web3.js with ethers.js?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#625]
Several people have recommended that we look at ethers.js which they claim is both more stable and better designed than web3.js.
We tried to isolate web3 handling to web3Service but migrating may still involve significant work.

**Comment by nfurfaro** [comment]
This could be a good resource if the decision is made to migrate to ethers.js.
https://github.com/LimeChain/etherlime/blob/master/README.md

**Comment by nfurfaro** [comment]
I've not used ethers.js, but more often than not I hear it described as being more stable than web3. It probably wouldn't hurt to migrate, but it doesn't seem critical unless there are too many pain-points with web3 to make working with it efficient/effective.

**Comment by julien51** [comment]
@benwerd I don't think moving to ethers.js would actually mean moving off of/away from Metamask ;) We just would use a different JS library to interface with the providers (including Metamask).

**Comment by benwerd** [comment]
Right, but it would give us more flexibility, right? Or am I misunderstanding that?

**Comment by julien51** [comment]
It looks like another option is [`web3x`](https://github.com/xf00f/web3x). What do you think @cellog ?

**Comment by cellog** [comment]
Will take a look

**Comment by akeem** [comment]
I'll give this a final check in the morning but believe that we can consider this resolved

**Comment by cnasc** [comment]
Might be worth adding a checklist here and closing this once every app has been migrated (if applicable, since I don't think wedlocks uses the chain at all)?

- [ ] unlock-app
- [ ] tickets
- [ ] paywall
- [ ] wedlocks
- [ ] locksmith

**Comment by akeem** [comment]
Closing as the web3 dependency has been removed from Locksmith
