### ISSUE TITLE
Login page briefly 'flashes' when user with a wallet navigates to https://app.unlock-protocol.com/keychain/

### ISSUE THREAD

**Issue by adamgobes** [unlock-protocol/unlock#6261]
**Describe the bug**
When a user with a crypto wallet (such as Metamask) enabled navigates to https://app.unlock-protocol.com/keychain/, the login page flashes for a brief second before the keychain page is loaded.

**To Reproduce**
1. Go to https://app.unlock-protocol.com/keychain with your Metamask wallet enabled
2. See Login page briefly
3. See keychain page

**Expected behavior**
1. Go to https://app.unlock-protocol.com/keychain with your Metamask wallet enabled
2. See keychain page right away without flashing the Login page

**Screenshots**
![](https://media.giphy.com/media/YmzLKcQVut4YArtAbq/source.gif)

**Additional context**
This is happening due to the `<KeychainContent />` component receiving a not yet updated version of the `account` field from the Redux store.

Three potential solutions to handle this:
1. We could initialize the `account` field similar to the way we do the `provider` field in `/unlock-app/src/config.js` using `environment.web3.currentProvider.selectedAddress`. 

The reason we don't initialize `account` inside `config.js`, I believe, is because we use a change handler inside `/unlock-app/src/middlewares/walletMiddleware.js` and initialize it that way. I believe this is what leads `account` to be `null` when the app first loads.

2. We can use another mechanism to determine whether the user is 'logged in'. Instead of using the `account` field, which essentially checks if they have a wallet address, we could use the `provider` field, which essentially checks if they have a wallet at all, but I'm not sure if this will work.

3. We could use a hack, such as an interval (`useInterval`) inside `<KeychainContent />`, to continuously poll the `account` field coming from the Redux store and see when it has stopped changing. This is the quickest/dirtiest solution, but is not sustainable long-term.

**Comment by cnasc** [comment]
Hi @adamgobes, thanks for the report. I think your analysis is correct -- there's actually a state we're not tracking. Right now we consider 2 states:

- There is an account (proceed with app)
- There is no account (prompt for login)

However, there is a third missing state:

- We don't know for sure whether there is or isn't an account (so wait until we're sure)

If we were to account for that state with either a loading spinner or just a delayed render of the main component, I think that would resolve this flicker. That may require some changes to `WalletService` to make sure it always emits when it knows whether or not there is an account and not just when it positively has one.

**Comment by adamgobes** [comment]
Hi @cnasc! That makes sense.

It seems that the logical place to put this logic would be in `walletService.connect`, however, this is not called when the user has no wallet because `walletService.connect` is only called in response to the `PROVIDER_READY` action being dispatched.

Is it reasonable to have it so that `walletService.connect` is always attempted?

**Comment by cnasc** [comment]
Hm, this is a bit tricky. My first impulse was to modify `WalletService.getAccount`:
https://github.com/unlock-protocol/unlock/blob/8a0363c29aa3bbe8e0458b3d1e8cefeb828cf42f/unlock-js/src/walletService.js#L89

On line 92 we handle the case where there is no account. I think the general approach would be to emit some kind of `NO_ACCOUNT` event there.

So we'd start with some value in the account state that indicates we're waiting to know about account status, and then WalletService would emit `account.updated` events that can change it into either the "no account" state or the "connected account" state.

Unfortunately, I think `walletMiddleware` calls `getAccount` right away when it is instantiated, which is before it can handle any `PROVIDER_READY` events, so it will always emit the no account event.

Maybe @julien51 can chime in with an idea on how to resolve that.

**Comment by adamgobes** [comment]
Yes, that was exactly my initial thinking as well.

Another problem, I believe is that if the user has no wallet account, `getAccount` is never even called in the first place. 

It's only called when `network.changed` is emitted, and this only happens if the user has a wallet account.

**Comment by julien51** [comment]
Thanks @adamgobes for raising this.
I believe we need to keep track of the 3rd state as @cnasc noted.

Instead of looking at the walletMiddleware, we could also look at `initializeProvider` inside of `providerMiddleware`.
This method already differentiates between the presence/absense of a crypto wallet which would trigger showing the form?

**Comment by adamgobes** [comment]
Yes Julien that is a great place to put it!

After drafting up the implementation and testing it seems that this will work great except for one case:

When a user has the Metamask extension in their browser but does not have their account connected. When this occurs, the `provider.enable()` promise at line 42 never seems to resolve: 

https://github.com/unlock-protocol/unlock/blob/2a76c2b957f8a83b8b0f8c81971fa127ff579109/unlock-app/src/middlewares/providerMiddleware.ts#L42-L51

Do either of you know why this occurs?

**Comment by cnasc** [comment]
Metamask should prompt the user to connect in that case. We've noticed some weirdness around how Metamask shows the prompt though, sometimes it's in a window that doesn't get focused. Can you confirm that Metamask doesn't prompt in that case and give reproduction steps?

**Comment by adamgobes** [comment]
Yes, so from my experience:

The first time you go on the app, that prompt will pop up and be in focus. If you dismiss the prompt, however, every subsequent to go on the app will not prompt the user anymore, and they need to manually connect using the metamask extension.

**Comment by julien51** [comment]
We have now changed the approach to how we handle providers and this is fixed :)
