### ISSUE TITLE
CI failure: can cancel a free key reverts

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#6283]
**Describe the bug**
CI failed on master

**To Reproduce**
https://circleci.com/gh/unlock-protocol/unlock/169020

**Comment by nfurfaro** [comment]
I'm not sure why this failed yet. I have tried to reproduce the failure locally with no luck. The test passes as it's supposed to.

**Comment by NickCuso** [comment]
looking

**Comment by NickCuso** [comment]
got a repro locally but not consistent..
