### ISSUE TITLE
Clear approvals when the keyManager changes

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#6302]
From the spec:
    ///  When a Transfer event emits, this also indicates that the approved
    ///  address for that NFT (if any) is reset to none.

**Comment by NickCuso** [comment]
Hmm need to fix a circular dependency first so that the setKeyManager call can reach _clearApproval

**Comment by nfurfaro** [comment]
@NickCuso 
 I see the issue with the circular dependency.
This is a bit hacky, but for now (until we refactor the mixins-pattern) maybe we just inline it?
So, every time we either call `_resetKeyManagerOf` or modify directly (such as https://github.com/unlock-protocol/unlock/blob/74a623bcd47e2ac81d608f6aba37aa9ae2a65ac5/smart-contracts/contracts/mixins/MixinGrantKeys.sol#L46), 
we follow up with a call to `_clearApproval`
Thoughts?
