### ISSUE TITLE
Add a caret icon to unlock-assets

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#6327]
We need to have a caret icon for use in styled `<select>` elements, and the natural place to put that is in `unlock-assets`.

Example in Figma:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/9300702/77476157-69a1a000-6df0-11ea-8d4a-f36cf225b1c6.png">

https://www.figma.com/file/YIvjlf89MZAXTFuBYXI3fv/Paywall-2?node-id=29%3A678

**Comment by julien51** [comment]
We have this 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/17735/79916382-a1533600-83f6-11ea-9090-11e6a043df93.png">
