### ISSUE TITLE
Mismatched compiler settings

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#6368]
The wiki says to compile contracts before publishing a new module with `yarn build`, which uses truffle.
When using openzeppelin-cli to push contracts before an upgrade, it fails unless the contracts are compiled using `yarn zos compile'.

We should pick one way to use solc in the project and use it consistently.

Related: I believe there may be a way to specify paths when compiling to avoid most of the diffs in the metadata swarm hash (at the end of the bytecode). Need to find where I read this...

**Comment by nfurfaro** [comment]
Ideally, we can just use `truffle compile --all` (via `yarn build`) consistently.
We don't currently have the evm version specified in our `truffle-config` file. The truffle docs say that the default is "Petersburg".
When we compile with truffle and then deploy, the next step is verification on etherscan. This step fails for me unless I set the evm version in etherscan to use "Petersburg". This should be fine, but for solidity 0.5.17 the default target-evm should actually be Istanbul.

I tried getting truffle-compile to use Istanbul, and then verifying on etherscan with evm version set to Istanbul as well. This did NOT work. Not sure what's up here.

**Comment by NickCuso** [comment]
The default is Muir per some release notes I saw. That's when I removed our setting as we were still on istanbul at the time I think.

**Comment by nfurfaro** [comment]
Ah, ok. The docs I'm looking at are out of date. 
Etherscan doesn't give Muir as an option. Strange that using the truffle default requires setting etherscan evm-version to Petersburg.

**Comment by NickCuso** [comment]
Although Muir was a hardfork, it was only about delaying the difficulty bomb. So no change to smart contracts.
