### ISSUE TITLE
Allow for cancellation

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#637]
This is a feature which I thinks public locks could have: the ability for their owner to define terms of a cancellation.
In practice I think cancelling a key would just mean "selling it back" to the lock by  the key owner. In that case the key owner would get a (partial) refund. I believe the easiest way to do that would be to decide on the amount of the refund based on the remaining validity of the key with an optional penalty by the lock owner.

What do you think @nfurfaro ?

**Comment by nfurfaro** [comment]
It seems reasonable on a technical level. It's probably preferable to have a key owner sell their key to another user rather than back to unlock ( from a revenue perspective). But if this is something you want to  implement, it will be relatively easy if done after some of the ERC721 changes discussed in #148, specifically the ability to " top-up a key's time with another key's time." If this were implemented, and the lock retained one key, cancellation would simply be selling the time remaining on a key to the lock via it's key.

**Comment by julien51** [comment]
I think this is right: cancelling a key would be transferring back the remaining time on it back to the lock owner.

**Comment by nfurfaro** [comment]
@julien51 Does it make sense to you to do this after #148 is complete?

**Comment by hardlydifficult** [comment]
How much of a refund would be offered?  e.g. maybe the Lock owner defines a rate per unit of time, where `refundRate * expirationDuration <= keyPrice`.  And/or a fixed penalty (selected by the Lock owner) could be applied as you suggested above.  Note that if both a refundRate and a fixed penalty are defined cancel won't make sense for keys which are near their cancellation date (which seems to make sense).  Options seem to be:
 - Cancel for a refund of `keyPrice - fixedPenalty`
 - Cancel for a refund of `costPerUnitTime * timeRemaining - fixedPenalty`
 - Cancel for a refund of `refundRate * timeRemaining`
 - Cancel for a refund of `refundRate * timeRemaining - fixedPenalty`

Cancel would fail if the Lock owner withdraws too much funds.  Do we accept that cancel may fail if this happens?  Or do we require a minimum amount of reserve funds remain in the contract? (if we implement a min, we will need to consider when all funds may be withdrawn so we don't effectively burn ETH) 

On a related note, `withdraw` has a TODO to consider partial withdraws.  It seems if this feature is added we need partial withdraws implemented as well.

**Comment by julien51** [comment]
I think all of these are good questions. Thanks @hardlydifficult !
I think the `refundRate` is fairly simple to compute `price * keyDuration/(expiration-now)`. I think the penalty is fair game. 

For now, since we have no user feedback on that, let's work on a thing where the penalty is 10% of the total price (at purchase time). This does indeed mean that at some point, it is not worth cancelling anymore.

The comment about the balance needing to be high enough is a good one too. Let's implement partial withdraws first.
