### ISSUE TITLE
Signing the card retrieval request

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6408]
Locksmith is adding [signature verification to the API call](https://github.com/unlock-protocol/unlock/pull/6406) to list cards for a user. We need to make sure this call is signed by unlock-app.

**Comment by cnasc** [comment]
One major question around how this will be handled:
Right now, we get cards right after we get an account. This means that once we start supporting cards for crypto wallet users they will be prompted for a signature every time they load unlock-app, whether they want to use a credit card or not (or whether it even makes sense for them to do so). How to we intend to minimize that impact?
