### ISSUE TITLE
More generic metadata title as not all locks are for purchases

### ISSUE THREAD

**Issue by pieman64** [unlock-protocol/unlock#6445]
**Is your feature request related to a problem? Please describe.**
Currently the prompt shown when the metadata form is displayed states something like "We need to collect more information for your purchase"

**Describe the solution you'd like**
As the lock could be for a tip / donation it might be better simply as "We need to collect more information"

**Describe alternatives you've considered**
Would be nice if lock producers could actually add their own prompt

**Comment by julien51** [comment]
I think we can easily add a `callToAction` . What do you think @cnasc ?

**Comment by cnasc** [comment]
We can definitely add another property to the `callToAction` object and use that as the text when the form is up!
