### ISSUE TITLE
Opera wallet for Android not asking to sign metadata

### ISSUE THREAD

**Issue by pieman64** [unlock-protocol/unlock#6446]
**Describe the bug**
Our lock injects the Opera wallet with Android when we don't have metadata but appears to be stuck at "Submitting Data" when we do.

Opera appears to be waiting for the wallet injection.

**To Reproduce**
Add metadata to a lock
Try to submit with from Opera wallet for Android

**Expected behavior**
Metadata should work with Opera wallet on Android.

**Smartphone (please complete the following information):**
 - Device: Galaxy J5
 - OS: Android 9
 - Browser Opera with VPN
 - Version57.1.2830.52480

**Comment by julien51** [comment]
Thanks! This is very helpful. We'll debug this ASAP.

**Comment by julien51** [comment]
Thanks, looking at this, I am not quite sure what is going on. I'll keep digging.

**Comment by julien51** [comment]
@pieman64 It looks like this is solved. Could you confirm on your end?
