### ISSUE TITLE
Paywall to private community

### ISSUE THREAD

**Issue by paulharnepher** [unlock-protocol/unlock#6476]
Unlock 

I am looking to use unlock as a paywall into a private discord server. This discord server will also act as a membership dao on aragon. Each member gets 1 nontransferable token used to vote. I also want to give each member who joins 100 erc20 tokens for fun. Members can send each other these tokens for good posts.

I am hoping I can mint their membership token and give them their erc20 tokens in one transaction when they use unlock protocol. 

I want to create a private community with it's own entrancy fee, governance and economy. 

I don't expect this erc20 token to be worth anything just given to others as gifts.

is this a good idea? What do you think?

**Comment by paulharnepher** [comment]
Just a paywall into a private discord would work. 

That extra stuff about giving them tokens is just for fun but idk would I get in trouble for selling coins without a license

**Comment by julien51** [comment]
This is absolutely one of the use cases that Unlock has been created for. Discord seems to have a nice `role` API which we could leverage here.

**Comment by julien51** [comment]
Hello! I am so sorry for the veryt late response here. One of our community members, @pi0neerpat built https://swordybot.com/ which I think would cover the discord part!

The 2nd part about Aragon is very interesting and we'd love to see it happen. What is the best way to chat about so we have a better understanding?
