### ISSUE TITLE
LockManagers missing for locks which were transfered

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6541]
Our subgraph allows us to query locks by lock manager.
I have found a lock for which the `lockManagers` field was not correct.

This lock (`0x43154Efc9cb33c80833C0dEc1E15bb9CfC1275e5`) shows `0xe5cd62ac8d2ca2a62a04958f07dd239c1ffe1a9e` as one of the lock managers, while this address should not be a lock manager. It also does not show `0x8Df168A41C3a3c6BE0e9208D5027EA80f2C5ba25` as a lock manager, even though this address, as it is the lock owner should be a lock manager.

**Comment by akeem** [comment]
Marking this  as now being resolved and closing. Issuing the following query for the mainnet subgraph should now yield the correct results for pre version 7 lock contracts that have been transferred to new owners.

```
{
  locks(where:{address: "0x43154Efc9cb33c80833C0dEc1E15bb9CfC1275e5"}){
    name
    owner
    
    LockManagers{
      address
    }
  }
}
```
