### ISSUE TITLE
Disable optimistic unlocking via locksmith

### ISSUE THREAD

**Issue by nickoneill** [unlock-protocol/unlock#6549]
**Is your feature request related to a problem? Please describe.**
I’m building a project using the example cloudflare worker and it describes the locksmith as being in charge of the optimistic unlocking functionality. My project is aimed at technical users and I would like to disable optimistic unlocking.

**Describe the solution you'd like**
Ideally this would be something I could pass in config via the worker to the cloudflare worker to turn this on or off.

**Describe alternatives you've considered**
I will most likely build v1 without this, but I’ll have to keep tabs on my users to see if anyone is cancelling transactions since the benefit after payment is immediate, not ongoing. Trust that people won’t know what they’re doing is the alternative :)

**Comment by julien51** [comment]
Hey! Thanks for your contribution! I think there will be no need to tinker with locksmith... just with the paywall application code to _not_ be optimistic (even though a transaction was sent until it's been mined, we keep the state as locked!).

Let's get to work  and hopefully we'll have something soon!

**Comment by julien51** [comment]
Here is a rough plan. Let me know if this fits what you're looking for.

Right now the paywall script will emit `locked` and `unlocked` events only. The `unlocked` event is triggered when a transaction was sent and we are optimistic about it.

The plan is to add a `pessimistic` option to the paywall config (see [config there](https://docs.unlock-protocol.com/#configure-the-paywall)). If set to true, the paywall script will _not_ emit any `unlocked` event when the transaction was sent.

Even though the above seems necessary I believe it will not be sufficient. Without the `unlocked` event, how would an implementing application know about the fact that a transaction was sent?

This highlights a "tension" which I have been considering in a few other cases. `locked` and `unlocked` events are useful but not enough. It is time to consider others.

Here are the events which I think we could add:
* `authenticated`: which is emitted when we know of the address of the user.  (we should pass the users' address)
* `transactionSent`: which is emitted when a transaction was sent. (we should pass the transaction hash).

This, I believe would provide a richer framework. What do you think @cnasc ?

**Comment by cnasc** [comment]
> This highlights a "tension" which I have been considering in a few other cases. `locked` and `unlocked` events are useful but not enough. It is time to consider others.
> 
> Here are the events which I think we could add:
> 
>     * `authenticated`: which is emitted when we know of the address of the user.  (we should pass the users' address)
> 
>     * `transactionSent`: which is emitted when a transaction was sent. (we should pass the transaction hash).
> 
> 
> This, I believe would provide a richer framework. What do you think @cnasc ?

I think this is reasonable. The first pass at this can probably be done rather easily. For completeness/good UX we'll also want to extend the checkout interface to stay in the processing state until the transaction reaches some minimum number of confirmations (perhaps that is also configurable)

**Comment by julien51** [comment]
Ok, thanks for your contibution. I'll start working on this.

Regarding the "processing state". I like that idea! this is certainly something we can add.

**Comment by julien51** [comment]
It looks like the API by web browsers does not supporting events in a very flexible way. Right now we emit strings in the `detail` attribute of the event object. See 

```
window.addEventListener('unlockProtocol', function(e) {
  var state = e.detail
  // the state is a string whose value can either be 'unlocked' or 'locked'...
  // If state is 'unlocked': implement code here which will be triggered when 
  // the current visitor has a valid lock key  
  // If state is 'locked': implement code here which will be
  // triggered when the current visitor does not have a valid lock key
})
```

This is to maintain compatibility with [older browsers](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/initCustomEvent#Parameters).
I will have to explore how to handle this gracefully.

**Comment by julien51** [comment]
Good news. I think we can get rid of the old approach () as the new one (CustomEvents) is now supported by the [vastest majority of web browsers](https://caniuse.com/#search=CustomEvent).

**Comment by julien51** [comment]
We also added docs https://docs.unlock-protocol.com/applications/paywall/advanced-paywall-configuration

Thanks a lot for the idea @nickoneill

**Comment by nickoneill** [comment]
Thanks! The additional docs here are awesome
