### ISSUE TITLE
Lock level metadata

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6563]
Currently, we have metadata for keys. We need a _new_ level for metadata: metadata for locks.
This should be served via a `GET` request to locksmith without authentication.

For every lock, we should serve by default:
* an image (the lock icon)
* name (the lock name)
* a description

For this, if records exist in the `LockMetadata` table exist, we should serve them. 
Otherwise, we should serve what we use as the `defaultMappings`. When the data from the database is partial. We should combine it with `defaultMappings`.
The [route we will use already exists](https://github.com/unlock-protocol/unlock/blob/master/locksmith/src/controllers/lockController.js#L25) but we should update it so that it always returns values, even if no record is set in the `LockMetadata` table.

Additionally, for every lock, we should let the lock owner update the `LockMetadata` record (I believe [we already do that](https://github.com/unlock-protocol/unlock/blob/master/locksmith/src/controllers/metadataController.ts#L83)!). (we might want to have that same logic at a different route since `/api/key/<lockAddress>` might not make a lot of sense.. but that's probably nitpicking!)

**Comment by akeem** [comment]
Linking for context around up coming code change https://github.com/unlock-protocol/unlock/pull/5967

**Comment by akeem** [comment]
Closing as the associated code change has been introduced into master
