### ISSUE TITLE
Self-Destruct does not totally remove a lock from the dashboard

### ISSUE THREAD

**Issue by bowensanders** [unlock-protocol/unlock#6575]
If you perform a self-destruct on a lock, it leaves behind a trace in the Unlock Dashboard as "New Lock" with no further information.

<img width="903" alt="Screen Shot 2020-04-22 at 12 01 52 PM" src="https://user-images.githubusercontent.com/27023908/80022535-0f4c3b80-8491-11ea-8888-835e10034946.png">

you can see a self-destructed lock at this address: https://etherscan.io/address/0x1e1eed8882dd411e7569ee79823a44f4f4a55cac#code

**Comment by julien51** [comment]
Thanks a lot @bowensanders 
I think this might be because our subgraph might not be updated correctly after the lock has been destroyed. We'll look into that!

**Comment by julien51** [comment]
cc @akeem

**Comment by akeem** [comment]
yeah, that makes sense. At the moment the state of things in the subgraph reflect interactions mostly if they have been initiated via ui surfaces that we have created, but we updated it to reflect some non-ui scenarios like transferring lock contracts.  We'll update this soon to support this use case as well.

**Comment by akeem** [comment]
@bowensanders we have released resolution for this issue, when you have a moment would you mind confirming that it is indeed resolved on your end?

**Comment by bowensanders** [comment]
At this point, for some reason none of my locks are loading? It's just giving me the loading animation.
<img width="1354" alt="Screen Shot 2020-04-28 at 11 34 48 AM" src="https://user-images.githubusercontent.com/27023908/80524327-46fd2c80-8944-11ea-9a78-a5e7b97bf3b5.png">

**Comment by akeem** [comment]
@bowensanders thanks for the heads up, you should now be able to use the dashboard as expected. We have an idea for a path for here as well

**Comment by bowensanders** [comment]
Okay, now all the locks are showing again, including the self-destructed ones. Not sure if that was intended, but at least they are showing up now :)

**Comment by akeem** [comment]
@bowensanders thanks for the update, that is the intention for the time being until there is new resolution for this. I've opened an other issue to add additional detail here: https://github.com/unlock-protocol/unlock/issues/6619

**Comment by julien51** [comment]
Hey @bowensanders !
Since it is taking us a little bit more time to fix our subgraph for this use case, we are pushing a fix to the front end in the next few hours to not show the lock if the contract is not deployed anymore.

**Comment by julien51** [comment]
This should now be resolved! Please confirm @bowensanders ...

**Comment by bowensanders** [comment]
Seems to be working great now! Thanks!

**Comment by julien51** [comment]
🚀
