### ISSUE TITLE
Upgrading the rinkeby deployed Unlock contract fails

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#665]
@nfurfaro recently [updated our smart contract code](https://github.com/unlock-protocol/unlock/pull/642) to use the latest version of OpenZeppelin (2.X).

We are now trying to deploy this up to date version to Rinkeby by upgrading the deployed version.
We are unfortunately unable to do so:

```
Using session with network rinkeby, sender address 0x33ab07df7f09e793ddd1e9a25b079989a557119a
Compiling contracts
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/PublicLock.sol...
Compiling ./contracts/Unlock.sol...
Compiling ./contracts/UnlockTestV2.sol...
Compiling ./contracts/UnlockTestV3.sol...
Compiling ./contracts/interfaces/ERC721.sol...
Compiling ./contracts/interfaces/ILockCore.sol...
Compiling ./contracts/interfaces/ILockPublic.sol...
Compiling ./contracts/interfaces/IUnlock.sol...
Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling zos-lib/contracts/Initializable.sol...

Compilation warnings encountered:

/Users/julien/repos/unlock/smart-contracts/contracts/interfaces/IUnlock.sol:20:3: Warning: Functions in interfaces should be declared external.
  function initialize(address _owner) public;
  ^-----------------------------------------^
,/Users/julien/repos/unlock/smart-contracts/contracts/interfaces/IUnlock.sol:27:3: Warning: Functions in interfaces should be declared external.
  function createLock(
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/julien/repos/unlock/smart-contracts/contracts/interfaces/IUnlock.sol:41:3: Warning: Functions in interfaces should be declared external.
  function computeAvailableDiscountFor(
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/julien/repos/unlock/smart-contracts/contracts/interfaces/IUnlock.sol:56:3: Warning: Functions in interfaces should be declared external.
  function recordKeyPurchase(
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/julien/repos/unlock/smart-contracts/contracts/interfaces/IUnlock.sol:68:3: Warning: Functions in interfaces should be declared external.
  function recordConsumedDiscount(
  ^ (Relevant source part starts here and spans across multiple lines).
,/Users/julien/repos/unlock/smart-contracts/contracts/Unlock.sol:122:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address _purchaser, // solhint-disable-line no-unused-vars
    ^----------------^
,/Users/julien/repos/unlock/smart-contracts/contracts/Unlock.sol:123:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    uint _keyPrice // solhint-disable-line no-unused-vars
    ^------------^
,/Users/julien/repos/unlock/smart-contracts/contracts/Unlock.sol:143:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address _referrer // solhint-disable-line no-unused-vars
    ^---------------^
,/Users/julien/repos/unlock/smart-contracts/contracts/Unlock.sol:161:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    uint _tokens // solhint-disable-line no-unused-vars
    ^----------^
,/Users/julien/repos/unlock/smart-contracts/contracts/UnlockTestV2.sol:30:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address _purchaser, // solhint-disable-line no-unused-vars
    ^----------------^
,/Users/julien/repos/unlock/smart-contracts/contracts/UnlockTestV2.sol:31:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    uint _keyPrice // solhint-disable-line no-unused-vars
    ^------------^
,/Users/julien/repos/unlock/smart-contracts/contracts/UnlockTestV3.sol:47:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address _owner
    ^------------^

Writing artifacts to ./build/contracts

Validating contract Unlock
- Variable locks (Unlock) contains a struct or enum. These are not automatically checked for storage compatibility in the current version. See https://docs.zeppelinos.org/docs/writing_contracts.html#modifying-your-contracts for more info.
- Variable 'address owner' in contract Ownable was renamed to _owner in openzeppelin-solidity/contracts/ownership/Ownable.sol:1._owner will have the value of owner after upgrading.
See https://docs.zeppelinos.org/docs/writing_contracts.html#modifying-your-contracts for more info.
One or more contracts have validation errors. Please review the items listed above and fix them, or run this command again with the --force option.
```

We need to understand how critical these 2 things are and find a way forward.

For the `enum` issue:
* How critical is it since the `enum` is in a distinct smart contract?
* I believe this should not affect the `Unlock` smart contract? Why is ZOS complaining about that then? 
* Could we "remove" the reference to the Lock's contract code from the Unlock Smart Contract and only store the address at which a version of the ABI is stored?

For the `Owner` issue:
* Since we're using OpenZeppelin and Zeppelin OS, we kind of expected things to work together, but it looks like they're not? 
* Does that mean we cannot update the dependencies which are not following the ZOS guidelines?
* Would a solution be to move to OpenZeppelin Ethereum (where OpenZeppelin libraries are deployed independently on the EVM)? If so, what are the drawbacks/challenges?

**Comment by nfurfaro** [comment]
Some context:

zOS has some built-in contract validation functionality. When attempting to upgrade it will check the layout of the new version so see if adheres to the storage requirements for upgrading. **Violating any of these storage layout restrictions will cause the upgraded version of the contract to have its storage values mixed up, and can lead to critical errors in your application.**

• "When writing new versions of your contracts, either due to new features or bugfixing, there is an additional restriction to observe: you cannot change the order in which the contract state variables are declared, nor their type."

• "Keep in mind that if you rename a variable, then it will keep the same value as before after upgrading. This may be the desired behaviour if the new variable is semantically the same as the old one:"

• "And if you remove a variable from the end of the contract, note that the storage will not be cleared. A subsequent update that adds a new variable will cause that variable to read the leftover value from the deleted one."

**Comment by nfurfaro** [comment]
For the first issue: ( Variable locks (Unlock) contains a struct or enum. )

zOS is simply warning us that it is unable to verify the validity of the storage in the contract we want to upgrade to, because it can't validate struct or enums. Here, it's complaining about the `struct LockBalances` which is used in the `locks` mapping. 

Solution: When upgrading, we need to manually confirm that we have not violate3d any storage layout restrictions in any structs or enums in `Unlock.sol`.

**Comment by nfurfaro** [comment]
For the second issue: ( Variable 'address owner' in contract Ownable was renamed to _owner in openzeppelin-solidity/contracts/ownership/Ownable.sol )

This is just a friendly reminder of one of the restrictions mentioned above in my first comment: 
"Keep in mind that if you rename a variable, then it will keep the same value as before after upgrading. This may be the desired behaviour if the new variable is semantically the same as the old one:"

Solution: Semantically, `_owner` has the same meaning as `owner`, and we want `_owner` to contain the value previously contained by `owner`. I don't think this is an issue, but rather the desired behavior. 

Note: When we first saw this warning, I misunderstood it to mean that `_owner` would be renamed to `owner` after upgrading which would break the app.

**Comment by julien51** [comment]
Ok, I'll go ahead and try to force things then!
I want us to get confidence so we should still clarify both of these points.

1. I think I agree/understand what you say, but I still do not understand *why* ZOS is complaining because the `enum` is in a fully different contract. I do not like that we get a warning like that if it is irrelevant. So there is something that we miss here. 

2. I think I am in line ;)

**Comment by nfurfaro** [comment]
As for #1.) "Variable locks (Unlock) contains a struct or enum."
It's a struct in this case.

**Comment by julien51** [comment]
Ho indeed, but my comments are the same ;)

**Comment by nfurfaro** [comment]
So `Unlock.sol` contains a struct `LockBalances` which is used in the mapping `Unlock.locks`. The current version of zos is not able to automatically check this struct for a diff between v1 and the new version we're trying to upgrade to, so we have to check it. If our new version did something like add a new field to `LockBalances` it would make a mess of things.

**Comment by julien51** [comment]
Hoooo, my mistake! I thought it was complaining about the struct in the `Lock.sol` contracts!
Do you recommend we do not use structs? (just 2 distinct mappings)

**Comment by julien51** [comment]
Deploy success! https://github.com/unlock-protocol/unlock/pull/669

**Comment by nfurfaro** [comment]
> Hoooo, my mistake! I thought it was complaining about the struct in the `Lock.sol` contracts!
> Do you recommend we do not use structs? (just 2 distinct mappings)

No, I think they're  a valuable data structure, and this warning will prompt us to review whether we've made changes to our struct before upgrading. We just can't make changes to it ;)

**Comment by julien51** [comment]
I think we will be able to to close this as soon as we have tested a new deploy/upgrade! cc @nfurfaro

**Comment by julien51** [comment]
@nfurfaro Let's try to upgrade that soon?

**Comment by nfurfaro** [comment]
@julien yes! I may be able to get a window tomorrow, will let you know.

**Comment by nfurfaro** [comment]
Of course, you can do it without me too.

**Comment by nfurfaro** [comment]
@julien51 not sure if I'll be able to sync in the next couple of days, but if you want to proceed with this update we could go ahead async. The procedure is fairly well documented in our wiki. I wouldn't mind merging a couple PR's first if possible.

**Comment by julien51** [comment]
Hey! Yes I want to review your PR and once they're merged actually deploy and upgrade to Rinkeby! Thanks

**Comment by julien51** [comment]
We upgraded successfully today https://github.com/unlock-protocol/unlock/pull/889 so we can now close!
