### ISSUE TITLE
OpenZeppelin 3

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6681]
We currently use OZ 2.5 (TBC @NickCuso). If we want to migrate to Solidity 0.6, which will have to support OZ 3, which is a *breaking* change per this thread. https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/issues/79

This likely means we will need to change the address of the Unlock contract. This can probably be done with some migration path, but will also need to cover the "callback" mechanism that each locks perform (we will need to upgrade the "old" unlock to point to the "newer" unlock in that case).

This is probably a very serious upgrade which we'll have to perform slowly and very carefuly.

**Comment by clemsos** [comment]
We are currently at 4.x open zeppelin and 0.8 solidity so closing this
