### ISSUE TITLE
Upgradable Public Lock

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6682]
The Public Lock contracts are currently *not* upgradable neither by us, nor by their owner or admin.
Ideally, at some point, we should make them upgradable by their admins, if they want to.

**Comment by julien51** [comment]
Let's revisit this!

The plan would be this:
* change how `deployLock` works on the Unlock contract so that it deploys a proxy for locks ([either transparent or UUPS](https://docs.openzeppelin.com/contracts/4.x/api/proxy#transparent-vs-uups)). The Unlock contract will be the proxy admin for all locks. (See if it makes sense to still use the [minimal proxy](https://blog.openzeppelin.com/deep-dive-into-the-minimal-proxy-contract/) to deploy the proxy contract.
* In Unlock, instead of keeping track of a single template, we should have an array of all supported templates. The `deployLock` function should always deploy the last item of the array above.
* In Unlock, we add an `upgradeLock` function that takes 2 arguments, the lock address, and the template address. This function should do the following:
  * Verify that the `msg.sender` is one of the lock managers on this specific lock (fail if not)
  * Verify that the template address is "supported" (in the array above) and fail if not
  * Verify that the version of the template address is strictly one version larger than the current version of the lock, and fail if not
  * proceed to the upgrade of the lock!

**Comment by clemsos** [comment]
For reference, WIP here https://github.com/clemsos/sol-upgrade-pattern/blob/master/contracts/ProxyDeployer.sol

**Comment by julien51** [comment]
Closing as this was merged!
