### ISSUE TITLE
Lock icon barely visible

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#671]
We "randomly" pick the color of the lock icons using their addresses. We need o ensure that the color will have sufficient contract over the (white) background.
<img width="226" alt="screen shot 2018-12-05 at 21 58 13" src="https://user-images.githubusercontent.com/17735/49558425-0200d200-f8d9-11e8-80f7-be3eb1c52f17.png">

This one was generated via the address `0xc5C809c94D71463E0c34e8e1c64FbF922839c197`.

**Comment by julien51** [comment]
cc @smombartz

**Comment by benwerd** [comment]
On this: WCAG 2.0 asks for a contrast ratio of at least 7:1 for text. I think it probably makes sense to also use this for icons?

**Comment by julien51** [comment]
Yes! Now to find how to compute that ratio ;)

**Comment by smombartz** [comment]
@julien51 how are you currently generating the colors? probably just dont go above a certain lightness/saturation. might be worth using HSV colors rather than RGB. more on that here: http://printingcode.runemadsen.com/lecture-color/
