### ISSUE TITLE
Recurring memberships

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#6736]
We want to enable recurring memberships.
For this, we will use the [keyPurchase contract](https://github.com/unlock-protocol/unlock/blob/master/smart-contract-extensions/contracts/KeyPurchaser.sol).

**Comment by julien51** [comment]
The keyPurchase is currently setup to use the v7 lock, which means we will need to make sure we "migrate" any lock which wants to use this feature to v7.

After that here is a list of actions:
1. [ ] Deploy the `keyPurchaser` factory. This contract lets us deploy keyPurchase contracts easily. 
2. [ ] Add a script to `unlock-js` to invoke the factory from a command-line.
3. [ ] Deploy a keyPurchaser for a v7 lock.
4. [ ] Update the paywall config to enable the passing of a `keyPurchaser` address to a lock's params.
5. [ ] If the paywall config has a `keyPurchaser` contract, then, we should show the terms of the auto-renewing membership.
6. [ ] If the paywall config has a `keyPurchaser` contract, then, when the user clicks on _purchase_, we should rather emit an `approval` transaction for the ERC20 contract of the lock.
7. [ ] We should update the nudge so that it monitors ERC20 approval to `keyPurchaser` contracts so that if a user has approved a `keyPurchaser` to spend their ERC20, then, we (or anyone!) can send a transaction to purchase a key for that user.
8. [ ] We should monitor expiring keys inside of the nudge as well to send more purchase transactions when applicable.

Note: the `keyPurchaser` contract has a method to specify an amount of gas which can be "paid back" to the msg sender.

**Comment by julien51** [comment]
@NickCuso Does that sound like a decent plan?

**Comment by NickCuso** [comment]
Yup sounds good. We could save a little code and use etherscan's form instead of "Add a script to unlock-js to invoke the factory from a command-line."

**Comment by julien51** [comment]
For those following at home, here is a full flow.

1. There is a lock at [`0x72ef8d4a46c94fe739f880b690bff2a825113abf`](https://etherscan.io/address/0x72ef8d4a46c94fe739f880b690bff2a825113abf). The lock has a key price of 1 DAI, and keys are 1 day long.
2. This lock has a KeyPurchaser at  [`0xa1c718312fd0252540e5ecf6b4cd83fdbfa06acb`](https://etherscan.io/address/0xa1c718312fd0252540e5ecf6b4cd83fdbfa06acb). This purchaser sets a 0.1DAI reward for every person who issues a transaction to purchase a key to a lock and will "renew" key any key that is set to expire within the next hour or has already expired.
3. User [`0x3ca206264762caf81a8f0a843bbb850987b41e16`](https://etherscan.io/address/0x3ca206264762caf81a8f0a843bbb850987b41e16) wants to get a key for this lock, renewing up to 10 times.
4. User [`0x3ca206264762caf81a8f0a843bbb850987b41e16`](https://etherscan.io/address/0x3ca206264762caf81a8f0a843bbb850987b41e16) [approved the KeyPurchaser on DAI to spend up to 10DAI](https://etherscan.io/tx/0x5d3fb6902a3272651460d1ada2abe3b2ab8433f24c9378853b6a4095afc127ce).
3. Another user, [`0xe5cd62ac8d2ca2a62a04958f07dd239c1ffe1a9e`](https://etherscan.io/address/0xe5cd62ac8d2ca2a62a04958f07dd239c1ffe1a9e) [issued a transaction](https://etherscan.io/tx/0xfd5f8dd28cd9f20da00435a562eda0171ecdfa21c8cb0f2367d888f407465aed) which granted a key to `0x3ca206264762caf81a8f0a843bbb850987b41e16`. This transaction did 4 things:
* withdrew 1.1DAI from  `0x3ca206264762caf81a8f0a843bbb850987b41e16`' balance
* sent 1 DAI to the lock, 
* which granted a key to `0x3ca206264762caf81a8f0a843bbb850987b41e16`
* paid 0.1DAI back to `0xe5cd62ac8d2ca2a62a04958f07dd239c1ffe1a9e` in order to cover the gas spent (given the outrageously high gas prices, this was not enough... but could/should have been in days of cheaper gas)

**Comment by julien51** [comment]
Ok, we'll be taking a slightly different approach to this, so probably best to re-open a new issue! Coming soon :)
