### ISSUE TITLE
"Your info could not be saved" sometimes

### ISSUE THREAD

**Issue by snario** [unlock-protocol/unlock#6749]
**Describe the bug**
User sees this error message:"Your info could not be saved"

**Expected behavior**
User should be able to stake on mobile wallet with email metadata field

**Additional context**
Happened on hack.ethglobal.co/hackfs

**Comment by julien51** [comment]
thanks! What wallet is this?

**Comment by snario** [comment]
I'm not sure, it was sent to me as a screenshot from a user. It looks like Coinbase Wallet.

**Comment by snario** [comment]
Seems to happen in other browsers too, with this error:

```js
inpage.js:1 MetaMask - RPC Error: MetaMask Message Signature: Error: Not supported on this device Objectcode: -32603data: {originalError: {…}}message: "MetaMask Message Signature: Error: Not supported on this device"stack: "Error: MetaMask Message Signature: Error: Not supported on this device↵    at t.exports.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:113840)↵    at Object.b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:877369)↵    at h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:876062)↵    at t.exports.s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:879048)↵    at t.exports._setMsgStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:116343)↵    at t.exports.errorMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:116084)↵    at t.exports.signTypedMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:141281)"__proto__: Object
(anonymous) @ inpage.js:1
```

```js
RPC Error: MetaMask Message Signature: Error: Not supported on this device Objectcode: -32603data: {originalError: {…}}message: "MetaMask Message Signature: Error: Not supported on this device"stack: "Error: MetaMask Message Signature: Error: Not supported on this device↵  
```

**Comment by karadikid** [comment]
Had this same issue:

1. Chrome with Metamask latest (May 20, 2020)
2. Brave with built-in Crypto Wallet
3. Both using hardware wallet integrated
4. Used the HW integration with Metamask all day for Dex.ag and others
5. Strange behavior, used MEW instead
6. OSX Catalina 10.5.5

Thanks!
![image (1)](https://user-images.githubusercontent.com/20405181/85963151-5881a580-b982-11ea-8d13-bab2a43a60ba.png)
![image](https://user-images.githubusercontent.com/20405181/85963152-591a3c00-b982-11ea-899e-17763d42491a.png)
![image (2)](https://user-images.githubusercontent.com/20405181/85963154-591a3c00-b982-11ea-97b1-8c2c099483c5.png)

**Comment by julien51** [comment]
@snario the error you see in the console for MetaMask is because we try multiple methods t get the signature (there is apparently not wide support for a typed data signature. (see https://github.com/unlock-protocol/unlock/blob/master/unlock-js/src/walletService.js#L340)

@karadikid I am trying with Chrome and MetaMask and it seems to be working fine. Are you also using a hardware wallet thru MM in that example? Is this Trezor? It looks like they do not support typed signatures https://github.com/trezor/trezor-firmware/issues/131 :/

**Comment by julien51** [comment]
Closing as stale.
