### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by srisankethu** [unlock-protocol/unlock#685]
**Describe the bug**
I was trying to follow the installation instructions and faced some issues.
On running "cd unlock-app && npm run dev", I  am getting errors.
Log -> https://pastebin.com/ACPqX5w3

**To Reproduce**
1. Follow Instructions in README.md

**Expected behavior**
Successful installation

**Comment by julien51** [comment]
Thanks! Could you tell us more about your setup? What OS, version of node?

**Comment by srisankethu** [comment]
On going to localhost:8545 on my browser, it is returning "400 Bad Request"

**Comment by julien51** [comment]
Why would you use a web browser? port `8545` is not necessarily an http server.
You have to find which process listens on that port and terminate it.

**Comment by srisankethu** [comment]
Yes, killed the process. New error though. Updated my log(pastebin).

**Comment by julien51** [comment]
Ok, run `npm install` again from the root because the error indicates you're missing dependencies ;)

**Comment by srisankethu** [comment]
Did it. Same error.

**Comment by julien51** [comment]
Hum. This is strange. Could you show the full logs from `npm install` ?

**Comment by srisankethu** [comment]
I need to do ``npm install eslint babel-register babel-polyfill`` for every new ``npm install`` i.e after ``git clean -dfx``

**Comment by srisankethu** [comment]
https://asciinema.org/a/vychGGRKOHYrR7NO8DDT1CBw8

**Comment by julien51** [comment]
Ok, here are some comments:
 - please do not use `sudo` when running `npm install`. This exposes you to terrible security issues.
- do not run unlock as `sudo` either for the same reasons.
- unfortunately I cannot read the error happening at 2:19. Could you paste it here? (please do not use pastebin because if someone bumps into similar error they would not be able to use search on github to find it...)

**Comment by julien51** [comment]
Hey. For the sake of it, i want ahead and started an AWS EC2 server with Ubuntu and followed the instructions and everything is running as expected. So I am confident we can get you past that finish line ;)

**Comment by julien51** [comment]
Hello, would you be able to provide more details?

Closing for now, but please reopen if you have more data. Thanks
