### ISSUE TITLE
Unlock membership for HTTP/Websocket API?

### ISSUE THREAD

**Issue by cheekybastard** [unlock-protocol/unlock#6864]
Hi,

I've searched code, issues & docs, I can't find any mentions of Unlock membership for HTTP/Websocket API?

With API memberships, the contract would be initiated via browser, but the locked content would be accessed by an non-browser client. Is there a solution for authorizing HTTP/WS access? Like https://api.lockedcontent.com/<authorization_key>

**Comment by julien51** [comment]
Hello!
I am not 100% sure I understand what you are asking for :)
In practice, you can just verify whether the current visitor owns a membership either from the front end, or from a backend service by querying the contracct directly? 
Thanks

**Comment by cheekybastard** [comment]
Hope this a better explanation :)

Your docs & example apps for access control are centred around webpages, which require a user client that can run on page javascript (browser). What I was attempting to ask about was: backend service to backend service access control.

For an example, to use infura.io API the user access control token (e.g. 123456) has to be included in the http request url, https://mainnet.infura.io/v3/123456

So with unlock, for the lock creators backend service to query the contract for user current membership status, the users address (that payed for the membership) would have to be included in the url or headers of the request?

e.g:

Payee address: 0x9876543210000000000000

https://mainnet.infura.io/v3/0x9876543210000000000000

Lock creators backend service parses 0x9876543210000000000000 from request & verifies membership status with contract?
