### ISSUE TITLE
Validate inputs on form when creating lock

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#688]
When creating a lock but entering values which are not of the right type (strings instead of numbers for example), nothing happens. We should probably show an error indicating that and/or update the form field to show it's not valid? (I like when form are circles in red to indicate trouble: @smombartz does it make sense).

**Comment by benwerd** [comment]
Thinking about using this: https://www.npmjs.com/package/react-form-validator-core

Which would allow us to swap out an "invalid" style pretty easily.
