### ISSUE TITLE
Paywall Modal SVG Logo Not Showing Up

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#7043]
**Describe the bug**
SVG logos are not showing up on the paywall modal. pngs work see [here](https://unlock-integration.webflow.io/) (Unlock the Content blue button)

**To Reproduce**
Click to become an unlock member on [homepage](https://unlock-protocol.com/)

**Screenshots**

**Desktop (please complete the following information):**
 - MacOs Chrome, Safari, Firefox

**Comment by julien51** [comment]
Fixed :)
