### ISSUE TITLE
Paywall Modal: Move & Update Wallet Buttons

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#7044]
# Description
- Move paywall modal buttons above lock purchase button to simplify user flow.
- Switch QR Code with walletconnect Icon (cleaned icon without color attributes [here](https://www.dropbox.com/s/wqs1ocsyo867zsu/walletconnect.svg?dl=0))
- [Figma Design & Specs](https://www.figma.com/file/YIvjlf89MZAXTFuBYXI3fv/Unlock-Paywall-2?node-id=388%3A1687)

## Mockup
<img src="https://user-images.githubusercontent.com/1377389/115449134-74dc2080-a1e8-11eb-83e2-c0c8800a1551.png" width="400" height="400">

## Current Implementation for Reference
<img src="https://user-images.githubusercontent.com/1377389/115449310-ad7bfa00-a1e8-11eb-9c87-79cc3e24a90d.png" width="400" height="400">

**Comment by julien51** [comment]
All shipped!
