### ISSUE TITLE
Paywall Modal: Confirmation Screen Update

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#7045]
# Description
- Move Thank You/Confirmation message above purchase button (that way there is a consistent messaging space across all screens)
- Change Close/Back to Site button styling
- [Figma Design & Specs](https://www.figma.com/file/YIvjlf89MZAXTFuBYXI3fv/Unlock-Paywall-2?node-id=388%3A1848)

## Mockup
<img src="https://user-images.githubusercontent.com/1377389/115452586-9b9c5600-a1ec-11eb-8f6c-71d68b25a0cf.png" width="400" height="400">

## Current Implementation for Reference
<img src="https://user-images.githubusercontent.com/1377389/115452627-a6ef8180-a1ec-11eb-9c4a-d29eec939716.png" width="400" height="400">

**Comment by julien51** [comment]
Wer're live :)
