### ISSUE TITLE
Keychain Wallet Auth Error Message

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#7046]
# Description
When you "Authenticate with your browser wallet" and you're not on the right network, there is no error message. There should be an error message though.

## Reproduce
- Got to https://app.unlock-protocol.com/keychain 
- Switch to a non Ethereum Mainnet netowrk
- Click Authenticate with your browser wallet

## Screenshots
mockup coming shortly...

**Comment by julien51** [comment]
Thanks~ Please let me know when design is ready :)
