### ISSUE TITLE
Paywall: Add addresses of unlocked locks in "unlockProtocol.status"-event

### ISSUE THREAD

**Issue by pwagner** [unlock-protocol/unlock#7070]
**Is your feature request related to a problem? Please describe.**
Currently the `unlockProtocol.status` event emits "unlocked" in `event.detail.state`, as soon as any of the locks from the paywall config is unlocked. It would be nice to also know which locks are unlocked.

**Describe the solution you'd like**
`event.detail` can be extended with a list of addresses named `locks`:
```
{
  state: "unlocked",
  locks: ["0x1234", "0x5678"]
}
```

**Describe alternatives you've considered**
In order to apply a special discount code associated with a lock, it's necessary to know whether a certain lock is unlocked or not. It would be nice to have that information available here, otherwise it needs to be retrieved in a separate step.

**Additional context**
This would be useful for example in the context of applying a specific discount code in Shopify.

**Comment by julien51** [comment]
That's a good one! I see you have submitted a PR. I will look into this! Thanks a lot.
