### ISSUE TITLE
Paywall: Load various sets of locks in distinct modals on same page

### ISSUE THREAD

**Issue by pwagner** [unlock-protocol/unlock#7072]
**Is your feature request related to a problem? Please describe.**
At the moment the paywall config is stored in `window.unlockProtocolConfig`, and all its locks are displayed in the same modal after calling `window.unlockProtocol.loadCheckoutModal()`. It's not possible to pass a specific set of locks to the checkout modal.

**Describe the solution you'd like**
It would be nice to be able to pass a list of lock addresses to the checkout modal:
```
const locks = ["0x123","0x456"]
window.unlockProtocol.loadCheckoutModal(locks)
```

**Describe alternatives you've considered**
In addition to relying on `window.unlockProtocolConfig` as fallback config, the modal could process any passed paywall config: `window.unlockProtocol.loadCheckoutModal(paywallConfig)`

**Additional context**
This is useful for example when a shop respects various external memberships, and you want to display related tiered memberships in the same checkout modal, but not all of the different types of memberships all at once.

**Comment by julien51** [comment]
Thanks @pwagner ! This is a very valid feature request and one that I think we can tackle very soon. For simplicity, my idea would be to actually re-use the same config used on the page and pass it to the checkout modal. This way it can be fully configured "differently" (call to actions, icons... etc) for each lock (or group of locks!)

**Comment by julien51** [comment]
Hi @pwagner I will need to update the the locks but you can now pass a custom config when opening the checkout modal!

Please confirm and I'll close this one :)

**Comment by pwagner** [comment]
Can confirm that `loadCheckoutModal()` accepts and applies the passed config. Thank you!
