### ISSUE TITLE
Create unlock domain link for membership purchase

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#7083]
forward [unlock-protocol.com/membership](unlock-protocol.com/membership) to the membership lock that lives [here](https://app.unlock-protocol.com/checkout?paywallConfig=%7B%22network%22:100,%22locks%22:%7B%220xac1fceC2e4064CCd83ac8C9B0c9B8d944AB0D246%22:%7B%7D%7D,%22callToAction%22:%7B%7D,%22referrer%22:%22%22%7D)

why? shorter link, also in case the lock changes the url can be persistent

**Comment by julien51** [comment]
Actually I'll make it so that it has both the current main lock and the xdai lock! Thanks.

**Comment by julien51** [comment]
Also @smombartz I don't know if that's useful bu I added the ability to redirect back to a page when the membership has been purchased.
