### ISSUE TITLE
Only `default` field shown from `callToAction` object regardless of state changes in the paywall

### ISSUE THREAD

**Issue by leopoldjoy** [unlock-protocol/unlock#7091]
**Describe the bug**
In the paywall, regardless of the current status (first time user, expired key, pending transaction, confirmed, no wallet, etc.) the `default` text from the config's `callToAction` object is always displayed.

**To Reproduce**
1. Open the paywall dialog.
2. Click connect wallet and submit a transaction.
3. Notice that the `default` text remains displays.

**Expected behavior**
The field displayed from the `callToAction` config object should reflect the current status of the paywall (first time user, expired key, pending transaction, confirmed, no wallet, etc.) .

**Screenshots**
![Paywall Issue](https://user-images.githubusercontent.com/8941653/117722525-74c8b280-b1e1-11eb-9814-d484f8c75459.png)
Notice that the default text, "This content is locked. Pay with cryptocurrency to access it!", remains displayed even though the user has already bought the key (notice the green check).

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave, Chrome
 - Version (respectively): 1.23.75, 90.0.4430.93

**Comment by julien51** [comment]
Thanks for reporting! I will have a fix coming this week for this along with a few other UX improvements. Please bear with us :)

**Comment by julien51** [comment]
The fix has been  merged and will deployed in the next few days...
