### ISSUE TITLE
Mobile UI for Dashboard

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#710]
The dashboard is currently not mobile friendly... at all!:
<img width="410" alt="screenshot 2018-12-12 at 22 11 23" src="https://user-images.githubusercontent.com/17735/49913239-e490b280-fe5a-11e8-8ef4-a45ea91d5fa4.png">

This is a bit sad because @smombartz actually did a pretty good job at it: 

<img width="519" alt="screenshot 2018-12-12 at 22 13 47" src="https://user-images.githubusercontent.com/17735/49913344-4ea95780-fe5b-11e8-8def-a1d4ad53de05.png">

See [this for live version](https://www.figma.com/proto/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-App?node-id=0%3A269&scaling=scale-down).

**Comment by julien51** [comment]
Similarly the form [can be adapted to mobile](https://www.figma.com/proto/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-App?node-id=0%3A301&scaling=scale-down):

<img width="462" alt="screenshot 2018-12-12 at 22 15 44" src="https://user-images.githubusercontent.com/17735/49913424-8a442180-fe5b-11e8-808c-4ace8637da94.png">

**Comment by benwerd** [comment]
I'll take this on tomorrow. We should consider making it a norm to include responsive screenshots as well as desktop ones when there's a visual change. Let's discuss tomorrow.

**Comment by cellog** [comment]
I started this about 30 minutes ago for fun. Got this much started which you should plagiarize:

```js
import { css } from 'styled-components'

const sizes = {
  desktop: {
    min:1366,
    max: false,
  },
  tablet: {
    min:737,
    max: 1366,
  },
  phone: {
    min: 300,
    max: 736,
  },
}

const media = Object.keys(sizes).reduce((acc, label) => {
  acc[label] = (...args) => css`
    @media only screen and (min-device-width: ${sizes[label].min}px)${sizes[label].max ?
  `and (max-device-width: ${sizes[label].max}px)`
  : ''
} {
      ${css(...args)};
    }
  `

  return acc
}, {})

export default media
```

Can be used like:

```js
const AccountHead = styled.header`
  ${media.desktop`
    display: grid;
    grid-template-columns: auto 1fr 1fr;
    align-items: center;
    grid-gap: 8px;
  `}
  ${media.phone`
    display: flex;
  `}
`
```

**Comment by cellog** [comment]
standard media queries from https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by benwerd** [comment]
Nice one @cellog!
