### ISSUE TITLE
Member List on xDai Lock Not Showing

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#7103]
## Describe the bug
When I go to this locks member list (0xef6389F33ac557405C961030Efcc3b1CE3e6bc17) i get asked to sign 2 metamask messages, then a loading indicator shows, after a while I get an error message.

https://app.unlock-protocol.com/members?locks=0xef6389F33ac557405C961030Efcc3b1CE3e6bc17

## Console
![image](https://user-images.githubusercontent.com/1377389/118562987-bf937e80-b73b-11eb-8fc0-e2ec9e161b60.png)

**Comment by julien51** [comment]
Strange that the locksmith requests are blocked for you. What browser is this? Also any specific extension or ad blocker?
Thanks!

**Comment by smombartz** [comment]
@julien51 Chrome and ad blocker is turned off for unlock domain. same thing in firefox (see console below) and chrome incognito (which only has 2 extensions enabled). it works on mainnet, remember this is on xdai. you don't get this error on xdai?

https://app.unlock-protocol.com/members?locks=0xef6389F33ac557405C961030Efcc3b1CE3e6bc17

**Comment by julien51** [comment]
Found the bug! Fixing it now :)
