### ISSUE TITLE
Unresponsive Lock after MetaMask Rejection

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#7106]
**Describe the bug**
When creating a new lock and then Rejecting the metamask transaction (to edit the lock name for example), I'm able to click into the form fields but as soon as I type anything they lock up (as if the transaction was submitted). See video below.

https://user-images.githubusercontent.com/1377389/118736267-271afe00-b810-11eb-93bd-f25578acaaa4.mov

**Comment by julien51** [comment]
Oh! Indeed. Let me look at this. Thanks for reporting!

**Comment by julien51** [comment]
This has been fixed since then... Not sure when though :)
