### ISSUE TITLE
Integration tests required for the platform app (unlock-app)

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#714]
**Is your feature request related to a problem? Please describe.**
At the moment the repo contains a few components, as items are being developed the totatlity of components need to be tested to ensure that their relationships support the existing set of functionality going forward.

**Describe the solution you'd like**
We should build a test suite that covers smoke testing of basic functionality of the application. 

* Does it load?
* Are locks displayed (with relevant data)?
* Can a basic lock be created?
* etc

**Additional context**
This issue is related to #458 and either should be considered when solving the other.

**Comment by julien51** [comment]
See https://github.com/unlock-protocol/unlock/issues/458 for more details on the integration testing setup.

**Comment by cellog** [comment]
assigning the two code gnomes working on this

**Comment by julien51** [comment]
Closing in favor of https://github.com/unlock-protocol/unlock/issues/1399!
