### ISSUE TITLE
Credit Card - UX Improvement // Unlock modal - Add a PAY NOW CTA

### ISSUE THREAD

**Issue by BarbaraHoudayer** [unlock-protocol/unlock#7190]
**Describe the issue**
As a user (potential member), it is not clear that I have to click in the white frame. 
I am drawn to the Account and Wallet icons which look like CTAs. 

**Suggested behavior/solution**
Have a PAY NOW green CTA instead of the subtle gray cart

**Screenshots**
<img width="1188" alt="Screenshot 2021-06-08 at 10 49 56" src="https://user-images.githubusercontent.com/85551643/121190346-40412880-c86b-11eb-8d82-6cf64e7e1244.png">

**Comment by julien51** [comment]
cc @smombartz I think this is a good idea! Maybe we can bring the arrow back?

**Comment by smombartz** [comment]
very good point. I think we need some bigger changes than just the arrow. theres an imbalance of calls to action.
