### ISSUE TITLE
Credit Card - UX Improvement // Unlock modal - Signup flow

### ISSUE THREAD

**Issue by BarbaraHoudayer** [unlock-protocol/unlock#7191]
**Describe the bug**
As a user, I want to see the Unlock signup modal without scrolling. 

**To Reproduce**
On https://staging-app.unlock-protocol.com/demo?network=4&lock=0x1ee3405841a562cDd987B29ae4bd95d76382ac40
On a Macbook Air 13" (native resolution: 2560 x 1600 at 227 pixels per inch.), Chrome, actual size display.

**Expected behavior**
The modal should not be cut. 
Centering / displaying the modal so the user does not need to scroll will ease signup / remove friction, especially for first time users. 

**Screenshots**
<img width="1431" alt="Screenshot 2021-06-08 at 10 41 02" src="https://user-images.githubusercontent.com/85551643/121191559-5ef3ef00-c86c-11eb-8225-46e69e91e7a7.png">

**Comment by julien51** [comment]
cc @smombartz Let's chat about ways to improve this!
