### ISSUE TITLE
Credit Card - Bug // Julien's Demo page - context does not expand upon payment confirmation

### ISSUE THREAD

**Issue by BarbaraHoudayer** [unlock-protocol/unlock#7194]
**Describe the bug**
On https://staging-app.unlock-protocol.com/demo?network=4&lock=0x1ee3405841a562cDd987B29ae4bd95d76382ac40
As a user paying with credit card, the locked content does not expand after clicking on the "Enjoy your membership" CTA. 

**To Reproduce**
On desktop, Mac, Chrome Version 90.0.4430.212
- Go to https://staging-app.unlock-protocol.com/demo?network=4&lock=0x1ee3405841a562cDd987B29ae4bd95d76382ac40
- Pay with test credit card (4242...)
- Click on "enjoy your membership" (see screenshot 1)
- Locked content remains locked (see screenshot 2)

**Expected behavior**
Locked content should expand after clicking on "Enjoy your membership"

**Screenshots**

Screenshot 1 
<img width="690" alt="Screenshot 2021-06-08 at 11 29 01" src="https://user-images.githubusercontent.com/85551643/121193435-22c18e00-c86e-11eb-99f1-ad5fdea05960.png">

Screenshot 2
<img width="769" alt="Screenshot 2021-06-08 at 15 28 27" src="https://user-images.githubusercontent.com/85551643/121193520-3240d700-c86e-11eb-9311-4aba9ac3d511.png">

**Comment by julien51** [comment]
Just fixed this :) Thanks for reporting!
