### ISSUE TITLE
Deploy all front-end applications to IPFS

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7198]
Our front-end code is currently deployed using a cloud service called Netlify but they are perfectly "static" applications. This means that they can/should also be deployed on IPFS so that they remain accessible at all points, without relying on Unlock Inc's hosting bills :)

We want to have all of our builds to be seamlessly deployed to IPFS, pinned to our Pinata server.
We want to deploy as part of our CI process using the following rules:
- if the CI is running as part of a PR: deploy to IPFS and (do not pin it?). Do not point the IPNS to it
- if CI is running as part of a "master" build deploy to IPFS, pin it forever in our pinata server. Point to a "staging" domain using IPNS
- if CI is running as part of our "production" build, deploy to IPFS, pin it forever in our pinata server. Point our production domain to it using IPNS.

Right now, all front-end applications are deployed thru our CircleCI config. ([see this for example](https://github.com/unlock-protocol/unlock/blob/master/.circleci/config.yml#L178)). This [script then calls](https://github.com/unlock-protocol/unlock/blob/master/scripts/deploy.sh) a yarn command `yarn run deploy-netlify`, but should also probably just call `yarn run deploy-ipfs` :)

We are attaching a 500 DAI bounty to this to which we add a 300 DAI bonus if completed by July 31st!

**Comment by gawainb** [comment]
I'd like to work this bounty also. Where can I find the Piñata credentials?

**Comment by julien51** [comment]
Hey @gawainb! This is exciting! I am sorry for the delay!
I just generated some credentials for you but please make it easy to change them :)

```
API Key: 9b85cfe6f7ea2a9a7930
 API Secret: cf54bb75174b3a4710ead05825ae57a7f0f0cbca4843246cdc4e8d9bb294c283
 JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIwMzc0ZWQyNi1iYmZhLTQyYzYtYWRlYi0zYzA5MDIyNDdhY2UiLCJlbWFpbCI6Imp1bGllbkB1bmxvY2stcHJvdG9jb2wuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siaWQiOiJOWUMxIiwiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjF9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZX0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6IjliODVjZmU2ZjdlYTJhOWE3OTMwIiwic2NvcGVkS2V5U2VjcmV0IjoiY2Y1NGJiNzUxNzRiM2E0NzEwZWFkMDU4MjVhZTU3YTdmMGYwY2JjYTQ4NDMyNDZjZGM0ZThkOWJiMjk0YzI4MyIsImlhdCI6MTYyNzU1NDUyN30.D70acHJFZUp1BKn8LL4tn6GYUCj0qJs3XJnV62NZxeY
```

**Comment by julien51** [comment]
Edit: bumping that reward to 500DAI + 500 DAI if completed by November 21st at midnight ET!

**Comment by searchableguy** [comment]
I had some time to look into it today. 

From what you described, we will need a script which warms a IPFS node in CI and add content to it so it can be queried temporarily (will be removed on garbage collection if no one else pins in the meantime - are there enough nodes to make this not a problem? I'm new to it)

For production run, we would pin this hash using pinata node sdk and add the domain using gateway APIs from pinata.

I had one question.

Is there any reason to not use a managed decentralized ipfs hosting service like [fleek](https://fleek.co/hosting/) which will pretty much take care of what we are doing and make it easier to manage long term?

@julien51

**Comment by julien51** [comment]
Thanks for doing the research here! Yes, I think garbage collection is not a huge challenge and I think we should find a mechanism to pin things.

Fleek could be a decent option, even if I want to explore what happens when/if they go "down" and how much coupling we would be introducing. Agreed about using ENS if we can!

Want to try to use Fleek? What do you need from me/us? An API key?
Thanks
