### ISSUE TITLE
Scaffold Eth integration

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7211]
[Scaffold Eth](https://github.com/austintgriffith/scaffold-eth) is a fantastic tool for developers who are starting their journey in the web3 world.

It would be fantastic to find a way for someone to create an example of how to use Unlock in a scaffold-Eth project

**Comment by SpookyTiang** [comment]
I will take this initiative

**Comment by julien51** [comment]
@daweth Are you still interested? Sorry for the delay here...

**Comment by daweth** [comment]
@julien51 , yes, will begin breaking ground in the next week or so

**Comment by julien51** [comment]
Very cool! Thanks @daweth !

**Comment by julien51** [comment]
I think this plugin should use https://github.com/unlock-protocol/unlock/tree/master/packages/hardhat-plugin

**Comment by blahkheart** [comment]
This is awesome, I'll love to work on this

**Comment by julien51** [comment]
Very excited to see the progress here @blahkheart !

**Comment by blahkheart** [comment]
Thanks @julien51 creating a PR to wrap things up. Would love for you to run through and see if everything is okay.

**Comment by amankaushik481** [comment]
hey @julien51  can I contribute to it now, it's my first open-source contribution

**Comment by julien51** [comment]
> Thanks @julien51 creating a PR to wrap things up. Would love for you to run through and see if everything is okay.

Yes! Let's find some time next week? Please ping me on Discord :)

**Comment by julien51** [comment]
> hey @julien51 can I contribute to it now, it's my first open-source contribution

As you can see this is nearly wrapped up! Anything else [in there](https://github.com/unlock-protocol/unlock/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that you might be interested in?

**Comment by blahkheart** [comment]
> > Thanks @julien51 creating a PR to wrap things up. Would love for you to run through and see if everything is okay.
> 
> Yes! Let's find some time next week? Please ping me on Discord :)

Okay, will do!

**Comment by wonderwomancode** [comment]
https://github.com/unlock-protocol/scaffold-eth-unlock
