### ISSUE TITLE
Error Handle Misconfigured Paywall

### ISSUE THREAD

**Issue by GeekyLumberjack** [unlock-protocol/unlock#7244]
**Describe the bug**
If a user incorrectly configures the paywall it will never tell them and never properly load

**To Reproduce**
1. purposely configure paywall incorrectly. Such as using an XDAI lock on the MATIC network
2. launch the paywall Modal

**Expected behavior**
An error letting the user know that the lock was not found on the configured network.

**Screenshots**
![Screenshot from 2021-06-26 02-37-56](https://user-images.githubusercontent.com/25039107/123506007-95c95380-d627-11eb-954d-d00866f9bed0.png)

**Comment by julien51** [comment]
Thanks, that's a good idea! I'll work on this early next week!

**Comment by julien51** [comment]
Fixed!
