### ISSUE TITLE
Package.json and package-lock.json inconsistency

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#728]
When `package.json` is changed we should enforce that the corresponding `package-lock.json` is also part of the commit.

**Comment by julien51** [comment]
For example, [this PR](https://github.com/unlock-protocol/unlock/pull/718) introduced a discrepancy.

**Comment by julien51** [comment]
Same "realm" as https://github.com/unlock-protocol/unlock/issues/808

**Comment by akeem** [comment]
This has been open for close to a year, it appears as though we have either found a work around for this or have deemed it a non-issue. If this is still an issue we can definitely revisit it
