### ISSUE TITLE
Color in App icon persistently 

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7302]
<img width="1113" alt="screenshot" src="https://user-images.githubusercontent.com/44031/125338984-bb33ae00-e305-11eb-8a2f-08e9fbd75064.png">

<img width="198" alt="screenshot" src="https://user-images.githubusercontent.com/44031/125339843-955ad900-e306-11eb-9c6d-0d222c7963d7.png">

App icon should be colored in to draw attention to it.

**Comment by julien51** [comment]
Good one!
