### ISSUE TITLE
Add more spacing between header and title

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7303]
Unlock Navigation and the blog title is too small. 

Interface feels crowded and not enough room. 
Try 64px or 72px spacing 

<img width="1161" alt="screenshot" src="https://user-images.githubusercontent.com/44031/125340190-0601f580-e307-11eb-8aec-e8bf16227e51.png">

**Comment by julien51** [comment]
Oh! That's a good one. I did not look at the blog at all, but I'll do a pass.

**Comment by julien51** [comment]
fixed

![image](https://user-images.githubusercontent.com/17735/125468881-a4eba6aa-7924-4da6-a7e8-9b22ddf42ba8.png)
