### ISSUE TITLE
Add links to all of the integration buttons 

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7305]
<img width="1142" alt="screenshot" src="https://user-images.githubusercontent.com/44031/125341332-5d549580-e308-11eb-9244-993703412c14.png">

None of these are linked yet. Please link to the relevant documentation. 
* https://docs.unlock-protocol.com/creators/plugins-and-integrations/wordpress-plugin
* https://docs.unlock-protocol.com/creators/plugins-and-integrations#webflow
* https://docs.unlock-protocol.com/creators/plugins-and-integrations#cloudflare
* https://docs.unlock-protocol.com/creators/plugins-and-integrations/discord
* https://docs.unlock-protocol.com/creators/plugins-and-integrations#discourse
* https://www.youtube.com/watch?v=oVZi7m-UOtE
* https://docs.unlock-protocol.com/creators/plugins-and-integrations#shopify 
*

**Comment by julien51** [comment]
Doh! Sorry about that! Fixed.
