### ISSUE TITLE
Link to lock part of documentation vs. just standard docs. 

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7306]
<img width="367" alt="screenshot" src="https://user-images.githubusercontent.com/44031/125343791-5418f800-e30b-11eb-9254-98b546cdead1.png">

Link this one to: 
https://docs.unlock-protocol.com/creators/deploying-lock
vs. just the raw documentation.

**Comment by julien51** [comment]
Good catch! Fixed.
