### ISSUE TITLE
Add more spacing between blog and tagline, turn tagline black for readibility 

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7312]
<img width="616" alt="screenshot" src="https://user-images.githubusercontent.com/44031/125389563-4341a400-e356-11eb-8fbc-d5a1c2cb60e3.png">

Consider 32 px or 45px 64px. 

Replace 
"We’re building the new business model for the web that empowers creators." 

With
"Unlock the potential of memberships".

**Comment by julien51** [comment]
Yup .Thanks. Fixed.
