### ISSUE TITLE
Async job to identify Unlock transactions

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7316]
One of the building blocks which we miss right now is the ability to trigger things when:
1. new locks are deployed
2. new memberships are purchased

We need to build a basic service that would leverage our hosts (Heroku) cron job feature and our subgraph to extract these things. The job should be able to ping a 3rd party service such as zappier with details so that we can fan-out to other applications such as a Twitter bot or our Discord... or Zapier.

## Registring hooks:

For this, we will use an API based on the [WebSub W3C recommendation](https://www.w3.org/TR/websub/), where we are hosting our own "hub" at `/api/1/hooks/`. (`1` is the current API version)
3rd party application will be able to register hooks on these 2 endoints:
* `/api/1/hooks/<network>/locks` for new locks deployed where `network` is the network on which the lock is deployed. `*` can be used to register a hook on locks being deployed on any network.
* `/api/1/hooks/<network>/locks/<lock address>/keys` for new keys being purchased on the lock deployed on `network` at `lock address`.

We will add more endpoints later on, for example to listen on lock property changes or key property changes.

## Triggering hooks

We will run a cronjob that runs every 1 minute. The job's workflow is this:
* for every supported network (see @unlock-protocol/networks), we will list all of the locks deployed within a (configurable) time frame of 1 hour to get started, using our subgraphs.
* for every lock in that list, prepare an update to be posted as a JSON object of lock (using the subgraph's schema). 
* identify all registered hooks
* check whether the hook has already been successfuly notified for that specific update in a dedicated `hook_triggers` table (that needs to be added)
* if the notification already happened, skip
* if the notification did not happen, perform the WebSub notification. 
* if the notification succeeds, store that state in the table.
* if the notification failed, store it in the table, but with a "failed" status and an indication of the "attempt" number. 
* drop any notification that has failed more than x times (x should be configurable but defaults to 5).

(This is WIP, please ask any clarifying question!)

**Comment by gawainb** [comment]
I can help get this taken care of. Do you prefer Zapier? Is there a community account to sign up with?

**Comment by julien51** [comment]
Thanks @gawainb ! Let's focus first on creating the job, and just printing the stuff which would be sent to Zapier and we can hook Zapier last. Does it make sense?

**Comment by gawainb** [comment]
> 
> 
> Thanks @gawainb ! Let's focus first on creating the job, and just printing the stuff which would be sent to Zapier and we can hook Zapier last. Does it make sense?

Gotcha!

**Comment by julien51** [comment]
Tasks:

* [ ] create a table `hooks` with the following fields: `hook_id` (primary key), `network`, `lock`, `expiration`, `url`, `secret`, + default time based attributes (`created_at`, `updated_at`)
* [ ] create a table `hook_events` with the following fields: `event_id` (primary key), `network`, `lock`, `key` (optional), `hook_id`,  `'body`, `state`, `attempts`
* [ ] implement API to `subscribe` to hook (`[using WebSub's API](https://www.w3.org/TR/websub/#subscribing-and-unsubscribing)`)
* [ ] implement cronjob to list locks
* [ ] implement cronjob to list keys

Later:
* [ ] implement API to `unsubscribe` from hook (`[using WebSub's API](https://www.w3.org/TR/websub/#subscribing-and-unsubscribing)`)

**Comment by searchableguy** [comment]
Odd how github automatically closes the issue. :/
