### ISSUE TITLE
Landing Page - Mobile optimisation

### ISSUE THREAD

**Issue by BarbaraHoudayer** [unlock-protocol/unlock#7319]
**Describe the bug**
When browsing the page on mobile, the frames and text do not use the full width of the screen. 
<img width="343" alt="Screenshot 2021-07-13 at 21 51 18" src="https://user-images.githubusercontent.com/85551643/125517157-63070ee2-9a82-4356-9f69-54e6e3bab4cd.png">

**To Reproduce**
Navigate to landing page on iPhone (iOS 14, Safari and Chrome)

**Expected behavior**
Fix right margins and padding across the page 
Example here:
<img width="404" alt="Screenshot 2021-07-13 at 21 51 42" src="https://user-images.githubusercontent.com/85551643/125517535-e73a83a1-a237-4a98-97f3-f8a83e3d9ee1.png">

**Comment by julien51** [comment]
Fixed!
