### ISSUE TITLE
Landing page - Above the fold mobile optimisation

### ISSUE THREAD

**Issue by BarbaraHoudayer** [unlock-protocol/unlock#7320]
**Describe the bug**
On mobile, the first block of content on the homepage is cut, which makes a weaker first impression. 

**To Reproduce**
Navigate to landing page on iPhone, iOS 14, Safari
or use chrome inspector and check for mobile devices.

**Expected behavior**
- Shorten grey margin at the top
- Remove the line break in the subtitle "community,<br> across all your platforms
- Possibly decrease H1 title and Subtitle font size for mobile resolutions
- Or possibly decrease the size of the image (may look tiny though)

**Screenshots**
<img width="343" alt="Screenshot 2021-07-13 at 21 51 18" src="https://user-images.githubusercontent.com/85551643/125518928-00b30237-8fbb-406a-8fad-51e7e3d95e5f.png">

**Comment by julien51** [comment]
Fixed, I think!

**Comment by julien51** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
