### ISSUE TITLE
Landing Page - Copy / Styling suggestions to improve legibility 

### ISSUE THREAD

**Issue by BarbaraHoudayer** [unlock-protocol/unlock#7323]
**Is your feature request related to a problem? Please describe.**
As a user scrolling on the landing page, the second block of content is too similar to the first one and is hard to read. 

<img width="671" alt="Screenshot 2021-07-15 at 21 57 54" src="https://user-images.githubusercontent.com/85551643/125849923-d8f5dcda-82da-41a6-bf9f-d3fbbe69e971.png">

**Describe the solution you'd like**

We need to set the "Create Locks and Manage Memberships" apart, otherwise it looks repetitive / overwhelming. 
See screenshots

1/ Remove white background (re-use same transparent background as "WHY UNLOCK")
<img width="525" alt="Screenshot 2021-07-15 at 21 55 58" src="https://user-images.githubusercontent.com/85551643/125849949-5305bbb3-301f-4bba-8d51-b92efdb81252.png">

2/ Replace "Create locks or Manage Memberships" by "WHAT YOU CAN DO WITH UNLOCK", and use the same styling as "WHAT THE COMMUNITY IS SAYING" (currently h4, would make h4 our h3)

<img width="487" alt="Screenshot 2021-07-15 at 22 03 53" src="https://user-images.githubusercontent.com/85551643/125851745-83a74cfd-3531-40c9-a744-1145967dd2b0.png">

- Replace "Keys and Memberships" CTA by "Manage keys & memberships"
<img width="328" alt="Screenshot 2021-07-15 at 22 15 48" src="https://user-images.githubusercontent.com/85551643/125851925-f9125686-ee64-423b-a141-91e297b377d0.png">

Thanks :)

**Comment by julien51** [comment]
Fixed!
