### ISSUE TITLE
Landing Page - Mobile optimization - spacing of "Why Unlock" benefits

### ISSUE THREAD

**Issue by BarbaraHoudayer** [unlock-protocol/unlock#7324]
**Describe the bug**
On mobile, the WHY UNLOCK benefits have sub-optimal spacing. 
It makes the benefits look cluttered. 

**Expected behavior**
- Increase spacing between "WHY UNLOCK" and the first benefits' image. 
- Add a capital C for "Community" inside "Your Content, your Community"
- Increase spacing between each benefit
- Increase spacing between the benefit image and its title to make it breathe

**Screenshots**
See description in the attached screenshot
<img width="349" alt="Screenshot 2021-07-13 at 22 47 41" src="https://user-images.githubusercontent.com/85551643/125523114-26cab2a4-66f3-40df-8788-8357cac38f37.png">

**Comment by julien51** [comment]
Good one! Fixed.
