### ISSUE TITLE
Improve lock flow and credit card lock flow 

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7326]
<img width="456" alt="screenshot" src="https://user-images.githubusercontent.com/44031/125836868-87eb9516-a552-47e7-96e4-6e15bdd92ae0.png">

Currently there are two blue buttons on the lock screen. These are distracting, because the user action to do is to click on the lock to access payment options. For returning users, usually there is a connect with wallet on the top right, but we cannot do that, because that is where the x is. 

## Part 1 
Remove the blue icons and replace with the following: 

1. Left justify 
"Already a member? Access with your" 

2. Below, place a text link to account 

Below that

3. Link to your wallet. 

This solves the issue of someone returning. They will not want to click through the lock again. 

## Part 2 
Make the blue arrow on the lock more prominent. 

(In general, we want people to click this button as the next step as this is how they will pay for the lock. After this they will get the pay with wallet or credit card. Over time we should consider ways to make this very prominent).

## Part 3 
If a lock has credit card enabled, show the FIAT amount more prominent than the ETH amount. 

This should solve some of the confusion we've been seeing with lock purchase flows. 

Once deployed, let's test this new flow to see any extra places people are getting stuck so we can further smooth the process.

**Comment by julien51** [comment]
Part 2 is a bit trickier so I have skipped for now :) but the rest is in place!
