### ISSUE TITLE
Add Unlock Showcase Link to Unlock Showcase Announcement Post

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7344]
https://unlock-protocol.com/blog/unlock-showcase doesn't have any links to Unlock Showcase, the site. 

**Unlock Showcase** features interesting projects built with Unlock Protocol as well as third party tools and resources for developers. They would love to get to know about yours: submit it now! 

Add the link: https://www.unlockshowcase.com/

**Comment by julien51** [comment]
Oh wow! Thanks for this. I'll fix it today.
