### ISSUE TITLE
change button color on dev page. 

### ISSUE THREAD

**Issue by desertrat10** [unlock-protocol/unlock#7351]
Nothing major, just think the button color on this orange block should be a white outline like the others (and the pink clashes w/that yellow a bit). If white on yellow isn't readable, the dark outline works too (same font color as the dark text in the yellow block. 

Also, is there another bluer galaxy background to swap out with the purple one? Since the other three are blue, the purple one seems out of place. This is a me being nit-picky, so ignore this if it's a pain in the arse to switch. 
![Screenshot (10)](https://user-images.githubusercontent.com/19274187/127718831-d659917d-5dca-49ff-9558-ef8788259bbc.png)
![Screenshot (11)](https://user-images.githubusercontent.com/19274187/127718834-ddc631d8-b4a3-481b-ba1e-0c43b7398369.png)

Other than that, everything looks good and it looks like all the buttons work too. ;)

**Comment by julien51** [comment]
Let's revisit this once we get the final design from the DeepWork team...
