### ISSUE TITLE
enforce npm version or investigate moving to yarn

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#738]
currently, we are getting a lot of package-lock.json noise on commits when different versions of npm are used. It would be great to enforce a particular npm version.

Alternatively, we could investigate moving to yarn as the preferred package manager

**Comment by nfurfaro** [comment]
Depending on how easy (or not) it is to pin the npm version, yarm may be the simplest approach? I had always thought that yarn was "better" in some way, but not sure if this is actually the case.

**Comment by julien51** [comment]
I juts went thru [this issue](https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json) and it looks like there are things we can do with `npm` to get started. The first one is probably to pin the versions inside our package.json.

Once we've done that we should ensure that @greenkeeper[bot] still works.

Another learning from this is that we can/should use `npm ci` in `tests.sh` to run on travis and co. This will make our builds faster and also more "stable".
