### ISSUE TITLE
Should not need to rely on `shell.exec` to call  the ZOS `add` command.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#740]
In `smart-contracts/test/Unlock/UnlockProxy.js` we are using shell.js to use the zos-cli in order to call the `add` script. It should be possible, and is preferable, to achieve the desired result without resorting to using `shell.exec`. It works...but can be viewed as a temporary workaround.

**Additional context**
For real deployments, we're using zos-cli (zeppelinOS). In our tests, we want to mimic as closely as possible the behaviour of the cli. The `zoz` package provides us with a `TestHelper` to make this easier, but it doesn't match exactly with the steps we're taking when we deploy with the cli. 
Calling `await shell.exec('zos add UnlockTestV2:Unlock --skip-compile')` helps us to sync our deployment/upgrade process in our tests with the process we use in the cli.

This could be an issue on the zos side of things, but it's not yet clear that this is the case. Here's the issue in the zos repo: https://github.com/zeppelinos/zos/issues/353#issuecomment-447864719

**Comment by julien51** [comment]
@nfurfaro Where are we on that front?

**Comment by nfurfaro** [comment]
@julien51 thx for pointing this out. this issue is fixed. closing.
