### ISSUE TITLE
typo on decentraland blog post---duplicate sentences

### ISSUE THREAD

**Issue by desertrat10** [unlock-protocol/unlock#7405]
At the bottom of the article, the first sentence is duplicated. I think this might have happened where the typo from the first draft was fixed. ;) 

_Unlocking games!

In a game, a membership can let the user access specific private spaces, like a saloon, a concert, a lecture… etc, but they can also let users unlock features or particular features. In a game, a membership can let the user access specific private spaces, like a saloon, a concert, a lecture…, but they can also let users unlock features or particular features, and more!_

**Comment by julien51** [comment]
Fixed!
