### ISSUE TITLE
Update image on Grant Class 1 Post 

### ISSUE THREAD

**Issue by caseorganic** [unlock-protocol/unlock#7412]
On the first grant class post, the image is incorrect. The current image reads 20201 instead of 2021. Also the contrast on the image is not sufficient for web standards. Below is a new graphic to use for the post: 
https://unlock-protocol.com/blog/udt-grantee-class-1

![grant-program June 2021](https://user-images.githubusercontent.com/44031/128648829-c657ffcb-ae66-4e76-bf0a-e54e23e2f7ff.png)

Change to the attached image which is in line with the new Unlock galaxy theme. All images for grants moving forward will follow this design. Update the image on this post https://unlock-protocol.com/blog/udt-grantee-class-1

**Comment by julien51** [comment]
good catch!
