### ISSUE TITLE
Mono repo improvements

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7427]
We currently use a mono repo approach but we're still duplicating too many dependencies between the various projects.
Additionally, some sub-folders such as unlock-js and unlock-assets are dependencies to others and we should simplify how they are being imported.

Eventually the goal is to make it much easier for anyone to run these applications as well as reduce our build/test time.

**Comment by clemsos** [comment]
Reading various docs and articles, a few other solutions exist outside of the combo yarn workspaces + lerna. 

- Lerna supports yarn natively and yarn recommends lerna in its [workspaces docs](https://classic.yarnpkg.com/en/docs/workspaces/#toc-how-does-it-compare-to-lerna). Both seems to work fine but I read lots of complains discussing how slooooww lerna is
-  [Microsoft Rush](https://github.com/microsoft/rushstack/tree/master/apps/rush) seems to work much faster and less trouble with [yarn hoisting](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/)
- [NX](https://nx.dev/) but it seems to address tasks for projects with much larger teams with automations, multiple languages, etc - see [here](https://nx.dev/latest/react/guides/lerna-and-nx)
- use pnpm with [workspaces](https://pnpm.io/workspaces), much faster, less code and deps

My takeaway from reading all this and previous experience with monorepos 

1) lerna is kind of bloated
2) moving to pnpm will really increase build speed - but may require to remove yarn from existing
3) rush and nx are both worth exploring more. Nx seesm to have steeper learning curve but provide top-nocth integration with ms stack (VS code, github, etc)

**Comment by clemsos** [comment]
After some testing, it looks like nx addresses several needs that aren't cover by yarn/lerna - for instance managing global eslint settings, using optimized test runners etc - see their [blog post](https://blog.nrwl.io/lerna-yarn-nx-faster-build-times-better-dev-ergonomics-2ec28463d3a5). There is also documented ways to run CIs / deploy using Circle or [Github actions](https://medium.com/ngconf/deploying-nx-affected-apps-from-github-actions-af28f8822ff3).

The only remaining question is the "migration" process. Nx, lerna, etc all have quite opinionated ideas about folders structure i.e. all code living in a `/packages` subfolder. Adding this tools will require quite a lot of changes in how the repo is organized - and therefore rewrite CIs etc . 

They both provide CLI tool to generate a fresh (empty) template with all config files. Then we will need to merge it at the root of the existing repo and add relevant config etc

**Comment by clemsos** [comment]
Run across [bolt](https://github.com/boltpkg/bolt/issues) which seems lighter and somehow less cumbersome than nx. The main issue is that it is not actively developed, even though it is used and maintained - so no additional features expected.

They are also a bunch of build systems like [Bazel](https://docs.bazel.build/versions/3.7.0/rules.html) by Google, [Buck](https://buck.build/) by Facebook, [Pants](https://www.pantsbuild.org/docs/welcome-to-pants) (by Twitter?) and even [Please](https://please.build/). These will mostly address build speed and most don't support many languages (mostly Go and few others).

As we are all JS, we should focus on 1) making the lint/test tooling consistent and 2) make the build/CI as smooth as possible. The best path will be 

1. add yarn workspaces for deps management
2. figure out a common test framework (jest?)
3. figure out consistent build
4. re-assess the needs and pick the right tool (lerna or nx?)

**Comment by clemsos** [comment]
Doing some more writeup at https://github.com/unlock-protocol/unlock/pull/7446#issuecomment-911528582 to bring some clarity. These 20min build time are killing me haha...

**Comment by clemsos** [comment]
From what I have gathered so far, monorepo-related improvements will be

- [ ] cleanup deps (see #7503 or #7501)
- [ ] move docker conf to buildx/multi-stage 
- [ ] create shared packages
   - [ ] eslint config
   - [ ] jest config
   - [ ] ts config
   - [ ] smart contracts test helpers
- [ ] add yarn v1 support for workspaces

once we are there, we can reassess the move to yarn v2 and its caching issues as discussed in #7446

**Comment by julien51** [comment]
Ok, this is really good! It looks like we're getting there! The last one is not quite fully mono-repo specific, so I'll close this issue!
