### ISSUE TITLE
Improvement: Add Disabled status to subgraph

### ISSUE THREAD

**Issue by iamzubin** [unlock-protocol/unlock#7429]
Currently there is no way of knowing if the lock has been disabled using the subgraph api
Add disabled status to lock query in subgraph would resolve this

**Comment by julien51** [comment]
This is a good one! We actually also should show it on the checkout UI because right now I don't think we do :(

**Comment by clemsos** [comment]
The disable feature has been removed starting with v10, so we can add for previous versions only
