### ISSUE TITLE
cleanup smart-contract deployment scripts

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7436]
in the `smart-contracts/scripts` folder, we have different kind of scripts that should be sorted out.  Also there are artefacts of past processes (like importing data from  the `OZ_CLI` export) that could be replaced directly by using the `.openzeppelin` manifest.

**Comment by clemsos** [comment]
here we could basically turn most of the hardhat scripts into tasks. So instead of having `hardhat run scripts/verify.js` we can have `hardhat verify -- contrat contracts/Unlock.sol` for instance

**Comment by julien51** [comment]
Awesome! great work!
