### ISSUE TITLE
Each key should have a unique and immutable ID for ERC721 compatibility.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#748]
We currently use the owner's address as the tokenId which means that when ownership is changed, the tokenId itself is changed, which is not how the ERC721spec works.

From the official spec: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md
"Every NFT is identified by a unique uint256 ID inside the ERC-721 smart contract. This identifying number SHALL NOT change for the life of the contract. "

**Additional context**
#148, #758, #759
 @ChrisCates has done some work on this.

**Comment by ChrisCates** [comment]
@nfurfaro, hey, sorry I've been AWOL on that PR. Fell behind on other work last week, I have been catching up this weekend, and, will make sure to get a proper PR for you guys to review.

Chat soon!~

**Comment by nfurfaro** [comment]
@ChrisCates No worries. I just thought it would make sense to break down "ERC721" compatibility into some smaller elements to make for simpler PR's/reviews. This is one such element.

**Comment by nfurfaro** [comment]
@hardlydifficult I was thinking the tokenID could be as simple as a uint that gets incremented, starting with 1 and leaving 0 unused (so we can always check a tokens' existence by checking if its ID == 0)
Is this more or less what you're thinking here?

**Comment by nfurfaro** [comment]
I think once we've defined here what the strategy is for assigning tokenID's we should get it implemented. Not sure that we want to merge changes before v0 launch or not, see my concerns here:
https://unlock-protocol.slack.com/archives/CB59A879U/p1547665104386300

**Comment by hardlydifficult** [comment]
I'm going to take a stab at this.  Let me know if it would be better to wait for our ERC721 conversation to continue, otherwise we can review in more detail once there's a PR.

**Comment by nfurfaro** [comment]
I think it's reasonable to go for it and discuss more on the PR review @hardlydifficult.
