### ISSUE TITLE
Mac M1: "The requested image's platform (linux/amd64) does not match the detected host platform"

### ISSUE THREAD

**Issue by MrsBookik** [unlock-protocol/unlock#7507]
**Describe the bug**

Building the containers with docker-compose gives the following error:

`"The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"
`
After this line nothing else will happen anymore and the whole process is in stuck, although the qemu-system-aarch64 is running on 100% CPU according to Activity Monitor until I press Ctrl-C.

**To Reproduce**
1. clone the repo
2. cd into "docker" directory
3. `docker-compose up --build`

**Expected behavior**

On older Intel macs, everything works fine.

**Desktop (please complete the following information):**
 - OS: MacOS 11.4

MacBook Pro M1 with 16 GB RAM.

**Comment by MrsBookik** [comment]
I was also asking on StackOverflow: https://stackoverflow.com/questions/69054921/docker-on-mac-m1-gives-the-requested-images-platform-linux-amd64-does-not-m

**Comment by julien51** [comment]
Thanks @MrsBookik for reporting this.
To be honest, I am not sure what is wrong here. Do you have a more complete trace just so I can identify which step is failing?

**Comment by julien51** [comment]
I will close because the SO response worked for me.
`docker build --platform linux/arm64  .`
