### ISSUE TITLE
Key Quantity: No way to switch back from Unlimited

### ISSUE THREAD

**Issue by zherring** [unlock-protocol/unlock#7511]
**Describe the bug**
No way to switch back to a **limited** key quantity 

**To Reproduce**
1. Go to Create new lock
2. Click on "Unlimited" under Key Quantity

**Expected behavior**
Would expect a way to switch back to a limited key quantity. Currently there is no way to switch without cancelling the lock and starting all over.

**Screenshots**
![image](https://user-images.githubusercontent.com/2172549/132361975-05c2d28a-ec6e-4538-b633-f83b9f73b8c4.png)

**Desktop (please complete the following information):**
 - MacOS
 - Firefox (MetaMask)
 - 91.0.2 (64-bit)

**
**Additional context**
I searched open and closed issues to make sure this wasn't already reported, hopefully this isn't just noise. Thanks!

**Comment by julien51** [comment]
Oh! You can just type in the field and it should just revert to a value :) Please let me know if that solves it!

**Comment by julien51** [comment]
Hey @zherring, please re-open if this is still an issue. Thanks!
