### ISSUE TITLE
Broken deployments

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7515]
As part of the move to a [simpler staged docker](https://github.com/unlock-protocol/unlock/pull/7505) setup we might have broken deployments for locksmith.

Indeed, this new PR removes the `unlock-core` image that we used until now, as well as the customer image for locksmith which is actually used to deploy to Beanstalk.

We should restore this :) as well as cleanup the script to promote images (as well as data on docker.com)

**Comment by clemsos** [comment]
Talking about deployments, it may be good to move all deployments logic to a `deploy` folder at the root instead of having `scripts` in each folder. Will be easier to get an overview of what is deployed where and reuse logic when necessary

**Comment by clemsos** [comment]
> as well as cleanup the script to promote images (as well as data on docker.com)

I removed all images that are mostly left dangling in docker hub. They dont even have a readme so not sure how useful it can be for tohers

**Comment by julien51** [comment]
> Talking about deployments, it may be good to move all deployments logic to a deploy folder at the root instead of having scripts in each folder. Will be easier to get an overview of what is deployed where and reuse logic when necessary

Let's do it!

**Comment by julien51** [comment]
> I removed all images except locksmith that are mostly left dangling in docker hub. They dont even have a readme so not sure how useful they can be for others


Yeah, I think that's fine. Let's just keep there a bit just in case we need them, but we can clean up in a few months.

**Comment by clemsos** [comment]
still broken, not sure why https://app.circleci.com/pipelines/github/unlock-protocol/unlock/17925/workflows/2e9e4aeb-c1e1-46e5-a0e8-7f330212545b/jobs/249246
