### ISSUE TITLE
Decrease the polling frequency of currency conversion checking within the platform application

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#754]
**Is your feature request related to a problem? Please describe.**
Currently we are polling a service provider to ensure that the platform application has up to date prices to support the pricing of keys (eth/dollars) etc.

**Describe the solution you'd like**
1. Reduce the frequency of fetching of data from the third party API
2. Move the initial fetch to the backend
  a. Start to proxy platform request to the backend
  b. Have the client poll the third party API if there is a need to fail over.

**Comment by julien51** [comment]
I think we can eventually cache the API call inside locksmith?
