### ISSUE TITLE
Full Unlock smart contracts deploy task

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7554]
In order to easily deploy to new networks we need a Hardhat task that can deploy a whole new environment for Unlock on any chain.

The task will take a few params, starting with the network id, and whether this is a test network or a production network.

Prerequisites (test net setup should be scripted):
* On production networks. 
    * bridge UDT from the mainnet to the sidechain/L2 (address of UDT on side chain shall be passed as param to the script). Passed as `--udt-address` to task
    * deploy Gnosis SAFE with signers + taken from Unlock's mainnet multisig `0xa39b44c4AFfbb56b76a1BF1d19Eb93a5DfC2EBA9`. Passed as `--multisig-address` to task.
* On test networks: 
    * deploy a UDT contract with premine assigned to deployer
* Create Uniswap v2 pool for UDT/native token (Eth on mainnet, Matic on Polygon... etc)
* Deploy Oracle for UDT price using pool from previous step

These are the tasks to do:
1. Deploy upgradable Unlock contract
2. Deploy the PublicLock template
3. On test networks only: grant `minter` role to UDT contract. (on prod network, we will transfer some UDT from mainnet to the local contract)
4. Configure Unlock contract with right values for UDT, native contract as ERC20 (Wrapped Eth on mainnet...), symbol, gas estimate, base URL for tokens
5. Set template address on Unlock
6. On production networks: change ownership of Unlock to multisig, change proxy admin to multisig (deployer should have no special role on any contract)

After that, extra steps remain to be done and the script should output the right info for easy configuration:
* Deploying subgraph on specific network
* Updating config for `unlock-app`, `paywall` and `locksmith`.

Past documents for references (outdated!):
* https://github.com/unlock-protocol/unlock/wiki/Releasing-a-new-version-of-the-contracts
* https://github.com/unlock-protocol/unlock/wiki/Releasing-a-new-version-of-the-contracts

**Comment by clemsos** [comment]
relates to #7436

**Comment by clemsos** [comment]
the main tasks are done, but some remains : 

- [ ] deploy subgraph
- [ ] set/configure gnosis safe
- [ ] update config files

**Comment by julien51** [comment]
@clemsos I think we're now all set, can you confirm please?

**Comment by clemsos** [comment]
yes we got all of these, esp the config maybe but thats done through the `networks` package now
