### ISSUE TITLE
website UI broken on mobile

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7591]
**Describe the bug**

![image](https://user-images.githubusercontent.com/743246/135209031-b42d5d38-2075-4a1c-8b07-ff38f04f8540.png)

![image](https://user-images.githubusercontent.com/743246/135209187-cfed1ae0-cba1-4ca8-a729-0e43aca82071.png)

**To Reproduce**

https://unlock-protocol.com

Safari on iPhone 12

**Comment by julien51** [comment]
Oh no! This is so strange. I don't have an iOS device. When I use Safari on my desktop with ther dev tools, it looks fine :/

**Comment by julien51** [comment]
@clemsos Mind checking if it is stil broken? @kalidiagne has pushed a fix! 
If it is fixed, please close! 
Thanks!

**Comment by clemsos** [comment]
Yes! works fine now :)
