### ISSUE TITLE
Logged out of Wallet Error

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#762]
**Description**
I tried to create a lock but was logged out of meta mask. I got an error when submitting the lock. the error message was not conclusive. Also does not follow [correct error message design pattern](https://www.figma.com/file/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-App?node-id=0%3A2).

**To Reproduce**
1. Log out of wallet
2. Attempt to create lock

**Expected behavior**
A more clear message that I'm not logged in to wallet or at least something more descriptive alerting me to an error with the wallet. Best option would be to alert the user before they even create a lock.

**Screenshots**
<img width="1248" alt="screen shot 2018-12-18 at 16 04 34" src="https://user-images.githubusercontent.com/1377389/50185731-b3930080-02e6-11e9-8750-51309947d30c.png">

**Comment by smombartz** [comment]
might be related to #327 and #749

**Comment by julien51** [comment]
I think a version of this is still happening.
We can detect pretty well when the user loads Unlock for the first time but they do not have Metamask unlocked. BUT if the user loads Unlock with metamask unlocked AND THEN logs out of Metamask we do not take the info into account while we should.

Assigning this to Greg once the v0 stuff is done!

**Comment by cellog** [comment]
this is probably going to be fixed by the implementation for #1093
