### ISSUE TITLE
Creator Dashboard Account Menu Labels Missing

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#763]
**Describe the bug**
The labels on the account menu on the creator dashboard are missing
<img width="730" alt="screen shot 2018-12-18 at 17 10 58" src="https://user-images.githubusercontent.com/1377389/50186233-31a3d700-02e8-11e9-8dc1-4aaf112d65e4.png">

**Expected behavior**
Like the menu on the landing page the menu icons should display a label on hover.
<img width="668" alt="screen shot 2018-12-18 at 17 14 18" src="https://user-images.githubusercontent.com/1377389/50186292-6748c000-02e8-11e9-86bc-02192b4c22d0.png">

**Comment by julien51** [comment]
Soooo, given that we are not using them and they're probably not ready for v0, can we just remove them for now?
