### ISSUE TITLE
Move CI from Circle to Github

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7658]
All of our code is open source, so we should be able to leverage Github Actions infrastructure for our CI pipelines!
The goal would be to have complete feature parity: ability to run test for each branch, perform deployments... etc.
We will also only do the switch if we do not see a strong increase in build time!

For this, we're attaching a 500 DAI bounty (paid on xDAI or Polygon network). And please let us know _before_ you start working on it so that we can formally assign it to you!

**Comment by FrederikBolding** [comment]
I came here to say that I was probably gonna take a while on this due to limited time, so you should hand it off to someone else if need be. I see that there is already a PR open, so good work! 💪

**Comment by julien51** [comment]
Thanks @FrederikBolding ! I appreciate it! @clemsos started on this and did most of the lift! We should get there soon!

**Comment by julien51** [comment]
We're almost there! We're now running all tests in Github and circle. Next is going to be too update the dependent scripts for GitHub.
