### ISSUE TITLE
Better packaging for @unlock-protocol/contracts

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7659]
We dont have currently a proper way to build and bundle the lib and just relies on `package.json` to indicate where files are. 

That means our imports path end up containing the `dist` folder, which is rather inelegant.

```js
import '@unlock-protocol/contracts/dist/PublicLock/IPublicLockV9.sol';
```

**Comment by julien51** [comment]
Also I think we export too much stuff in there because the package ends up pretty heavy when it should just be solidity interfaces and abi?

**Comment by clemsos** [comment]
hmmm it seems like ABIs files are really heavy. Sol files are negligeable.

```
du -sh packages/contracts/dist/**/* | sort -h -r

 11M	packages/contracts/dist/abis
6.1M	packages/contracts/dist/abis/Unlock
4.6M	packages/contracts/dist/abis/PublicLock
1.6M	packages/contracts/dist/abis/PublicLock/PublicLockV0.json
1.4M	packages/contracts/dist/abis/Unlock/UnlockV9.json
1.1M	packages/contracts/dist/abis/Unlock/UnlockV8.json
844K	packages/contracts/dist/PublicLock
692K	packages/contracts/dist/abis/Unlock/UnlockV7.json
588K	packages/contracts/dist/abis/Unlock/UnlockV6.json
572K	packages/contracts/dist/abis/Unlock/UnlockV5.json
492K	packages/contracts/dist/Unlock
436K	packages/contracts/dist/abis/Unlock/UnlockV4.json
436K	packages/contracts/dist/abis/Unlock/UnlockV3.json
404K	packages/contracts/dist/abis/PublicLock/PublicLockV9.json
404K	packages/contracts/dist/abis/PublicLock/PublicLockV8.json
396K	packages/contracts/dist/abis/PublicLock/PublicLockV7.json
392K	packages/contracts/dist/abis/PublicLock/PublicLockV6.json
376K	packages/contracts/dist/abis/PublicLock/PublicLockV5.json
340K	packages/contracts/dist/abis/Unlock/UnlockV2.json
320K	packages/contracts/dist/abis/Unlock/UnlockV1.json
304K	packages/contracts/dist/abis/PublicLock/PublicLockV4.json
[etc.]
``` 

After some investigation, we got 1.5 M bytes in latest Unlock  ABI...

```shell
# total bytes
cat packages/contracts/dist/abis/Unlock/UnlockV9.json | wc -c
1498520

# check by json keys 
cat UnlockV9.json | jq -r 'keys | join("\n")' | xargs -I % -n 1 sh -c 'printf %; jq .% UnlockV9.json | wc -c' | sort -k2 -r

legacyAST  418377
ast  418377
metadata   16212
bytecode   15025
deployedBytecode   14987
deployedSourceMap   14920
source   13639
abi   12101
devdoc    1964
userdoc    1578
compiler      77
sourcePath      66
updatedAt      27
sourceMap      26
contractName       9
schemaVersion       8
networks       3
```

Ok so seems like the `AST` and `legacyAST` keys are the ones who weights really on the file. 

It seems like support for `legacyAST` has been removed from solidity a year ago https://github.com/ethereum/solidity/issues/9512 so that could be dropped

**Comment by julien51** [comment]
Yes, we should try to cleanup the `.json` files and only keep the ABI and the strict necessary code to deploy (bytecode), or even maybe put that in different files so that it's easy for 3rd party applications to only load the ABI they need and avoid keeping the bytecode... etc. 
It would be worth looking at how to do tree shaking here?

**Comment by julien51** [comment]
@clemsos I think this can be closed, correct?

**Comment by clemsos** [comment]
We still dont have proper packaging for sol files. This will require to introduce sth like roll up which I am not sure we want to add right now. The packaging is working, just some unwanted "dist" folder in the exported path which seems tolerable

**Comment by julien51** [comment]
Ok then I am closing :)
