### ISSUE TITLE
coinbase wallet support for airdrop 

### ISSUE THREAD

**Issue by monkofthewest** [unlock-protocol/unlock#7734]
hello friends looking to benefit from the airdrop like many others but i use coinbase wallet . doesnt seem to be support for that at the moment. thanks for all your hard work. cheers

**Comment by julien51** [comment]
That's a good idea! I'll work on this this week.

**Comment by julien51** [comment]
Hey! It looks like we will need this upstream PR to be merged. https://github.com/Web3Modal/web3modal/pull/266
Let's say that generally Coinbase has not been the best citizen in the ecosystem and it's hard for a lot of open source devs to spend time adding support to their stuff :(
