### ISSUE TITLE
Reporting for smart contracts coverage

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7739]
Coverage has been added in #7635 but we still lack integration into CI and proper reporting to evaluate what is missing. Per previous discussions, the coverage target for the main contracts (such as publicLock or even UDT) should be close to 100%. 

We are in the process of upgrading UDT and integrate contracts "integration" testing on a mainnet fork (see #7655 ), we could as well add coverage repotring at least for the unit testing part. Could use Coveralls or another similar service

Sidenote: maybe #1781 can be closed?

**Comment by julien51** [comment]
Absolutely! I think we should think about ways to run this integration test suite against a local prod fork. Let's circle back on this in a few weeks!

**Comment by julien51** [comment]
The folks at Akira raised that too...
