### ISSUE TITLE
Unlock Protocol BSC integration

### ISSUE THREAD

**Issue by rwallsg0d3x** [unlock-protocol/unlock#7742]
In order to have a greater adoption of the protocol with a network with the second largest volume of users, I propose the integration of Unlock in BSC.
There we could carry out airdrops without practically commissions and deploy locks at a very cheap price.

**Comment by julien51** [comment]
I'll look into this in the next few days!

**Comment by julien51** [comment]
We made good progress on Thursday but are stuck with a bizarre error on the subgraph. Well keep investigating!

**Comment by julien51** [comment]
We are live! https://unlock-protocol.com/blog/binance-smart-chain

**Comment by julien51** [comment]
@rwallsg0d3x Please spread the word!
