### ISSUE TITLE
Use Uniswap v3 oracles

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7746]
We currently rely on v2 pools to extract Oracle data about the price of tokens when computing the GDP. We also use that same v2 pool oracle when looking at the price of UDT when determining how many tokens need to be granted to the referrer.

Uniswap now has v3, that we could use directly.

This is not a high priority.

**Comment by julien51** [comment]
This will be part of a larger change in Unlock that we hope to ship by year end 2022.

**Comment by hrik2001** [comment]
Hello @julien51! I am an intermediate solidity developer who has just got into the field.
I really like what you guys are working on and I should probably give this issue a try.
I believe I can work on a PR over time that fixes this ticket/issue (based on my understanding so far)
Do let me know if you want me to work on this!

**Comment by clemsos** [comment]
Closed in favor of #9554
