### ISSUE TITLE
ios13 layout issue on website

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#7757]
**Describe the bug**
Layout issue on ios13 visiting the unlock-protocol.com homepage 

**Screenshots**

<img width="358" alt="Screenshot 2021-11-09 at 22 45 51" src="https://user-images.githubusercontent.com/20865711/141010345-79b8723b-1f3f-41b7-8d61-2f8dfe7a6964.png">

**Smartphone (please complete the following information):**
 - Device: iphone8
 - OS: IOS13
 - Browser safari

**Comment by julien51** [comment]
Fixed! Thanks @kalidiagne
