### ISSUE TITLE
pre-commit linting hook does not catch lint errors

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#776]
if code has a linting error, the pre-commit hook is not stopping commit

**Comment by julien51** [comment]
Probably not a p-1 but more of a p-3? (no impact on users...)
Also I am not sure it was ever set up to actually stop a commit?

**Comment by cellog** [comment]
it would be great if it stopped a commit. It's wasted about 30 minutes of my time today so far with linting errors that made it to Travis :)

**Comment by julien51** [comment]
@cellog Any way to quickly reproduce this one?

**Comment by cellog** [comment]
I found this happens 100% of the time by:

1) introduce a linting error
2) git commit -m "something"

**Comment by akeem** [comment]
@cellog do you believe that #1295 helps to resolve this issue?

**Comment by cellog** [comment]
yes

**Comment by akeem** [comment]
closing as resolved
