### ISSUE TITLE
Complete procedure / checklist for contract upgrades

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7763]
To make sure we make or contract upgrade process more solid, we need a complete procedure / checklist that details each step that should be taken (and how).

Here is a first draft

1. make sure current flattened version in `@unlock-protocol/contracts` is correct (or add it)
1. bump version number in contract (in a single PR)
2. make required changes in the contract - with unit testing of the new functions if necessary
3. test storage conflict locally (how exactly - to clarify)
4. add relevant mainnet tests (these should be run on CI at some point)
5. make upgrade on a testnet (rinkeby) and check for possible issues
6. deploy the implementation on mainnet
7. submit the upgrade for approbation (either DAO or multisig)

We are going to need this one solved to release the new Lock upgrade feature as mentioned on #6682

**Comment by julien51** [comment]
@clemsos I think we have all that in the hardhat task now, correct?

**Comment by clemsos** [comment]
Yes we have all the pieces in place now, plus their documentation in smart contracts README file
