### ISSUE TITLE
"Create lock" and actions button not clickable on small resolution

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#7800]
**Describe the bug**
On smaller resolutions actions on the right side are not clickable, this includes also "Create Lock"

**To Reproduce**
1. Go to 'dashboard'
2. Resize the screen under 1100px or less
3. Try to click items on navbar or "Create Lock"
4. Actions are not clickable

**Expected behavior**
Actions have to be cliccable at any resolution

**Screenshots**

https://user-images.githubusercontent.com/20865711/142724289-8f504cb4-3353-4ba3-b3d7-fc00808c74c8.mp4

**Desktop:**
 - OS: Mac OS
 - Browser: Brave

**Comment by julien51** [comment]
Thanks for this @kalidiagne . Indeed this is a known issue for far too long.
We are right now working on a very significant change to how the dashboard works and I hope we can get that fixed as part of this.

**Comment by julien51** [comment]
I think @searchableguy has found a fix?
