### ISSUE TITLE
Simplify contracts manifest workflow

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7819]
So far we are using locally stored JSON files in a `deployments` folder to keep track of deployments. This actually appear to be a duplicate of `.openzeppelin` manifests which also stores contract addresses after deployments.

The only difference is that we store contract *names* in these files, plus abi etc - while contract names does not appear in OZ manifests.

**Comment by clemsos** [comment]
We should be able to remove the logic in the deployments folder entirely now, as the tests only use helpers that will redeploy the contracts and avoid race conditions.

**Comment by julien51** [comment]
Ok, please add that to your plate!

**Comment by julien51** [comment]
Please update the status on that one when you get a minute!

**Comment by clemsos** [comment]
didnt remove the `deployments` folder yet but we dont really use it now so should be quite straightforward to delete
