### ISSUE TITLE
Labels on icons are not aligned, nor using right color

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#783]
**Describe the bug**
The labels on the lock buttons are not aligned not in the right color.
See screenshot:
<img width="235" alt="screenshot 2018-12-19 at 17 03 39" src="https://user-images.githubusercontent.com/17735/50250909-3469ff00-03b0-11e9-9066-3f60923ca5b9.png">

**Comment by smombartz** [comment]
this is also the case for the top level menu
<img width="229" alt="screen shot 2018-12-20 at 17 29 56" src="https://user-images.githubusercontent.com/1377389/50298493-904f8900-047f-11e9-9da8-b382672dbedb.png">

**Comment by julien51** [comment]
Re-assignig to @cellog for now...

**Comment by smombartz** [comment]
specs can be found here: https://www.figma.com/file/fTMYnZ5z0kT4lcSCDymkHT/Unlock-Landing-Page?node-id=0%3A861
