### ISSUE TITLE
Smart contracts doc

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7907]
This hard hat zero conf plug-in for contract doc seems interesting. Could be useful to document doc properly 

https://github.com/primitivefinance/primitive-dodoc

**Comment by julien51** [comment]
Very interesting, yes! It would be cool to see if we can easily integrate in our https://github.com/unlock-protocol/docs repo!

**Comment by clemsos** [comment]
yes that will be much easier to have technical doc directly into the contract. Will see how that can work

**Comment by clemsos** [comment]
should generate from contracts package directly so we keep versioning

**Comment by clemsos** [comment]
updates on this after merging #8807

A `docs` was added to the `@unlock-protocol/contracts` package that generates md docs from docstring for all Unlock and PublicLock versions.

The docs will be released directly on npm in the `docs` folder of the contracts package

Also added a script to create a pull request in the docs repo with latest changes   

```
sh scripts/docs-contract-pr.sh
```

Here is a PR example with all the docs https://github.com/unlock-protocol/docs/pull/31

Now we need a workflow on the docs side to see how this gets plug into
