### ISSUE TITLE
Adding `__gap` before upgradable locks

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#7919]
Since we're moving forward with upgradable locks, we need to make our mixins "future proof". OpenZeppelin uses `__gap` variables at the end of each contract so that we can add/change storage inside of the mixins without completely changing the structure of these contracts when we want to upgrade them.

All mixins used in `PublicLock` should have a `__gap` method of say 1,000 uint256 slots.

See details on https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0d40f705a7d4a42ff622ae3a0e1a90305fc5b93e/docs/modules/ROOT/pages/upgradeable.adoc#storage-gaps

**Comment by julien51** [comment]
Example there: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC721/ERC721Upgradeable.sol#L431

Let's use a pretty large gap like `1000`. It does not cost us anything but allows for a lot more flexibility.

**Comment by clemsos** [comment]
Yes makes sense. 

Also we may need to use another variable name as we may run into conflicts when importing OZ __gap which has a different size. The upgrades plugin will throw when comparing names - consider it a renaming. 

Maybe __unlock_gap or ____gap?
