### ISSUE TITLE
SmartBCH EVM/MetaMask-compatible BCH-sidechain support

### ISSUE THREAD

**Issue by jQrgen** [unlock-protocol/unlock#7924]
I humbly request SmartBCH EVM/MetaMask-compatible BCH-sidechain support.

Read more here: https://smartbch.org & https://helpme.cash

**Comment by julien51** [comment]
Thanks @jQrgen ! It is the first time I hear from that chain. Do you know creators who would be interested in deploying their locks there?

**Comment by jQrgen** [comment]
Yes. I am a part of an NFT collective with several interested artists.

**Comment by julien51** [comment]
Ok I'll look into this. It let take a few weeks given it roadmap at this point.
Let me know if you'd like to help. I can show you how to deploy there...

**Comment by jQrgen** [comment]
I can help. How?

**Comment by kemperboyd911** [comment]
how could one deploy on IOTA EVM? is it easily done? or...

**Comment by julien51** [comment]
@kemperboyd911 @jQrgen Are you still interested in this? We have improved our deployment process to make things easier so we can add more EVM chains easily. Please let us know. cc @clemsos
