### ISSUE TITLE
Remove $ balance of account

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#793]
**Describe the bug**
We currently show the USD balance on each account. I believe this is not useful (and was not part of @smombartz 's original design). All wallets will actually show that information more accurately than us and it is probably one of the key features... while not very useful for us!

Let's remove it!

<img width="1293" alt="screenshot 2018-12-19 at 22 04 08" src="https://user-images.githubusercontent.com/17735/50261518-e0c0db00-03da-11e9-9e16-69d2910c6783.png">

**Comment by cellog** [comment]
I'll eat my own dog food on this one :)

**Comment by julien51** [comment]
🐶
