### ISSUE TITLE
Remove "Earnings" from Dashboard

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#794]
**Is your feature request related to a problem? Please describe.**
The dashboard shows an "Earnings" value, which should be the sum of all earnings accross all locks.
We currently do not extract that information and I am not sure it is that useful (but would do for a nice vanity metric!)

We should consider removing it for now (or implementing it) but it may not be trivial because it will involve looking at all transactions happening on a given lock since it was created... which will likely take a little time once the lock has sold 100s of keys.

<img width="1269" alt="screenshot 2018-12-19 at 22 05 25" src="https://user-images.githubusercontent.com/17735/50261597-43b27200-03db-11e9-9672-ae0d5c558c5a.png">

**Comment by cellog** [comment]
fixed by #817
