### ISSUE TITLE
Menu for wiki pages are in random order

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#799]
Currently, the wiki's menu on the right side has a totally different order from the nice, well-ordered list on the front page of the wiki itself

**Comment by julien51** [comment]
Unfortunately, I am not sure we control that at all? This is GitHub's stuff? Right @benwerd ?

**Comment by benwerd** [comment]
Actually you can add a custom sidebar, which will auto-minimize the default one. I've just started work on doing that.
