### ISSUE TITLE
rename SuspendedError to SuspendedRender

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#805]
**Is your feature request related to a problem? Please describe.**
The original conception of SuspendedError was to suspend rendering for 200ms and then display an error if necessary, but it is now also being used to suspend rendering before displaying a lock, so the name is at best confusing.

**Describe the solution you'd like**
rename all occurrences in the source code to SuspendedRender

**Comment by julien51** [comment]
Closing! Thanks @vikaskyadav
