### ISSUE TITLE
Upgrade contracts package via CI

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8055]
It will be useful to recompile / upgrade the contracts package each time there is any change in contracts, so we make sure that it is up to date - also that we don't break Unlock js and others dependencies.

**Comment by julien51** [comment]
Oh yes! automate all the things!
(after release of the new contracts!)

**Comment by clemsos** [comment]
we could also rebuild the contract docs when a new version of the package is published https://github.com/unlock-protocol/unlock/pull/8807

**Comment by clemsos** [comment]
duplicate of #6091

**Comment by clemsos** [comment]
hey @searchableguy will the package will be released automatically via ci if we bump the version?

**Comment by searchableguy** [comment]
@clemsos yes and without version bump too if the content has changed, since we bump through yarn version:apply.

**Comment by clemsos** [comment]
so I think we can safely close this
