### ISSUE TITLE
Branding on Mobile Dashboard Missing

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#806]
**Describe the bug**
The Unlock Logo is missing on the mobile version of the Dashboard.

**Expected behavior**
Should look like so: https://www.figma.com/proto/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-App?node-id=0%3A269&viewport=-929%2C1471%2C0.662482&scaling=min-zoom

**Screenshots**
<img width="354" alt="screen shot 2018-12-20 at 17 42 54" src="https://user-images.githubusercontent.com/1377389/50298555-b6752900-047f-11e9-9901-51031684f23b.png">

**Specs**
Chrome Desktop Mobile View and iOS, iPhoneX

**Comment by benwerd** [comment]
Oops, I let this languish. @cnasc lmk if you've started on this, but I'm going to assume you haven't and will grab it.
