### ISSUE TITLE
Mobile Menu Behaviour Push instead of Overlay

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#807]
**Describe the bug**
When the menu is opened on mobile view it lays over the content directly below instead of pushing it down.

**Expected behavior**
The expanded menu should push the existing content down and show both menu and content at the same time. See [mockup](https://www.figma.com/proto/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-App?node-id=0%3A369&viewport=-929%2C1471%2C0.662482&scaling=min-zoom).

**Screenshots**
<img width="703" alt="screen shot 2018-12-20 at 17 59 03" src="https://user-images.githubusercontent.com/1377389/50299117-0e605f80-0481-11e9-93c5-c592bf701af6.png">

<img width="375" alt="screen shot 2018-12-20 at 18 02 10" src="https://user-images.githubusercontent.com/1377389/50299237-6ac37f00-0481-11e9-93e0-9d9ce677104a.png">

**Comment by cellog** [comment]
fixed by #934
