### ISSUE TITLE
Show a skeleton UI when waiting for dashboard to load

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8075]
**Is your feature request related to a problem? Please describe.**

Currently, when a user goes to dashboard again (after connecting their wallet previously), they are shown only a loading icon with prompt to reconfirm their wallet. See below for screenshot.

![image](https://user-images.githubusercontent.com/73341821/150817320-c22dba2d-0322-48ba-8e31-4701f44032ad.png)

This is confusing for the user.

**Describe the solution you'd like**

We should show a skeleton UI while waiting for user to confirm their wallet. There should be more information on what is happening on the screen.

**Comment by julien51** [comment]
Love that!

**Comment by aindrajaya** [comment]
Hi, If this issue is still open and needed. Could you assign this issue to me? I will take this one.

**Comment by searchableguy** [comment]
@aindrajaya thanks for the offer but right now, we are in the process of overhauling the dashboard. We would tackle this there because of the changes required.

**Comment by aindrajaya** [comment]
@searchableguy Oh okay, Thank you for the information.

**Comment by julien51** [comment]
@ChialiTsai @kalidiagne This should be part of the dashboard refactor :)

**Comment by julien51** [comment]
We have that on the new dashboard! Yay!
