### ISSUE TITLE
Multiple purchase

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8100]
Our locks currently only support purchasing one key at a time. 
We need to add support for the ability to purchase multiple keys at a time. We should still have the same mechanism where the buyer is the payer but of course they could/should set multiple recipient addresses.

The base use case is for conferences like EthCC who want to be able to offer the ability to people to purchase multiple keys at once for multiple attendees (like someone in the company buys keys for all of their team members).

**Comment by clemsos** [comment]
won't it be better to have a `purchaseMultiple` function ? Or we generalize `purchase` to accept multiples, but we keep a `purchaseOne` ?
