### ISSUE TITLE
Upgrade node version across all our services

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8176]
**Describe the bug**

We are actually using node v12 for many of our services. It is defined in the alpine docker image at root.

This is going to be completely unsupported in 2 months.

https://endoflife.date/nodejs

**Solution**

Upgrade the node version to latest LTS such as v16 and make sure nothing breaks.

There are some pollyfills we can get rid of such as AbortController in the process as well.

**Comment by RishiKumarRay** [comment]
Assign me, I would like do this

**Comment by julien51** [comment]
@RishiKumarRay Thanks! Feel free to fork and open a PR :)

**Comment by julien51** [comment]
@searchableguy Good catch! Do you think it could be safer/easier to do incremental changes by moving to 14 first?

**Comment by searchableguy** [comment]
I think that would be redundant. It would be as safe to just migrate to v16 (LTS).

**Comment by searchableguy** [comment]
https://github.com/unlock-protocol/unlock/pull/8215 require fixing old tests which I'm not familiar with so I'm reassigning this.
