### ISSUE TITLE
Cross Posting blog

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8192]
We should cross post our blog's RSS to the following:
* Medium
* Reddit
* Discourse
* Discord (we used to have it but it looks like it's not working anymore?)
* Telegram

**Comment by ccarfi** [comment]
discourse, telegram, and medium: done
discord happens when posts are posted on twitter, automatically cross-posts to discord.
going to defer reddit for now. need to figure out broader reddit approach before setting up automated posts to that community.
