### ISSUE TITLE
New design housekeeping

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8217]
Here is a list of things to keep track of for the new design:

* [x] Favicon update
* [x] SEO 
* [x] UTM Tagging 

Other tools to run website against:
* [x] lighthouse (accessibility, load times, mobile): add to CI on `master` builds so we can measure rather than block.

**Comment by searchableguy** [comment]
Can you elaborate on UTM tagging?

It should work on the current site.

**Comment by searchableguy** [comment]
As for the lighthouse.

1. I'm not sure increased time and complexity would be worth it for the main site which will be fairly contained. 

2. If we do add lighthouse, I think we should run it only in the PR affecting the site than master. This allows the person to make changes to improve the score before merging the changes. Simply showing the report on master means we will ignore it or there is resistance to making another PR for fixing trivial regressions. 

It will be non-blocker.

**Comment by julien51** [comment]
Agreed, let's not do lighthouse for now.
Do you have access to Google analytics? Can you make sure that the traffic measures are "consistent" with the old website?
Thanks!

**Comment by searchableguy** [comment]
I don't have access to the google analytics. 

@julien51

**Comment by julien51** [comment]
Done :D
