### ISSUE TITLE
"burn" key

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8230]
Right now, we have a way to expire keys either by their owners as a cancellation measure, or by the lock manager, as a way to remove someone from the set of people who have access.
It would be interesting to explore the idea of _deleting_ a key once its expired. This would reset the fields but also reduce the number of keys in the supply to make it available for another purchaser.

**Comment by clemsos** [comment]
Note that we have a `ownsOrHasOwnedKey` modifier that will need to be removed after that. Also we have a logic in `_recordOwner` to prevent looping in the `owners` array that will need to change too.
