### ISSUE TITLE
Signing CLA

### ISSUE THREAD

**Issue by pscott** [unlock-protocol/unlock#8242]
Opening an issue as recommended by the bot [here](https://github.com/unlock-protocol/unlock/pull/8240#issuecomment-1041988296) :)

**Comment by pscott** [comment]
Maybe I just need to add my name to the [.clabot](https://github.com/unlock-protocol/unlock/blob/master/.clabot) file but I'm not sure so prefer opening an issue :D

**Comment by julien51** [comment]
Ho Hey! fixed it https://github.com/unlock-protocol/unlock/pull/8244 :)
