### ISSUE TITLE
suggestion: change to PR template

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#832]
The template should probably explain that *any* modification to configuration or package.json should be in its own PR. This is because it is not intuitively obvious to those who have not been burned by difficulty reverting PRs that config changes should be separate, even ones that are tightly integrated with the PR.

**Comment by julien51** [comment]
Isn't that covered by the "1 PR, 1 PuRpose" rule?

**Comment by benwerd** [comment]
Theoretically yes, but I agree with @cellog that it's probably not explictly obvious.

**Comment by cellog** [comment]
I suggest adding this line to the end:

```
- [ ] this PR does not introduce any configuration/package.json changes, or is ONLY configuration changes
```

I experimented with this in the PR I just submitted, #841

**Comment by julien51** [comment]
Works for me. Please submit a PR with the new template.

**Comment by cellog** [comment]
(reopening so I can find it when I do PR)
