### ISSUE TITLE
Use Unlock hardhat-plugin in tests

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8336]
We now have a [hardhat plugin for Unlock] that could be used to run tests in different part of the repo such as `unlock-js`, `smart-contracts` and even `smart-contract-extensions`. 

This will prevent having duplicated code and logic for similar task and also offer a good opportunity to improve the hardhat plugin workflow

**Comment by julien51** [comment]
@clemsos Any update on this?

**Comment by clemsos** [comment]
Yes, we should be using this in the coming integration test suite first. Then we see if we really need it else where

**Comment by julien51** [comment]
Well I think the integration test suite will likely not use the hardhat plugin? It will test the behavior of our front-end applications...
