### ISSUE TITLE
Adding the ability to skip metadata collection when all fields are optional

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8361]
In a checkout flow [like this one](https://app.unlock-protocol.com/checkout?redirectUri=https://blackpool.finance/events/nft-barcelona3-28-2022?booked=true&paywallConfig={%22pessimistic%22:true,%22locks%22:{%220x89e975EA43E0Cfe338205e016BFFaeFeFdbc3511%22:{%22network%22:137,%22name%22:%22NFT%20Barcelona%22}},%22icon%22:%22https://blackpool.finance/favicon.ico%22,%22callToAction%22:{%22default%22:%22The%20traditional%20BlackPool%20NFT%20Auction,%20to%20take%20place%20in%20the%20incredible%20Valkiria%20Hub%20in%20Barcelona.%20RSVP%20below!%20If%20you%20show%20up%20to%20the%20event,%20your%20ticket%20enables%20you%20to%20participate%20in%20a%20raffle%20for%20a%20physical%20airdrop%20at%20the%20bar!%22},%22metadataInputs%22:[{%22name%22:%22email%22,%22type%22:%22email%22,%22required%22:false,%22public%22:false}]}), we want to allow the user to "skip" the metadata collection phase as all fields are optional.

The "Skip" button should _only_ be visible if all fields are optional. Alternatively it could just be a small text button below the "Save and Continue" button.

**Comment by kalidiagne** [comment]
@julien51 In the case some fields are required, what will be the action that "skip" will have? 
In the current PR opened I covered only the first case

**Comment by kalidiagne** [comment]
Resolved with https://github.com/unlock-protocol/unlock/pull/8369
