### ISSUE TITLE
"Check your wallet"

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8388]
In multiple places in our application, we ask the user to check their wallet to "connect", sign a message or even send a transaction.
We need to surface this, much better in our application (there is actually no indication about it right now).

On the dashboard, we could add a message in one of the corners of the application, in the (current) checkout, it would be worth adding a intermediate screen when that is the case.... etc.

**Comment by searchableguy** [comment]
I added check your wallet notification in the required confusing areas. Any further notifications should be tackled in the redesign.
