### ISSUE TITLE
Missing data on querying subgraph

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8427]
**Describe the bug**

When you try to grab the totalSupply  and maxNumberOfKeys, you will get 0 and null respectively. 

This is on Rinkeby and the Unlock Rinkeby Subgraph here — https://thegraph.com/hosted-service/subgraph/unlock-protocol/unlock-rinkeby?selected=playground

**To Reproduce**
1. Go to unlock subgraph on thegraph explorer
2. Run below query

```graphql
{
  locks(where : {address: "0xDea369C7Dd7CaC10267516C3CAc47a41B610D41E"}){
    id,
    name,
    price,
    expirationDuration,
    totalSupply,
    maxNumberOfKeys,
    keys(where:{owner:"0xbe14c2f410ec78b64cbd54f72081533cb392a3d1"}){
      id,
      keyId
    },
    owner,
    version
  }
}
```
3. Check for totalSupply and maxNumberOfKeys. Those will be 0 and null.

**Expected behavior**
Proper values for totalSupply and maxNumberOfKeys

I'm not sure if this happens on other subgraph as well. We should confirm it.

**Comment by cgigl** [comment]
Adding a few more details: 
- The issue does appear to be on mainnet as well. 
- `totalSupply` looks like it always equals `0`. This query returns empty:
```
{
  locks(where :{totalSupply_gt : 0}){
    id,
    name,
    totalSupply,
    maxNumberOfKeys,
    version
  }
}
```
- `maxNumberOfKeys : null` for lock contracts version 7 and greater. This query also returns empty:
```
{
  locks(where :{maxNumberOfKeys_not : null, version_gt : 6}){
    id,
    name,
    totalSupply,
    maxNumberOfKeys,
    version
  }
}
```

**Comment by cgigl** [comment]
I can't say this with any degree of certainty as I have no idea how the subgraph is deployed, but the `maxNumberOfKeys` issue may be a simple fix. Looking at [lockProcessing.ts](https://github.com/unlock-protocol/unlock/blob/master/subgraph/src/lockProcessing.ts), the `processv7` function appears to be missing [this line](https://github.com/unlock-protocol/unlock/blob/361fe8c123e01ca9e92422d7e3a2c1203f6dd61d/subgraph/src/lockProcessing.ts#L73) from `processPreV7`:
```
lock.maxNumberOfKeys = chainPublicLock.maxNumberOfKeys()
```
so `maxNumberOfKeys` is never set. If that's the case, would make sense why it's returning `null`

**Comment by cgigl** [comment]
Awesome, thanks @julien51 ! I noticed this the other day and it's in our queue to use the updated version. I'll let you know if we run into issues. Sincerely appreciate it.

**Comment by julien51** [comment]
Closing as I believe we now have the missing fields!
