### ISSUE TITLE
Reset approvals on key transfers

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8448]
During the audits we noticed that we are not properly resetting the `approvals` for that key.
Let's fix this (note: the key manager should remain unchanged) but all previous approvals should be reset.

**Comment by clemsos** [comment]
one thing that is unclear is that the approvals are set for an address so if you cancel approvals when you transfer or cancel a key, then this may affects other keys by the same user. This is an issue esp for recurring memberships #6736 as when you end/cancel the memberships, this could revoke approvals for other memberships owned by the same address

**Comment by clemsos** [comment]
@julien51 does that solve it ?
