### ISSUE TITLE
Add gas refund to `extend` and `renewMembershipFor`

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8451]
Currently gas refund is only available when purchasing

**Comment by julien51** [comment]
Oh yes we need to add it for these 2 other functions (and assume for now that the actual gas spent is kind of the same?) How hard would it be to base the refund on the _actual_ gas spent until the actual refund part?

**Comment by clemsos** [comment]
> Oh yes we need to add it for these 2 other functions (and assume for now that the actual gas spent is kind of the same?) How hard would it be to base the refund on the _actual_ gas spent until the actual refund part?

Not sure it is good to have multiple mechanisms for gas refund in the contract. We created the `setGasRefund` for purchasing so we should keep using it elsewhere. Adding different mechanisms will make things more complicated for the user, also will increase code size even more
