### ISSUE TITLE
Fix eslint-plugin-react settings

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#852]
When running linting locally we get the following warning:
> Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.

My understanding is that specifying a value will allow for tighter linting rules. We should do that!

**Comment by cellog** [comment]
fixed by https://github.com/unlock-protocol/unlock/commit/93e9f2ec0ee97c22c284d559439206f0c3ba79a6
