### ISSUE TITLE
Deploy to netlify from Travis

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#855]
We currently deploy to netlify from github's master.
The "build" process happens on netlify's end, which means we're limited in what we can do there. For example we cannot compile the smart contracts `.sol` files in there (because there is no pre-installed) libraries to do that. 
We are able to build and compile the whole project on travis and we should deploy from there, rather than from Github. This would be more robust and remove some coupling. (including adding the .json artifacts to .gitignore! #363)

**Comment by nfurfaro** [comment]
I'm strongly in favor of doing all our smart-contract compilation in Travis as well, as long as we're able to use the newly compiled artifacts (which I think this would let us do?)

**Comment by julien51** [comment]
Yes! I think this is probably doable. I'll do some research but I am hopeful!

**Comment by julien51** [comment]
This is done! Closing
