### ISSUE TITLE
Add authentication to locksmith based on sign in ethereum EIP 4361

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8550]
**Describe the bug**
We don't have a good authentication system that can cover all the API endpoints without constant signature verification. Many uses typed data signature which hasn't been as widely adopted by wallets as predicted initially. 

**Solution** 
Implement a session-based authentication system using sign-in with Ethereum based on the [EIP 4361](https://eips.ethereum.org/EIPS/eip-4361).

**Proposal for implementation**

1. Create a `/login` endpoint on the locksmith
   - Any client who wants to authenticate will send a POST request with message based on [EIP standard message](https://eips.ethereum.org/EIPS/eip-4361#example-message-to-be-signed) for authorization with a unique nonce. 
   - On receiving the signed message locksmith will check if the nonce was used before and if it was, it will return an error. If successful,  It will expire the nonce so it cannot be used again for establishing a secure session.
   - After successful validation, the locksmith will attach an encrypted HTTP-only cookie with an expiry date to the response. 
 
 2. Any further request to the locksmith will include this cookie. 
    - Protected endpoint will use the authentication middleware which will attach an unencrypted session to the request and can be used to access the user.
    - Controller can access the user through the request object inside the code and can further validate or restrict the use. For example, in the case of modifying data for a key. Controllers should check if the wallet in the session matches the one associated with key data. 

To not break the compatibility with existing endpoints, I will be using `/v2` and files such as `key_v2.tsx` for routes until we deprecate the older APIs. 

Any questions and suggestions will be useful.

**Comment by searchableguy** [comment]
An example of how an application would authenticate and use this.

```ts

const response = await fetch("https://locksmith.unlock-protocol.com/api/v2/login")
// handle status code other than 200 here ...

// We get the text message
const message = await response.text()

// Sign it using a wallet utility
const signature = await wallet.requestSign(message) 

// Make post request with the signature and body
const loginResponse = await fetch("https://locksmith.unlock-protocol.com/api/v2/login", {
  method: "POST",
  body: signature
})

// If successful, an encrypted http-only session cookie will be attached so any further request to locksmith endpoint will have it and require no change from user.
```

**Comment by julien51** [comment]
Looks good to me!
