### ISSUE TITLE
The staging deploy is not triggered when `run-all-tests` tag is used on CI 

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8562]
**Describe the bug**

Currently we use a `run-all-tests` tag to launch the entire test suite. However this will not trigger the entire staging deploy workflow.

see https://github.com/unlock-protocol/unlock/actions/runs/2088954946

**To Reproduce**
1. Tag a PR with `run-all-tests`

**Expected behavior**
Should run the entire deploy steps

**Comment by julien51** [comment]
The new approach is to use `/run-all-tests` in comments :) (similar to `/rebase`)
