### ISSUE TITLE
unlock-js testing should have a way to test only a single version

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8580]
**Is your feature request related to a problem? Please describe.**

We have integration tests for unlock js for all Unlock > PublicLock pairs, which is good. Now we need a way to simply test the latest version of a lock because development becomes slow and painful by running the entire suite - which leads to basically having less tests, less reliable. 

**Describe the solution you'd like**
A way to (uint) test functions in a single version of a lock

**Comment by julien51** [comment]
I wonder if there would be a way to pass what version to tests as params. I used to comment out the versions I needed to tests. 
Something like this:

```
yarn run test src/__tests__/integration/walletServiceIntegration.test.js --unlock-version 10 --public-lock-version 9 
```

We could also pass some params to skip deploying unlock for example... etc like that:

```
yarn run test src/__tests__/integration/walletServiceIntegration.test.js --unlock 0x12314... 
```

I think what we want to avoid is creating multiple different test suites for each version...

**Comment by clemsos** [comment]
> I think what we want to avoid is creating multiple different test suites for each version...

Instead of splitting by versions, we could split by functions that contains the different by version into their own files - with all the  `if(version === ...)` we currently have. We will simply pass unlock and lock instance to the call.

That will allow to have a simple test runner for a single function we can use locally, and a single integration file where we make sure all lock/unlock versions are tested against each other (like we have now)

**Comment by clemsos** [comment]
also maybe we should move away from jest here and use mocha which is more native to hardhat. The current way to run jest tests with hardhat is kind of a hack

**Comment by searchableguy** [comment]
I wonder if https://github.com/foundry-rs/foundry would be a good candidate as well if you are thinking of moving from jest. 

It will speed up the tests and allow us to write tests directly in solidity.
