### ISSUE TITLE
Deprecate old Unlock community locks (both xDAI and mainnet)

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8599]
We need to replace them with a more recent version of the PublicLock contract and add Chris and others as managers.

**Comment by ccarfi** [comment]
<img width="1310" alt="Screen Shot 2022-04-11 at 2 55 43 PM" src="https://user-images.githubusercontent.com/214760/162845372-3752e09a-556d-4f6a-aa4b-bfa231abd827.png">

<img width="1331" alt="Screen Shot 2022-04-11 at 3 45 17 PM" src="https://user-images.githubusercontent.com/214760/162845494-d939da96-8747-498c-b26a-0b8008a49459.png">

```0xCE62D71c768aeD7EA034c72a1bc4CF58830D9894```
