### ISSUE TITLE
Improve performance of the website

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8643]
**Is your feature request related to a problem? Please describe.**
Our website is slow because of unoptimized images and javascript loading. 

**Describe the solution you'd like**
Replace image tags with next-image in main pages, blog generation, etc. Use svg or css instead of pngs for background double U, optimize the loading of javascript in key places through the lazy load. 

**Additional context**
You will need to use a local image optimization strategy for the next image because we host on netlify so there isn't an out of box on-demand image optimization. All images will be generated at build time as a result which may increase the CI time.

**Comment by julien51** [comment]
That's a great idea!
