### ISSUE TITLE
Duplicated lock in list during minting

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#8648]
**Describe the bug**
When a lock is created, during minting a duplicated lock is shown. 

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'Create lock' and create a lock
3. Watch the locks list during minting

**Screenshots/video**

<img width="300" alt="Screenshot 2022-04-25 at 18 31 03" src="https://user-images.githubusercontent.com/20865711/165133527-b2bb3fdf-e415-4568-ba5d-ec9b7ede5874.png">

https://user-images.githubusercontent.com/20865711/165133678-c2fbd750-2a08-4646-a5bd-ef1b5136c466.mov

**Comment by julien51** [comment]
Oh, interesting @kalidiagne . Do you think you could try to debug/fix this?

**Comment by julien51** [comment]
This is now fixed!
