### ISSUE TITLE
onGrantKey Hook

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8658]
Let's add a hook for when keys are granted on order to match the behavior of the hook `onPurchase`.
Maybe it is worth using the same hook (and rename it to `onKeyCreation`) as long as we have an easy way to identify if it is a grant or a purchase.

**Comment by clemsos** [comment]
ouch got a "contract size too big" by just adding a call... 

```
Warning: Contract code size is 24704 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> contracts/PublicLock.sol:26:1:
   |
26 | contract PublicLock is
   | ^ (Relevant source part starts here and spans across multiple lines).
```
