### ISSUE TITLE
storybook broken in master

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#867]
**Describe the bug**
Not sure why, but https://github.com/unlock-protocol/unlock/commit/a2c500ade5c2dda18052a323a38f3588c038bc7e broke storybook.

**To Reproduce**

`npm run storybook`

**Expected behavior**
<img width="1680" alt="screen shot 2018-12-30 at 10 17 51 pm" src="https://user-images.githubusercontent.com/98250/50554023-04104380-0c81-11e9-9f67-5c2daf4ade5b.png">

**Screenshots**
<img width="1680" alt="screen shot 2018-12-30 at 10 18 49 pm" src="https://user-images.githubusercontent.com/98250/50554029-10949c00-0c81-11e9-955e-1464c6c58da4.png">

**Comment by julien51** [comment]
Dang. I can revert this but I am more worried that the tests passed. I thought we had snapshot-ting enabled for the stories?

**Comment by cellog** [comment]
The tests pass, the error is in storybook's interaction with itself. So storyshot successfully makes the stories, it is a subtle configuration change in storybook.

Perhaps there is a use of config in the storybook.config.js that we didn't see?

Not sure what the procedure is on a revert, do you revert then resubmit with the thing fixed? Or just submit a new commit with the fix?  Because in this case it doesn't affect CI, just screenshots for new PRs

**Comment by julien51** [comment]
Closing as this was fixed!
