### ISSUE TITLE
Balances does not account for cancelled and expired keys in the same way

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8692]
**Describe the bug**
Currently, when a key is cancelled we internally call `cancelKey` which triggers `_deleteOwnershipRecord`, which will remove ownership data and decrease the user balance. 

As a result, after a key has been cancelled, calling `balanceOf` for the owner address will return a null value (even though a cancelled key exists). When a key expires, no specific event is triggered, therefore leaving an expired key in the user balance.

Therefore, the results of `balanceOf` can be considered inconsistent.

**To Reproduce**

1. Buy a key
2. Cancel it
3. call `balanceOf`

**Expected behavior**

`balanceOf` should return the total number of keys, expired or not.

**Comment by julien51** [comment]
Let's make sure that explicit cancellation (by lock owner, key manager or key owner) behaves the same as "natural" expiration.

**Comment by julien51** [comment]
The only difference is that we *must* reset the `_originalPrices` in case of explicit expiration/cancellation?

**Comment by clemsos** [comment]
solved by https://github.com/unlock-protocol/unlock/issues/8693
