### ISSUE TITLE
Visual diffing for storybook changes

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#870]
**Is your feature request related to a problem? Please describe.**
Recently, we had a PR that broke storybook, and we didn't catch it. If we were doing visual diffing of storybook run screenshots, this would be caught. In addition, when changes are made to visual display of a storybook component, this would provide a visual diff as well as the snapshot diff.

**Describe the solution you'd like**
The most promising solution I found is called loki:

https://loki.js.org/

The setup works best with chrome in docker, and requires graphicsmagick. Fortunately:

https://hub.docker.com/r/jcsousa/nodejs-alpine-graphicsmagick/

I think we can make a docker image based on this image that will merge with chrome docker and run our storybooks, then we can make this a commit hook like test failures.

**Describe alternatives you've considered**
I considered using some kind of PR web hook, but there is no existing service and so we would have to make one and ... no.

**Additional context**
This is early stage. comments from @julien51 @benwerd @akeem @smombartz ?

**Comment by cellog** [comment]
That makes sense. I think this tool is great, and we should consider it. For this issue, which is just verifying that storybook is actually working, maybe I am thinking too large.

Perhaps we can add 1 new unit test that runs our storybook in a sandbox, gets the html of the first page and creates a snapshot we can compare? This would verify it works

**Comment by julien51** [comment]
I think you're right. I am still not fully sure I understand how the snapshot could be compared if storybook did not run?

**Comment by cellog** [comment]
Could we leverage the integration test infrastructure to run storybook, and grab the html from puppeteer?

**Comment by cellog** [comment]
OK, Here is the setup I think we should explore: https://medium.com/bleeding-edge/screenshot-testing-with-react-and-storybook-19ab7e49ec92

storybook-chrome-screenshot and reg-suit together will give us a way to create screenshots and see the differences with a pixel diff

**Comment by julien51** [comment]
See https://github.com/unlock-protocol/unlock/issues/821 for options of tools.

**Comment by cellog** [comment]
implemented with chromatic
