### ISSUE TITLE
Something is wrong with our telegram button

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#877]
When hovering in the top bar the telegram button does not behave like the other ones. I suspect is it placed too gar on the right as well.

![telegram](https://user-images.githubusercontent.com/17735/50599034-bc550c00-0e7a-11e9-9eb5-91b15d8b7d58.gif)

**Comment by julien51** [comment]
Unfortunately this is not currently solved. Re-opening.
The problem is still with the alignment of the icons as seen on the following screen capture:

<img width="1280" alt="screenshot 2019-01-12 at 22 15 25" src="https://user-images.githubusercontent.com/17735/51081176-c2878b80-16b7-11e9-98e8-5e2e670e6ee0.png">

**Comment by smombartz** [comment]
@julien51 thinks this issue is also causing the below bug where the header is cut off on opera (51.0.2830.40)

![image](https://user-images.githubusercontent.com/1377389/51278757-72574480-19a9-11e9-8c34-848861a16eb4.png)
