### ISSUE TITLE
explore implementing EIP-2981 for royalty signaling

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#8773]
**Describe the solution you'd like**
As a creator, I'd like to be able to specify a royalty request to marketplaces when a key is resold on one of those marketplaces.

**Additional context**
This is a common request in the Unlock Discord.

The specification is here:
https://eips.ethereum.org/EIPS/eip-2981

A potential implementation hint:
https://www.reddit.com/r/opensea/comments/pvgc91/can_anyone_confirm_if_opensea_supports_eip_2981/htfqo1o/

The above Reddit post links to this repo (NOTE: NOT REVIEWED FOR SECURITY OR COMPLETENESS) 
https://github.com/dievardump/EIP2981-implementation

**Comment by ccarfi** [comment]
For the backlog and for consideration.

**Comment by julien51** [comment]
Thanks @ccarfi We'll explore with @clemsos !

**Comment by refex** [comment]
Hi @ccarfi, i agree that it would be a nice addition for our use of Unlock too (we are developing a ticketing platform). Adding some info here:

openzeppelin already has a ERC721Royalty extension based on EIP-2981 https://docs.openzeppelin.com/contracts/4.x/api/token/erc721#ERC721Royalty

**Comment by ccarfi** [comment]
manifoldxyz and coinbase NFT thread wrth reading
https://twitter.com/manifoldxyz/status/1516841481398595584?s=20&t=oy1EjsOgE2cjO0zNd759gA

**Comment by clemsos** [comment]
Yep also seems like opensea does not support it so far (my thread is a bit old tho)

https://twitter.com/clemsos/status/1479580570841669634?s=21&t=r3Qp5kUQX9_Z1hzDhcJjMA

**Comment by clemsos** [comment]
tutorial using https://royaltyregistry.xyz/configure

**Comment by julien51** [comment]
Adding @wonderwomancode and @ccarfi Because I think this is a great "tutorial" for the guides!
