### ISSUE TITLE
Checkout fails silently when gas fees too high to claim

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#8775]
**Describe the bug**
Checkout infinitely spins if things fail on the backend due to gas fees with no feedback to user

**To Reproduce**
Try to claim a key on Polygon when gas fees are high

**Expected behavior**
Some feedback to user if transaction fails, instead of hanging

**Screenshots**
Here's what I see as a user
<img width="419" alt="Screen Shot 2022-05-07 at 7 51 31 AM" src="https://user-images.githubusercontent.com/214760/167259656-3d358784-4ae5-4722-9d7c-241e569161d5.png">

Here's what we saw on the logs
<img width="491" alt="Screen Shot 2022-05-07 at 7 51 50 AM" src="https://user-images.githubusercontent.com/214760/167259669-fa16f613-7a00-4f1f-aa19-0ed1019cf7a3.png">

**Comment by julien51** [comment]
Hey @ccarfi Sorry for the delay here. You are correct that we need to show a message to the user. I will look into that!

**Comment by julien51** [comment]
This has now been fixed. No more silent failure!
