### ISSUE TITLE
Remove @unlock-protocol/types package and move updated type definition to unlock-js

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8787]
**Is your feature request related to a problem? Please describe.**
The unlock types package is outdated. Due to this, we have duplicate types in our apps.

**Describe the solution you'd like**
Remove the package entirely. It is extra maintenance for a single file which overlaps a lot with frequently updated unlockjs. Unlockjs already generates many types so I think it would be good to move the definitions there. 

**Describe alternatives you've considered**
Continue to update the type definitions in the type package but I suspect this won't work in the long term as it hasn't so far. If the package isn't directly providing functionality, it is easy to forget to update it.

Many types are needed by external applications as well and we don't publish the type package.

**Comment by clemsos** [comment]
can we build the package from the unlock-js repo? it is useful to have the unlock types as a package for other things like the hardhat plugin or the contracts package

**Comment by searchableguy** [comment]
You can import types directly from the unlockjs package.

If you `import type {} from "unlockjs"`. Then unlockjs won't be bundled. All the typed will be stripped after compilation.

**Comment by clemsos** [comment]
sounds good !

regarding generating the types from the contract, that should be doable using the ABI - already in unlockjs. However the current versions for the actual contract are untyped in unlockjs, so not sure how useful that will be (at least internally)

**Comment by julien51** [comment]
Maybe we in fact need to keep it but move zod definitions in there, as well as import unlockjs exported types here.

**Comment by searchableguy** [comment]
Created a core package containing zod definition which we can share with other utilities. Closing this.
