### ISSUE TITLE
renewals handling of nonsensical or malicious renewal occurrences

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#8798]
**To Reproduce**
Update the _recurringPayments_ part of the querystring right in the address bar of the browser to specify an odd, irrational, or malicious renewal value.

**Expected behavior**
Such values would not be accepted and would not progress to the checkout phase of the transaction. 

**Screenshots**
half a renewal
<img width="407" alt="Screen Shot 2022-05-11 at 7 18 04 AM" src="https://user-images.githubusercontent.com/214760/167872681-672d26df-a17e-46e7-8d95-df49f02f76b6.png">

-100 renewals ("negative 100 renewals")
<img width="410" alt="Screen Shot 2022-05-11 at 7 19 04 AM" src="https://user-images.githubusercontent.com/214760/167872732-d8d1caa1-47b8-4d7a-a80a-d97f1261d03b.png">

**Comment by clemsos** [comment]
Fractional values are not supported as this is basically X transactions
