### ISSUE TITLE
eslint 5.8->5.10 uncovers a slew of problems

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#880]
**Describe the bug**
While upgrading deps in package.json, I discovered that eslint 5.8 missed a whole bunch of problems that eslint 5.10 catches. This bug tracks that, so that a separate PR to upgrade eslint can be done

**Comment by julien51** [comment]
oh... I found when there are too many changes (noit sure if this is the case here) that it is often easier to submit a first PR which temporarily disables the failing rules and then submitting individual PR for each re-enabled rule (along with the fixes ;p)

**Comment by julien51** [comment]
I this related to that https://github.com/unlock-protocol/unlock/issues/875?

**Comment by julien51** [comment]
Assigning this to me because this is blocking on another PR ;)

**Comment by julien51** [comment]
Ohh, we upgraded to 5.10 ;) 
Closing now!
