### ISSUE TITLE
NFT image on keychain not showing updated image of lock

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#8801]
**Describe the bug**
NFT image on keychain not showing updated image.

**To Reproduce**
Viewing keychain on Rinkeby / Mac / Chrome.

<img width="806" alt="Screen Shot 2022-05-11 at 10 57 52 AM" src="https://user-images.githubusercontent.com/214760/167916010-dc40b5eb-c92e-447a-a119-32e39c4f391b.png">

Here's what the lock looks like:
<img width="397" alt="Screen Shot 2022-05-11 at 11 01 38 AM" src="https://user-images.githubusercontent.com/214760/167916180-14eab2b1-87f7-4eb4-806d-18f6190952d0.png">

**Comment by julien51** [comment]
CAn ypu paste the lock address here + a purchase link please?

**Comment by ccarfi** [comment]
lock address (it's the 10 minute membership one)
0x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3

purchase link:
https://staging-app.unlock-protocol.com/checkout?redirectUri=https%3A%2F%2Fwww.unlock-protocol.com&paywallConfig=%7B%22locks%22%3A%7B%220x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3%22%3A%7B%22network%22%3A4%7D%7D%2C%22pessimistic%22%3Atrue%2C%22persistentCheckout%22%3Atrue%2C%22icon%22%3A%22https%3A%2F%2Fstaging-locksmith.unlock-protocol.com%2Flock%2F0x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3%2Ficon%22%7D

@julien51, you *should* have one of these in your keychain already, i think?

**Comment by julien51** [comment]
ok, confirming it is an issue in the staging vs. production setup. We "save" to the staging DB but the the keychain reads from the prod db.
