### ISSUE TITLE
Renewals not renewing

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#8802]
**Describe the bug**
The "Ten Minute Membership" key expired and never renewed. Initial transaction (should have) set it up for 12 renewals.
<img width="725" alt="Screen Shot 2022-05-11 at 11 04 26 AM" src="https://user-images.githubusercontent.com/214760/167917320-4a490269-0eee-4328-96cf-1cb6cdb3b147.png">

<img width="718" alt="Screen Shot 2022-05-11 at 11 05 31 AM" src="https://user-images.githubusercontent.com/214760/167917334-02cc79c1-dc99-44a8-8fae-916f545621ac.png">

https://rinkeby.etherscan.io/tx/0xae359613f15c88ad6922374f54fbd8639d777b1e8ef37f661f2672fb2876bd8a

**Comment by ccarfi** [comment]
Lock is at https://rinkeby.etherscan.io/address/0x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3

**Comment by julien51** [comment]
It looks like this is fixed now?
