### ISSUE TITLE
"Enable Recurring" flag on lock turned itself off 

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#8804]
**Describe the bug**
Enable Recurring flag on lock on dashboard has previously been enabled. Refreshed page, and flag had turned off.

<img width="1364" alt="Screen Shot 2022-05-11 at 6 50 14 PM" src="https://user-images.githubusercontent.com/214760/167976173-3af2ac1b-cb19-4c78-ac7b-d3dbf39ca417.png">

**Comment by ccarfi** [comment]
This is the same lock we were testing earlier today, which had the flag turned on.

**Comment by ccarfi** [comment]
May be a visual bug...after flipping to another tab in browser and returning, flag was back on with no other action taken.
<img width="1360" alt="Screen Shot 2022-05-11 at 6 54 06 PM" src="https://user-images.githubusercontent.com/214760/167976378-3f822e40-8638-461b-8c4c-e27b49031445.png">

**Comment by julien51** [comment]
Let me look into that.

**Comment by julien51** [comment]
I was not able to reproduce this :(
