### ISSUE TITLE
Unable to repurchase (extend) a renewing key that has expired

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#8812]
**Describe the bug**
Unable to renew / extend a subscription that has successfully run its course. Example: I buy a one year, monthly-recurring membership in Jan 2022. It recurs ever month and then expires at the end of Dec 2022. It expires after 12 recurrences. I now want to extend it for another year of monthly recurring memberships. When trying to purchase the subscription again, I see an error message of "The transaction could not be sent as it appears to fail."

**To Reproduce**
Purchase the "10 minute subscription" at

https://staging-app.unlock-protocol.com/checkout?redirectUri=https://www.example.com&paywallConfig=%7B%22locks%22:%7B%220x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3%22:%7B%22network%22:4,%22recurringPayments%22:3%7D%7D,%22pessimistic%22:true,%22persistentCheckout%22:true,%22icon%22:%22https://staging-locksmith.unlock-protocol.com/lock/0x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3/icon%22%7D

Let it renew three times over the course of 30 minutes.

Try to purchase it again after it expires the third time.

**Expected behavior**
I should be able to extend and "renew" this recurring subscription.

**Screenshots**

Lock address: 0x8E9F8fAb9043a09aF9C35bCB9f9e29e9B0eD1DD3
Keyholder address: 0x26110d6D055292410B9E2Ff566322C072B26d350

<img width="433" alt="Screen Shot 2022-05-13 at 6 30 19 AM" src="https://user-images.githubusercontent.com/214760/168294470-85feea49-53af-4c68-a0cb-751627567b47.png">

<img width="561" alt="Screen Shot 2022-05-13 at 6 29 16 AM" src="https://user-images.githubusercontent.com/214760/168294489-e649fe52-91bd-4696-bff9-381f567a2b9d.png">

No errors in console.
<img width="567" alt="Screen Shot 2022-05-13 at 6 30 14 AM" src="https://user-images.githubusercontent.com/214760/168294669-6d282ef1-85a1-42c6-9507-0cbba6ded3e1.png">

**Comment by julien51** [comment]
Fixed in https://github.com/unlock-protocol/unlock/commit/e4886bfa7b0137cdb3c93fd322a1cec8db71c154
The issue was a type error when the contract throws an error rather than returning 0 when there is no allowance.
