### ISSUE TITLE
Check correct UDT distribution is happening on Gnosis Chain and Polygon, OP, Base and Arbitrum

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8823]
**Describe the bug**
When looking at transactions on Gnosis Chain and Polygon it looks like the number of UDT being distributed is extremely low.
We need to investigate to ensure that we have the correct configuration for these.
I suspect and issue with the oracles?

**Comment by julien51** [comment]
Related https://github.com/unlock-protocol/unlock/issues/13543

**Comment by clemsos** [comment]
For that we need to 

- [ ] check the state of UDT Uniswap Pools 
- [ ] make sure the oracles are deployed and set correctly
- [ ] test on Tenderly forks : send UDT to Unlock, buy a key

**Comment by clemsos** [comment]
For Polygon, the oracle address for UDT needs to be changed to this one https://polygonscan.com/address/0x7157C87fc940dceDEff6902130d1f0C21B1Fdc7b#code

The reason being that the current oracle uses a fee of 500 by default, while the udt pool fee is 3000. The contract above is an oracle that uses pool of fee 3000 to check prices

the function to call is `setOracle(0xf7E78d9C4c74df889A83C8C8d6D05BF70fF75876,0x7157C87fc940dceDEff6902130d1f0C21B1Fdc7b)`
