### ISSUE TITLE
Redeploy to another testnet

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8824]
Rinkeby is going away, we better move to another testnet 

https://twitter.com/peter_szilagyi/status/1526065078604292097?s=21&t=ojQAxM-Exe7y5EVrHU0k6A

**Comment by julien51** [comment]
That's a good point! Want to take a shot at Ropsten and/or Kovan?
We should make sure automate this as much as possible, including the multisig handling so we can use the same setup on more production EVM environments.

**Comment by searchableguy** [comment]
Those are going as well (ropesten and kovan). 

Goerli and sepollia are the only two which should work after the merge.

**Comment by julien51** [comment]
Let's go for Goerli! I think we could also add Mumbai
