### ISSUE TITLE
Convert unlock-asset package to typescript

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#8851]
**Is your feature request related to a problem? Please describe.**
Types are missing from unlock-assets package because we haven't set up svgr to generate ts files instead of js for svg components. 

**Describe the solution you'd like**
Add typescript support by modifying the template and package.

**Comment by julien51** [comment]
Maybe @ m00n620 might be interested :)

**Comment by jordang7** [comment]
Hey, I was playing around with this a little and it seems the SVGR CLI tool has some weird compatibility issues with typescript. I am only able to get the generated components to be typescript files. Couldn't find a solution to convert the actual template file and the rest into typescript.

Let me know if just generating the ts files has some value, or if the whole package needs to be typescript as well.
