### ISSUE TITLE
Remove web3js dependencies

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8856]
Our smart contract code is tested with 2 different framework : ethers (through HardHat) and web3js. Most of the `web3js` tests are for older versions of Unlock which are 1) not used anymore and 2) deprecated.
We should remove the `web3js` dependencies, starting by removing support for old versions of Unlock (only >= 4 are supported right now).
Then, we would need to rewrite remaining tests using hardhat/ethers.

PS: we could consider also deprecating v4 or v5 depending on how many active (has active memberships and sold/minted >1 in the last 6 months)

**Comment by clemsos** [comment]
It seems that this will speed up the test suite 

```
    Using ethers
      ✔ Should return the new greeting once it's changed (74ms)
    Using truffle/web3
      ✔ Should return the new greeting once it's changed (2214ms)
```

**Comment by julien51** [comment]
😮
