### ISSUE TITLE
Verify proxy on Optimism Etherscan

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8953]
It looks like some of our contracts are not verified on Optimism as reported by @ccarfi  https://optimistic.etherscan.io/address/0xd104f6236deac27fd79af6953e044a8f262e713b

@clemsos reported we need to run this:

```
yarn hardhat verify-proxy --public-lock-address 0xb3d245242bb28c456d15c74be0f5eb3518e83918 --proxy-admin-address 0x0141f9b191e531918c08105df714557472b74e51 --network optimism
```

**Comment by clemsos** [comment]
ok done

**Comment by julien51** [comment]
NICE!
