### ISSUE TITLE
run-all-tests bagde does not seem to work!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8955]
All in the title :) 
It looks like it's not really running all of the tests. See this for example https://github.com/unlock-protocol/unlock/pull/8898

**Comment by clemsos** [comment]
the problem with it is that it only works when a new commit is added. It won't work by just adding a tag to the PR (gh-actions had no trigger for that last time I checked) so one need to add the tag then push an empty commit or sth.

one workaround will be to have a `/tests` command like we have `/rebase` that will trigger the tests again, and the tag will likely get picked up

**Comment by julien51** [comment]
Oh that's a neat idea! I like that.

**Comment by clemsos** [comment]
So now the tests got triggered but don’t get reported on the PR itself 

see https://github.com/unlock-protocol/unlock/actions/runs/2578184523
