### ISSUE TITLE
Disable "native" transfers for keys with a manager

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9005]
One of the audits revealed a risk for keys to be "stolen" with the following scenario:
* a malicious user purchases a key on a lock
* the set an address of theirs as the key manager
* they put that key up for sale on a platform like OpenSea
* a victim buys the key from them
* the malicious user recaptures the key they sold.

We can't expect platforms like OpenSea to surface the fact that a key manager is set and that the seller has the ability to re-transfer a token their way. 

In order to mitigate this, we should do the following
* disable the "default" `transfer` and `transferFrom` functions if a key manager is set (and/or reset the keyManager when these are called)
* add a new `lend` function that lets someone change the owner, without changing the manager.

**Comment by clemsos** [comment]
the `transfer` function is actually a call to `shareKey` that will just create a new key with the specified amount of time for the recipient, so this change should only affect `transferFrom`
