### ISSUE TITLE
"flash" on checkout UI loading

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9045]
We noticed a flash on the checkout UI. It is not a breaking issue but fairly annoying and does not provide the smooth experience we are aiming for: let's fix it!

**Comment by searchableguy** [comment]
This happens because we try to auto login the user on loading the first for the first time. This results in normal loading bar which appears when you aren't authenticated.

**Comment by julien51** [comment]
Fixed!

https://github.com/unlock-protocol/unlock/pull/10402
