### ISSUE TITLE
Open camera from verifier screen

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9047]
One feature that could be interesting is being able to open the camera from the verifier screen to scan the "next" ticket.
Do you think that would be doable @kalidiagne ?

**Comment by kalidiagne** [comment]
Nice idea! 
Because we are doing it from web-app and not from a mobile-app, we can't use HTML media capture.
It only allows you to take pictures with your device's camera or select an existing one.
But I think there are some workaround/libs to allow this type of operation also from web page.

**Comment by julien51** [comment]
Let's add a button "Scan another ticket" to the verifier page which opens the camera and lets a user immediately scan another ticket. Ideally, once the QR code has been "read", instead of opening the URL in another tab, the page would extra the query params and load the corresponding ticket info.

**Comment by julien51** [comment]
This has now been merged! Thanks @searchableguy!
