### ISSUE TITLE
Generate QR code and send it by email to the owner of key as part of the email sent to confirm a purchase.

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9053]
As part of the refactoring and simplication of our ticketing use case, we want to be able to send a QR Code by email directly when users are purchasing their NFT ticket.

We already send a confirmation email. We will ADD an attachment to that email which is the QR code itself so people don't even have to come to the keychain to generate their own QR code.

This work then includes the following requirements:
 * Add a library to generate a QR code image from locksmith 
 * Add a function that generates a QR code from a verification URL generated by locksmith using a signature generated by locksmith (using the `signToken` method in `Dispatcher`)
 * When we're sending the confirmation, add the attachment. The wedlock API should already support attachements
 * Additionally, for convenience, we will a new locksmith API endpoint that can only be called a lock manager OR a key owner that will send trigger the email being sent.

**Comment by julien51** [comment]
Let's see why email sending is not working?

**Comment by julien51** [comment]
We need to reconsider this!

**Comment by kalidiagne** [comment]
Send email from members page works!
there is an issue on confirmation email fixed in this PR https://github.com/unlock-protocol/unlock/pull/9287
