### ISSUE TITLE
New Checkout flow - Provide default title when is not present in paywallConfig

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#9193]
in new checkout UI a default title or lock title is not visible in the card when the parameter is not set in paywallConfig

### refs 

Card when `name` parameters is missing

<img width="600" alt="Screenshot 2022-07-06 at 16 57 58" src="https://user-images.githubusercontent.com/20865711/177586032-c70b2279-616f-4dbd-b57d-59c8daa44c96.png">

Card when `name` parameters is present
<img width="600" alt="Screenshot 2022-07-06 at 17 34 16" src="https://user-images.githubusercontent.com/20865711/177588710-f06da10e-82c9-43fb-9ec3-ec943a9fe259.png">

Old version, when `name` is missing from parameters lock name will be visible

<img width="600" alt="Screenshot 2022-07-06 at 16 58 41" src="https://user-images.githubusercontent.com/20865711/177586083-51fbf7ff-9a58-42b9-aa43-548a875630ff.png">

cc: @searchableguy

**Comment by searchableguy** [comment]
That's a bug for lock name.

For the title, it is intended.
