### ISSUE TITLE
Filter by members by email address and checked in time

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9213]
The team at Dappcon indicated that it would be really useful for them to be able to filter by email address, as well as by checked-in time.
I do agree we will need to support these. However, our current approach to these makes it really hard. We will need to do 2 things:
* move the owner email + checked-in time outside of the JSON so we can easily look up by these
* have a way to query locksmith first for the matching owners/token ids, retrieve from the subgraph next and query locksmith again for the rest of the metadata.

Given that this is a significant change, let's work on this a bit later but we need to have that live by August 15th.

**Comment by searchableguy** [comment]
We don't need to move them outside of data field. Simply migrate column to JSONB. We use postgres which supports native indexing on json fields which should work fine for this purpose.

**Comment by julien51** [comment]
Interesting! Let's talk more about this and the steps involved!

**Comment by julien51** [comment]
@searchableguy Please work on the migration so we can work on the actual feature after that!

**Comment by julien51** [comment]
I think we can close this. Please confirm @kalidiagne

**Comment by kalidiagne** [comment]
Closing, new filter endpoint was merged!
