### ISSUE TITLE
What happens if the same account is using Unlock on muliple devices

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9246]
We are considering using Unlock accounts for the verifiers.
What happens if multiple devices use the same Unlock account?

**Comment by kalidiagne** [comment]
Tested with 2 different browsers with the same account.
Working fine for both, I see that the access token in the same and scanning works.

@searchableguy do you think we can have any problem in the described scenario?

**Comment by searchableguy** [comment]
I don't think we should have any problem with that. We should be generating different access/refresh tokens for each user on login.

**Comment by julien51** [comment]
Ok this is great news. I can close that one!
