### ISSUE TITLE
Maintain compatibility with old lock versions

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#9266]
**Describe the bug**
Current checkout isn't well tested and may have edge or bugs which appear on locks older than v10 due to previous lock not supporting multiple memberships. 

We should test on previous locks and make fixes for backward compatibility.

**Comment by julien51** [comment]
I think it would be good to have a script to identity the list of locks (+versions) that have sold at least one membership in a given time frame for all networks. This should use the subgraph.
I think it is safe to remove support (at least one the checkout... but probably at the UnlockJS level) for anything that has not sold a membership in 1 year. wdyt?

**Comment by julien51** [comment]
>  We could show an error - you need to upgrade lock in the checkout if we find it's not compatible and ask user to upgrade.

Absolutely. I expect we will add an explicit way to upgrade on the new dashboard.

**Comment by searchableguy** [comment]
The issue can be closed because we already test with v9 (our own lock for members). For below, we don't have any active locks so testing with them is not useful.
