### ISSUE TITLE
Easier credit card autocomplete

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9289]
Our new checkout should support semantic markup to make credit card autocomplete work!
Example 
https://codepen.io/yuriyromadin/pen/KXGPyO

**Comment by searchableguy** [comment]
We don't control this. It is part of stripe UI library.

https://github.com/stripe/stripe-js/issues/150

**Comment by julien51** [comment]
Dang. It's frustrating because it makes adding a card really painful on mobile :/

**Comment by searchableguy** [comment]
I think their payment element supports it so I will see if it will work there when we add more payment options

**Comment by searchableguy** [comment]
I think auto complete works with the new payment element so this should be resolved.
