### ISSUE TITLE
Using https://gnosisscan.io/

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9449]
It looks like we now have a https://gnosisscan.io/ for Gnosis chain!
Let's see the status and if we can use it instead of blockscout!

**Comment by clemsos** [comment]
That will require to verify contracts there again. Also the hardhat verify command does not support this explorer but we can add it as a custom network (like celo).

Note that will be good as part of the renaming away from xdai #9461

**Comment by julien51** [comment]
We have now verified the most recent contracts on GnosisSwap, so we can move forward with this!

**Comment by clemsos** [comment]
we are using gnosisscan as default verifier for gnosis now

**Comment by clemsos** [comment]
one last missing thing here will be to verify past / older version of the contracts on Gnosis Scan. If not, I think we can close

**Comment by clemsos** [comment]
ok transparent proxy used by unlock v11 has been verified (using solc 0.8.7 and oz contract 4.4.2 (see https://github.com/unlock-protocol/unlock/issues/9461#issuecomment-1323892771 )

**Comment by clemsos** [comment]
remains 
- [ ] previous versions of public lock and unlock 
- [ ] hooks

**Comment by clemsos** [comment]
ok, verified these hooks

- https://gnosisscan.io/address/0xd10DF26AEaE179521D6195Cf6f3b2701B5089Fb6
- https://gnosisscan.io/address/0x4F44e968961f5ff818b788E626564BBAF2c96bAC

**Comment by julien51** [comment]
Thanks @clemsos!

Do you think it would be a big pain to verify these older versions as well? like 9, 10 and 11?

**Comment by julien51** [comment]
https://gnosisscan.io/address/0x19f11E9D43260411b29e538c489426e73e365B4a/transactions#code

**Comment by julien51** [comment]
We're actually using Gnosisscan!
