### ISSUE TITLE
Check if key can be granted

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9451]
Our UI to airdrop keys does not check if a key can effectively be granted.
We should do that and show an error message to the user when it cannot.
To check if a key can be granted, we need to retrieve the "max key per address" setting on the lock, and see if a given addresss already has one (or more) keys.

**Comment by kalidiagne** [comment]
Solved by https://github.com/unlock-protocol/unlock/pull/9527

**Comment by kalidiagne** [comment]
Solved by https://github.com/unlock-protocol/unlock/pull/9527
