### ISSUE TITLE
Confirmed Locks not showing on the Dashboard from Goerli

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/unlock#9453]
**Describe the bug**
A user created a Lock from the Dashboard UI on the Goerli testnet and even after confirmation, it wasn't showing.

Transactions for reference:
https://goerli.etherscan.io/tx/0xf6ea38a044643c967f38c92b4ac04844327fa89dc5555b359b431e680778befc
https://goerli.etherscan.io/tx/0xf0f97457cf7f139478f18df0dba9b951c39bb3b1a05b22070f0fc2c7a9b42961

**To Reproduce**
I was not able to reproduce it on my account even using the exact same configuration she did and insured the browser version she was using was up to date. 

**Expected behavior**
After confirmation the Locks should show up on the list, they never did. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18197239/184962825-aeae37c5-bfaa-4d2f-b248-b814f4e097a3.png)
![image](https://user-images.githubusercontent.com/18197239/184962937-4796787f-3d4c-4500-823e-07ef8a1933ea.png)
![image](https://user-images.githubusercontent.com/18197239/184962978-84f44bf6-c893-41bf-9706-5f4ba0daf69b.png)
![image](https://user-images.githubusercontent.com/18197239/184963011-b098d79e-e7f0-42ca-a8e1-b719007ddfdb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome 104.0.5112.81 (Official Build) (64-bit)

**Additional context**
For any other questions please contact NuclearGeek.eth#9119 on Discord. Additionally, this user was able to successfully create and view Locks on other networks. Disconnecting and reconnecting the wallet did not solve the problem.

**Comment by julien51** [comment]
This is really strange. I can find both locks on the block explorer:
* https://goerli.etherscan.io/address/0xc45175d8c33a0a58d7d7a6b454320e630459beee#readProxyContract
* https://goerli.etherscan.io/address/0xeff98be19de02711ddda6a6b3ae7d5d6de6bbe8e#code

**Comment by julien51** [comment]
Thanks for the clarification @searchableguy.
I think this is one more reason to work on the provider proxy.... I am on it.
