### ISSUE TITLE
Use Local Memory Type Variable Instead of Global Storage Type Variable in Event to Save Gas

### ISSUE THREAD

**Issue by Ether1oop** [unlock-protocol/unlock#9458]
Hi, we recently have conducted a systematic study about Solidity event usage, evolution, and impact, and we are attempting to build a tool to improve the practice of Solidity event use based on our findings. We have tried our prototype tool on some of the most popular GitHub Solidity repositories, and for your repository, we find a potential optimization of gas consumption arisen from event use.  

The point is that when we use emit operation to store the value of a certain variable, local memory type variable would be preferable to global storage type (state) variable if they hold the same value. The reason is that an extra SLOAD operation would be needed to access the variable if it is storage type, and the SLOAD operation costs 800 gas.

For your repository, we find that the following event use can be improved:

- [PublicLockV4.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/PublicLock/PublicLockV4.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

```Solidity
    function initialize(address sender) public initializer {
        _owner = sender;
        emit OwnershipTransferred(address(0), _owner);
    }
```
&emsp;&emsp;**function name:**&emsp;*updateKeyPrice*
&emsp;&emsp;**event name:**&emsp;&emsp;*PriceChanged*
&emsp;&emsp;**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*
```Solidity
  function updateKeyPrice(
    uint _keyPrice
  )
    external
    onlyOwner
    onlyIfAlive
  {
    uint oldKeyPrice = keyPrice;
    keyPrice = _keyPrice;
    emit PriceChanged(oldKeyPrice, keyPrice);
  }
```

- [PublicLockV0.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/PublicLock/PublicLockV0.sol)
**function name:**&emsp;*updateKeyPrice*
**event name:**&emsp;&emsp;*PriceChanged*
**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

```Solidity
  function updateKeyPrice(
    uint _keyPrice
  )
    external
    onlyOwner
  {
    uint oldKeyPrice = keyPrice;
    keyPrice = _keyPrice;
    emit PriceChanged(oldKeyPrice, keyPrice);
  }
```

- [PublicLockV7.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/PublicLock/PublicLockV7.sol)
**function name:**&emsp;*updateKeyPricing*
**event name:**&emsp;&emsp;*PricingChanged*
**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

```Solidity
  function updateKeyPricing(
    uint _keyPrice,
    address _tokenAddress
  )
    external
    onlyLockManager
    onlyIfAlive
  {
    uint oldKeyPrice = keyPrice;
    address oldTokenAddress = tokenAddress;
    require(
      _tokenAddress == address(0) || IERC20(_tokenAddress).totalSupply() > 0,
      'INVALID_TOKEN'
    );
    keyPrice = _keyPrice;
    tokenAddress = _tokenAddress;
    emit PricingChanged(oldKeyPrice, keyPrice, oldTokenAddress, tokenAddress);
  }
```

- [PublicLockV8.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/PublicLock/PublicLockV8.sol)
**function name:**&emsp;*updateKeyPricing*
**event name:**&emsp;&emsp;*PricingChanged*
**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [PublicLockV3.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/PublicLock/PublicLockV3.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

&emsp;&emsp;**function name:**&emsp;*updateKeyPrice*
&emsp;&emsp;**event name:**&emsp;&emsp;*PriceChanged*
&emsp;&emsp;**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [PublicLockV6.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/PublicLock/PublicLockV6.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

&emsp;&emsp;**function name:**&emsp;*updateKeyPricing*
&emsp;&emsp;**event name:**&emsp;&emsp;*PricingChanged*
&emsp;&emsp;**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [PublicLockV1.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/PublicLock/PublicLockV1.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

&emsp;&emsp;**function name:**&emsp;*updateKeyPrice*
&emsp;&emsp;**event name:**&emsp;&emsp;*PriceChanged*
&emsp;&emsp;**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [UnlockV0.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV0.sol)
**function name:**&emsp;*updateKeyPrice*
**event name:**&emsp;&emsp;*PriceChanged*
**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [UnlockV6.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV6.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

- [UnlockV4.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV4.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

&emsp;&emsp;**function name:**&emsp;*updateKeyPrice*
&emsp;&emsp;**event name:**&emsp;&emsp;*PriceChanged*
&emsp;&emsp;**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [UnlockV1.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV1.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

&emsp;&emsp;**function name:**&emsp;*updateKeyPrice*
&emsp;&emsp;**event name:**&emsp;&emsp;*PriceChanged*
&emsp;&emsp;**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [UnlockV3.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV3.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

&emsp;&emsp;**function name:**&emsp;*updateKeyPrice*
&emsp;&emsp;**event name:**&emsp;&emsp;*PriceChanged*
&emsp;&emsp;**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

- [UnlockV9.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV9.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

- [UnlockV7.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV7.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

- [UnlockV8.sol](https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/UnlockV8.sol)
**function name:**&emsp;*initialize*
**event name:**&emsp;&emsp;*OwnershipTransferred*
**variable:**&emsp;&emsp;&emsp;&emsp;*_owner->sender*

- [MixinLockCore.sol](https://github.com/unlock-protocol/unlock/blob/master/smart-contracts/contracts/mixins/MixinLockCore.sol)
**function name:**&emsp;*updateKeyPricing*
**event name:**&emsp;&emsp;*PricingChanged*
**variable:**&emsp;&emsp;&emsp;&emsp;*keyPrice->_keyPrice*

Do you find our results useful? Your reply and invaluable suggestions would be greatly appreciated, and are vital for improving our tool. Thanks a lot for your time!

**Comment by clemsos** [comment]
closed as mentioned changes only concerns past contract versions. Also not very clear what changes exactly are proposed
