### ISSUE TITLE
Consider removing `smart-contracts\test\Unlock\Unlock.js.` to save time when running tests.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#946]
From a comment by @hardlydifficult :

"To save on test run time, you could consider removing smart-contracts\test\Unlock\Unlock.js. That file demonstrates direct access to the Unlock contract vs going through a proxy. If you are moving forward with the proxy solution - there should be no benefit in maintaining both tests. smart-contracts\test\Unlock\UnlockProxy.js includes all the same tests running through a proxy."

**Comment by julien51** [comment]
Please triple check that indeed these tests are duped...

**Comment by nfurfaro** [comment]
> Please triple check that indeed these tests are duped...

Absolutely.
