### ISSUE TITLE
Rename xdai to gnosis chain in code

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#9461]
Even tough we are now showing it as Gnosis Chain (#8950) to the user, we still use xdai under the hood in all dev-related tasks. Will be good to replace it across the board

**Comment by julien51** [comment]
We also need to verify v12? https://gnosisscan.io/address/0xf673F1BC3e5AB6a425b8b6235Ab93a15C37299EF#code

**Comment by clemsos** [comment]
started in  #10346
