### ISSUE TITLE
When doing a filtered search, reset pagination

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9465]
When the user does a search, we should not take the page number into account, otherwise we will show "no result" when there are results.
See this https://share.getcloudapp.com/lludjDgP

**Comment by kalidiagne** [comment]
fix with: [9213-restore-pagination](https://github.com/unlock-protocol/unlock/pull/9488)

**Comment by kalidiagne** [comment]
fixed with https://github.com/unlock-protocol/unlock/pull/9488
