### ISSUE TITLE
Treat `email` differently

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9472]
Of all the user metadata collected, email is treated differently: it is used to send an email to the owner of an NFT.
Let's treat it differently (ie. not through `metadataInputs`) by doing the following:
* in the paywallConfig, let's add a `collectEmail`: `boolean` field. 
* If set to to true, the checkout flow will include the metadata collection UI with the email field (+ any another field id `metadataInputs` is present)

**Comment by searchableguy** [comment]
Added
