### ISSUE TITLE
CSV import on airdrop UI

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9473]
Our airdrop UI supports airdropping to multiple recipients + saving emails.

We need to add support for CSV imports on that UI. For that, we will limit the size of the CSV file to 100 rows (this should be within the block limit!). The CSV file must have the following characteristics:
* first row: name of the fields
* first column: address (or ENS)
* second column: email
* any other column will be saved as "text" in the private metadata field for each address.

**Comment by julien51** [comment]
@kalidiagne This is not high priority. Let's aim for end of September.

**Comment by searchableguy** [comment]
https://github.com/unlock-protocol/unlock/pull/9688
