### ISSUE TITLE
Decode logs on block explorers

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#9490]
Currently the event logs are not decoded by the various block explorers, but that's quite useful to get the address of a new lock from the tx 

- https://arbiscan.io/tx/0x0abf2c7475c0aab76c5e5a3e0e3a2991c505324fcf660cad1726e0febdd33b3e#eventlog
- https://snowtrace.io/tx/0x5d79c32cd5bb0c0e199beb2fc2af2c37c5126d34f69edc28f21cb44d544d899b#eventlog

Is there a straightforward way to reference events to the block explorer so it get decoded properly?

If possible, will be good to add to our pipeline when deploying to a new chain.

**Comment by clemsos** [comment]
We need to make sure the signatures are on https://www.4byte.directory as its used on Tally to decide DAO calls - and it currently shows exceptions there https://www.tally.xyz/gov/unlock/proposal/67650238492744053870551188976528991701570154819711289520259087104693406921512?chart=list

**Comment by julien51** [comment]
It looks like this is not something we control... so closing!
