### ISSUE TITLE
Chore Automation

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9511]
We need to automate more some of our chores.

## Publishing packages to npm. 

We now have multiple packages (`contracts`, `networks`, `unlock-js`, ... and soon a lot more: `unlock-express`, `unlock-react`... etc). We need to automate their publishing.

The flow should be fairly straightforward:
* when the code in a package is updated, we need to update the `package.json` file's `version` number 
* once merged in `production`, a new Github action should check if the version of the `package.json` is different from the published one. If it is, publish it using some dedicated npm credentials which can be rotated. 
Related: https://github.com/unlock-protocol/unlock/issues/6091

## Docs 

We have docs in multiple places:
* smart contracts
* unlock-js
* locksmith

We need a similar flow to the one above where a new Github action runs the script that automates the docs generation and opens pull-requests against the docs repo. Having pull requests will allow @wonderwomancodes to review then drafts and merge if everything is good!

## Production deploys

WE have a script for production deploys that is supposed to run on Tuesdays every week... for some reason it currently does not run.

**Comment by julien51** [comment]
We should also include deploying subgraphs: https://github.com/unlock-protocol/unlock/issues/9637

**Comment by clemsos** [comment]
This issue is quite broad, and we have #9270 #8055
