### ISSUE TITLE
Report slow tests!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9512]
In an effort to improve our codebase, we want to identify friction and pain points!
Please report here any slow tests or issues running them!

**Comment by clemsos** [comment]
shoudl look into this https://observablehq.com/d/6f4dded6f845ec8f

**Comment by clemsos** [comment]
that failure happens often https://github.com/unlock-protocol/unlock/actions/runs/3592943038/jobs/6049267527

any idea what this is @searchableguy ? seems like jest picking up build folders ?

**Comment by searchableguy** [comment]
@clemsos it's memory leak. No idea why it happens sometimes and sometimes not though.

**Comment by julien51** [comment]
Thanks for reporting @clemsos ! Hopefuly moving to Vitest will help!

**Comment by julien51** [comment]
closing as stale. Please open new issues when you find a slow test.
