### ISSUE TITLE
Keeping track of Oracles

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9518]
Let's add the oracle contract addresses used on the Unlock contracts to the networks package.
Let's also deploy any missing oracle for the networks that we support.

**Comment by clemsos** [comment]
Just deployed an oracle on Goerli : [0x5b45aC05B06A19E790A07e3613e807F1EeE5bA53](https://goerli.etherscan.io/address/0x5b45aC05B06A19E790A07e3613e807F1EeE5bA53#writeContract) using @HardlyDifficult lib. I also managed to verify it eventually

This won't be so easy for Optimism as there are no Uniswap V2 here (only v3). One approach will be to write a wrapper contract that keeps the same Oracle API but uses Uniswap v3 to make actual requests
