### ISSUE TITLE
Show lock manager status somewhere

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#9523]
**Describe the bug**
We treat lock managers differently in multiple pages where we also allow user to access them such as keys page for a lock. We only show protected metadata for lock managers so users are confused when they don't see it if they connected a different wallet. 

We should show an indicator that user is not lock manager and they should switch their wallet to see everything.

**Comment by julien51** [comment]
Agreed! That's a good idea for the "Manage Lock" page.

**Comment by kalidiagne** [comment]
This can be close? 
We added this warning for `non-lock manager` ref: https://github.com/unlock-protocol/unlock/pull/9847#issuecomment-1268680334 

@julien51

**Comment by julien51** [comment]
yes!
