### ISSUE TITLE
Subgraph versioning

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#9524]
As we are rewriting the subgraph entirely and will maintain both version for some time, we need a coherent approach to version them.

Easiest will be to just add a '-v2' suffix after the existing graph name. 

Just wondering if we want to add more advanced versioning somewhere as the graph may keep evolving.

**Comment by julien51** [comment]
> Easiest will be to just add a '-v2' suffix after the existing graph name.

I think that's correct. let's use `unlock-<network>-v2` for each?

My goal would be for this new subgraph to stick around MUCH longer as it is more robust.
