### ISSUE TITLE
Link to block explorer on lock

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9575]
We currently only show the link to the block explorer pretty late in the checkout process (confirmation screen). Let's add a small link from the first screen,

**Comment by searchableguy** [comment]
would be nice to get an answer to above here @julien51

**Comment by julien51** [comment]
Sorry for the delay here! I still think it's useful to show it _before_ users make a choice or before they connected their wallets.
We can remove it from later screens though

**Comment by searchableguy** [comment]
https://github.com/unlock-protocol/unlock/pull/9707
