### ISSUE TITLE
Creating locks from Dashboard is not work on Mumbai

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/unlock#9599]
**Describe the bug**

**To Reproduce**
1. https://app.unlock-protocol.com/dashboard
2. Select Mumbai Network
3. Create Lock
4. Submit

**Expected behavior**
Lock is created
<img width="1189" alt="Screen Shot 2022-09-13 at 7 28 20 AM" src="https://user-images.githubusercontent.com/18197239/189929318-2f88d2da-fcb2-428a-a44c-b6fcfaea61ce.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 104

**Additional context**
No feedback on the page but the console is showing a network error, see screenshot

**Comment by julien51** [comment]
It looks like the rpc provider we use for Mumbai isn't working right now :(

**Comment by searchableguy** [comment]
This has been resolved. Julien changed the network and I tested it again. It should be working now.
