### ISSUE TITLE
Refactor lockMiddleware to separate web3Service listening from actions on it

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#962]
As evidenced by #888, it is difficult to respond to web3Service events outside of the lockMiddleware currently. There are 2 possible solutions to this, one is to combine middlewares (put new code inside lockMiddleware). The other is what I recommend, splitting out the listening from web3Service and the code that reacts to it.

This would be accomplished by having a middleware whose purpose is to listen to web3Service events and to emit redux actions.

Then, we can add middlewares downstream that respond to these actions by emitting new actions. The upstream middleware would listen for these and convert them into web3Service calls. This will allow us to more easily trace how bugs occur and also to add new functionality without touching existing code.

**Comment by cellog** [comment]
That's exactly what this issue proposes, I spoke to Akeem about that. I could do the refactoring part since it's redux stuff, if you'd like, @akeem @julien51, and then this PR could be updated to use that

**Comment by julien51** [comment]
Closing as done.
