### ISSUE TITLE
Deploy subgraph automatically from ci

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#9637]
Will be useful. See an example here https://github.com/graphprotocol/graph-network-subgraph/blob/master/.github/workflows/deploy-production-subgraph.yaml

**Comment by julien51** [comment]
That would be.... perfect!

**Comment by clemsos** [comment]
one step closer with the subgraph deployment script

**Comment by julien51** [comment]
This would have been useful today! :D

**Comment by julien51** [comment]
From Discord: 
cd subgraph && yarn deploy-all
need to add to ci somewhere
so it deploys on each prod pr:
```
cd subgraph && yarn deploy-all
```

**Comment by clemsos** [comment]
a fix is in the works at #10350

**Comment by julien51** [comment]
I can confirm this works! Closing!

**Comment by clemsos** [comment]
It seems that the graph deployment from CI is failing silently, as exemplified in https://github.com/unlock-protocol/unlock/actions/runs/10095179618/job/27914692424

**Comment by julien51** [comment]
Annoying! Let's debug this!

**Comment by clemsos** [comment]
Also on a sidenote, the subgraph CLI fails with exit code 0 which does not help  https://github.com/graphprotocol/graph-tooling/issues/1570
