### ISSUE TITLE
off-by-one somewhere in key counts

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#9663]
top of dashboard says this

<img width="200" alt="Screen Shot 2022-09-22 at 3 42 47 PM" src="https://user-images.githubusercontent.com/214760/191864747-18839f3b-81e1-4402-bee5-5a964e6c9255.png">

last key is one number less, both on screen and in exports. is there a tokenID of 0 somewhere? or is this an off-by-one somewhere?

<img width="1322" alt="Screen Shot 2022-09-22 at 3 42 38 PM" src="https://user-images.githubusercontent.com/214760/191864842-960d5903-0ebf-447c-bd6f-e76b263cbc2e.png">

**Comment by kalidiagne** [comment]
Checked and is not an issue on UI, the total value is now get directly from the lock.
i can only reproduce with `Unlock Members` contract, there is always +1 in the total value 

for some reason we have a `total members > key sold` 🤔 

@julien51 any suggestions ? 
<img width="530" alt="Screenshot 2022-10-11 at 18 04 21" src="https://user-images.githubusercontent.com/20865711/195142922-e7032668-701b-414c-bcf0-27971033b7bd.png">

**Comment by julien51** [comment]
@kalidiagne That's a good question!
Where are both numbers coming from?

**Comment by kalidiagne** [comment]
> @kalidiagne That's a good question!
> Where are both numbers coming from?

Both from *getLock*

**Comment by julien51** [comment]
ok. Thanks. I'll investigate further.
