### ISSUE TITLE
Updating the system email templates

### ISSUE THREAD

**Issue by ChialiTsai** [unlock-protocol/unlock#9679]
To update the system email with better readability and support images.

Here is a template to try out for confirming your email, https://github.com/unlock-protocol/unlock/blob/master/wedlocks/src/templates/confirmEmail.js

Will supply the rest of HTML template once this one is confirmed without any render issue.

[ConfirmEmail-template.zip](https://github.com/unlock-protocol/unlock/files/9648884/ConfirmEmail-template.zip)

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/9708
