### ISSUE TITLE
We should run our smart-contract tests once on rinkeby before deploying to mainnet.

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#969]
This is recommended by truffle:
>"Both Ganache and Truffle Develop are significantly faster than other clients when running automated tests. Moreover, they contain special features which Truffle takes advantage of to speed up test runtime by almost 90%. As a general workflow, we recommend you use Ganache or Truffle Develop during normal development and testing, and then run your tests once against go-ethereum or another official Ethereum client when you're gearing up to deploy to live or production networks."

https://truffleframework.com/docs/truffle/testing/testing-your-contracts

**Comment by nfurfaro** [comment]
Not at all.

**Comment by nfurfaro** [comment]
I'm looking into this now. When we run `truffle test` now, truffle will run our migration scripts  ( on network 'test') and then use snapshotting to ensure our tests do **Not** share state with each other.
`2_deploy_unlock.js` on network 'test' will deploy Unlock directly, with no proxy.
We can also pass `truffle test` an alternate network, such as `truffle test --network rinkeby`.
As per the truffle docs, 
>"When running against other Ethereum clients like go-ethereum, Truffle will re-deploy all of your migrations at the beginning of every test file to ensure you have a fresh set of contracts to test against."

This means we need to be explicit in our migrations scripts about what actions Truffle should take when `network === rinkeby`. I think the cleanest and clearest way to do this would be with a switch statement. for example:
```
deployer.then(() => {
    switch (network) {
      case 'test':
        break
      case 'development':
        if (
          shell.exec(
            // reset?
            `zos push --network development --from ${proxyAdmin}`
          ).code !== 0 || shell.exec(
            `zos update Unlock --init initialize --args ${unlockOwner} --network ${network} --from ${proxyAdmin}`
          ).code !== 0
        ) {
          throw new Error('Migration failed')
        }
        break
      case 'rinkeby':
        console.log("you're on rinkeby")
        // do something here
        break
      case 'mainnet':
        console.log("you're on mainnet")
        // do something here
    }
  })
```

**Comment by nfurfaro** [comment]
There is one issue that may be trickier to deal with... 
When we run `truffle test`, the Unlock contract is deployed by the truffle deployer:
`if (network === 'test') {
      return deployer.deploy(Unlock, unlockOwner)
    }`
We can then access the contract in our tests:
```
contract('Lock', (accounts) => {
  before(() => {
    return Unlock.deployed()
      .then(_unlock => {
        unlock = _unlock
```
But, in some of our tests we use zos instead (which I think we should be doing consistently via a zos helper PR. I will create an Issue for this). 
On rinkeby, I don't know that we want to be creating a bunch of different proxyies on a test by test basis (but I need feedback on this)? Or, if we do, then it would make sense to just deploy Unlock directly in our migrations, and let our tests handle the proxy creation. This would mean we would not be testing our deployed rinkeby proxy & contract, but creating new ones just for testing purposes...

cc @julien51

**Comment by julien51** [comment]
Thanks Nick for your work on this.
I am not sure I like the idea of tweaking the deployer with a switch statement.
The more I think about it, the more I think it is not required to run the unit tests on the deployed lock as is.

I think we should have another acceptance test suite which would be independent from our unit tests (and would not try to deploy the contract) but would test the "core" functionnalities as a black box? This test suite would not know anything about how the contract was deployed etc. 

What do you think?

**Comment by nfurfaro** [comment]
Thanks for the feedback, Julien. This reinforces my feeling about not needing to run the existing test suite against the deployed contract.
On your points:
• tweaking the deployer - I'm not ok with tweaking the deployer, but am totally ok with adding network-based conditionality to the migrations scripts. Truffle docs have good examples of this: https://truffleframework.com/docs/truffle/getting-started/running-migrations#network-considerations
(Of course, we're doing this already; I just thought a switch statement would be cleaner if we add 2 more networks).
Also, given that we're using truffle as a framework, it makes sense to me to make the most of what it offers, and migrations are a pretty powerful tool to have at our disposal, keeping track of our deployment logic and history making it repeatable, and enforcing that the steps can only be run once, in the correct order. Being explicit about what will happen when `truffle migrate` is run on each network we care about is pretty sweet if we're going to be using `truffle migrate/deploy` at all. But this is more an issue of how you want future automated deployments to be structured, and whether that involves using truffle for the task or not.

• independent acceptance test suite - I really like this idea. In the end, I think it will likely be simpler and more effective than attempting to make the current suite do too many things (and making it harder to reason about in the process).

**Comment by julien51** [comment]
Ok, let's open an issue for an acceptance suite and I am closing this one ;)

**Comment by julien51** [comment]
Done https://github.com/unlock-protocol/unlock/issues/1176
