### ISSUE TITLE
Missing items in subgraph V2

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#9711]
The following needs to be added to the subgraph v2

Lock 

- [ ] totalKeys : total number of minted keys
- [ ] maxNumberOfKeys - NB: we dont have update event

**Comment by julien51** [comment]
Did you write a tutorial on how to update the graph so that I (or someone else) can do it easily?

**Comment by clemsos** [comment]
yes #9722

**Comment by clemsos** [comment]
this is a bit too generic, also the mentioned items are in the subgraph so closing
