### ISSUE TITLE
Better handling of mobile when connecting wallet

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9716]
Our checkout UI (but also the dashboard) offer the ability to connect a wallet as part of the process.
We should handle the "injected wallet" flow better because I worry this brings confusion to users, especially because we assume it _is_ MetaMask when it could be another wallet.

Here is the flow I recommend, based on Desktop or mobile.

1. Desktop
 a. If there is an injected wallet, try to find its flavor and show a relevant icon (Brave as `isBraveWallet` and MM has `isMetaMask` for example). 
     i. If an wallet can be "guessed", show the correct icon... 
     ii. if not, show the MetaMask one
 b. if no injected wallet exists, show a greyed "generic" wallet icon that, when clicked opens a simple modal that has a simple text like "Wallets give access to your funds and Ethereum applications. Only you should have access to your wallet." and then links to https://ethereum.org/en/wallets/find-wallet/
2. Mobile
  a. if there is an injected wallet (rare!), try to find its flavor and show the relevant icon (same as desktop)
  b. if no injected wallet exists, open the WalletConnect UI, which should handle the wallet discovery flow.

What do you think @searchableguy ?

**Comment by searchableguy** [comment]
I think that looks good. We can do it.
