### ISSUE TITLE
lag or lost emails from unlock accounts

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#9731]
created three unlock accounts about one hour ago through the demo page at
https://app.unlock-protocol.com/demo?network=100&lock=0xCEaAb271f2089D9ECd1763AbcA1E4Fe9c680BFb5

created all three with emails using plus addressing (e.g. ccarfi+somerandomstring@gmail.com).

ISSUE: have not received any emails confirming the unlock account creation

with third account, i had it send a key. i think this is the transaction
https://blockscout.com/xdai/mainnet/address/0xe240Eefd2506d6924C615A5a80bDF0b5825C56C8/tokens/0xceaab271f2089d9ecd1763abca1e4fe9c680bfb5/token-transfers#address-tabs

also did not receive any email noting that i'd received a key.

**Comment by julien51** [comment]
It looks like Sendgrid is holding on to our emails. I emailed support to clarify what is going on :(

**Comment by ccarfi** [comment]
fwiw, i HAD received a transactional email about 30min before that.

<img width="747" alt="Screen Shot 2022-10-01 at 10 10 59 AM" src="https://user-images.githubusercontent.com/214760/193420553-470d5061-77db-47a9-825d-34608ada9bd4.png">

**Comment by julien51** [comment]
This now fully resolved...
