### ISSUE TITLE
Multiple error conditions should be displayable at once in the Error component

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#977]
After it is possible to store multiple errors in the redux store, it should be possible to display them in the Error component on the frontend. @julien51 @smombartz it would be useful to have a sense of what this should look like before proceeding

**Comment by smombartz** [comment]
how this?
![image](https://user-images.githubusercontent.com/1377389/50996155-2a3eaa80-14ef-11e9-9b41-0d7547274f47.png)

mock: https://www.figma.com/file/gmhVq6Pqeu2gH7e3FC2lr0ax/Unlock-App?node-id=0%3A2

**Comment by cellog** [comment]
looks good, I just implemented it, screenshot in the PR
