### ISSUE TITLE
Lock settings page

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#9795]
This is a common request in the discord and will be useful to us as well:

> Allow people to change max number of keys per recipient on the manage lock page. #9795

**Comment by kalidiagne** [comment]
> I think there are a bunch of small functionalities we could indeed, like that:
> 
>     * change name
> 
>     * add lock manager
> 
>     * revoke lock manager
> 
> 
> I'll prepare a more complete list!

Waiting for the list! 
What about adding a section accessible with a tab with all the actions? To solve also the actual problem of too many button in the manage lock page

**Comment by julien51** [comment]
We should also support the following:

* gasRefund setting (used for recurring)
* Setting referrerFee

**Comment by julien51** [comment]
> What about adding a section accessible with a tab with all the actions? To solve also the actual problem of too many button in the manage lock page

Let me chat with @ChialiTsai about the best way to support all these.

**Comment by julien51** [comment]
We also need to consider how we want to link to the verifier's page (or specific applications based on the "type" of usage for the lock: events, subscriptions...)

**Comment by julien51** [comment]
We also need to show the version of the lock and support upgrading a lock

**Comment by julien51** [comment]
We should also make it easy to plug hooks such as  bring your own NFT, password, captcha... etc

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/issues/9204

**Comment by julien51** [comment]
Making keys non-transferable should be doable via UI too!

**Comment by julien51** [comment]
Alright, I just renamed this to "Lock settings page" as this issue will be part of us introducing a new "settings" page for the the locks. @ChialiTsai has worked on the design.

The goal here is to offer a UI for lock managers to change settings on their lock, including things like enabling credit cards... etc.
