### ISSUE TITLE
Paywall Subscription Status Flag Expanded Metadata

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#981]
**Solution**
A user can expand the Paywall [Subscription Status Flag](https://github.com/unlock-protocol/unlock/issues/980) to show metadata (like duration, price, ...)

**Design**
![image](https://user-images.githubusercontent.com/1377389/50996947-5f4bfc80-14f1-11e9-842a-c855d6bf5bc6.png)

Mock: https://www.figma.com/file/LkWSSnCGlKEITBB5T5NYXW/Paywall?node-id=5%3A141

**Comment by julien51** [comment]
Pushing this to v0+.

**Comment by cnasc** [comment]
As of #1402 we're in position to finish this up. I'll take a look at it once the wallet check overlay is done.
