### ISSUE TITLE
Tickets QR codes

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9850]
Our QR codes are fairly basic for now!
We need to implement a better "ticket" UI that does include the QR code but also a lot of information!

![image](https://user-images.githubusercontent.com/17735/194121906-44825ab4-416e-4a71-ab4e-b866bd5fe490.png)

Since the QR codes are generated both on the front-end and the backend and to avoid replicating this, we should create an API endpoint that, given the signature and the signed details will generate a PDF. This API will be used on the front-end from the keychain so it can be sent by email... as well as a from the websub worker directly.

The ticket should be in the PDF format and should include the following:
- the NFT image
- the lock name
- the token id
- the owner address

Once we have more specific metadata for events we will add them to the tickets (location, date... etc)

**Comment by searchableguy** [comment]
Any reason to switch to PDF from PNG currently for QRcode?

PDF file won't be shown by default in gmail and other clients unlike PNGs. They also cannot be displayed on the frontend without pulling in dependencies so we will need to the actual UI or PNG.

**Comment by julien51** [comment]
We don't expect to show the PDF on the front-end. It can be downloaded from there though...
And we will send it as an attachment by email.
