### ISSUE TITLE
Allow recurring "forever"

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9867]
In our current checkout config, the number of recurring purchases is "fixed":

> `recurringPayments`: The number of time a membership should be renewed automatically.

We should enable "forever". In that context, the membership will stop only if the user stops it explicitly and/or they run out of funds. 

When the membership is forever, the ERC20 approval should be MAX_UINT and the UI should say “Pay every X days until canceled”.

**Comment by searchableguy** [comment]
Before enabling this option, I think we should have an option to cancel the subscription from keychain.

**Comment by julien51** [comment]
Well we do! If you cancel (trashcan icon) it will cancel the subscription =)
