### ISSUE TITLE
Missing "returns" in ABI

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9877]
Some of our functions are missing the `returns` statement in their interface even though we do actually return something :D
Example: 
`function publicLockVersions(address _impl) external view` should in fact be
`function publicLockVersions(address _impl) external view returns(uint16)`.

Let's fix them all if we can!

**Comment by sebastiantf** [comment]
https://github.com/unlock-protocol/unlock/blob/master/packages/contracts/src/contracts/Unlock/IUnlockV11.sol#L183-L187

`publicLockVersions`,  `publicLockImpls` in `IUnlockV11` doesn't have return types
