### ISSUE TITLE
Improve UI feedback on bulk airdrop

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#9904]
**Describe the bug**

Bulk Airdrop does not provide individual feedback for entries which were discarded right now. It only tells the number of entries. 

Many users have complained about lack of specific entries since they have to look out for them manually. 

We should show invalid entries with reason next to it to ease this.

**Comment by julien51** [comment]
Another issue that came twice already: some application export CSV with `;` instead of `,`... can we support both?

**Comment by julien51** [comment]
Related https://github.com/unlock-protocol/unlock/issues/10002
