### ISSUE TITLE
JSX is still put into redux store, which is an anti-pattern

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#991]
**Describe the bug**
#985 does not fix the underlying problem of putting JSX into the redux store, it just adds a level on indirection.

Pre-985:
```js
setError(<p>message</p>)
```

Post-995
```js
error ={
 MISSING_PROVIDER: <p>message</p>
}

this.emit(new Error(MISSING_PROVIDER))

setError(error.message)
```

which translates into:

```js
setError(<p>message</p>)
```

We cannot store jsx in the redux store, it makes serializing the store impossible, and breaks time travel debugging.

The correct solution is to store only the metadata used to generate error jsx in the store, and then to generate the error message in the React components. This is the approach that #982 took, and the reason that it took that approach.  Let's talk on Monday and hash this out.

**Comment by julien51** [comment]
Huh I cannot reproduce? In master, so post 995, the variable `MISSING_PROVIDER` is coming from `errors.js`:
```
export const MISSING_PROVIDER = 'MISSING_PROVIDER'
```

So this is not JSX? Could you tell me more?

**Comment by julien51** [comment]
[this is not affecting users in any way... so changed to p3]

**Comment by cellog** [comment]
This was an end-of-day misreading of source code, closing as invalid
