### ISSUE TITLE
Show lock balances on list

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9920]
2 different teams said it was cool to see the balance of the lock on the list... and save clicks!
Let's see if we can add it back!

**Comment by kalidiagne** [comment]
> 2 different teams said it was cool to see the balance of the lock on the list... and saved clicks! Let's see if we can add it back!

What is `saved click`? where we store that info?

**Comment by julien51** [comment]
> What is saved click 🤔

Ha It should save "save click" (there was a typo). It saves clicks for lock managers as they don't have to click though anymore to know the balances :D
