### ISSUE TITLE
Update the default lock images for v13

### ISSUE THREAD

**Issue by ChialiT** [unlock-protocol/unlock#9972]
To give the community a fresh look from v12, I'd like to propose the new default lock images.
This is composed by 4 layers, all svg format.

- BG - as the based layer, serves as background, 5 variants
- Layer-bottom - as decoration, 44 variants
- Layer-top - as decoration on top of the section, 44 variants
- Logo - as very top of the layer

the provided svg is 400 x 400 px.
[locks-img-v12.zip](https://github.com/unlock-protocol/unlock/files/9814487/locks-img-v12.zip)

some samples:
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/16527634/196527036-ef4be8d5-2fab-4d2d-949a-9311732b8dcf.png">

**Comment by julien51** [comment]
I'll work on this! Also, any way to use a black & white version on expired ones?

**Comment by ChialiTsai** [comment]
> I'll work on this! Also, any way to use a black & white version on expired ones?

i think so, probably it should be set of grey shades.
how can I help? should I create the same set but with the grey shades or?
or we just simply "tinted" the generated version to grey?

**Comment by julien51** [comment]
I think we can just use tint, that'll be better.

**Comment by julien51** [comment]
Unfortunately we missed the v12 window. Let's aim for v13 but we need to implement this logic first!
