### ISSUE TITLE
max recipient error message is wrong

### ISSUE THREAD

**Issue by kalidiagne** [unlock-protocol/unlock#9999]
trying to put `6` into a lock that's have `maxRecipients: 5` give this error message 

`You cannot purchase more than 1 memberships at once` instead of `You cannot purchase more than 5 memberships at once`

<img width="1137" alt="Screenshot 2022-10-21 at 13 31 51" src="https://user-images.githubusercontent.com/20865711/197186557-dd711132-a2cf-4079-85f5-d3cdd8554810.png">

https://staging-app.unlock-protocol.com/alpha/checkout?redirectUri=&paywallConfig=%7B%22locks%22%3A%7B%220x0155f60f075de9ec5ead8117b6946de48fa96b47%22%3A%7B%22network%22%3A5%2C%22name%22%3A%22%22%2C%22recurringPayments%22%3A%22%22%2C%22captcha%22%3Afalse%2C%22password%22%3Afalse%2C%22emailRequired%22%3Afalse%2C%22minRecipients%22%3A%221%22%2C%22maxRecipients%22%3A%225%22%2C%22superfluid%22%3Afalse%2C%22default%22%3Afalse%2C%22dataBuilder%22%3A%22%22%7D%7D%2C%22metadataInputs%22%3A%5B%7B%22name%22%3A%22test%22%2C%22type%22%3A%22text%22%2C%22required%22%3Afalse%7D%5D%7D

**Comment by julien51** [comment]
Good catch @kalidiagne !
